### ISSUE TITLE
collecting proposed changes to v2 disk & memory representations

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1001]
Important repo format considerations:
- [ ] "Old name" lookups should be fast, Like O(1)
- [ ] LCA lookup should be fast (faster than O(_history_))
- [ ] Merges should be fast (essentially: identifying and materializing the LCA)
- [ ] Dependency lookups (namespaces, definitions) should be O(_dependencies_)
  * _i.e._, index them separately, compactly
- [ ] Codebases should be small (comparable to text-based git repo)
  * We should make significant use of sharing / deltas, specifically for older versions of things.
    * This should be straightforward for namespaces, tbd for definitions.
    * Some shared representation for similar sets of attached metadata?
  * Causal spines are amenable to a packed, fixed-width format, with Cons strings laid out in a sequence, and only jumping for merges.
    * We should look for a clever way to do LCA in this format, although the format is more suited to DFS than BFS (which I'm assuming our LCA uses).  Actually: just load each cons string into memory, and put them onto the BFS queue.  Whenever a merge node is encountered, each of its parents' cons strings belong on the queue at this level. 🏆 
  * We might design a scheme for retaining only critical subsets of history
    * Maybe user-tagged versions + shared versions (relevant for LCA calculations)
    * Maybe some exponentially drop-off schedule for retaining recent changes
      * How much local history does IntelliJ keep?
- [ ] We know we want to change the "patch" format.  Can we do that without changing the repo format?
  * Include a version number field in the patch object?
  * Make patch objects Unison terms?
    * Would we still merge patches on `merge` in this case?
    * Does the merge thing mean we shouldn't make patch objects Unison terms (yet)?
- [ ] We know we watch to change the definition representation at some point (e.g. #1061). Is there something we can do now to ease that transition later?
  * Include a version number in the term object?
  * Maybe we just do a minor repo format update in this case and it's fine?
- [ ] Can we inherit the old reflog, refer to old hashes?

Questions:
- Can we get great performance without writing a lot of custom code? e.g. can we take advantage of sqlite?  
  * For implementing certain indexes?
- How do we upgrade a reflog, or published urls, if v2 hash values are different?
  * Maintain indexed mapping from old hashes to new hashes?

Performing a repo format upgrade at runtime:
1. On startup, look in .unison directory for `v<N>` directories. 
2. If none exists, or more than one exists, or one exists > current version, explain and quit.
3. If `v<N>` = current version, then done.
4. Else (`v<N>` is older version), call `v<N>To<Current>` upgrade procedure, copying `v<N>` elements to `v<Current>`.
5. Delete `v<N>`.
* After a failed lookup of a hash of unknown version, check old>new hash index for a match and retry.

**Comment by aryairani** [comment]
If we're not using git for merging anymore, is it valuable to use a git-mergeable codebase structure anymore?  What additional cost in terms of git transaction time does it impose to have ~4500 files in `unisonweb/base` instead of 1?

**Comment by aryairani** [comment]
I think that currently when we serialize a branch, we write a `Branch.Raw` file and name it after the hash of the `Causal`.  I was thinking it might be nice if we could come up with a way separate the namespace from the Causal history, allowing more sharing on disk.

For example, a git commit consists of a _tree_ hash, a list of _parent_ hashes, author, committer, message, date, I think, along with a hash of those seven fields (the commit hash).  Point being that the _tree_ is stored separately and can be shared among commits.  

Though maybe there is no equivalent for Unison, because while git's history only forks in one dimension, our Causal forks in two dimensions, meaning `children` link to advancing Causals, not reusable trees.

**Comment by pchiusano** [comment]
@aryairani - the branch file could have a pointer to a "level" file file, which is content-addressed directory, keyed by the hash of the contents of terms and types at that level. The children still have to be stored in the branch file, since they are pointers to a full Causal.

**Comment by anovstrup** [comment]
#1061 is related — maybe under "general design review on the data structure for metadata"?

**Comment by aryairani** [comment]
Distinguish decl reference.ids from term reference.ids so that you can find them without checking two directories?  The situation I'm in currently is that I looked up transitive dependencies from the disk, and want to copy them to a new codebase, but have to check in two places.

**Comment by aryairani** [comment]
> For next repoformat we should make dependencies available without deserializing the term
> Like store the term structure, with a separate array of the dependencies

**Comment by pchiusano** [comment]
Idea: store the structure of terms and types separately from their dependencies. So for each hash, keep structure.ub and dependencies.ub, where structure just has integer indices for references, integers refer to positions in dependencies, which is just an array of references.

**Comment by aryairani** [comment]
> @aryairani - the branch file could have a pointer to a "level" file file, which is content-addressed directory, keyed by the hash of the contents of terms and types at that level. The children still have to be stored in the branch file, since they are pointers to a full Causal.

I guess if we are switching "off by one", then the "level" would just be a maybe term, maybe type, maybe patch; probably maybe not worth it.  Otherwise yeah I guess it would be the namesegments maps, which maybe would be worth it.

**Comment by aryairani** [comment]
> Idea: store the structure of terms and types separately from their dependencies. So for each hash, keep structure.ub and dependencies.ub, where structure just has integer indices for references, integers refer to positions in dependencies, which is just an array of references.

Is the reason not to keep a copy of the dependencies in `structure.ub`/`compiled.ub` just for space?  Could just keep the terms as-is (minus variable names, or whatever we end up doing) and a separate copy of dependencies; instead of two files and reassembling them later.

**Comment by aryairani** [comment]
> Distinguish decl reference.ids from term reference.ids so that you can find them without checking two directories? The situation I'm in currently is that I looked up transitive dependencies from the disk, and want to copy them to a new codebase, but have to check in two places.
> 
> We could just add an extra byte before the sha hash.

Or at least use something like `data X = Term Id | Type Id` for the range of the "dependents" and future "dependencies" indices.

**Comment by pchiusano** [comment]
Ed Kmett has LCA calculation in log h time, where h is length of history. It wasn’t obvious to me that his approach can be applied to DAGs as well, but it can be: https://twitter.com/pchiusano/status/1257509428460470273 

However... I don’t think that choice of just making the merge result a child of the LCA is going to yield good results if there’s repeated merging: it’s effectively discarding the history on both branches after the LCA

I’m still hoping for a logarithmic time LCA that yields the same results as the breadth first algo.

**Comment by pchiusano** [comment]
Idea: make sure the file formats are "framed", so it's easy to read information from them selectively without a full decoding. For instance, lists can be length encoded, but with the total number of bytes up front, so the entire list can be skipped.

Idea: Content address All The Things, for maximal sharing and minimal storage. For instance, rather than storing a `Set Reference` directly inside a namespace file, store the hash of that `Set Reference`, and then when reconstituting the namespace, obtain the value by looking it up a directory of hash-named files. You can make this as granular as your want - even the `Set Reference` could be further decomposed. This leads to a lot of small files if done naively, but perhaps the content-addressed directories are represented as zip files.

**Comment by aryairani** [comment]
Archiving original ticket contents, since they are all boring / obvious / obsolete now

----
## Naming stuff
* Don't have `#` in any directory or file names as it is not url-friendly or search engine friendly. (#1133)
  - also not `bash`-friendly, as `#` starts a line comment
  - recommend moving to the more conservative https://superuser.com/a/358861 `[0-9,a-z,A-Z,-._]`
  - simplify `encodeFileName`/`decodeFileName` <details><summary>for example</summary>

    My thinking is that 

    `$forward-slash$private$forward-slash$var$forward-slash$folders$forward-slash$gb$forward-slash$tmp$forward-slash$T$forward-slash$git-pull-53f7f0894006b1e6$forward-slash$repo.git` 

    is an even greater departure / harder to read than

    `$fs$private$fs$var$fs$folders$fs$gb$fs$tmp$fs$T$fs$git-pull-8de7dab557c9eb8d$fs$repo.git`

    although obviously neither is great.

    ![image](https://user-images.githubusercontent.com/538571/79608214-93ce4100-80c2-11ea-9179-cc4318047a99.png)</details>


## Don't serialize Branch.Raw with Star, as they are redundant:
- Drop the `(namespace, reference, metadata type)` index, as there is a separate `(namespace, reference, metadata type, metadata reference)` index.
-  Don't need to repeat the `Reference` in each Relation; can use a `Map Reference Int` and write them out as `varints` 

## Reconsider Star
- May be able to drop `fact` field, you can use `lookupDom d1`; unless you're meant to be allowed to link metadata in places with no associated name. #1060
  - And if you want to do that, you can use `lookupDom d1 <> lookupDom d2 <> lookupDom d3`

## Let's do a general design review on the data structure for metadata.

## General design review of nested namespaces
- Do we maybe want different kinds of nesting: nesting of term names vs nesting of project scopes?

**Comment by aryairani** [comment]
> Ed Kmett has LCA calculation in log h time, where h is length of history. It wasn’t obvious to me that his approach can be applied to DAGs as well, but it can be: https://twitter.com/pchiusano/status/1257509428460470273
> 
> However... I don’t think that choice of just making the merge result a child of the LCA is going to yield good results if there’s repeated merging: it’s effectively discarding the history on both branches after the LCA
> 
> I’m still hoping for a logarithmic time LCA that yields the same results as the breadth first algo.

@pchiusano Wait, why would it have to make the merge result a child of the LCA, when you have the two query nodes right there?  Disclaimer: I didn't immediately understand or try to fully read the papers linked in the Twitter thread.

**Comment by ceedubs** [comment]
I think that this is outdated, since we have been settled on a SQLite codebase format for a while now. I'm going to close this out, but feel free to open more targeted issues for any lingering items.
