### ISSUE TITLE
Add ucm command to preview adds/updates 

### ISSUE THREAD

**Issue by anovstrup** [unisonweb/unison#1028]
I find myself touching my scratch file at times just to get ucm to echo the output that it produces when a scratch file is saved. It would be nice if there were a ucm command that would produce this output on demand, without having to save/touch a scratch file. (It can be useful when the output from other intervening ucm commands has "hidden" the output produced after the most recent save or the codebase/namespace has changed in ways that alter the interpretation of the current scratch code.)

This [was discussed](https://unisonlanguage.slack.com/archives/CLKV43YE4/p1575669593027300) briefly on the Slack channel, and some possible command names were thrown around: `load`, `status`, `preview`/`add.preview`/`update.preview`.

**Comment by aryairani** [comment]
Hi @anovstrup @pchiusano, let's decide exactly what this would do

Option 1. Preserve and re-display the typechecking results from last time (shows you "hidden" output again)

Option 2: re-parse/typecheck the previously typechecked file (takes into account namespace changes)

**Comment by anovstrup** [comment]
I'd prefer Option 2, as that was part of my motivation for this suggestion in the first place. We could potentially avoid reparsing/type-checking when it really isn't necessary, but that's an implementation detail that should be invisible to the user, IMO.  I want to know what's going to happen to my codebase if I `add` or `update` _now_ (even if that's changed since the last time I touched/saved my scratch file).

**Comment by aryairani** [comment]
Just to clarify: as things currently stand, I believe that if you save your scratch file and ucm typechecks and prints the status, then you change the namespace, and then you `add`/`update`, the changed namespace doesn't affect the outcome of the `add`/`update`.  Does this change anything for you?

**Comment by anovstrup** [comment]
Well, it would change my mental model. 😂

**Comment by anovstrup** [comment]
But, actually, I don't think that's correct. Consider:

In scratch.u:
```
add1 x = x + 1
```

In ucm:
```
add
cd childns
```

In scratch.u:
```
add2 x = (add1 . add1) x
```
(ucm reports errors, because it can't resolve `add1`)

In ucm, `cd..` (notionally) then `add`.

(ucm successfully adds `add2`)

**Comment by anovstrup** [comment]
And, for what it's worth, this behavior is exactly what I would expect—that `add` or `update` applies my changes to the _current_ state of the codebase/namespace, regardless of the state it was in when I saved/touched the last scratch file.

**Comment by pchiusano** [comment]
Not sure on the name, I think I like `load` which can take an optional scratch file argument, defaulting to the latest file otherwise. It has the exact same effect as if you touched the file (and maybe is even implemented that way) - everything gets reparsed and typechecked. I think this is the most useful behavior. Like you've just done some munging of the namespace such that the source in the scratch file will parse differently, and now you want to trigger a reload of it.

**Comment by anovstrup** [comment]
I suggested `preview` because I was thinking of the loading behavior as an implementation detail. Maybe it's not loading anything at all—if the scratch files haven't changed since they were last processed, ucm could potentially have everything it needs for `preview`, `add`, and `update` already in memory. 

My _intent_ is not to load a particular file, it's to find out whether my scratch code parses/typechecks in the current namespace/codebase state and what the effects of `add` and/or `update` will be.

On the other hand, I'd avoid _too_ much bike-shedding on this because ucm command names may [become about as important as term/type names](https://github.com/unisonweb/unison/issues/922#issuecomment-564240776) (which is not to say completely unimportant, but the canonical names will be significantly less important when users can customize them at will).

**Comment by aryairani** [comment]
> But, actually, I don't think that's correct. Consider:

What I mean is:

In u.u:
```unison
foo = 1 + 1
```
In ucm
```ucm
  I found and typechecked these definitions in ~/unison/u.u. If you do an `add` or `update`, here's
  how your codebase would change:
  
    ⍟ These new definitions are ok to `add`:
    
      foo : base.Nat
   
  Now evaluating any watch expressions (lines starting with `>`)... Ctrl+C cancels.

.> add

  ⍟ I've added these definitions:
  
    foo : base.Nat
```

In u.u:
```unison
bar = foo
```

In ucm:
```ucm
.> 

  I found and typechecked these definitions in ~/unison/u.u. If you do an `add` or `update`, here's
  how your codebase would change:
  
    ⍟ These new definitions are ok to `add`:
    
      bar : base.Nat
   
  Now evaluating any watch expressions (lines starting with `>`)... Ctrl+C cancels.

.> delete.term foo
.> cd cat

  ☝️  The namespace .cat is empty.

.cat> add

  ⍟ I've added these definitions:
  
    bar : .base.Nat

.cat> view bar

  bar : .base.Nat
  bar =
    use .base.Nat *
    .foo#okihqtpuur * 3

.cat>
```

The current behavior of `add` is to add whatever it typechecked when the file was saved last.  Any intervening changes to the namespace is ignored.

**Comment by aryairani** [comment]
Maybe a `reload` or `reparse` command would be appropriate.

**Comment by anovstrup** [comment]
> The current behavior of add is to add whatever it typechecked when the file was saved last. Any intervening changes to the namespace is ignored.

So `add` behaves as if intervening changes to the namespace/codebase are _significant_ if parsing/typechecking failed after the most recent change, but _insignificant_ if parsing/typechecking passed?  That seems like it could end up causing confusion.  

My mental model, at least, was that the scratch code is always interpreted in the context of the _current_ state of the namespace/codebase, until the point when its added to codebase (at which time its interpretation becomes fixed). I'm curious what others' intuitions are on this.
