### ISSUE TITLE
discuss swapping out Star for Relation4 in Branch0.terms/types

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1060]
`Relation4 r n t v` is a fully indexed version of `Set (r, n, t, v)`, whereas `Star3 r n t (t,v)` is a bidirectionally indexed version of `(Set (r,n), Set (r, t), Set (r, (t, v)))`.

This would allow us to associate metadata with individual names rather than only at the enclosing namespace: e.g:
> _#r_ has name _n_ with metadata (t,v)
> _#r has name _n2_ with metadata (t,v2)

The `Star3` version denotes:
> _#r_ has name _n_
> _#r_ has name _n2_
> _#r_ has metadata of type t
> _#r_ has metadata (t, v)
> _#r_ has metadata (t, v2)

This doesn't have to affect the serialization format initially; we can convert during serialization; but we wouldn't have to use both within `Branch.hs`.

P.S. This is independent of the "one-off" branch concern. In the alternate one-off formulation, a `n` is implied and only `Relation3 r t v` is needed.

**Comment by aryairani** [comment]
There is certainly at least a mismatch between the one-off and Star3; and things are going to be somewhat broken until it's resolved.  What we can do in the mean time is to pretend that 
```haskell
(r,n,t,v) forall r <- facts, n <- d1(r), (t,v) <- d3(r)
```

**Comment by aryairani** [comment]
#1001

**Comment by mitchellwrosen** [comment]
Metadata has been mostly removed in #4574 , so `Star3` would ideally become `Relation` now, not `Relation4`. Tracked in #4429
