### ISSUE TITLE
BranchUtil.get{Term,Type}MetadataAt ignore the input NameSegment

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1062]
I think we ultimately want to be able to associate different metadata to different names (#1060), but in the mean time, we suppose we don't want to return metadata when requesting a name that doesn't exist. 

They are currently called when handling `AliasTermI`, `AliasTypeI`, `doSlurpUpdates`, and `getLinks`.  We should think through each case and see if the caller can be simplified as well.

It could be that `get{Term,Type}MetadataAt` should take a `Maybe r`, to avoid an having to do a filter + fold in some cases?

### On the other hand

The functions _do_ take a Ref, so it may be that we don't ever construct such invalid queries.

**Comment by aryairani** [comment]
#1001

**Comment by mitchellwrosen** [comment]
fixed in #4574
