### ISSUE TITLE
`delete` suggestion

### ISSUE THREAD

**Issue by mitchellwrosen** [unisonweb/unison#1070]
# Current behavior:

- If the name is unambiguous, delete it.
- If the name is ambiguous, complain that you need to be more specific.
  - But if the command is issued a second time, it's like sudo/-f, just do it

# Proposed behavior:

Just delete all terms/types with the given name, even if there are many.

# Why now?

Recent patches improve the story here: delete shows a diff (#1068) and prettified diff is more accurate/informative (#1069).

**Comment by aryairani** [comment]
SGTM
