### ISSUE TITLE
Deleted tests leave something in a namespace

### ISSUE THREAD

**Issue by mitchellwrosen** [unisonweb/unison#1085]
Unison:
```
test> foo.x = []
```
Ucm:
```
.> add
.> delete foo.x
.> ls
  
  ...
  4. foo/              (0 definitions)

```

**Comment by aryairani** [comment]
`foo` is supposed to get deleted too, once if it's empty.
`Branch.stepAt0M` calls `Branch.setChildBranch`, which calls `Branch.updateChildren`, which calls `Map.delete` on a newly-emptied child.  Need to determine why this isn't enough.

**Comment by mitchellwrosen** [comment]
Some info: the branch does end up empty but its hash is not equivalent to `Branch.empty`'s hash.

**Comment by mitchellwrosen** [comment]
Hm, oh, my ticket description is wrong. It doesn't need to be a test... just deleting the last term in a namespace leaves it empty.

I think that makes the problem clear: we don't want to call `isEmpty`, because of course the hash is different than `Branch.empty`... it has a history.

Should be something like `if branchDoesntHaveAnyStuffInIt then delete else don't` instead?

**Comment by aryairani** [comment]
Yeah good catch.  I meant to use `isEmpty0 . head`, not `isEmpty`.

**Comment by aryairani** [comment]
@mitchellwrosen fyi we reverted this patch in #1337; undecided on whether it should be at least hidden.

I kind of think it should be; most hierarchical package viewers omit empty packages. /cc @pchiusano
