### ISSUE TITLE
Non-history-aware merge and/or ability to forget history of a namespace

### ISSUE THREAD

**Issue by mitchellwrosen** [unisonweb/unison#1086]
Idea from @pchiusano in Slack.

Context: if I try to
```
.> pull git@github.com:runarorama/unisonlibraries.git .lib
.> merge .lib .base
```

I get a bunch of deletes. Presumably somewhere in `.lib`'s history, `.base` was deleted and then born anew. But I, an end user, just want the new stuff!

**Comment by aryairani** [comment]
Maybe a wildcard / recursive copy?

**Comment by aryairani** [comment]
@mitchellwrosen Very different usage, but #1236 in conjunction with `find` might do the trick?

**Comment by pchiusano** [comment]
Yeah I think #1236 does the trick for me for this.
