### ISSUE TITLE
UCM renders escape characters verbatim

### ISSUE THREAD

**Issue by BenFradet** [unisonweb/unison#1093]
escape characters seem to be rendered verbatim:

```
t : Text
t = "multi\nline\r"

> t
```

gives back:

```
    5 | > t
          ⧩
          "multi\nline\r"
```

**Comment by aryairani** [comment]
I’m guessing they are being stored verbatim, instead of converted.

**Comment by pchiusano** [comment]
This is correct behavior - the string is decoded when read and encoded again when it is printed, same as Haskell. The rendering of watch expressions is supposed to be valid source code.

You can verify by inspecting the individual characters or by printing the string to console using the IO functions.

**Comment by BenFradet** [comment]
makes sense :+1:

**Comment by aryairani** [comment]
Great.
