### ISSUE TITLE
link command that accepts 1 or more source definitions

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1127]
Currently, `link` command just takes one source definition, and one target, so `link thing .licenses.MIT`. Instead, let's make it work for any number of source definitions:

```
.mylib> find
.mylib> link 1-148 .authors.pchiusano
.mylib> link 1-148 .licenses.MIT
.mylib> link def1 def2 .authors.runarorama
```

It has the same effect as running `link` on each definition in the namespace. Primary use case is probably exactly this - assigning authorship and license info in bulk. We'll want to do this for base and others will want to do this for preexisting Unison packages they've written.

Separate issues:

* base library should be licensed MIT and can get an author of myself, Runar, and Arya. As new definitions get added to base they'll be authored by whoever writes them!
* we might want to have a config setting for default author and license used for new definitions

**Comment by runarorama** [comment]
This changes the type of the repository history. Is that a problem?

**Comment by aryairani** [comment]
> This changes the type of the repository history. Is that a problem?

Changes what how?

**Comment by runarorama** [comment]
@aryairani Never mind, that was a misunderstanding.
