### ISSUE TITLE
Add Windows compliant ctrl+c handling

### ISSUE THREAD

**Issue by matthewess** [unisonweb/unison#1131]
#912 added Unix compliant ctrl c handling in ucm. Discussion there called for a followup to add Windows compatibility. See [ghci](https://gitlab.haskell.org/ghc/ghc/blob/581cbc28e143a4ed8e7f794ed1618161222a5646/libraries/ghci/GHCi/Signals.hs#L35-L46) for an example.

**Comment by aryairani** [comment]
and https://github.com/ghc/ghc/blob/master/libraries/base/GHC/ConsoleHandler.hs
