### ISSUE TITLE
`push` is incomplete in transcript runner (but ok in interactive ucm)

### ISSUE THREAD

**Issue by anovstrup** [unisonweb/unison#1136]
Observed in release M1g. To reproduce:

1. Create a fresh git repo (on GitHub, or in a local directory). 
2. Download [ucm-push-not-working.txt](https://github.com/unisonweb/unison/files/4048550/ucm-push-not-working.txt). 
3. Rename it `ucm-push-not-working.md`. (GitHub does't allow .md files to be posted in issues, but the transcript runner won't run .txt files.) 🤷‍♂️ 
4. Change the GitHub url in the transcript to point to your fresh repo.
5. Run the transcript with `ucm transcript ucm-push-not-working.md`.

For me, this resulted in [this commit being pushed](https://github.com/anovstrup/ucm-push-not-working/commit/7fdb94cc712e051a35688525af59eeeecc1d8562).

**Comment by aryairani** [comment]
You can always post transcript files (and transcript output files!) in a Gist at gist.github.com

**Comment by anovstrup** [comment]
Here's the command line output when I run the transcript:
```
  Transcript will be run on a new, empty codebase.

  ⚠️

  Initializing a new codebase in:
  /Users/anovstrup/Projects/unison/fpis-unison/transcript-222b152de2e192fc

   _____     _
  |  |  |___|_|___ ___ ___
  |  |  |   | |_ -| . |   |
  |_____|_|_|_|___|___|_|_|

  Running the provided transcript file...


⚙️   Processing stanza 4 of 4.⚙  git clone 'https://github.com/anovstrup/ucm-push-not-working' /Users/anovstrup/.cache/unisonlanguage/gitfiles/gp210hat6ko3r5u7h8kj98sll4ql69f56atrgognc9ig8qpol1nuj98s056gf1u96jqmb4feknefm12du1rpda3hlcdej51f1gcgnso/HEAD
Cloning into '/Users/anovstrup/.cache/unisonlanguage/gitfiles/gp210hat6ko3r5u7h8kj98sll4ql69f56atrgognc9ig8qpol1nuj98s056gf1u96jqmb4feknefm12du1rpda3hlcdej51f1gcgnso/HEAD'...
warning: You appear to have cloned an empty repository.
⚙  git -C /Users/anovstrup/.cache/unisonlanguage/gitfiles/gp210hat6ko3r5u7h8kj98sll4ql69f56atrgognc9ig8qpol1nuj98s056gf1u96jqmb4feknefm12du1rpda3hlcdej51f1gcgnso/HEAD rev-parse --git-dir
.git
⚙  git clone 'https://github.com/anovstrup/ucm-push-not-working' /Users/anovstrup/.cache/unisonlanguage/gitfiles/gp210hat6ko3r5u7h8kj98sll4ql69f56atrgognc9ig8qpol1nuj98s056gf1u96jqmb4feknefm12du1rpda3hlcdej51f1gcgnso/HEAD
Cloning into '/Users/anovstrup/.cache/unisonlanguage/gitfiles/gp210hat6ko3r5u7h8kj98sll4ql69f56atrgognc9ig8qpol1nuj98s056gf1u96jqmb4feknefm12du1rpda3hlcdej51f1gcgnso/HEAD'...
warning: You appear to have cloned an empty repository.
⚙  git -C /Users/anovstrup/.cache/unisonlanguage/gitfiles/gp210hat6ko3r5u7h8kj98sll4ql69f56atrgognc9ig8qpol1nuj98s056gf1u96jqmb4feknefm12du1rpda3hlcdej51f1gcgnso/HEAD rev-parse --git-dir
.git
⚙  git -C /Users/anovstrup/.cache/unisonlanguage/gitfiles/gp210hat6ko3r5u7h8kj98sll4ql69f56atrgognc9ig8qpol1nuj98s056gf1u96jqmb4feknefm12du1rpda3hlcdej51f1gcgnso/HEAD add --all .
⚙  git -C /Users/anovstrup/.cache/unisonlanguage/gitfiles/gp210hat6ko3r5u7h8kj98sll4ql69f56atrgognc9ig8qpol1nuj98s056gf1u96jqmb4feknefm12du1rpda3hlcdej51f1gcgnso/HEAD commit -m 'Sync branch 7asfbtqmoj56pq7b053v2jc1spgb8g5j4cg1tj97ausi3scveqa50ktv4b2ofoclnkqmnl18vnt5d83jrh85qd43nnrsh6qetbksb70'
[master (root-commit) 7fdb94c] Sync branch 7asfbtqmoj56pq7b053v2jc1spgb8g5j4cg1tj97ausi3scveqa50ktv4b2ofoclnkqmnl18vnt5d83jrh85qd43nnrsh6qetbksb70
 2 files changed, 1 insertion(+)
 create mode 100644 .unison/v1/paths/7asfbtqmoj56pq7b053v2jc1spgb8g5j4cg1tj97ausi3scveqa50ktv4b2ofoclnkqmnl18vnt5d83jrh85qd43nnrsh6qetbksb70.ub
 create mode 100644 .unison/v1/paths/_head/7asfbtqmoj56pq7b053v2jc1spgb8g5j4cg1tj97ausi3scveqa50ktv4b2ofoclnkqmnl18vnt5d83jrh85qd43nnrsh6qetbksb70
⚙  git -C /Users/anovstrup/.cache/unisonlanguage/gitfiles/gp210hat6ko3r5u7h8kj98sll4ql69f56atrgognc9ig8qpol1nuj98s056gf1u96jqmb4feknefm12du1rpda3hlcdej51f1gcgnso/HEAD push --all 'https://github.com/anovstrup/ucm-push-not-working'
Counting objects: 8, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (8/8), 684 bytes | 0 bytes/s, done.
Total 8 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), done.
To https://github.com/anovstrup/ucm-push-not-working
 * [new branch]      master -> master

💾  Wrote /Users/anovstrup/Projects/unison/fpis-unison/ucm-push-not-working.output.md

  🌸

  I've finished running the transcript(s) in this codebase:

    /Users/anovstrup/Projects/unison/fpis-unison/transcript-222b152de2e192fc

  You can run
  `ucm -codebase /Users/anovstrup/Projects/unison/fpis-unison/transcript-222b152de2e192fc` to do
  more work with it.
```

And here's the output markdown file: https://gist.github.com/anovstrup/90561482449c11aca1885ca6a14d55e4

**Comment by anovstrup** [comment]
The warnings about an empty repo are probably relevant?

**Comment by aryairani** [comment]
Well, the bad news is that my first attempt worked fine:

https://gist.github.com/aryairani/90ca3c4b47ef9e50d9e432eefc864cf1

**Comment by anovstrup** [comment]
Weird. Wonder if it's relevant that you're using a file url? I'll try that.

**Comment by aryairani** [comment]
Bad news, my second attempt (on github) also worked fine:

https://gist.github.com/aryairani/b0f5bb4762a613ce2cfd23302f55123a

**Comment by aryairani** [comment]
Here is the resulting repo: https://github.com/aryairani/repo-1136

**Comment by aryairani** [comment]
I used the default repo creation settings, although it's supposed to not matter:
<img width="422" alt="image" src="https://user-images.githubusercontent.com/538571/72193552-0d75d500-33d8-11ea-9b0a-69a2585d2b4a.png">

**Comment by anovstrup** [comment]
Bad news indeed. :(

**Comment by anovstrup** [comment]
Meanwhile on my end, using a file url with a bare git repo has the same (broken) results...

**Comment by aryairani** [comment]
Any chance you are on an older version?  I'm using the M1g binary release from 2019-11-26

**Comment by anovstrup** [comment]
Did you run the transcript itself or just the same commands/steps? I don't have the "ucm codebase init" stuff in my output.

**Comment by anovstrup** [comment]
oh, I'll check that.

**Comment by anovstrup** [comment]
No, it just tells me that "1.0.M1g already installed".

**Comment by aryairani** [comment]
That's so weird.  Are you on macOS or Linux?

**Comment by anovstrup** [comment]
mac

**Comment by anovstrup** [comment]
Okay, progress! It seems to have worked correctly when I used `ucm -codebase codebase init` first.  Can you try running the transcript directly? I suspect that will allow you to reproduce the issue.

**Comment by anovstrup** [comment]
When I first encountered the issue, it was with the codebase in my home directory (`~`) and running `ucm` from within a different work directory.

**Comment by aryairani** [comment]
I still don't quite understand, unfortunately.  If you can spell out, like, character for character what I should try though, I will do it :)

**Comment by anovstrup** [comment]
@aryairani Did you already follow the step-by-step in the issue description at the top of this page to run the attached transcript using ucm's transcript runner?  

I noticed that in the gists you posted, it appears that you ran `ucm -codebase codebase init` at the command line and then worked with that codebase in ucm (manually, I assume, rather than with the transcript runner). 

When I do the same, the `push` command works correctly, just as it does in your gists.  However, it _does not_ work when I run the transcript or when I use the codebase that's in my home directory (e.g., `/Users/anovstrup`) while running `ucm` from a different working directory (e.g., `/Users/anovstrup/Projects/unison`).  I also found that the push command _does_ work with that same codebase (in my home directory) if I launch `ucm` from the same directory!

**Comment by aryairani** [comment]
> @aryairani Did you already follow the step-by-step in the issue description at the top of this page to run the attached transcript using ucm's transcript runner?

Oops, sorry, no I hadn't!  When I do that, I encounter the same error as you (or similar).

**Comment by aryairani** [comment]
compare https://github.com/aryairani/1136-ucm/tree/master/.unison/v1 with https://github.com/aryairani/1136-transcript/tree/master/.unison/v1.

**Comment by anovstrup** [comment]
@aryairani Note, I observed the same sort of difference in behavior in interactive ucm between a codebase in the local directory where I was running (e.g., `ucm -codebase .`) and the default codebase (in the home directory or wherever?) that ucm uses when launched without args. I launched ucm from the same (non-home) project directory in both cases. `push` worked correctly in the `ucm -codebase .` case and _not_ in the `ucm` case.

**Comment by aryairani** [comment]
@anovstrup Thanks for the `-codebase` clue.

**Comment by aryairani** [comment]
Wait it worked correctly when you specified the codebase but not when you used the default?

**Comment by anovstrup** [comment]
@aryairani 
> Wait it worked correctly when you specified the codebase but not when you used the default?

In my case, yes. The default codebase was the one I'd been using since first starting with M1g (back in November?).  The `-codebase .` one was a new one that I had initialized, following your gists on this issue.

**Comment by anovstrup** [comment]
@aryairani Also, my memory's a little fuzzy—I'm not sure now if the `-codebase` one was `ucm -codebase .` or `ucm -codebase <subdir>`, with `subdir` an immediate child of the working directory. That probably doesn't matter, but letting you know in case it's significant.

**Comment by aryairani** [comment]
Maybe can spot the cause while working on #1281

**Comment by aryairani** [comment]
Hi @anovstrup, this seems to be working now.  I'm not sure exactly what fixed it (feel free to bisect if you're curious) but I'm gonna close for now.  Please reopen if you can reproduce in `master`.  Don't forget `builtins.merge` is needed now, whereas I assume it wasn't, when you first opened this ticket.

e.g. 
    Create a definition:

    ```ucm:hide
    .> builtins.merge
    ```

    ```unison
    type Person = { firstName: Text, lastName: Text }
    ```

    Add it to a namespace and then push the namespace to GitHub.

    ```ucm
    .> cd .myns
    .> add
    .> push repo.git .myns
    ```
