### ISSUE TITLE
'ucm edit .' generates scratch.u that fails to parse 

### ISSUE THREAD

**Issue by rhencke** [unisonweb/unison#1139]
ucm version: release/M1g

When editing the definition of `.`, ucm generates a scratch.u that fails to parse.

Steps to reproduce:
1) Open `ucm`
2) `pull https://github.com/unisonweb/base .base`
3) `cd base`
4) `edit .`
5) Open scratch.u and save it.

Expected result:
scratch.u is parsed successfully

Actual result:
```
/Users/robert.hencke/src/scratch.u:1:1:
unexpected .
expecting ability, type, or use
    1 | . : (b ->{𝕖} c) -> (a ->{𝕖} b) -> a ->{𝕖} c
```

**Comment by aryairani** [comment]
I flagged this as a printer bug, but @atacratic could you confirm?

**Comment by atacratic** [comment]
Agree.  When printing a binding, the pretty-printer should wrap symbolic names in parentheses.

Right now it outputs
```haskell
. : (b ->{𝕖} c) -> (a ->{𝕖} b) -> a ->{𝕖} c
. f g x = f (g x)
```

Instead it should output
```haskell
(.) : (b ->{𝕖} c) -> (a ->{𝕖} b) -> a ->{𝕖} c
(.) f g x = f (g x)
```

Need to check up the situation for local bindings (within a function) as well.

The relevant function is `prettyBinding0`.  Oddly it looks like it already tries to get this right, going on the call to `parenIfInfix` in `renderName`.
