### ISSUE TITLE
Nontrivial distributed programming libraries

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#114]
Nontrivial libraries for distributed systems
- Raft / Paxos (anyone)
- Load-balanced DIndex that uses Raft / Paxos to maintain cluster state (anyone with good feel for remote API)
- DIndex which uses Raft to maintain cluster state? (anyone)

**Comment by proegssilb** [comment]
What's the status of this with regards to readiness, help-wanted, and unison-vs-haskell implementation?

(I'm half-expecting "not ready"/"Don't know", just asking because Raft is relevant to my interests)

**Comment by pchiusano** [comment]
This is going to be blocked for a while, at a minimum we would need:

* #106  
* #107
* #105

That would at least let you write and typecheck more interesting distributed programs. To run them for real, we need some other stuff like #59 ...

**Comment by kanishka-azimi** [comment]
"Total order broadcast and multicast algorithms: Taxonomy and survey" paper might be of use here. I am not sure if there is a more recent survey after it.

**Comment by kanishka-azimi** [comment]
https://z.cash/technology/zksnarks.html - still trying to understand these, but seem like a good example of (distributed) programs that are hard to implement generally (stage n).
