### ISSUE TITLE
Propagate doesn't do constructor replacement when producing new terms

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1145]
When doing a propagate, we call `Term.updateDependencies` to produce an updated version of each term, however, that function doesn’t do constructor replacement, note the todo in the implementation of this function:

```Haskell
updateDependencies
  :: Ord v
  => Map Reference Reference
  -> Map Reference Reference
  -> AnnotatedTerm v a
  -> AnnotatedTerm v a
updateDependencies termUpdates typeUpdates = ABT.rebuildUp go
 where
  -- todo: this function might need tweaking if we ever allow type replacements
  -- would need to look inside pattern matching and constructor calls
  go (Ref r    ) = Ref (Map.findWithDefault r r termUpdates)
  go (TermLink (Referent.Ref r)) = TermLink (Referent.Ref $ Map.findWithDefault r r termUpdates)
  go (TypeLink r) = TypeLink (Map.findWithDefault r r typeUpdates)
  go (Ann tm tp) = Ann tm $ Type.updateDependencies typeUpdates tp
  go f           = f 
```

I think we should add another to this function or else make the `termUpdates` have type `Map Referent Referent` instead of `Map Reference Reference`.

The current implementation results in edits not being propagated as they could otherwise if the constructor was applied.

**Comment by aryairani** [comment]
propagation going away
