### ISSUE TITLE
Issues printing output in unicode

### ISSUE THREAD

**Issue by Sheyne** [unisonweb/unison#1152]
I went to try playing with Unison and created the following devcontainer.  https://github.com/Sheyne/unison These are very easy to use from VSCode [just open container in vscode with the containers plugin, and it'll config your dev env in the VM for consistent builds (more info: https://code.visualstudio.com/docs/remote/containers)]. 

I'm having trouble printing unicode as evidenced by: 

<img width="676" alt="image" src="https://user-images.githubusercontent.com/679358/72576726-5bca1e80-3885-11ea-9ecc-7fb87e55cdc9.png">

I'm still very new to unison, so I don't know how to troubleshoot this at all. Thanks for your help

**Comment by Sheyne** [comment]
If I add a scratch file with unicode: 

```
❤ : a -> a
❤ a = a

> ❤
```

I get `ucm: <stdout>: commitBuffer: invalid argument (invalid character)`: 

```
# ucm 

   _____     _             
  |  |  |___|_|___ ___ ___ 
  |  |  |   | |_ -| . |   |
  |_____|_|_|_|___|___|_|_|
  
  Welcome to Unison!
  
  I'm currently watching for changes to .u files under /workspaces/unison
  
  Type help to get help. 
ucm: <stdout>: commitBuffer: invalid argument (invalid character)
.> 
```

**Comment by Sheyne** [comment]
<img width="577" alt="image" src="https://user-images.githubusercontent.com/679358/72578022-a8aff400-3889-11ea-869b-80c56c50ea89.png">
Here's a screenshot to show colors working

**Comment by aryairani** [comment]
I get:
```
  /Users/arya/unison/u.u:1:1:
  unexpected UnknownLexeme
  expecting ability, type, or use
      1 | ❤ : a -> a
```

**Comment by aryairani** [comment]
@Sheyne Could you open a separate issue for the  `❤` stuff?  I think it's unrelated.

**Comment by aryairani** [comment]
> Here's a screenshot to show colors working

As a heads up, color (ANSI) support and unicode support are unrelated.

Thanks for reporting this, we'll try to get to the bottom of it.

**Comment by aryairani** [comment]
On which platform are you running VSCode?

**Comment by aryairani** [comment]
FWIW, no issues here running native unison in standard vs code (1.37.0) terminal on mac.

**Comment by aryairani** [comment]
@Sheyne Your screenshot reminds me of some of the display issues we had with a native win32 build.  If you are running vscode in windows, I would guess it's a problem with its terminal emulator.

**Comment by aryairani** [comment]
When I try to run `ucm` installed by your devcontainer, in vscode mac, it terminates immediately with only a blank line for output:

![image](https://user-images.githubusercontent.com/538571/72672389-19d8de00-3a27-11ea-9f2e-32a3ce8f555c.png)

**Comment by aryairani** [comment]
Disregard, that was actually ucm invisibly complaining about the absence of an initial codebase.

Again, it seems to not render `Pretty`s that include emoji, from this particular devcontainer in this particular terminal emulator.

![image](https://user-images.githubusercontent.com/538571/72672625-af29a180-3a2a-11ea-9f57-52ba33203718.png)

**Comment by aryairani** [comment]
We probably can't spare the resources to track this down further in the near term, but would love it if someone else could.  It would be slick to be able to run ucm properly within a vscode devcontainer!

**Comment by Sheyne** [comment]
@aryairani I am running on Mac VS code, I’ll try from docker directly in macOS terminal. Thanks

**Comment by aryairani** [comment]
@Sheyne Have you been able to run it alright (with unicode) using the native mac binary release?

**Comment by aryairani** [comment]
When I try running in your docker container directly in the macOS terminal:
`docker exec -t cocky_sinoussi ucm`
it still acts up after the first emoji in the welcome message.
![image](https://user-images.githubusercontent.com/538571/72674112-1fdbb880-3a41-11ea-9a3f-2e0bd2ca770b.png)

**Comment by aryairani** [comment]
I had the same result after building from source in the same ubuntu:latest docker container; however, ucm seems to work fine running from the bionic beaver live cd environment:

![image](https://user-images.githubusercontent.com/538571/72674625-e0b06600-3a46-11ea-8e23-484e8838ac4b.png)

**Comment by aryairani** [comment]
Apparently fixed in in https://github.com/Sheyne/unison/pull/1, but feel free to add more info if you still have trouble.
