### ISSUE TITLE
Transcript parser does not recognise other programming languages

### ISSUE THREAD

**Issue by pete-ts** [unisonweb/unison#1160]
When using the transcript parser to write documentation, they may or may not want to for example add a different language block, and that block should be passed through to the transcript runner as-is.

Currently for the input:
<pre>
```scala
blah
```
</pre>

The output is:
<pre>
```
scala
blah
```
</pre>

https://github.com/unisonweb/unison/blob/a6013ebd3471c00c48bd60da2b3f6afc17f2bba2/parser-typechecker/src/Unison/Codebase/TranscriptParser.hs#L290-L294

The problem seems to be with `lineUntilSpace`, unless parsing `ucm` or `unison`, this always returns an empty string for `fenceType`

**Comment by pete-ts** [comment]
According to [this](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml) 

http://github.com/github/linguist/blob/53379ce42c00e26a816434dd4471b304efd83b09/lib/linguist/languages.yml#L9-L10

Languages recognised (for github at least?) must match by file name, meaning the `fenceType` must be a lower char or underscore. (To allow for `:hide:error`)

**Comment by aryairani** [comment]
@pete-ts Is that "linguist" lib for recognizing fenced code blocks in markdown rendering, or for highlighting full files in the editor and syntax highlighters?  Or both?

**Comment by pete-ts** [comment]
I am not 100% sure, what I am sure about is for a codeblock like triple quote X to be recognised as markup, the X must be one of the filenames in that repo.

**Comment by aryairani** [comment]
@pete-ts Did I dream that you (or someone) had a PR for this?

**Comment by aryairani** [comment]
Closed via #1177.
