### ISSUE TITLE
`transcripts` executable creates `transcript-out` directory even when no transcript output codebases remain to stash there

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1178]
After #1155, the transcript runner deletes the temporary codebase unless `-save-codebase` is specified.  This means that after a successful `stack exec transcripts`, there are no transcripts hanging around.

However, the `transcripts` executable unconditionally creates a `transcript-out` directory and moves specific (or all?) transcripts into it.  This sometimes results in an empty `transcript-out` directory for no reason.  

It would be better not to crteate the directory if there's nothing to move into it.

/cc @pete-ts 🙏😅

**Comment by pete-ts** [comment]
Ah, correctly observed, the directory creation should be conditional. 
Can take a swing at it (in the coming days).

**Comment by aryairani** [comment]
Closed via #1179.
