### ISSUE TITLE
Watch expressions can perform IO

### ISSUE THREAD

**Issue by anovstrup** [unisonweb/unison#1182]
Watch expressions should not be able to perform IO, but as this program demonstrates they actually can (in M1h):

```
helloWorld : '{IO} ()
helloWorld _ =
  use .base.io
  printLine "What is your name?"
  name = !readLine
  printLine ("Hello, " ++ name ++ "!")

ioHandler : Text -> Request IO t -> Text
ioHandler s r = case r of
  { .base.io.IO.putText_ _ s' -> k } ->
    handle k (Right ()) with ioHandler (s ++ s')
  { _ } -> s

> handle !helloWorld with ioHandler ""
```

Once the program typechecks and starts evaluating the watch expression, it hangs waiting for input. Once input is entered, it proceeds to compute the "pure" output value, which will include that console input. (This program arguably shouldn't even compile, since `ioHandler` does not exhaustively handle all IO requests.)

**Comment by anovstrup** [comment]
Here's a minimal program exhibiting the issue:
```
ioHandler r = case r of { x } -> x

> handle .base.io.printLine "Oops!" with ioHandler
```

The output in M1h looks like:
```
  I found and typechecked these definitions in ~/Projects/unison/fpis-unison/scratch.u. If you do
  an `add` or `update`, here's how your codebase would change:

    ⍟ These new definitions are ok to `add`:

      ioHandler : Request 𝕞 𝕧 -> 𝕧

  Now evaluating any watch expressions (lines starting with `>`)... Ctrl+C cancels.

Oops!

    3 | > handle .base.io.printLine "Oops!" with ioHandler
          ⧩
          ()
```
(Note the "Oops!" that snuck out.)

**Comment by atacratic** [comment]
Wow, great bug! That partial handler definition allows you to drop the {IO} from the signature without actually handling the IO requests. I think this is actually OK from a type system point of view, and the sort of thing a future pattern match exhaustiveness checker would help with. Maybe here we should be running watch expression execution in a different context where IO requests trigger an 'unhandled request' runtime error. (Might have a relationship to #1172 where IO ought to behave differently during transcripts.)

**Comment by aryairani** [comment]
#1213

**Comment by anovstrup** [comment]
In addition to #1213, I think Unison should make sure, in general, that code that's not meant to have access to the IO ability is run in a context where it _cannot_ do IO.  Pattern exhaustiveness checking would ensure that _Unison_ does not compile code that illegally performs IO, but it wouldn't protect against third-party manipulation of the serialized AST.

**Comment by pchiusano** [comment]
100% agree - we shouldn't solely rely on the typechecker to restrict access to capabilities. This is something we've talked about for the distributed programming API as well, where it's even more important and where you don't know for certain that the Unison computation you've received has even been typechecked (nor do you want to run typechecking on it at runtime).

**Comment by aryairani** [comment]
Ditto

**Comment by aryairani** [comment]
@pchiusano This is done now in the local and distributed runtimes, right?
