### ISSUE TITLE
unsoundness after unpacking existential that uses an ability?

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#1184]
I managed to smuggle a function that uses an ability into what the type system believes is a pure function and execute it.  

In this example, the type checker thinks `c` is pure, but when I add `d` to run it I get an unhandled ability request error.

```haskell
type Exists F = Exists (forall b. (forall a. F a -> b) -> b)

some : forall F. F a -> (Exists F)
some t = Exists.Exists (f -> f t)

unique ability Foo where
  foo : ()

unique type Pack a = Pack ('a) (a -> ())

dispatch : Pack a -> ()
dispatch a = case a of
  Pack.Pack first andThen ->
    andThen (!first)

dispatch' : Exists Pack -> ()
dispatch' sa = case sa of
  Exists.Exists f -> f dispatch

p = 'let
  Foo.foo
  3

q = 'let
  Foo.foo
  ()

a = Pack.Pack p q
b = some a
c = '(dispatch' b)
d = !c
```
yields the following...
```

  I found and typechecked these definitions in ~/unison/scratch.u. If you do an `add` or
  `update`, here's how your codebase would change:
  
    ⍟ These new definitions are ok to `add`:
    
      type Exists F
      unique ability Foo
      unique type Pack a
      a         : Pack Nat
      b         : Exists Pack
      c         : ∀ (). () -> ()
      d         : ()
      dispatch  : Pack a -> ()
      dispatch' : Exists Pack -> ()
      p         : ∀ (). () ->{Foo} Nat
      q         : ∀ (). () ->{Foo} ()
      some      : ∀ a F. F a -> Exists F
   
  Now evaluating any watch expressions (lines starting with `>`)... Ctrl+C cancels.


  💔💥
  
  I stopped evaluation after encountering an unhandled request:
  
    foo
  
  This happens when using a handler that doesn't handle all possible requests.
  
  I'm sorry this message doesn't have more detail about the location of the failure. My
  makers plan to fix this in a future release. 😢

.> 
```
(master@84e6446)

**Comment by atacratic** [comment]
can't tell if this might be related to #852 ?

**Comment by atacratic** [comment]
I guess the question is what the `'a` and `a -> ()` mean in the following - are they pure?
```haskell
unique type Pack a = Pack ('a) (a -> ())
```
And so should constructing `a = Pack.Pack p q` be allowed, given `p` and `q` use an ability.

So the following is a minimized example (albeit with no runtime failure).

```
unique ability Foo where
  foo : ()

unique type Pack a = Pack ('a) (a -> ())

p = 'let
  Foo.foo
  3

q = 'let
  Foo.foo
  ()

-- should the following typecheck?  At the moment it does, as `Pack Nat`.
a = Pack.Pack p q
```

(If I change `Pack` to `unique type Pack a = Pack (() ->{} a) (a ->{} ())` then sure enough the definition of `a` doesn't type check.)

Is it trying to do effect generalization for the components of `Pack`?  But `Pack` has no effect type parameters for that to make sense.  ([Here's](https://gist.github.com/atacratic/d9f663603d800b6e34f841a956bce466) what happens when I add one: I can't see any unsoundness, but I can't pull off the trick I wanted to.)

**Comment by anovstrup** [comment]
@atacratic I reduced this example down to 
```
unique ability Foo where foo : ()

unique type Delayed a = Delayed ('a)

force : Delayed a -> a
force = cases Delayed.Delayed v' -> !v'

p : '{Foo} Nat
p = 'let
  Foo.foo
  3

a = Delayed.Delayed p
b = force a
```
Not that different from your minimized version, but cuts out some extraneous elements and preserves the runtime error. 

I find it interesting that the type of `a` is inferred as `Delayed Nat`, and if you annotate it as `a : Delayed ({Foo} Nat)`, the typer claims that the body of _**`a`**_ requires the ability `Foo`.

**Comment by pchiusano** [comment]
Thanks! I’d like to get to this and other abilities typechecking issues soon.

**Comment by atacratic** [comment]
Another gremlin, not sure if the same or different.  No abilities involved this time, at least not as far as I can see.

The following correctly fails to typecheck:
```haskell
unique type Pack a = Pack ('a) (a -> ())

p = 'let
  3

q : '()
q = 'let
  ()

a = Pack.Pack p q
-- line above hits "The 2nd argument to the function Pack.Pack is 
-- ._base.prs._2.Unit -> ._base.prs._2.Unit, but I was expecting 
-- ._base.prs._2.Nat ->{𝕖} ._base.prs._2.Unit"
```
...but if I remove the type annotation on `q` it typechecks, giving `q` the same type as I gave it before:
```
  I found and typechecked these definitions in ~/unison/scratch.u. If you do an `add` or `update`,
  here's how your codebase would change:
  
    ⍟ These new definitions are ok to `add`:
    
      unique type Pack a
      a : Pack Nat
      p : 'Nat
      q : '()
```

**Comment by pchiusano** [comment]
If you leave off the signature the parameter is inferred polymorphic, so makes sense that typechecks. But I'm guessing for the signature it uses () as the parameters type. And then there's an inconsistency in when the prettyprinter shows that delay syntax. Like maybe it is just keying off the var name.

Maybe 'a should just mean () -> a at both the term and type level.

**Comment by pchiusano** [comment]
I think this is maybe also a case of incorrect usage of `existentializeArrows` in the typechecker. See #1457

**Comment by dolio** [comment]
The example from Oct 4 seems unrelated to the original issue. Is there an issue to track it separately?
