### ISSUE TITLE
create and use Snoc instances for Path.

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1200]
[Snoc](http://hackage.haskell.org/package/lens-4.19/docs/Control-Lens-Cons.html#t:Snoc) candidates include:
- [x] `Path -> NameSegment -> Path`
- [x] `Path' -> NameSegment -> Path'`
- [x] `Relative -> NameSegment -> Relative`
- [x] `Absolute -> NameSegment -> Absolute`
- [x] `Name -> NameSegment -> Name`
Note that `Cons` is generally wrong for `Absolute` — we had a `consAbsolute`, but it was only used in one place, to implement a bug (#1199).  😅

**Comment by mitchellwrosen** [comment]
Also:
- [ ] `Name -> NameSegment -> Name`
