### ISSUE TITLE
Write up code tour

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#122]
I'd like to do a writeup of the current code to help onboard new contributors. Goal: a document that, in conjunction with #115, gives people most of what they need to start contributing meaningfully to the codebase, assuming they have the relevant technical background. Doc should also provide links to technical background that's a prerequisite for understanding parts of the code, for people who want to school themselves. :) I'd prefer a document that we can point to repeatedly (and that potential future contributors who are observing the project can read).

Things are changing rapidly, and I don't want to document stuff in detail that will be obsolete soon, so I'll probably timebox this to an afternoon or so.

We can do a call after I produce the doc, where people will come having read it and having browsed the codebase and will have questions or comments that we can use to revise the doc and make it more effective!

**Comment by atroche** [comment]
Speaking of schooling ourselves, which resources come to mind as being most valuable for wannabe contributors to read, @pchiusano?
