### ISSUE TITLE
Too many entries in history for sub-namespaces

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#1225]
E.g.

```unison
myLibrary.f x = x + 9
myLibrary.g x = x + 10
myLibrary.h x = x + 3
```

```ucm
.> add
.> history
.> cd myLibrary
.myLibrary> history
```

The first `history` command (from the root) has one entry for all three functions, but the second command (issued from the `myLibrary` namespace) shows three entries; one for each function.

**Comment by aryairani** [comment]
I think this means rewriting `Branch.{stepManyAt0,stepManyAt0M}` to construct a tree from the input paths, do like a post-order traversal of that tree, applying updates from the leaves up, to the `Branch`.

At one point we knew we needed to do this, then we had a broken implementation for it, then it became hard to see where that code would actually go, or that it didn't already do the right thing; I think that's where we are now.
