### ISSUE TITLE
Research optimal Data.Trie usage for Index

### ISSUE THREAD

**Issue by sfultong** [unisonweb/unison#123]
Currently Index.lookupGT traverses more of the Tries than probably necessary.

Email Data.Trie maintainer, and possibly implement PR for Data.Trie lookupGT/lookupLT functions.

**Comment by sfultong** [comment]
@pchiusano FYI, mail to maintainer of this package failed.

Delivery to the following recipient failed permanently:

     wren@community.haskell.org

**Comment by chreekat** [comment]
That's probably because of community.haskell.org, and probably not because of the maintainer. :) Try https://github.com/wrengr/bytestring-trie, or posting to haskell-cafe where they are fairly active.

**Comment by sfultong** [comment]
Thanks! I didn't realize there was a github clone of the darcs repo

**Comment by kanishka-azimi** [comment]
How did you detect it traverses more Tries than necessary?
