### ISSUE TITLE
Add a UCM flag to run transcripts with access to builtins

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1231]
As of #1228, `ucm transcript mytranscript.md` will run from a completely empty codebase. You can put a `.> builtins.merge` at the start of said transcript but it adds some noise. 

We could add a `ucm transcript.builtins mytranscript.md` option which runs from a codebase that has executed `builtins.merge` at the root as its first action. Suspect this will be a straightforward refactoring. See the `Main.hs` for UCM and also possibly the `TranscriptParser.hs`.

**Comment by aryairani** [comment]
I think we might be moving in the wrong direction on this.

* I noticed that even builtins alone aren’t enough for some interesting transcripts.

* This effectively creates two transcript runners and two classes of transcripts, which aren’t necessarily compatible with each other.

* Maybe a better approach is to look for a way to  accelerate/streamline a `pull` so we could pull base (or other) less painfully as part of the transcript.
  * The pull doesn’t have to be from the internet, it could be from disk.

* Alternatively, maybe explicit `builtins.merge` in the transcript isn’t so bad.

* Alternatively, we could have a `-base` flag that pulls base on startup, or `-builtin` to dump builtins, or a `-pull <repo> <path>` option (could be passed multiple times).

**Comment by aryairani** [comment]
Closing this, but feel free to reopen if disagree
