### ISSUE TITLE
Issue with 3-way merge

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1250]
See https://github.com/unisonweb/base2/issues/3 - the merged result appears to be computed incorrectly. We originally thought it was something with `pr.load` but if you do a pull manually and do the merge, you get the same weird results. So it appears to be a problem with the merge function itself.

This could use a more minimal failing example, but the issue linked above does show the behavior.

/cc @runarorama

**Comment by pchiusano** [comment]
We figured out that the existing `BranchDiff` doesn't contain enough info to be able to talk about changes to child namespaces:

```Haskell
data BranchDiff = BranchDiff
  { addedTerms :: Star Referent NameSegment
  , removedTerms :: Star Referent NameSegment
  , addedTypes :: Star Reference NameSegment
  , removedTypes :: Star Reference NameSegment
  , changedPatches :: Map NameSegment Patch.PatchDiff
  } deriving (Eq, Ord, Show)
```

Still not sure what the fix is yet and it's kind of brain melting. Some stuff we've talked about - 

* We contemplated making `BranchDiff` "deep", basically talking about the entire namespace tree, but we concluded that we want the 3 way merge to pick a different LCA for each node of the namespace tree, otherwise you can get pretty terrible results. (Different nodes of the namespace tree will have vastly different LCAs, so trying to pick a single LCA for the entire namespace might pick something super ancient or irrelevant)
* We talked about other changes to `BranchDiff` (like an `addedChildren : Map NameSegment (Branch m)`) but it wasn't clear how that would work especially given that you want to track child deletes as well.
* We considered leaving `BranchDiff` alone and then just fixing up `Branch.merge` to do some post-processing of the children after the `apply` that's called by `Causal.threeWayMerge` something something. This seemed a bit hacky and weird.

@dolio thought maybe that we need a special `Causal.nested3WayMerge` that is aware of the nested structure (that `Branch` is a `Causal` and also contains `Causal` child nodes).

@pchiusano suspects that it'll "Just Work" with the right `BranchDiff` and apply representation, which is unknown at the moment.

**Comment by aryairani** [comment]
In #1151, we talked about replacing `Branch.BranchDiff` with `Unison.Codebase.BranchDiff.BranchDiff`, but that isn't aware of child history either.

**Comment by aryairani** [comment]
> * We talked about other changes to `BranchDiff` (like an `addedChildren : Map NameSegment (Branch m)`) but it wasn't clear how that would work especially given that you want to track child deletes as well.

`modifiedChildren :: Map NameSegment BranchDiff`, does the trick, right?

**Comment by pchiusano** [comment]
@aryairani yeah the other BranchDiff type is not meant to be used for a single level, it summarizes a whole tree of changes. Though there’s some good things about that (it can detect moves better, and we could do the same for a single level I suppose) I don’t think it’s what we want because of my first bullet point above - you want to pick separate LCA for each level being merged.

**Comment by pchiusano** [comment]
Discussion this morning about how to do this properly. Will use a running example: suppose we have two branches, `P1` and `P2`, and a subnamespace, `foo`, which we'll refer to with `P1.foo` , `P2.foo`. `LCA(P1,P2)` is the lowest common ancestor of `P1` and `P2`. To compute `merge(P1,P2)`, we:

1. Compute `LCA(P1,P2)` and do a three way merge of that level of the tree. What about the children of `P1` and `P2`? Let's just consider a child namespace `foo`. There are a few cases:
   1. `P1` and `P2` both have foo as a child namespace. Then `merge(P1,P2).foo == merge(P1.foo, P2.foo)`
   2. `P1` has `foo` as a child namespace, but `P2` does not (or vice versa). Then we have two subcases:
      1. `LCA(P1,P2)` has no `foo`. This means that `foo` child namespace was added by `P1`. The merged result for the `foo` subnamespace is just `P1.foo`. 
      2. `LCA(P1,P2)` does have `foo`. This means that `P2` _deleted_ the `foo` subnamespace. The merged result for the `foo` subnamespace is then `merge(P1.foo, cons empty LCA(P1,P2).foo)`. This does a history-preserving delete of all the definitions that existed at the `LCA` point in history.
         1. Example is like if `P1` added a new definition `foo.bar = 23` after the `LCA`, then `foo.bar` will exist in the merged result, but all the definitions that existed in `foo` at the time of the `LCA` will be deleted in the result.

### Implementation

We were thinking of just modifying `Causal.threeWayMerge` to accept a `(e -> e -> e -> m e)`, since the above algorithm doesn't factor nicely into diffs being combined and the applied. Internal to the function it could still reuse the existing `BranchDiff` machinery for handling the merge of stuff at the current level, but it will be doing this other thing for merging the children.

Should be a very surgical change to that function and to `Branch.merge` (which calls that function), so seems fairly low risk if we decide we want to change it later.

#### Notes

We debated whether to incorporate `LCA(P1,P2).foo` somehow into case 1 above. It seems not relevant, because at best it would a worse `LCA` than the `LCA(P1.foo, P2.foo)`. This is based on the observation that whenever you update a subnamespace, you have to also update the parent namespaces, up to the root, so LCAs are going to be "tighter" further down in the namespace.

@aryairani do you want to try to understand the above and see if you can break it?

**Comment by runarorama** [comment]
This sounds sane to me. Particularly I like that there's a homomorphism law `merge(P1,P2).foo == merge(P1.foo, P2.foo)` :)

**Comment by aryairani** [comment]
@runarorama Does it still hold in case 1.ii.b.a?  If so, then I'm sold.

**Comment by runarorama** [comment]
I think it does hold in the sense that if `P2` has `foo` removed, then it will also be removed in either case.
