### ISSUE TITLE
Publish elmz?

### ISSUE THREAD

**Issue by joneshf** [unisonweb/unison#126]
I know the elm frontend is history, but you have a ton of great things in `Elmz` that are still missing in current elm-land. Any interest in publishing it for others? If not, would you mind if I fork it to its own project?

**Comment by pchiusano** [comment]
Please go right ahead and fork it to its own project if it is useful to you, license is MIT. :)

**Comment by refried** [comment]
Note to self to see what Elmz is.

**Comment by joneshf** [comment]
It was the stuff here: https://github.com/unisonweb/unison/tree/master/editor-elm/src/Elmz. Now lives here: https://github.com/elmzed/elmz
