### ISSUE TITLE
`update` output uses non-suffixified PPE

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1273]
We see this before #1254

![image](https://user-images.githubusercontent.com/538571/75273377-0b899900-5801-11ea-8524-05725534c964.png)

as well as after:

![image](https://user-images.githubusercontent.com/538571/75273346-fdd41380-5800-11ea-9c80-8c95be673d6c.png)

**Comment by pete-ts** [comment]
when `add` gets handled the output is produced here:
https://github.com/unisonweb/unison/blob/c76caf178470ad396fbb5c2e475504656cb47514/parser-typechecker/src/Unison/Codebase/Editor/HandleInput.hs#L1360-L1363

and when `update` gets handled the output is produced here:
https://github.com/unisonweb/unison/blob/c76caf178470ad396fbb5c2e475504656cb47514/parser-typechecker/src/Unison/Codebase/Editor/HandleInput.hs#L1467-L1470

`update.preview` also seems to align with `add` and `add.preview`

It looks like a quick change from `prettyPrintEnv` to `prettyPrintEnvDecl` does indeed change all transcripts that call `update` to produce suffixied output.

Shall I create the (small) PR ?

**Comment by pchiusano** [comment]
Yea sounds great! I had a feeling it would be a small change
