### ISSUE TITLE
Docker build failed on macOS 10.12.1

### ISSUE THREAD

**Issue by GetContented** [unisonweb/unison#128]
Opening this issue as per instructions in Readme. Follows is the tail of the log output (I'm now attempting a stack install):

        kan-extensions-4.2.3: copy/register
        lens-4.12.3: configure
        lens-4.12.3: build
        lens-4.12.3: copy/register
        ghcjs-dom-0.2.2.0: copy/register
        unison-shared-0.1: copy/register

        --  While building package haskell-src-exts-1.16.0.1 using:
              /root/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.22.4.0-ghcjs-0.2.0.20151001_ghc-7.10.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.4.0_ghcjs build --ghc-options " -ddump-hi -ddump-to-file"
            Process exited with code: ExitFailure 1
            Logs have been written to: /opt/unison/.stack-work/logs/haskell-src-exts-1.16.0.1.log

            Configuring haskell-src-exts-1.16.0.1...
            Building haskell-src-exts-1.16.0.1...
            Preprocessing library haskell-src-exts-1.16.0.1...
            [ 1 of 22] Compiling Language.Haskell.Exts.Annotated.Syntax ( src/Language/Haskell/Exts/Annotated/Syntax.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0_ghcjs/build/Language/Haskell/Exts/Annotated/Syntax.js_o )
            
            /tmp/stack7/haskell-src-exts-1.16.0.1/src/Language/Haskell/Exts/Annotated/Syntax.hs:112:1: Warning:
                The import of ‘Data.Foldable’ is redundant
                  except perhaps to import instances from ‘Data.Foldable’
                To import instances alone, use: import Data.Foldable()
            
            /tmp/stack7/haskell-src-exts-1.16.0.1/src/Language/Haskell/Exts/Annotated/Syntax.hs:113:1: Warning:
                The import of ‘Data.Traversable’ is redundant
                  except perhaps to import instances from ‘Data.Traversable’
                To import instances alone, use: import Data.Traversable()
            ghcjs-0.2.0.20151001-7.10.2.bin: out of memory (requested 2097152 bytes)
        The command '/bin/sh -c stack --stack-yaml editor.yaml build' returned a non-zero code: 1

**Comment by kanishka-azimi** [comment]
haskell-src-exts usually is the breaking point for memory when building on other projects I have worked on. We usually just increase the memory on the machine to fix this.

**Comment by GetContented** [comment]
@kanishka-azimi The machine this build was output on has 16 GB of RAM.

**Comment by kanishka-azimi** [comment]
We usually hit the limit on 2gb ec2's. I also sometimes hit the limit on my
laptop if I run concurrent builds.

I wonder if there is anything limiting how much memory is allocated to the
build...

On Dec 3, 2016 8:55 PM, "www.getcontented.com.au" <notifications@github.com>
wrote:

@kanishka-azimi <https://github.com/kanishka-azimi> The machine this build
was output on has 16 GB of RAM.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/unisonweb/unison/issues/128#issuecomment-264678875>,
or mute
the thread

**Comment by GetContented** [comment]
@kanishka-azimi what about the output I was getting led you to believe it's RAM related?

**Comment by pchiusano** [comment]
See #138, am getting rid of the Docker stuff from the build and simplifying things. Use the Vagrant VM if you like, or just use stack directly.
