### ISSUE TITLE
ucm exits when autocompleting path arg for push command

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1282]
```
.> push file:///Users/arya/unison4/repo/ t20:15 ~/unison4 (master)$ 
```

**Comment by pete-ts** [comment]
I cannot tell if this is a duplicate of https://github.com/unisonweb/unison/pull/1374 :thinking: , but I think so.

**Comment by aryairani** [comment]
Oops!  I was wondering where I had put this. :)
