### ISSUE TITLE
`ucm:hide` blocks are hidden from the transcript failure output

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1295]
For example:

    Dangerous scary words!
    
    ```ucm:hide
    .> move.namespace foo bar
    ```

Yields:
```
⚙️   Processing stanza 2 of 2.Dangerous scary words!



🛑

Transcript failed due to the message above.
```

which is confusing, because the error is hidden.

* `unison:hide` blocks are okay-ish, as they still print the offending source.
* `unison:hide:all` blocks again hide all of the problem.

**Comment by pete-ts** [comment]
@aryairani I think I might have some time to look into this, after a spell of being tied up. Do you have a suggested target/fixed behaviour in mind?

**Comment by pete-ts** [comment]
(As long as "help-wanted" of course!)

**Comment by aryairani** [comment]
@pete-ts 
![image](https://user-images.githubusercontent.com/538571/75915264-77e64700-5e56-11ea-9da9-06771006a70f.png)
😁

I was thinking the behavior should be:  If a transcript fails as a result of a hidden stanza (either due to encountering an error, or failing to encounter an expected error), then the stanza should still be printed to the console before "The transcript failed due to an error encountered in the stanza above."

"The transcript failed to fail as expected in the stanza above." also seems reasonable, if you are willing to set up a separate message for the two cases.
