### ISSUE TITLE
Evaluation in Docs should not show the name of the evaluated definition

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#1305]
Currently, given `foo = 2 + 2` the Doc `[: @[evaluate] foo :]` renders as `foo = 4`. We should change this so it just results in `4`. The old behaviour can be accomplished with `[: foo = @[evaluate] foo :]` instead.

This change should be made in `DisplayValues.hs`.

**Comment by aryairani** [comment]
I think want to be able to accomplish the old behavior with something that's represented with a reference and not just a string though, so the name will update automatically too; so not just `[: foo = @[evaluate] foo :]`

**Comment by runarorama** [comment]
So `@foo = @[evaluate] foo` then
