### ISSUE TITLE
Building the editor fails using stack

### ISSUE THREAD

**Issue by prange** [unisonweb/unison#131]
I get 
```
exit status: 1                                
stderr: Warning: No remote package servers have been specified. Usually you would have
one specified in the config file.             
setup: dist/: does not exist                  
cabal: Error: some packages failed to install:
Cabal-1.22.4.0 failed during the configure step. The exception was:
ExitFailure 1  
```
when running `stack --stack-yaml editor.yaml setup` in the folder i downloaded Unison from github. I run version `Version 1.2.0 x86_64 hpack-0.14.0` on a MacOS Sierra `10.12.1`

Any ideas of where i screwed up?

**Comment by beenotung** [comment]
I did not fail when building editor, but seems not working as expected.

After running `stack exec node`, it enter haskell REPL, instead of starting the editor web server.

**Comment by pchiusano** [comment]
See #138, editor is being allowed to bitrot intentionally, so closing this
