### ISSUE TITLE
Write up and/or reproduce "name conflict" issue in a transcript

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1310]
This one:
>Resolving a name conflict is actually really hard. First, it complains that there's a conflict. And there's no help for how to resolve it.

**Comment by aryairani** [comment]
Also found this:
> Resolving a name conflict is actually really hard. First, it complains that there's a conflict. And there's no help for how to resolve it. When you then resolve the (local) name conflict (by deleting all the names), you get a NEEDS ALIAS for some totally unrelated name (outside the current namespace).

**Comment by runarorama** [comment]
Resolved by #1254

**Comment by aryairani** [comment]
@runarorama Wait, #1254 is only half of this, right?

**Comment by aryairani** [comment]
¯\\\_(ツ)_/¯
