### ISSUE TITLE
tab completion crash on second argument to `push`

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1324]
I thought I'd already created a ticket for this, but I can't find now.

Anyway, I think the issue is related to having two differently-typed `InputPattern.IsOptional.Optional` arguments — as initially designed, `Optional` arguments were only expected at the end; they could only follow Required arguments (or how would you know which kind of argument you were supposed to be completing?)

I guess we could fix by adding logic that says "earlier `Optional` arguments are assumed to have been present when parsing later ones", or reorg the argument parsing code more severely.

```haskell
push :: InputPattern
push = InputPattern
  "push"
  []
  [(Optional, gitUrlArg), (Optional, pathArg)]
  ...
```

**Comment by aryairani** [comment]
I guess I'd just change `gitUrlArg` to `Required`, as it's required before you can use auto-complete for `pathArg`.  

Later, if we start doing more with the `IsOptional` fields (such as automatically generating help), then we can revisit this and expand the language or whatever.

**Comment by pete-ts** [comment]
As per @aryairani 's comment above, making the first argument `Required` does seem to fix this. 

```
-  [(Optional, gitUrlArg), (Optional, pathArg)]
+  [(Required, gitUrlArg), (Optional, pathArg)]
```

Shall I raise the single-line PR, or is there more context I might not be aware of?

**Comment by aryairani** [comment]
@pete-ts Yeah go for it!  Could you just put a note in the PR description (to compensate for my brain's one-byte buffer) that asserts that the with the PR, the auto-complete does work, i.e. doesn't crash :)

**Comment by pete-ts** [comment]
I will do you one better, and attach a pic or two.
