### ISSUE TITLE
Add escape sequence for space (?\s) to list of escape sequences in LanguageReference.md.

### ISSUE THREAD

**Issue by drewctaylor** [unisonweb/unison#1330]
Add escape sequence for space (?\s) to list of escape sequences; currently, it is the only escape sequence from Lexer.hs not present in the document.

**Comment by anovstrup** [comment]
@drewctaylor Here's the source: https://github.com/unisonweb/unisonweb-org/blob/master/src/data/docs/language-reference/README.md

Would you mind submitting a quick pull request?

**Comment by anovstrup** [comment]
(For small changes like this, it's easiest to just edit the source right on github.)

**Comment by aryairani** [comment]
Fixed in https://github.com/unisonweb/unisonweb-org/pull/102
