### ISSUE TITLE
pretty-printer should produce annotations allowing hyperlinked source

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#1332]
@seagreen asked me to raise this - he reckons he'll have a crack at it, in order to implement hyperlinked source in Unison Codebase Explorer (https://github.com/seagreen/unison-code-explorer/issues/3)

There are some implementation tips here: https://github.com/atacratic/unison/commit/c935fed329de28e403d8a5a8fc05acfba2a0f4ee  (you can also clone https://github.com/atacratic/unison.git and check out branch topic/syntaxtext-markup, or apply this patch: 
[patch.txt](https://github.com/unisonweb/unison/files/4308944/patch.txt)).

Currently, the pretty-printer emits `Pretty SyntaxText`.  The `Pretty` is one layer of markup, relating to layout.  The `SyntaxText` includes another layer of markup on top of the raw text - styling info that supports syntax highlighting.  The idea here is to extend `SyntaxText` so that references (to other terms and types) have some metadata available, giving the full unabridged name, and the hash (in fact a `Referent`/`Reference`).

That will just be ignored when rendering to plaintext or ANSI console text, but when rendering HTML it can be used for hyperlinking or hover text.

(Unlike the situation imagined in #282, here we're able to run the pretty-printer when we already have a specific fixed `PrettyPrintEnv` in mind.)

FYI @pchiusano

**Comment by pchiusano** [comment]
This would be great!! And I am on board with the basic approach of just extending the annotation type used to contain an optional `Reference` / `Referent`.
