### ISSUE TITLE
runtime doesn't implement `##List.empty`

### ISSUE THREAD

**Issue by drewctaylor** [unisonweb/unison#1338]
When you place this line in a scratch file

&gt; base.List.empty

You'll receive the following error:

https://gist.github.com/drewctaylor/5d8cf40b808d1985c3de82589c35c482

    The program being compiled referenced this definition ##List.empty
    but the compilation environment has no compiled form for this reference.

`ucm --version` returns `release/M1h`.

**Comment by aryairani** [comment]
I think your installation may be a touch messed up from an earlier version; can you try deleting base.List.empty and then pulling again?

**Comment by raam86** [comment]
Pretty sure it is something with the env too:

```
  The program being compiled referenced this definition ##Bytes.fromSequence
    but the compilation environment has no compiled form for this reference.
...
    Bug reference: B8920912182
...
    CallStack (from HasCallStack):
      error, called at src/Unison/Runtime/IR.hs:498:18 in unison-parser-typechecker-0.1-3tWDCIbHDtSBY3Ao9EQ2rv:Unison.Runtime.IR
```

**Comment by drewctaylor** [comment]
I tried `delete.namespace base`; still happened. I also tried deleting my `~/.unison` directory and re-creating via `ucm init`; still happened. Recall this is `release/M1h` - I haven't tried the `master` branch.

**Comment by drewctaylor** [comment]
[unison.zip](https://github.com/unisonweb/unison/files/4318847/unison.zip)

**Comment by aryairani** [comment]
Could you try putting this code block into a markdown file (with the backticks and everything) and run `ucm transcript thatfile.md` and report back?

    ```ucm
    .> pull https://github.com/unisonweb/base .base
    ```
    ```unison
    > base.List.empty
    ```

**Comment by drewctaylor** [comment]
https://gist.github.com/drewctaylor/254411c7fdb4bab6f687270bb64d2f30

**Comment by aryairani** [comment]
@drewctaylor I was able to reproduce this, thanks for reporting.  Until it's fixed, you can use `[]` instead of `List.empty`.

**Comment by aryairani** [comment]
Okay, upon further reflection, I think we want to go on the opposite direction: eliminate both `##List.empty` (which isn't handled by the runtime) and `##Sequence.empty` (which accidentally is).

Better probably is:
1. add `List.empty = []` to `base`
2. `D` deprecate `##List.empty` and `##Sequence.empty` in `Builtins.hs`? (I don't totally remember what this means anymore)
3. replace `##List.empty` and `##Sequence.empty` with the new `base.List.empty` in some patch?
  * it may not be possible to add these builtins to a patch if they're straight-up deleted from builtins; as there is some validation for the builtins that are supplied to `replace.term`.  Maybe Step 2 comes into play here.

**Comment by pchiusano** [comment]
@drewctaylor If you pull latest base, `List.empty` is now just `List.empty = []` and should work totally fine. Please reopen if not. Note that if you have some existing code in your codebase that uses the old `List.empty`, you can do:

```
.> pull https://github.com/unisonweb/base .base
.mycode> patch .base.patch
```

The `patch .base.patch` will replace the old `List.empty` (you can do `view.patch .base.patch` to see what's in there).

If the code is just in a scratch file and not in the codebase yet, then just reparsing that scratch file after pulling the latest `base` should fix.
