### ISSUE TITLE
fix Name.suffixes and add a unit test

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1339]
eg `suffixes “foo.Bar.baz”` should include `[“foo.Bar.baz”, “Bar.baz”, “baz”]` and not include `””`.

**Comment by pete-ts** [comment]
Question around `suffixes` input domain: is the empty string `""` valid input for this function? 
And if yes do you expect `[]` as the output?

**Comment by aryairani** [comment]
I would say:
* No, it isn't valid input
* I would expect `[]` as the output.
