### ISSUE TITLE
Old metadata stays linked after update

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#1349]
1. Add a `Doc` to the codebase.
2. Link it to a definition.
3. Edit the `Doc` from step 1 and `update`.

The link from step 2 stays between the old Doc and the definition. I'd expect it to get removed and replaced with a link to the Doc from step 3.

There's also no way of unlinking the old `Doc`, since it now has a hash-qualified name and `unlink` can't handle those.

**Comment by aryairani** [comment]
Geez, bad combination.

**Comment by pchiusano** [comment]
I’ll close this in favor of #1497

I thought unlink does now work with hash qualified but could be wrong.

**Comment by aryairani** [comment]
@runarorama @pchiusano 

I'd like to make it our new standard procedure that bug reports — particularly those of the form "follow these steps to reproduce the issue" — be submitted with a transcript.  (They can be embedded in markdown just by indenting the whole thing 4 spaces.)  For example:

    ```unison:hide
    ability Stream e where
      emit : e ->{Stream e} ()
    ```
    
    ```ucm
    .tutorials.abilities> add
    .tutorials.abilities> load
    ```

And optionally relevant excerpts from the `.output.md`; it can also go into a gist whenever that's more appropriate.

This is both a tool to help the submitter to verify / minimize their report, and the responder the ability to easily check if the issue still exists in later builds.

I propose we strongly encourage this among all those capable of producing them (intermediate users and up), while understanding that not every circumstance allows for creating a "complete" bug report.
