### ISSUE TITLE
pull-request.create very long timeout in case of typo

### ISSUE THREAD

**Issue by pete-ts** [unisonweb/unison#1355]
I tried creating a PR with the `pull-request.create` command.
Due to the folding of my terminal I did not notice that instead of `github.com`, I pointed the pr to `github.cm`.

The PR process stood still for quite a long time, before eventually coming back with 

```
fatal: unable to access 'https://github.cm/x/base/': Failed to connect to github.cm port 443: Connection timed out

  I couldn't access a git repository at https://github.cm/x/base. Make sure
  the repo exists and that you have access to it.
```

**Comment by aryairani** [comment]
I think our hands are kind of tied on this one; github.cm has an IP address and it ignores https requests instead of rejecting them.  If you do a `$ git clone https://github.cm/x/base` you'll see the same behavior.

I'm going to close this issue for now, but feel free to reopen if you have an idea for how you'd like to see it work differently.

**Comment by anovstrup** [comment]
@aryairani A (relatively) simple solution would be to keep a list of common domains and use edit distance (Text.EditDistance?) to compare an unrecognized domain against the list. If the edit distance is small enough, say something like 
```
Did you mean github.com?

  1. Yes, replace "github.cm" with "github.com" and continue.
  2. No, just run my command.
```
Probably not real high on the priority list, but maybe worth reopening?

**Comment by aryairani** [comment]
@anovstrup I would rather find a way to make `github.com` privileged than to penalize `github.cm` which is someone's domain.  I used to have a syntax like `gh:anovstrup/base` but I couldn't decide whether it should expand to `https://github.com/anovstrup/base` (authentication optional, but unlikely to be configured) or `git@github.com:anovstrup/base` (authentication more likely to be configured, but most people would be denied access).

**Comment by anovstrup** [comment]
@aryairani ooh, the hidden feature is neat! Maybe that could be surfaced (e.g., if the domain is github.com, the tool could say "Tip: `gh` tab-completes to https://github.com/")?

I guess I wouldn't feel too bad about "penalizing" domains that are clearly trying to profit off of people's typos, especially if the penalty is a relatively harmless prompt.  🤷‍♂️:-)

**Comment by aryairani** [comment]
> @aryairani ooh, the hidden feature is neat! Maybe that could be surfaced (e.g., if the domain is github.com, the tool could say "Tip: `gh` tab-completes to https://github.com/")?

@anovstrup Nice idea; help wanted! 😄
