### ISSUE TITLE
`link` allows re-linking and breaks ucm on `unlink`

### ISSUE THREAD

**Issue by pete-ts** [unisonweb/unison#1356]
The usage of the link command to reproduce this issue might not technically be correct, but `ucm` allows it and thus ends in a bad state (I think)

When linked documentation gets updated, the user can `re-link` the documentation. This leads to a situation where multiple documentation links are shown, and an attempt to `unlink` crashes `ucm`

https://gist.github.com/pete-ts/ddb8dea0fc4ffc9f21e73c7820781844

**Comment by pchiusano** [comment]
Started work on this in fix/1356 branch. Started by removing all the `fromJust` calls and replacing them with `fromMaybe` calls that print an error, now get the following:

```
⚙️   Processing stanza 15 of 15.
unison: HashQualified'.unsafeFromHQ
CallStack (from HasCallStack):
  error, called at src/Unison/HashQualified'.hs:37:9 in unison-core-0.1-rbFF5SjospGfLqkeyzsrn:Unison.HashQualified'
```

@aryairani anything jump out at you on this one? The transcript is the one @pete-ts linked above: https://gist.github.com/pete-ts/ddb8dea0fc4ffc9f21e73c7820781844

**Comment by aryairani** [comment]
@pchiusano Looks like that function is 
```haskell 
HashQualified'.unsafefromHQ :: HQ -> HQ'
```
Metadata links a `Reference` to a `(Reference,Name)` pair.  `HQ'` is the one that requires a name, so this makes sense.  Looks like somewhere along the way it's being represented as an `HQ` (which doesn't require a name), and then "unsafe"ly converted to the one that does require a name, and fails because it doesn't have one.

I'm not familiar with the `links` code, so I'm not sure where that might happen without doing some digging.

**Comment by aryairani** [comment]
```haskell
  | LinkI [Path.HQSplit'] Path.HQSplit'
  -- unlink from to
  | UnlinkI [Path.HQSplit'] Path.HQSplit'
```
make sure that the ones in the array are parsed as HQ' and not HQ.  The last one (the metadata) can be HQ.

**Comment by pchiusano** [comment]
Thanks that is very helpful. Think I know what’s going on - the unlink code is expecting the attached metadata to have a name in the current namespace. It doesn’t though after the update.

**Comment by aryairani** [comment]
Can't speak to the assumptions of the unlink code, but conceptually, it should be okay for the attached metadata to not have a name.  If it's something like: it's just being converted `HQ -> HQ'` to reuse some display function for pretty-printing, then that's the mistake.

**Comment by pchiusano** [comment]
Yeah agree it should definitely support unnamed metadata.
