### ISSUE TITLE
want to be able to detect branch load failure

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1359]
```haskell
data Codebase m v a = Codebase { 
  --
  , getRootBranch      :: m (Branch m)
  --
  , getBranchForHash   :: Branch.Hash -> m (Branch m)
  --
  }
```
Currently these both return `Branch.empty` on failure which is indistinguishable from success from the outside; not sure what the best way to go about fixing this is.

* Have them return `m (Maybe (Branch m))`?  It quickly forces you down a path towards `m (Maybe (Branch (MaybeT m)))` or other horrible gymnastics
* Use a `Codebase (EitherT String m) v a`?  Also doesn't seem right.

Thoughts?  /cc @pchiusano 

We have some underlying functions that take one of these, which seems like a joke in retrospect:
```haskell
module Unison.Codebase.BranchLoadMode where
-- When loading a nonexistent branch, what should happen?
-- Could bomb (`FailIfMissing`) or return the empty branch (`EmptyIfMissing`).
--
-- `EmptyIfMissing` mode is used when attempting to load a user-specified
-- branch. `FailIfMissing` is used when loading the root branch - if the root
-- does not exist, that's a serious problem.
data BranchLoadMode = FailIfMissing | EmptyIfMissing deriving (Eq, Show)
```

Why did we want to silently fail when attempting to load a user-specified branch? lol

Seems like we always want `FailIfMissing`, but to `MonadFail` into something nice like a `Maybe` or `Either String`.  From there, we can `cata` into `Branch.empty`, or `<|>` or whatever the application logic calls for.

**Comment by aryairani** [comment]
updated ^

**Comment by pchiusano** [comment]
If user types a branch hash in UCM (like with fork), that might not exist, so not a catastrophic error... however you also still wanna know about it.

Seems like it can just be: m (Either Reason (Branch m)) for the return type. There’s no Either/Maybe on the inside - once you have a Branch, all the child and history pointers are presumed valid unless something is catastrophically wrong with the codebase. (In which case bombing with an exception and as helpful a message as possible seems ok to me - could even catch at top level and restart the UCM loop)

You could use EitherT Reason m / MonadError everywhere but that does not sound like a fun refactoring and not sure how much it buys you.

**Comment by aryairani** [comment]
It doesn’t happen with fork because I have that going through a call to resolve short branch hashes first, but it’s still an issue from an internal api perspective.  Thanks for the feedback.  It seemed hairier than I thought it should have, but I’ll take another stab at just getting Either on the outside; not worrying about serialization errors but just basic “is the file present” for now.

**Comment by aryairani** [comment]
Just making a note here:
`FileCodebase.branchFromFiles` deserializes a `Branch m` by calling `Branch.read`, which has this signature:

```haskell
Monad m
  => Causal.Deserialize m Raw Raw
  -> (EditHash -> m Patch)
  -> Hash
  -> m (Branch m)
```

It can fail, but it seems like an annoying refactor to even figure out if the top level can load.  So I will just have `Nothing` (at the higher level) not be "I failed to load" (e.g. because I got bits I didn't expect), but like "I couldn't even try to load" (e.g. because it was not present in my `Map`, or the appropriate file doesn't exist).

**Comment by aryairani** [comment]
the signatures have been updated to return failure values.  I'm not sure if this means they _definitely_ still don't call `fail`, but fingers crossed.

```haskell
getRootBranch      :: m (Either GetRootBranchError (Branch m))

getBranchForHash   :: Branch.Hash -> m (Maybe (Branch m))
```
