### ISSUE TITLE
Doc value parses incorrectly

### ISSUE THREAD

**Issue by anovstrup** [unisonweb/unison#1363]
This doc value ends up being parsed incorrectly:

```unison
void.doc = [: `@void op` executes an effectful computation `op` for its effects,
  ignoring the return value. `@void op` is equivalent to `@ignore . op`.

  __See also__ @ignore

:]
```

After adding the definition, `view void.doc` prints the following:
```
  void.doc : #v00j3buk6m
  void.doc =
    [: `@voidop` executes an effectful computation `op` for its effects,
    ignoring the return value. `@void op` is equivalent to `@ignore .
    op`.

    __See also__ @ignore

    :]
```
(Note the missing whitespace in "voidop".)

Based on this showing up in the _view_ output, this seems to be a parser issue? The behavior is inconsistent; a similar definition is parsed/rendered as expected:

```
ignore.doc = [: `@ignore a` ignores the argument `a` and returns `()`. :]
```

**_See also_** [this gist](https://gist.github.com/anovstrup/941af998bd503abc2886d94889f4fa4d), and [the gist output](https://gist.github.com/anovstrup/63d2269adce3efe7744390216bdd29eb)

**Comment by atacratic** [comment]
Have most of a fix - just need to dig into a regression it causes.

btw I think your comment example should read `@ignore !op` rather than `@ignore . op` - reasoning as follows:

```haskell
void op = let
  !op
  ()

ignore a = ()

op = 'let
  printLine "foo"

f = 'let
  void op

g = 'let
  ignore !op
```
```
  I found and typechecked these definitions in ~/unison/scratch.u. If you do an `add` or `update`,
  here's how your codebase would change:
  
    ⍟ These new definitions are ok to `add`:
    
      f      : ∀ (). () ->{IO} ()
      g      : ∀ (). () ->{IO} ()
      ignore : a -> ()
      op     : ∀ (). () ->{IO} ()
      void   : '{𝕖} o ->{𝕖} ()
   
  Now evaluating any watch expressions (lines starting with `>`)... Ctrl+C cancels.

.> 

```

**Comment by anovstrup** [comment]
> btw I think your comment example should read `@ignore !op` rather than `@ignore . op` - reasoning as follows:

I think that makes sense with that definition of `void`, but mine is
```
void : (a ->{e} b) -> a ->{e} ()
void = (.) ignore
```

... which I just realized still means that my documentation for `void` is grossly inaccurate, but for different reasons. :-)
