### ISSUE TITLE
print a warning when one or both namespaces to be diffed are Branch.empty

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1367]
```
.temp> diff.namespace temp.base temp.merged

  The namespaces are identical.

.temp> diff.namespace temp.haed temp.merged

  The namespaces are identical.
```
🤔  I didn't notice I was adding "temp" but was already in .temp

Maybe something like
> The namespaces .temp.temp.base and .temp.temp.merged are empty.  Was there a typo?

or

> ⚠️ The namespace .temp.temp.haed is empty, was there a typo?
>
> Added: ...

**Comment by pchiusano** [comment]
Also, maybe a separate ticket, but when one of the arguments to a `pr.create` or `pr.load` is empty, that's worth a warning as well!

**Comment by aryairani** [comment]
Maybe some heuristic too for rejecting pushes with unrelated* histories.

*Our histories are always related by the empty Branch, but maybe they
wouldn't have to be?
