### ISSUE TITLE
Audit all autocomplete providers

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1377]
I think I want to switch all but `ls` and `cd` over to fuzzy matching, but want to think through it.

**Comment by aryairani** [comment]
It's gonna be so good :)

**Comment by aryairani** [comment]
We might find that `ls` and `cd` with relative arguments could also be fuzzy, but we would probably want to do something visually to make it clear that these are fuzzy matches where appropriate.  Or maybe there's a user syntax for fuzzy jumps like `cd ~multiset`.

**Comment by aryairani** [comment]
Test case: `view .List.map<tab>`

**Comment by aryairani** [comment]
partly covered by #4513

**Comment by aryairani** [comment]
I think this was done in #4519
