### ISSUE TITLE
`create.author` command

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1392]
Proposed usage:

```
.foo> create.author alicecoder "Alice McGee"
   
  I created:
    
    metadata.authors.alicecoder
    metadata.copyrightHolders.alicecoder 

  Suggestion: Add `License` values for `alicecoder` under `metadata.authors.alicecoder`.

.foo> link metadata.authors.alicecoder def1 def2
...
.foo> link metadata.authors.alicecoder.defaultLicense def3 def4
```

So it creates the `Author` and `CopyrightHolder` values under the current path, `alicecoder` is the unison identifier name used for the definitions. Would typically be issued at the root of a project.

**Comment by aryairani** [comment]
@pchiusano Do you want `metadata.authors.alicecoder.guid`? Or inlined?

**Comment by pchiusano** [comment]
@aryairani create the guid, don’t inline
