### ISSUE TITLE
crazy parse bug

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1393]
```haskell
b y = case a of n -> y
```
```
.temp> add

  ⍟ I've added these definitions:
  
    b : y -> case -> a -> of -> n -> y

.temp> view b

  b : y -> case -> a -> of -> n -> y
  b y case a of n = y

.temp> 
```
Just, what?

**Comment by anovstrup** [comment]
I don't think this is a bug. The definition is equivalent to
```
f x = g a b c -> x
```
because `case` and `of` are not keywords.

**Comment by pchiusano** [comment]
@anovstrup epic! Pretty funny though.

**Comment by aryairani** [comment]
Oh, yikes though.  I mean I knew `case` and `of` weren't keywords, but forgot about lambda syntax.
