### ISSUE TITLE
autocomplete for `link` feels broken

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1398]
![image](https://user-images.githubusercontent.com/538571/78414145-c1a68680-75e8-11ea-96d7-3ed252840f1e.png)

What. I don't want to browse, I just want to autocomplete the word `metadata`. 😕 

Propose just doing forward completion of a suffixified namespace.  (Ref #1377)

**Comment by aryairani** [comment]
![image](https://user-images.githubusercontent.com/538571/78414252-48f3fa00-75e9-11ea-9b2e-32413474baac.png)

This is the point where I realized I'm not going to be able to auto-complete at all without typing out all of a unique substring, which may be quite long.

**Comment by mitchellwrosen** [comment]
fixed in #4574
