### ISSUE TITLE
Pretty-printing of non-ascii characters in Text is broken.

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#1429]
Unison:
```unison
> "Rúnar"
```

UCM:
```ucm
    1 | > "Rúnar"
          ⧩
          "R\250nar"
```

But `\250` is not a valid escape sequence in Unison.

**Comment by pete-ts** [comment]
I have investigated the issue and come up with a possible fix:
The output for `Text'` is not escaped, as per the description of the issue.
https://github.com/unisonweb/unison/blob/ea39f957b3e0a13c5603302812971299ec2931f0/parser-typechecker/src/Unison/TermPrinter.hs#L190-L193

On the one hand:
* An existing package for escaping can be used here and it solves the issue
* https://github.com/pete-ts/unison/compare/master...pete-ts:escape-sequences

But on the other hand:
* The package I found is not actively maintained and not being 100% familiar with the Haskell ecosystem maybe there is an alternative I am not aware of?
** http://hackage.haskell.org/package/unicode-show-0.1.0.4/docs/Text-Show-Unicode.html 
** https://github.com/haskell-jp/unicode-show#readme
* Is there value coming up with the escaping code from scratch potentially? (but the cost of testing to ensure it is correct in the face of corner-cases...)
* Could use the approach taken for `Weighted` and incorporate the 3rd party OSS code to the project? (maintaining the original license and credits).

**Comment by atacratic** [comment]
My view would be your patch is fine. OK to have the dependency. It shouldn't need much active maintenance. Should be fine to replace it later if there are problems.

Worth testing we can round-trip a text literal containing backslashes, single quotes, double quotes? Round trip meaning pretty print, then reparse the result to get the original term. Made easy in the TermPrinter file in the tests.

**Comment by pete-ts** [comment]
Sidenote: there is an issue with `pending` tests caused by yours truly :disappointed: 
1. There is a comment/test about a the lexer not supporting escaped double quotes. That one is actually passing if I remove the `pending`
2. The same test with single escaped quotes is failing, wrapping in `pending` for now.
2. The icelandic and japanese texts also pass when tested, but the ancient greek not so much. Wrapping these in `pending` for now.

**Comment by pete-ts** [comment]
So if the fix goes ahead in its current form, a new issue is needed for the lexer to be able to keep up?

**Comment by atacratic** [comment]
Do you know of any cases which worked before but don't now?  Assuming not, yes I think just raise a separate ticket to go on the pile for other glitches you've found :-)
