### ISSUE TITLE
move.namespace to a nested target appears to lose data

### ISSUE THREAD

**Issue by pete-ts** [unisonweb/unison#1430]
`move.namespace x x.y` appears to lead to a loss of the namespace `x`.

Unclear if this is affected by relative or absolute paths.
The namespace reappears in the original location after an `undo`.

[gist in lieu of transcript](https://gist.github.com/pete-ts/c2154a2cd52fda58f2786080f68498d6)

**Comment by pchiusano** [comment]
If this happens to you, you can use `reflog` command to go back in time. 

Workaround: to `move.namespace x x.y`, do `move.namespace x .tmp` then `move.namespace .tmp x.y`.

**Comment by aryairani** [comment]
Superseded by #1552
