### ISSUE TITLE
Support addressing git branches / tags / commits?

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1436]
As touched upon [here](https://github.com/unisonweb/unison/issues/1343#issuecomment-614317252), providing support for addressing git branches / tags / commits from within ucm was something I thought was worth implementing.  But it's turned out to be somewhat challenging to do correctly and efficiently, so I'm stubbing it out with an error message that sends people here, for now.

Depending on how important it is to folks (for realistic use cases, not for completeness), we can flesh it out later, or nix it altogether.

**Comment by aryairani** [comment]
Implementation notes for later.

User may request: 
* **the default branch.**  if you need to know it's actual name, you can use something like:
  ```
  git ls-remote --symref <uri>
  ```
  and find the `ref:` where the 3rd column is `HEAD`, e.g.:
  ```
  ref: refs/heads/master	HEAD
  ```
* **some branch head / tag.** identify branch heads / tags with 
  ```bash
  git ls-remote foo://host.com/repo #maybe cached from before? 😃
  ```
  e.g.
  ```
  6b02d69f03d0ee2c9c0d30bdc94b6906b22e5636	refs/heads/fix/missing-spaces
  c469d573548ce2befdd97cba3da1d7ddb4cfd7d7	refs/heads/kindexperiment
  4b20ca776887487a31aee73ac7d644771f51e7e1	refs/heads/master
  939a88f153bbaf81e979c573bdd521ccd297929e	refs/tags/branchful
  6b9a9d505b83b844103c5d404db2fdc7746af3e0	refs/tags/jvm-runtime
  9732cd8a9f1383c68a0d5d18a877fcde80e40af6	refs/tags/release/M1
  6afddb53df1b192ba4f62bf2b976d489590343fb	refs/tags/release/M1a
  ```
  given a valid branch head, I can do a shallow commit; haven't tried for tags.
* **some specific commit.**
  Can't generally fetch a particular commit from a git server, because Security.  Can try iterative deepening (along known branches?) like [Buckaroo](https://github.com/LoopPerfect/buckaroo/wiki/How-to-Fetch-a-Commit), or download a deep clone.

**Comment by aryairani** [comment]
```haskell
-- |returns true if `treeish` is a remote branch or tag
isRemoteBranch :: MonadIO m => CodebasePath -> Text -> m Bool
isRemoteBranch path treeish =
  gitTextIn path ["ls-remote", "-q", "--heads"] <&>
    -- "03359691e15b0b4b419663d860a9cbca5bc98099	refs/heads/topic/List.empty" 
    --  -> "topic/List.empty"
    elem treeish . fmap (last . Text.splitOn "refs/heads/") . Text.lines

--7ec9cf12006d524dba7486af5540d4649ab07c06	refs/heads/IO#fgaevis4bljt5
--5809b219e913d49893383a160f1e2e2a6507d6da	refs/heads/IO#q55hl65t8qk2m
--ca1d639c8bcd7f7ecdd47c4635c723028255cc1a	refs/heads/aryairani-patch-1
--3ffc7dfc9aa7a87f9c97ee0d7769c4725833c7e0	refs/heads/aryairani-patch-2
--5fcae0a9125a81c035ab26221d49840ad3b13d87	refs/heads/master
--149a9afb470e10aa1b04f72af8893a3987f1985c	refs/heads/runarorama-patch-1
--03359691e15b0b4b419663d860a9cbca5bc98099	refs/heads/topic/List.empty
```
🤪

**Comment by aryairani** [comment]
I don't think we're going to do this.

**Comment by ChrisPenner** [comment]
If we eventually support tar-files they could pull the tar file of a given branch I think. You just couldn't push afterwards, but what does it mean to push to a "commit" anyways?

**Comment by aryairani** [comment]
You could pull from a branch, tag, or commit; or push to a branch (only).  Same with Unison namespaces hashes; we can address them in read-only contexts.
