### ISSUE TITLE
missing names in PR

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#1447]
I pull @anovstrup 's [PR](https://github.com/unisonweb/base/issues/23) for adding `Memo` to base, but when I view one of the definitions, `merged.Memo.evalOnce.test`, it takes about 12 seconds to render, and then it's missing some names.

![image](https://user-images.githubusercontent.com/21991324/79800375-01dd6700-8354-11ea-8cc4-b6c2da88ede8.png)

Maybe @anovstrup these were names that didn't get included in your PR somehow?

@aryairani you were planning a fix for that case I think, so names get dragged along into the PR?  I can't remember if that's happened yet or not.  Also I seem to remember reading stuff about slowness from going through all the history - is that a dup of a known issue about rendering things with no name?

Sorry for the spam if this is all known issues.

**Comment by anovstrup** [comment]
My mistake. I mean, maybe the names should be brought in automatically, but I didn't think about the fact that my `Memo` PR is using names from my `Store` PR to implement that test — the missing names are `Store.store`, `Store.modify`, and `Store.get`, respectively.

**Comment by atacratic** [comment]
Ooh, interesting and important use case for ucm to cope with!

**Comment by aryairani** [comment]
Superseded by #1802
