### ISSUE TITLE
State of the Unison

### ISSUE THREAD

**Issue by ts468** [unisonweb/unison#146]
What is the state of the editor of unisonweb?

In particular:
- what are the correct versions of reflex and reflex-dom that should be used?
- is it possible to use the GHC backend of reflex for running the editor?

It seems that the editor got out of sync from the rest of unisonweb and I wondered if someone could maybe help me with running it on the GHC backend of reflex. I tried to fix the editor myself, but although I managed to compile it at some point, it seems to be quite broken, still. Any help would be highly appreciated, and of course I'm happy to create a PR with the changes I tried so far in case that might help.

**Comment by kirbyfan64** [comment]
Should've been titled "State of the **Uni**s**on**"...

**Comment by atacratic** [comment]
This got discussed a few weeks ago at https://gitter.im/unisonweb/unison?at=58c85df800c00c3d4f09e5d4 - but I'm sure Paul would be interested to hear if anyone felt they had substantial time to push the editor on.

**Comment by pchiusano** [comment]
Am closing this, but yes, if someone is willing and able to work on the semantic editor that would be cool and come chat with us in Gitter. My feeling is this should wait until compiler and codebase API is more stable though (in next couple months).
