### ISSUE TITLE
configurator auto-reload not working?

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1474]
I had thought `configurator` was wired up to automatically load changes to the config file:

parser-typechecker/src/Unison/CommandLine/Main.hs
```haskell
    (config, cancelConfig)   <-
      catchIOError (watchConfig configFile) $ \_ ->
        die "Your .unisonConfig could not be loaded. Check that it's correct!"
```
 but this isn't working for me.  i.e. add/remove/change settings in `~/.unisonConfig` while `ucm` is running; it just uses the settings as they were at initial `ucm` launch.

**Comment by runarorama** [comment]
Works here

**Comment by aryairani** [comment]
It works here now too. ¯\_😕_/¯

**Comment by aryairani** [comment]
Possibly related: I guess it only reloads when there's no parse error; if there is, you find out the next time you start ucm.
