### ISSUE TITLE
text based editing interface chokes on non-ASCII characters

### ISSUE THREAD

**Issue by imuli** [unisonweb/unison#148]
The subject kinda covers it, specifically this breaks editing generics.

```sh
; echo 'id x = x' > id.u
; unison add
; unison view id
# id : ∀ v . v -> v
# id x = x
# 
; unison edit id
# unison: 5KPWofXAueZxSD.u: commitBuffer: invalid argument (invalid character)
; cat 5KPWofXAueZxSD.u
# id : 
```

**Comment by imuli** [comment]
This appears to be a locale thing - with a UTF8 locale it works fine, but inside the stack environment it doesn't (possibly due to my using stack --nix). With various combinations I've gotten out a '\0' in place of the '∀' too.

So I guess the question is whether to force everything to UTF8?

**Comment by pchiusano** [comment]
Yeah, am probably doing file I/O with a function that assumes locale
encoding (which may not match what your editor is producing)? It's probably
better to just use UTF8 explicitly (and ideally, bomb with meaningful error
if can detect that encoding is something other than UTF8).

The codebase editing tool is buggy and rough around edges and will probably
be changed substantially / rewritten, so I wouldn't bother with reporting
bugs against it here.

**Comment by imuli** [comment]
Yeah, I sort of came to "not quite time to be working on interface bugs" once I dug a little deeper. Sorry for the noise.

**Comment by pchiusano** [comment]
No problem. 😀
