### ISSUE TITLE
Editing a function defined with function composition renders incorrectly

### ISSUE THREAD

**Issue by symbiont-eric-torreborre** [unisonweb/unison#1482]
I created the following functions
```
plusOne : Nat -> Nat
plusOne n = n + 1

plusTwo : Nat -> Nat
plusTwo = plusOne . plusOne
```
And `add`ed them. Then I tried to `edit` `plusTwo` and got this in my file:
```
plusTwo : Nat -> Nat
plusTwo =  plusOne plusOne
```

The `.` is missing so it does not typecheck anymore.

**Comment by pchiusano** [comment]
@symbiont-eric-torreborre this is an amazing bug, thanks for reporting! I think I know what's going on.

Note to self - the thing that produces suffixed names probably needs a special case if the thing's FQN ends in `..` (like `base..`)

**Comment by atacratic** [comment]
dup of #1063 - close this one?

**Comment by symbiont-eric-torreborre** [comment]
Sure.
