### ISSUE TITLE
Default metadata generates too much history.

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#1486]
If you add a bunch of definitions, with default `Author` and `License` metadata, you get 3 entries in the history:

1. All the terms/types you're adding.
2. All the author links.
3. All the license links.

Would be great if only one history entry were generated on `add`.

**Comment by runarorama** [comment]
I'm happy to provide directions to the relevant parts of the code.

**Comment by mitchellwrosen** [comment]
fixed by #4574
