### ISSUE TITLE
Check that pull verifies hash in destination repo, not source repo

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1491]
It looks from this thread like pull is failing fast when the pull source has a transitive dependency which is not in the pull source repo: https://unisonlanguage.slack.com/archives/CLUNF0J5S/p1588239848027800

But it could probably get away with just verifying that dependency is in the pull destination repo (and ideally notifying the user that the pull source repo has broken links).

@aryairani thought this was already the behavior of pull but seems like maybe not.

**Comment by aryairani** [comment]
Closing as obsolete.
