### ISSUE TITLE
unclear how to link an author on first PR

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#1492]
I've been playing around in Unison, and my experience has been that ramping up on the language has been smooth, but there are barriers to learning the daily workflows. I know that this is very much a work in progress, so I'll try to create helpful issues/PRs as I understand where I'm having trouble.

One issue I'm running into is attaching author metadata to my first `base` PR. The docs suggested the `create.author` command, which worked great. But _using_ the metadata isn't so clear to me.

The [Day-to-day development: creating and merging pull requests](https://www.unisonweb.org/docs/codebase-organization/#day-to-day-development-creating-and-merging-pull-requests) docs don't mention attaching author metadata. But I had seen the [Configuration](https://www.unisonweb.org/docs/configuration) section, so I suspected that this was something that I should do. When I followed these instructions I ran into a couple of questions/issues:

1. I was in a `.prs._myPR` namespace when I ran `create.author` command. Should I do this separately for each project that I work on, or should I have an `author` object somewhere in a common place that I reuse across projects? The docs mention that I can `alias` or `copy` the author object, but I don't know what that would look like.
2. When I follow the instructions on the configuration page and run `add` I get an error message `I couldn't find any metadata matching ._base.trunk.metadata.authors.ceedubs`. I suspect that this is because my `author` metadata isn't actually in `trunk` yet - it only lives in my `.prs._myPR` namespace. Should I be referencing my `.prs._myPR` namespace in my config? Or should I just try to manually link the author object until I exist in `trunk`? When I tried manually linking I had trouble figuring out how to do it.

**Comment by mitchellwrosen** [comment]
fixed in #4574
