### ISSUE TITLE
Updating documentation or other metadata requires tedious unlinking and relinking

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1497]
Currently, if you update a `Doc`, you have to unlink the old documentation and then link the new docs. I think that `update` should just replace linked metadata as well. 

So if `mydocs` is linked to a definition, `foo`, and `mydocs -> mydocs'` is in the patch, then `mydocs` will be unlinked from `foo` and `mydocs'` will be linked to it after the patch is applied.

Suggested workaround for now is to just `unlink` the existing docs (say it's called `foo.mydocs`, do the `update` of it), then `link foo.mydocs foo` the now updated version back in.

Originally I was concerned that this could be a bad idea, but now that I understand patch management better, I think it's the right move.

**Comment by aryairani** [comment]
This makes sense to me.  So given `d -> m`, 
updating `m` yields `d -> m'`
updating `d` yields `d' -> m`
updating `d` and `m` yields `d' -> m'`

**Comment by aryairani** [comment]
Same as #1497

**Comment by pchiusano** [comment]
Rúnar commented that it’s not possible to unlink the old metadata after the update, since it no longer has a name. I’m unsure if that’s still and issue but flagging here to check.

**Comment by ceedubs** [comment]
Fixed by #1853
