### ISSUE TITLE
Inferred abilities can’t be solved to a universal type variable

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1500]
When an unadorned arrow gets inferred, if the type that should be inferred to has universal type variables, the user gets a type error (basically the same error one gets when attempting to instantiate an existential to a universal which appears after it in the context). Moreover it’s a confusing type error.

If the restriction can’t be lifted, a good message might be something like “I tried inferring the ability requirements on this arrow, but couldn’t. Try adding an explicit ability list here.”

**Comment by etorreborre** [comment]
Here is a self-contained example which happened to me while doing the tutorial
```
ability Stream e where
  emit : e ->{Stream e} ()

Stream.range : Nat -> Nat -> {Stream Nat} ()
Stream.range n m =
  if n >= m then ()
  else
    emit n
    Stream.range (n + 1) m

Stream.toList : '{Stream a} () -> [a]
Stream.toList stream =
  h : [a] -> Request {Stream a} () -> [a]
  h acc = cases
    {Stream.emit e -> resume} ->
      handle resume () with h (acc ++ [e])
    {u} -> acc
  handle !stream with h []

ability Ask a where
  ask : a

Ask.provide : a -> '{Ask a,e} r -> '{e} r
Ask.provide a asker =
  h = cases
    {r}                 -> r
    {Ask.ask -> resume} -> (handle resume a with h)
  '(handle !asker with h)

use Ask ask

Stream.pipe : '{Stream a} () -> '{Ask a, Stream b} r -> '{Stream b} ()
Stream.pipe input output _ =
  feed : '{Stream a} () -> Request {Ask a, Stream b} r -> ()
  feed i = cases
    {u} -> ()
    {Ask.ask -> resumeOutput} ->
      handle !i with cases
        {u} -> u
        {Stream.emit a -> resumeInput} ->
          handle resumeOutput a with feed resumeInput
    {Stream.emit b -> k} -> let
      emit b
      handle k () with feed i
  handle !output with feed input

Stream.map : (a -> {}b) -> '{Stream a} () -> '{Stream b} ()
Stream.map f s =
  go : () -> ()
  go _ = let
    emit (f ask)
    !go
  Stream.pipe s go

> Stream.toList (Stream.map (n -> n+1) '(Stream.range 1 11))
```
If the signature of `Stream.map` is set as
```
Stream.map : (a -> {}b) -> '{Stream a} () -> '{Stream b} ()
```
Then the compiler raises an error:
```
I found a value of type a1 where I expected to find one of type a:
  
     47 | Stream.map : (a -> b) -> '{Stream a} () -> '{Stream b} ()
     48 | Stream.map f s =
     49 |   go : () -> ()
     50 |   go _ = let
     51 |     emit (f ask)
  
    from right here:
  
     20 | ability Ask a where
```

**Comment by pchiusano** [comment]
Thanks!

**Comment by pchiusano** [comment]
Note to self: this might be possible to fix, not just give a better error message. Issue is that for a type signature with foralls, like `(a -> b) -> a ->{Store s} b`, the existential ability variables need to be generated _after_ unraveling the forall. If they are generated beforehand, they appear in the context before the universals and can't be solved to any type involving those universals.

**Comment by folkertdev** [comment]
I also ran into this problem while doing the tutorial. It looks like the problem can be fixed by adding an explicit type annotation to the `ask`ed value

```
use .base

ability Stream e where
    emit : e ->{Stream e} ()


ability Ask a where
    ask : a

Ask.provide : a -> '{Ask a} r -> r
Ask.provide a asker =
    h = cases
        {r} -> r
        {Ask.ask -> resume} -> handle resume a with h

    handle !asker with h

Stream.pipe : '{Stream a} r -> '{Ask a, Stream b} r -> '{Stream b} r
Stream.pipe s f _ =
  h inner = cases
    {u} -> u
    {Ask.ask -> resumeF} ->
      handle !inner with cases
        {u} -> u
        {Stream.emit a -> resumeS} ->
          handle resumeF a with h resumeS
    {Stream.emit b -> resumeF} ->
      emit b
      handle resumeF () with h inner
  handle !f with h s


Stream.map : (a -> b) -> '{Stream a} r -> '{Stream b} r
Stream.map f s =
  go _ = 
    -- x : a
    x = ask
    emit (f x)
    !go

  Stream.pipe s go
```
when `x : a`, the program typechecks. When the annotation is commented like above, it gives the weird error message.

**Comment by pchiusano** [comment]
Thinking for a proper fix:

* When you have `Ann e t` where `t` is a `forall`, rather than calling `existentializeArrows` on `t` to generate `t'` and then doing `check e t'`, instead! unravel the forall(s), then call `existentializeArrows`, then do `check e t'`. This might just work.
* Audit all uses of `existentializeArrows` and `existentialFunctionTypeFor`. 

Thinking for generating a better error message:

* The function `existentializeArrows` is used to convert signatures like `(a -> b) -> [a] -> [b]` to `(a ->{e1} b) ->{e2} [a] ->{e3} [b]`, where `e1`, `e2`, `e3` are fresh existentials. Also see `existentialFunctionTypeFor` which serves a similar role for bindings with no annotation (`f x y = ...` with no annotation on `f`).
* Look at the type of variable that's generated by that
* At some point later, there's a type error involving an inference var being compared with a universal var.
* Thinking: add a `AbilityInferenceFailure` case to `Unison.Typechecker.TypeError`, and then write an extractor following the example in that file (maybe `BooleanMismatch` for example), then add to the the `allErrors` list.
* Then go update `PrintError` to generate a nice message for this new failure type.

When you generate a typechecking error, you call `failWith`, which just takes a `Context.Cause`. The typechecker will fail with - 

```
data ErrorNote v loc = ErrorNote {
  cause :: Cause v loc,
  path :: Seq (PathElement v loc)
} deriving Show
``` 

Where the `path` is a stack of stuff that says what the typechecker was doing when it failed.
