### ISSUE TITLE
view.patch is really slow

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#1504]
Possibly related to #1487

**Comment by atacratic** [comment]
I just hit this too - `view.patch` took about 30 seconds.  You can reproduce it using the codebase attached to https://github.com/unisonweb/unison/issues/1509, and doing `view.patch` from under `.prs.base2._foo`

Incidentally the view.patch output when it came was as follows.

```
.prs.base2._foo> view.patch

  Edited Terms:
    ##List.empty                                                 -> List.empty
    ._1e7.external.unison_random_mersenne.v1._base_additions.any -> List.any
    ._1e7.external.unison_random_mersenne.v1._base_additions.all -> List.all
  
  Tip: To remove entries from a patch, use delete.term-replacement or delete.type-replacement, as
       appropriate.

```

**Comment by aryairani** [comment]
Is this still slow, with the recent caching?  Although we will want to reevaluate if we try to do something simpler than caching, for memory-conservation purposes.

**Comment by runarorama** [comment]
Yes, still slow.

**Comment by aryairani** [comment]
Bummer, ok.

**Comment by aryairani** [comment]
Closing for now, see #2128
