### ISSUE TITLE
In docs, when @[source] and @[evaluate] yield multiline results, only the first line keeps its indenting

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#1510]
When displaying multiline spliced elements in docs, the indenting present for the splice directive should be applied to the element being spliced in.

It's important that people can indent these directives - if they can't, it gets treated as prose and line-wrapped which is usually not what you want.

Example...

```haskell
d = [: My doc.

Here's some code.

    @[source] List.filter

    @[source] List.init

All done.

:]
```

Gets rendered as

```
  My doc.
  
  Here's some code.
  
      ._base.releases._M1j.List.filter pred as =
    List.foldl (acc a -> (if pred a then acc :+ a else acc)) [] as
  
      ._base.releases._M1j.List.init = cases
    []      -> []
    xs :+ _ -> xs
  
  All done.

```

But we want the function bodies to be indented more.  

I'll get to fixing this at some point, hopefully soon, as it's already annoyed a couple of people on the slack.

**Comment by aryairani** [comment]
Do you mean that a parsing enhancement is needed to be able to support this in the pretty-printer?

**Comment by atacratic** [comment]
It's the function that implements `display` for docs that needs a tweak I reckon. The pretty printer ( i.e. `view`) is fine, because it's not doing the expansion of splices.

**Comment by atacratic** [comment]
oops, dup of #1256
