### ISSUE TITLE
Slow push with oldish codebase

### ISSUE THREAD

**Issue by bascott** [unisonweb/unison#1512]
Attempting to push the codebase I've attached to this issue seems to cause a memory leak. Issue solved by reinitializing codebase.
[codebase.tar.gz](https://github.com/unisonweb/unison/files/4569456/codebase.tar.gz)

**Comment by aryairani** [comment]
I'm able to reproduce this here, pushing to a local git repo; thanks for reporting.  I haven't looked into the cause yet.

**Comment by aryairani** [comment]
After a long warmup, I see a message `  Staging files for upload to test.git ...`.  However, I don't see any files actually being staged, in `~/.cache/unisonlanguage/gitfiles/test.git` where I would expect them.

**Comment by aryairani** [comment]
@bascott With our new sync implementation, your codebase should push in about 20s.

A separate issue is that your codebase is missing 6 term definitions, I just wanted to record it here until I have a chance to dig into it further.
```
MissingTerm #dk56i -- old doc for Optional.isSome
MissingTerm #fm4rr
MissingTerm #gvvm0 -- old doc for Optional.isNone.
MissingTerm #h83dg
MissingTerm #kccnr
MissingTerm #ucsc8
```
