### ISSUE TITLE
impossible to reference symboly ids in Doc

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1518]
```ucm
    .> alias.term ##Nat.+ Nat.+
    .> alias.term ##Nat.+ Nat.plus
    ```
    ```unison
    docs.plus = [: @Nat.plus very useful for adding. :]
    ```
    ```unison
    docs.+ = [: @Nat.+ is not as useful. :]
    ```

```
scratch.u:1:1:
unexpected docs.+
expecting ability, type, or use
    1 | docs.+ = [: @Nat.+ is not as useful. :]
```

**Comment by sellout** [comment]
This is a Doc _v1_ issue. Doc v2 has a different syntax and it works for these. Even if we revert to `[:``:]` for Doc delimiters, I believe we’d still use the Doc v2 parser. So, can this be considered obsolete (or do we need to remove Doc v1 from Unison before we do so)?

**Comment by mitchellwrosen** [comment]
About removing v1 docs from the parser: I have a WIP branch, I or someone else just needs to finish porting over the transcripts that show off v1 doc features.

Since we don't care about the v1 doc syntax anymore, I think this issue can be closed.

**Comment by sellout** [comment]
Great. Closing due to #5116.
