### ISSUE TITLE
it would be handy if you could type things like `view 1-5,9` or `view 1-5,9-12`

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#1524]
`ucm` numbers the terms/types listed in (much of) its output.  It lets you feed those numbers into further commands, e.g. `view 1-5`, which is very useful.

It would be great if this worked in a general way, even for non-contiguous sets of indices.  For example `view 1-5,9` or `view 1-5,9-12`.

**Comment by pchiusano** [comment]
You can, just use spaces instead of the commas :)

**Comment by pchiusano** [comment]
Example: view 1-7 9-22

**Comment by atacratic** [comment]
d'oh :smile:
