### ISSUE TITLE
`dependents` includes deleted names

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#1525]
Transcript (input):
```
    ```unison
    a = 1
    b = a
    ```

    ```ucm
    .> add
    .> names b
    .> delete.term b
    .> ls
    .> dependents a
    ```

    Problem: `dependents a` still lists b by both name and hash, 
    even though the name is deleted, and without flagging that b is gone.
```

The output of the final command is
```

  Dependents of #jk19sm5bf8:
  
    Reference     Name
    #51ahuj5sm6   b
```
[transcript-and-output.zip](https://github.com/unisonweb/unison/files/4571780/transcript-and-output.zip)
master@6a36f1c

Arya's comment via slack: "we’ll have to think a little bit about what it means for something to be deleted, since it could still be referenced historically, but, I don’t think there’s any reason not to note that it’s deleted"

**Comment by aryairani** [comment]
It would probably be easy to just put `(deleted)` next to the name.

**Comment by aryairani** [comment]
Not sure what I was on about; `dependents` should only show dependents that exist in the most recent root namespace.  Some future command like `dependents.all` or `dependents.historical` could list more, but let's not tackle that here.
