### ISSUE TITLE
simplify diff.namespace with current namespace as "after"

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#1531]
## motivation

Almost every time that I run `diff.namespace before after` I want to use the current namespace as `after`. I think that it would be nice to have a concise way to do this.

possibly related: #1515 

## proposal 1: default `after` to current namespace

This would be similar to `git` diffs. If you run `.prs._myPR> diff.namespace ._base.trunk` it would be equivalent to `.prs._myPR> diff.namespace ._base.trunk .prs._myPR`.

### pros

* familiar to people with git experience
* probably usually the thing that you want
* aligns with `merge` command behavior

### cons

* probably causes a mess if it's _not_ what you want
* default arguments can be confusing and error-prone (if I only provide one arg, is it `before` or `after`?)
* git maybe isn't the best reference for how to make an intuitive UI
* doesn't generalize beyond `diff.namespace` (see proposal 2)

## proposal 2: keyword for current namespace

If there were a shortcut for the current namespace, one could run `prs._myPR> diff.namespace ._base.trunk <shortcut>`.

Since `ucm` is a command-line tool, and `cd .prs._myPR` can be used to switch to the `.prs._myPR` namespace, someone with experience in Unix/Linux could reasonably expect `.` to be a reference to the current namespace, and that `prs._myPR> diff.namespace ._base.trunk .` would do what they wanted. Unfortunately, in Unison `.` refers to the root namespace.

### pros

* could be generally useful for other commands, such as `pull`
* avoids confusion with default arguments

### cons

* Finding the right shortcut could be tricky. It should be short but not conflict with `.` or namespace names that might reasonably be used.
* magic nature of this shortcut could throw off beginners

**Comment by anovstrup** [comment]
Related: when preparing a PR that just adds definitions, I use diff.namespace to compare my current namespace with an empty namespace: `diff.namespace .z .current.namespace`. Maybe `diff.namespace` (without arguments) could be a shortcut for this?

**Comment by aryairani** [comment]
Aside: @anovstrup (or anyone) Do you remember if there was already a ticket similar to proposal 1?

**Comment by anovstrup** [comment]
I don't recall one.

**Comment by sullyj3** [comment]
+1, I just came here looking for this exact ticket
