### ISSUE TITLE
Slowness with push / pull / merge and related commands

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1535]
As the base library has gotten larger, we've started to notice serious slowness with `push`, `pull`, `merge`, and related commands like `pr.create` and `pr.load` that are defined in terms of them. These commands should take in the 5-20s range, not minutes. This ticket tracks work we are doing to track down what's slow and come up with fixes.

Related tickets: #1276

* Phases of a pull:
  * __Git fetch:__ Git operation to fetch the latest commit of the remote
  * __Sync:__ Copy definitions that are present in the source namespace but not present in the destination namespace.
  * __Merge:__ Merge of the source namespace and the destination namespace (this calls `Causal.before`)
  * Anything else??
* Phases of a push:
  * __Git fetch:__ Git operation to fetch the latest commit of the remote (note: this is the same as a `pull`)
  * __Merge:__ Merge the source namespace and destination namespace. (this calls `Causal.before`)
  * __Git fetch:__ Apart from a round-trip over the network to the remote git server, this should be a no-op if there are no new commits on the remote since the previous __Git fetch__.
  * __Verify fast-forward:__ Reject unless it's a fast forward (calls `Causal.before` to check).
  * __Sync:__ Copy definitions that are present in the source namespace but not present in the destination namespace.
  * __Git push:__ Git operation to add a local commit and push it to the remote repo.

__Scenarios:__

1. `.> pull git@github.com:unisonweb/base:.trunk base` on an empty repo
2. `.> pull git@github.com:unisonweb/base:.trunk base2` on the same repo as 1
3. Some stuff 

__Results:__

### `.> pull <base> .base` in empty repo

__base git commit 245f053, 3/11/2020__

|base git commit       |245f053|CFI|3c928b7|CFI|
|--------              | ----- |---|------ |---|
|**date**              |**11-Mar**           ||**06-May**   ||
|branchFromFiles       | 0.03s / 0.03s       |0.03s|1.3s / 1.45s ||
|syncFromDirectory     | 4.2s / 4.34s        |0.15s|343s / 421s  ||
| --- LoadDependentsDir |                    |0.02s|343s / 421s  ||
| --- CopyTransitiveDeps|                    |0.00s|343s / 421s  ||
| --- Copy Dependents Index|                 |0.00s|343s / 421s  ||
| --- Copy Type Index   |                    |0.03s|343s / 421s  ||
| --- Copy Type Mentions|                    |0.09s|343s / 421s  ||
|merge branch           | 0.42s / 1.61s      |0.00s|4.5s / 38.66s||
|propagate default patch | 0.0075s / 0.0075 || .78s / 1.06s||

### `.> pull <base> .base2` in same (now non-empty) repo

|base git commit      | 245f053       |3c928b7       |
|--------             | ------------- |------------  |
|**date**             | **11-Mar**    |**06-May**    |
|branchFromFiles      | 0.03s / 0.03s |1.53s / 1.82s |
|syncFromDirectory    | 0.00s / 0.00s |0.00s / 0.00s |
|merge branch         | 0.39s / 1.03s |3.0s  / 4.35s |
|propagate default patch | 0.002s / 0.002s | 0.45s / 0.45s|

It's interesting that just `branchFromFiles` is so slow. Why is that?

* Do some sharing of the sub-branches
* Is the slowness just linear slowdown because we're loading 50x more branch files? We think yes, just because lots of tests and docs were added, and new definitions with docs and tests nested underneath.
* Idea: try the other syncing method (would improve the syncFromDirectory phase)
* Idea: load the sub-branch directly, rather than loading the root (would improve branchFromFiles a bit)
* Idea: keep a namespace cache, keyed by hash, use it to preserve sharing (may help with branchFromFiles)
  * `Util.cache :: (MonadIO m, Ord k) => k -> m v -> m (k -> m v)`, just use this in a few places in `FileCodebase`. For implementation, either a `TVar (Map k v)` or the [concurrent map from `stm-containers`](https://hackage.haskell.org/package/stm-containers-1.1.0.4/docs/StmContainers-Map.html).
  * Next step may be to prepopulate this cache in the background.
* Idea: in the code that syncs a namespace, are we avoiding visiting the same namespace twice? When crawling through history, the same namespace may occur many times.
* Idea: in `Causal`, put elements in `m e` rather than `e`. It's kind of a big refactor (or maybe not?)
  * Along same lines, load a `Causal m ()`, store that in the `Branch` as well, various operations on `Branch` could use the `Causal m ()` spine instead.
* Idea: have a starter Unison repo that includes base and that UCM can just install directly when it first starts up on a fresh codebase. When it does this, it's just a straight file copy into the codebase being initialized. Avoids the many minute "fresh base pull" slowness.
  * The starter repo could also have the recommended namespace setup.
* Idea: Implement archived namespaces

### Raw results

```
.> pull https://github.com/aryairani/base-fork .base
Finished Git fetch in 0.00608s (cpu), 0.481169s (system)            
Finished FileCodebase.Common.branchFromFiles in 0.033558s (cpu), 0.034246s (system)
Finished FileCodebase.Common.getRootBranch in 0.033868s (cpu), 0.034554s (system)
Finished Git fetch (sbh) in 0.0339s (cpu), 0.034587s (system)
Finished SyncFromDirectory in 4.210363s (cpu), 4.340794s (system)
Finished Merge Branch in 0.424144s (cpu), 1.616646s (system)
Finished Propagate Default Patch in 0.0075s (cpu), 0.00751s (system)

.> pull https://github.com/aryairani/base-fork .base2
Finished Git fetch in 0.005311s (cpu), 0.496279s (system)           
Finished FileCodebase.Common.branchFromFiles in 0.033443s (cpu), 0.033981s (system)
Finished FileCodebase.Common.getRootBranch in 0.03375s (cpu), 0.034285s (system)
Finished Git fetch (sbh) in 0.033784s (cpu), 0.03432s (system)
Finished SyncFromDirectory in 0.000128s (cpu), 0.000144s (system)
Finished Merge Branch in 0.39215s (cpu), 1.026571s (system)
Finished Propagate Default Patch in 0.001895s (cpu), 0.001891s (system)
```

pulling master
```
.> pull https://github.com/unisonweb/base .base
Timing Git fetch...
Finished Git fetch in 0.007145s (cpu), 1.50681s (system)       
Timing Git fetch (sbh)...
Timing FileCodebase.Common.getRootBranch...
Timing FileCodebase.Common.branchFromFiles...
Finished FileCodebase.Common.branchFromFiles in 1.291687s (cpu), 1.45078s (system)
Finished FileCodebase.Common.getRootBranch in 1.29208s (cpu), 1.451172s (system)
Finished Git fetch (sbh) in 1.292109s (cpu), 1.4512s (system)
Timing SyncFromDirectory...s into local codebase...
Finished SyncFromDirectory in 343.271177s (cpu), 421.425816s (system)
Timing Merge Branch...                             
Finished Merge Branch in 4.577604s (cpu), 38.657448s (system)
Timing Propagate Default Patch...
Finished Propagate Default Patch in 0.780459s (cpu), 1.062506s (system)
.> pull https://github.com/unisonweb/base .base2
Timing Git fetch...
Finished Git fetch in 0.007562s (cpu), 1.806194s (system)      
Timing Git fetch (sbh)...
Timing FileCodebase.Common.getRootBranch...
Timing FileCodebase.Common.branchFromFiles...
Finished FileCodebase.Common.branchFromFiles in 1.530779s (cpu), 1.823564s (system)
Finished FileCodebase.Common.getRootBranch in 1.531172s (cpu), 1.823964s (system)
Finished Git fetch (sbh) in 1.531204s (cpu), 1.823994s (system)
Timing SyncFromDirectory...s into local codebase...
Finished SyncFromDirectory in 0.000127s (cpu), 0.000133s (system)
Timing Merge Branch...                             
Finished Merge Branch in 3.000088s (cpu), 4.35114s (system)
Timing Propagate Default Patch...
Finished Propagate Default Patch in 0.448015s (cpu), 0.452972s (system)

```

### Raw Results, with CopyFilterIndex sync
base as of march
```
Timing FileCodebase.Common.getRootBranch...
Timing FileCodebase.Common.branchFromFiles...
Finished FileCodebase.Common.branchFromFiles in 0.000332s (cpu), 0.000337s (system)
Finished FileCodebase.Common.getRootBranch in 0.000878s (cpu), 0.000894s (system)
⚙️   Processing stanza 1 of 1.Timing Git fetch...
Finished Git fetch in 0.007285s (cpu), 2.045757s (system)           
Timing Git fetch (sbh)...
Timing FileCodebase.Common.getRootBranch...
Timing FileCodebase.Common.branchFromFiles...
Finished FileCodebase.Common.branchFromFiles in 0.033141s (cpu), 0.078254s (system)
Finished FileCodebase.Common.getRootBranch in 0.033336s (cpu), 0.078448s (system)
Finished Git fetch (sbh) in 0.033357s (cpu), 0.078472s (system)
Timing SyncFromDirectory...s into local codebase...
Timing Load Dependents Dir...
Finished Load Dependents Dir in 0.023473s (cpu), 0.023509s (system)
Timing Copy Transitive Dependencies...
Finished Copy Transitive Dependencies in 0.000043s (cpu), 0.000044s (system)
Timing Copy Dependents Index...
Finished Copy Dependents Index in 0.000077s (cpu), 0.000078s (system)
Timing Copy Type Index...
Finished Copy Type Index in 0.032337s (cpu), 0.032429s (system)
Timing Copy Type Mentions Index...
Finished Copy Type Mentions Index in 0.090889s (cpu), 0.091452s (system)
Finished SyncFromDirectory in 0.147237s (cpu), 0.147935s (system)
Timing Merge Branch...                             
Finished Merge Branch in 0.000224s (cpu), 0.000222s (system)
Timing Git fetch...
Finished Git fetch in 0.004898s (cpu), 0.593304s (system)           
Timing Git fetch (sbh)...
Timing FileCodebase.Common.getRootBranch...
Timing FileCodebase.Common.branchFromFiles...
Finished FileCodebase.Common.branchFromFiles in 0.030922s (cpu), 0.031982s (system)
Finished FileCodebase.Common.getRootBranch in 0.031356s (cpu), 0.03241s (system)
Finished Git fetch (sbh) in 0.031392s (cpu), 0.032447s (system)
Timing SyncFromDirectory...s into local codebase...
Timing Load Dependents Dir...
Finished Load Dependents Dir in 0.046921s (cpu), 0.049333s (system)
Timing Copy Transitive Dependencies...
Finished Copy Transitive Dependencies in 0.000028s (cpu), 0.000031s (system)
Timing Copy Dependents Index...
Finished Copy Dependents Index in 0.000181s (cpu), 0.000203s (system)
Timing Copy Type Index...
Finished Copy Type Index in 0.049949s (cpu), 0.050617s (system)
Timing Copy Type Mentions Index...
Finished Copy Type Mentions Index in 0.133033s (cpu), 0.138627s (system)
Finished SyncFromDirectory in 0.230755s (cpu), 0.239438s (system)
Timing Merge Branch...                             
Finished Merge Branch in 0.000165s (cpu), 0.000163s (system)
```

Misc notes:

* Git shallow (`--depth 1`) clone of base takes about 2-3 seconds

Speculation of possible issues:

* Traversing codebase structure and reserializing
* `Causal.before` was super inefficient — have a patch in \<branch TBD\>.
* `Causal.merge`'s use of `before a b` followed by `before b a`, is inefficient; it would be good to pursue both tests fairly, in parallel — maybe LCA provides exactly that?
  * Say you are computing `merge a b`. If:
    * `lca a b == a` then merge result is `b`
    * `lca a b == b` then merge result is `a`
    * `lca a@(merge [a1,a2]) b@(merge [a1,a2,a3])`  will be `a1` or `a2`, so it's not equal to `a`, even though `before a b` is true here.
    * What if LCA returns a set of LCAs, all at the same path length? Then before just checks that...
    * Seems like need n-way merge
    * Laws for merge:
      * `before a (merge a b)`
      * `before b (merge a b)`
    * Given `merge a@(merge [a1,a2]) b@(merge [a1,a2,a3])`, could produce:
      * `merge [a1,a2,a3]` (basically, `b`)
      * `merge [a1,a2,a3,a]` (make `a` an ancestor of the new merge node)
      * `merge [a1,a2,b]` (make `b` an ancestor of the new merge node)
      * `merge [a,b]` (make `a` and `b` ancestors of a new merge node)
* Deserializing

**Comment by aryairani** [comment]
Here's the one I'm trying to benchmark with:
    ```ucm
    ._prs> pull-request.load https://github.com/unisonweb/base:#ts55p9js2a.trunk https://github.com/zenhack/base-1:#o15u21qkp.prs.base._ascii
    ._prs> fork base merge2
    ._prs> merge head merge2
    ```

**Comment by pchiusano** [comment]
Some numbers from this transcript, which takes about 15-20s to sync, and which we're using for profiling:

    ```ucm
    .> pull git@github.com:unisonweb/base:#ba4oq97j8u .base.List
    ```

There's 3 different syncing methods, we tested them all (see `log-timing` branch, which we added some additional tracing to). We also inspected the Reserialize syncing to make sure it wasn't duplicating work. Here's the numbers:

* Reserialize: 15s
* CopyFilterIndex: 18s
* CopyRegenerateIndex: 17.395401s

Unless CopyFilter/RegenerateIndex are doing something silly, this tells us that serializing, deserializing, and I/O of writing the terms is not the bottleneck. Also, since CopyFilterIndex and CopyRegenerateIndex are not serializing branch files, that is also not the bottleneck.

An old version of base completes the pull faster, but runtime seems to be scaling linearly with the amount of info that needs to be copied. It does not seem to be the case that there is something weird about recent base compared to old base, just that there is more of it. Here's a transcript to pull an old version of base, this took about 5s.

    .> pull git@github.com:unisonweb/base:#9fmbsss .base

### What could be the bottleneck?

- Deserializing branch files:
  - Might be helped by adding the caching
  - Might be helped by being lazier
- Building the in-memory structure of a `Branch`, like `Star3` stuff, relations, etc (possibly deepTerms/deepTypes is getting computed even though we don't need it), also would be helped by caching
  - Might be helped by deserializing into some other structure - all that we need from the branch for push / pull is its list of dependencies, its list of child namespace hashes, and its list of ancestor hashes
- If the work is I/O bound, we can do some threading
- Possible memory leak, leading to swapping #1512
- Other ideas?

Todo:

- [ ] Verify that CopyFilterIndex and CopyRegenerateIndex are not serializing branches, only copying files
- [ ] Verify that CopyFilterIndex and CopyRegenerateIndex are not doing something silly

```
-- Something to try later
-- ._prs> pull-request.load https://github.com/unisonweb/base:#ts55p9js2a.trunk https://github.com/zenhack/base-1:#o15u21qkp.prs.base._ascii
```

**Comment by aryairani** [comment]
I ran a comparison between Reserialize and the bfs sync (SlimCopyRegenerateIndex) on

    ```ucm
    .> pull git@github.com:unisonweb/base:#ba4oq97j8u .base.List
    ```

Reserialize: 19.1s, 21.7s, 22.9s
BFS + Regenerate: 5.4s, 5.0s, 5.1s

**Comment by aryairani** [comment]
I ran some 

# digitalocean ubuntu-m-2vcpu-16gb-nyc3

## pull https://github.com/unisonweb/base:#6cpa1csq7g _base

| branch| samples | mean | stddev|
| ------------ |---|-----|-----|
| `log-timing` | err | err | err |
| `topic/filecodebase-cache` | 5 | 47.79s | 0.17s |
| `topic/bfs-sync-warn-missing` | 5 | 20.87s | 0.64s |

`log-timing` bombs with a "ghc bug"  on this transcript when it exhausts ram on the no-swap linux machine; I tried running it with `+RTS -M14G`; it's been half an hour and hasn't completed yet.

## .> pull git@github.com:unisonweb/base:#ba4oq97j8u .base.List

| branch| samples | mean | stddev|
| ------------ |---|-----|-----|
| `log-timing` | 5 | 10.18s | 0.09s |
| `topic/filecodebase-cache` | 5 | 6.64s | 0.00s |
| `topic/bfs-sync-warn-missing` | 5 | 2.68s | 0.03s |

**Comment by pchiusano** [comment]
Okay, nice work everyone, this is in much better shape after #1549 #1545 #1548

A common workflow of pulling some branches and doing some merges (transcript below) is ~ 14.7x faster than before. All of base and its history can be pulled into an empty repo in ~20-30s which can probably be improved further, but this only needs doing once, then subsequent pulls are faster.

__New stuff:__

Total time: 7.75s wall clock

* Sync 1: 4.2s
* Pull merge 1: .14s
  * Pull propagate 1: .31s 
* Sync 2: 0s
* Pull merge 2: .09s
  * Pull propagate 2: .20s 
* Merge branch 1: .29s
  * Propagate: .02s
* Merge branch 2: .01s 
  * Propagate: .02s

__Old stuff:__

Total time: 114.05s

* Sync 1: 26.92s
* Pull merge 1: .19s
  * Pull propagate 1: .32s 
* Sync 2: 0s
* Pull merge 2: .18s
  * Pull propagate 2: .12s 
* Merge branch 1: 41.88s
  * Propagate: .02s
* Merge branch 2: 42.11s 
  * Propagate: .02s

Here's the transcript used for these numbers: 

```ucm
.> pull git@github.com:unisonweb/base:#u86hp5f086 .newbase
.> pull git@github.com:unisonweb/base:#trpm76pe0i .oldbase
.> fork newbase newbase2
.> fork oldbase oldbase2
.> merge newbase oldbase
.> merge newbase2 oldbase2
```

/cc @aryairani @runarorama @emiflake @ceedubs @zenhack @bascott
