### ISSUE TITLE
Unexpected <outdent> on a printed signature with ∀ ()

### ISSUE THREAD

**Issue by thoradam** [unisonweb/unison#1538]
Save file with
```
foo = '1
```
do `add` and then `edit foo` and get:
```
foo : ∀ (). () -> Nat
foo = '1
```
resaving now gives:
```
  /Users/thoradam/Code/u/scratch.u:1:10:
  unexpected <outdent>
      1 | foo : ∀ (). () -> Nat
```
where the closing paren after the forall is highlighted.

**Comment by atacratic** [comment]
Annoying isn't it? :face_with_head_bandage:  Good ticket, but let's treat it as a dup of #689 ?

**Comment by thoradam** [comment]
Ah sorry yeah, I searched but didn't find that one ^_^
