### ISSUE TITLE
transcript.fork seems to have stopped working for me on linux

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#1541]
I run `stack exec unison -- transcript.fork make-test.md` and I get the following error...

```
chris@chris-thinkpad:~/unison$ stack exec unison -- transcript.fork make-test.md 

  Transcript will be run on a copy of the codebase at:
  
    /home/chris

unison: /home/chris/.dbus: getDirectoryContents:openDirStream: permission denied (Permission denied)
```

I _think_ this used to work for me?

**Comment by aryairani** [comment]
If you feel up to it, could you double-check that `transcript.fork` isn't trying to copy your whole home directory?  Possibly related to #1113.

**Comment by atacratic** [comment]
Ah, yes, it is trying to copy my whole home directory.  

It starts that process by `stat`ing every file in every immediate subdirectory (and chokes on a permission denied when it tries subdirectory ~/.dbus.)

snippet of strace output:

```
write(4, "\n  Transcript will be run on a c"..., 79) = 79
close(4)                                = 0
wait4(14823, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 14823
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=14823, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
mkdir("/home/chris/unison/transcript-fd50eb6e23b53bee", 0777) = -1 EEXIST (File exists)
stat("/home/chris/unison/transcript-fd50eb6e23b53bee", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/home/chris", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
fstat(3, {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
getdents(3, /* 95 entries */, 32768)    = 3160
getdents(3, /* 0 entries */, 32768)     = 0
close(3)                                = 0
stat("/home/chris/lamdu-0.7.1-release", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
... many more iterations of openat/fstat/getdents/close/stat follow...
```

The trace confirms that 'path' [here](https://github.com/unisonweb/unison/blob/7f6a3cc0f09fc46b127e70c8a28b862f8274e26c/parser-typechecker/unison/Main.hs#L184) is `/home/chris`, i.e. my home directory, rather than `/home/chris/.unison`, which I guess is the problem.

(One interesting thing in the trace snippet above is that `/home/chris/unison/transcript-fd50eb6e23b53bee` already exists.  [createTempDirectory](http://hackage.haskell.org/package/temporary-1.3/docs/src/System.IO.Temp.html#createTempDirectory) is trying to use a random number, and the internet claims that the haskell runtime seeds the global RNG from the clock or a hardware RNG on each run, and I can't see anything in the unison codebase that is reseeding here.  So why the same value each time?)

**Comment by aryairani** [comment]
@atacratic Oh no, okay.  This is probably a regression introduced in #1317 and needs a fix similar to #1422. The call in `unison/Main.hs` to 
```haskell
Path.copyDir path tmp
```
needs to change to
```haskell
Path.copyDir (path </> codebasePath) (tmp </> codebasePath)
```
or a version of that won't crash, if this one does.

Not sure what would be causing the `createTempDirectory` issue though.  There is some `srand`-type stuff that happens in the transcript runner, but I wouldn't think it could affect this.

**Comment by ceedubs** [comment]
I'm running into a similar issue on Mac OS. It looks like it's trying to copy my `.Trash` directory and is hitting a permissions issue.

```
  Transcript will be run on a copy of the codebase at:                                                                                                                               
                                                                                                                                                                                     
    /Users/cody                                                                                                                                                                      

ucm: /Users/cody/.Trash: getDirectoryContents:openDirStream: permission denied (Operation not permitted)
```

**Comment by aryairani** [comment]
If anyone has some time to implement the fix in my previous message, I'd be happy to have it :)

**Comment by ceedubs** [comment]
I'm hoping to be able to give it a try in the next couple of days.
