### ISSUE TITLE
Question about hashing

### ISSUE THREAD

**Issue by chrisdone** [unisonweb/unison#1544]
What's your plan for hashing with respect to versions of the AST?

For example if I've parsed my text code and hashed it with unison, then later, unison changes its internal AST shape, in some small way, in its Haskell code, so that the same code I wrote in the past now hashes to something else.

Do we just say "it's fine that there are two copies of the same code with different hashes?" That seems like an acceptable answer, just curious. Maybe you have some "defenses" against AST changes that are hash-applicable.

**Comment by runarorama** [comment]
> Do we just say "it's fine that there are two copies of the same code with different hashes?" 

I think it's basically that. Although the way to look at this isn't that there are two copies of the same code with different hashes, but that there's a definition that happens to have the same input form (or "source code") in one version of Unison as a different definition in another version of Unison.

It's important to note that the textual input form of your code is not the source of truth, but merely a user interface, so the fact that the source-to-AST transformation is different between versions of Unison is totally fine.

In fact, we've already run into this, where we changed the parser or the AST in some small way between alpha releases of Unison.
