### ISSUE TITLE
pull base.trunk into _base hangs

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#1546]
Is pulling the latest `trunk` of `base` working for others? I have tried this on two separate computers (both Macbooks on Catalina, but this worked on both of them last week), and have even completely removed the `.unison` directory first in case I had some bad state.

```
❯ rm -rf ~/.unison

~
❯ ucm version
ucm version: release/M1l

~
❯ ucm
No codebase exists in /Users/cody.allen
Run `ucm -codebase /Users/cody.allen init` to create one, then try again!

~
❯ ucm -codebase /Users/cody.allen init
Initializing a new codebase in: /Users/cody.allen

~
❯ ucm

   _____     _             
  |  |  |___|_|___ ___ ___ 
  |  |  |   | |_ -| . |   |
  |_____|_|_|_|___|___|_|_|
  
  Welcome to Unison!
  
  I'm currently watching for changes to .u files under ~
  
  Type help to get help. 😎
  
  Enter pull https://github.com/unisonweb/base:.releases._M1l .base to set up the default base
  library. 🏗

.> pull git@github.com:unisonweb/base:.trunk _base
  Importing downloaded files into local codebase...
```

Pulling the git repo works (fairly quickly), but then it seems to indefinitely stay on `Importing downloaded files into local codebase...`. I've let it go for about 10 minutes, and I don't see any signs of progress. During this time it's using pretty significant CPU and memory resources (though not fully pegged).

**Comment by aryairani** [comment]
@ceedubs Sorry, no, it isn't currently working for anyone; we are actively working on a fix though.

**Comment by aryairani** [comment]
@ceedubs `base` has grown to the point where the algorithm in `ucm` can't handle it, so we are reworking it.

**Comment by ceedubs** [comment]
@aryairani no problem thanks for the quick response.

**Comment by ceedubs** [comment]
@aryairani one thought: are you confident that the problem is that it's grown too much? It's strange to me that this took hardly any time for me last week but seems to hang indefinitely now. It made me wonder if it's possible that there's somehow aliasing that has resulted in an infinite loop or something. I know pretty much nothing about how ucm works so probably ignore me, but I just didn't want you all to feel the need to rewrite the whole algorithm if there's something simpler going wrong :)

**Comment by aryairani** [comment]
@ceedubs I had my doubts too, and I'm still not totally sure (though it has grown in terms of number of files to the extent we felt it was plausible), but the "fix" is "almost" done, so we will know more soon :D
