### ISSUE TITLE
Integrate new runtime into UCM

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1559]
Now that @dolio is getting to a good point with the new runtime work, we think we're ready to start trying to integrate it into UCM. I am excited about this. :) :) The hope is that this should be pretty painless since we've planned ahead by having a reasonable `Runtime` interface that can be swapped out for a new implementation. First, let's take a look at that:

https://github.com/unisonweb/unison/blob/master/parser-typechecker/src/Unison/Codebase/Runtime.hs#L26-L36

- [x] @dolio provide an implementation of this interface, might look like `someParams -> IO (Runtime Symbol)` 

Some interesting things that may come up here: this interface demands that the resulting value be decompiled, as that is how watch expressions currently work. @dolio and I have discussed that decompilation of functions / closures doesn't need to be pretty or closely mirror the original source, it just has to be a valid definition.

Also the implementations of `Universal.==`, `Universal.<` etc could be interesting and there may be design questions here. 

Next up is plumbing this through UCM such that it can be. We'd like to keep the old runtime around and be able to switch between runtimes... at runtime.

- [ ] Add a command line flag to UCM, maybe `-runtime2`, to select the new runtime
- [ ] Add a command line flag to the `tests` executable to select the new runtime for testing

_At this point, we can test out pure watch expressions that don't do IO._ The existing test suite should now be runnable (it doesn't use `IO`). This is a big milestone.

- [ ] Get `stack exec tests` working with new runtime

Next up is hooking up the new IO to the typechecker and to the `run` command.

To make the new `IO` type-checkable:

- [ ] Add `IO` as a builtin type: https://github.com/unisonweb/unison/blob/master/parser-typechecker/src/Unison/Builtin.hs#L150-L164
- [ ] Add type signatures for all `IO` functions here: https://github.com/unisonweb/unison/blob/master/parser-typechecker/src/Unison/Builtin.hs#L227 

Loose ends which @aryairani will be able to help figure out how to handle:

- [ ] The old runtime calls a horrible function, `makeSelfContained` which produces a self-contained monolithic term (the new runtime shouldn't have to do this, and can just load cached compiled forms directly and reference them). I'd grep for `makeSelfContained` and figure out some way to not call it when the runtime is the new version. 
- [ ] The `run` command in UCM is currently hardcoded to use the old `IO` type as the top-level handler. This will need to be changed to be dynamic, based on the selected runtime. If the new runtime is chosen, the top-level ability allowed is new `IO`, otherwise it's old `IO`. This is a good exercise for the eventual FFI we support, which would also be similar - based on what foreign libraries are loaded that affects what you can `run`.

That's all I can think of for now. Excited!

**Comment by aryairani** [comment]
The `PrettyPrintEnv` is no longer needed, is it?

**Comment by pchiusano** [comment]
I think it is used to produce the error message for bug / todo builtins. I could see a refactoring where the runtime error type is some data type and the thing that calls the runtime is in charge of printing. That could be done before or after this integration.
