### ISSUE TITLE
update to ghc 8.8

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1562]
The goal is to give us better tool support; maybe more out of the box builds for hie/ghcide, maybe ghc profiling modes `-pr` etc. to discover what's retaining memory; this currently segfaults for me in our current 8.6.5 build.

I started an attempt in `topic/lts-15`, which is still in the middle of upgrading from megaparsec 6.5 to 8.0.

**Comment by mitchellwrosen** [comment]
- [ ] https://github.com/unisonweb/configurator/pull/2

**Comment by aryairani** [comment]
@mitchellwrosen I went ahead and approved https://github.com/unisonweb/configurator/pull/2, https://github.com/unisonweb/haskeline/pull/1, https://github.com/unisonweb/megaparsec/pull/1. 

I stopped short of merging them until we get CI going, but I'm assuming that doesn't affect #1579, which hard-codes the desired commits into `stack.yaml`.

I did merge #1581 though.
