### ISSUE TITLE
Codebase bloat plan

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1573]
Discussion from today re: codebase bloat and why there are so many namespace files, which dominate the codebase size (base has currently 1600 or so definitions, and 26,374 namespace files). There doesn’t seem to be anything screwy going on, it’s just that things add up pretty quickly. For instance, if adding 50 definitions to the List namespace, each definition with tests and docs and attached default metadata:

```
  50 definitions
x 4  avg depth of each definition (trunk.List.blah.tests.test1)
x 2  default metadata steps per definition
x 3  revisions per definition (of docs, say)
x 3  linking operations per definition (to link doc)
= 3600 namespace files
```

Each file is at least 4K on disk, so that's 14.4MB right there. Most of this history isn't relevant so in the short term (over next week) we'll do some things to avoid building so much history up in the first place. Long term (over next month or two), we will engineer a better repoformat, likely some more normalized representation that isn't tons of small files.

In the short term (over next week or so), we will:

* Toss out the history of base, using [squash merge](https://github.com/unisonweb/unison/issues/1465), which needs implementing.
* When merging PRs for base, use squashing pretty much all the time as the history of the PR itself generally isn't relevant.
* Increase visibility of number of namespace files involved in a `push`, `pull`, or `merge` so we avoid accidentally introducing history with tons of namespace files (which we don't even care about). Like "This `pull` added 2837 namespace files" would be good to know; alerts you that you might want to do a squash merge.

The namespace file format could also use some obvious tweaking to avoid redundant storage of hashes. That won't cut down on the number of files but we could likely fit each namespace file in under 4K pretty easily (4K is 64 hashes).

**Comment by aryairani** [comment]
Once we’re talking namespace file format changes, we should think about some kind of delta compression too.

**Comment by aryairani** [comment]
I'm having some second thoughts about this plan; maybe we should try doing a smaller codebase format upgrade?

**Comment by pchiusano** [comment]
Discussed this some more today with @aryairani. Going to keep base history alone, but will squash trunk activity since last release and force push that. That will reduce size of base to something reasonable. Will still use squashing during PR review of base going forward until we have better repoformat.

@pchiusano and @runarorama will add some logging statements to the codebase sync just to get more visibility and avoid accidentally pushing tons of history to base during review. Will also spot check the actual commits and make sure number of files is reasonable.

Will begin work on next repoformat ASAP.
