### ISSUE TITLE
`unison --help` hard-codes the string "ucm"

### ISSUE THREAD

**Issue by juhp** [unisonweb/unison#1585]
Have you considered renaming the `unison` executable to just `ucm` in `unison-parser-typechecker.cabal`? :)

**Comment by aryairani** [comment]
Hi @juhp, we'd intended for them both to be named `unison`, but `unison` was already in use by various package managers; now `unison` vs `ucm` distinguishes the development builds vs the released binaries.

**Comment by juhp** [comment]
So the reason for filing this issue is that `stack install` gives one a executable named `unison` but `unison --help` refers to `ucm`, so I suggest doing something about this. :-)

**Comment by aryairani** [comment]
Ok, maybe we can update the help to show the executable's name.
