### ISSUE TITLE
UCM `add` crashes on the name `.`

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#1586]
The default metadata lookup is unable to handle terms or namespaces with `.` in the name, resulting in a crash with:

```
InvalidWordyId ""
```

Transcript:

```unison
(.) f g x = f (g x)
```

```ucm
.> add
```

**Comment by aryairani** [comment]
I kind of forget, is it a consequence of `Name` not having enough structure to distinguish absolute identifiers, or is it just a run-of-the-mill bug in the parser?  (related to https://github.com/unisonweb/unison/issues/1523)
