### ISSUE TITLE
Consider disallowing name segments with `.` in them.

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#1587]
Since `.` refers to the root of the namespace tree, and is also used as a namespace separator, the fact that this character is allowed in "symboly" identifiers is a source of a lot of bugs. It would be simpler if this character were simply disallowed in mames. We can then revisit later.

**Comment by aryairani** [comment]
Seems reasonable to me, but what do we do about codebases that already have `.` in them?  Make a point of ignoring those names?

**Comment by aryairani** [comment]
Not opposed to disabling this, pending #1589, if that would still help?

**Comment by aryairani** [comment]
This should be the case now.
