### ISSUE TITLE
Add or co-opt syntax for escaped identifier names

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1589]
Inspired by:
https://unisonlanguage.slack.com/archives/CLG4P0GSD/p1590663931259900
#1523 - `.` is accepted as namespace name, but leads to issues
#1586 - `add` crashes on the name `.`
#1587 - consider disallowing namesegments with `.` in them
#1362 - syntax error when trying to define | as an operator (and some other weirdness)

### Motivation
Already, with `.` (and possibly `||` and `&&`?), we are running into parsing complications with somewhat-or-more- reserved characters in Unison identifiers.  With pluggable syntax (#499), we will have the additional problem that different syntaxes have different reserved characters, and different reserved words.  It is and will continue to be important to have a way to render and reference names created in one syntax but illegal in yours.

A `Name` should be represented by a `Seq NameSegment`, where `NameSegment` is a `newtype` of `Text` or `String`.  Any `NameSegment` consisting of printable characters should be allowed, and every pluggable syntax (including Unison's current one) should have a syntax to unambiguously parse and display it.

Some escaping options we've considered so far:

#### Backslashes
  - `foo.\<.\>.bar` means `Relative ["foo", "<", ">", "bar"]`
  - `foo.\<\.\>.bar` means `Relative ["foo", "<.>", "bar"]`
  - `.` means `Absolute []`
  - @aryairani doesn't love this one.

#### Backticks
  - ``foo.`<`.`>`.bar`` means `Relative ["foo", "<", ">", "bar"]`
  - ``foo.`<.>`.bar`` means `Relative ["foo", "<.>", "bar"]`
  - `` foo.`type` ``  means `Relative ["foo", "type"]`
  - `.` means `Absolute []`
  - `` `.` `` means `Relative ["."]`
  - Pro: Scala uses similar syntax
  - Pro/Con: backticks would no longer mean "infix wordy operator"
    - these aren't really being used well currently anyway; e.g. ``x `contains` set`` 🤔, also the 
pretty-printer doesn't generate them.
  - what about backticks in identifier names?
    - moar backticks!
      - markdown style:
        - ``` `` `.` `` ``` means ``Relative ["`.`"]``; leading and trailing space is ignored
        - ```` ``` ``. ``` ```` means ```Relative ["``."]```
      - scala style? something to do with triple-backticks though, and not super expandable
    - backslashes? 🤦🏻‍♂️
      - `` `\`.\`` ``   means ``Relative ["`.`"]``
      - `` `\`\`.` ``   means ```Relative ["``."]```
#### Parentheses
  - `foo.(<).(>).bar.` means `Relative ["foo", "<", ">", "bar"]`
  - `foo.(<.>).bar` means `Relative ["foo", "<.>", "bar"]`
  - `foo.(type)`  means `Relative ["foo", "type"]`
  - `.` means `Absolute []`
  - `(.)` means `Relative ["."]`
  * We already use this syntax to make operators first-class, although we say `(Int.+)`, not `Int.(+)`.
  * Q: how hard would it be to parse distinctly from parenthesized expressions?
  - Q: What about parens in identifier names?  I guess we disallow that.

### Task

Choose a syntax from above or from the forthcoming discussion below, and update:
- [ ] `InputPatterns` parser(s)
- [ ] auto-completion parser(s)
- [ ] `TermParser`
- [ ] `TermPrinter` (and/or open a separate ticket and ask @atacratic nicely for help) 😁

### Known loose ends:
- Per #1586, configurator doesn't like `.` namesegments either.  or maybe a lot of namesegments.  How should we escape these / replace configurator (#1472, #1129)?

**Comment by aryairani** [comment]
We decided to go with backticks over parens, due to parsing complexity.

Any printable characters (`Data.Char.isPrint`) will be allowed in identifier names, but leading and trailing space (`Data.Char.isSpace`) will be ignored (partly in anticipation of supporting markdown-like multi-backtick escaping syntax).

Markdown-like multi-backtick escaping syntax is: Surround a string containing at most N consecutive backticks with N+1 opening and closing backticks.  A space should be used to separate the opening/closing backticks from the enclosed string, if the enclosed string starts/ends with a backtick, respectively:
|input|result|
|---|---|
|`` `hello world!` ``|`hello world!`|
|`` `  hello world!  ` `` (not recommended)| `hello world!`|
|``` ``hello`world!`` ``` | ``hello`world!``|
|``` `` `hello world!`` ``` | `` `hello world!``|


If the markdown-style multibacktick is easy to implement, we can go ahead with that, otherwise we can disallow backticks in variable names for now.

**Comment by aryairani** [comment]
@mitchellwrosen We should chat about whether it's necessary to switch over the representation of `Name` like we'd tried before, or whether it's important to hold off on that due to some remaining blocker beyond the need for this escaping syntax.

**Comment by anovstrup** [comment]
This topic came up [in the #alphatesting Slack channel recently](https://unisonlanguage.slack.com/archives/CLUNF0J5S/p1643072576027100). Several people (myself included) cited a desire for escape syntax for identifiers that would otherwise be interpreted as reserved words. Since the Slack history will eventually be lost, I'll summarize the use cases mentioned:
* one user (@ceedubs) was surprised that `namespace` could not be used as an identifier
* pluggable/configurable syntaxes (locale-specific syntax?!) might have different reserved words
* @rlmark mentioned that her Doc codebase is using variations on keywords like `typez`, `aliaz` to workaround this issue
* @alvaroc1 pointed out the benefit of preserving exact names for code generated from a schema (database, thrift, etc.)

**Comment by ChrisPenner** [comment]
Current status: This PR is ready to go, but we're waiting to merge it until there's a way to refer to old-names with `.` in them so that we don't make some terms impossible to reference. @mitchellwrosen  is working on a separate PR for that, and once that's merged we can go ahead and merge this one too 👍🏼
