### ISSUE TITLE
Create a non-leaky data structure to canonicalize bytestrings and text

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1597]
## The problem

The codebase is full of 512-bit hashes and `Text`-based names.  When we load these `ByteString` and `Text` values into memory, they are all separate instances of the same data.  Since they are immutable, it would be better to let them all share the same copy in memory.

We could use `Map` or `Unison.Util.Cache`, but they don't really give us a way to release unused memory, at most they let us cap the maximum memory usage of the Map.  I want to be able to garbage-collect the mapping once there are no live references to the data, but the Map contains live references to the data, so every hash will stay around forever.

This would probably be an improvement over the current representation, honestly, but let's just go ahead and build something that will release what isn't needed.

So this leads to: some kind of Map of [`System.Mem.Weak`](http://hackage.haskell.org/package/base-4.14.0.0/docs/System-Mem-Weak.html) pointers.
> A weak pointer expresses a relationship between two objects, the key and the value: if the key is considered to be alive by the garbage collector, then the value is also alive. A reference from the value to the key does not keep the key alive.

```haskell
-- | Establishes a weak pointer to @k@, with value @v@ and a finalizer.
--
-- This is the most general interface for building a weak pointer.
--
mkWeak  :: k                            -- ^ key
        -> v                            -- ^ value
        -> Maybe (IO ())                -- ^ finalizer
        -> IO (Weak v)                  -- ^ returns: a weak pointer object

-- | A specialised version of 'mkWeak', where the key and the value are
-- the same object:
--
-- > mkWeakPtr key finalizer = mkWeak key key finalizer
--
mkWeakPtr :: k -> Maybe (IO ()) -> IO (Weak k)
mkWeakPtr key finalizer = mkWeak key key finalizer

Dereferences a weak pointer.  If the key is still alive, then
@'Just' v@ is returned (where @v@ is the /value/ in the weak pointer), otherwise
'Nothing' is returned.

The return value of 'deRefWeak' depends on when the garbage collector
runs, hence it is in the 'IO' monad.
-}
deRefWeak :: Weak v -> IO (Maybe v)
deRefWeak (Weak w) = IO $ \s ->
   case deRefWeak# w s of
        (# s1, flag, p #) -> case flag of
                                0# -> (# s1, Nothing #)
                                _  -> (# s1, Just p #)
```
## The task

1. Write a function that can be used to exchange an input `ByteString` (or `Text`) for an existing copy in memory, if one exists.  If the resulting `ByteString` is no longer being used by the application, the data structure that supports the canonicalization shouldn't prevent it from being GCed.

   ```haskell
   -- signatures not exact
   canonicalizeByteString :: Canonicalize ByteString -> ByteString -> IO ByteString
   canonicalizeText :: Canonicalize Text -> Text -> IO Text
   ```

2. Plus tests or a sample program to demonstrate that it works.

## A straightforward approach

I was planning something like having a `TVar` `IO (Map ByteString (Weak ByteString))`.  The first time the user tries to canonicalize a string `bs`, one `copy` of the string becomes the `Map` key, and a second `copy`* becomes the `Weak` ptr, and is returned from the `canonicalize*` function.  The first and second copies need to be distinct, so that the Map key (first copy) itself isn't keeping the second copy alive.  Then the `Weak` finalizer should then delete the `Map` entry.

\* this could be the original string too, though we tend to want to call `copy` anyway since ByteStrings are generally slices of other, bigger, `ByteString`.  I guess it depends on whether that other, bigger, `ByteString` is going to be in memory anyway, but I guess the whole premise is that we're expecting to be able to release these strings eventually.

## A better approach?

I saw some suggestions that a hash table was the way to go instead.

I don't think you can just use a `HashTable ByteString (Weak ByteString)` without still having separate copies for the `HashTable` key and the `Weak` pointer, as the `HashTable` will retain a list of keys in the hash bucket to distinguish among hash collisions (thus the `Eq key` constraint).

But I think you _could_ use a `HashTable Int [Weak ByteString]`, where you'd hash the key `ByteString` yourself to get the `Int`.  **Now you don't have a second copy of the ByteString for the key!**  You can call [`HashTable.mutate`](https://hackage.haskell.org/package/hashtables-1.2.3.4/docs/Data-HashTable-Class.html#v:mutate) to search the hash bucket for a matching `ByteString`, dropping any dead `Weak` you encountered along the way.  The `Weak` finalizer would also clean up the hash bucket, possibly deleting it altogether. (`mutate` can do this too.)

```haskell
empty :: MonadIO m => m (Canonical a)
canonicalize :: (MonadIO m, Eq a, Data.Hashable a) => Canonical a -> a -> m a
```

Wdyt?

**Comment by mitchellwrosen** [comment]
I like this idea a lot! [This issue](https://github.com/gregorycollins/hashtables/issues/55) concerns me, it would be good to investigate whether the other hash table types can drop data. Since the issue specifically calls out "cuckoo", I assume the others are ok. Still 😬

**Comment by mitchellwrosen** [comment]
Could use [IntMap](https://hackage.haskell.org/package/containers-0.6.2.1/docs/Data-IntMap-Strict.html) as well.

**Comment by aryairani** [comment]
Yeah I would just use the Basic HashTable; IntMap would also be fine IMO.

Re https://github.com/gregorycollins/hashtables/issues/55#issuecomment-637884382, if there's a better hashing class than `Data.Hashable`, that would be fine too.  I guess it would be good if there were some methods to have some methods to get the average and max bucket size, if we go with hashing (and I think we should).

**Comment by mitchellwrosen** [comment]
I put a work-in-progress PR up, if you want to peep at it @aryairani #1605

**Comment by mitchellwrosen** [comment]
This is done (and also it didn't work well)
