### ISSUE TITLE
try using pinboard to canonicalize data in V1 codebase, and quantify

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1606]
I think the PinBoard (#1605) is really going to improve UCM's memory usage, and maybe speed as well.

Task: 

1. Compare and quantify in terms of 
* peak memory usage
* if possible: average or product memory usage (I was getting this via ghc memory profiling)
* time

when run the transcript given in https://github.com/unisonweb/unison/issues/1535#issuecomment-628296954 

    ```ucm
    .> pull https://github.com/mitchellwrosen/unisonweb-oldbase:#u86hp5f086 .newbase
    .> pull https://github.com/mitchellwrosen/unisonweb-oldbase:#trpm76pe0i .oldbase
    .> fork newbase newbase2
    .> fork oldbase oldbase2
    .> merge newbase oldbase
    .> merge newbase2 oldbase2 
    ```

with/without
a. `PinBoard Hash` (by modifying the definition or usage of `V1.getHash`)
b. `PinBoard Text` (by modifying the definition or usage of `V1.getText`)
c. `PinBoard` substituted for `Branch.Cache` / `Unison.Util.Cache` (introduced in #1549)

2. Make a PR based on the findings.

Notes: 
* Because we had to squash the unison history of `base` as a performance workaround, instead of pulling from github master, you'll have to pull from git sha1 `517accd5fdd8a0c401f035f606c6a8ff6a230216`, which probably means pulling your own bare copy locally, and setting its head to that, and using that as the git repo to pull from for experiments.
* See `Unison.Util.Timing.enabled = True` to get the internal timing output

**Comment by pchiusano** [comment]
Seems like a very good idea to explore this!

One note: a canonicalizing map based on weak refs is great for reducing memory usage but not really a good fit for caching (where the goal is to avoid hitting disk and doing deserialization work for recently accessed stuff). If it happens to work okay it is basically a coincidence - the GC just so happens to not be aggressive enough about cleaning up garbage to ruin your cache hit rate. I’d be kinda wary of relying on it for that reason... like no matter what testing you do, you can later end up with way worse cache hit rate based on the whims of GC.

**Comment by mitchellwrosen** [comment]
Interesting! I think what you're saying is we don't necessarily want to free data when its last reference is dropped, because (per typical `ucm` usage) it might be needed soon after.

> If it happens to work okay it is basically a coincidence - the GC just so happens to not be aggressive enough about cleaning up garbage to ruin your cache hit rate

I really think GHC is good about running finalizers almost immediately - the finalizers are all _scheduled_ (via normal thread scheduling stuff) on time, I think the docs are just conservatively reminding you that finalizers _might_ not run promptly, in the same way that a forked thread isn't guarantee to start running in any finite amount of time.

Given that, do you think this is still worth pursuing (maybe as just a baseline for a future, smarter data structure?) Or, do you think that some sort of canonicalizing+caching hybrid should be imagined first? (Or neither?)

**Comment by aryairani** [comment]
Yes, a canonicalizing map is not a cache at all, it's only a tool for lowering memory residency and improving like L3 cache hit rate.

It's definitely still important to try a) and b), and maybe interesting to try c) as a baseline.  We can split c) into a separate lower-priority task if it's a big deal though.

**Comment by pchiusano** [comment]
Yeah, 100% agree on a) and b) and I'm a little curious about c) even though it seems kinda iffy to me.

**Comment by aryairani** [comment]
Yes c) is iffy, probably somewhere between pointless and "maybe we'll learn something unexpected".  I think the real answer to the stuff that we currently address with caching is simply: need less data, but that's a v2 thing.

**Comment by mitchellwrosen** [comment]
Here are some preliminary results for (a) and (b); running that transcript takes a bit so the sample size is pretty small (10 runs).

Canonicalizing `Hash`:

![gethash](https://user-images.githubusercontent.com/1074598/83951544-18565980-a800-11ea-9920-6bdd5a0c8792.png)

Canonicalizing `Text`:

![gettext](https://user-images.githubusercontent.com/1074598/83951554-30c67400-a800-11ea-9f9f-0e528c0246d9.png)

Canonicalizing both:

![both](https://user-images.githubusercontent.com/1074598/83951639-e72a5900-a800-11ea-858e-0024d539d5ce.png)

**Comment by aryairani** [comment]
@mitchellwrosen I love that tool, what is it?

**Comment by mitchellwrosen** [comment]
@aryairani it's this, I wrote it for this purpose :) https://github.com/mitchellwrosen/haskell-perf-comparator

**Comment by aryairani** [comment]
@mitchellwrosen Hah, fantastic.

I just wanted to doublecheck whether those stats were with the `517accd5fdd8a0c401f035f606c6a8ff6a230216` git branch, or with `master`?

**Comment by mitchellwrosen** [comment]
These are against `master` using the transcript from `517accd5fdd8a0c401f035f606c6a8ff6a230216`, but pointing at https://github.com/mitchellwrosen/unisonweb-oldbase per your instructions on how to reset

**Comment by aryairani** [comment]
Ok, I was just checking because I had thought that the baseline for that was using even more memory (like gigs), but maybe I thinking of an older build of UCM.

**Comment by aryairani** [comment]
Hmm, I don't understand the results.

I added a transcript to the issue description that I assume is the same as what you're using. When I `ucm transcript <that>` using the M1m binary, and keep an eye on it with htop, it seems to use about 300MB before petering out, so I was surprised that you were only seeing 144MB.  But `ucm` is not `unison`, so maybe the different optimization settings affect the memory footprint.

Could you try running it with this transcript too?
    ```ucm
    .> pull https://github.com/mitchellwrosen/unisonweb-oldbase _base
    ```
Doing a `git clone --bare https://github.com/mitchellwrosen/unisonweb-oldbase` and then using the resulting dir as your transcript repo location should improve the variance if you weren't already doing that. It will be slower though (2.5mins and ~2.2GB for me), so feel free to do fewer samples, like 3.

**Comment by mitchellwrosen** [comment]
> it seems to use about 300MB before petering out, so I was surprised that you were only seeing 144MB

The number I put above (144MB) is the total amount of Haskell memory allocated; this is different from the peak memory the RTS allocates from the OS (300MB). I've updated `haskell-perf-comparator` to report both numbers now. Here's one run of the slow transcript as an example:

![2020-06-06-223719_503x587_scrot](https://user-images.githubusercontent.com/1074598/83958992-4e1e3100-a846-11ea-9c71-c70b2b15115a.png)

> But ucm is not unison, so maybe the different optimization settings affect the memory footprint.

How's it different? I'm just building unison with `stack build`, so not applying any GHC or RTS flags that are not defined in the cabal file. (Tweaking those would probably be smart).

> Doing a git clone --bare https://github.com/mitchellwrosen/unisonweb-oldbase and then using the resulting dir as your transcript repo location should improve the variance if you weren't already doing that.

Could you explain? Do you mean modify the transcript itself to point at a folder rather than https://github.com/mitchellwrosen/unisonweb-oldbase?

**Comment by aryairani** [comment]
> The number I put above (144MB) is the total amount of Haskell data/closure memory allocated; this is different from the peak memory the RTS allocates from the OS (300MB). 

> I've updated haskell-perf-comparator to report both numbers now. Here's one run of the slow transcript as an example:

| | |
|--|--|
| Max live memory | 144 mb |
| Memory allocated | 11 gb |
| Max copied during GC | 2.4 gb |
| Max memory reserved | 376 mb |

Could you help me understand the difference between these categories? 

> How's it different? I'm just building unison with stack build, so not applying any GHC or RTS flags that are not defined in the cabal file. (Tweaking those would probably be smart).

The `series/M1` branch has altered build files; I forget if `stack.yaml` or `.cabal`, but it uses -O2 and some other things.  This scheme is admittedly a little weird.  On the other hand, people compiling from `master` have the settings you see.

> Could you explain? Do you mean modify the transcript itself to point at a folder rather than https://github.com/mitchellwrosen/unisonweb-oldbase?

Yeah, like `git clone --bare https://github.com/mitchellwrosen/unisonweb-oldbase` and then modify the transcript itself to point at `unisonweb-oldbase.git` which will get created by `git clone`.  It should only affect the time outcomes.

What do you make of the results from https://github.com/unisonweb/unison/issues/1606#issuecomment-640099251 ?  

If I understood the tables correctly, there's a 34% slowdown when canonicalizing `Hash`; negligible change when Canonicalizing `Text`, and then somewhere in between when Canonicalizing both.  Maybe I should just be looking at the "(cpu") times — and using `git clone --bare` to take the network out of the equation will improve the variance of the non-(cpu) results.  

But even looking at the cpu times, I'm a little surprised by the 27–29% slowdown.  However, this is only a 1-second slowdown.  Is it still 1-second on the big run, or is it still 27–29% on the big run?

> See `Unison.Util.Timing.enabled = True` to get the internal timing output

^ This will cause unison to output some timings for each phase; it would be interesting to understand which phases are affected by the change.  Maybe just a spreadsheet for those, since it involves some parsing of the output.

**Comment by mitchellwrosen** [comment]
As discussed on Slack, we think there might be a bug in pointing a transcript at a local git dir - it's crazy slow. So, I was unable to repeat the experiment will less variance, but I'll document how to do this yourself for anyone interested (and for repeating later).

First, I compile `unison` three times and chuck them in `bin/`:

```
#!/bin/sh

set -ex

mkdir -p bin

git fetch

git checkout origin/master
stack build unison-parser-typechecker:exe:unison
cp $(stack exec which unison) bin/unison-master

git checkout b0f77c56aafee579ab12a00b17355b5687d08b49
stack build unison-parser-typechecker:exe:unison
cp $(stack exec which unison) bin/unison-pin-hash

git checkout caf58862fb6b5965e9fe0c6700b692d5ce783c6d
stack build unison-parser-typechecker:exe:unison
cp $(stack exec which unison) bin/unison-pin-text
```

These are master, "canonicalize getHash", and "canonicalize getText" commits.

Then, I run

```
haskell-perf-comparator -n 10 './bin/unison-master transcript slow.md' './bin/unison-pin-hash transcript slow.md' -l master -l getHash
haskell-perf-comparator -n 10 './bin/unison-master transcript slow.md' './bin/unison-pin-text transcript slow.md' -l master -l getText
```

to produce tables (using https://github.com/mitchellwrosen/haskell-perf-comparator). Here are those tables today:

![gethash](https://user-images.githubusercontent.com/1074598/84082785-7032c300-a9ae-11ea-8ae0-6b3e954dc302.png)

![gettext](https://user-images.githubusercontent.com/1074598/84082794-73c64a00-a9ae-11ea-9b9a-85daffb335d8.png)

> Could you help me understand the difference between these categories?

Sure! 

- Max live memory, now renamed to "max residency" - the largest amount of live data that we ever witnessed during a major garbage collection.
- Memory allocated, now renamed to "allocated" - the total number of bytes allocated over the entire run, for Haskell closures (like, we might `malloc` a page/block/whatever from the OS, and then "alloc" only 24 bytes of that for an `Int`, or something. That's this number)
- Max copied during GC, now renamed to "copied during GC" - when using the default garbage collector, it copies all live data every GC. This number probably isn't too interesting, it's mostly a function of how much live memory there is (better summarized by total/max/avg allocated)
- Max memory reserved, now renamed to "allocated from OS" - this is the actual amount of memory allocated by the RTS from the operating system; again it's maybe not so interesting for optimization purposes, just a factoid.

> If I understood the tables correctly, there's a 34% slowdown when canonicalizing Hash; negligible change when Canonicalizing Text, and then somewhere in between when Canonicalizing both. Maybe I should just be looking at the "(cpu") times — and using git clone --bare to take the network out of the equation will improve the variance of the non-(cpu) results.

> But even looking at the cpu times, I'm a little surprised by the 27–29% slowdown. However, this is only a 1-second slowdown. Is it still 1-second on the big run, or is it still 27–29% on the big run?

The phrasing was a bit misleading on the previous images so I'll refer to the ones from this comment instead. The real timing number we probably care about is *total elapsed time*, it's what the user running the command feels. This is further divided into "mutator" and "GC" time, with percentages (and there are a couple of other things I'm not displaying that don't seem interesting, like the time it takes to initialize and tear down the runtime system).

Summary of canonicalizing `getHash`:
- It takes 17% longer
- It takes 20% less memory (average and total allocated)

Summary of canonicalizing `getText`:
- Doesn't seem to have had much of an effect at all

I don't think I really know the full story here, in particular I'm not exactly sure why canonicalizing `getHash` results in 20% (!) more generation 0 garbage collections. That seems to be the major factor in slowing everything down.

I also think it's probably a good idea to run this experiment again more stably (basically, against a local git repo as you recomment).

About the "big run" - the 2 minute guy - I haven't gotten around to that one yet, all these images are from running the transcript from your first comment.

**Comment by aryairani** [comment]
> As discussed on Slack, we think there might be a bug in pointing a transcript at a local git dir - it's crazy slow. So, I was unable to repeat the experiment will less variance, but I'll document how to do this yourself for anyone interested (and for repeating later).

@mitchellwrosen until #1610, we can work around the local git dir issue by just giving the absolute path, as shown at the top of that ticket.

Next, thanks for writing up the `haskell-perf-comparator` instructions.

> I don't think I really know the full story here, in particular I'm not exactly sure why canonicalizing getHash results in 20% (!) more generation 0 garbage collections. That seems to be the major factor in slowing everything down.

Yeah, I would not expect this to result in more generation. 🤔  Could you point to the `getHash` branch online? and I might take a peek :)

**Comment by mitchellwrosen** [comment]
Yeah, sorry, I put the commits above but didn't mention the branch. They're on mitchell/use-pinboard

**Comment by aryairani** [comment]
Oops, I had totally missed them; thanks.

**Comment by aryairani** [comment]
Pro tip: since there's only one `unison` target, you can just `stack build :unison`

**Comment by aryairani** [comment]
One thought: although it would complicate the implementation:

```haskell
getHash = do
  len <- getLength
  bs <- B.copy <$> getBytes len
  pure $ Hash.fromBytes bs
  pure $! pinGlobalHash (Hash.fromBytes bs)

**Comment by aryairani** [comment]
One thought, although it would complicate the implementation:

For explanatory purposes, here is a _modified_ version of `getHash`:

```haskell
getHash :: MonadGet m => m Hash
getHash = do
  len <- getLength
  bs <- getBytes len
  pure $! pinGlobalHash $ Hash.fromBytes $ B.copy bs
```

`Hash.fromBytes bs` and `Hash.fromBytes $ B.copy bs` should produce the same hash under `Data.Hashable`.  It we could save an allocation if we only had to force `B.copy` when `bs` doesn't already exist on the pinboard.  Currently it has to be forced in order to compute the hash, and then it is immediately discarded.  Maybe an unsafe insert method that lets you pass the hash and a lazy value independently?

I'm not sure why we are seeing _more_ allocations in that branch anyway, but with this a change like this, we should see fewer, right?

**Comment by aryairani** [comment]
Could the `PinBoard` itself be responsible for extra allocations?  GCing old `IntMap`s?

**Comment by mitchellwrosen** [comment]
Good idea about copying only when necessary. I tried that, it didn't seem to have any affect. I made these things tweakable by env vars; to play around yourself, you can:

- Build the latest `haskell-perf-comparator` if you're using that.
- Build the latest `unison` on `mitchell/use-pinboard` (I copy it out to `./bin/unison-mitchell-pinboard`)

It respects the `UNISON_PIN_HASH=` and `UNISON_PIN_TEXT=` env vars for pinning hashes and texts, and then optionally uses your "copy if necessary" idea if `UNISON_PIN_WITH=` is set.

Example usage:

```
haskell-perf-comparator -n10 -l master -l pinHash -l 'better pinHash' './bin/unison-use-pinboard transcript slow.md' 'UNISON_PIN_HASH= ./bin/unison-use-pinboard transcript slow.md' 'UNISON_PIN_HASH= UNISON_PIN_WITH= ./bin/unison-use-pinboard transcript slow.md'
```

I think next it would be interesting to compare other data structures for the pinboard, like a hashmap and a hashtable. But, yeah, so far the time/memory trade-off seems not great.

**Comment by mitchellwrosen** [comment]
> I don't think I really know the full story here, in particular I'm not exactly sure why canonicalizing getHash results in 20% (!) more generation 0 garbage collections. That seems to be the major factor in slowing everything down.

This comment I made is incorrect - although 20% more garbage collections occur, we only spent 6% more time garbage collecting, and 5% less time garbage collecting relative to the mutator.

The increase in elapsed time is (presumably) mostly due to actually inserting into this global IntMap

**Comment by mitchellwrosen** [comment]
Numbers for the big boy, just n=1 :[
![2020-06-12-193833_662x994_scrot](https://user-images.githubusercontent.com/1074598/84554101-58c44480-ace4-11ea-850f-e2d98bf2a081.png)

**Comment by mitchellwrosen** [comment]
I did compare `IntMap` to `HashMap` and (a non-threadsafe) `HashTable` implementation. `HashMap` was pretty similar (but better); here's a comparison of `master`/`IntMap`/`HashTable`

![2020-06-12-205427_1076x1028_scrot](https://user-images.githubusercontent.com/1074598/84556233-0fc5bd80-acef-11ea-9529-605c1b42f49c.png)

Summary of not using a pinboard vs. using a HashTable pinboard:

- Using pinboard takes 15% longer and uses 20% less memory on average

**Comment by aryairani** [comment]
> > I don't think I really know the full story here, in particular I'm not exactly sure why canonicalizing getHash results in 20% (!) more generation 0 garbage collections. That seems to be the major factor in slowing everything down.
> 
> This comment I made is incorrect - although 20% more garbage collections occur, we only spent 6% more time garbage collecting, and 5% _less_ time garbage collecting relative to other things.

I didn't follow (other things?); although, I guess I don't care so much about the time spent allocating or garbage collecting, as knowing how much time is spent in the different conceptual phases, and keeping the total time down.  The former (memory management operations) contributes to the latter (phase runtime though), and then it is still important to understand how and why.

> The increase in elapsed time is (presumably) mostly due to actually inserting into this global IntMap

Is there a way we can directly measure this time?  On whatever data structure we think is going to be fastest, without letting the copying time contribute to the measurement for the insert.

> Summary of not using a pinboard vs. using a HashTable pinboard:
> 
> * Using pinboard takes 15% longer and uses 20% less memory on average

I don't get this either.  With "better HashTable", we should be doing less copying than before, because we skip the copy when the element already exists in the HashTable, right? Are you thinking that computing the hash and manipulating the hash buckets (asymptotically O(1) when the HashTable is allowed to grow automatically, right?) is slower than the reduction in copying?

And could you check these on the big operation, which will mute the constant factors a bit?


And speaking of muting, can you hide whatever rows of output you don't think are informative?  Guessing this will include "Elapsed time", "Allocated per second" through "Fragmented", "Parallel Collections", "Time" (as opposed to "CPU Time")

Why do you suppose +45.4% is Allocated in pinHash?

Do you suppose there's some timing library (maybe what's already in RTS) that lets us attribute different operations into different timing buckets?

**Comment by aryairani** [comment]
Also can we try `TVar` per @pchiusano's comment (somewhere).

**Comment by mitchellwrosen** [comment]
> Is there a way we can directly measure this time? On whatever data structure we think is going to be fastest, without letting the copying time contribute to the measurement for the insert.

I think it is possible, yeah, but I checked out a flamegraph and couldn't really glean anything from it :/. I can put together some instructions on how to generate one if you want to click around.

> I don't get this either. With "better HashTable", we should be doing less copying than before, because we skip the copy when the element already exists in the HashTable, right? Are you thinking that computing the hash and manipulating the hash buckets (asymptotically O(1) when the HashTable is allowed to grow automatically, right?) is slower than the reduction in copying?

I think so. It seems the time it takes to mutate the global hash table (whether we actually insert a hash or not) for every hash read off disk does indeed dwarf any time savings from not actually copying the duplicate hashes.

I was curious, so I just counted the number of pinboard cache hits/misses for this transcript. 4000 misses, 735,000 hits. Tons of duplicates as you suspected :O

> And could you check these on the big operation, which will mute the constant factors a bit?

Sure, will post those results, too.

> And speaking of muting, can you hide whatever rows of output you don't think are informative? Guessing this will include "Elapsed time", "Allocated per second" through "Fragmented", "Parallel Collections", "Time" (as opposed to "CPU Time")

Yeah, I think I could, though that will probably take a bit of time as this little script isn't exactly pretty, or very extensible. For now, I think just ignoring the meaningless-ish metrics would be better.

> Why do you suppose +45.4% is Allocated in pinHash?

I... don't know. That is surprising, yeah. Maybe there's a bug in the implementation. Hm... we could look at it together if you'd like. I actually can't see how so much more allocation is happening, since we should simply be calling `ByteString.copy` less, at the cost of CPU time. Mm mm mm...

> Do you suppose there's some timing library (maybe what's already in RTS) that lets us attribute different operations into different timing buckets?

Hm, none come to mind. What were you imagining? The only difference between these two branches is the implementation of `getHash`, so I'm not totally sure where you were thinking such a library would be used.

> Also can we try TVar per @pchiusano's comment (somewhere).

Unless I misunderstood, that wouldn't really work, as manipulating the pinboard requires IO. Of course, a TVar could just be mutated afterwards, non-atomically, but... the point is moot (for the latest experiments) that are using a `HashTable` implementation, since no locking occurs (it's not thread-safe).

**Comment by mitchellwrosen** [comment]
I think this can be closed?
