### ISSUE TITLE
Document on unison-language vs. chapel-language?

### ISSUE THREAD

**Issue by zhongwm** [unisonweb/unison#1612]
Did we considered some documenting on unison-language vs. chapel-language?

**Comment by pchiusano** [comment]
I don't know much about Chapel, and just in general, I don't really want Unison's official docs or these GitHub issues to be about making comparisons to other technologies (that we're not experts in anyway). Maybe we'd reconsider at some point later, if it's a technology we know super well and we get asked about how Unison compares a lot.

That said, if anyone in the Unison community has experience with Chapel and wants to write something up on their blog or whatnot, some folks might be interested in that. But I don't think it goes in the official docs or in these GitHub issues. Thanks!
