### ISSUE TITLE
@[source] should probably preserve indentation

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#1635]
I realized that trying to use Unison docs and `display` to produce readable Markdown docs runs into an issue if you use a `@[source]` to show the source of a term that gets rendered as more than a single line. This can be particularly annoying when an implementation seems like it should be a one-liner but renders with a `use` line.

For example, take the following method:

```
natDiv: Nat -> Nat -> Nat
natDiv = (/)
```

Now add a doc:

```
natDiv.doc = [: 
  Here is the definition:
  
      @[source] natDiv
:]
```

If you `view` these, they both look good:

```
.scratch> view natDiv

  natDiv : Nat -> Nat -> Nat
  natDiv =
    use Nat /
    (/)

.scratch> view natDiv.doc

  natDiv.doc : Doc
  natDiv.doc =
    [: 
    Here is the definition:
    
        @[source] natDiv
     :]

```

But if you `display` the doc the `natDiv` implementation isn't indented with 4 spaces, so only the top line of it renders as a code block in Markdown:

```
.scratch> display natDiv.doc

  
  Here is the definition:
  
      natDiv =
    use Nat /
    (/)
```

In rendered Markdown it looks like this:

Here is the definition:

    natDiv =
  use Nat /
  (/)

**Comment by pchiusano** [comment]
As a workaround for now, you can put the code in a fenced code block - 

````
Here is the definition:

```
@[source] natDiv
```
````

**Comment by ceedubs** [comment]
@pchiusano I had tried that but the closing triple backticks render on the same line as the last line of the item being sourced, so they don't actually end the Markdown code block.

I just checked and if you put put a blank line before the closing backticks you end up with an annoying trailing empty line in the rendered code block, but it's a suitable workaround.

**Comment by pchiusano** [comment]
Ah, that's too bad.

I keep thinking that we might want to make the doc type more structured. Like even if you write in something Markdown-ish and that's the plain text rendering, it's actually parsed into a more structured thing that can be rendered to multiple targets easily.

**Comment by ceedubs** [comment]
@pchiusano that sounds like it could be cool, but it would fall low on my priority list. Markdown is pretty ubiquitous, so most people will probably be pretty happy with it.

A notable potential exception that comes to mind is linking to other terms within docs. I'm not sure whether that requires more structure than is currently present? Since they render with an underline when I use `display` I assume that there's already enough structure?

**Comment by atacratic** [comment]
I think this is a dup of #1256 ?  I did sit down to fix it a few months ago but then didn't...

**Comment by ceedubs** [comment]
Yes it is thank you @atacratic. I even searched for this issue before creating it! But I guess that I used the wrong search terms. Consider this ticket issue search optimization for anyone doing so in the future 😛.

Closing as duplicate of #1256.
