### ISSUE TITLE
Consider standardizing extensions throughout every component

### ISSUE THREAD

**Issue by seagreen** [unisonweb/unison#1643]
It makes for one less thing to think about ("Can I use LambdaCase here? Or is that the other package?") which IMHO is important when development is already so mentally taxing.

I don't think it matters much which extensions you pick, eg the ones already in `parser-typechecker:lib` seem fine.

I'd be happy to make a PR for this if you decide it's worth doing.

**Comment by aryairani** [comment]
I would love this.  Is there a way to just have it in one spot though, instead of copied into every component?

**Comment by seagreen** [comment]
You can use common stanzas (https://cabal.readthedocs.io/en/latest/cabal-package.html#common-stanzas) to get the repetition down to once-per-cabal file, which I don't think is too bad.

**Comment by aryairani** [comment]
Is there anything nice you can do to share the settings across cabal files?

**Comment by seagreen** [comment]
Not that I know of. Maybe @mitchellwrosen has suggestions?

For now I made a PR for use to peruse that just has a note on each common stanza to keep them in sync throughout the repo: https://github.com/unisonweb/unison/pull/1644

I agree it would be better to have them in one place, but since there are only three I don't think this is too bad.

**Comment by aryairani** [comment]
There are only 3 now, but I have a branch with like 20. 😬

**Comment by seagreen** [comment]
Oh goodness!

Each time this comes up I have to mention the using separate branches of the module tree for separating subprograms (eg https://github.com/purescript/purescript/tree/master/src/Language/PureScript, but you see this everywhere) is also an option.

And it has the advantage that tooling likes it better. Eg jump-to-definition works today in ghcide within a component.

However, I know there are advantages to separate packages too.

**Comment by seagreen** [comment]
Also relevant, the compile time implications of separate packages: https://www.parsonsmatt.org/2019/11/27/keeping_compilation_fast.html

---

As far as this issue goes though, since we merged https://github.com/unisonweb/unison/pull/1644 should we close it?

**Comment by aryairani** [comment]
> As far as this issue goes though, since we merged #1644 should we close it?

Yeah; recommend using "implements #xxx" or "fixes #xxx" as appropriate in the PR when it's directly paired to an issue like this was, so that it will close on merge.
