### ISSUE TITLE
pull-request.create is awkward when the output is bigger than a screen

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#1646]
What are others doing when the `pull-request.create` output is longer than their screen size?

For me the output opens in `less` (I think?), and I don't know of a convenient way to copy the entirety of the text to paste in a GitHub issue.

I tried doing `echo 'pull-request.create git@github.com:unisonweb/base:.trunk git@github.com:ceedubs/unison-dev:.prs._base.nelfoldl' | ucm | pbcopy`, but this ends up capturing a lot of ANSI escape characters.

I could be missing something obvious, but it seemed worth capturing in an issue since this might trip up others.

**Comment by ceedubs** [comment]
In case it's helpful to anyone else, this is what I ended up doing:

```sh
echo 'pull-request.create git@github.com:unisonweb/base:.trunk git@github.com:ceedubs/unison-dev:.prs._base.nelfoldl' | ucm | sed -E "s/[[:cntrl:]]\[[0-9]{1,3}m//g" | pbcopy
```

**Comment by aryairani** [comment]
Oof yeah.  I guess I’d just page to the bottom using Spacebar and then scrollback to copy.  We have talked about calling pbcopy internally, but would still need to be careful about the escape sequences.

**Comment by ceedubs** [comment]
The `pull-request.create` command is no more.
