### ISSUE TITLE
ucm uses CPU while idle - most time being spent in GHC RTS in scheduleDetectDeadlock

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#1660]
Symptom:  I start ucm, and I see one of my CPU cores go to 40-60% and stay there.

If I pass `+RTS -I0` when I start ucm, then it goes away, so I think something's probably triggering/aggravating the issue described [here](https://gitlab.haskell.org/ghc/ghc/-/issues/13164): the GHC runtime system apparently has a tradeoff where it does GCs even when idle, as a form of deadlock detection.

Why it should be happening a bunch more now I don't know, so I guess that's the next question - read on below for clues related to repeating background work.

The rest of this summary was written before I found the link above and the -I0 flag.

I'm going to down tools on this now!

-----

I recompiled with debug symbols and used 'perf' and gdb (I'm on linux).  ~70% of time is spent in the following stack (most recent function call at the bottom.)
```
__GI___clone (inlined)
start_thread
workerStart
scheduleWorker
schedule
scheduleDetectDeadlock (inlined)
scheduleDoGC
GarbageCollect
scavenge_until_all_done
scavenge_loop1
scavenge_find_work (inlined)
scavenge_block1
```
I use gdb and I find we are moving around in schedule(), part of the GHC runtime system, the main scheduler work loop. (Latest GHC code for that function at the time of writing is [here](https://gitlab.haskell.org/ghc/ghc/-/blob/3f50154591ada9064351ccec4adfe6df53ca2439/rts/Schedule.c#L193) - although I haven't dug in to work out exactly what code revision we're currently running with.)

I can see us executing scheduleDetectDeadlock and scheduleYield.  After much stepping around in gdb I still haven't proven the exact code flow, but I suspect we're going through the `continue` statement [here](https://gitlab.haskell.org/ghc/ghc/-/blob/3f50154591ada9064351ccec4adfe6df53ca2439/rts/Schedule.c#L317) and therefore repeatedly doing the scheduleDetectDeadlock and the GC inside it in a tight loop (same disclaimer that I haven't checked we're running the exact code version at that link - in fact I know from line number mismatches that we're not). 

Note this interesting comment in the RTS code (added 8 years ago) about GC livelock: [here](https://gitlab.haskell.org/ghc/ghc/-/blob/3f50154591ada9064351ccec4adfe6df53ca2439/rts/Schedule.c#L665). 

It's possible that the gdb-based part of this analysis could be being confounded by the gdb attach I'm doing, looking like an interrupt and causing different behavior after the scheduleDetectDeadlock - so would need to hack the RTS sources to add some debug trace to be sure what's going on.   

Not much luck from googling around, but I haven't tried thoroughly.  Recent history of the RTS scheduler code is [here](https://gitlab.haskell.org/ghc/ghc/-/commits/master/rts/Schedule.c), but again no obvious hot leads.  

[This](https://gitlab.haskell.org/ghc/ghc/-/issues/4322#note_44382) might be a clue: are we doing some repeated background work maybe on a repeating timer that is then causing a GC each time?  Maybe there's some GHC RTS logging that will tell us what 'idle GCs' are happening?  And some config to allow them to be less frequent?

Best next steps are probably 
- search recent unison history for stuff to do with repeating background work
- more research around idle GCs
- binary chop to see what unison commit triggered it (wild guesses would be any GHC upgrades or stuff to do with either GC config, multi-threading, or the file watcher or other I/O handing.)

Notes to self on the debugging steps (only good on linux):
 - building ucm with [dwarf debug symbols](https://gitlab.haskell.org/ghc/ghc/-/wikis/dwarf):  `stack build --ghc-options="-g" --no-strip`, and then find the resultant binary and run it directly, as `stack exec` seems funny/[broken](https://github.com/commercialhaskell/stack/issues/4863) about which binary it uses as soon as you start to customize the build; (use `nm` to check if a given binary has debug symbols)
- `perf record -F 99 -p PID --call-graph dwarf sleep 10` as per [this](http://www.brendangregg.com/perf.html), then `perf report` or `perf report --stdio -n -g folded` to decode
- gdb attach directly to the LWP of the offending thread, not just the parent process (easy to see which is which in htop, and the child thread will have a higher PID)

unison commit trunk@519cbe

**Comment by atacratic** [comment]
Could also play about with RTS event logging: [more info](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/runtime_control.html#tracing), and [required link flag](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/phases.html#ghc-flag--eventlog).

**Comment by aryairani** [comment]
Crazy theory: I wonder what would happen if we just replaced all our `ByteString` with `ShortByteString`?  Maybe we're running afoul of some heuristic that tries to defrag ram to reduce the big usage of a big codebase?

**Comment by pchiusano** [comment]
Wow, good sleuthing @atacratic. Does the problem also disappear when pointing to a fresh codebase? If yes, sounds like same issue @runarorama was seeing.

**Comment by atacratic** [comment]
> Does the problem also disappear when pointing to a fresh codebase?

Yup!

**Comment by atacratic** [comment]
Here's the RTS event log, rendered in [threadscope](https://github.com/haskell/ThreadScope). (So this is now ucm built with `stack build --ghc-options="-g -eventlog" --no-strip` and run with `+RTS -l`)

![image](https://user-images.githubusercontent.com/21991324/90981217-a7e5eb80-e557-11ea-9254-af7670818339.png)

I've highlighted the row where it's about to spend 0.53 seconds on the GC *(which we know from above is invoked from scheduleDetectDeadlock).  It's repeating that process every second, so I think we're looking for a 1 second repeating timer somewhere.  I see from a grep that yaks/configurator/Data/Configurator/Types/Internal.hs:157 talks about a minimum 1 second check interval for config updates - could that be the trigger?  1 second is the [default](https://github.com/bos/configurator/blob/master/Data/Configurator.hs#L174).

scheduleDoGC (which is in our culprit stack above) makes the [trace call](https://github.com/ghc/ghc/blob/c0979cc53442b3a6202acab9cf164f0a4beea0b7/rts/Schedule.c#L1740) which comes out as `HEC 0: requesting parallel GC` in the event trace in the screenshot above.  

Here's the documentation of the idle GC RTS feature.  [link](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/runtime_control.html#rts-flag--I%20%E2%9F%A8seconds%E2%9F%A9)

> In the threaded and SMP versions of the RTS (see -threaded, Options affecting linking), a major GC is automatically performed if the runtime has been idle (no Haskell computation has been running) for a period of time. The amount of idle time which must pass before a GC is performed is set by the -I ⟨seconds⟩ option. Specifying -I0 disables the idle GC.

> For an interactive application, it is probably a good idea to use the idle GC, because this will allow finalizers to run and deadlocked threads to be detected in the idle time when no Haskell computation is happening. Also, it will mean that a GC is less likely to happen when the application is busy, and so responsiveness may be improved. However, if the amount of live data in the heap is particularly large, then the idle GC can cause a significant delay, and too small an interval could adversely affect interactive responsiveness.

> This is an experimental feature, please let us know if it causes problems and/or could benefit from further tuning.

Binary event log file here - from starting ucm in my codebase and leaving it up for 20 seconds:  
[unison.eventlog.zip](https://github.com/unisonweb/unison/files/5114101/unison.eventlog.zip)

**Comment by atacratic** [comment]
... sorry, had to post the above and reboot.

Summary:
- We're doing deadlock-detection GCs (which seem to use at least some of the idle GC mechanism) every second, which are burning the CPU.
- Strongly suspected but not proved: it's the configurator check-for-updated-config-file update that is the trigger.
- From reading the RTS scheduler, it seems plausible that making a foreign function call triggers the RTS to go into a kind of quick shutdown which then triggers the GC.  But haven't fully followed that through the code and confirmed.

This being new since the adoption of configurator would make sense - haven't checked though.  The fact that GC will take longer when we have more stuff in memory matches with the fact we don't see this on fresh codebases, only bigger ones.

Possible directions:
- change the configurator check interval and confirm it changes the observed GC interval
- check that this was introduced by the commits that added in usage of configurator 
- google around to try and find existing similar issues out there with the same root cause
- code read the RTS scheduler (also docs [here](https://gitlab.haskell.org/ghc/ghc/-/wikis/commentary/rts/scheduler)) to understand why it thinks this behavior is sensible, or whether there is maybe some other extra factor which is causing it
- just turn off idle GC
- ...?

**Comment by atacratic** [comment]
Maybe this is the RTS working as intended.  [edit - I now think this is very likely]  The point of the idle GC is to do a GC after a certain period (0.3s) of idleness - better to do it while the system is idle and the user won't notice.  So 0.3s after the operation we're doing on a 1 second timer, we do a GC.  

I wonder if it's possible to make background 'check for changes' type work not count for the purposes of the idle GC scheduling.  So we do it once, 0.3 seconds after the user sits back to have a think, but not endlessly thereafter.

If not, I think just switching it off is the way forwards....  Adding `-with-rtsopts=-I0` to a ghc-options somewhere I guess?  [edit - I think this is the right fix]

Or making it happen at most once per minute with [`-Iw60`](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/runtime_control.html#rts-flag--Iw%20%E2%9F%A8seconds%E2%9F%A9).

**Comment by aryairani** [comment]
First off, thanks so much @atacratic for digging into this, I don't think we would've found this any time soon.

Some comments + things I would love to understand, although they shouldn't necessarily hold up the PR:

* Why does configurator use 1-second polling?  Isn't there some event-driven version?
* Does commenting out configurator also fix the issue?
* Is there something funny about our heap that is making GC unusually expensive?
  > if the amount of live data in the heap is particularly large
  
  I don't think the live data *should* be particularly large, but I suppose it is, at the moment.

I think we should probably only treat turning off the idle GC as a short-term workaround that hides and enables the real culprits: unnecessary Haskell activity and unnecessarily large heap usage.

> the main issue with ucm responsiveness is clamping down on commands that use many seconds of CPU, not saving a small constant increment on commands that use significant but sub-second CPU.

Lastly, though minor, I would push back on the above assertion: sub-second lags are still something we should strive to eliminate if we can.  We are used to all software being pretty laggy — but we will notice and appreciate it when it isn't!

**Comment by mitchellwrosen** [comment]
If this problem is fixed by disabling idle GC, I don't think it's the same one @runarorama was experiencing: https://unisonlanguage.slack.com/archives/CLG4P0GSD/p1594171198187100

**Comment by aryairani** [comment]
> If this problem is fixed by disabling idle GC, I don't think it's the same one @runarorama was experiencing: https://unisonlanguage.slack.com/archives/CLG4P0GSD/p1594171198187100

Hm, thanks @mitchellwrosen.

Side note, I have a codebase with the latest full `base`, and UCM version M1m is hovering between 0.0% and 0.1% CPU utilization; `trunk` `-O2` idles at 20–40%, `trunk` `-O0` at 25–55%.

This says to me that it's not exactly a problem of codebase size, even if that is a factor.

I'm running `git bisect` now.

**Comment by atacratic** [comment]
All good questions @aryairani :+1: 

Idle GC seems like a misfeature to me.  Setting up repeating timers (for example for polling but not only that) is common in many applications.  I'd be surprised if ucm didn't sprout more as it grows, e.g. towards distributed operation.  Idle GC means that by default each timer pop ends up costing a prodigious amount of CPU.  It would be better if it was up to the application code to ask the runtime for an extra bonus 'just getting ahead' GC when it wants one - and presumably there will in fact be some way of doing that if we really want to in the future.  I dimly suspect though that things are how they are for complicated reasons to do with deadlock detection, although it's not obvious to me why GC should need to be part of the deadlock detection mechanism.  

> sub-second lags are still something we should strive to eliminate

Agree!  We want all commands to seem super fast, and 'sub second' is still slow.  Actually I was thinking as follows.  
- This getting-ahead-on-GC optimization which idle GC is doing, only actually makes a difference to a subsequent command's runtime if that subsequent command would have ended up hitting at least one GC pause.  
- And only if the first of those pauses is then avoided or reduced because of the previous extra idle GC.  
- Presumably (?) super fast (<20ms) commands will rarely hit a GC pause anyway, so they won't be harmed by the loss of idle GC. 
But actually I don't know enough about GC scheduling to really do more than speculate.  

@mitchellwrosen there was another slack conversation starting [here](https://unisonlanguage.slack.com/archives/CLG4P0GSD/p1597970927001600)

**Comment by aryairani** [comment]
Ok, so it was the addition of the `-threaded` flag in PR #1619 that activated the deadlock detection; which in retrospect, is the comments you quoted also say.  Also, ["The main purpose of the idle GC is not really to collect garbage, it's for deadlock detection."](https://gitlab.haskell.org/ghc/ghc/-/issues/13164#note_131013)

So do we want `-threaded` without deadlock detection, or not `-threaded`?  I guess the former, but it's a weird spot to be in.

**Comment by aryairani** [comment]
I noticed that even on an empty codebase, idle GC takes 0.5–1% of my CPU, as opposed to 0.0–0.1% without.
