### ISSUE TITLE
Hashing and HMAC builtins proposal

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1694]
Will start with an example usage:

```Haskell
ex : Bytes
ex = 
  hmac.new Sha3_512 secretKey
    |> append "uno"
    |> append (1,2,3)
    |> append [1,2,3,4]
    |> appendBytes (Text.toUtf8 "Oat bag, gonna get my oat bag now!")
    |> hmac.finish 
```

Here's the API.

## Hashing

These would go in a new namespace, `crypto.hash`. Based on https://hackage.haskell.org/package/cryptonite-0.27/docs/Crypto-Hash.html.

```Haskell
-- type used for incremental hashing
builtin type Sha3_512

-- create a new hashing context
Sha3_512.new : Sha3_512

-- add any value to the hash context, incorporating type information into the hash
Sha3_512.append : Sha3_512 -> a -> Sha3_512

-- add bytes to the hash context
Sha3_512.appendBytes : Sha3_512 -> Bytes -> Sha3_512

-- all done, convert to raw `Bytes`
Sha3_512.finish : Sha3_512 -> Bytes
```

We'd have very similar functions for `Sha3_256` and other hashing functions we want to support. No fancy types. If you want to abstract over the hashing function, you can do so with pure Unison code (just a record of functions will do).

## HMAC

These would go in `crypto`. Based on https://hackage.haskell.org/package/cryptonite-0.27/docs/Crypto-MAC-HMAC.html

```Haskell
unique type Hash h = 
  { new : h
  , append : forall a . h -> a -> h
  , appendBytes : h -> Bytes -> h
  , finish : h -> Bytes
  }

builtin type Hmac

Sha3_512 : Hash Sha3_512
Sha3_512 = Hash Sha3_512.new Sha3_512.append Sha3_512.appendBytes Sha3_512.finish

hmac.new : Hash h -> Key -> Hmac h
hmac.append : Hmac h -> a -> Hmac h
hmac.appendBytes : Hmac h -> Bytes -> Hmac h
hmac.finish : Hmac h -> Bytes
```

**Comment by stew** [comment]
This looks good, but I'm skeptical of how one would implement `append` that is universally quantified on `a`. In the haskell Library this is accomplished by relying on a typeclass to provide an image of `a` as a byte array, right?

**Comment by pchiusano** [comment]
@stew Unison can support universal hashing for all types, much like it can already support universal equality and ordering. 😀
