### ISSUE TITLE
IO ability not inferred

### ISSUE THREAD

**Issue by fboeller** [unisonweb/unison#1696]
The watch expression in this code successfully evaluates, although it requires the `IO` ability. It prompts once for a line during the evaluation of the watch expression and then keeps this result, even after closing and opening the UCM session. The inferred type of `dialog` is just `Text` but should be `{IO} Text` and therefore should be rejected.

Code: 
```
Ask.provide : '{IO} a -> '{Ask a} r -> r
Ask.provide answer asker =
  h = cases
    {r}                 -> r
    {Ask.ask -> resume} -> handle resume !answer with h
  handle !asker with h

dialog = Ask.provide readLine '("Hi, " ++ Ask.ask ++ "!")

> dialog
```

Output of UCM on file save after entering `abc` for readLine during the evaluation of the watch expression:
```
  I found and typechecked these definitions in ~/src/unison-expect/ask.u. If you do an `add` or
  `update`, here's how your codebase would change:
 
    ⍟ These new definitions are ok to `add`:

      Ask.provide : '{IO} a -> '{Ask a} r -> r
      dialog      : Text

  Now evaluating any watch expressions (lines starting with `>`)... Ctrl+C cancels.

    10 | > dialog
           ⧩
           "Hi, abc!"
```

**Comment by pchiusano** [comment]
If we add an annotation to the handler, it fails to typecheck as expected:

```Haskell
ability Ask where ask : Nat

unique ability Zoot where
  zoot : Nat

Ask.provide : '{Zoot} Nat -> '{Ask} r -> r
Ask.provide answer asker =
  h : Request {Ask} r -> r
  h = cases
    {r}                 -> r
    {Ask.ask -> resume} -> handle resume !answer with h
  handle !asker with h

dialog = Ask.provide 'zoot '("Awesome number: " ++ Nat.toText Ask.ask ++ "!")

> dialog
```

We suspect that without the signature, `h` is getting an inferred type of `Request {Ask,Zoot} r -> r`.

So this seems like an issue with type inference and/or `handle` block typechecking/inference.

Failing transcript is in fix/1696 branch.

**Comment by pchiusano** [comment]
@dolio theory is that this code, when it infers the type of `h`, has a unsolved existential in `et`, which then gets pushed into the ambient context when typechecking `body`, basically giving `body` a free pass to run any ability!

```Haskell
  go (Term.Handle' h body) = do
    -- To synthesize a handle block, we first synthesize the handler h,
    -- then push its allowed abilities onto the current ambient set when
    -- checking the body. Assuming that works, we also verify that the
    -- handler only uses abilities in the current ambient set.
    ht <- synthesize h >>= applyM >>= ungeneralize
    ctx <- getContext
    case ht of
      -- common case, like `h : Request {Remote} a -> b`, brings
      -- `Remote` into ambient when checking `body`
      Type.Arrow' (Type.Apps' (Type.Ref' ref) [et,i]) o | ref == Type.effectRef -> do
        let es = Type.flattenEffects et
        withEffects es $ check body i
        o <- applyM o
        let (oes, o') = Type.stripEffect o
        abilityCheck oes
        pure o'
```

**Comment by dolio** [comment]
Experiment:

    loophole x = cases
      { y } -> y
      { A.a -> k } -> handle k !x with loophole x

Inferred type:

    loophole : ∀ x1 g x. '{g, x1, A} Int ->{g} Request {A, x1} x ->{g} x

So, the type checker is clearly assuming that some arbitrary other abilities are able to be discharged. It's probably just incidental that they end up in `x1` rather than `g`.

**Comment by dolio** [comment]
More experiments:

```
ability A where
  a : Nat

f x = cases
  { y } -> y
  { A.a -> k } -> handle k !x with g x

g : '{e} Nat -> Request {A} r ->{e} r
g x = cases
  { y } -> y
  { A.a -> k } -> handle k !x with g x
```

inference:

```
      f : ∀ g x x1. '{g, A} Nat -> Request x1 x ->{g, A} x
      g : '{e} Nat -> Request {A} r ->{e} r
```

`f` seems completely wrong. It doesn't even seem to know that it's matching on `A` stuff, and that only gets inferred by accident when handlers are recursive. So I think pattern type checking is missing some key piece in these cases.

**Comment by pchiusano** [comment]
That's a good clue. Check out this example:

```Haskell
ability A where
  a : Nat

f x = cases
  { y } -> y
  { A.a -> k } -> 42
```

It infers `f : ∀ x1 x. x1 -> Request x Nat -> Nat`, which is definitely wrong. So yeah, seems like a bug in the pattern match checking.

**Comment by dolio** [comment]
Yeah, I figured that out later as a simpler example, but didn't mention it. It definitely leaves no doubt.
