### ISSUE TITLE
IO.putBytes, Text.toUtf8, Text.fromUtf8 builtins

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1697]
Let's add the following: 

```Haskell
io2.putBytes : Handle -> Bytes ->{IO} ()
Text.toUtf8 : Text -> Bytes
-- returns some message on the left if malformed
Text.tryFromUtf8 : Bytes ->Either Text Text

-- not a builtin, but could be written in pure Unison
io2.putUtf8 : Handle -> Text ->{IO} ()
io2.putUtf8 h t = putBytes h (toUtf8 t)
```

### Question: should we just remove `putText` entirely?

`putText` is not really a thing for file handles... what is the encoding? UTF8? UTF16? Something system specific?? "Something system specific" seems like a bad answer: there's no need for writing to a file handle to invoke magic system environment state to do its job.

If default encodings are a useful thing, we could introduce other builtins like: `defaultEncoding : {IO} (Text -> Bytes)` or some such. Personally, I think that default encodings are bugs waiting to happen... you write some data (in random, system dependent encoding) and then elsewhere read it (in coincidentally, the same system dependent encoding), and then 6 months later read it someplace else (where default encoding differs), leading to crazy errors.

For standard out/in, does `putText` make sense? It seems like the console will support some particular encoding, and that's what you want to be targeting. Ideally you could interrogate the default encoding of the console and use that.

**Comment by aryairani** [comment]
Same conclusion here.  Any "default encoding" stuff would just use `io2.putBytes`.

`putText` doesn't make sense IMO, unless that's just a name that we use instead of `putUtf8`.

Other encodings can be built on top of `putBytes` and `getBytes`.

**Comment by pchiusano** [comment]
@stew is going to work on this, using latest instructions for adding builtins.

Let’s just delete the putText, getText builtin functions per the discussion above.
