### ISSUE TITLE
Roundtrip fails for `cases` syntax for functions with more than 1 argument

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#1737]
At the moment, this compiles but is a bit perplexing:

```
type B = T | F

f = cases 
  (T) (x) -> "hi"
  (x) (F) -> "bye"
```

Add this to the codebase and edit it again. The roundrtip fails with a pattern arity mismatch:

```
type B = T | F

f = cases 
  T x -> "hi"
  x F -> "bye"
```

As it should, since you'd still want to be able to say

```
f = cases
  Some x -> "hi"
  None -> "bye"
```

instead of 

```
f = cases
  (Some x) -> "hi"
  None -> "bye"
```

We could take up the Purescript convention which would separate patterns with a comma:

```
type B = T | F

f = cases 
  T, x -> "hi"
  x, F -> "bye"
```

**Comment by pchiusano** [comment]
I was thinking we might be able to avoid parens for nullary constructors, like Haskell does:

```Haskell
or True x = True
or x True = True
or _ _ = False
```

But Haskell gets away with this by requiring parens even for single argument functions - like `isJust (Just x) = True`. We could do the same for single argument `cases`:

```Haskell
isSome = cases (Some x) -> true
```

But I feel like that's too easy to forget and you don't get great error messages if you forget the parens as @runarorama discovered.

Another option would be to disambiguate based on the arity of the pattern. I think we should rule that out - the parser doesn't have that information available and arguably it probably shouldn't.

So I think we're stuck with the Purescript syntax of using a `,` or some other delimiter between the patterns.
