### ISSUE TITLE
updating churning for unique types

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1758]
ucm should recognize the a new unique type otherwise identical in name and structure to an existing unique type probably has already been added and doesn't need an update.  Currently you can `load` and `update` forever, getting new random keys each time and producing meaningless churn in the namespace history.

Also you can get type mismatches between codebase-only definitions that reference the existing type, and file-only definitions that reference the unintentionally new but otherwise identical unique type in the file.

**Comment by aryairani** [comment]
See #2196

**Comment by pchiusano** [comment]
Is #2196 just a dupe of this or vice versa? They seem to be talking about the same thing.

**Comment by aryairani** [comment]
This one was the problem, #2196 was a proposed solution; forgot to link them though.
