### ISSUE TITLE
Documentation v2 Design Writeup

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1771]
We've learned a lot from the existing documentation support and are ready for version 2. The new documentation type will be more structured and thus easy to give good feedback and errors while authoring, and easy to render to different targets (like rendering as plain text at various widths or HTML or Javascript-y HTML), and will be seamless to write and update. We want it to be delightful experience!

In this design, documentation can be unnamed, added inside double braces `{{ }}` before any definition. 

Within each `{{ }}`, opening another `{{ }}` escapes out to regular Unison code, making it easy to generate documentation fragments programmatically. There's no limit to the nesting, so this is confusing but totally valid: 

    {{ This is a {{ (x -> x) {{ nested }} }} documentation block. }}

Which is equivalent to:

    {{ This is a nested documentation block. }}
    
Here's a more realistic example showing how you might document a definition using an anonymous documentation block. Unlike before, you won't have to add `List.map` to the codebase first before writing the docs:

```
{{
 `List.map f xs` applies `f` to each element of `xs`.
 
 ## Examples
 
 {{ example '(List.map (x -> x*10) [1,2,3,4]) }}
 
 {{ example '(List.map (x -> "hi") []) }}
 
 ## Also see
 
 * @List.filter
 * @List.fold
}}
List.map : (a -> b) -> [a] -> [b]
List.map f xs = 
  go acc = cases
    [] -> acc
    h +: t -> go (acc :+ f h) t
  go [] xs
```

The anonymous documentation before a binding, `List.map` is sugar for `List.map.doc = {{ .. }`, and the `docs List.map` command will look for `List.map.doc` if no documentation is explicitly linked to `List.map`. This avoids a tedious linking step for the most common case where you're following the standard convention of where to put the docs.

In addition, saving a scratch file `blah.u`, UCM (re)generates `blah.u.{md,html}` containing markdown and html rendered versions of any documentation elements declared in the file. So you can easily preview your work without needing to add anything to the codebase.

### Syntax

Within documentation blocks, we do a full parse of the text into an AST like the below (DRAFT, still tweaking). Unlike the current `Doc` type, it's very structured, so it's easy to generate good feedback during authoring and also target multiple backends. I want parse and type errors at the time you're authoring the documentation, not some nonsense or runtime error later when you go to view the documentation.

<details><summary>Proposed documentation AST, still being evolved</summary>

```Haskell
unique[e88630dc5277b2e84086cca85565494ae802862c] type Doc2 f
  = TypeLink Link.Type
  | TypeSource Link.Type
  | TermLink Any 
  | TermSource Any
  | TermSignature Any
  | Evaluate Any
  | Trace Any
  | Example Nat Any -- Example 3 (Any (x y z -> x + y + z)) will render as `x + y + z`.
  | Element (f (Doc2 f))
  -- no need for transclusion, just evaluation will do it
  -- what about anchors?

unique[fadb42d14e8e64c65713c237faf6604fd8aaea40] type Doc2.Element a 
  = Word Text
  | Code a 
  | Bold a 
  | Italic a
  | Quote a
  | Embed Any -- Embed (Any (Img "Rad image alt text" "https://xkcd.com/1433/")) 
  | Block a
  | Blankline
  | Aside (Optional a) a -- Aside title content
  | Folded Boolean a a -- Folded isFolded whenFolded whenUnfolded
  | Link a a -- Link destination title
  | Paragraph [a]
  | Unordered [a]
  | Ordered Nat [a] -- `Nat` is the starting number
  | Section a [a] -- Section title children
```
</details>

Some interesting stuff to note:

* Whitespace is ignored within paragraphs, though blanklines are preserved. For instance `{{ the   dog }}` is just parsed as `paragraph [word "the", word "dog"]`. 
* Inline examples are actually parsed and typechecked. When you write inline `List.map id xs`, this actually gets parsed and when you view docs that make use of inline examples, it will use the latest names and you can be assured as a reader that what's there isn't nonsense. Notes:
  * For raw inline code formatting, perhaps put an `r` immediately before the backticks, as in: ``r`List.map id xs` ``
  * You can start these with multiple backticks and finish with the same number of backticks.
  * In `List.map id xs`, the parser will presume `List.map`, `id`, and `xs` are actual values and during typechecking will complain if they don't exist. If you want any of these to just be variables local to the example, you can say `List.map id $xs`, prefixing that variable with a `$`. (Also idea: treat the function being called as a literal and the arguments as variables by default?)
* The `Embed` element allows open ended embedding of values of various types. Not all renderers will support all embedded elements, and rendering is best effort.

__An important point:__ the parser won't actually generate the AST directly, instead, it will call named functions (like `Doc.paragraph` and `Doc.word`), allowing this syntax to be overridden (even local to a function) for other documentation-like types. We'd have these names be by default bound to functions that produce the above AST though that could be changed by the user if they want.

We can add more syntax and special elements over time. For instance, even with the base syntax, you could do `{{ bold {{hi}} }}` to generate some bold text within a document, but nothing stops us from adding `__hi__` as syntax for that now or later (I'd probably add this one now since it's familiar from markdown and pretty handy, but you get the idea).

## Other notes

The pretty-printer should render documentation source as appropriate.

Open to suggestions on syntax or other bikeshedding!

Since the documentatation is a fully parsed tree, rendering it a different widths or indented is easy (unlike currently, where that logic has gotten pretty complicated and still doesn't work that great). 

We can also render it to HTML or whatever.

What happens to the old syntax? We can keep it around if we want, or delete it. I'd probably keep it around for a deprecation cycle, since it's easier to convert from the old documentation syntax to the new one vs the old documentation AST to the new one (the AST form is hard to edit).

Why `{{`? Any matching brace-like thing will do. The double braces is available and is easy to type, and it looks pretty good to me. Technically, the syntax conflicts with a nested ability list, like you could write `a ->{{IO},{Store Nat}} b`, but that has the same meaning as `a ->{IO, Store Nat} b` so I don't see a downside to stealing this syntax.

**Comment by pchiusano** [comment]
Tagging @runarorama @aryairani @atacratic. 

Also credit: many ideas for this came out of brainstorming session with @runarorama. 🧠😀

**Comment by atacratic** [comment]
Great!  :tada: 

A fuller example would be good, (a) showing more of the features, and (b) showing what idioms really nice documentation will use and how it works out.  

Questions/comments...

>  ```{{ example '(List.map (x -> "hi") []) }}```

Do the examples have to be delayed?  Seems awkward.

> Inline examples are actually parsed and typechecked.

Does the context grow throughout the Doc?  i.e. can I make my doc render something like this?

```
{{
    {{ xs = [1] }}
    And behold!
    {{ List.map (x -> x + 1) xs }}
}}
```

> Whitespace is ignored within paragraphs

Is there a way I can write some text in which whitespace is preserved?  E.g. tables, ascii art.  Bit painful if not.  (Is this what `Block` is for?)

> blah.u.html

Is this just the documentation elements?  Or nicely rendered source code as well?

> the parser won't actually generate the AST directly, instead, it will call named functions (like Doc.paragraph and Doc.word), allowing this syntax to be overridden (even local to a function) 

Every other definition in Unison is rename-able.  Seems like it might not be true of, say, Doc.word?  If you rename it, you can no longer write docs because the parser doesn’t know the new name.  Maybe the parser should know the hash of (the canonical) Doc.word, and then look up a name for it.  

> (even local to a function)

Sounds like a source of puzzlers.

> prefixing that variable with a $

Does that fit with other ways we may also want to use $ ?

> deprecation cycle

Yes please. I have many docs to convert…  I guess you might want a deprecation warning, maybe when [: :] docs are added/updated.

And other stuff...
- Are 'inline comments' still just floating unreferenced Doc2 expressions in a block?  And still significant for hash?  For now I guess.
- Please check that docs round-trip through pretty-print/reparse with no change...  
- Can I escape a {{ ?  So it actually appears in my doc?
- How does `Folded` render in markdown?  
- What is `Trace Any`?
- Should it be `Link a a` or `Link Text a`?  
- Should it be `Unordered` or `Unnumbered`? (they’re still ordered, right?)
- What’s the `Nat` in `Example Nat Any`?

**Comment by aryairani** [comment]
A couple of clarifying questions:

* What’s the difference between `Any` and `Link.Term`?

* I kinda don’t get the whole bullet on “Inline examples”.  Is it even being rendered correctly on Github, or is it missing some backticks?
  * What's "raw inline code formatting" ?
  * What if you never said `` `List.map id $xs` `` and instead said `` `xs -> List.map id xs` ``; would that achieve the same goal?

* Re “The parser won’t actually generate the AST… it will call named functions…” — these are Unison functions?

This sounds great!

**Comment by pchiusano** [comment]
Thanks for taking a look @aryairani and @atacratic

> Do the examples have to be delayed? Seems awkward.

For an example you want to show both the source and the evaluated result, so yes, it has to be delayed I think - otherwise the renderer will just have the evaluated result. `example` is just an ordinary function here, which anyone could write, which makes this very flexible. That said, maybe examples are such a common case that they warrant some special syntax.

> Does the context grow throughout the Doc? i.e. can I make my doc render something like this?

No, that won't work. Each thing in `{{ }}` is just a single expression - there's no binding structure that spans "the whole document". 

> Is there a way I can write some text in which whitespace is preserved? E.g. tables, ascii art. Bit painful if not. (Is this what Block is for?)

There definitely should be. Just needs some syntax.

> blah.u.html Is this just the documentation elements? Or nicely rendered source code as well?

I mean, why not both, but the more pressing thing is the docs, since you want to be able to inspect the rendering during authoring.

> Every other definition in Unison is rename-able. Seems like it might not be true of, say, Doc.word? If you rename it, you can no longer write docs because the parser doesn’t know the new name. Maybe the parser should know the hash of (the canonical) Doc.word, and then look up a name for it.

This is what we do now for the current doc type, but I don't really like it. It makes the syntax too rigid and tied to a particular data type - the parser becomes dependent on that particular data type. I want to be able to override the syntax and evolve what it points to and I think others should be able to do the same. 

> (even local to a function) Sounds like a source of puzzlers.

I'd probably pick names like `syntax.documentation.word` or some such that no one is going to be accidentally renaming or picking as local variable names. 

> prefixing that variable with a $ Does that fit with other ways we may also want to use $ ?

Good catch - `$` is a valid operator.

> Yes please. I have many docs to convert… I guess you might want a deprecation warning, maybe when [: :] docs are added/updated.

And other stuff...

> Are 'inline comments' still just floating unreferenced Doc2 expressions in a block? And still significant for hash?

Yeah, that is orthogonal to this proposal.

> Please check that docs round-trip through pretty-print/reparse with no change...

Yup

> Can I escape a {{ ? So it actually appears in my doc?

I was thinking `\{{`, and then `\\` for a single backtick.

> How does Folded render in markdown?

It could use the `<details>` tag maybe, or just pick the branch that's selected

> What is Trace Any?

Totally made up - it would show an explorable evaluation trace of that expression! 

> Should it be Link a a or Link Text a?

I considered both and am still not sure. There's the link destination and how the link is displayed. How it's displayed should definitely be another doc, and the link destination you also might want to be something other than a url - like a link to a Unison definition. But maybe that is overkill / have a separate element for that.

> Should it be Unordered or Unnumbered? (they’re still ordered, right?)

Yeah, or maybe "Bulleted".

> What’s the Nat in Example Nat Any?

An example could be a lambda, like `x y -> x`, so you need to know which of the lambda's parameters are to be hidden when rendering. So `Example 0 (Any (x y -> x))` will render as `x y -> x`, while `Example 1 (Any (x y -> x))` will render as `y -> x`.

> What’s the difference between Any and Link.Term?

`Any` can contain any value, while `Link.Term` only refers to named definitions in the codebase. Using `Link.Term` is limited as it forces you to declare your examples and such elsewhere, outside the document. Which is a pain for very short examples.

> I kinda don’t get the whole bullet on “Inline examples”. Is it even being rendered correctly on Github, or is it missing some backticks?
> What's "raw inline code formatting" ?
I'll try to go back and clarify the original text here and fixup any formatting.

> What if you never said `List.map id $xs` and instead said `xs -> List.map id xs`; would that achieve the same goal?

Well, when you render that in the docs, do you actually want to show the lambda that introduces `xs`? Probably not. It's just a variable you're making up to stand for an arbitrary expression. Like when you write:

    Satisfies the property that `List.map id xs == xs`

If the rendered version shows the `xs` being introduced explicitly, that's ugly and not what a person would write or want to read.

> Re “The parser won’t actually generate the AST… it will call named functions…” — these are Unison functions?

I realize this wasn't explained too well but maybe my earlier reply to Chris helps some. Short answer is yes, the syntax desugars to calls to named functions. So changing what that syntax means just requires changing what those names refer to. 

This is sort of a neat general idea that I didn't come up with and it can be used for other syntax customization. Like you could have `[1,2,3]` desugar to calls to `syntax.list.empty` and `syntax.list.cons`. We can have `base.syntax.list.empty` and `base.syntax.list.cons`, but then you could have `arya.syntax.list.empty` and `arya.syntax.list.cons`, and folks could `use arya` to get your definitions to control what list literals mean.

**Comment by pchiusano** [comment]
Simon got me thinking about annotating and commenting source code. I'm trying to figure out if this is something to design for in the new docs format (even if we don't do anything with it yet) or if is a separate concern (like it's just metadata, or just some stuff stuck in the AST). Exploring that here.

There's a few kinds of use cases here that are related but distinct:

* Writing API docs for types and functions. I feel like this is pretty well covered by the new doc type so I'm not going to say more about it here.

There's other use cases which require the ability to attach annotations to specific subexpressions: 

* Commenting your code. Not documenting functions or types, but things like explaining details of the implementation that aren't obvious from just the code alone.
* Detailed code annotations as part of a tutorial. Looking at https://wattenberger.com/blog/react-and-d3 for inspiration.
* Code annotations as part of code review. Looking at GitHub PR process for inspiration. It seems like code review might be handled just with the codebase-ui and its ability to link to segments of code.

Here are a few options for how annotations could be attached (not necessarily mutually exclusive):

1. Annotations are somehow embedded in the AST. This might be as simple as having a function `annotate : a -> b -> b` which behaves like `_ b -> b` but gets displayed in a special way, and is perhaps normalized away before hashing if we didn't want annotations to affect hashes.  
2. Annotations are just metadata stored completely separate from terms and types.
3. Annotations are part of docs: when a doc transcludes some source, it can attach annotations to subexpressions of that source, like using a `[(Path, Doc)]` list.

If we were doing option 3, we should design for it now. If we're doing 1 and/or 2 we can delay thinking about this until later. So, thinking this through:

* Docs reference definitions by hash. The set of metadata that's attached to that hash might differ in the namespace where the doc is viewed vs the namespace where the doc was written.
  * This seems pretty good for things like source code comments - when looking at a definition, you might be happy to just look at it in /latest or whatever namespace and see whatever the most recent attached comments are. 
  * I think this also works well for code review if we wanted code review artifacts to live in Unison - I generally want to just see all the latest review comments associated with a hash. And when comments are resolved, they can be deleted from the namespace (but still found in the history) or archived.
  * However, when I'm writing a tutorial that includes detailed walkthroughs of code snippets, I want to select annotations much more carefully, since the rest of my document may have prose that depends on information included in those annotations ("as we showed in the annotated code snippet above, the AbstractSingletonProxyFactoryBean can really do it all"). 

A couple possibilities for freezing the annotations for the tutorial use case:

* My tutorial link can use a specific namespace hash, meaning it will always look the same when viewed in the context of that namespace. The problem here is that I may have other parts of my document where I explicitly do want to see the latest names for things.
* An `@annotatedSource` documentation element. Syntax might be something like: `@annotatedSource{type Foo @ tutorial.sample1.note1 tutorial.sample2.note2 authors.alice }`. 

I like this second option. The annotations are just a list of terms which the doc renderer might do something intelligent with: 

* For instance, one might annotate source with its author and license, and a renderer might have a little caption at the bottom that gives proper attribution and links to the license.
* A `unique type Note = Note Path Doc2` might be given as an annotation to supply rich commentary or remarks on a piece of code. The design of the `Path` type to index into subexpressions is TBD.

An `@annotatedSource` element seems easy to add to the Doc AST so I think I'm going to go for it.
