### ISSUE TITLE
Destructuring bind requires parens (unless there's a guard)

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#1772]
There's a transcript in the repo (unison-src/transcripts/destructuring-binds.md), showing this example, which works fine.

```unison
ex3 =
  Some x | x > 10 = Some 19
  x + 1
```

```ucm

  I found and typechecked these definitions in scratch.u. If you
  do an `add` or `update`, here's how your codebase would
  change:
  
    ⍟ These new definitions are ok to `add`:
    
      ex3 : Nat

```
But if I delete the guard then it doesn't work.

```unison
ex3' =
  Some x = Some 19
  x + 1
```

```ucm

  I'm not sure what x means at line 3, columns 3-4
  
      3 |   x + 1
  
  Whatever it is, it has a type that conforms to builtin.Nat.
  

```
You need parentheses to make it happy, which is non-obvious.

```unison
ex3' =
  (Some x) = Some 19
  x + 1

```

```ucm

  I found and typechecked these definitions in scratch.u. If you
  do an `add` or `update`, here's how your codebase would
  change:
  
    ⍟ These new definitions are ok to `add`:
    
      ex3' : Nat

```
Would be better if the parens weren't needed?  Either way it's tricky that it depends on the presence of a guard.

(trunk@b586abb)

[destructure.md.txt](https://github.com/unisonweb/unison/files/5719578/destructure.md.txt)
[destructure.output.md.txt](https://github.com/unisonweb/unison/files/5719579/destructure.output.md.txt)

**Comment by pchiusano** [comment]
It's ambiguous: is Some x = Some 42 defining a function called Some with one parameter or doing a destructuring bind? Currently it's treated as a function definition and I think that's the right move - you should be able to define uppercase functions.

I think there was some discussion of this in the PR that introduced this feature. A way to avoid the ambiguity is use a different symbol than = for destructuring bind. But I am not a fan of that.

I'm inclined to close this and treat it as a quirk of the syntax. We could document it better though. WDYT?

**Comment by atacratic** [comment]
Ah yeah.  (You mentioned it [here](https://github.com/unisonweb/unison/pull/1700#pullrequestreview-497813278).)

I think the PR didn't quite surface this enough because the examples focused on tuples: `(a, b) = x`.

I'm looking at some code I wrote, 

```
  (Door open locked) = get
```

and thinking that it's weird that `( ) =` is so different to just `=`.  Usually adding parens doesn't cause a big change of meaning, but just controls associativity.  I dunno, maybe I can get used to it.  Does feel like it might be a bit of a learning hazard for people though.  

Also thinking that this is not some edge case either - doing this is going to be pervasive in people's code.  

So I would say maybe have another think about `Door open locked <- get`.  (But yeah, if not, a helpful error message and more docs would be good.)

**Comment by atacratic** [comment]
Idea, possibly dubious: if the names on the left hand side are not mentioned on the right, then take it as a destructuring bind.

I still think I prefer <- (and for that to be the only syntax option).
