### ISSUE TITLE
Destructuring bind fails print/parse round trip (parens omitted from LHS)

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#1774]
A function like the following fails a print/parse round trip.

```haskell
f x =
  foo
  (Blah a b) = x
  a
```
The parens get dropped when it's pretty-printed, which changes the meaning, as discussed in #1772 

Transcript....

Let's write a function f with a destructuring bind.

```unison
type Blah = Blah Boolean Boolean

ability Foo where
  foo : ()

f : Blah -> Boolean
f x =
  foo
  (Blah a b) = x
  a
```

```ucm

  I found and typechecked these definitions in scratch.u. If you
  do an `add` or `update`, here's how your codebase would
  change:
  
    ⍟ These new definitions are ok to `add`:
    
      type Blah
      ability Foo
      f : Blah ->{Foo} Boolean

```
```ucm
.> add

  ⍟ I've added these definitions:
  
    type Blah
    ability Foo
    f : Blah ->{Foo} Boolean

.> view f

  f : Blah ->{Foo} Boolean
  f x =
    foo
    let
      Blah a b = x
      a

```
It's come out with no parens on the left hand side of the bind (plus with an extra let block).  That's going to cause a problem when we feed it back in for the round trip.

```unison
f : Blah ->{Foo} Boolean
f x =
  foo
  let
    Blah a b = x
    a
```

```ucm

  I'm not sure what a means at line 6, columns 5-6
  
      6 |     a
  
  Whatever it is, it has a type that conforms to builtin.Boolean.
  

```

[destructure-print.md.txt](https://github.com/unisonweb/unison/files/5719849/destructure-print.md.txt)
[destructure-print.output.md.txt](https://github.com/unisonweb/unison/files/5719850/destructure-print.output.md.txt)

(trunk@b586abb)

**Comment by pchiusano** [comment]
Fixed by https://github.com/unisonweb/unison/pull/2390
