### ISSUE TITLE
use stack to install ghc in CI

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1782]
I noticed when trying to update from 8.8.3 to 8.10.3 that I needed to update the version both in `stack.yaml` and in several spots in `ci.yaml`. Should we not just use `stack` to install whatever version of ghc is specified in the resolver?  Alternatively, can we set a variable with the ghc version in `ci.yaml`?

/cc @mitchellwrosen (Sorry I think you answered this once, but I lost it.)

**Comment by mitchellwrosen** [comment]
That seems reasonable, the original reason for switching to `ghcup` to install GHC is given here: https://github.com/unisonweb/unison/pull/1761

**Comment by aryairani** [comment]
Oh right! — Thanks.

**Comment by aryairani** [comment]
@mitchellwrosen Do you have some time to knock this one out?  We should prioritize stack since the cabal build still isn't officially maintained/supported.

**Comment by mitchellwrosen** [comment]
Sure, I can take care of it
