### ISSUE TITLE
Spurious type error in this abilities checking example

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1792]
@dolio this might be connected to / fixed by #1185.

```Haskell
unique ability A where zoot : x
unique ability Stream e where tell : e -> ()

f1 : '{A, g} x ->{g} x
f1 ax = todo ()

toList.handler : Request {Stream a} r -> [a]
toList.handler _ = todo ()

f3 : '{Stream Text} ()
f3 _ =
  go _ = emit 1
  _ = handle f1 go with toList.handler
  emit "hi"

  -- The expression in red  needs these abilities: {Stream base.Nat, Stream base.Text}, but this location only has access to these abilities: {Stream base.Nat, Stream base.Text}
  --   16 |   _ = handle f1 go with toList.handler
```

The error message is confusing, but what I suspect is going on is that the `g` parameter in `f1 go` is being instantiated to all of ambient at its call site, which includes `{Stream Nat, Stream Text}` since the `toList.handler` is pushing an extra `Stream a` onto the ambient stack. This results in an ability check failure because the ability checking looks for a head match only: the `Stream Text` ends up getting subtyped with `Stream Nat` and the typechecker can't pick out the correct `Stream` in the ambient.

It seems like you want to instantiate `g` to just `{Stream Nat}` which is the only ability actually used by `go`, rather that instantiating it to all of ambient.

**Comment by dolio** [comment]
Isn't this also a problem because `{Stream Nat, Stream Text}` makes no sense? There's no way to distinguish ability requests based on an instantiation of a type parameter, so it shouldn't be possible to have two different instantiations of the same ability in play at the same time, right?

**Comment by pchiusano** [comment]
@dolio ooh good point. Maybe the fix is as simple as: when pushing an ability onto the ambient stack, delete anything below it that shares the same head. In this case, that would delete the ambient `{Stream Text}` and push `{Stream a}` for a fresh existential `a'` (which would later get solved to `Nat` when the `emit 1` is hit.

That seems simple enough, but I was think about handlers with signatures like: `Request {Stream a, g} r ->{g} r`. What do you do when pushing the unsolved `g` onto ambient? Just leave it there?

So maybe a more robust fix is: whenever you change the ambient, either by pushing onto it, or by solving existentials, you go through it from top to bottom and remove any entries in the ambient with duplicate heads.

I feel like this could use more thought, but I think you are on the right track that you should not ever end up with an ambient where there's duplicate heads.

**Comment by dolio** [comment]
Hey, I was just looking into this.

I think what is being displayed is just confusing (assuming your setup is comparable to the one I was testing in). There are two `Stream` abilities in play. One from base, and one declared here. The one you declared here has `tell` as the request, but your functions used `emit`. So both abilities are involved, but it's unclear which is which.

When I just use `tell` and rename the ability to make sure the name resolution unambiguous, it works fine.

**Comment by pchiusano** [comment]
Ah, good catch.

We could do with a better error message in this case, but that's a separate issue. I'll create something for that.
