### ISSUE TITLE
Slack Invitation Expired

### ISSUE THREAD

**Issue by rlp10** [unisonweb/unison#1799]
Hi folks

When I tried to join the Slack, it said that the invitation had expired. Perhaps it wants updating on the website?

The link I used is: https://join.slack.com/t/unisonlanguage/shared_invite/enQtNzAyMTQ4ODA0MDM4LWYxZTNkMGUxMDEzNTg3NTMxNjMxOGM2Zjg4ODFjM2RhNGY0OGU2NTMzYmQ1YWIwN2Y0YTc1NjQ1NjgzYzEzOWI

I got it from here:
https://www.unisonweb.org/community

Many thanks.

**Comment by pchiusano** [comment]
Thanks so much for reporting this! Will fix momentarily.

**Comment by pchiusano** [comment]
Okay, https://unisonweb.org/slack is the new canonical URL for the slack invite, and is linked from the community page. Thanks again for reporting!

**Comment by rlp10** [comment]
No worries - now I get to pester you all with newbie questions on Slack! :)

**Comment by pchiusano** [comment]
Haha, great! Welcome :)

**Comment by FlorianBELLAZOUZ** [comment]
It's the case again :
https://unisonlanguage.slack.com/join/shared_invite/zt-8yk99oli-8ePQ4QE1h1MWMYxviIHD2g#/
"This link is no longer active
To join this workspace, you’ll need to ask the person who originally invited you for a new link."

From the website https://www.unisonweb.org/community
And from the Readme

**Comment by pchiusano** [comment]
Thanks for reporting, give it a few minutes for site to rebuild, then https://unisonweb.org/slack should work again. I set the link to "never expire" but I thought I did that before. Hopefully this will do it but definitely report if you are having trouble.

I'll reopen this but can you comment and close the issue assuming that it's been fixed?

**Comment by FlorianBELLAZOUZ** [comment]
It's work ! :) 
Thanks !
