### ISSUE TITLE
Transcript parser occasionally leaves out a trailing backtick

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1809]
As in, the input file has `` `foo` `` but the output looks like `` `foo ``. Example is here: https://github.com/unisonweb/unison/pull/1808/files#diff-49f174e20f1f6d21f42d2210d20568b37501cee5b6d789d4e622385b9fe5686bR33

Note to self, the transcript parser could make use of `manyTill` combinator, which I didn't know about at the time I wrote the transcript parser originally. So the current parser has some weird logic where it temporarily pauses whenever it hits a backtick, in case that one backtick is followed by two more backticks. 

Doing ````manyTill anyChar (string "```")```` would probably fix this and be simpler to boot.

**Comment by sellout** [comment]
This issue still exists, but the linked transcript is no longer valid. Here’s a close one that behaves the same:
````
This transcript tests that UCM can always access the definition of
`IsTest`/`isTest`, which is used internally.

```ucm
.> builtins.merge
```

```unison:hide
test> pass = [Ok "Passed"]
```

```ucm
.> add
.> dependents pass
```

The definition and type of `isTest` should exist.
````

<details>
<summary>And here’s the output</summary>

````
This transcript tests that UCM can always access the definition of
`IsTest`/`isTest`, which is used internally.

```ucm
.> builtins.merge

  Done.

```
```unison
test> pass = [Ok "Passed"]
```

```ucm
.> add

  ⍟ I've added these definitions:
  
    pass : [Result]

.> dependents pass

  pass has no dependents.

```
The definition and type of `isTest should exist.
````

</details>
