### ISSUE TITLE
Builtin function to switch off I/O at the runtime level for a thunk's evaluation

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1818]
```Haskell
builtin withoutIO : '{g} a ->{g} a
```

This will crash the runtime much like calling `bug` if the `{g} a` attempts to perform any I/O.

Conceptually, a Unison node server will in a loop deserialize computations sent to it over the network, negotiating any missing hashes, and then runs each computations using some top level handler. You don't want remote computations to be able to perform arbitrary I/O, and while the typechecker prevents this, someone can bypass the typechecker and send a node server some bytes that correspond to a program that does I/O.

I/O is special in this way, because it is opaque and is typically just interpreted directly. Other abilities which someone tries to sneak in and aren't supported by the remove server will just bomb with an unhandled request exception, which is fine.

**Comment by ceedubs** [comment]
We now have a slightly different solution to this use case. We have tracked builtins and validateSandboxed. I'm going to close this out, and if there are remaining items we can open a more targeted issue.
