### ISSUE TITLE
Self-contained binaries

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1819]
Add a command to UCM, `compile`, which takes a `main` function and produces a single self-contained binary.

It would have to embed the runtime and the `main` function and all its dependencies.

Currently `IO` is missing access to environment variables and command line arguments, so we'd need to add that as well.

**Comment by pchiusano** [comment]
We've had multiple people say that this would be really great and make Unison easier to deploy, use for scripting, little services etc. Rust and Go have benefited from this.

Also it would be great if this could do cross-compilation to other architectures.

**Comment by stew** [comment]
Huge +1 from me. I think that this would be enormous for what it would do for getting people actually using unison.

**Comment by ceedubs** [comment]
And unlike a lot of languages, the binary would only have to include terms depended on (directly or transitively) by the specified `main` function, right? No more including support for printers and CORBA just because they were added to the standard library at some time in the past?

**Comment by pchiusano** [comment]
First step: design jam to figure out how to do this. @aryairani and @pchiusano both some ideas.

**Comment by aryairani** [comment]
My suggestion for self-contained binaries is to not create a self-contained binary—which, when it's not native code, is hard both to create and to execute—and to instead create a [shebang file](https://en.wikipedia.org/wiki/Shebang_(Unix)), _e.g._:

```
#!/usr/bin/env unison-run
<compiled program data...
...
...>
```

When the user's system "executes" this file, it will launch `unison-run <path-to-this-file>`. `unison-run` is an executable we need to publish, that will ignore the first line of the file, and execute the rest.  (We could also just use `ucm` for this purpose.  `#!/usr/bin/env ucm run-binary`)

**Comment by pchiusano** [comment]
This still needs some design. Originally I was thinking: just serialize the term and its dependencies, and this functions as the "bytecode" for Unison. That would totally work, but we might want the compiled form to just get `mmap`'d in and lazily decoded, reducing startup time.

**Comment by pchiusano** [comment]
Did some jamming on this with @dolio 

Idea 1: could have a separate executable, `unison-rt`, which is just given an empty `CodeLookup`. It deserializes a self-contained  file with a term (assumed to be of type `[Text] ->{IO} ()`) and all its dependencies. Using [this function](https://share.unison-lang.org/@roa59i6g321fr95kk9o6arnt183bsci46go5v03gno76usq5ru6l87llt57u2i99raa1s580i1dttpf9a38akhh00m4fsceqip4aqbg/terms/builtin/Value/serialize). Call this the "bytecode file".

Idea 1a: Idea 1, but mmap the file and lazily decode as definitions as needed. Would need some sort of index at the front of the file, `Map Reference (Position, NumBytes)`. Could maybe use lazy I/O. Seems complicated.

Idea 2: a custom `CodeLookup` that directly read the bytecode file. Issue with this is it's going to be doing compilation of the code.

Idea 3: [compact regions](https://github.com/ezyang/compact). 

The compact regions stuff seems the most promising so @dolio is going to investigate that.

New ucm command: `compile foo`, where `foo` should have type `[Text] ->{IO,Exception} ()`. Creates `foo.uc`, a compiled Unison file. This will be specific to the version of Unison, so these files aren't meant to be long-lived, and it should do a version check on startup when running one of these files.

Could add a subcommand to ucm, `ucm run.compiled foo.uc`.

Could add a separate executable, `unison-rt foo.uc`.

Probably should just do both.

**Comment by ceedubs** [comment]
@pchiusano is this available now? Are there some instructions on how to use it?
