### ISSUE TITLE
Allow multiple commas between elements of a list, and allow a trailing comma

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1841]
This comes up when rearranging or deleting elements of a list. I can't see any reason not to just allow ignored optional commas. The current UX is you get an annoying or cryptic parse error. Once the code gets added to the codebase, it will get nicely formatted with the proper number of commas but it's okay to have some sloppiness at parse time.

You can check out `Parser.seq` in `Parser.hs` which is the only place that would need modification I think.

```Haskell
seq :: Ord v => (Ann -> [a] -> a) -> P v a -> P v a
seq f p = f' <$> reserved "[" <*> elements <*> trailing
  where
    f' open elems close = f (ann open <> ann close) elems
    trailing = optional semi *> reserved "]"
    sep = P.try $ optional semi *> reserved "," <* optional semi
    elements = sepBy sep p
```

**Comment by ceedubs** [comment]
I'm 👍 on allowing a trailing comma. I've used this pattern in other languages and have never seen it cause issues.

Multiple commas between elements seems a bit weirder to me. But the fact that the code will be stored as an AST and the commas will quickly become irrelevant is pretty intriguing. Since `,` isn't a valid identifier in Unison I can't _think_ of a way that this could cause trouble.

**Comment by asoltysik** [comment]
Also a big 👍 on the trailing commas. As for multiple commas I don't recall ever having a syntax error caused by that in the past, so no opinion on that.

**Comment by pchiusano** [comment]
Great! Well, PR welcome. 😀 

There's some subtlety to avoid committing to expecting another element after each comma and allowing a closing brace (or another comma). May need to use lookAhead combinator and/or notFollowedBy.

**Comment by maralorn** [comment]
I think having a lenient parser is just one of the luxuries unison can afford. If we later think that it steals syntax we want for something else. (idk. list sections maybe?) then we can still change that and no ones code will break.

**Comment by stew** [comment]
after having gotten used to being able to have trailing commas I want the to always be valid!!!! (I've also never considered multiple commas in a row, which seems weird but not enough to object to)

**Comment by aryairani** [comment]
Multiple commas in a row useful for when you don't want to think too hard about how you are mixing 
```
, x
, y
```
-style lists with 
```
x,
y,
```
-style lists.

then there's also 
```
x
,
y
,
z
```
-style lists

which might become
```
x
,
-- y
,
z
```

**Comment by aryairani** [comment]
I'd also allow initial commas if we're doing all the rest

**Comment by JohannesHuster** [comment]
I also like the idea of allowing those cases at parse time 👍 

I’ve added a [PR](https://github.com/unisonweb/unison/pull/1850) for this and introduced myself on [Slack](https://unisonlanguage.slack.com/archives/CNZTD4DJS/p1616510098011200) 🙂 I went with allowing multiple commas leading, trailing and in between elements. But that would be quick to adapt.
