### ISSUE TITLE
ready-to-merge Github Label no longer readies to merge?

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1861]
We had been using `.mergify.yml` and the `ready-to-merge` Github Label to mark PRs that had been approved "pending CI success" to be merged automatically upon CI success.  But, it no longer happens, and we're back to merging manually.

So the question is: why, and how do we fix it?

**Comment by pchiusano** [comment]
I think it stopped working when we switched to GitHub actions for the build, but I'm not sure why.

**Comment by aryairani** [comment]
I'm gonna try updating the yaml according to: https://docs.mergify.io/conditions/#about-status-checks
