### ISSUE TITLE
`Bytes.at 0` always returns None

### ISSUE THREAD

**Issue by asoltysik** [unisonweb/unison#1888]
*Version*: devel/M1l-1068-gb0dd6e549 (almost latest trunk)
Same results with `--new-runtime` and without it.

How to reproduce:

```
    1 | > Bytes.fromList [77, 13, 2] |> Bytes.at 0
          ⧩
          None
```

```
    1 | > Bytes.fromList [77, 13, 2] |> Bytes.at 1
          ⧩
          Some 13
```

**Comment by pchiusano** [comment]
Wow thanks for the report! There's probably something silly in Bytes.hs and then we should improve the testing of that type. 

Here's the relevant section of Bytes.hs: https://github.com/unisonweb/unison/blob/65a8ff839d5b06699c3ce282155db17e115d7396/parser-typechecker/src/Unison/Util/Bytes.hs#L83

And here's the current unit tests: https://github.com/unisonweb/unison/blob/trunk/parser-typechecker/tests/Unison/Test/Util/Bytes.hs

**Comment by pchiusano** [comment]
This is weird. I'm able to reproduce within a transcript but not when I just run in a scratch file:

```
  Now evaluating any watch expressions (lines starting with `>`)... Ctrl+C cancels.


    2 | > Bytes.fromList [77, 13, 2] |> Bytes.at 0
          ⧩
          Some 77
```

See fix/1888 branch.

**Comment by pchiusano** [comment]
Okay, I figured out the inconsistency - the bug is in the new runtime, but once cached, the watch expression isn't recomputed. So if you happen to use the old runtime after the new, you'll get the (incorrect) cached value again.

You can do: 

```
rm -rf ~/.unison/v1/watches/_cache/  
```

to clear the cache.

It works correctly with the old runtime.
