### ISSUE TITLE
Errors in Map.fromList

### ISSUE THREAD

**Issue by asoltysik** [unisonweb/unison#1901]
Working minimal case:
```
> Map.fromList [(1, "a"), (2, "b")]
```
Result:
```
    1 | > Map.fromList [(1, "a"), (2, "b")]
          ⧩
          Bin 2 1 "a" Tip (Bin 1 2 "b" Tip Tip)
```

Failing minimal case:
```
> Map.fromList [(1, "a"), (2, "b"), (3, "c")]
```
Result:
```
dumpData: bad closure: Foreign (Wrap ##Sequence _)
```

It doesn't seem to be exactly related to number of elements. For example this doesn't throw an error
```
> Map.fromList [ (774, "MACADDR"), (774, "MACADDR8"), (3614, "TSVECTOR"), (3615, "TSQUERY") ]
``` 
but it produces an incorrect result (the map contains only the last entry from the list).:
```
    1 | > Map.fromList [ (774, "MACADDR"), (774, "MACADDR8"), (3614, "TSVECTOR"), (3615, "TSQUERY") ]
          ⧩
          Bin 1 3615 (Cons "TSQUERY" ()) Tip Tip
```

However this one throws an error. Notice that the only thing that changed is that the first key became `773` instead of `774`:
```
> Map.fromList [ (773, "MACADDR"), (774, "MACADDR8"), (3614, "TSVECTOR"), (3615, "TSQUERY") ]
```

No idea whether the "bad closure" error and the incorrect result error are related.

**Unison version:** devel/M1l-1068-gb0dd6e549 (close to current HEAD of trunk)
**New runtime:** yes

**Comment by pchiusano** [comment]
Thanks for reporting. It looks like Map.fromList does weird things with duplicate entries. That is just a bug in base. @runarorama can take a look.

The runtime error sounds like an unrelated decompilation bug - watch expressions get decompiled back to terms before being printed.

**Comment by pchiusano** [comment]
Update on this, #1910 should fix the `bad closure` error. Still digging on the other issue. 

@dolio can you check this example when you fix the `||` compilation issue that we spotted?

**Comment by pchiusano** [comment]
Fixed in trunk
