### ISSUE TITLE
`-codebase` option is ignored on trunk

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1905]
Regression that may have been introduced in #1900 ?

```
~/unison [trunk●] » stack exec unison -- -codebase mycodebase init
Initializing a new codebase in: /Users/pchiusano/unison/mycodebase

~/unison [trunk●] » stack exec unison -- -codebase mycodebase     
Invalid option `-codebase'
Usage: unison [--token STRING] [--host STRING] [--port NUMBER] [--ui DIR]
```

So `init` works fine but then I can't start ucm using the initialized codebase. 😬

@aryairani speculated -

> I wonder if the server is somehow inspecting all of the command-line args and blowing up when it encounters
>`-codebase`?  But I don’t see that happening anywhere.

Grepping for `getArgs` the only place I see that called in our code is in `Main.hs` (and `Transcripts.hs`, another main). Could Servant be doing something weird, assuming it can parse all the command line args?

```Haskell
      Server.start theCodebase $ \token port -> do
```

Aside: `getArgs` is pretty janky as an interface to command line args. I don't get why Haskell didn't just make the type of `main :: [String] -> IO ()` and instead chose to make args globally available to anything that does IO.

**Comment by pchiusano** [comment]
Once this is addressed @aryairani is unblocked on getting #1895 merged.

**Comment by aryairani** [comment]
Side note that the `Usage:` message that gets printed seems very server-specific; I initially thought it meant I was picking up some completely non-ucm-unrelated `unison` executable on my path.

**Comment by aryairani** [comment]
`-codebase` isn't the only flag that triggers the error:
```
% stack exec unison -- --old-codebase
Invalid option `--old-codebase'

Usage: unison [--token STRING] [--host STRING] [--port NUMBER] [--ui DIR]
```
