### ISSUE TITLE
UCM crashes when encountering malformed pattern matches 

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#1931]
If you "forget" a case in your pattern match like so: 
```
ability Abort where
  abort : x
toOptional : '{Abort, g} a ->{g} Optional a
toOptional a = handle !a with cases
  { Abort.abort -> _ } -> None
> toOptional '(1 + abort)
```
ucm will crash with the following error message: 
```
expandBindings': more patterns than expected ([Var],[])
CallStack (from HasCallStack):
  error, called at src/Unison/Runtime/ANF.hs:1234:19 in unison-parser-typechecker-0.0.0-2dM7tNDqeOvDQFHAl25PFL:Unison.Runtime.ANF
``` 

Another example exposing a similar issue: 
```
ability Abort where
  abort : x
  z : Int
toOptional : '{Abort, g} a ->{g} Optional a
toOptional a = handle !a with cases
  { a } -> Some a
  { Abort.abort -> _ } -> None
> toOptional '(1 + abort)
```
will crash with the following error message 
```
unison2: too few patterns for effect bind
CallStack (from HasCallStack):
  error, called at src/Unison/Runtime/Pattern.hs:547:25 in unison-parser-typechecker-0.0.0-2dM7tNDqeOvDQFHAl25PFL:Unison.Runtime.Pattern 
  ```

version: devel/M1l-1394-gc9ce5906d

**Comment by pchiusano** [comment]
The workaround if you encounter this is to make sure your handler covers all the operations of the ability it handles, though obviously the user should get a nice error message in that case, not a crash. 

```Haskell
  { a } -> todo "pure case"
  { Abort.abort -> resume } -> todo "abort case"
  { Abort.z -> resume } -> todo "z case"
```

Note that this crash is happening during compilation of the handler--it doesn't matter if the unhandled operations are never used by the computations being handled.

Long-term, it would be preferable to make this a type error via #913.
