### ISSUE TITLE
Uncons and Unsnoc returning incorrect types

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#1934]
In the new runtime uncons and unsnoc return `Some (Cons ?h "i")` instead of `Some ?h "i"` as expected 

```
> Text.uncons "hi"
           ⧩
           Some (Cons ?h "i")
```

Later, when pattern matching on these values, this was what was causing the error messages like `  dumpData: bad closure: Foreign (Wrap ##Text "bcdefg?")` to surface.

**Comment by pchiusano** [comment]
Also here's `unsnoc`:

```Haskell
    2 | > Text.unsnoc "abba"
          ⧩
          Some (Cons "abb" ?a)
```

That should be `("abb", ?a)`.

**Comment by pchiusano** [comment]
@dolio I think we should fix this for M2

When you fix, you can add some unit tests for it in `builtins.md`
