### ISSUE TITLE
Decompilation issue when rendering docs

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1940]
Noticed a possible issue with doc rendering, where it produces

```
  cannot decompile an application to a local recusive binding
```

It's weird because I only see the error when calling the doc rendering in a slightly different way than usual, which I wouldn't think would matter at all.

There's a failing transcript in the [fix/1940](https://github.com/unisonweb/unison/tree/fix/1940) branch, see [this file](https://github.com/unisonweb/unison/blob/fix/1940/unison-src/transcripts/bug-strange-closure.md).

```
stack exec transcripts -- bug-strange-closure.md
```

Will run just the failing transcript.

**Comment by dolio** [comment]
I think this is not a runtime bug, at least.

If I perform the steps from the transcript interactively, I can reproduce the problems. If I make the watch cache just `pure Nothing`, things start working every time. So it seems like somehow the cache is causing bad code to be fed into the runtime that results in the subsequent decompilation problems and GHC errors (the latter are just a symptom of running off the end of an array; I got a segfault once, too).

Forcing the watch cache off doesn't make the transcript work for some reason. Do transcripts have their own extra caching somehow?

I'm not really sure yet if it's the caching code itself that's broken (i.e. probably something in the new codebase impl) or if its being told to cache something that's already bad by the output end of the new runtime (e.g. decompiling to a bad term).
