### ISSUE TITLE
ucm display command crashes when displaying Doc2 types containg `@eval`

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#1946]
ucm will exit with the following error 

```
.> display myValue2.doc
unison2.1: DatabaseIntegrityError (NoObjectForPrimaryHashId (HashId 6256)) in getWatch
CallStack (from HasCallStack):
  error, called at src/Unison/Codebase/SqliteCodebase.hs:261:88 in unison-parser-typechecker-0.0.0-2dM7tNDqeOvDQFHAl25PFL:Unison.Codebase.SqliteCodebase
  getCycleLen, called at src/Unison/Codebase/SqliteCodebase.hs:590:38 in unison-parser-typechecker-0.0.0-2dM7tNDqeOvDQFHAl25PFL:Unison.Codebase.SqliteCodebase
```

when the display command for a linked doc definition is called: `display myValue2.doc` 

Code example:
```
{{this is a doc associated with @eval{myValue2}}}
myValue2 = "I am a string2"

{{this is a doc associated with a value}}
myValue = "I am a string"
```

Attempting to display a doc which does not contain an eval command does not appear to trigger this crash. 

version:  devel/M1m-1317-gefa894c4a

**Comment by rlmark** [comment]
Note: this behavior is seen using both the `docs` and `display` commands, on the off chance that provides any further info.

**Comment by pchiusano** [comment]
As a temporary workaround, I suspect `display` will start working again once you add these definitions to the codebase.

**Comment by pchiusano** [comment]
@rlmark This has been fixed in trunk, looks like, or at least I can't reproduce. :) Can you pull latest trunk and try it, and if it's fixed, close this issue?

**Comment by pchiusano** [comment]
```
  I found and typechecked these definitions in ~/unison/scratch.u. If you do an `add` or `update`,
  here's how your codebase would change:
  
    ⍟ These new definitions are ok to `add`:
    
      myValue2     : Text
      myValue2.doc : Doc2

.> display myValue2.doc

  this is a doc associated with `"I am a string2"`
```

**Comment by rlmark** [comment]
The `display myTermName` command in the UCM now works both before and after adding to the codebase. 😸  Closing!
