### ISSUE TITLE
UCM exits if reassigning delayed computation variables in body of function

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#1959]
If you are working with a function with a delayed value as its input and you reassign that parameter to another value anywhere in your function (imagine you're working incrementally towards something and typechecking as you go), as below: 

```
test : 'Text -> 'Nat 
test t = 
  stuffs = t
  '5
```

Unison will exit with the following error message: 

```

  I found and typechecked these definitions in ~/Unison/my-unison-work/scratch.u. If you do an
  `add` or `update`, here's how your codebase would change:
  
    ⍟ These new definitions are ok to `add`:
    
      test : 'Text -> 'Nat

unison2.1: unsupported compound direct letTerm (Tm AVar User "t")
CallStack (from HasCallStack):
  error, called at src/Unison/Runtime/MCode.hs:916:5 in unison-parser-typechecker-0.0.0-2dM7tNDqeOvDQFHAl25PFL:Unison.Runtime.MCode
```
version: devel/M1m-1317-gefa894c4 (This is 1 or 2 days old, so I can recheck if neccesary)

**Comment by pchiusano** [comment]
Thanks for this report! I see the same behavior on trunk. @dolio can you have a look?

**Comment by rjdestigter** [comment]
I think this might be related to what I encountered earlier today https://github.com/unisonweb/unison/issues/1951

**Comment by dolio** [comment]
The thing in the error message doesn't even look like a 'compound direct let,' so hopefully it's just a corner case in a check or something. I'll see if I can knock it out.
