### ISSUE TITLE
`Branch.before` also wants codebase / sql magic treatment

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1961]
to save up to 24 seconds from push to base.

![image](https://user-images.githubusercontent.com/538571/118358288-1f2b3780-b54c-11eb-82eb-604bb1540815.png)

![image](https://user-images.githubusercontent.com/538571/118358300-2a7e6300-b54c-11eb-887c-d68e02f522da.png)

**Comment by pchiusano** [comment]
Note that Branch.before is just Causal.before, which just checks if the LCA is equal to the first argument.

    before :: Monad m => Causal m h e -> Causal m h e -> m Bool
    before a b = (== Just a) <$> lca a b

So this will be an easy little refactoring, no new wizardry needed.

**Comment by aryairani** [comment]
Closed by #1964
