### ISSUE TITLE
error: unknown option `--initial-branch=master' with git version 2.25.1

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1969]
In #1834 we added this flag to suppress a warning that appeared in the newest versions of git, but it's not backwards-compatible with even fairly recent versions of git, which will instead exit with an error.

This came up on a digital ocean box running Ubuntu 20.04.1 LTS.

Possible solutions:
* Revert #1834 and live with the warnings
* Find a way to disable or suppress the warnings and revert #1834
* Programmatically run `git --version`, parse the result, and issue different commands depending on the outcome
* Use a git library rather than a git executable to manipulate the repo; I don't know whether there are any such suitable libraries, but I'd start by investigating [gitlib](https://hackage.haskell.org/package/gitlib).  The good news is that as of v2, we are really only committing one file now, which means less work with the git library; but I suppose we want to preserve whatever `README.md` or other supplemental files a publisher has stored in their repo.
* Stop using Git 😁

**Comment by aryairani** [comment]
relevant: https://stackoverflow.com/questions/55463863/how-to-turn-off-the-help-hints-in-git-output

**Comment by pchiusano** [comment]
I'd say reverting that change and living with the warnings is okay for M2, if that's the easiest thing, and then one of the other options is better for the beta.

**Comment by ceedubs** [comment]
Sorry for the trouble. I don't really have capacity to help with a change at the moment, but I would have no heartburn about reverting the change for now. At some point relying on a global git version might be a problem that we want to address in the various distributions. Or maybe at some point with the new code base format git won't be needed at all?

**Comment by aryairani** [comment]
@ceedubs No worries (it seemed like a good idea at the time) and thanks for the input.  

Yes, at some point git won't be needed at all, because we'll want our own transfer protocol (inspired by git-pack) instead of shipping around full databases anyway; or some other efficient thing.

**Comment by pchiusano** [comment]
For M2 we're just going to revert this and people will see this annoying warning until it's fixed in a more robust way.
