### ISSUE TITLE
Improve running UI for developers of ucm

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#1979]
Running the UI from with `ucm` can be a little annoying as a developer of `ucm` if you're not also a developer of the UI as it involves running the UI dev server etc.

One possible solution could be to have `ucm` provide an error if there are no files in the ui folder it was looking at (either default location, set through args or through env vars) and tell the user that they can either start the UI dev server (with link to the ui repository instructions) or give the user a prompt to download the UI into a `ui` folder in the root of the `unison` project (where `ucm` by default looks for the UI), if the user then accepts this, `ucm` will download into that folder the `latest` tag from the Codebase UI repository and extract the `ucm.zip` into the `ui` folder and then on success provide the user with the URL to start the UI.

**Comment by pchiusano** [comment]
@hojberg feel free to reopen if you think there's more to this than what's done in the dev-ui-install.ah script and that PR.

One limitation I could see is it just fetches the latest release from GitHub, so the code needs to be committed and built by CI.

Though I suppose you could also have the ui path set to some local build directory of the codebase UI if you want the backend to rely on uncommitted or unreleased front end code.

**Comment by hojberg** [comment]
I think we can do a more integrated experience than the script, but it seems fine for now.
