### ISSUE TITLE
Codebase server should maybe dedup based on reference

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1997]
<img width="834" alt="Screen Shot 2021-05-21 at 4 50 26 PM" src="https://user-images.githubusercontent.com/11074/119201618-e52ec980-ba54-11eb-843d-72790739865e.png">

These implementations of `List.map` are all the same.

There might be some front-end work if we want to also show aliases in the find results, like it shows `List.map` (in `.base` and 6 other locations)

**Comment by hojberg** [comment]
This has been fixed in a recent effort.
