### ISSUE TITLE
Build on HalVM

### ISSUE THREAD

**Issue by Ericson2314** [unisonweb/unison#20]
[HalVM](https://github.com/galoisinc/halvm) run Haskell on Xen without an OS. Since unison is all about leaving the Unix world behind, it would be nice if the node could be built on this.

**Comment by pchiusano** [comment]
I've been thinking more about this. I think it could be a good idea. Nodes now run in the same process as the node container, and nodes don't necessarily even need access to an underlying file system, so it seems like it could be possible.

If you are interested in exploring this let me know.

**Comment by pchiusano** [comment]
Hey @Ericson2314 am going to close this for now, but would love to have you another volunteer investigate at some point. I don't currently have bandwidth for it, though.

**Comment by Ericson2314** [comment]
Sounds good. I don't quite either, but I'll definitely keep this at the back of my head.
