### ISSUE TITLE
Update SQLiteCodebase implementation of LCA

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2004]
The empty namespace can technically be the LCA due to how we represent history (all namespaces start out with an empty namespace at the start of their history), but it's basically never the LCA you want. Here's an example:

```
j1: ... - v1 - v2 - v3 - v4 - v4a - v5 - v6 - v7
                                              /
                                  <empty> - v5a

j2: ... - v1 - v2 - v3 - v4 - v4a - x1 - x2 - x3 
                             /    /     / 
                            /  <empty> <empty> 
                        big shallow wide tree
```

This could find `<empty>` as an LCA even though we want v4 as the LCA.

In this PR we avoid returning a Causal.One (a causal with no parents) as the LCA and keep looking.

https://github.com/unisonweb/unison/pull/2002

The sql implementation of LCA needs updating accordingly. I think it's as simple as restricting the query to namespaces with at least one parent.

**Comment by pchiusano** [comment]
Cc @runarorama tracking this loose end to update the sql calculation of LCA

**Comment by aryairani** [comment]
Is there a transcript to test that the LCA implementation is working correctly?  How did #2002 pass without #2004?

**Comment by pchiusano** [comment]
There's not a transcript yet. We just updated some unit tests for the other PR.

We should construct a transcript based on the above sketch. I can work on that if you don't beat me to it.

**Comment by pchiusano** [comment]
@aryairani okay there's a transcript here in #2015 and in the fix/2004 branch
