### ISSUE TITLE
Miscellaneous base issues to fixup

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2024]
Populating this as we go during review with @rlmark

__M2:__

- [x] `alias.type #fgaevis4bl IO.Deprecated` to make sure old IO type has a name of some kind
- [x] `alias.term #ags0v5hfe5#8 Doc.Join` it looks like the name for this was accidentally deleted
- [x] `Exception.*` functions that exist are actually functions on `Throw`. Should move them to `Throw`.
- [x] rename `Throw.raise` to `Throw.throw`
- [x] `forkComp` should be renamed to `fork`
- [x] `io.IO.setBuffering_ : #b7kh3q81n1 -> Optional #u934c4e54d ->{#fgaevis4bl} Either Error ()` should probably be deleted, I think it's an old I/O function
- [x] `io.openFile : FilePath -> Mode ->{#fgaevis4bl} #b7kh3q81n1` should be deleted - old I/O
- [x] `io.IO.openFile_ : FilePath -> Mode ->{#fgaevis4bl} Either Error #b7kh3q81n1` should be deleted - old I/O
- [x] is `io2` a copy of `io`? This might have been fixed in latest base
- [x] There's a bunch of things called `==`, do we want to rename these to `Map.equals`, `Bag.equals` and so on so people can use `==` with no imports? Just do `find ==` to find these. Decision: we're going to leave these as is so people don't accidentally use an incorrect `==`.
- [x] `rename.term Universal.== Universal.===`

__Later:__
- [x] Various helper functions on `Exception`
- [x] review patches, there's one called `Patch` in the root, and there's an empty namespace `patches`
- [x] `Stream.map` and friends are missing, I think this was in an unmerged PR by @anovstrup. Should update that PR to new codebase format and get it merged.
- [x] assign MIT license and Unison computing as copyright holder for all (new) builtins

**Comment by pchiusano** [comment]
@runarorama when you're done with this, can you also do:

```
.> squash trunk .releases._M2
.> fork releases._M2 releases._latest
```

(The releases namespaces are all squashed - no need to fetch history for these.)

That will ensure that these instructions work [in the quickstart guide](https://www.unisonweb.org/docs/quickstart) work - 

```
pull https://github.com/unisonweb/base:.releases._latest base
```

**Comment by runarorama** [comment]
OK, that's done
