### ISSUE TITLE
"Cannot decompile Foreign" when running function with IO 

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#2026]
The following code using IO prints out the error `Cannot decompile Foreign`

```unison
ex = unsafeRun '(printLine "hello world")

Exception.unsafeRun : '{Exception, g} a -> '{g} a
Exception.unsafeRun e _ = 
    h : Request {Exception} a -> a 
    h = cases 
        {Exception.raise fail -> _ } -> 
            bug fail 
        {a} -> a 
    handle !e with h 

```

In the UCM this is the command and error

```ucm
.base.io> run ex
hello world

  cannot decompile Foreign
```

Transcript below: 
[fix2026.md](https://github.com/unisonweb/unison/files/6549641/fix2026.md)

**Comment by pchiusano** [comment]
@dolio working on a self contained transcript for this one currently..

**Comment by dolio** [comment]
I can add the transcript above, but it won't actually display the "hello world" in the transcript output. I guess that's not the part that matters, though.

I should add, I'm not sure there's any better way to test this.

**Comment by pchiusano** [comment]
Right. That's fine, I'd still add it - that transcript previously would produce that weird message in the output.
