### ISSUE TITLE
Ucm exits with "No builtin type called: io2.Failure" when calling new IO functions 

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#2027]
When calling some of the new IO functions (I was experimenting with Sockets so the transcript contains that as an example) the following error will surface and the ucm will exit. 

```
No builtin type called: io2.Failure
CallStack (from HasCallStack):
  error, called at src/Unison/Runtime/IOSource.hs:63:16 in unison-parser-typechecker-0.0.0-6U6boimwb8GAC5qrhLfs8h:Unison.Runtime.IOSource
```

Attached is a transcript which should replicate the issue 
[fix2027.md](https://github.com/unisonweb/unison/files/6550160/fix2027.md)

**Comment by rlmark** [comment]
Also this transcript involves includes pulling all of the `base` library (🕐 ) but it's actually material for the error to surface.

**Comment by pchiusano** [comment]
@dolio I see what's going on - the runtime is referencing `IOSource.failureReference` (which should have been deleted as it doesn't exist in the Unison source included in IOSource) when it should be referencing `Unison.Builtin.Decls.failureRef`.

I'm guessing this is only triggered by I/O programs that actually throw errors (and maybe you even have to inspect the type of the error in a certain way to trigger it). I'd delete `IOSource.failureReference` and add a regression test to `io.md` transcript that doesn't require pulling all of base.

I'd also audit all the imports of stuff from `IOSource` in the runtime - most of those should be pointing to things in `Unison.Builtin.Decls`.

```
~/unison [trunk●] » rg failureReference 

parser-typechecker/src/Unison/Runtime/Builtin.hs
35:import Unison.Runtime.IOSource (ioFailureReference, tlsFailureReference, eitherReference, failureReference)
907:        . TLetD fail BX (TCon failureReference 0 [stack1, stack2])
917:        . TLetD fail BX (TCon failureReference 0 [stack1, stack2])
930:        . TLetD fail BX (TCon failureReference 0 [stack1, stack2])
943:        . TLetD fail BX (TCon failureReference 0 [stack1, stack2])
957:        . TLetD fail BX (TCon failureReference 0 [stack1, stack2])
```
