### ISSUE TITLE
Ucm exits with `unimplemented: symbol1to2 Pattern` when using `display` command 

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#2053]
[fix2053.md](https://github.com/unisonweb/unison/files/6580679/fix2053.md)
UCM exits with the following error when calling `display` in the UCM. 

```
unimplemented: symbol1to2 Pattern
CallStack (from HasCallStack):
  error, called at src/Unison/Codebase/SqliteCodebase/Conversions.hs:246:16 in unison-parser-typechecker-0.0.0-6U6boimwb8GAC5qrhLfs8h:Unison.Codebase.SqliteCodebase.Conversions
```

A transcript is attached.

**Comment by heyrudy** [comment]
Hi,

I just came across the same issue while I was running this example :
[example.md](https://github.com/unisonweb/unison/files/6679039/example.md)

 And I was getting this message :
 
> ucm: unimplemented: symbol1to2 Pattern
>CallStack (from HasCallStack):
>  error, called at src/Unison/Codebase/SqliteCodebase/Conversions.hs:246:16 in unison-parser-typechecker-0.0.0-2ZZpIeQc0fn4bLbpvD8Zs0:Unison.Codebase.SqliteCodebase.Conversions
  
 @rlmark already suggest me a workaround that work perfectly though

**Comment by aryairani** [comment]
In @rlmark's example, `view List.map` is okay:

```
builtin.List.map : (a ->{e} b) -> [a] ->{e} [b]
builtin.List.map f a =
  go i as acc =
    match List.at i as with
      None   -> acc
      Some a ->
        use Nat +
        go (i + 1) as (acc :+ f a)
  go 0 a []
```

but `display List.map` fails.

On a v1 codebase, it succeeds, but note that output has synthetic variables in it (these are what crash `symbol1to2`). Is that expected? @pchiusano @dolio 
```
go f i as acc =
  _pattern = List.at i as
  match _pattern with
    None           -> acc
    Some _pattern1 ->
      use Nat +
      go f (i + 1) as (acc :+ f _pattern)
f a -> go f 0 a []
```

I'm not even sure why `symbol1to2` (which is for serializing to the codebase) gets called by the `display` command.

**Comment by dolio** [comment]
Yeah, that's expected right now. Maybe it could be avoided more, but in general it's going to happen sometimes.

I can't speak to the `symbol1to2` thing.

**Comment by aryairani** [comment]
I guess `display` puts its result into the watch expression cache, which I didn't know needed to support synthetic variables.  I guess I can just convert them to text, but what do we miss out on by by throwing away that info?  I kind of want to support just what's used by the runtime, not everything that's used by the parser/typechecker.

**Comment by pchiusano** [comment]
We don't miss anything by tossing that info out after typechecking, but to do it correctly while avoiding variable capture you need to have the whole term available. 

You can take a look at how this is done for terms coming out of the typechecker. Look for the TopLevelBindings note in Context.hs I think. There was also a PR by me a while ago to remove synthetic type variable names from inferred types, you might be able to find that and check the diff.

Cc @dolio
