### ISSUE TITLE
P.bulleted doesn't work and/or user error

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#2066]
```haskell
suggestUpgradeMessage exec resolvedDir specifiedDir =
  P.lines $
    map
      P.wrap
      [ "I looked for a" <> prettyFmt V2 <> " codebase in " <> P.backticked' resolvedDir ","
          <> "but found only a"
          <> prettyFmt V1
          <> "codebase there.",
        "",
        "You can use:",
        P.bulleted
          [ P.backticked (P.wrap $ exec <> maybe mempty ("-codebase" <>) specifiedDir <> "upgrade-codebase")
              <> "to update it to"
              <> P.group (prettyFmt V2 <> ",")
          , P.backticked (P.wrap $ exec <> maybe mempty ("-codebase" <>) specifiedDir <> "init")
              <> "to create a new"
              <> P.group (prettyFmt V2 <> "codebase alongside it,")
              <> "or"
          , P.backticked (P.wrap $ exec <> "-codebase <dir>")
              <> "to load a"
              <> prettyFmt V2
              <> "codebase from elsewhere."
          ]
      ]
```

produces:

```
I looked for a v2 codebase in `/Users/arya`, but found only a v1 codebase there.

You can use:
* `unison upgrade-codebase` to update it to v2, * `unison init` to create a new
v2codebase alongside it, or * `unison -codebase <dir>` to load a v2 codebase from
elsewhere.
```

**Comment by aryairani** [comment]
@pchiusano I assigned you just for initial triage.

**Comment by aryairani** [comment]
Maybe it has more to do with `P.wrap`

**Comment by pchiusano** [comment]
@aryairani 

Yeah just reduce the scope of the wrap to just the paragraph before the bullets.

**Comment by pchiusano** [comment]
And if you need to you can add a wrap around each of the bulleted list items if they are too long for one line.

**Comment by aryairani** [comment]
:+1:

**Comment by aryairani** [comment]
I keep running into this issue about 1x/year: #949, #950, #1190, and now #2066.

I think for `P.wrap . P.lines` or `P.wrap . P.bulleted`, etc. that instead of forgetting `lines` / `bulleted`, that it should wrap what's inside them.  Is that a hard change?

**Comment by pchiusano** [comment]
Yeah, it's hard. :| 

Because `bulleted` and `lines` are just derived combinators, they aren't just constructors that we can distribute `wrap` over. I don't think they should be constructors; instead I'd just introduce `wrapBulleted` and/or `wrapLines` as combinators if that's a common pattern you think you want.

```
wrapBulleted ps = bulleted (wrap <$> ps)
```

**Comment by aryairani** [comment]
Maybe naive, but is there some other constructor they could use like `Group`; so that even if `wrap` didn’t distribute over them, it wouldn’t be canceling them out?

And then `wrapBulleted` could also be a thing with the definition you gave, if that’s a common pattern.
