### ISSUE TITLE
Update VS Code Dev Container for M2

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2071]
This might be done and working but needs testing by someone with intel hardware, follow instructions here:

https://github.com/unisonweb/vscode-devcontainer

**Comment by aryairani** [comment]
Slowly downloading Docker for Apple Silicon for testing, but otherwise the repo is updated in unisonweb/vscode-devcontainer@41e40ab, but the install docs still need to be updated to not say it's not ready.

**Comment by pchiusano** [comment]
@aryairani I've updated the install docs. You can close this ticket once you've verified it works.

**Comment by aryairani** [comment]
@stew We currently are using Ubuntu 18.04 LTS Bionic here; lmk if you recommend something different (or feel free to update it).  Also feel free to update the install script with the debian package when it's ready, although it's probably not hurting anything as-is.

**Comment by aryairani** [comment]
@pchiusano @stew I pushed a new version that will probably work on Intel machines.  I still can't actually test it locally without an Linux-arm64 build of ucm.  I'm guessing the devcontainer users are probably mostly Wintel, so maybe this is good enough for now, but why don't we throw in a Linux-arm64 build anyway?  There are Windows arm64 users out there too, that would be supported by a new build.

Could someone on an Intel machine try it out too, though?

**Comment by pchiusano** [comment]
@stew is going to give this a go

**Comment by pchiusano** [comment]
@stew is this still open?

**Comment by pchiusano** [comment]
We are going to call this done but if you are having problems with https://github.com/unisonweb/vscode-devcontainer then please reopen.
