### ISSUE TITLE
fatal: couldn't find remote ref refs/heads/

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2072]
```
pull-request.create https://github.com/unisonweb/base:.trunk https://github.com/pchiusano/unisoncode:.prs.initialize
```
This produces:

```
fatal: couldn't find remote ref refs/heads/masteronweb/base ...
ucm: callCommand: git --git-dir '/Users/pchiusano/.cache/unisonlanguage/gitfiles/https$x3A$$x2F$$x2F$github$dot$com$x2F$unisonweb$x2F$base/.git' --work-tree '/Users/pchiusano/.cache/unisonlanguage/gitfiles/https$x3A$$x2F$$x2F$github$dot$com$x2F$unisonweb$x2F$base' pull --force --quiet (exit 1): failed
```

**Comment by pchiusano** [comment]
@aryairani this was fixed for me by deleting `~/.cache/unisonlanguage` and seems unrelated to the `pull-request.create` command. The pull of base was bombing for some reason. What was weird is that it had worked previously, but then I guess the cache got into a funky state.

I'd love to just get rid of the cache or if you're going to have a cache, use more explicit sharing - like you can get a guid-named codebase, and reference it across multiple commands, but you don't share the cache just because the remote repo is the same.

**Comment by aryairani** [comment]
Agreed.  We could probably design a working cache by going back to the drawing board thinking in terms of FSMs, though there would be questions to resolve about how to use `git` commands to accurately detect the state of the machine.  Anything else might reduce but not eliminate the race conditions.

Alternatively, we replace git and the local codebase becomes the cache.
