### ISSUE TITLE
ucm refuses to find/upgrade a v1 codebase at the non-default path

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#2080]
I can't upgrade a v1 codebase unless it's in ~/.unison.

Initially it looks like ucm can cope with v1 codebases and advise me about what to do with them - for example, I get this nice message:

```
chris@chris-thinkpad:~/ucm_m2$ ./ucm
I looked for a v2 codebase in `/home/chris`, but found only a v1 codebase there.

You can use:
* `ucm upgrade-codebase` to update it to v2,
* `ucm init` to create a new v2 codebase alongside it, or
* `ucm -codebase <dir>` to load a v2 codebase from elsewhere.
```

But sometimes it struggles, I guess when I give it a codebase at something other than the default path.

```
chris@chris-thinkpad:~$ cp -R .unison unison_main_upgrade_1
chris@chris-thinkpad:~$ cd ucm_m2
chris@chris-thinkpad:~/ucm_m2$ ./ucm -codebase ~/unison_main_upgrade_1
No codebase exists in /home/chris/unison_main_upgrade_1.
Run `ucm -codebase /home/chris/unison_main_upgrade_1 init` to create one, then try again!
chris@chris-thinkpad:~/ucm_m2$ ls ~/unison_main_upgrade_1
v1
chris@chris-thinkpad:~/ucm_m2$ ./ucm upgrade-codebase -codebase ~/unison_main_upgrade_1
I looked for a v2 codebase in `/home/chris`, but found only a v1 codebase there.

You can use:
* `ucm upgrade-codebase` to update it to v2,
* `ucm init` to create a new v2 codebase alongside it, or
* `ucm -codebase <dir>` to load a v2 codebase from elsewhere.

```

**Comment by pchiusano** [comment]
Can you try `ucm -codebase <dir> upgrade-codebase`? I think the `-codebase` flag needs to come before anything else.

Related: #1991

**Comment by aryairani** [comment]
The `-codebase` flag needs to come before anything else.

**Comment by pchiusano** [comment]
Going to close this, but if you want to do a PR that amends the help text to show this as an example, that'd be welcome.

**Comment by aryairani** [comment]
I had an example in at one point, but because `-codebase` needs to come before any of the other commands, `init`, `run`, `transcript.fork`, `headless`, I felt it looked out of place as an extra example on `upgrade-codebase`, I hoped that the existing phrasing would be sufficient:

```
  unison -codebase path/to/codebase
  Starts Unison interactively, using the specified codebase. This flag can also be set before any
  of the below commands.
```

I changed "for any of the commands" to "before any of the commands".

**Comment by aryairani** [comment]
A PR that lets you supply flags in a different order might be nice though :)
