### ISSUE TITLE
Universal.< gives the wrong answer for large Nat values

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#2083]
The first of these is wrong:

```
    2 | > (Universal.<) 9223372036854775808 0
          ⧩
          true
  
    3 | > (Nat.lt) 9223372036854775808 0
          ⧩
          false
```
At a guess, `Universal.<` seems to be comparing Nats as Ints.  9223372036854775808 (2^63) is the smallest Nat that doesn't fit in an Int - interpreted as an Int, that bit pattern means -9223372036854775808, which would fit with the behaviour above.

Nats go up to 2^64-1, so it's the upper half of the range that has the problem.  Presumably the other comparison operators are affected too.

This causes a failure in a property test for me, and the test used to work.  But adding the `--old-runtime` flag (is that a thing?) and retrying (with cleaned cache) still shows the failure, so I don't understand what's made the change.  

I can work around by switching to `Nat.lt` (which is probably better anyway - I didn't realise I was using universal comparison til I dug into this...)

This is on the M2 release candidate from 4-Jun.

(Code reading, I got as far as `universalCompare` in Stack.hs and then gave up.  But I do see that the `Closure` type in that file is using `Int` not `Nat`...)

tagging @dolio

**Comment by pchiusano** [comment]
This has also come up with regard to #1717 

Not sure what to do about it yet though. At least for boxed nats I think we have enough info to dispatch to different logic based on the type.

**Comment by dolio** [comment]
Yeah, we could make universal ordering work like Nat ordering for Nat, I think.

I guess I already expressed my concern in that other issue, though. In general, it's not going to be possible to make the automatic 'universal' ordering coincide with orderings that aren't just structural. It can serve as a sort of arbitrary ordering for e.g. ordered maps, but for more meaningful orderings, some kind of overloading is probably better.
