### ISSUE TITLE
Pass terminfo = disabled to haskeline when building

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2085]
We use [haskeline](https://hackage.haskell.org/package/haskeline) for tab completion and line editing in UCM. It depends on terminfo at runtime by default, but can be passed a flag to disable that.

See https://hackage.haskell.org/package/haskeline

We should pass that flag to disable that dependency to make our linux binaries more portable (currently people get runtime errors if they've got a different version of libtinfo). According to the note here https://github.com/judah/haskeline:

> Runs on POSIX-compatible systems, using the terminfo library to support non-ANSI terminals.

But we expect an ANSI terminal anyway since we’re using ANSI codes for formatting. Also, realistically, we don’t care about supporting non ANSI terminals.

I’m not sure what the incantation is to pass a build flag to a dependency but this issue is just to do that.

**Comment by aryairani** [comment]
https://stackoverflow.com/a/35123917
```
flags:
  haskeline:
    terminfo: false
```

or `--flag haskeline:-terminfo`
