### ISSUE TITLE
factor component cycle length out of `Reference`

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#2100]
This is rarely used auxiliary info that is better confined to the few spots that use it, than duplicated in every reference.  We can start by auditing where it's actually used.

It also will resolve a class of crashes we see when trying to construct V1-style References that aren't known to the V2 codebase. (#2181, #2011, #2122, #2195, maybe be able to reverse 
bd94933)

**Comment by aryairani** [comment]
- [x] Changed `Reference.componentFor`, `PPE.declarationPPE` to accept a length
- [x] Add getCycleLength to `Codebase` to facilitate loading whole V1 components (e.g. in `Sync12.check{Term,Decl}Component` 
  - [ ] fully propagate
- [ ] Copy and use `Reference` as `Reference.V1` so as to not change the `Serialization` code
  - [x] created
  - [ ] referenced
  - [ ] propagated

**Comment by aryairani** [comment]
Currently stuck trying to decouple the v1 codebase implementation from the "trunk" `Reference` type, because it depends on the current representation, and can't be changed without breaking backwards compatibility.

I've been trying to do this by updating `FileCodebase` and its dependencies to use a separate reference type, but it's a huge amount of manual work to separate them.  I've tried: 
* Starting from an empty file, and adding missing dependencies one by one; 
* Starting from the full codebase and deleting unneeded code, with `weeder`, discovered `weeder` was giving false positives due to not understanding `PatternSynonyms`.
Both are huge tasks, lacking automated tool support.

**Comment by ChrisPenner** [comment]
Done in #2627 🎉
