### ISSUE TITLE
UCM should not crash when evaluating n / 0 

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#2101]
[fix2101.md](https://github.com/unisonweb/unison/files/6620719/fix2101.md)
UCM currently crashes if you divide by zero - it should raise an appropriate error instead. 

A transcript is attached but you can just enter `> 5 / 0` in a watch expression to see the failure.

**Comment by stew** [comment]
```
  ~/devel/distributed/scratch.u changed.
  
  Now evaluating any watch expressions (lines starting with `>`)... Ctrl+C cancels.

Encountered exception:
divide by zero
.share.unison.public.base.main> 
```

This bug seems to have gotten fixed somewhere along the way.
