### ISSUE TITLE
Bug in pattern matching with constants

### ISSUE THREAD

**Issue by aslakg** [unisonweb/unison#2106]
```unison
type Tree = Branch Tree Tree | Leaf Nat

tst x = match x with
  Leaf n             -> 0
  Branch (Leaf 0) i -> 1
  Branch i (Leaf 0) -> 2
  Branch i1 i2       -> 3

> tst (Branch (Leaf 1) (Leaf 0))`
```
This returns 3, instead of the expected 2.
Possibly due to a reordering of the pattern matching cases.

**Comment by aryairani** [comment]
I noticed that if you swap the 2nd and 3rd cases, that the result changes..  Really, if the `2` case is anywhere but where it is.  @dolio Could you take a look?

**Comment by aryairani** [comment]
Simpler:
```
tst = cases
  (0, _) -> 1
  (_, 0) -> 2
  _ -> 3

> tst (1, 0) -- 3
```

**Comment by dolio** [comment]
Yeah, something wrong with pattern compilation. Not sure exactly what yet.
