### ISSUE TITLE
ucm crashes trying to reference ##IO.getLine.impl.v3

### ISSUE THREAD

**Issue by samgqroberts** [unisonweb/unison#2118]
I just upgraded to M2g. I had the old base definitions in `.basev1`. I pulled the new base into `.basev2` and applied the `.basev2.patch` to this `._2048.upgrade.cli` namespace. I went into this term to try to now update from `IO.Deprecated`, changed `basev1` to `basev2` in the `use` statement, and hit the crash below.

```
promptOptsThenStartGame _ =
  use Nat fromText
  use Optional None
  use basev2.io printLine readLine
  printLine "Grid Size?"
  match fromText !readLine with
    None          ->
      printLine "Invalid"
      ()
    Some gridSize ->
      printLine "Animation Delay (in microseconds)?"
      match fromText !readLine with
        None                ->
          printLine "Invalid"
          ()
        Some animationDelay ->
          startGame
            (_2048.trunk.engine.GameConfig.GameConfig gridSize)
            (UIConfig animationDelay)
```

```
._2048.upgrade.cli> 

  I found and typechecked these definitions in ~/unison/scratch.u. If you do an `add` or `update`,
  here's how your codebase would change:
  
    ⍟ These names already exist. You can `update` them to your new definition:
    
      promptOptsThenStartGame : ∀ _. _ ->{IO, Exception, IO.Deprecated} ()

ucm: refLookup:tm: unknown reference: ##IO.getLine.impl.v3
CallStack (from HasCallStack):
  error, called at src/Unison/Runtime/Machine.hs:1412:5 in unison-parser-typechecker-0.0.0-2ZZpIeQc0fn4bLbpvD8Zs0:Unison.Runtime.Machine
```

Following the rabbit hole starting at `readLine`

```
.> view 1

  basev2.io.readLine : '{baseconflicting.IO, basev2.Exception} Text
  basev2.io.readLine = '(#h2q07t325h stdIn)

.> find #h2q07t325h

  😶
  
  No results. Check your spelling, or try using tab completion to supply command arguments.

.> view #h2q07t325h

  #h2q07t325h : basev2.io.Handle ->{baseconflicting.IO, basev2.Exception} Optional Text
  #h2q07t325h h = reraise (##IO.getLine.impl.v3 h)

.> view ##IO.getLine.impl.v3

  ⚠️
  
  The following names were not found in the codebase. Check your spelling.
    ##IO.getLine.impl.v3
```

Here's a zip of my codebase in this state:

[codebase-bugged.tar.gz](https://github.com/unisonweb/unison/files/6658962/codebase-bugged.tar.gz)

**Comment by pchiusano** [comment]
It definitely shouldn't crash like that, but there's not currently a `getLine` in the new IO type and the latest version of `base` doesn't have a `getLine`. Am guessing that you grabbed a version of base that accidentally got a copy of `getLine`.

The `getLine` function is waiting on #1999 and see [this comment](https://github.com/unisonweb/unison/pull/1999#issuecomment-861868933) on current status.

cc @runarorama

**Comment by aryairani** [comment]
@samgqroberts I see now that the problematic `io.readLine` came from `base:.releases._M2f`, and that it's absent from `base:.releases._M2g`, pending a working version.

**Comment by aryairani** [comment]
I'm going to close this issue, but I'm glad to have it documented, as you probably aren't the only person who tried `M2f`.

**Comment by aryairani** [comment]
Ok so we have three pieces
1. we recommend against merging a new base into an older base (this doesn't totally make sense to me for long term; but for now, at least, it doesn't work).
2. the offending term came from `M2f`'s base
3. it shouldn't have crashed (#2120)

**Comment by samgqroberts** [comment]
Thanks for the investigation @aryairani and @pchiusano :). Seems like I should wait for https://github.com/unisonweb/unison/pull/1999 to land before further attempts to upgrade my projects
