### ISSUE TITLE
Adding from a scratch files that both has new and updated definitions crashes

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#2126]
With a scratch file that results in both new definitions to add and definitions to update, issuing the `add` command crashes `ucm` with a SqliteCodebase error:

<img width="957" alt="Screen Shot 2021-06-16 at 11 56 10" src="https://user-images.githubusercontent.com/2371/122420353-a1e35000-cf59-11eb-8750-b55bda0dbf2f.png">

**Comment by aryairani** [comment]
This is unexpected.

**Comment by aryairani** [comment]
@hojberg could you run `debug.file` after type-checking to get the list of hashes in the file

**Comment by hojberg** [comment]
Hmmm I've tried a bunch of various configurations now and can't get it to crash. I think the only difference between then and now is that I have an updated `base` 🤔 Maybe we just close this and look out for any re-apperance?

**Comment by aryairani** [comment]
Ok, sorry.
