### ISSUE TITLE
Pretty-printer should prefer names whose FQN has fewest number of segments

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2133]
Right now, we don't really have any way of prioritizing what names are chosen by the pretty-printer. The current algorithm is deterministic but basically never what you want / it's just accidental implementation-defined (see example below). We've talked about having some separate name prioritization scheme and maybe that's a good idea but feels maybe overkill and it would need more design. 

This is a simple proposal that can be implemented in a few lines of code today. It also wouldn't preclude having something fancier for prioritizing names later.

The thing I want is for:

````
zoink = 230498234
ooga = zoink + 1209
````
```
.> alias.term zoink zoink.aliases.aaaa
.> view ooga
```

To use the name `zoink` (whose FQN has fewer segments) rather than `aaaa` (whose FQN has more segments but whose unique suffix comes alphabetically first). Currently it picks `aaaa` because the unique name has 1 segment and it comes first alphabetically.

The proposed algorithm is to have the pretty-printer prefer names whose fully-qualified name has the fewest number of name segments (like `foo.bar.baz` has 3 segments). If there's multiple names with the the same number of segments, it can pick alphabetically.

Rationale for this change is to just have a predictable and simple algorithm for picking names which is easy to think about and lets users prioritize names. Another way of looking at it is that we're wasting an opportunity with the current algorithm, which is pretty random and not useful IMO. Just having something that's non-random and useful is a step up.

For instance, with this change, we can start including aliases for a definition `foo` under `foo.aliases`. It also works when someone includes a copy of `base` in `external` of their library and maybe changes some of the names - these won’t be chosen either (though archived namespaces will probably help with this also - I think `_external` should be archived).

My view is that “pick which comes first alphabetically” should only be done if there is no other information to make a decision on.

One way of doing this with our current name printing is tweaking `PrettyPrintEnv.fromNames`. It already picks the shortest name (in terms of number of segments), it can be modified to take the shortest name (according to the number of segments of the longest name each name is a suffix of, or 1 if the name is not a suffix of any name other than itself).

So in the above example, `aaaa` will have a length of 3,  because `aaaa` is a suffix of the name `zoink.aliases.aaaa` which has length 3. Whereas `zoink` will have a length of 1 because it is not a suffix of any other name.

Aside: If the representation of names were more like `(Path, UniqueSuffix)` then this would be simpler - it would just be sorting based on the combined segment length of Path + Suffix. Right now we’re throwing away information by just associating this bag of names with a hash, forgetting that some of those names were formed by taking a suffix of an existing name.

cc @runarorama @hojberg @aryairani

**Comment by aryairani** [comment]
I think some of this stuff has to get folded into #2110 because there may not be enough info to make the determination if we don't have the entire namespace in the `Names` the PPE comes from.

**Comment by pchiusano** [comment]
@aryairani right I think

> Aside: If the representation of names were more like (Path, UniqueSuffix) then this would be simpler - it would just be sorting based on the combined segment length of Path + Suffix. Right now we’re throwing away information by just associating this bag of names with a hash, forgetting that some of those names were formed by taking a suffix of an existing name.

Like maybe #2110 should just return a `Set (Path, Suffix)` rather than two sets?

**Comment by aryairani** [comment]
@pchiusano Yes, about throwing away information. And yes, maybe a `Set (HashQualified (Path, Suffix))`.

**Comment by aryairani** [comment]
I think that simply tweaking the heuristic isn't going to be helpful, that it will just move the problem.

**Comment by pchiusano** [comment]
@aryairani WDYT of this argument

> This is a simple proposal that can be implemented in a few lines of code today. It also wouldn't preclude having something fancier for prioritizing names later.

Basically, I see this as - the implementation needs to use some heuristic in cases where the user has not fully specified what names they want to see, so better to pick a heuristic that gives better results. 

Even if we support some more explicit priortization of names, we won't necessarily have a total order on the possible names, and forcing the user to give us a total order is placing more of a burden on them. Having a more explicit way of tracking name preferences means users have to specify that information somehow... which takes effort on their part. So I think there will always be a place for some reasonable heuristic to pick a name when multiple names are possible.

Also, I want to make the case that heuristics can be a good thing for the DX and they complement more explicit mechanisms. If the heuristic is simple and predictable, then in the X% of the cases where they give good results, the user doesn't need to do any work to specify what they want more explicitly. Everybody wins in this situation.

**Comment by pchiusano** [comment]
I think the suffix-based name resolution is an example of a pretty good heuristic - the user hasn't fully specified what they want in some sense, but if they've used a unique suffix, we can take a good guess. This is a big DX improvement over needing explicit imports everywhere, IMO, and it's also much simpler than implementing a more complex feature like "first-class imports" which the user needs to then specify and maintain.

**Comment by aryairani** [comment]
I agree we shouldn't expect the user to give us a total order, and that without one you need something to fill in the gaps, but I think the heuristic should be the product of a design session, not a substitute for one.

I think the suffix-based name resolution is a good example of a heuristic that sounds good at a high level, but immediately breaks down in general use.  I can't confidently provide a suffix without knowing every name in the codebase. Maybe it just needs a better error message in that case, like instead of "i don't know what you mean by `structure`", maybe  "you said `structure`, but did you mean `.my.projects.data.structure` or `libs.neatpkg.structure`?".

I just realized my example is about parsing instead of pretty printing; for pretty-printing it's less of a big deal because you can mouse-over for more info when you are missing context; for parsing it's a pain to supply it.

**Comment by pchiusano** [comment]
>  I can't confidently provide a suffix without knowing every name in the codebase. Maybe it just needs a better error message in that case, like instead of "i don't know what you mean by structure", maybe "you said structure, but did you mean .my.projects.data.structure or libs.neatpkg.structure?".

Yeah, I think it's that for parsing, but also, it's problematic that so many versions of the same function can easily exist in your namespace tree, so without something like #1340 the unique suffixes can stop being unique and it becomes hard to predict what will be.

**Comment by aryairani** [comment]
I'm imagining something like: a user-defined set of custom imports, similar to what you might put in your scratch file to curate your parsing environment, effectively defining shorter names for your commonly used definitions.  And then anything that's not covered by your custom imports is probably "infrequent use" and deserves a FQN.  WDYT?

And then... for that, we could prefer FQNs that have the fewest number of segments. 😅

**Comment by aryairani** [comment]
So maybe that's what you were saying to begin with.

**Comment by ceedubs** [comment]
#1868 may relate to this
