### ISSUE TITLE
"missing integral case" when comparing `Float` values

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#2136]
Minimal example:

```unison
> 0.0 == 0.0
```

Runtime crashes with `"missing integral case"`

**Comment by dolio** [comment]
Found the problem. The floating instructions `EQLF` and `LEQF` are accidentally giving back floating point `0.0` and `1.0` as the boolean indicators. `0.0` is the same as integer `0`, but `1.0` is not the same as `1`.

I'll fix it soon.
