### ISSUE TITLE
something fishy with find by type / type-mention

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#2140]
`find : Nonempty a -> a` doesn't seem to find `Nonempty.last` (or anything else).
`Nonempty.last` is `#4s2e6fpcpb`

In my v1 codebase, I see these hashes in the type-mentions-index for `Nonempty.last`:
`% find ~/.unison/v1/type-mentions-index/ | grep 4s2e6fpcpb`
```
#gku1kqleg9n619vfvu1iuig4fe3f937o3nbaa0dq0man4tjhg07idfadst0e5pufnnbh5ckun4rhl0f3ob2fnodimgm4sel20oau2qo
#9f58iojnfqnkf14ifh966q052vv9u8f3ov58icl53qre0jtn2m05fdfhasnjllvv7qv599ctbt188uc2b7d8bp4em1ds4t9lhvnkuso
#kh9ar9iiaa3sn503l5rqmo7josbjvpe9qfh2nn5qpqdtg0df9un3bn59dkhdfkhphcddril2b0d4g4gjs8eqipejrmco16dj4ta2vog
#mlcfeh2294igm228dlq3u9bn0i0c42q8fc700f6c57tpqntn7omoml9liepcvkq3v9v79n824d9t0rp63otl6f86purvlv08gu56ih0
#94a25njontg9htj2q8elv0jajublc92q5c6t3mrj0p17if0j5lfc6nnp7jgr4km0vjm0v2rucb63dvjnpeltj53jhs4m63mpnqp42mo
```

In my v2 codebase I see these hashes in the type-mentions-index for `Nonempty.last`:
```sql
select out.base32 
from find_type_mentions_index, hash_object, hash, hash as out 
where hash.base32 like '4s2e6fpcpb%' 
  and hash.id = hash_id 
  and object_id=term_referent_object_id 
  and type_reference_hash_id = out.id;
```

```
4ej7f14gj2761smju0pdk9b1v1aflunmjtej8ek562rrd9dlkvr9ak2q0p28tf2m37003jq9a2sffdavpgcv9uiinncdruf7qps2l3g
6hvd1hivr57ok2ftti8carcai9eag2dunrb3r5k84nef2e6vcjjosnqdsogqfjhebh8hbc7tsmq4jc2gmi0bl1q0ke06cud2e8utkbo
9f58iojnfqnkf14ifh966q052vv9u8f3ov58icl53qre0jtn2m05fdfhasnjllvv7qv599ctbt188uc2b7d8bp4em1ds4t9lhvnkuso
gku1kqleg9n619vfvu1iuig4fe3f937o3nbaa0dq0man4tjhg07idfadst0e5pufnnbh5ckun4rhl0f3ob2fnodimgm4sel20oau2qo
skpghar6nnkqrsl76gb0qq8jn1a2kfnbpf2ts7jffopc9ar2jrj5t10s4cbd0kk53bu8mr2dughhinr8gluqi31kn94912ie9rjlq60
```

2 of the 5 match, so my guess is that the hashes are being computed wrong for the index although it was meant to be computed in the same way as before.

After figuring out what's wrong with computing the hashes, we'll need either a command to rebuild the two indexes, or (probably better for users) increment the schema version number and rebuild the indexes automatically on the first startup.

Also we should improve our test coverage since this isn't being flagged.

**Comment by aryairani** [comment]
The type index also doesn't match, so I guess I'd start there.

```sql
select out.base32 
from find_type_index, hash_object, hash, hash as out 
where hash.base32 like '4s2e6fpcpb%' 
  and hash.id = hash_id 
  and object_id=term_referent_object_id 
  and type_reference_hash_id = out.id;
```
```
4ej7f14gj2761smju0pdk9b1v1aflunmjtej8ek562rrd9dlkvr9ak2q0p28tf2m37003jq9a2sffdavpgcv9uiinncdruf7qps2l3g
```

versus

```bash
find ~/.unison/v1/type-index/ | grep 4s2e6fpcpb         
```
```
/Users/arya/.unison/v1/type-index//#94a25njontg9htj2q8elv0jajublc92q5c6t3mrj0p17if0j5lfc6nnp7jgr4km0vjm0v2rucb63dvjnpeltj53jhs4m63mpnqp42mo/#4s2e6fpcpbdi5m3cokm6u81ego15ediq65bnv75qlojoke535s6e1e61nf69n0i92jbd7enfhkftehbhlom93849l4kho5lei27uke0
```

**Comment by aryairani** [comment]
The V2 index is populated here:
https://github.com/unisonweb/unison/blob/bd8514b3ff0c77b5a6d6de47da31c61aa395edd7/codebase2/codebase-sqlite/U/Codebase/Sqlite/Operations.hs#L465-L473
and
https://github.com/unisonweb/unison/blob/bd8514b3ff0c77b5a6d6de47da31c61aa395edd7/codebase2/util-term/U/Util/Type.hs#L28-L39

The V1 index is populated here
https://github.com/unisonweb/unison/blob/bd8514b3ff0c77b5a6d6de47da31c61aa395edd7/parser-typechecker/src/Unison/Codebase/FileCodebase/Common.hs#L457-L459
and
https://github.com/unisonweb/unison/blob/bd8514b3ff0c77b5a6d6de47da31c61aa395edd7/unison-core/src/Unison/Type.hs#L522-L533

It looks like the problem is that the V2 `TypeUtil.toReference` is computing the hash of the V2 type representation, but the ucm query uses the hash of the V1 type representation, and I wasn't cognizant of this mismatch.

I suppose a quick fix would be to enlist the `Codebase` in constructing the `find` query, or just move over to V2 hashing everywhere, which would cause some problems for V1 codebases.

**Comment by aryairani** [comment]
Put another way, the problem is that we have hashes computed in different places — sometimes in the codebase implementation and sometimes outside of it.  We should pick one, IMO passed in, with its own independent representation that's locked to "hashing" version.

**Comment by puffnfresh** [comment]
I just ran into this too by searching for `find : [a] -> Optional a`.

I think I understand the hash problem if the types are exactly the same, but it's resorting to fuzzy matching and still not finding the functions. Shouldn't fuzzy find everything?

**Comment by puffnfresh** [comment]
It looks like this is manifesting in the docs too:

```
.> docs Nonempty.init                          

  Returns all but the last element of a nonempty list.

.> docs base.List.distinctBy                       

  
  base.List.distinctBy : (a ->{g} b) -> [a] ->{g} [a]
  
    The expression `distinctBy f xs` removes duplicate elements from the
    List `xs`, but only considers any two elements to be the same if the function
    `f` returns the same value for both. For any group of duplicate elements,
    only the first such element in the List is retained.
 ```

Any type not being found by "find" also won't be shown when I run docs on it.

**Comment by aryairani** [comment]
Hi @puffnfresh,
 
> I think I understand the hash problem if the types are exactly the same, but it's resorting to fuzzy matching and still not finding the functions. Shouldn't fuzzy find everything?

`find` should find everything, but all the modes of find use hashing under the hood, and the issue is that hashes are being computed in multiple places with different values; they need to be consolidated to one place so that the same hashes are used for indexing and querying.

> Any type not being found by "find" also won't be shown when I run docs on it.

I didn't understand what the example was trying to show, but there shouldn't be any connection between `find` and `docs`, and hashing shouldn't come into play for `docs` either.

Re. the WIP, for the time being we're trying to support the old codebase format too with `ucm --old-codebase`, so just bringing the V2 implementation details into the generic interface only moves the problem. Though, I'm not sure I have a good reason for not deleting V1.

**Comment by puffnfresh** [comment]
@aryairani if you look at my example, `init` doesn't have a type shown while `distinctBy` does. I think it's trying to lookup the type of the expression somewhere and failing.

I think deleting V1 would be great.

**Comment by aryairani** [comment]
> @aryairani if you look at my example, `init` doesn't have a type shown while `distinctBy` does. I think it's trying to lookup the type of the expression somewhere and failing.

Ah, no; `docs` only shows a type if the doc author put one into the doc.  You can use `view Nonempty.init` and it should show the type.
