### ISSUE TITLE
Feature Proposal: A `ui` command in `ucm`

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#2150]
It would be really cool to have a `ui` command in `ucm`. Here's how I imagine it working:

* `.> ui`, opens the UI in the browser if there's a UI folder that `ucm` knows about (set through `--ui` or `UCM_WEB_UI`).
* `.> ui install` to install and perhaps also update? (could be a separate command) the UI. Which version of the UI that gets downloaded could be specified and/or determined by a mechanism to tag which version of ucm the ui can run with (per @aryairani's suggestion).
* `.> ui` without a UI folder present, `ucm` would tell the user (instead of attempting to open the URL) and ask if the user would want to download the UI, allowing them to choose between `latest` and the current release (`M2g` for instance).
* `.> ui List.map` would work similar to `display List.map` except that it would open `List.map` in the UI—in the future this could open directly in an Electron app which would allow us to support multiple calls to `ui <definition>` to open in the same window instead of in a new browser tab every time.
* `.> ui List.map List.filter` would open both `List.map` and `List.filter` in the UI.
* `.> ui .base` would open the UI zoomed into the on the `base` namespace (relative to)

**Comment by aryairani** [comment]
wrt downloading the UI, could we have a way of keeping track of the newest ui that is supported by the user's version of ucm?  (this involves tweaking our git tags to produce a `git describe` version number that is meaningful in sequential, which is possible and common, though not obvious)

And if we have a way to automatically download the ui, we should have a way of automatically updating the ui to the latest supported.

**Comment by hojberg** [comment]
Right! `.> ui update` and `.> ui install` and `.> ui install unstable` for instance. I like it—added it to the list.

**Comment by ceedubs** [comment]
I imagine that this would come for "free", but just to throw it out there:

It would be nice if `ui 3` worked like `view 3` does (the 3rd result from the previous command).

**Comment by hojberg** [comment]
@ceedubs nice!

**Comment by hojberg** [comment]
Closing for now.
