### ISSUE TITLE
`universalCompare` returns false on alpha-equivalent lambdas

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#2162]
For example:

```
        (x -> x) === (y -> y)
        ⧨
        false
```

I would expect this to return `true` and `Unison.Runtime.Stack.universalCompare` to ignore any difference between these two values.

A good rule might be that two objects are considered identical if they have the same hash.

**Comment by pchiusano** [comment]
Ooop, looks like Runar and I filed at the same time. Closing as a dupe. 

@runarorama I usually link to an issue I create in Slack if it's discussed there. :)

**Comment by pchiusano** [comment]
Also the current behavior is unrelated to alpha equivalence (I'd be really surprised if it did):

```
    1 | > (x -> x) === (x -> x)
          ⧩
          false
```

@dolio would know better, but my guess is that it's independently compiling the two lambdas, giving each a different number even though they are the same function, and then comparing based on that local numbering.
