### ISSUE TITLE
pattern match matches guards and variable cases in wrong order 

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#2169]
In a pattern match, if you use a guard statement for one case, with a `_` or variable case as the last case, you get undesirable/unexpected behavior for which `case` statement gets matched and executed. 

```
use Universal
ex1 : Text -> Text
ex1 = cases  
  "A" -> "literal"
  x | (Text.size x === 4) -> "patternGuard"
  _ -> "fallback"

> ex1 "abcd"
```
returns 
```
    9 | > ex1 "abcd"
          ⧩
          "fallback"
```

Note, if you remove the fallback/variable case, the case statement works fine 

```
ex2 : Text -> Text
ex2 = cases  
  "A" -> "literal"
  x | (Text.size x === 4) -> "patternGuard"

> ex2 "abcd"
```
returns 
```
    17 | > ex2 "abcd"
           ⧩
           "patternGuard"
```

**Comment by pchiusano** [comment]
This looked familiar to me and there was some pattern compilation bug with reordering that @dolio fixed recently which I don't think is in a release yet. 

In any case, I can't reproduce with latest trunk.
