### ISSUE TITLE
Codebase Server API: Include metadata in `/getDefinition`

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#2173]
Extend the `/getDefinition` codebase server API with metadata like author, license and data.

Completing this ticket will support this UI ticket: https://github.com/unisonweb/ui-core/issues/24

## Suggested response

To the already existing `/getDefinition` API, add a `metadata` field with the following shape:

```elm
type Metadata {
  authors: List Author,
  copyrightHolders: List CopyrightHolder,
  licenses: List License
  createdAt: String, -- ISO 8601 formatted date time 
  updatedAt: String -- ISO 8601 formatted date time
}
```

❗This is dependent on https://github.com/unisonweb/unison/issues/2205

**Comment by pchiusano** [comment]
Revisit this after finalizing a design.

**Comment by hojberg** [comment]
Moved the design and JSON serialization specifics into its own ticket since it's needed for several other tickets: https://github.com/unisonweb/unison/issues/2205

Adjusted the RICE score accordingly

**Comment by mitchellwrosen** [comment]
#wontfix
