### ISSUE TITLE
Codebase Server Pretty Printer: Constructors should include hashes

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#2176]
Right now constructors are not clickable in the Codebase UI source rendering as the UI lack data to be able to link them.

Suggest adding adding a `Hash` to the `Constructor` variant of `Element`: https://github.com/unisonweb/unison/blob/trunk/parser-typechecker/src/Unison/Server/Syntax.hs#L98

This will fix (is a dupe of?) https://github.com/unisonweb/codebase-ui/issues/105

**Comment by pchiusano** [comment]
I think this is an easy one.

**Comment by hojberg** [comment]
Just realized that this will point to a constructor reference that should be either a `DataConstructorReference` or an `AbilityConstructorReference` so that information needs to be part of this syntax text element.

**Comment by hojberg** [comment]
`Request` should have a hash as well.
