### ISSUE TITLE
Verify that kinds are the same when propagating type edits

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2188]
Right now when you add a type replacement to a patch, during propagation, we don't verify that the kinds of the old and new type are the same. This can lead to ill-kinded type declarations and then terms that depend on those ill-kinded declarations can't typecheck (or maybe they can still typecheck, but they can't actually be called).

Anyway, I thought we were being overly conservative previously and refusing to do any type propagation, but it turns out we just had bug in the constructor mapping: #2254

**Comment by pchiusano** [comment]
Idea to increase certainty of this: reduce scope of the issue to a timeboxed investigation of possible fix

**Comment by runarorama** [comment]
Depends on #567
