### ISSUE TITLE
Delete files containing namespace blocks.

### ISSUE THREAD

**Issue by philderbeast** [unisonweb/unison#2189]
Please delete the 10 *.u files in this repo that still use namespace. These can be found with this [search](https://github.com/search?q=namespace+repo%3Aunisonweb%2Funison+extension%3Au&type=Code&ref=advsearch&l=&l=). It is a natural thing to want to write scratch files with namespaces and finding examples like these suggests it is still possible but namespace blocks have been removed (but may come back #449).

**Comment by pchiusano** [comment]
@philderbeast PR welcome! Or we'll get to it sometime...
