### ISSUE TITLE
Allow `test` command to take an optional namespace argument

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2190]
So `test .foo.bar` runs all the tests in that namespace. Rather than needing to `cd .foo.bar` then `test` with no args.

**Comment by rlmark** [comment]
I just ran into this as a result of fielding challenges to the Exercism track workflow, +1! Now that we have scoped namespaces, it's most common for folks to work high in their namespace tree with the `lib` directory present (though, I understand this will change in the near future with `projects` work); in any case, it would be nice not to have to `cd` down the namespace tree to run tests.
