### ISSUE TITLE
Passed check(true == false). Failed check(true == true).

### ISSUE THREAD

**Issue by philderbeast** [unisonweb/unison#2198]
While trying to add multiple checks to a single named test I found this oddity:

```
# scratch.u
test> checkTrueIsFalse =
        check (true == false)
        check (true == true)

# ucm
   ⍟ These new definitions are ok to `add`:

      checkTrueIsFalse : [Result]

  Now evaluating any watch expressions (lines starting with `>`)... Ctrl+C cancels.


    2 |         check (true == false)

    ✅ Passed : Proved. (cached)
```

Swapping the order of the checks:

```
# scratch.u
test> checkTrueIsNotTrue =
        check (true == true)
        check (true == false)

# ucm
   ⍟ These new definitions are ok to `add`:

      checkTrueIsNotTrue : [Result]

  Now evaluating any watch expressions (lines starting with `>`)... Ctrl+C cancels.


    2 |         check (true == true)

    🚫 FAILED  (cached)
```

**Comment by pchiusano** [comment]
It's pretty confusing, but what's happening here is that `check` is an expression, not a statement. So the `check (false == true)` result is just being discarded. You can do `check (false == true && (true == true))`. (you need the parens, there's no operator precedence).

Discarding non-unit results like this should be at least a warning, and I created https://github.com/unisonweb/unison/issues/2200 to track that. Going to close this issue though.

Aside is we'd like to revamp the testing library. Among other things, I don't really like having to explicitly combine a bunch of conditions in testing code. It's more ergonomic and can give better error messages to just check them conditions with an effectful function as they come up.

**Comment by philderbeast** [comment]
@pchiusano warning about the discard would be nice.

In each example line 2 is reported as the line of the test failure but that's the discarded check. Shouldn't we be displaying line 3?

**Comment by pchiusano** [comment]
It's just reporting the first line of the test, it doesn't actually know what line is responsible for the failure. Same goes for any watch expression - it just tells you what the first line of the watch expression is when printing out its result. Maybe it would be better to just show the entire watch / test, but it was thought that might be too much.
