### ISSUE TITLE
Learning materials: Abilities part 1 - Motivation + using handlers 

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#2202]
We'll break the Abilities tutorial into 2+ parts - this first part has the goal of getting users comfortable with their core purpose and usage patterns. 

Outlined here: https://www.notion.so/Why-and-how-we-use-Abilities-aa656e2303814570946cd072b4c6fb17 

- [ ] Why do we need them 
- [ ] Mental model
- [ ] How do I “provide an ability”
    - [ ] Using pre-built handlers
    - [ ] What do I do when a function calls for more than one ability handler.
    - [ ] Control flow pt 2. handlers and exception/error handling
 - [ ] Exercises

**Comment by ceedubs** [comment]
Nailed it! https://www.unison-lang.org/learn/fundamentals/abilities/
