### ISSUE TITLE
Learning materials: Abilities part 2 - Writing handlers 

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#2203]
The second part of the Abilities tutorial is about writing handlers.  

- [ ] Write an ability together - Potentially change example from effectful `Stream` to something more concrete (contender: KVStore or Parse)
- [ ] Example handler (where handler contains no internal state - `()` return value)
        - [ ] Dissect handler signature and parts
        - [ ] The `Request` datatype 
- [ ] Example handler (where handler contains no internal state but returns non unit value)
- [ ] Example handler (handler contains internal state)
- [ ] Multi handlers 
- [ ] Exercise / project

**Comment by ceedubs** [comment]
Done! https://www.unison-lang.org/learn/fundamentals/abilities/writing-abilities/
