### ISSUE TITLE
Doc website

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#2204]
We want to be able to render Unison Doc on the website to support the new documentation efforts.

This effort is dependent on being able to serialize docs to JSON and to render them with Elm:
* https://github.com/unisonweb/unison/issues/2112
* https://github.com/unisonweb/codebase-ui/issues/77

Additionally there are other efforts required:
* [x] Setup a UCM for the website docs
* [x] Finalize the way to structure the docs for rendering on the website
* [x] Support <title> element and social sharing image
* [x] Finalize the web-design
* [x] Figure out where the website UI code lives given that the Doc rendering lives in Codebase UI, but other aspect of the website doesn't really belong there.
* [ ] Automate deployment of doc website
* [ ] Add doc section on website and finetune doc output

**Comment by pchiusano** [comment]
Phase 1 is a timeboxed design jam (2 meetings, Simon goes off and mocks a few things up between first and second meeting) to figure out what the front-end will need to do.
