### ISSUE TITLE
Codebase Server: Support returning metadata in JSON

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#2205]
We want to be able to show metadata that exists in a Unison codebase in the UI.
This data is formatted as Unison code and we don't currently have a way, outside of SyntaxText to represent it.

Metadata include things like authors and licenses, but also dates about when a namespace/definition was last updated etc.

Metadata isn't a strict thing, so it can actually include all kinds of Unison types and terms. This effort explore metadata as a more formal construct.

A suggested schema (that can be used for several different endpoints that include metadata):

```elm
type Metadata {
  authors: List Author,
  copyrightHolders: List CopyrightHolder,
  licenses: List License
  createdAt: String, -- ISO 8601 formatted date time 
  updatedAt: String -- ISO 8601 formatted date time
}

type Author = {
  guid: String,
  username: String,
  name: String,
}

type CopyrightHolder = {
  guid: String,
  username: String,
  name: String,
}

type LicenseType = {
  name: String, -- "MIT"
  description: String
}

type License = {
  name: String,
  year: Nat,
  type: LicenseType
}
```

Required to support:
* https://github.com/unisonweb/unison/issues/2172
* https://github.com/unisonweb/unison/issues/2186
* https://github.com/unisonweb/unison/issues/2185

**Comment by mitchellwrosen** [comment]
#wontfix
