### ISSUE TITLE
The codebase server `/list` API doesn't return a `namespaceName` when queried with a hash

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#2214]
Querying a namespace with the list API and a hash doesn't return a name (the value is a `null`):

`GET http://127.0.0.1:8080/asdf/api/list?namespace=%232bbp1bkbef8t4b75sblro3m8kd7sjsgrvcont5sg85su77eich2ncgnoprmn7b8ipto6l5mtjs8t7qrh9pc1ohe7tmfg5r5a4r5ll88` (`%23` is the URL encoded version of `#`)

returns 

```js
{
  "namespaceListingName": null, // this should be "ANSI" or ".ANSI" (?)
  "namespaceListingHash": "#2bbp1bkbef8t4b75sblro3m8kd7sjsgrvcont5sg85su77eich2ncgnoprmn7b8ipto6l5mtjs8t7qrh9pc1ohe7tmfg5r5a4r5ll88",
  "namespaceListingChildren": [ /* ... abbreviated ...  */ ]
}
```
The name should be `ANSI`.

This is blocking https://github.com/unisonweb/codebase-ui/issues/78

**Comment by hojberg** [comment]
The RICE score is based on the `/list` API being used over https://github.com/unisonweb/unison/issues/2172 in the initial version of https://github.com/unisonweb/codebase-ui/issues/78

**Comment by hojberg** [comment]
Rúnar mentions that since oldnames are not working, `namespaceListingName` can be `null`, but shouldn't be a problem for the latest version of a namespace.

**Comment by hojberg** [comment]
Old names effort: https://github.com/unisonweb/unison/issues/2128

**Comment by pchiusano** [comment]
This needs a discussion with @hojberg, @runarorama and @pchiusano to figure out how important it is and next steps, given that it seems like it will require a new repo format (or maybe just some aux tables in the current schema).

**Comment by hojberg** [comment]
Removing the p1 label. We still eventually want to support this, but got around it for the UI by including the codebase hash + namespace name in urls instead.
