### ISSUE TITLE
Codebase server API: `/list` should include a fully qualified name

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#2216]
When querying the `/list`API, there's a relative `namespaceListingName`, which is great, but it would be very helpful to additionally have a `namespaceListingFQN` field (perhaps based on `namespaceListingName` to pick a name if there are multiple). 

The UI currently walks the tree and constructs FQN based on `namespaceListingName` and this is a bit brittle and expects that the `/list` API is always queried from the root, which wont work for https://github.com/unisonweb/codebase-ui/issues/78

❗  Blocks: https://github.com/unisonweb/codebase-ui/issues/78

**Comment by pchiusano** [comment]
Fixed by #2266
