### ISSUE TITLE
Pretty printing multiple list head matches removes parens

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#2224]
The pretty printer removes parens on list head matches when they are chained:

```
match xs with
  x +: (x' +: rest) -> ...
```

gets pretty printed as

```
match xs with
  x +: x' +: rest -> ...
```

which does not type check

**Comment by runarorama** [comment]
I think you meant `+:` and not `:+`

**Comment by hojberg** [comment]
Ah yeah, I always forget the direction of that :D
