### ISSUE TITLE
Syntax sugar for multiple guards on a single pattern

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2227]
Eg 

```
match x with
  Cons x y | x > 10 -> p
           | otherwise -> q
```
Can desugar at parse time to:
```match x with
  Cons x y | x > 10 -> p
  Cons x y | otherwise -> q
```

And optionally we can modify the pretty-printer to use this syntax opportunistically.

**Comment by pchiusano** [comment]
Incidentally, I'm thinking `Cons x y | otherwise` can just be special syntax for `Cons x y` with no guard, rather than `otherwise` being an alias for `true` which is pretty weird.

**Comment by dolio** [comment]
Makes sense. I guess the `otherwise` just wouldn't get displayed unless there are previous identical cases that have guards?
