### ISSUE TITLE
Typechecking regression when calling functions that have covariant-only ability variables

### ISSUE THREAD

**Issue by philderbeast** [unisonweb/unison#2231]
How can I compose `atan . tan` without eta abstraction?

```
# scratch.u
a : Float -> Float
a = tan

b : Float -> Float
b = atan

c : Float -> Float
c x = atan (tan x)

d : Float -> Float
d x = x |> tan |> atan

# ucm
    ⍟ These new definitions are ok to `add`:

      a : Float -> Float
      b : Float -> Float
      c : Float -> Float
      d : Float -> Float
```

Trying with eta reduction:

```
# scratch.u
e : Float -> Float
e = atan . tan

# ucm
  The expression in red

                needs the abilities: {𝕖14}
    but was assumed to only require: {𝕖12, 𝕖13}

  This is likely a result of using an un-annotated function as an argument with concrete abilities. Try adding an annotation to the function definition whose body is red.

      3 | e = atan . tan
                     ^^^
```

**Comment by pchiusano** [comment]
@philderbeast is this with current trunk or with latest release?

**Comment by pchiusano** [comment]
Thanks for reporting. 

Just confirmed trunk has this issue as well. @dolio looks like a type inference regression, it works with latest release.

Note that compose has a pretty general type:

```
.> view compose

  (basedev..) : (b ->{𝕖} c) -> (a ->{𝕖} b) -> a ->{𝕖} c
  (basedev..) f g x = f (g x)
```

**Comment by philderbeast** [comment]
> @philderbeast is this with current trunk or with latest release?

I've been building from source and am at e8dd1d5b7d94857bf5ba7a5e22736bc3010c3162 on trunk.

**Comment by pchiusano** [comment]
@dolio here's another one, likely same issue

```
List.foldLeft (Text.++) "It's " ["Super", "Duper", "Awesome"]
```

```
  The expression in red
  
                needs the abilities: {𝕖10}
    but was assumed to only require: {𝕖11, 𝕖12}
  
  This is likely a result of using an un-annotated function as an argument with concrete abilities. Try adding an annotation to the function definition whose body is red.
  
  The expression in red
  
                needs the abilities: {𝕖10}
    but was assumed to only require: {𝕖11, 𝕖12}
  
  This is likely a result of using an un-annotated function as an argument with concrete abilities. Try adding an annotation to the function definition whose body is red.
  
      1 | > List.foldLeft (Text.++) "It's " ["Super", "Duper", "Awesome"]
                           ^^^^^^^^
```

We talked about stripping covariant-only ability variables from types before typechecking, which is something I think we could also do before pretty-printing instead of the thing we are currently doing which is wrong (see #2242). I guess I wonder if there's some fix that would also just let it work even if those covariant-only variables are still there in the types.

**Comment by dolio** [comment]
Okay, so, one factor here is that base has a bunch of functions with types that are not well designed with respect to the way that the new algorithm works.

Composition has the type:

    (b ->{e} c) -> (a ->{e} b) -> a ->{e} c

The thing that causes the algorithm to get in trouble is that checking `f . g` requires figuring out some compatible solution `e` incorporating the effects of `f` and `g`. But this doesn't happen all at once, it happens by first doing the `f` part and then doing the `g` part. To make this work, you can't just equate things, you have to leave some 'slack' when you solve `e` the first time, but that can lead to multiple variables being in the row, which makes it unclear which should be instantiated.

If composition instead has the type:

    (b ->{e2} c) -> (a ->{e1} b) -> a ->{e1,e2} c

It just works, and this is the type that the new algorithm infers for composition.

`foldLeft` and `foldRight` do the same thing. Their types are like:

    (a ->{e} r ->{e} r) -> r -> [a] ->{e} r

But this isn't the type the new algorithm infers. Instead it's:

    (a ->{e1} r ->{e2} r) -> r -> [a] ->{e1,e2} r

And if you use this type, then your example just works.

I was still getting similar errors when working on stuff on Wednesday, and I'm not sure they were related to these sort of types in base. But the choice of types makes the problem more likely.

**Comment by runarorama** [comment]
We can certainly change the types of these functions in `base`

**Comment by pchiusano** [comment]
The thing is, the existing signature of `compose` is a perfectly reasonable signature that a user might write, so the typechecker should ideally support using it. What about the idea of stripping out covariant-only ability variables from signatures before typechecking? That should work fine for pure functions, not sure when dealing with effectful functions.

**Comment by pchiusano** [comment]
This was fixed (at least for this and other examples) by a recent PR, I can't find it now though.
