### ISSUE TITLE
Always show ability variables if they appear in invariant or contravariant position

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2242]
Example:
``` 
f : ‘a -> Nat
f x = 42
```
Unison will infer that as `forall e a . ‘{e} a -> Nat` but then elide the `’{e}` from the signature on display.

I’m imagining writing:

`removeCovariantAbilities : Type v a -> Type v a` can strip out ability variables in covariant position, and then the term printer should call this instead of whatever it’s doing now.

**Comment by runarorama** [comment]
Is this resolved? Please close if so.

**Comment by pchiusano** [comment]
Ya
