### ISSUE TITLE
Add Float.isNaN and related Float predicates

### ISSUE THREAD

**Issue by philderbeast** [unisonweb/unison#2243]
If someone looks at this, it might also be a good moment to consider whether we should be able to parse or pretty-print float values Infinity, -Infinity and NaN.  ([comment](https://github.com/unisonweb/unison/blob/bf943e2df6b33acfcca549dfb8617d99e3988b35/parser-typechecker/src/Unison/TermPrinter.hs#L166))

_Originally posted by @atacratic in https://github.com/unisonweb/unison/issues/611#issuecomment-516529082_

**Comment by philderbeast** [comment]
Can we please add predicate functions to Float that test for +Infinity, -Infinity and NaN. Haskell's GHC does it with [FFI calls](https://gitlab.haskell.org/ghc/ghc/-/blob/master/libraries/base/GHC/Float.hs#L1416-1426).

**Comment by pchiusano** [comment]
Good idea.

I think we can just have `Float.Infinity : Float` and `Float.NegativeInfinity : Float` and `Float.NaN` as builtins, and then the pretty-printer can use the names for these builtins when printing floats.

**Comment by pchiusano** [comment]
https://github.com/unisonweb/unison/blob/trunk/docs/adding-builtins.markdown is (I think?) mostly up to date if you feel like having a go at this one. :)

**Comment by philderbeast** [comment]
These comments from [primFloat.c](https://gitlab.haskell.org/ghc/ghc/-/blob/master/libraries/base/cbits/primFloat.c) say how to test for these:

```c
   /* Floating point NaN iff exponent is all ones, mantissa is
      non-zero (but see below.) */

    /* A float is Inf iff exponent is max (all ones),
       and mantissa is min(all zeros.) */

    /* A (single/double/quad) precision floating point number
       is denormalised iff:
        - exponent is zero
	- mantissa is non-zero.
        - (don't care about setting of sign bit.)
    */

    /* sign (bit 31) set (only) => negative zero */
```

**Comment by pchiusano** [comment]
@philderbeast ah that's a good point, if we just have a bitwise cast from `Float` to `Nat` then we can just write these in pure unison. I think I like that better.

**Comment by aryairani** [comment]
Maybe this was the motivation for #2313.

**Comment by seaoflanguages** [comment]
Shouldn't this issue be closed?

**Comment by stew** [comment]
we already had the 3 special values, I just added tests for the three values to base: https://share.unison-lang.org/@unison/code/latest/namespaces/public/base/main/;/terms/Float/isNaN
