### ISSUE TITLE
Make unique types the default or make structural/unique required

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2251]
It's very common to leave off `unique` for types that really should be. Suggest just making `structural` a keyword and have `type Foo` mean `unique type Foo` and `structural type Foo` mean the structural type. 

Kinda goes along with #2196

**Comment by pchiusano** [comment]
Steps:

- [x] Change in `Lexer.hs` to add `structural` as a keyword, audit of the lexer to see if that's going to mess anything up.
- [x] `Parser.hs`, add a new error type for missing keyword
- [x] `FileParser.hs`, modify that to look for `unique` keyword
- [x] `PrintError.hs`, modify to render the new parse error
- [x] `DeclPrinter.hs`, modify to insert the keyword as needed
- [x] Update all the transcripts! Idea:
  - [x] replace `unique type` with `basldklfjsdflkjsdf93`
  - [x] replace `type` with `structural type`
  - [x] replace `basldklfjsdflkjsdf93` with `unique type`

**Comment by hojberg** [comment]
This was fixed in #2251 🎉
