### ISSUE TITLE
Docs: `@source` and `@foldedSource` sometimes doesn't include term signatures

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#2261]
There seem to be an inconsistence between the rendered `SyntaxText` of `@source` and `@foldedSource`.

The API returns 2 fields (in a tuple), 1 for folded source and one for unfolded source, but in the attached screenshot, where `@source{List.map}` and `@source{example.example1}` are used, the JSON has different shapes. 

`@source{example.example1}` has the signature included in its "unfolded" field, `List.map` does not.

Resulting example (double signature for `example.example1`, single for `List.map`):

<img width="710" alt="Screen Shot 2021-07-21 at 20 27 42" src="https://user-images.githubusercontent.com/2371/126647892-bdf68cd5-ecd8-4bcb-87e4-95b02f5e1208.png">

The shape of the "unfolded" field should be consistent across terms.

**Comment by hojberg** [comment]
Note that from a frontend perspective it would be preferable if the signature was not included since it is also present in the "folded" source and having them separate makes it easier to work with.

In lieu of that the frontend can chop up the response to remove the signature of the term, by comparing the name of the term and seeing where it appears twice (using newlines isn't sufficient).

**Comment by pchiusano** [comment]
I think I know what's going on - some terms have a programmer-provided signature, in addition to the signature that is automatically put on all top-level terms. Others don't because they were just inferred. 

New behavior: all terms get a type signature put on them, uses the inferred type if there is no programmer-provided one.
