### ISSUE TITLE
Complex formula has operators with too much unindent.

### ISSUE THREAD

**Issue by philderbeast** [unisonweb/unison#2262]
I'm porting Vincenty's inverse solution to unison that I already have in [Haskell](https://github.com/BlockScope/flare-timing/blob/main/lang-haskell/earth/library/Internal/Ellipsoid/PointToPoint/Vincenty/Double.hs#L27-L121) and [F#](https://github.com/BlockScope/meridian-arc/blob/7c19e56e317efaf59691cd75896d05b905701b5a/earth/library/Flight/Vincenty.fs#L170-L262). I've added a `.flight.Geodesy.Vincenty.inverse` function to the codebase with ucm but when I ask to edit it, some math formulae fail to render in the scratch file in a way that compiles. I won't paste the whole function here, just the snippets that are rendered badly. I've shown them as diffs with the edits I had to make to get them accepted by the compiler.

```diff
-        A =
-            1.0
-          + (  u²
-            / 16384.0
-            * (4096.0 + (u² * (-768.0 + (u² * (320.0 - (175.0 * u²)))))))
+        A =
+            1.0
+                + (  u²
+                  / 16384.0
+                  * (4096.0 + (u² * (-768.0 + (u² * (320.0 - (175.0 * u²)))))))
```

```diff
-        y =
-            cosσ
-          * (-1.0 + (2.0 * cos²2σm))
-          - (  B
-            / 6.0
-            * cos2σm
-            * (-3.0 + (4.0 * sin²σ))
-            * (-3.0 + (4.0 * cos²2σm)))
+        y =
+            cosσ
+                * (-1.0 + (2.0 * cos²2σm))
+                - (  B
+                  / 6.0
+                  * cos2σm
+                  * (-3.0 + (4.0 * sin²σ))
+                  * (-3.0 + (4.0 * cos²2σm)))
 ```

I tried for a minimal reproduction but this was reformatted as a single line addition so I'm not sure why unison is respecting lines of formula in one case and not in the other.

```
# scratch.u
A =
    1.0
        + 2.0

# ucm
    ⍟ These new definitions are ok to `add`:

      A : Float

.> add A

  ⍟ I've added these definitions:

    A : Float

.> edit A

  ☝️

  I added these definitions to the top of /Users/pdejoux/dev/src/blockscope/flat-earth/scratch.u

    A : Float
    A =
      use Float +
      1.0 + 2.0

  You can edit them there, then do `update` to replace the definitions currently in this namespace.
```

**Comment by aryairani** [comment]
I think this has been fixed, @philderbeast.

Currently they render as:

```
A : Float
A =
  use Float * + - /
  1.0
    + (u²
        / 16384.0
        * (4096.0 + (u² * (-768.0 + (u² * (320.0 - (175.0 * u²)))))))

y : Float
y =
  use Float * + - /
  cosσ
    * (-1.0 + (2.0 * cos²2σm))
    - (B / 6.0 * cos2σm * (-3.0 + (4.0 * sin²σ)) * (-3.0 + (4.0 * cos²2σm)))
```

Line breaks are still ignored by design, but the unindent seems to be fixed.
