### ISSUE TITLE
Design efficient text manipulation primitives

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2263]
Can’t be higher order

**Comment by pchiusano** [comment]
Rough draft:

```Haskell
unique type Regex txt
  = Literal txt
  | Zero
  | One
  | Star (Regex txt)
  | Or (Regex txt) (Regex txt)
  | Sequence (Regex txt) (Regex txt)
  | Capture (Regex txt)

Text.matches : Regex Text -> Text -> Optional [Text]
Text.matches = <builtin>

-- Bytes.matches : Regex Bytes -> Bytes -> Optional [Bytes]
-- Bytes.matches = <builtin>

Regex.whitespace : Regex Text
Regex.whitespace = ...

Regex.sequence : [Regex a] -> Regex a
Regex.sequence = foldLeft Sequence Zero

-- example
Text.trim : Text -> Text
Text.trim txt = 
  match Text.matches (Regex.sequence [whitespace, Capture (Star One), whitespace]) with
    Some [_, inner, _] -> inner
    _ -> txt
```

Alternately, make `Regex` an opaque builtin, with the constructors becoming builtins, and the `Text.matches` function as before.

**Comment by pchiusano** [comment]
I think I like `Regex` better as a builtin. It can be done more efficiently, without a level of interpretation overhead to convert the Unison type to a Haskell type, and we can also add more regex primitives over time if we want.

**Comment by ceedubs** [comment]
```haskell
Text.trim txt = 
  match Text.matches (Regex.sequence [whitespace, Capture (Star One), whitespace]) with
    Some [_, inner, _] -> inner
    _ -> txt
```

@pchiusano What are the semantics of `One`?. I assumed that it was the multiplicative identity of the semiring. That is, it always matches and consumes no input (often called epsilon in regular expressions). But then `Capture (Star One)` wouldn't make any sense. In the case of `Regex Char` I could see it always matching a single `Char`, but this is a `Regex Text`, so I don't really know what that means.

It might be worth considering what something like `Regex.whitespace` or `Regex.ascii` would look like. With only `Literal` and `Or` things like this could get pretty bulky (`Or (Lit 'a') (Or (Lit 'b') Or (Lit 'c') (...))`). One thing that I've done in the past that seemed to work well (though I haven't been able to find reference of other people doing so maybe there are better ways) is to have constructor that is a discrete interval encoding tree (or possibly the negation of one) of items that would match. I don't think that this makes much sense for `Regex Text`, but for `Regex Char` it allows you to efficiently support ranges.

It might also be worth considering what it would look like to try to do a case-insensitve match. On the one hand, case-insensitivity kind of stops making sense for some characters. On the other hand, people want to do it all the time, so it might be worth considering what it would look like to try to do that if it has to be in terms of `Literal` and `Or`.

Random note: for a while I had a hobby project that was a regular expression lib. It went through multiple stages (at one point it was implemented with recursion schemes and compiled down to an efficient form, when I left it, it had nice applicative capturing sytnax but was horrendously slow). A fun thing that it did was create `Gen` instances for regular expressions and for matches for regular expressions. You can interactively play with it [here](https://ceedubs.github.io/irrec/docs/regex-explorer) :)

**Comment by pchiusano** [comment]
@ceedubs yeah you're right. I goofed that example up. I wrote it thinking `One` would match and consume any single symbol, but you're right that it would typically match the empty string. I was taking inspiration from https://github.com/Gabriel439/slides/blob/main/regex/regex.md That calls the "match 1 char" `dot`. 

They get grep-like speeds for < 64 states.

I am not sure the capturing API is worth the complexity and you can build a more efficient API without capturing. 

To get capturing-like behavior you could have these be the main ways you run a regex:

``` Haskell
Regex.take : Regex txt -> txt -> txt
Regex.drop : Regex txt -> txt -> txt
Regex.takeEnd : Regex txt -> txt -> txt
Regex.dropEnd : Regex txt -> txt -> txt
```

`Regex.take r blah` captures `r` from the front of `blah`, `Regex.drop r blah` captures everything after `r`. `takeEnd` is like `take` but starting from the end.

I think the right move is to do `Regex` as a builtin type that we can add more cases to, like range matches and whatever else we find useful. But it still has to compile down to something, and I'm not sure what. Maybe a cleaned up version the library I linked above?

**Comment by ceedubs** [comment]
@pchiusano it might not need to be all or nothing with capturing. You could provide a capturing function and a separate non-capturing function that only returns `Boolean`. The non-capturing version could compile the AST down to a more efficient form and treat `Capture r` as though it were just `r`.

I'll need to take some time to digest this doc that you linked. I wish that I would have known about this when I was working on my regex project. At a quick glance it talks about a lot of the stuff that I stumbled around for a long time 😅

**Comment by ceedubs** [comment]
> But it still has to compile down to something, and I'm not sure what.

Say that it were to down to an NFA: what does that mean for people using the regex? Ideally they could compile it to the efficient form once and then reuse it in multiple places (within a loop, etc). But would that mean that they would need to have the compiled form as a builtin as opposed to just `Regex`?

**Comment by pchiusano** [comment]
@ceedubs no you can still just have `Regex` as the Unsion type, but on the Haskell side, you have that be an AST which has a lazy field in it which is the compiled form. In this way the compiled form is only computed once and the user doesn't have to explicitly create it, it'll just be created on demand on first use.

**Comment by ChrisPenner** [comment]
As far as designing the Regex AST if we go that route, I found this to be a fascinating read 😄 
https://blog.jle.im/entry/free-alternative-regexp.html

**Comment by pchiusano** [comment]
Consolidating my thoughts a bit more. A builtin type, `Regex`, with this API:

```haskell
Regex.text : Text -> Regex Text
Regex.charRange : Char -> Char -> Regex Text
-- Regex.bytes : Bytes -> Regex Bytes

-- zero or more
Regex.repeat : Regex txt -> Regex txt

-- matches a sequence, greedily
Regex.sequence : [Regex txt] -> Regex txt

-- matches if either matches
Regex.or : Regex txt -> Regex txt -> Regex txt

-- always fails, consuming no input
Regex.fail : Regex txt

Regex.take : Regex txt -> txt -> txt
Regex.drop : Regex txt -> txt -> txt
Regex.takeEnd : Regex txt -> txt -> txt
Regex.dropEnd : Regex txt -> txt -> txt
```

**Comment by pchiusano** [comment]
Okay @dolio is working on this. API is below. **This is going to be way way way faster for text stuff.** No conversion to and from boxed lists of characters. And if you use `many` in your pattern, that just runs as a fast loop in Haskell. The implementation uses some rather neat partial evaluation stuff also, so the pattern is compiled down to ordinary Haskell functions to represent the state machine. Should be extremely low overhead.

```haskell
-- just checks for a match
Pattern.isMatch : Pattern a -> a -> Boolean

-- checks for a match and returns captures
Pattern.run : Pattern a -> a -> Optional ([a], a)
```

Notice that it's `Pattern a`, where `a` is the underlying sequence type. Initially, we're just adding primitives for `Pattern Text`, but we can later add `Pattern Bytes` primitives for doing efficient binary parsing stuff. It can even share the implementation.

```haskell
-- succeeds if the input starts with this text
Text.patterns.literal : Text -> Pattern Text

-- consume any single char
Text.patterns.anyChar : Pattern Text
```

Here's the other combinators:

```haskell
-- capture the segment of text this matches
Pattern.capture : Pattern a -> Pattern a 

-- 0 or more repetitions of this pattern
Pattern.many : Pattern a -> Pattern a 

-- left-biased choice: tries the first, and if it fails, tries the second 
Pattern.or : Pattern a -> Pattern a -> Pattern a 

-- sequencing: run the second pattern on leftover input after first (assuming the first succeeds)
-- join [many (literal "hi"), capture (many digit)] 
Pattern.join : [Pattern a] -> Pattern a
```

And other leaf-level char patterns:

```haskell
-- consumes one char that exists in the given list
Text.patterns.charIn : [Char] -> Pattern Text

-- consumes one char that DOES NOT exist in the given list
Text.patterns.notCharIn : [Char] -> Pattern Text

-- consumes one char in the given range
Text.patterns.charRange : Char -> Char -> Pattern Text 

-- consumes one char NOT in the given range
Text.patterns.notCharRange : Char -> Char -> Pattern Text

-- succeeds if given empty input 
Text.patterns.eof : Pattern Text

-- consume a single digit
Text.patterns.digit : Pattern Text

-- consume a single letter
Text.patterns.letter : Pattern Text

-- consume a single space character (any `Char.isSpace`)
Text.patterns.space : Pattern Text

-- consume a single space character (any `Char.isPunctuation`)
Text.patterns.punctuation : Pattern Text

-- can add others easily later
```

`patterns.digit` and so on could be defined in terms of other stuff but having them as special cases lets us do fancier things in the interpreter.
