### ISSUE TITLE
check (0 == 0) versus check (A 0 == A 0)

### ISSUE THREAD

**Issue by philderbeast** [unisonweb/unison#2269]
I can write a test `0 == 0` in the presence of a unique type `A`.

```
# scratch.u
test> zeroEq = check (0 == 0)

# ucm
    ⍟ These new definitions are ok to `add`:

      zeroEq : [Result]

  Now evaluating any watch expressions (lines starting with `>`)... Ctrl+C cancels.


    1 | test> zeroEq = check (0 == 0)

    ✅ Passed : Proved. (cached)
```

```
# scratch.u
unique type A = A Nat
test> zeroEq = check (0 == 0)

# ucm
    ⍟ These new definitions are ok to `add`:

      unique type A
      zeroEq : [Result]

  Now evaluating any watch expressions (lines starting with `>`)... Ctrl+C cancels.


    2 | test> zeroEq = check (0 == 0)

    ✅ Passed : Proved. (cached)
```

If I also define `(A.==)` for this unique type, the `Nat` type from the test is inferred for `(A.==)` even though I've added an explicit type signature `(A.==) : A -> A -> Boolean`.

```
# scratch.u
unique type A = A Nat
(A.==) : A -> A -> Boolean
(A.==) x y =
  (A x') = x
  (A y') = y
  x == y
test> zeroEq = check (0 == 0)

# ucm
  The 1st argument to `(A.==)`

            has type:  Nat
      but I expected:  A

      2 | (A.==) : A -> A -> Boolean
      3 | (A.==) x y =
      4 |   (A x') = x
      5 |   (A y') = y
      6 |   x == y
      7 | test> zeroEq = check (0 == 0)
```

 If I check `A 0 == A 0` unison hangs.

```
# scratch.u
unique type A = A Nat
(A.==) : A -> A -> Boolean
(A.==) x y =
  (A x') = x
  (A y') = y
  x == y
test> A.test.eq = check (A 0 == A 0)

# ucm (hangs!)
    ⍟ These new definitions are ok to `add`:

      unique type A
      A.==      : A ->{g} A ->{g} Boolean
      A.test.eq : [Result]

  Now evaluating any watch expressions (lines starting with `>`)... Ctrl+C cancels.
```

**Comment by philderbeast** [comment]
Could this be because the `(A.==) : A -> A -> Boolean` type signature is not using the `unique type A = A Nat` from the scratch file when the `A` has not yet been added to the codebase?

**Comment by pchiusano** [comment]
The current behavior is that if a name suffix is unique in the scratch file, that is the one used, even if that name suffix also exists in the codebase. The idea is that things in the local file take precedence. Though I think a warning would be nice in that situation, or perhaps we should reconsider the behavior.

In any case, with the current behavior in mind, this function just has an infinite loop:

```haskell
(A.==) : A -> A -> Boolean
(A.==) x y =
  (A x') = x
  (A y') = y
  x == y
```

Since that `x == y` is just being resolved to `x A.== y`, using the `==` that is unique to the scratch file.

If you instead change that line to `x' Nat.== y'` then it should work, or also you could do:

```haskell
(A.==) : A -> A -> Boolean
(A.==) x y =
  use Nat ==
  (A x') = x
  (A y') = y
  x == y
```

**Comment by philderbeast** [comment]
Thanks @pchiusano. This might be a gotcha for people coming from Haskell and expecting `==` to be resolved the same way, via typeclass instance resolution.
