### ISSUE TITLE
`raw` multiline codeblocks in the docs indent themselves weirdly  

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#2271]
Upon saving a Doc with a `raw` codeblock element, the element will indent the code successively. 

```
type Book = Book [Text]

flipToPage: Nat -> Book -> Optional Text
flipToPage desiredPage book = 
    match book with 
        Book pages -> List.at desiredPage 
        _ -> None  
```
becomes: 
``` raw
         type Book = Book [Text]
                
                        flipToPage: Nat -> Book -> Optional Text
                        flipToPage desiredPage book = 
                          match book with 
                            Book pages -> List.at desiredPage 
                            _ -> None  
```

Odd indentation is present upon viewing source in the console, and editing code once saved into the ucm.

**Comment by aryairani** [comment]
@pchiusano Can you take a look at this and see if it's something obvious with the doc renderer?

**Comment by pchiusano** [comment]
I tried reproducing this with current trunk and wasn't able to... so maybe it somehow depends on the surrounding doc. @rlmark do you have a full (minimal) example transcript?

````
d = {{

# Oog

Testing 1 2 3

``` raw
type Book = Book [Text]

flipToPage: Nat -> Book -> Optional Text
flipToPage desiredPage book = 
    match book with 
        Book pages -> List.at desiredPage 
        _ -> None  
```

Dos

}}
````

**Comment by pchiusano** [comment]
@rlmark I have a theory about what's going on - whitespace after the start of the block is being ignored, but then after that, it just reads the whole string until the closing triple backtick:

````
  Here is an example:

  ``` raw
  This line won't be indented.
  But this line will be.
  ```
````

If you unindent the whole thing, I'm guessing it works:

````
Here is an example:

``` raw
This line won't be indented.
But this line will be.
```
````

But I think the pretty-printer will produce the indented version.

Assuming this is what's going on, which you can verify, I have an idea for a fix in the lexer - it can note the column where the backticks begin, and then, after each newline, strip that number of whitespace characters that begin each line.

**Comment by rlmark** [comment]
I'll write up some samples to test the indentation theory!

**Comment by rlmark** [comment]
Ok, I think you're right @pchiusano. 🧠  If the raw block starts with no indentations, there is no format problem. 

Looks good: 
````
docTest1 = {{
# No indentation 

```raw 
myVal1 = 42 
myVal2 = 43
myVal4 = 44
```
}}
````

But if the raw text body is indented at all, the lines after the first line in the raw block are offset. They're offset by a function of how "indented" the raw text body is. So if your raw text body is at 2 tabs / 4 spaces, your text body has more of a "stair-step" appearance than if your raw text body is at 1 tab / 2 spaces. 

````
docTest2 = {{
  # Full doc body indented

  ```raw 
  myVal1 = 42 
  myVal2 = 43
  myVal4 = 44
  ```

    ```raw
    indented1= "hi"
    indented2="this is two indents"
    ```
  I am two spaces over
}}
````

**Comment by atacratic** [comment]
There are some bits of code for handling the old doc format it might be good to be aware of - some slightly horrific code I put in. Don't know if it's kicking in for new docs (or if it might help if some of it did):

Normalization in parser: https://github.com/unisonweb/unison/blob/85435c3c3c6cd89d29f51b95be0100458ec13dc2/parser-typechecker/src/Unison/TermParser.hs#L571

Some whitespace munging in the old lexer: https://github.com/unisonweb/unison/blob/85435c3c3c6cd89d29f51b95be0100458ec13dc2/parser-typechecker/src/Unison/Lexer.hs#L632

For completeness, V1 pretty: https://github.com/unisonweb/unison/blob/85435c3c3c6cd89d29f51b95be0100458ec13dc2/parser-typechecker/src/Unison/TermPrinter.hs#L688

**Comment by pchiusano** [comment]
@atacratic thanks, yeah, we might crib from there!
