### ISSUE TITLE
Destructuring bind parse bug

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2281]
Spotted by @alvaroc1
```
foo : '{Stream Nat} ()
foo = 'let
  (x,y) = (1,2)
  Stream.emit 1
  Stream.emit 2

foo2 : '{Stream Nat} ()
foo2 = 'let
  match (1,2) with
    (x,y) ->
      Stream.emit 1
      Stream.emit 2

> Stream.toList! foo
> Stream.toList! foo2
```
`foo2` returns [1,2] as expected, but `foo` returnes just `[2]`, even those these should parse the same.

Workaround for now is to not use the destructuring bind sytnax for this example. It’s weird because the syntax works fine in other situations.

**Comment by pchiusano** [comment]
This has been fixed. I seem to recall @dolio fixed something related to this but I can't find the PR.

**Comment by dolio** [comment]
The thing I fixed was destructuring binds causing the remaining bindings in the same sequence to be recursive, even if they don't need to be.
