### ISSUE TITLE
`squash` discards history of all sub-namespaces

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2309]
`squash new old` where `new` is ahead of `old` should keep all the `old` history and just create (at most) a single step for any updated subnamespace.

Instead it appears to discard all history of all subnamespaces of `old`, leading to really bad LCAs later.

Step 1 is just a transcript to reproduce this.

**Comment by aryairani** [comment]
Eep!

**Comment by aryairani** [comment]
IIRC this would be a new command. I don't think any special knowledge is needed to implement this, but I'm happy to discuss or review.

**Comment by aryairani** [comment]
Closing this because history for subnamespaces at all is on its way out for now.
