### ISSUE TITLE
Bitwise casting from/to Int, Nat, Float

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2313]
We could use these
```
-- bitwise casting from Nat <-> Float <-> Int
Float.toRepresentation : Float -> Nat
Float.fromRepresentation : Nat -> Float
Int.toRepresentation : Int -> Nat
```

**Comment by aryairani** [comment]
I worry that this will introduce a whole can of worms. Is there something more specific we could do? When would we use these?

**Comment by aryairani** [comment]
@pchiusano and I chatted on the phone and he more or less convinced me that this is fine, although we didn't discuss names specifically ;-)
