### ISSUE TITLE
can't override default metadata for deeper namespaces, only union

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#2314]
With this `~/.unisonConfig`, 
```
DefaultMetadata = [ ".config.author.arya"
                  , ".config.license.arya_mit_2021" ]

DefaultMetadata {
  cantstop = [".config.license.arya_mit_2021"]
  dogfood = ["#1lmvrom87b","#nr47uo1650"]
}
```

if I add something to `.dogfood`, I get the top-level default metadata as well as the `.dogfood` metadata.  I could imagine wanting that, but I didn't in this case; I wanted to apply only a unisoncomputing license (`#1lmvrom87b`) and not the `arya_mit_2021` license.

**Comment by mitchellwrosen** [comment]
fixed by #4574
