### ISSUE TITLE
Warn message on adding terms which are missing author/license info

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#2319]
@hojberg and I were pairing in a new codebase and after pushing our code to Share we realized that it was missing license and authorship info. To help avoid this in the future we could create a "warn" message when adding terms which are missing authorship / license metadata to the unison codebase. 

Alternatively, we could make terms which do not have license/author metadata a component of TODO and then make TODO more visible to the user, and then allow the user to bulk add metadata to terms. 

The former case is probably a faster win for the UCM and the user.

**Comment by aryairani** [comment]
This is part of a growing set of tickets that I'd call "not relevant today because the affected feature has been removed, but relevant in the future if a similar feature is ever reintroduced". However, I'm not sure what to do with such tickets for now other than close them, so ...
