### ISSUE TITLE
find_type_mentions_index table has redundant rows

### ISSUE THREAD

**Issue by stew** [unisonweb/unison#2332]
I was exploring why the database for my codebase is so large and found that the `find_type_mentions_index` table is the largest. Looking at this table it seems that there are many duplicate rows. Here's the table schema:

```
sqlite> .schema find_type_mentions_index
CREATE TABLE find_type_mentions_index (
  type_reference_builtin INTEGER NULL CONSTRAINT find_type_mentions_index_fk1 REFERENCES text(id),
  type_reference_hash_id INTEGER NULL CONSTRAINT find_type_mentions_index_fk2 REFERENCES hash(id),
  type_reference_component_index INTEGER NULL,
  term_referent_object_id INTEGER NOT NULL CONSTRAINT find_type_mentions_index_fk3 REFERENCES object(id),
  term_referent_component_index INTEGER NOT NULL,
  term_referent_constructor_index INTEGER NULL,
  CONSTRAINT find_type_mentions_index_c1 CHECK (
    (type_reference_builtin IS NULL) =
    (type_reference_hash_id IS NOT NULL)
  ),
  CONSTRAINT find_type_mentions_index_c2 CHECK (
    (type_reference_hash_id IS NULL) =
    (type_reference_component_index IS NULL)
  )
);
CREATE INDEX find_type_mentions_index_type ON find_type_mentions_index (
  type_reference_builtin,
  type_reference_hash_id,
  type_reference_component_index
);
```

When I count the number of rows in the table:

```
sqlite> select count(*) from find_type_mentions_index;
696323
```

and the number of unique rows in the table:

```
sqlite> select count(*) from (select distinct type_reference_builtin,type_reference_hash_id,type_reference_component_index, term_referent_object_id,term_referent_component_index ,term_referent_constructor_index from find_type_mentions_index);
44389
```

We find that the table is 15 times as large as it needs to be:
```
sqlite> select 696323.0 / 44389;
15.6868368289441
```

And note that this table and its index make up more than 50% of the data in our database!

**Comment by aryairani** [comment]
I just noticed this isn't the case on my local codebase, which surprised me. 🤔

There shouldn't ever be duplicates here, but I can't find where or how these duplicates are getting created either.

**Comment by aryairani** [comment]
I was planning to fix this by adding a unique constraint across the whole relation, but when I sat down to do it, I realized I didn't necessarily want to put another index into the DB.  So now I'd like to figure out where the duplication is happening at runtime.

**Comment by mitchellwrosen** [comment]
A unique index would certainly help track down where the duplicates are coming from, whether or not we actually want that index long-term

**Comment by aryairani** [comment]
Good idea.

If we are trying that, we have to temporarily remove `ON CONFLICT DO NOTHING` from `addToTypeIndex` and `addToTypeMentionsIndex` as well.  I don't know if this problem occurs with the dependents index too (`addToDependentsIndex`), but I don't see why it would be any different from the other two.

**Comment by mitchellwrosen** [comment]
Could you publish your codebase @stew, if you still have it?

Edit: nevermind, I found a codebase in the wilderness with this property.

```
.> pull git@github.com:unisonweb/share.git share
```

**Comment by mitchellwrosen** [comment]
@aryairani I looked into this a bit and found one fishy and obviously wrong thing, but I don't have a complete fix yet.

One question I have for you is whether during a `sync22` a single object should ever fall down into the "not synced" code path more than once.

```haskell
  O oId ->
    isSyncedObject oId >>= \case
      Just {} -> pure Sync.PreviouslyDone
      Nothing -> do
        -- right here
```

Just based on the general flow of the sync algorithm I would have guessed "no", but tracing says "yes", and I'm wondering if that's unexpected to you.

**Comment by aryairani** [comment]
@mitchellwrosen Hmm, interesting. That is unexpected.

`isSyncedObject` first looks in `oCache` for a corresponding `oId` in the target codebase.  My first thought at your comment was "Oh, maybe it's being evicted from the cache?" but that doesn't make sense because a) the cache is big enough that nothing should be getting evicted, and b) even if the answer isn't in the cache, it shouldn't copy something that already exists in the target:

```haskell
isSyncedObject :: ObjectId -> m (Maybe ObjectId)
isSyncedObject = Cache.applyDefined oCache \oId -> do
  hIds <- toList <$> runSrc (Q.hashIdsForObject oId) -- get the local hashId for the local object
  hIds' <- traverse syncHashLiteral hIds -- get or create remote hashIds for those local hashIds
  ( nubOrd . catMaybes
      <$> traverse (runDest . Q.maybeObjectIdForAnyHashId) hIds'
    ) -- look for remote objectids for the remote hashids
    >>= \case
      [oId'] -> do
        when debug $ traceM $ "Source " ++ show oId ++ " is Dest " ++ show oId'
        pure $ Just oId' -- there's exactly one, so save it in the cache and jump back to `pure Sync.PreviouslyDone`
      [] -> pure $ Nothing -- there's none, so jump back to `Nothing`, but only once!
      oIds' -> throwError (HashObjectCorrespondence oId hIds hIds' oIds') -- there's more than one? crash
```

So no, it shouldn't be able to get to the `--right here` more than once for the same `oId`.

**Comment by aryairani** [comment]
Update: We determined that we can normally enter the region in question more than once.  On an earlier entry we may abort early if we discover missing dependencies.  But we shouldn't enter the region again after a successful transfer.
