### ISSUE TITLE
Doc rendering - Unison codeblock syntax doesn't preserve inner pattern match names 

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#2333]
Block codeblock examples which use a pattern match render inner pattern match names in odd manner

The following codeblock in a docs block 
```
  use Universal
  myMatch : Either Text Text -> Either Text Text 
  myMatch = cases  
    Right _ -> Right "I found a Right"
    leftValue@(Left b) | b === "oh no" -> leftValue 
    Left _ -> Left "I found a Left"
```

Turns into 

```
myMatch h4ohj0sdjs1 =
  match h4ohj0sdjs1 with
    Left _pattern2  ->
      use Universal ==
      if _pattern == "oh no" then h4ohj0sdjs1
      else Left "I found a Left"
    Right _pattern1 -> Right "I found a Right"
```

A text file with a doc blob: 
[patternMatchDocIssue.txt](https://github.com/unisonweb/unison/files/7008774/patternMatchDocIssue.txt)

**Comment by aryairani** [comment]
Granted, I don't know a ton about docs, but I would expect it to work if you made it a `@typecheck` block; does it? (Or, why not?)

**Comment by aryairani** [comment]
Actually, I can't reproduce this today. Could you confirm whether it's fixed?

**Comment by aryairani** [comment]
I still can't reproduce:
<img width="703" alt="image" src="https://github.com/unisonweb/unison/assets/538571/b2b6a249-3fa3-4396-9693-a48b88f5ea9f">
going to assume fixed; but lmk if not
