### ISSUE TITLE
Adding to a large codebase is slow

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2338]
I’ve noticed that adding definitions to the codebase is quite slow (like maybe 10s?). It seems like it pauses for a long time during the default metadata step, but I’m not certain of this.

**Comment by mitchellwrosen** [comment]
I think this is partially addressed by #2458, maybe fully. More work is needed to make diffing branches faster (for snappier `link`, `unlink`, `merge` etc.), but that may fall under a different issue.

**Comment by mitchellwrosen** [comment]
I'm going to close this because the main cause of slowness has been addressed by #2458 (and a few other patches improved the branch diff performance, too).
