### ISSUE TITLE
cannot view some terms in my codebase

### ISSUE THREAD

**Issue by stew** [unisonweb/unison#2345]
I know of at least two terms in my codebase which I'm not able to view or edit. If I try to view or edit them my ucm process starts chewing through memory. I've let it run for 30 minutes and ~60Gb of ram without gettng a response. I've gone through the process of squashing this codebase compeltely, and no matter what, for at least these two terms, I don't seem to be able to get ucm to show me the body of these functions

**Comment by pchiusano** [comment]
Hmm. Sounds like an infinite loop of some sort. Do you know the hashes for the definitions? `names foo` will show the hashes for a definition `foo`.

As a first step, I'd use `move.term`/`move.type` to move the definitions into a namespace, and then push that namespace to a fresh git repo. Then we can reproduce the issue with a transcript.

**Comment by pchiusano** [comment]
My money is on some sort of infinite loop in the pretty-printer which somehow we've never hit before.
