### ISSUE TITLE
M2h base changes

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2347]
Base library should be updated for M2h release. Here’s a checklist: 

- [x] Merge open base PRs
- [x] Add aliases for new builtins that are present in releases/M2h tag of UCM. Maybe use `builtins.merge` and `diff.namespace` to help find new definitions?
- [x] `delete.namespace .releases._latest`
- [x] `squash .trunk releases._M2h`
- [x] `fork .releases._M2h .releases.latest`

**Comment by runarorama** [comment]
Released in root hash `#hl9um4vnig` 🦄
