### ISSUE TITLE
UCM onboarding improvements

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2348]
- [x] UCM should just go ahead and create a codebase in `~/` if none exists, rather than requiring this `init` step. Can instead add a `--no-init` flag or something to disable this functionality.
- [x] UCM should just go ahead and pull the correct version of base on codebase initialization. Can add a `--no-base` flag or something to disable this functionality.
- [x] Make author/license setup painless, this probably needs design

**Comment by stew** [comment]
perhaps include #2326 with this effort

**Comment by rlmark** [comment]
Proposal for another task/story: 
When running `init` a user most likely wants to start programming in Unison immediately, currently `init` drops the user back into the terminal to start the codebase in a second command. Would it be an onboarding improvement to change the behavior of `init` to open the UCM? Would that be a non-trivial amount of work to implement?

**Comment by rlmark** [comment]
I'm gonna close this for now! Hopefully onboarding is a bit easier for new codebases.
