### ISSUE TITLE
Typechecker hang in this example

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2355]
Here’s a self-contained example that hangs the typechecker. Adding a type signature on the inner function `go` causes it to typecheck fine.

```
ability A t g where 
  fork : '{g, A t g} a -> t a
  await : t a -> a
  empty! : t a
  put : a -> t a -> ()

example : '{A t {}} Nat
example = 'let
  r = A.empty!
  -- adding this signature makes it not loop
  -- go : Nat ->{A t {}} x
  go u = 
    t = A.fork '(go (u + 1))
    A.await t
  
  go 0
  t2 = A.fork '(A.put 10 r)
  A.await r
```

**Comment by dolio** [comment]
Somehow the typechecker is deciding that the `go u = A.fork '(go (u+1))` sort of thing means that we should do a refinement `e = A t e`, and there's no occurs check on that part. Not sure exactly why yet. I think it might have to do with the stand alone `g` in `fork` getting associated with effect inference variable for `go`.
