### ISSUE TITLE
Add `--no-base` flag

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2398]
~~I don’t think this one is particularly urgent since the autoinitialization only affects totally empty codebases.~~

Disregard, @aryairani thinks this one is pretty important to support local testing. So I'd try to knock it out. :)

**Comment by aryairani** [comment]
Wait, 100% of codebases start out totally empty.

**Comment by pchiusano** [comment]
Ha, I just meant... it will only be run once for a codebase, then never again. It also isn't run for transcripts.

It's probably more a feature that we might use sometimes when developing Unison, like for testing purposes. I'm not sure many end-users would make use of it.

**Comment by pchiusano** [comment]
Fixed by #2414
