### ISSUE TITLE
pretty printer: Unit applied to type constructor is printed with !

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#2402]
`Some 3` is printed as `Some 3`, but `Some ()` is printed as `!Some`.

I'm guessing that there's some logic to pretty-print unit being applied to a thunk (a _function_) that is also being applied to type constructors.

[Here](https://gist.github.com/ceedubs/3bd3a09edc6b3a2bf0819f6d07398d6c) is a transcript with a couple of failing examples.

**Comment by ceedubs** [comment]
I just realized that this isn't actually a problem for a pretty-printing/parsing round trip, because `!Some` is also a valid way to construct an `Optional Unit`.

I guess that I don't know if this is a technically a bug, then. But it's not how I'd expect a data structure to be printed.

**Comment by pchiusano** [comment]
Suggested fix in lieu of something fancier - if the head of the function application is a `Term.Constructor`, do `Foo ()` (or more generally `Foo x y ()`), otherwise if it's not, render as `!Foo` or `!(Foo x y)`.
