### ISSUE TITLE
content-addressed updates kind of break TDD/implementation stubs

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#2406]
This is a variation of previous discussions about how a top-level term like `numRetries = 3` means that if you change it to `numRetries = 4`, `ucm` will attempt to update _every_ top-level term with a value of `3` to now be `4`.

In this case you might stub out two different functions as you start some test-driven development:

```haskell
fn1 : Nat -> Text
fn1 = .base.todo

fn2 : Nat -> Text
fn2 = .base.todo
```

If you fill in an implementation for `fn1`, then `ucm` will also update `fn2` to point to your new implementation for `fn1`.

```
(The old definition is also named fn2. I'll update this name too.)
```

[Here](https://gist.github.com/ceedubs/8dce1f34464469c034242fbab4bfae1b) is a transcript that shows the issue and below is the output of it.

## transcript output

```unison
fn1 : Nat -> Text
fn1 = .base.todo

fn2 : Nat -> Text
fn2 = .base.todo
```

```ucm

  I found and typechecked these definitions in scratch.u. If you
  do an `add` or `update`, here's how your codebase would
  change:
  
    ⍟ These new definitions are ok to `add`:
    
      fn1 : Nat -> Text
      fn2 : Nat -> Text

```
```ucm
.> add

  ⍟ I've added these definitions:
  
    fn1 : Nat -> Text
    fn2 : Nat -> Text

```
```unison
fn1 : Nat -> Text
fn1 = Nat.toText
```

```ucm

  I found and typechecked these definitions in scratch.u. If you
  do an `add` or `update`, here's how your codebase would
  change:
  
    ⍟ These names already exist. You can `update` them to your
      new definition:
    
      fn1 : Nat -> Text
        (The old definition is also named fn2. I'll update this
        name too.)

```
```ucm
.> update

  ⍟ I've updated these names to your new definition:
  
    fn1 : Nat -> Text
      (The old definition was also named fn2. I updated this
      name too.)

```
```unison
> fn1 3
```

```ucm

  ✅
  
  scratch.u changed.
  
  Now evaluating any watch expressions (lines starting with
  `>`)... Ctrl+C cancels.

    1 | > fn1 3
          ⧩
          "3"

```
```unison
> fn2 3
```

```ucm

  ✅
  
  scratch.u changed.
  
  Now evaluating any watch expressions (lines starting with
  `>`)... Ctrl+C cancels.

    1 | > fn2 3
          ⧩
          "3"

```

**Comment by pchiusano** [comment]
Yeah, this is a known issue. I'd say it's probably an instance of: https://github.com/unisonweb/unison/issues/2252

As a workaround for now, you can write something like

```Haskell
fn2 : Nat -> Text
fn2 n = todo ("implement fn2", n)
```

Or otherwise work some unique name or id into the stubbed implementation.

**Comment by ceedubs** [comment]
I'm going to go ahead and close this out. There is at least one other issue for this sort of thing, and I think that the workaround is reasonable as we explore content-addressed updates.
