### ISSUE TITLE
`Debug.trace : a -> ()`

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2411]
Behaves like `a -> ()` but prints out the `a` to the console as a side effect, using the same machinery as `bug` or `todo` - it decompiles the `a` then pretty-prints it.

There’s currently `Debug.watch : Text -> b -> b` and this would basically supercede that, allowing any value to be printed, not just `Text`.

I find `Debug.watch` unpleasant since it requires doing a bunch of string munging. The default pretty-printing is often sufficient for debugging purposes.

If the value cannot be decompiled it can just print whatever but shouldn't halt execution.

WDYT?

**Comment by pchiusano** [comment]
@alvaroc1 suggested just `a -> ()` as the signature for the primitive which I think I prefer. We can always other variations like

```Haskell
Debug.traceThen : a -> b -> b
Debug.traceThen a b =
  trace a
  b
```

**Comment by dolio** [comment]
It can't use the same machinery, which is to throw an exception with the value in it. Entirely new machinery could be added, though.
