### ISSUE TITLE
error-prone update behavior with code cycles 

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#2425]
@hoelzro #1794 may be related to this.

This issue description was created from a transcript. The raw transcript can be found [here](https://gist.github.com/ceedubs/4ed8113558b4bc2a700c6e4802893424), and the output is pasted below.

When there is a cycle in code (ex: function `f` calls function `g` and function `g` calls function `f`), if you edit only one of the functions at a time and then run a `ucm` `update`, it won't fully propagate the change that was made.

In this example, `isEven` and `isOdd` call into each other. They are both created in a scratch file and added at the same time, and everything works as one would expect.

```unison
isEven : Nat -> {Stream Text} Boolean
isEven n =
  emit ("isEven called with " ++ (Nat.toText n))
  if n Nat.== 0 then true
  else if n Nat.== 1 then false
  else isOdd (decrement n)

isOdd : Nat -> {Stream Text} Boolean
isOdd n =
  emit ("isOdd called with " ++ (Nat.toText n))
  if n Nat.== 1 then true else (isEven (decrement n))

isOddLogs : Nat -> [Text]
isOddLogs n =
  (logs, res) = !(toListWithResult '(isOdd n))
  logs :+ ("result is " ++ (Boolean.toText res))
```

```ucm

  I found and typechecked these definitions in scratch.u. If you
  do an `add` or `update`, here's how your codebase would
  change:
  
    ⍟ These new definitions are ok to `add`:
    
      isEven    : Nat ->{Stream Text} Boolean
      isOdd     : Nat ->{Stream Text} Boolean
      isOddLogs : Nat -> [Text]

```
```ucm
  ☝️  The namespace .testing is empty.

.testing>add

  ⍟ I've added these definitions:
  
    isEven    : Nat ->{Stream Text} Boolean
    isOdd     : Nat ->{Stream Text} Boolean
    isOddLogs : Nat -> [Text]

```
```unison
> isOddLogs 4
```

```ucm

  ✅
  
  scratch.u changed.
  
  Now evaluating any watch expressions (lines starting with
  `>`)... Ctrl+C cancels.

    1 | > isOddLogs 4
          ⧩
          [ "isOdd called with 4",
            "isEven called with 3",
            "isOdd called with 2",
            "isEven called with 1",
            "result is false" ]

```
If you inspect their hashes, you can see that Unison gives them a matching hash prefix, because the cycle is detected and they are handled as a group.

```ucm
.testing>names isOdd

  Term
  Hash:   #6vtcjksd1u.0c2
  Names:  isOdd

.testing>names isEven

  Term
  Hash:   #6vtcjksd1u.1c2
  Names:  isEven

```
**the problem**

The problem comes if you decide that you want to change one of the functions. Here we just change the log message from `isOdd`:

```unison
isOdd : Nat -> {Stream Text} Boolean
isOdd n =
  emit ("isOdd *VERSION 2* called with " ++ (Nat.toText n))
  if (n Nat.== 1) then true else (isEven (decrement n))
```

```ucm

  I found and typechecked these definitions in scratch.u. If you
  do an `add` or `update`, here's how your codebase would
  change:
  
    ⍟ These names already exist. You can `update` them to your
      new definition:
    
      isOdd : Nat ->{Stream Text} Boolean

```
```ucm
.testing>update

  ⍟ I've updated these names to your new definition:
  
    isOdd : Nat ->{Stream Text} Boolean

```
Let's check the output now:

```unison
> isOddLogs 4
```

```ucm

  ✅
  
  scratch.u changed.
  
  Now evaluating any watch expressions (lines starting with
  `>`)... Ctrl+C cancels.

    1 | > isOddLogs 4
          ⧩
          [ "isOdd *VERSION 2* called with 4",
            "isEven called with 3",
            "isOdd called with 2",
            "isEven called with 1",
            "result is false" ]

```
As you can see, we updated the `isOdd` definition to include our new log message, but it still points to an implementation of `isEven` that points to the _old_ `isOdd` implementation with the original log message.

You can also see that the hash for `isEven` is the same, but the hash for `isOdd` has changed and is no longer prefixed by the special cycle group hash.

```ucm
.testing>names isOdd

  Term
  Hash:   #3op6h1d6cj
  Names:  isOdd

.testing>names isEven

  Term
  Hash:   #6vtcjksd1u.1c2
  Names:  isEven

```
**the solution**

In some ways, this is Unison doing its job, but it makes working with code cycles _really_ error-prone. I spent half of yesterday chasing my tail because I didn't realize that this was going on.

One possible "solution" would be that if a user does a `ucm` `edit` command for a term that is part of a cycle, `ucm` could put the code for all of the terms within the cycle into the scratch file and output a message explaining why it did that. This won't fix every troublesome case (for example a user could just start defining a new implementation of the term without using the `edit` command), but it seems fairly simple and probably avoids the issue most of the time.

**Comment by pchiusano** [comment]
Yeah, I think the correct behavior is to have the `edit` command actually give you the full cycle of definitions. So if you `edit ping` the scratch file gets both `ping` and `pong`

**Comment by aryairani** [comment]
The message is key.

What should it do after giving you the full cycle of definitions but you delete some of them from the scratch file before hitting `update`?

A warning is probably warranted here too.

**Comment by ceedubs** [comment]
@aryairani 👍 a warning there could definitely be useful as well.

The biggest problem with the current state is that it's pretty easy to edit a term and not realize that you are falling into this trap. I think that warning the user that they might want to be editing `x, y, z` terms as well would go a long way.

**Comment by aryairani** [comment]
Strongly agree, thanks for writing this up.

**Comment by aryairani** [comment]
@ChrisPenner and/or @mitchellwrosen This is a high-value one if you need a break from codebase migration. I'm happy to chat about or pair on it too.

V1: When you `edit` a definition that's part of a component of size >1, put the entire component into the scratch file.

V1.1: The above, plus a comment added to the scratch file as well, explaining that these definitions are mutually recursive and should be updated together

V2: The above, plus when you're `update`ing a definition, if you are replacing some but not all of its component, you get a warning w/ an arbitrarily nice explanation at the CLI, and maybe even an `undo` suggestion.  This situation could arise despite  V1, if the user deleted some of the definitions from the scratch file before `update`.

**Comment by mitchellwrosen** [comment]
Sounds good, I can take this one

**Comment by ceedubs** [comment]
Thank you so much @mitchellwrosen!

I've been the grumpy one asking for this one to be prioritized (sorry). I really like the v1/v1.1/v2 plan that @aryairani proposed. And I'd say that v1 and v1.1 would solve 99% of my problems with this, so personally I'm totally fine with punting on V2 for now if that saves a decent amount of effort.

**Comment by mitchellwrosen** [comment]
V1 was addressed now by #2563

V1.1 and V2 are not being worked on currently, but V1.1 in particular would not be difficult to add, we just weren't sure it was really worth the effort at this time since it would require:

- Some additional plumbing
- Coming up with a precise "look" for the types/terms brought into a file. Specifically, how to order them, and what comments we might want to put where, to explain what's going on.

If anyone has any concrete suggestions I'd be happy to pick this back up, but again, for now it just dumps entire components into your scratch buffer exactly as if you had explicitly asked to `edit` them, with no additional explanation.

**Comment by ceedubs** [comment]
@mitchellwrosen thank you so much! I just tried this out on the infamous cycle that has been causing Stew and me a lot of trouble, and it worked perfectly.

Regarding the additional plumbing: does that change at all if you slap the message into the ucm stdout as opposed to the scratch file? Though currently that might not be that helpful, because `edit` can spam the screen. @rlmark had brought up the possibility of not showing the entire implementation in the `edit` output, which I agree with. That's certainly outside of the scope of this issue, though.

Anyway a message describing what happened might go a long way to help a confused user, but for me personally I'm totally fine with messages being punted on for a while.

**Comment by ceedubs** [comment]
The main concern here has been addressed, so I'm going to close this out. I created #2583 as a follow-up item to add user-facing messages explaining what happened.
