### ISSUE TITLE
Unison-server should either not use special characters in IDs, or accept their un-escaped versions

### ISSUE THREAD

**Issue by anchpop** [unisonweb/unison#2426]
There's an annoying issue in my [devcontainer pr](https://github.com/unisonweb/vscode-devcontainer/pull/4/commits/24fb31997eca0472a09c8dca3d11d182c336130c#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R26) caused by what seems to be a [vscode bug](https://github.com/microsoft/vscode/issues/133551). It would be resolved if the IDs generated didn't include special characters that had to be escaped. (I wonder if they're encoded in base64, and you just need to use a url-safe encoding instead?)

**Comment by hojberg** [comment]
I've noticed this as well. It might be worth also making the token a lot smaller.
