### ISSUE TITLE
diff.namespace should accept namespace hashes

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#2429]
The `history` command lists hashes for namespaces. But if you try to supply those hashes as arguments to `diff.namespace` it says something like:

```
.testing> diff.namespace #0uks4r5ned #qk75glqep0
 
  I expected an identifier but found #0uks4r5ned
```

This limits the usefulness of the `history` output.

**Comment by ChrisPenner** [comment]
Ran into this today; I'll throw it on the TODO queue
