### ISSUE TITLE
Add default metadata according to term's namespace instead of UCM CWD

### ISSUE THREAD

**Issue by ChrisPenner** [unisonweb/unison#2451]
Currently the default metadata is chosen based on the namespace of your UCM session, not the location of the term being added. E.g. if I add the following:

```
.base.List.map = ...
```

And my ucm session is at `.>` It will use the metadata from `.>` instead of `.base.List` if default metadata is specified there.

**Comment by mitchellwrosen** [comment]
#wontfix
