### ISSUE TITLE
UCM `api` command

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#2452]
For folks needing to use the UCM web API, we should add a UCM command: `api` that gives details about the API. At minimum should report back the API url.

Example (from within `ucm`):

```ucm
.> api
The API is running on https://127.0.0.1:8080/asdf/api`
.>
```

**Comment by StevenXL** [comment]
I might be able to help with this. I'll try to get a PR in within the next week. Besides adding the `Api` data constructor to the `Command` data type, the only other bit is to consolidate how we fill in the missing values in `CodebaseServerOpts`. This is in `CodebaseServer.startServer`, so I'll probably extract that out into a function that can be called when we execute the `Api` command.

**Comment by solomon-b** [comment]
@StevenXL I hope you don't mind I wrote another PR based on the updated issue requirements.
