### ISSUE TITLE
When there’s a name resolution failure, tell me what it could be!

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2453]
This is a very high value fix that’s pretty simple to do. It is to give a nice error message if a type or term name is ambiguous.

```
    ❓
    
    I couldn't resolve any of these types:
    
        9 | Value.dependenciesOfType : Link.Type -> Value -> [V8alue]
    
    `Value` could refer to: 
       base.Value or 
       distributed.Value

    `V8alue` doesn’t match any type names.
```
With a similar message if there’s term resolution failures.

The fix will be in `PrintError.prettyResolutionFailures`. Pass the `PrettyPrintEnv` to that function and use that to print out the possibilities - inside the `ResolutionFailure` (defined in `ResolutionResult.hs`) has the `Set Reference` of possibilities. You can call `PrettyPrintEnv.typeName` to print each one. Similarly for term resolution failures.

Notice the different treatment above for the error message if the symbol can’t be resolved vs it being ambiguous.

**Comment by ChrisPenner** [comment]
I can take this one 👍🏼
