### ISSUE TITLE
Resolution doesn't continue with type-directed search if there's a local definition

### ISSUE THREAD

**Issue by ChrisPenner** [unisonweb/unison#2464]
```
(*) : Nat -> Duration -> Duration
times * d = match d with
  Nanosecond n -> Nanosecond (times * n)
```,

Errors with:

```
  The 2nd argument to `(*)`

            has type:  Nat
      but I expected:  Duration

      2 | (*) : Nat -> Duration -> Duration
      3 | times * d = match d with
      4 |   Nanosecond n -> Nanosecond (times * n)
```

When instead, I would expect it to look up the correct `Nat.*` automatically.

**Comment by pchiusano** [comment]
For better or worse, this is as designed. It is a design choice, but at the moment, scratch file names shadow codebase names much like if the codebase were an outer scope. You can always do `Nat.*` there or `use Nat *` in places where you want the codebase definition.

This transcript specifies name resolution behavior and walks through various corner cases -

https://github.com/unisonweb/unison/blob/trunk/unison-src/transcripts/fix1578.output.md 

The reason for not doing TDNR in cases like this is that TDNR is pretty unreliable (see https://github.com/unisonweb/unison/issues/448) and isn't the best user experience... you save a bit of typing, but then if your program has any type errors (and sometimes even if it doesn't), TDNR leads to cryptic and misleading type errors... I'd be very hesitant to invoke it more than we already do and I almost think we could just get rid of it entirely, especially if there's a nice message on ambiguity.

**Comment by ChrisPenner** [comment]
I think the best case would perhaps be to shadow, but to also print a warning that a combinator of the correct type exists in the codebase as well, and print that out so that the user isn't left scratching their head about why TDNR happened to fail in this isolated case. This is probably a bit tougher to implement though.

Thanks for the context!
