### ISSUE TITLE
ucm: more helpful completion when a namespace is provided

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#2490]
This is relevant to at least the `cd`, `ls` and `view` commands, but probably a number of other commands.

If I type `view .base.<TAB>`, ucm hangs for a second and then prompts `Display all 7430 possibilities? (y or n)`. What I would _like_ for it to do is only offer completion for the direct children of the `.base` namespace (of which `ls .base` currently shows there are only 141).

I think that there's a separate use-case where I want to type `view List.map` without providing a FQN, and it would be nice if ucm still attempted to find the thing that I'm asking for. I guess the difference is that in the first case I am either providing a FQN (via a leading `.`), or I'm giving a namespace relative to my current namespace.

**Comment by ceedubs** [comment]
It seems like `cd` might have behavior that is closer to what I'd expect than `ls` or `view`?

**Comment by ChrisPenner** [comment]
I can take this one 👍🏼

**Comment by ChrisPenner** [comment]
Pretty sure this should be fixed up (or at least a lot better) in trunk; feel free to clarify and re-open if not 😄

**Comment by ceedubs** [comment]
@ChrisPenner awesome, thanks! It does indeed seem to be a lot better in trunk.

It looks like if I use `view`, `docs`, or `display` and try to pass in a relative namespace the results are still the way that they were. But that's maybe a more difficult problem because you don't know whether I'm trying to provide the suffix of the term name or the start of a relative namespace. If only I could use `.` to refer to the current ~directory~ namespace then I would be able to signal to it that I'm trying to create a relative path 😃

**Comment by aryairani** [comment]
@ceedubs Do you want to open a new ticket for remaining elements? (Only if it feels urgent, I guess.)

**Comment by ceedubs** [comment]
@aryairani this has been less of an issue for me since the fzf support. I recall being frustrated by `ls` a bit but don't remember the details. I'll open issues issues if I get sufficiently annoyed :)
