### ISSUE TITLE
Feature: Bulk updating metadata

### ISSUE THREAD

**Issue by ChrisPenner** [unisonweb/unison#2491]
I recently wrote a small library before I had configured my default metadata, adding the metadata afterwards was a very tedious process of linking each individual piece of metadata to every term and type in the namespace 😬 

Long term I think I'd love to see some form of globbing, e.g. "link x .namespace.*"

At any rate there should be some less tedious way to do this 😄

**Comment by pchiusano** [comment]
There is actually a super-secret hidden way of doing this. The `link` command lets you supply multiple definitions. So you can do `find` and then `link .authors.chrispenner 1-30`.

It is mentioned if you do `help link` but I think only like 4 people know about it. :)

**Comment by ChrisPenner** [comment]
I added globbing, so I'm happy now 😄 
#2511
