### ISSUE TITLE
Parser bugs in ucm

### ISSUE THREAD

**Issue by stew** [unisonweb/unison#2503]
`view #a.` will cause ucm to abend with `unison: Prelude.read: no parse`

`view #a` seems to cause an infinite loop

**Comment by ChrisPenner** [comment]
Looks like `view #a` actually just runs a prefix search for EVERY definition in your codebase with a hash starting with `#a`; it completes successfully for me on a small codebase.

For the other issue I did a super quick patch in #2776 to improve the error for now.

**Comment by aryairani** [comment]
We can improve this by an order of magnitude or two by requiring 2-3+ characters to do a search by hash.

**Comment by aryairani** [comment]
But also... `view #a` _shouldn't_ be super slow, IMO, even if it does produce a lot of output.  I can believe that it is super slow despite should-not-being, though.

**Comment by stew** [comment]
so sorry! I had realized after chatting about this with Arya right after filing this that #a was just a slow super broad search that I had no patience for with my large codebase :) I had just not updated the bug.I'd much rather us do something like require at least 4 disambiguating characters to avoid this than to do a deep dive into performance on this which we can assume is just a mistake (as it was on my part, it was a typo)
