### ISSUE TITLE
Misleading results in search by type

### ISSUE THREAD

**Issue by ramon93i7** [unisonweb/unison#2508]
Tried to find `List.zip` by its signature but got no results:
<img width="652" alt="Screenshot 2021-10-16 at 23 42 38" src="https://user-images.githubusercontent.com/4787916/137601778-0fb3eb6e-528a-4b59-bd7f-36b7703bd715.png">

**Comment by aryairani** [comment]
It looks like this was fixed at some point:
```
@unison/base/main> find : [a] -> [b] -> [(a,b)]

  1. data.List.zip : [a] -> [b] -> [(a, b)]
  
```
