### ISSUE TITLE
Clear up `Star3` a bit

### ISSUE THREAD

**Issue by mitchellwrosen** [unisonweb/unison#2515]
Slack discussion: https://unisonlanguage.slack.com/archives/CLG4P0GSD/p1634648262222300

`Star3` has a misleading doc comment; I think it could use a small cleanup/documentation pass to address that, slap an explicit export list on it, that kind of thing.

I also think it could be moved to the `unison-util-relation` package, as it is very closely related to the relation data structure. It's basically just a tuple of relations with faster access to the domain.

**Comment by aryairani** [comment]
> There's a weird relationship between `Star3`, `Relation4` and `Branch`, that still exists and not clear whether it should be fixed. — @mitchellwrosen

**Comment by aryairani** [comment]
@mitchellwrosen is gonna look around his git worktrees to figure out what the status of this is.

**Comment by aryairani** [comment]
We think we will stop using this type before we deeply care about fixing it.
