### ISSUE TITLE
improve pager support

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#2518]
Currently there are several things that are not ideal about the way that `less` is used:

- If ucm is called within a script, the script can hang indefinitely since there isn't a user to hit `q`
  - This came up with the cron job to update Unison Share, since the `pull` command calls `less` to determine what has updated.
  - We should probably check on whether we are connected to a tty and not call `less` if we aren't. We are doing this if `INSIDE_EMACS` is defined, but that is a pretty ad-hoc solution.
- We should probably fall back to the `PAGER` environment variable (with no args) if `less` isn't available.
- Currently the dependency on `less` is within `parser-typechecker`. This seems like a good candidate to move out to `cli`.
  - `cli` also seems to depend on the `unix` module, which I think can answer whether we are connected to a tty

**Comment by iacore** [comment]
The current usage of pager is weird.
- Type `.> find .base.`  and press <kbd>Tab</kbd> uses `more` to show the results.
- `.> find .base` uses `less`.
- `fzf` support is gone

**Comment by ceedubs** [comment]
> Type .> find .base. and press Tab uses more to show the results.

@locriacyber hmm I'm not seeing anywhere that the code appears to be calling `more`, but I don't know the CLI codebase well. How can you tell that it's opening `more`? I don't think that it is for me.

> fzf support is gone

fzf support is in trunk but hasn't made it into a release yet. It should be in the next release which I think might be out next week.

**Comment by aryairani** [comment]
It doesn't call `more`, but maybe haskeline is doing something internally that looks like it.  Currently we call `less`, `git`, and in trunk `fzf` optionally.

Still, the current usage of pager _is_ weird.

**Comment by iacore** [comment]
There's `--- more ---` as the last line when there is more output. I think it's calling `more`.
![image](https://user-images.githubusercontent.com/74560659/141670071-ef124b53-8db2-4bb6-9d76-d25cec8c52da.png)

**Comment by aryairani** [comment]
Coincidentally, if you try calling `more` yourself from the command-line, e.g. `ls | more`, it _doesn't_ show `--- more ---` as the last line when there is more output. It just shows `:`.

**Comment by aryairani** [comment]
> * We should probably fall back to the `PAGER` environment variable (with no args) if `less` isn't available.

`PAGER` isn't normally set on Windows, so we'd need another backup option for non-unix. Windows ships with `more`, fwtw.

> * We should probably check on whether we are connected to a tty and not call `less` if we aren't. We are doing this if `INSIDE_EMACS` is defined, but that is a pretty ad-hoc solution.

Definitely this. Can we do this in a way that implicitly solves the emacs case too?

> * Currently the dependency on `less` is within `parser-typechecker`. This seems like a good candidate to move out to `cli`.

Agreed.

Re #2939, I'm inclined to just bundle `less`, although I don't love bundling a binary we didn't author. Not sure what the software package management story for Windows is today, but `brew` at least will let us list the requirement if we don't already.

**Comment by iacore** [comment]
How to check if stdout is terminal on POSIX systems:
https://rosettacode.org/wiki/Check_output_device_is_a_terminal#C

**Comment by ceedubs** [comment]
thanks @locriacyber. We'd probably be using a Haskell binding, so [here](https://rosettacode.org/wiki/Check_output_device_is_a_terminal#Haskell) is the relevant section. This uses the `unix` library, so I don't know whether that would work for Windows.

@aryairani regarding bundling `less`: do you just mean in the case of Windows? I don't think that we should be trying to bundle it for unix environments where that would be handled by `brew`, `nix`, etc. Also for cases like servers running standalone Unison binaries, I think that people should be able to run `ucm` without `less` installed.

Honestly I think that even if you just fell back to not paging if `less` isn't available, there would be few complaints about it and it would be a reasonable short to medium term solution.

**Comment by ChrisPenner** [comment]
#2953 should address most of the concerns listed here 😄 

* It checks whether `stdin` is a terminal and doesn't use a pager if so,
* It provides proper fallbacks when `less` is missing
* It allows a custom pager using `UNISON_PAGER`; see the issue for info on why I didn't use `PAGER`.

We should probably still move it into `unison-cli` at some point, but that doesn't affect functionality.
