### ISSUE TITLE
“missing integral case”

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2526]
````
.> pull https://github.com/unisonweb/distributed:#52rs9190dk .distributed


```
ex3 _ = Async.run 'let
  -- use Async await
  -- a = Async.detach '("hi")
  Async.fail parentCompleted
  -- b = Async.detach '(2 + 2)
  -- printLine ("Answer: " ++ Nat.toText (await a + await b))
  printLine "hi"
```

```ucm
.> run ex3
```

````

Yields “missing integral case”. The commented out lines give the same error.

**Comment by dolio** [comment]
That pull command doesn't seem to work. I think ucm doesn't like the `#`.

This is a weird one. That error comes from an inserted default case for matching on some integer type. But there's no matching on integers in the sample code. So I guess it's somewhere else?

**Comment by pchiusano** [comment]
@dolio try 

```
.> pull https://github.com/unisonweb/distributed:#52rs9190dk .distributed
```

(with no `.` after the `:` - I had that goofed up. Thanks to @aryairani for setting me straight.)

**Comment by dolio** [comment]
This was triggered by a faulty implementation of `tryPut`. Should have a patch soon (adding it on to the other `MVar` fix that hasn't been merged yet).
