### ISSUE TITLE
Auto-complete crashes second argument if both arguments are optional

### ISSUE THREAD

**Issue by ChrisPenner** [unisonweb/unison#2527]
The `pull` command has two optional arguments,

```
.> pull https://github.com/ChrisPenner/unison-codebase:.base .temp<TAB>
.> pull x yucm: Input pattern "pull" has an invalid argument list: [Optional,Optional]
CallStack (from HasCallStack):
  error, called at src/Unison/CommandLine/InputPattern.hs:64:10 in unison-parser-typechecker-0.0.0-8iNyHDVYveQ9Wi84mdnSZS:Unison.CommandLine.InputPattern
CallStack (from HasCallStack):
  error, called at src/Unison/CommandLine/Main.hs:175:28 in unison-parser-typechecker-0.0.0-8iNyHDVYveQ9Wi84mdnSZS:Unison.CommandLine.Main
```

Discovered this when unifying the argument ingestion for transcripts in #2511

**Comment by aryairani** [comment]
What or where was the fix?

**Comment by ChrisPenner** [comment]
@aryairani 
Right here:
https://github.com/unisonweb/unison/pull/2511/files#diff-1f3781f30176d0e0863fcb14e8ce541887d465da6f8504136eadfc8eb04d327aR66-R70

The previous iteration asserts that you can't have two `Optional` arguments and errors, but it's perfectly sensible to have two optional arguments as long as the assumption is that they're filled from left to right; which is how `pull`'s arguments currently work 😄

**Comment by aryairani** [comment]
Ah, good point. I don't think I thought of making that assumption.
