### ISSUE TITLE
fail to parse arrow preceded by line break, 'unexpected Semi'

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#254]
Tried to parse `a -> b -> c -> d` with line breaks before the arrows.  Hit parse error `unexpected Semi`.

Note from Paul:

> Note to self, or if you want to have a go at this, it should be a simple parser fix - in TypeParser, the -> token should I think be parsed as try (optional semi *> reserved "->") instead of just reserved "->". The semis are inserted by the lexer immediately before a non-blank line which has the same indentation as the previous non-blank line. There are a couple places in the grammar like this where we want to allow semis but just want to ignore them if they appear.

Note there's a pending testcase for this in parser-typechecker/tests/Unison/Test/TypePrinter.hs

I will fix this.

**Comment by pchiusano** [comment]
Is this still relevant...? This program parses okay:

``` haskell
foo : a
   -> b
   -> c
   -> a
foo a b c = a
```

**Comment by aryairani** [comment]
Not sure, but maybe he means something like this program?
```
> (x : a
-> b)
```
The above currently produces `unexpected ->`, which is maybe expected.  😜
Fwiw, the equivalent Haskell program does parse:
```
Prelude> :set +m
Prelude> (a :: b
Prelude| -> c)

<interactive>:4:2: error: Variable not in scope: a :: b1 -> c1
Prelude> 
```

**Comment by atacratic** [comment]
That's right - here's the example from the TypePrinter test:

```haskell
a
-> b
-> c
-> d
```
If it's as-intended that it doesn't parse, then we should change the pretty-printer, because this is what it produces at the moment, if it has to line break.

Umm, I will un-self-assign this, sorry :(

**Comment by mitchellwrosen** [comment]
This isn't a round-trip error anymore; please re-open if we misunderstood, though.
