### ISSUE TITLE
Codebase server `/getDefinition` renders `()` instead of `Optional`

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#2547]
When queried with a `relativeTo` of `unison.base` and a `names` of `Optional`, the codebase server finds the `()` (unit) definition and returns it instead of `Optional`.

It finds the right definition if queried without a `relativeTo` and a `names` of `unison.base.Optional`.

Report by @alvaroc1

**Comment by mitchellwrosen** [comment]
~~I suspect this has to do with https://github.com/unisonweb/unison/pull/2477~~

**Comment by mitchellwrosen** [comment]
I solved the mystery. Check out this term:

https://share.unison-lang.org/@bbipr4ode027l26cc9m5obsvo06dn5uaqogm5hc7bllgi5qjdrh9t024td24ihg1ioabpncv3i3nrpgqkcf103u0fnjbrnhpqk7c438/types/pdejoux/flight/Geodesy/Maybe

It's a lurking

```
type Maybe = Optional
```

from deep within share.

**Comment by aryairani** [comment]
Oh man.

**Comment by hojberg** [comment]
been debugging this with @pchiusano - I think we're going to not do external names for the codebase server when a relativeTo is set.

**Comment by hojberg** [comment]
This has been fixed.
