### ISSUE TITLE
Deduplicate type renderers - PrintError.renderType should be replaced with TypePrinter.pretty

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#255]
[PrintError.renderType](https://github.com/unisonweb/unison/blob/master/parser-typechecker/src/Unison/PrintError.hs#L463) is a pretty-printer for Types, but now we have another one in TypePrinter.hs, which also supports the delay sugar.  It also differs in some details (like is it `∀` or `forall`).  

We should replace `renderType`'s implementation with a call to TypePrinter.pretty, so that Types are rendered consistently between error messages and code, and to reduce future maintenance burden.

This will involve adding some extra support for annotations, I think to the PrettyPrint library, so that pretty-printed text can optionally carry things like color styling.  

I will do this at some point.  I will check the PrettyPrint API changes with people before going too far.

**Comment by aryairani** [comment]
👍 Just noticed this today too. 😄

**Comment by pchiusano** [comment]
As part of this, do we need to tweak the pretty-printer for types so it can do colors? I'm going to add a separate issue for that.

**Comment by runarorama** [comment]
Reverted the fix as it caused a regression. Will need to think about this more carefully, as the error printer wants to annotate the type based on location, and doesn't want syntax highlighting generally.
