### ISSUE TITLE
Some wild doc selection when passing `relativeTo` parameter

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2557]
I'm in perspective with `unison.base.Text`, and I'm viewing `Text.take` and `Text.drop`. It's showing me the docs for `MVar.take` (called `MVar.take.doc` presumably) and `Stream.drop` (called `Stream.drop.doc`). 

<img width="733" alt="Screen Shot 2021-10-27 at 11 06 48 PM" src="https://user-images.githubusercontent.com/11074/139185677-f11a74e9-d513-4b62-a470-f5f7b130e351.png">

What I think is happening is:

* The `Names` being used is one that includes all names, not just those in the current namespace.
* When looking at `take`, it's doing a suffixed lookup of `take.doc` to locate the docs, and it's finding `MVar.take.doc` outside the current namespace given by the `relativeTo`.

I think the fix is perhaps as simple as not doing a suffixed lookup when resolving docs - it's gotta be an exact match for the correct FQN.

If that doesn't work:

* Just use the local names at the specified `relativeTo` path for purposes of finding docs for a definition.
* The overall names should still be used for pretty-printing, since definitions may reference stuff outside the current namespace and we want those to get names, not hashes, in their rendering.

**Comment by pchiusano** [comment]
Okay, I think the trouble is this line in `Backend.hs`:

```Haskell
      docResults :: [Reference] -> [Name] -> Backend IO [(HashQualifiedName, UnisonHash, Doc.Doc)]
      docResults rs0 docs = do
        let refsFor n = NamesWithHistory.lookupHQTerm (HQ.NameOnly n) parseNames
```

The `lookupHQTerm` there does suffix-based resolution. I'm thinking we either need to write `NamesWithHistory.lookupExactHQTerm` and call that instead. Or use something other than `parseNames` - we basically just want the names from the current namespace.

**Comment by hojberg** [comment]
Dupe of https://github.com/unisonweb/unison/issues/2360, but i'll close that one since you got a lot more info here.

**Comment by hojberg** [comment]
@pchiusano yeah this is kind of similar to that Optional problem, in that the codebase server should consider "relative to" more confining.
