### ISSUE TITLE
add a `delete.force` command

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#2572]
Like `delete` from #2571, but instead of aborting when it would be deleting the last name for some dependents' dependencies, print them in a report showing the **name of the thing** being deleted and **the remaining definitions** that now have the thing as an unnamed dependency, and then delete them with a hint to undo.

Also create `delete.term.force`, `delete.type.force`, `delete.namespace.force` which produce the same report.

**Comment by pchiusano** [comment]
I am currently being badly bitten by this... and I literally don't know how to work around it.

**Comment by ChrisPenner** [comment]
Are we intentionally avoiding having flags/options for our ucm commands? It's fine if we some reason to, but I'm a bit worried about the combinatorial explosion.

E.g., if we add the "generic" versions of `move` and `delete` now we have:

```
move
move.term
move.type
move.namespace
move.force
move.term.force
move.type.force
move.namespace.force
delete
delete.term
delete.type
delete.namespace
delete.force
delete.term.force
delete.type.force
delete.namespace.force
```

Rather than just `move` and `delete` with a few options 🤔

**Comment by ceedubs** [comment]
> I am currently being badly bitten by this... and I literally don't know how to work around it.

@pchiusano until #2611 is merged you can `move.namespace .unwanted .unwanted.void` or `move.namespace .unwanted .unwanted.devNull` 🙂

**Comment by pchiusano** [comment]
> Are we intentionally avoiding having flags/options for our ucm commands? It's fine if we some reason to, but I'm a bit worried about the combinatorial explosion.

I like how it looks and find it simpler to use and type, and it autocompletes nicely. It also encourages us to keep the command set simple, which I think we should be disciplined about. Think of the commands more like functions in Haskell - do you have a single Haskell function that does 12 things by passing it various flags? No, you have different functions, with a common naming scheme.

At the end of the day, the information has to be specified somehow. Is `delete --force blah` better than `delete.force blah`?

Also we don't need `move.force` - a move always succeeds. I think the commands people will actually use are just `delete`, `delete.force`, and `move`. Anything else is an obscure case.
