### ISSUE TITLE
`edit`: only show type signatures and not implementations

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#2582]
@rlmark has pointed out that the `ucm` `edit` can spam a lot of output lines that aren't particularly useful. I agree. Usually when I use `edit`, I immediately hit `q` to close out of `less` and switch to my scratch file where I can see the same output.

Proposal: `edit` should show the names/type signatures that it added to the scratch file but not the entire definitions.

**Comment by aryairani** [comment]
Currently it just displays a count.  Feel free to open a new ticket if you decide you still want the names/type signatures to be  shown.
```
@unison/base/main> edit Bytes.fromList

  ☝️
  
  I added 1 definitions to the top of scratch.u
  
  You can edit them there, then run `update` to replace the definitions currently in this
  namespace.

InputPattern: 93.8 ms (cpu), 131 ms (system)
@unison/base/main> 
UnisonFileChanged: 46.0 µs (cpu), 219 µs (system)
@unison/base/main>    
```
