### ISSUE TITLE
unintended transitive updates in ucm

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#2587]
If we create an update `#hash1 -> #hash2` and then _afterwards_ create an update `#hash3 -> #hash1`, then the patch file will transitively update `#hash3 -> #hash2`, even though we only ever wanted `#hash3` to update to `#hash1`.

This is kind of hard to articulate. An example might be most useful. Below is the output of the transcript. The raw transcript can be found [here](https://gist.github.com/ceedubs/57403ccff78f89a8ac4ccc9702ab239b)

We create `one` (oops with the wrong value).

```unison
one = "two"
```

```ucm
.>add

  ⍟ I've added these definitions:
  
    one : ##Text

```
We realize our mistake, so we fix the definition of `one`.

```unison
one = "one"
```

```ucm
.>update

  ⍟ I've updated these names to your new definition:
  
    one : ##Text

```
We create `two` (oops with the wrong value).

```unison
two = "three"
```

```ucm
.>update

  ⍟ I've added these definitions:
  
    two : ##Text

```
```ucm
.>view one two

  one : ##Text
  one = "one"
  
  two : ##Text
  two = "three"

```
We realize our mistake, so we fix the definition of `two`.

```unison
two = "two"
```

After an update, `one` and `two` are both equal to the string literal `"one"`.

```ucm
.>update

  ⍟ I've updated these names to your new definition:
  
    two : ##Text

.>view one

  one : ##Text
  one = "one"

.>view two

  one : ##Text
  one = "one"

```
If we look at the `patch` we see the `"two" -> "one"` update followed by the `"three" -> "two"` update.

```ucm
.>view.patch patch

  Edited Terms:
    two#r7kgo9gabm -> one
    #tbla48tav7    -> two#r7kgo9gabm
  
  Tip: To remove entries from a patch, use
       delete.term-replacement or delete.type-replacement, as
       appropriate.

```
But based on the terms `one` and `two` are both ending up as `"one"`, then the `two` term must be getting the `"three" -> "two"` update followed by the `"two" -> "one" update, even though though the latter happened later in time.

**Comment by aryairani** [comment]
How would it be if `x -> y` deleted all the rules `? -> x`?

There's a function `updatePatch :: Patch -> Patch` in `HandleInput.hs` which dictates how a patch is updated when you run the `update` command.  We should confirm what it does now, and look at what we could do differently.

Another option would be to issue a warning and make the user decide what to do, but if there was just a right thing to do, just doing that would be better.

**Comment by ceedubs** [comment]
> How would it be if x -> y deleted all the rules ? -> x?

@aryairani I don't think that's always what you want. For example consider this scenario:

1. We find a bug in `.base.trunk.List.map#1`, so we change fix it and create `.base.trunk.List.map#2`.
2. We find a bug in `.base.trunk.List.map#2` (this will be `x`), so we change fix it and create `.base.trunk.List.map#3` (this will be `y`).
3. A library that was using `.base.trunk.List.map#1` pulls the latest `.base.trunk`. The patch no longer includes the `map#1 (?) -> map#2 (x)` rule, so they don't pick up any of the changes to `List.map`.

Or am I misunderstanding?

**Comment by ceedubs** [comment]
I was just bitten by this again :(

**Comment by aryairani** [comment]
moot for now as patches have gone away, but we should revisit if we implement anything similar again

**Comment by aryairani** [comment]
Here is the current output, btw:

---
We create `one` (oops with the wrong value).

```unison
one = "two"
```

```ucm
.> add

  ⍟ I've added these definitions:
  
    one : ##Text

```
We realize our mistake, so we fix the definition of `one`.

```unison
one = "one"
```

```ucm
.> update

  Okay, I'm searching the branch for code that needs to be
  updated...

  Done.

```
We create `two` (oops with the wrong value).

```unison
two = "three"
```

```ucm
.> update

  Okay, I'm searching the branch for code that needs to be
  updated...

  Done.

```
```ucm
.> view one two

  one : ##Text
  one = "one"
  
  two : ##Text
  two = "three"

```
We realize our mistake, so we fix the definition of `two`.

```unison
two = "two"
```

After an update, `one` and `two` are both equal to the string literal `"one"`.

```ucm
.> update

  Okay, I'm searching the branch for code that needs to be
  updated...

  Done.

.> view one

  one : ##Text
  one = "one"

.> view two

  two : ##Text
  two = "two"

```
