### ISSUE TITLE
create `gist` command

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#2603]
Implement a command to create a "gist" of the current (or specified) namespace.

The command syncs the designated namespace to a specified Unison `WriteRepo` (defaults to the default repo for the root of the local codebase, if specified in `.unisonConfig`), with no name in the remote repo; just sync the namespace over.

e.g.
```
.prs.basedev.trunk.pr42> gist git@github.com:bob/unison

  Gist created. Pull via:

    pull git@github.com:bob/unison:#2390843af228
```

```
.prs.basedev.trunk.pr42> gist

  Gist created. Pull via:

    pull git@github.com:bob/unison:#2390843af228
```

Note that this creates some "garbage" in the remote repo (in the sense of data not necessarily reachable from the root), and that might be something we care about in the future but not while this command is only part of a prototype workflow.

**Comment by hojberg** [comment]
It'd be really cool if we could tie this in with Unison Share in some way

**Comment by aryairani** [comment]
@hojberg My thinking was that once we are hosting all of the repos and gists instead of github hosting them, then yeah it will be easy to open them up in Unison Share like any other namespace, given a namespace hash.

If you have any ideas about how to achieve it before that, let me know!

**Comment by ChrisPenner** [comment]
Can you explain the use-case for this? How does this improve on just adding a sub-namespace for whatever you want to share? Is it just that downloading it will be faster?

I'll admit I'm not sold on this feature yet, if there are other reasons I'd love to hear them, but if it's just for performance it really sounds like we should work on fixing our  ability to load sub-branches rather than introducing either "sub-codebases" or orphaned roots just to solve this problem 🤔

**Comment by aryairani** [comment]
@ChrisPenner It's just to be able to quickly share a unison namespace without having to think about where you want to archive it; it's not for performance. It's part of https://github.com/unisonweb/unison/pull/2247#issuecomment-900409775.

**Comment by hojberg** [comment]
@aryairani @ChrisPenner @mitchellwrosen I'd love to connect about this to help me get an understanding of the UX and the implications this might have on Share, both now and in the future — it's definitely a feature we'd want Share to support, and I wonder if there's some quick wins there.

**Comment by hojberg** [comment]
Oh I think I understand slightly more about what this is. I was confused by the "gist" terminology here and thought it to literally be that. 🤔

**Comment by aryairani** [comment]
@hojberg Yeah it would definitely be the sort of thing where if you had a Share hooked up for that particular codebase, you could generate a share link to the namespace by hash.
