### ISSUE TITLE
Proposal: some additional type safety / information around references/referents

### ISSUE THREAD

**Issue by mitchellwrosen** [unisonweb/unison#2620]
@ChrisPenner @aryairani and I concluded something like this would probably be worthwhile to introduce, for a little bit of type safety and grokkability:

```haskell
-- Could be made newtypes, if that would be useful
type TermReference = Reference
type TypeReference = Reference

data ConstructorReference = ConstructorReference TypeReference ConstructorId
```

**Comment by aryairani** [comment]
@mitchellwrosen currently has a patch against trunk, but need a separate PR against `topic/rehash-codebase` that we would try to merge simultaneously.
