### ISSUE TITLE
runtime benchmark in parser-typechecker package currently doesn't build

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#2631]
@dolio Could you take a look and see if we want to keep this and, if so, to see what it would take to get it building again?  Then we can add it to CI to keep it happy.

@mitchellwrosen Do you have thoughts about where building benchmarks should go in the CI script slash could you add it once it's building :)

The output of `stack build --fast --bench` is [here](https://gist.github.com/aryairani/80f6205ecf28ce7479c29be0e6df708a).

**Comment by dolio** [comment]
I think maybe we should just get rid of it. I'm not sure it's really that useful. I could probably fix it, but it was written before the more complicated runtime environment, and I'm not sure the few micro benchmarks in there are worth it.

**Comment by aryairani** [comment]
Totally your call IMO.

**Comment by aryairani** [comment]
It builds now
