### ISSUE TITLE
Better readline support

### ISSUE THREAD

**Issue by iacore** [unisonweb/unison#2632]
The current `ucm` doesn't handle many key combinations including:
- Delete
- Ctrl + Arrow Right
- Ctrl + Backspace

I hope the CLI interface uses a readline library like GNU readline so using ucm CLI is more pleasant.

**Comment by ChrisPenner** [comment]
Hello 👋🏼 

`ucm` currently uses `haskeline` as our readline library, and it allows the user to specify their own keybinds if they like.

It's definitely weird that `delete` doesn't work by default, I'm not sure why haskeline made that choice. We should consider adding common bindings like that into ucm by default, but in the mean-time feel free to add them to your own config 😄 .

Check out [this section](https://github.com/judah/haskeline/wiki/CustomKeyBindings#control-leftright) to see how you can set it up.

**Comment by aryairani** [comment]
I'm going to close this for now, but feel free to reopen if the haskeline config didn't do the trick for you.
