### ISSUE TITLE
keyword fragments appearing in doc links are treated as their Unison entities 

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#2642]
If you're writing a `Doc` link, as in `{{I am a doc which links to a term called {abilityPatterns} in the codebase}}` the UCM will error with 

```
I couldn't find a type for Patterns.
  
      9 | {abilityPatterns}
```

Indicating that it's looking for an ability named Patterns. 

Likewise with terms that are prefixed with `type` as in `{{ I am a doc which links to a term called [Type signatures](typeSignatures)}}`

The UCM will fail to typecheck with a message about how a type named Signatures could not be found in the codebase. 

As long as your keyword-fragment is not at the top level of the codebase, you can work around this by qualifying the term, as in `languageReference.abilityPatterns`, but this may not be ideal in the long run.

**Comment by aryairani** [comment]
Interesting!

**Comment by rlmark** [comment]
Possibly related: https://github.com/unisonweb/unison/issues/2829 linking to UCM commands in Docs may also be causing tdnr issues.

**Comment by kanwren** [comment]
This is an issue in the lexer. I can take this if you want, since it's on the codepath I'm already debugging, and should be a super quick fix.

**Comment by rlmark** [comment]
@nprindle that would be amazing! 🤩 Go for it! It's all you!
