### ISSUE TITLE
create "how to pr in unison"

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#2651]
Write up a tutorial on how to use UCM to create and review pull requests like unisonweb/base#53 today.

I stubbed out a page at https://github.com/unisonweb/unison/wiki/How-to-Review-a-PR-in-Unison, and we can move it to the doc site if and when we want to.

**Comment by hojberg** [comment]
There's also this on the website right now https://www.unisonweb.org/docs/codebase-organization#day-to-day-development-creating-and-merging-pull-requests

**Comment by ChrisPenner** [comment]
Looks like the link Simon posted is a good start on this, we'll want to revisit this after we have some better PR tools, but we'll close for the meantime.
