### ISSUE TITLE
Add pattern matching on vectors / sequence

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#266]
Looks like we might be missing a way to pattern match on vectors?

The pattern parser is missing handling for them.  When given 
```haskell
case x of [a, b] -> a
```
it throws 
```
unexpected [
expecting (, blank, false, symbol, or true
```
... and there's nothing in the pattern AST for it to parse to anyway (unless maybe a special constructor, like with Pair and ().)

(Related: in the term language, does Vector really pay its way as a member of the AST definition?  How about if [a,b,c] was sugar that mapped to `App (Constructor Vector 0) (the tuple (a, b, c))`?  Would that prevent Vector being its own thing at runtime?)

**Comment by runarorama** [comment]
That's definitely missing. Want to take a stab at adding?

**Comment by noahhaasis** [comment]
Do you think this is a good issue for someone new to the codebase?

**Comment by pchiusano** [comment]
I am calling this blocked, until we decide what we're doing with the runtime. I don't want to add this and then have to redo the runtime part of it if we migrate away from the Scala runtime.

**Comment by aryairani** [comment]
As we've disavowed the scala runtime, this is no longer blocked.

We had talked about supporting some of the following kinds of vector matches:
```haskell
case v of
  [] -> -- nil
  [1, 2, 3, 4] -> -- fixed length vector
  head +: tail -> -- un-cons
  init :+ last -> -- un-snoc
  [1, 2] ++ suffix -> -- maybe?
  prefix ++ [3,4] -> -- maybe?
```

**Comment by aryairani** [comment]
Steps:
* [ ] Add to the Pattern AST (PatternP, Pattern)
* [ ] Add to the term parser
* [ ] Add to the typechecker
* [ ] Add to the runtime
* [ ] Add to the term pretty-printer
* [ ] Profit!
