### ISSUE TITLE
Error encountered when opening a codebase is ignored

### ISSUE THREAD

**Issue by mitchellwrosen** [unisonweb/unison#2669]
https://github.com/unisonweb/unison/blob/a6c4533e96ca18286e2cb780f49ab4feff37c7b4/parser-typechecker/src/Unison/Codebase/Init.hs#L89

This line ignores the error that comes out of `openCodebase`, and just goes on to print "no codebase found at specific dir". I think the error message should depend on exactly what failed.

**Comment by aryairani** [comment]
Seems to be fixed now?
https://github.com/unisonweb/unison/blob/release/0.5.23/parser-typechecker/src/Unison/Codebase/Init.hs#L135
