### ISSUE TITLE
a PR where we move `ORMOLU_DISABLE` to below the module imports

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#2685]
Follow-on to #2666.

HLS puts imports in the wrong spot, and rather than continuing to try to thread them in manually without disturbing the surrounding imports, or not (and increasing the entropy), let's do this.

**Comment by ChrisPenner** [comment]
I can probably script something to make this patch, but of course in the mean-time feel free to just move it down as it causes issues.

This'll also be nice for avoiding conflicts on imports I think, since HLS always adds them at the end which causes contention, whereas ormolu sorts them.

**Comment by aryairani** [comment]
![image](https://user-images.githubusercontent.com/538571/149991156-3b1234d8-08e8-4ef3-bb2f-ba99e876a2d0.png)
Apparently the comment also needs to be moved to a separate line.

**Comment by aryairani** [comment]
Let's wait until after #2471

**Comment by ChrisPenner** [comment]
Closed in #2956
