### ISSUE TITLE
Segfault in ucm for watch expression with larger lists

### ISSUE THREAD

**Issue by hagl** [unisonweb/unison#2693]
The following code causes a segfault in ucm on MacOS
```
list = List.range 0 2000
> List.map id list
```
Here is the output of ucm:
```
.>

  I found and typechecked these definitions in ~/projects/unison/bug.u. If you
  do an `add` or `update`, here's how your codebase would change:

    ⍟ These new definitions are ok to `add`:

      list : [Nat]

  Now evaluating any watch expressions (lines starting with `>`)...
  Ctrl+C cancels.

Segmentation fault: 11
```

If I add the `list` to the workspace first and then use the watch expression it works fine. Also if I inline the list term or use a smaller-sized list.

**Comment by aryairani** [comment]
@dolio Any ideas on this? (Can you even repro on linux? I haven’t tried on mac yet.)

**Comment by dolio** [comment]
It doesn't seem to be happening here, no. Strange.

Actually, scratch that. It just doesn't happen every time, I think.

**Comment by dolio** [comment]
Okay, I think I figured out what's happening.

It actually works the first time you run it. But then unison caches a gigantic list literal and tries to use that instead the next time it happens in a watch. That's the thing that causes a problem.

**Comment by dolio** [comment]
Should be fixed now.
