### ISSUE TITLE
List.foldLeft helper function type error

### ISSUE THREAD

**Issue by jakerosen** [unisonweb/unison#2702]
I was writing a function using List.foldLeft with a helper function to fold the list, but I got a confusing type error and I'm not sure if it's a bug or not.
```
foo : [Nat] -> Nat
foo l =
  bar : Nat -> Nat -> Nat
  bar = todo ""

  List.foldLeft bar 0 l
```
```
The expression in red
  
                needs the abilities: {𝕖9}
    but was assumed to only require: {𝕖22, 𝕖8}
  
  This is likely a result of using an un-annotated function as an argument with concrete abilities. 
  Try adding an annotation to the function definition whose body is red.
  
      6 |   List.foldLeft bar 0 l
```

If we change the signature of bar to `Nat -> {e} Nat -> {e} Nat` or `Nat -> {} Nat -> {} Nat`, then it works fine.

**Comment by hojberg** [comment]
I've been seeing this error as well with `List.foldLeft`, and have been confused by it. I think its meant to just be inferred automatically 🤔

**Comment by aryairani** [comment]
I'm not sure exactly when this was fixed, but it seems to have been fixed.

The example provided typechecks fine in v0.5.23.

```
    ⍟ These new definitions are ok to `add`:
    
      foo : [Nat] -> Nat
```
