### ISSUE TITLE
Bytes.fromList crashes ucm

### ISSUE THREAD

**Issue by stew** [unisonweb/unison#2715]
this expression in a scratch file causes ucm to crash with an exception:

   > Bytes.fromList [256]

Causes this crash:

    ~/scratch.u changed.
    
    Now evaluating any watch expressions (lines starting with `>`)... Ctrl+C cancels.
    
    Exception: Enum.toEnum{Word8}: tag (256) is outside of bounds (0,255)
    unison: Enum.toEnum{Word8}: tag (256) is outside of bounds (0,255)

**Comment by aryairani** [comment]
It looks like it's now `Bytes.fromList.impl` and throws an unchecked exception if an input is out of range.
The wrapper function `Bytes.fromList` validates all the inputs and throws a checked exception if any is out of range.

In either case, it no longer crashes ucm:
```
Encountered exception:
Enum.toEnum{Word8}: tag (256) is outside of bounds (0,255)
@unison/base/main> 
```
