### ISSUE TITLE
consolidating tests?

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#2736]
Currently we run six different commands to see if tests pass.  

```
stack test unison-cli
stack exec tests
stack test unison-util-relation
stack exec transcripts
stack exec unison transcript unison-src/transcripts-round-trip/main.md
stack exec integration-tests
```

Would it be practical to have a single executable that summarizes the passing and failing tests from all six?

Note that some tests have overlapping functionality — i.e. a change that breaks of fixes one test may break or fix another in another suite as well, but either later suites are short-circuited, or failures in earlier suites are buried under a mountain of output.

**Comment by mitchellwrosen** [comment]
I think this PR is the right way to go, at which point all tests could be run with `stack test`

https://github.com/unisonweb/unison/pull/2656

**Comment by aryairani** [comment]
Ah. Would that PR + running `stack test` take care of the business of earlier test failures getting lost in a stream of output too?

**Comment by aryairani** [comment]
Between #2656 and just keeping `scripts/check.sh` up to date, I'm going to go ahead and close this ticket.
