### ISSUE TITLE
Line wrapping after every word

### ISSUE THREAD

**Issue by slightknack** [unisonweb/unison#2737]
When running unison, lines wrap after every word (sometimes):

<img width="823" alt="Screen Shot 2021-12-07 at 7 02 14 AM" src="https://user-images.githubusercontent.com/54823450/144975131-4a1755c3-988b-4f01-8a98-cfc4dea8101e.png">

If I type something like `help`, I get the same thing:

<img width="661" alt="Screen Shot 2021-12-07 at 7 03 25 AM" src="https://user-images.githubusercontent.com/54823450/144975296-3221ee46-32cf-4734-8ba0-36f9d079e4cc.png">

It looks like, for whatever reason, the line wrapper thinks I have a terminal width of zero (or something).

Any help to fix this issue is appreciated, let me know what additional information is required to resolve this issue.

## Build Steps

I just grabbed unison's source:

```
git clone <unison url> --recursive --depth=1
cd unison
```

and built it with:

```
stack build --compiler ghc-8.10.7 --system-ghc
```

Then ran unison with:

```
stack exec unison --compiler ghc-8.10.7 --system-ghc
```

(The flags are there to tell `stack` where to look for `ghc`, I don't think they have anything to do with the issue.)

Oh, and if you're curious:

```
$ stack exec tests --compiler ghc-8.10.7 --system-ghc
...
✅  857 tests passed, no failures! 👍 🎉
```

Looks like all tests pass, which implies this is most likely something wrong on my end (or something on my end that `ucm` isn't picking up).

## System

Hardware: MacBook Air (M1, 2020)
OS: macOS Monterey 12.0.1
Terminal: iTerm Build 3.4.14
GHC: 8.10.7
Stack: Version 2.7.3 aarch64
Unison: Commit `138799f92` (latest as of posting)

**Comment by ceedubs** [comment]
@slightknack thank you for reporting this! @runarorama is running into the same issue. It seems to be specific to aarch/arm64 builds.

**Comment by hagl** [comment]
This sounds related to these issues:

https://github.com/biegunka/terminal-size/pull/17
https://github.com/judah/haskeline/pull/163

So an upgrade of haskeline might help. Unfortunately I don't have the hardware to test
