### ISSUE TITLE
Make sure schema hasn't been silently upgraded while another codebase client is running

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#2742]
Is it as "simple" as checking "schema version" when we check "data version" (which we already need to do more consistently).

---

Chris's edits:

Ideas for addressing this issue:

* Store the codebase for the v2 schema at a different filepath entirely; e.g. `.unison/v3/unison.sqlite3` or `.unison/v2/unison.v2.sqlite3`
  * This allows us to easily provide both schema v1 and v2 versions of libs like base and share so that users can choose to upgrade ucm at their leisure.
  * This allows us to leave the v1 database untouched for existing ucm processes to use, the migration will occur only within the schema v2 codebase.
  * This allows alpha testers (and us as developers) to use v1 and v2 ucm's interchangeably without interfering with each other during development.
  * This would obviate the need to make a back-up before migrating.
 
We can achieve this goal in a few different ways, one way is to load the existing codebase, then `VACUUM INTO .unison/unison.v2.sqlite3`, then close the existing codebase, open the new one and perform the migration in-place over there.

**Comment by ChrisPenner** [comment]
~Perhaps we should do the whole migration in an `EXCLUSIVE` transaction just to be 100% sure.~

Apparently this still doesn't evict open READ connections when in WAL mode 🤔 ,
one solution would be to use `VACUUM INTO` as our final step, then delete the old codebase and move over the new one.

We just really don't want a ucm to write old-hash data into a freshly migrated DB.

**Comment by ChrisPenner** [comment]
We ended up just printing a prompt before starting the migration.
