### ISSUE TITLE
Question: AST Normalisation/deduplication

### ISSUE THREAD

**Issue by tristangodfrey** [unisonweb/unison#2758]
Hi guys, apologies if this question has been answered before (or if it is mentioned somewhere in the docs), but I was unable to find anything related to this.

My question is as follows:

If two AST instances are semantically synonymous, but syntactically different (e.g. a different ordering of arguments to a commutative operator), will the content hashes of these AST instances differ, or be equal to one another?

This is important to me because synonymous functions can lead to language ambiguity in the programs that depend on these functions.

Thanks in advance!

P.S.: Awesome project! I've been looking for something like this ever since I saw the strangeloop talk by Joe Armstrong (https://www.youtube.com/watch?v=lKXe3HUG2l4&ab_channel=StrangeLoopConference)

**Comment by ceedubs** [comment]
Hi @tristangodfrey. There are people who know more on this subject (particularly what might happen in the future), but I think that I know enough to speak about current behavior.

Currently there is a small amount of normalization that happens. Term hashes won't be affected by their names or the names of parameters/variables. However the normalization is not sophisticated enough to recognize commutative operations, etc. Even wrapping a block in a call to the identity function is enough to change the hash.

 That's not to say that stronger normalization couldn't be applied in the future. However there is a tradeoff as that would mean that a function's hash could change depending on which version of Unison compiled it (though this should be pretty harmless in practice).

**Comment by ceedubs** [comment]
I am going to leave this issue open for now because questions about normalization come up every once in a while and we should probably add this to the FAQ.

**Comment by runarorama** [comment]
At the moment two ASTs should have the same hash if they are _Alpha-equivalent_. I don't think Unison will ever attempt to get the same hash for Beta-equivalent terms, as there is no fast way to do this, but we might do some amount of normalisation of the AST in the future. This is currently not on the roadmap.

**Comment by tristangodfrey** [comment]
Thanks for the clarification! I think a high degree of normalisation could lead to some very interesting properties such as the ability to construct a normalised cache for common operations, where you hash the entire function call & map it to the computed return value. Cache lifetime won't be an issue of course if you're working with pure functions. Though I'm not sure how useful this would be

**Comment by ceedubs** [comment]
I'm going to close this out, as I think that the question has been answered.
