### ISSUE TITLE
codebase UI shows wrong docs for a hash qualified name in a relative view

### ISSUE THREAD

**Issue by iamevn** [unisonweb/unison#2759]
Here is a term on unison share in the namespace containing that term [queried by name](https://share.unison-lang.org/latest/namespaces/iamevn/advent/year2021/day03/;/terms/main) and [queried by hash](https://share.unison-lang.org/latest/namespaces/iamevn/advent/year2021/day03/;/terms/@69dn0qqsinretcrhuvjhhfr3ue18qcvij5cv3lno22oja294et6532chuoeoknufid3ftl1kf08o168h6r8vmjasd35uubqunp6k8u0). The hash query shows docs from another term with a similar name. this term should have no docs.

They both query `/api/getDefinition` with the same parameters for `rootBranch` and `relativeTo` but differ for `names` (hashes shortened):
```
names=main
rootBranch=#rubverph...
relativeTo=iamevn.advent.year2021.day03

names=%2369dn0q...
rootBranch=#rubverph...
relativeTo=iamevn.advent.year2021.day03
```
The response for the hash query includes entries in `termDocs` where there should be none:
![image](https://user-images.githubusercontent.com/5936748/145770856-b6e35b5b-4138-46ba-9265-fe500ff80dc1.png)

Going from the root namespace instead seems to work correctly: [query by name](https://share.unison-lang.org/latest/terms/iamevn.advent.year2021.day03.main) / [query by hash](https://share.unison-lang.org/latest/terms/@69dn0qqsinretcrhuvjhhfr3ue18qcvij5cv3lno22oja294et6532chuoeoknufid3ftl1kf08o168h6r8vmjasd35uubqunp6k8u0)

**Comment by hojberg** [comment]
Hmmm, thought this one had been fixed (https://github.com/unisonweb/unison/issues/2557). Should verify if this problem is just the server or if ucm is impacted as well.

**Comment by hojberg** [comment]
@ceedubs reports this also happening on the new Share.

**Comment by hojberg** [comment]
@aryairani I might need some backend assistance on this.

**Comment by hojberg** [comment]
Here's an example 

<img width="772" alt="CleanShot 2022-08-10 at 08 45 50@2x" src="https://user-images.githubusercontent.com/2371/183904698-c1cc0a95-546b-4402-bce3-2774e84eb548.png">


https://share.unison-lang.org/@hojberg/code/latest/namespaces/public/projects/html/latest/;/terms/div
