### ISSUE TITLE
Docs pattern match issue in fenced codeblocks

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#2778]
It appears that expressions which use pattern matching in fenced codeblock elements in the Docs have their case statements reordered upon evaluation. For example the following should be `true`: 

````
myDoc = {{

  I am a doc

  ```
  match 1 with
    1 -> true
    _   -> false
  ```
}}
````

But this `display`s as 

```
.> display myDoc

  I am a doc
  
      _pattern = 1
      false
      ⧨
      false
```

A transcript with doc file to load is attached to replicate. A workaround I'm using where evaluation is not key for docs writing is to simply load the source into the Doc with `@source`. 

[docLoad.txt](https://github.com/unisonweb/unison/files/7803587/docLoad.txt)
[reorderingMatch.md](https://github.com/unisonweb/unison/files/7803588/reorderingMatch.md)

**Comment by dolio** [comment]
I think this looks like a pattern compiler issue or something. It's throwing away the `1` case completely, and clearly evaluating it wrong.

Edit: oh wait, I understand now. Is the problem that there's some kind of double evaluation going on? The first one evaluates the doc and emits a backwards matching block:

```
match 1 with
  _ -> false
  1 -> true
```

Then that gets evaluated wrong?
