### ISSUE TITLE
Awkwardness tagging/untagging terms as tests

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#2780]
It's really simple to add a test with `test> mytest = check (1 === 2)`. However, if you've previously added `mytest` to the codebase without marking it as a test, there isn't an obvious way to retroactively make it a test.

If you `edit` `mytest` and add a `test>` prefix, `ucm` states that `mytest` has already been added to the codebase but doesn't actually run `mytest` when you run the `test` command.

A workaround is to run `link .base.metadata.isTest mytest`. This isn't so bad, but is neither obvious nor documented.

One other slightly awkward piece is that `edit mytest` doesn't pretty-print the `test>` prefix.

@aryairani has raised the question of whether editing `mytest` and stripping the `test>` prefix should unlink the `isTest` metadata. This seems like it would be surprising behavior, which is perhaps an argument about doing anything too clever in this space.

**Comment by aryairani** [comment]
Currently (v0.5.23):

Any value of type `[test.Result]`
* is considered a test
* is rendered with `test>`
* is run/displayed when running the `test` command in ucm.

The presence of `test> ` in the scratch file has two effects:
1. the test is evaluated (or loaded from cache) on save, and rendered in a nice-ish way in ucm:
    <img width="290" alt="image" src="https://github.com/unisonweb/unison/assets/538571/99583801-95da-4798-9b9e-50ebae2c0de8">
    a. if it's changed to a `> ` watch expression, it will be rendered more simply:
        <img width="253" alt="image" src="https://github.com/unisonweb/unison/assets/538571/bd7e9dff-da73-47da-b254-6aae0aec94e7">
    b. if it's not a watch expression at all, it won't be evaluated on save:
        <img width="655" alt="image" src="https://github.com/unisonweb/unison/assets/538571/5e568a08-744f-4bcb-a397-fb755a20d92e">

2. it implicitly adds a type constraint that the expression be of type `[test.Result]`
    <img width="386" alt="image" src="https://github.com/unisonweb/unison/assets/538571/e771d6e8-146d-40a5-9357-881fea17cc44">

Closing this ticket as fixed/moot, but feel free to reopen with any concerns about testing DX
