### ISSUE TITLE
Prioritized Doc Rendering Improvements 

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#2795]
* Preserving the type signatures for Unison terms in fenced codeblocks. See for example the difference between the following term renderings: 

`````
test = {{
  ```
  t : Text
  t = "hi"

  t
  ```
  @source{t1}

}}

t1 = "hi"
`````

* Pattern match issue in fenced codeblocks - https://github.com/unisonweb/unison/issues/2778

**Comment by dolio** [comment]
So, I don't see signatures for either of these. The desire is that they both have signatures? Or just `t`?

**Comment by rlmark** [comment]
Ah, sorry I should have been more specific, the rendered doc (in the ui) for `test` will have the type signature included for the `@source{t1}` example but will omit the signature for the fenced codeblock. We were hoping to have the fenced codeblock include the type signatures in the manner that the `@source` tagged code does. 
![Screen Shot 2022-01-10 at 2 32 15 PM](https://user-images.githubusercontent.com/7613551/148849466-848f6ae7-3118-40a1-8190-759a73fa4eec.png)

**Comment by dolio** [comment]
Oh, I see. The terminal display doesn't have a signature for `t1` either. But I guess it must be missing in whatever ends up in the evaluated doc, or the gui would be showing it for both (I assume).

**Comment by rlmark** [comment]
Oh that's a good question, I assumed it was a server-side issue but I should check with @hojberg to see if there's anything in the rendering of the fenced codeblocks that would solve the problem on the front end.

**Comment by rlmark** [comment]
Checked with Simon and it does not have the type signature in the Json payload.
