### ISSUE TITLE
Pretty Printer change: overapplied operators should render with infix syntax 

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#2796]
For functions like "compose" (.) or (<<) the renderer will not use infix syntax leading to somewhat confusing code. 

The following expression 
```
(f . g) x
```

renders as the following: 
```
(.) f g x 
```

This isn't a huge issue, it came up while documenting function application, but if it's easy to do that would be awesome.

**Comment by ceedubs** [comment]
#2741 is closely related to this
