### ISSUE TITLE
`update` initial dirty set does not include unnamed things

### ISSUE THREAD

**Issue by mitchellwrosen** [unisonweb/unison#2807]
When computing the initial dirty set of references to propagate an update to, we (intentionally) throw away unnamed references. Curiously, after the initial set, propagation proceeds through unnamed references. I think it may be more consistent and correct to just delete the line of code that filters out unnamed references from the initial dirty set.

The following transcript demonstrates an update to `one`, with transitive dependency `three` that is left referring to the old `one`.

````
```unison
one = 1
inner.two = one + 1
three = inner.two + 1
```

```ucm
.> add
.> delete.namespace.force inner
```

```unison
one = 100
```

```ucm
.> update
.> view three
```
````

Output:

````
```unison
one = 1
inner.two = one + 1
three = inner.two + 1
```

```ucm

  I found and typechecked these definitions in scratch.u. If you
  do an `add` or `update`, here's how your codebase would
  change:
  
    ⍟ These new definitions are ok to `add`:
    
      inner.two : Nat
      one       : Nat
      three     : Nat

```
```ucm
.> add

  ⍟ I've added these definitions:
  
    inner.two : Nat
    one       : Nat
    three     : Nat

.> delete.namespace.force inner

  Removed definitions:
  
    1. two : Nat
  
  Tip: You can use `undo` or `reflog` to undo this change.

  ⚠️
  
  Of the things I deleted, the following are still used in the
  following definitions. They now contain un-named references.
  
  Dependency   Referenced In
  two          1. three

```
```unison
one = 100
```

```ucm

  I found and typechecked these definitions in scratch.u. If you
  do an `add` or `update`, here's how your codebase would
  change:
  
    ⍟ These names already exist. You can `update` them to your
      new definition:
    
      one : Nat

```
```ucm
.> update

  ⍟ I've updated these names to your new definition:
  
    one : Nat

.> view three

  three : Nat
  three =
    use Nat +
    #9d4sko62oe + 1

```
````

**Comment by mitchellwrosen** [comment]
Chatted with @aryairani about this one today. It seems the general goal of not propagating through unnamed updates is desirable (because unnamed things are outside the update scope), except when an unnamed thing is depended on by a named thing!

So there are a couple problems with the current implementation:

- It's incorrect to omit unnamed things from the initial dirty set, because they may have named dependencies.
- It's incorrect to propagate through unnamed things iff the unnamed thing has only unnamed dependencies.

**Comment by pchiusano** [comment]
It's fine to propagate through unnamed things, you just don't want to replace names outside the current namespace. The propagation state is a mapping from old hash to new hash. It's okay if that mapping ends up being bigger than is needed to map all the definitions in the current namespace. This then saves you from having to do any complicated calculations about whether an unnamed thing has any named transitive dependents in the current namespace.

OTOH, it would be cheaper to avoid doing work (and creating unused unnamed hashes) for hashes with no transitive dependents in the current namespace.  

Also #2248 has some notes about some incorrect propagation and how to fix.

**Comment by aryairani** [comment]
We no longer have a dirty set, etc. We should collect a list of requirements at some point though, for regression testing any new designs.
