### ISSUE TITLE
Kind-preserving type edits should not reinfer type signatures

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2811]
I don't have a transcript for this one, but we recently made a change to the `Location` type of the distributed library, and despite it being a kind-preserving change that should have propagated automatically, a bunch of functions got reinferred. And the inferred types were bad, with lots of extra slack variables. These signatures then needed manual fixing up.

We should continue to improve the inference algorithm, but regardless, we should really avoid throwing out an existing type signature if at all possible. That's what this issue is about.

A good next step would be just producing a regression transcript, which I'll work on.

**Comment by aryairani** [comment]
no longer applicable, although we should have a regression transcript
