### ISSUE TITLE
Transcripts don't support fenced codeblocks in Docs

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#2826]
Because the triple backtick syntax is used to open transcript stanzas AND fenced codeblocks in the docs, any fenced codeblock within a Doc snippet is interpreted as the closure of a stanza. 

A workaround for the curious: 
You can write your unison code in a separate text file, add a `load` statement in the ```ucm block, and then add it to the codebase.

**Comment by aryairani** [comment]
Here is an example:
````
```unison

doc = {{
  @typecheck ```
  x = 3
  ```
}}

```
````

yields

````
The transcript failed due to an error in the stanza above. The error is:


  scratch.u:2:14:
  unexpected end of input
  expecting "```" or white space
````  

This (extra enclosing backticks) doesn't throw an error, but also doesn't do the right thing:

`````
````unison

doc = {{
  @typecheck ```
  x = 3
  ```
}}

````
`````

It doesn't recognize the block as unison code, and just produces some useless output:
````
```
`unison

doc = {{
  @typecheck 
```

x = 3
  ```
}}


```
````

**Comment by sellout** [comment]
[CommonMark allows whitespace before a closing (or opening) fence](https://spec.commonmark.org/0.31.2/#fenced-code-blocks), so the initial example _should_ fail. But adding more backticks to the fences is the right way to fix this, and definitely a bug that it doesn’t.

**Comment by aryairani** [comment]
Oops, I'm not sure what I was thinking with the initial example. Agree that adding more backticks is the right way to fix this.
