### ISSUE TITLE
Minified repro for hash appearance in cycles 

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#2839]
It appears you can still create a cycle and trigger a hash reference in doc links. 

[hashRepro.md](https://github.com/unisonweb/unison/files/7938188/hashRepro.md)

This repro assumes you have a file called `scratch.u` in the codebase where you're running the transcript out of. 

Note, if you try to do this with the entire cycle in your buffer the UCM will not let you save the cycle, so it's still a workaround to keep the code you're working with in the edit buffer. 

version (latest-1510-g446cd222d (built on 2022-01-14)

**Comment by aryairani** [comment]
It looks like the new `update` won't let you create the cycle.  For reasons I don't understand, the transcript runner messes this up https://github.com/unisonweb/unison/issues/5169, so I can't just demonstrate in a transcript, but with ucm v0.5.23 when you get to this step:

```unison
doc3 = {{
  Doc3

  [link to doc1]({doc1})
}}
```

ucm will send all 3 docs back to the scratch file, from which it then complains about the cycle:

```
.> update

  Okay, I'm searching the branch for code that needs to be updated...


  That's done. Now I'm making sure everything typechecks...


  Typechecking failed. I've updated your scratch file with the definitions that need fixing. Once
  the file is compiling, try `update` again.

.> 

  Loading changes detected in ~/work/unison/trunk/scratch.u.


  These definitions depend on each other cyclically but aren't guarded by a lambda: doc33, doc14, doc25
      1 | doc1 : Doc2
      2 | doc1 =
      3 |   {{
      4 |   Doc1
      5 |   
      6 |   [link to doc2]({doc2})
      7 |   }}
      8 | 
      9 | doc2 : Doc2
     10 | doc2 = {{ Doc2 [link to doc3]({doc3}) }}
     11 | 
     12 | doc3 : Doc2
     13 | doc3 =
     14 |   {{
     15 |   Doc3
     16 |   
     17 |   [link to doc1]({doc1})
     18 |   }}
```
