### ISSUE TITLE
`Doc` fails to `display` on `topic/rehash-codebase`

### ISSUE THREAD

**Issue by ChrisPenner** [unisonweb/unison#2840]
```
README = {{
Hi
}}
```

```
Encountered Exception: PE [("die",SrcLoc {srcLocPackage = "unison-parser-typechecker-0.0.0-LZIUVczRl7wJ89oxDaccfj", srcLocModule = "Unison.Runtime.Interface", srcLocFile = "src/Unison/Runtime/Interface.hs
", srcLocStartLine = 127, srcLocStartCol = 18, srcLocEndLine = 127, srcLocEndCol = 60})] Lit          
  AnnotatedText (fromList [Segment {segment = "Unknown term reference: #4rv8d", annotation = Nothing}])
```

 https://unisoncomputing.slack.com/archives/CLGTK464E/p1643319318010400

**Comment by ceedubs** [comment]
Note that this problem happens with `display` but not with `view` or when looking at docs through the local UI.

**Comment by ChrisPenner** [comment]
Hrmm, so running `builtins.mergeio` on the migrated codebase solves this issue, but that suggests that there's some mismatch between the way old builtins are being migrated vs how they're added with `builtins.mergeio`.

EDIT:
The hash `#4rv8d` refers to a version of `base.syntax.docFormatConsole`, which is somehow added by running `builtins.mergeio`, but for some reason doesn't have actually a name in the migrated codebase 🤔 '

EDIT:
Okay, so it seems like migrating `base` from trunk is resulting in a different `base.syntax.docFormatConsole` hash (`#uji6nns90b`) than running `builtins.mergio` on the new ucm (`#4rv8dvuvf5`), or from running `builtins.mergeio` on ucm and then migrating it (`#4rv8dvuvf5`)

**Comment by ChrisPenner** [comment]
I’ve found that migrating the same v1 hash can result in two different v2 hashes depending on the state of the rest of the codebase, which doesn’t make much sense to me.

Specifically, if I start from a clean codebase, run `.> builtins.mergeio` , then `builtins.syntax.docFormatConsole` has the v1 hash `#4522dhabfa`. If I then migrate that codebase, I find that `builtins.syntax.docFormatConsole` has the v2 hash `#4rv8dvuvf5`.

HOWEVER, if I start a new v1 codebase and let it pull base, base.syntax.docFormatConsole has the same v1 hash `#4522dhabfa`, but after migrating that codebase the result base.syntax.docFormatConsole has a different v2 hash `#uji6nns90b`!

**Comment by ChrisPenner** [comment]
Okay, so I tracked down why the same hash can turn into two different v2 hashes, it's because the type is now part of the hash, and the type of many terms in the base codebase are different from the types provided by a `builtins.mergeio`.

base should probably be updated to include the correct types, but it's not a dealbreaker since this doesn't indicate any issues with regard to codebase integrity.

However it still leaves the question of why we're getting this particular error, I'll dig deeper into that next.

**Comment by ChrisPenner** [comment]
Okay, so I think this is what's happening.

When we `display` a term, we hit this codepath:

https://github.com/unisonweb/unison/blob/trunk/unison-cli/src/Unison/CommandLine/DisplayValues.hs#L81

Which calls through to:

https://github.com/unisonweb/unison/blob/trunk/parser-typechecker/src/Unison/Runtime/IOSource.hs#L224 ;

Which parses the IOSource `source` block and returns the hash for its `syntax.docFormatConsole`. This code implicitly assumes that this term has already been added to your codebase.

If the term it expects to find in your codebase is missing, it simply crashes because it can't find it by the expected hash.

The reason this is manifesting differently on a post-migration codebase is that in the migrated codebase, a term by the name `syntax.docFormatConsole` DOES exist, but it doesn't have the expected hash, this is because we now include types in the hash of a term, and some of these terms in base are old enough that they have types which used a different ability inference algorithm, and thus have different hashes than the code in IOSource's `source` block.

Ultimately this isn't a codebase integrity issue or anything luckily.

My suggestion would be:

1. when we release the migrated version of base, either round-trip every term in IOSource through a scratch file to update the inferred type-signatures, or just delete the old ones and do `builtins.mergeio` to get the up-to-date terms with the correct type signatures.
2. We probably shouldn't be just relying on the existence of terms by certain names or hashes like this, or if we do rely on certain hashes, they should probably be added to the codebase on codebase creation or something. We can chat about alternative approaches in a future step.

As it is, you can end up with pretty weird results by having terms of specific names in your codebase; e.g.

```unison
syntax.docWord _ = 1
syntax.docParagraph _ = 1
syntax.docUntitledSection _ = 1
syntax.docFormatConsole = 1
```

```ucm
.> add
```

```unison
README = {{hi}}
```

```ucm
.> display README

  1
```


The current version also fails to handle name-conflicts properly

![image](https://user-images.githubusercontent.com/6439644/152244187-cf2f38b6-5f0a-4182-bf2a-3494d860a93b.png)

**Comment by aryairani** [comment]
Related to https://github.com/unisonweb/unison/issues/2845

**Comment by aryairani** [comment]
There are a bunch of definitions that UCM expects to have around, to work properly, it seems like you identified another one that I wasn't aware of. IMO we should just start adding any of these that are missing, on ucm startup. We should not delete them during GC. The set may change from version to version of ucm, but that's fine. We shouldn't let multiple versions of ucm access a codebase at the same time (or we do something else to make sure they aren't garbage collecting essentials out from each other).

OR maybe better

Instead of relying on "the codebase" to provide essential definitions, we could keep them in in some virtual read-only store inside of UCM, so they're always available.

**Comment by ChrisPenner** [comment]
Same underlying issue as: #1970

**Comment by ChrisPenner** [comment]
Me, @aryairani and @mitchellwrosen  met up to discuss longer-term solutions for this issue since we've encountered it several times, and since it's likely to manifest again in the future when we make changes to terms in IOSource.hs

There are two core issues:
1. What if terms like `syntax.docUntitledSection` are required by the doc unsugarer but don't exist in the codebase
2. What about the terms like `syntax.docFormatConsole` (and some pretty printing combinators) whose hashes are required to exist in the codebase by the `display` command.

We've decided to address only 2 for now and leave 1 for another time since it's trivially remedied by either pulling base or running `builtins.mergeio`.

In solving 2 we had several goals:
* Commands like `display` shouldn't crash even on an empty codebase.
* The solution shouldn't slow things down too much, ideally we could even speed things up by avoiding the need to parse & typecheck `IOSource` on every run of ucm.
* We should be able to update implementations of the IOSource definitions which are used internally without crashing on codebases which haven't `builtins.mergeio`'d them yet.

Here are some ideas:

1. When we parse/typecheck IOSource.hs, also ensure those definitions are in the codebase (save them to the codebase without names if they aren't already there);

Pros: Uses the codebase to store the code rather than circumventing it.

Cons: These definitions will be orphaned in many codebases, what happens when we garbage collect?

2. Augment the code lookup which is passed to the runtime (for `display` only) to include definitions from IOSource.hs

Pros: the runtime will always have the most up-to-date versions. This should be pretty easy to add and should run fast.

Cons: Are there downsides to providing the runtime with definitions which don't exist in the codebase itself? Could we end up in a weird situation?

Enhancement: Parse and typecheck in template-haskell at compile time

3. On codebase creation (and migration), call builtins.mergeio (possibly without actually adding names for these definitions)

Pros: This would only run once.
Cons: What if these definitions get garbage collected at some point? What if we update these definitions down the road?

**Comment by pchiusano** [comment]
> 2. Augment the code lookup which is passed to the runtime (for `display` only) to include definitions from IOSource.hs

This seems good. I don't think there's any downsides, especially since `display` is just printing some stuff out. If it makes reference to stuff that's not in the codebase while doing so, that's fine.

When doing this, put the `CodeLookup` from `IOSource` last and it will be lazy, only consulted when displaying a doc or something else that uses stuff from `IOSource`.

**Comment by aryairani** [comment]
Agreed.
