### ISSUE TITLE
Rehash-migration pretty-printing fails for constructors with polymorphic fields

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2849]
```
structural type Foo = Foo (forall a . a -> a)
```
Then just `add` and then `view Foo` to trigger the error.

```
Encountered Exception: Failed to typecheck record field: User "up.Random.RNG._.set"
CallStack (from HasCallStack):
  error, called at src/Unison/DeclPrinter.hs:152:36 in unison-parser-typechecker-0.0.0-LZIUVczRl7wJ89oxDaccfj:Unison.DeclPrinter
```

In the rehash migration branch, types are now incorporated into term hashes. This is good and expected, but it means that our trick for detecting whether to use record accessor syntax now has to run type inference of the generated record accessors.

Since higher rank types are not inferred, this causes an inference failure during pretty-printing. The fix is as simple as just bailing on using record syntax if the field accessor doesn't typecheck, at least until https://github.com/unisonweb/unison/issues/498 can be addressed. But #498 is a bigger deal than it seems so I wouldn't make that critical path.

@aryairani not sure who best person is for this, but forwarding to you to decide. :)

**Comment by aryairani** [comment]
Closed by #2866
