### ISSUE TITLE
Change pretty printers to use color

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#287]
Currently, `Unison.TypePrinter` and `Unison.TermPrinter` produce a `Pretty String`. It would be great if it could produce color, when printing terms to the console, and we can also use this as the basis for HTML rendering (also, having a "copy to HTML" could be nice if you're like, pasting some Unison code into an email and want syntax highlighting).

Goal: change all pretty printers to return a `Pretty ColorText`. Since `ColorText` (reexported by `Unison.Util.Pretty` module I think) has an `IsString` instance, change should be really simple to do. Like it might even just work if you change the signature of the `pretty` functions.

After that, we could add some simple syntax highlighting - I'd suggest adding some constants for different semantic elements (keywords, numeric literals, special operators like `->` and `{}`, `'`).

Since we can map over the `Pretty`, the exact colors chosen doesn't matter too much, as long as distinct colors are used for distinct elements, we can always remap them later.

@atacratic this is all yours if you like, but you can assign to someone else if you're busy with other stuff

**Comment by LukaJCB** [comment]
Did you start working on this yet @atacratic, if you haven't, I'd be happy to work on this one :)

**Comment by atacratic** [comment]
No I haven't, you feel free, that would be great! 😀

**Comment by atacratic** [comment]
I might have a crack at this at some point, but un-self-assigning for now.
