### ISSUE TITLE
Pretty-printer for ability and data declarations

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#288]
The goal: we gotta be able to pretty-print type declarations. 

(To clarify, `Int -> Int` is a _type_, and `type Optional a = None | Some a` and `ability Remote where ...` are type _declarations_. A type declaration introduces both a new type and also some set of terms and patterns for constructing / deconstructing values of that type.)

What needs to be done: 

- [ ] Add `Unison.TypeDeclarationPrinter` module.
- [ ] In it, add `pretty` functions analogous to what @atacratic already wrote in `TermPrinter` and `TypePrinter`

Once this is done let's integrate it into the codebase editor so these things can be viewed from there.

If you have any questions about pretty-printing, talk to @atacratic.

**Comment by virusdave** [comment]
I'm interested in taking a whack at this one.  I've started reading the existing pretty printer code.

**Comment by pchiusano** [comment]
@virusdave go for it!! We will probably start using this as early as THIS WEEK though, so let us know if you aren't going to have a chance to look at it before then.

**Comment by virusdave** [comment]
I will only have time to look into this over this weekend (and a little tonight).  Apologies for late response, my github notifications get routed out of my inbox due to volume :(   I'll need to update my filters.  If this is too late / slow for this functionality given your need for it, don't worry, i'll be happy to pick up a different piece that's less time critical.

**Comment by pchiusano** [comment]
Hi @virusdave just checking to see if you’ve had a go at this yet or need any help getting started. 😀

**Comment by virusdave** [comment]
Hi Paul!  I'm getting over sickness, but i did get a chance to start on this over the weekend.  I didn't make much progress, beyond trying to understand the existing referenced pretty printers.  I think i'll be able to make some concrete progress before long, but if there's anything else you want to point me to speed that up, definitely please do :)  Documentation in this project has definitely improved (i'm able to build it now, it seems), but there's still a lot of manual browsing to understand how things are organized, etc.  Not a complaint (i like the challenge and landscape), but hints / pointers welcomed!

**Comment by virusdave** [comment]
This is fantastic, thanks! I'll look at these tonight :)

**Comment by pchiusano** [comment]
@virusdave I pinged you in Gitter about this, but we had to take this one over. Sorry to swoop in, but we were kinda blocked on it! You can take a look at the results here: https://github.com/unisonweb/unison/blob/master/parser-typechecker/src/Unison/DeclPrinter.hs
