### ISSUE TITLE
Styling in docs fails to parse if split over one line

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#2882]
If a styling element in a doc like double underscore or double asterisk splits two lines. The UCM will fail to parse. 

For example: 

```
doc = {{
__ Important 
doc__ text 
}}
```

While most of the time you can get around this by not splitting your style elements up, sometimes you might have a line that is longer than the minimum width of the pretty printer output.

**Comment by aryairani** [comment]
Hopefully will fix these definitions from [website](https://github.com/unisonweb/website:#8agaqj52kh):
* [ ] fundamentals.abilities.usingAbilitiesPt1

**Comment by sellout** [comment]
This works now, but the example in the description has a bug – there’s a space between the opening `__` and `Important`. I don’t know if that’s just a typo in the issue report or what made this look like a bug in the first place, but
```unison
> doc = {{
__Important
doc__ text
}}
```
```
    1 | > doc = {{
          ⧩
          Paragraph [Italic (Paragraph [Word "Important", Word "doc"]), Word "text"]
```
