### ISSUE TITLE
record types are not rendered correctly at https://www.unison-lang.org/docs/language-reference/record-types/

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#2905]
<img width="756" alt="image" src="https://user-images.githubusercontent.com/538571/153339154-916bdfd3-57b3-4f49-8256-fdd76bdcab5e.png">

I suppose this is actually a ucm problem, but I could use help to confirm.

**Comment by hojberg** [comment]
Yeah this has been a recurring problem. @pchiusano and I fixed it somewhat a few months ago, but not clearly completely.

**Comment by hojberg** [comment]
Moving to the unison repository.

**Comment by hojberg** [comment]
Marking this as a roundtrip bug. cc @runarorama

**Comment by aryairani** [comment]
the page in question no longer exists
