### ISSUE TITLE
publish Unison Share hosting roadmap

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#2911]
- Unison Share style code browsing of all repos
- Awesome PR workflow
- In-browser editing; w/ awesome pair/mob support
- ...

- ecosystem-wide vulnerability patching

**Comment by hojberg** [comment]
I'm planning on making a dedicated page on Share for this btw.

**Comment by hojberg** [comment]
We have a roadmap on https://unison-lang.org/roadmap
