### ISSUE TITLE
ucm won't launch without `less`

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#2939]
We could bundle https://github.com/jftuga/less-Windows
http://www.greenwoodsoftware.com/less/download.html
http://gnuwin32.sourceforge.net/packages/less.htm
Or have ucm look for different pagers

**Comment by ceedubs** [comment]
Related: #2518

**Comment by runarorama** [comment]
Can we just use the PAGER env var? If not present, just don't page. If on windows, MORE is always available.
