### ISSUE TITLE
Better error message for "No such file or directory"

### ISSUE THREAD

**Issue by francisdb** [unisonweb/unison#295]
Not sure what is not found here but the error message could be better. 

What is it trying to do?
What file is not found where?
How can this be fixed?

```
➜  unison git:(master) ./scripts/unisonloop.sh
unison: scala: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
Well that didn't work.
Press any key to re-launch.
```

```
➜  unison git:(master) stack exec unison
unison: scala: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

and related

```
➜  unison git:(master) ./scripts/unisonloop.sh
./scripts/unisonloop.sh: line 4: bloop: command not found
Well that didn't work.
Press any key to re-launch.
```

**Comment by pchiusano** [comment]
I think this needs a ‘stack build’ first? Agree error msg is not good.

**Comment by aryairani** [comment]
No, I think it wants the runtime built with bloop first.  Try running ./scripts/watchwatch.sh from the project root and then kill it once it finishes building.  Then you should be good to go.  Agree the message and the workaround are not good.

**Comment by francisdb** [comment]
The issue was that Scala was missing in the PATH. Maybe the message could point to that?

On a side note, would it not be possible to fall back to the version that sbt is using/installed?

**Comment by pchiusano** [comment]
Hey @francisdb - am going to close this issue but feel free to contribute a PR to improve the docs for getting started with development and/or any improvement to the scripts themselves. Just FYI, the scripts in that directory are all quick and dirty, hacks for the dev team, and some might be obsolete. :)

**Comment by francisdb** [comment]
This is failing in the haskell code, not the scripts. Would adding a check to [JVM.hs](https://github.com/unisonweb/unison/blob/master/parser-typechecker/src/Unison/Codebase/Runtime/JVM.hs#L90) be ok?
We could use this function to check if scala is available in the path:
https://hackage.haskell.org/package/directory-1.3.1.5/docs/System-Directory.html#v:findExecutable

**Comment by runarorama** [comment]
@francisdb do it! 👏
