### ISSUE TITLE
support symboly namesegments in scratch file parser

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#2970]
Verify whether this sort of thing can round trip; and propose a solution if not.
![image](https://user-images.githubusercontent.com/538571/156695088-0f20f3fe-70a4-40cc-9986-29b543e1c54f.png)

**Comment by ChrisPenner** [comment]
I looked into this a little, we'll need to decide how we parse something like `-.-.-` ; since if `.` is a valid operator character then it could be any number of valid parses; E.g. the operator could be `-`, or it could be `-.-` inside the `-` namespace; etc.

**Comment by runarorama** [comment]
We should simply disallow . as an identifier

**Comment by ChrisPenner** [comment]
Yeah I think disallowing `.` as an operator char is the simplest valid solution here, I can make that change to the parser, but it'll mean that any existing operators using `.` won't round trip and will need to be renamed 👍🏼

**Comment by aryairani** [comment]
Eventually we can support escaped names; in the mean time I think disallowing whatever makes our lives easiest is fine.

**Comment by ChrisPenner** [comment]
> Eventually we can support escaped names; in the mean time I think disallowing whatever makes our lives easiest is fine.

The reason to support escaped names would be to ensure that users who already have dots in operator names can still round-trip their codebases and not get stuck in a weird state. They can re-name any of those operators from ucm of course, just want to make sure we're okay with the possibility some users would be in a weird state. Most likely if they've updated ucm but haven't re-pulled base recently.

**Comment by rlmark** [comment]
Hello! Apologies if this is the wrong parent ticket to mention this in, but this has [surfaced in the slack as a question again](https://unisonlanguage.slack.com/archives/C036D4CGA0K/p1698003589580999). One of our community members is interested in adding tests for `Duration./` and our old workaround of adding the test term as `Duration.divide.test1` and then renaming the term to its operator form no longer works as the parser for command inputs also rejects operator names now.
