### ISSUE TITLE
Links suffixed with `.html` don't render appropriately in docs 

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#2979]
We may have to move this ticket over to the website repo, but I'm recording it here as a place to start triaging. 

A `.html` link in a doc (below) ends up stripping the ''.html'' from the rendered link in the final generated html components. 
```
doc = {{
[See a how-to for this process](https://www.tenforums.com/tutorials/180053-how-change-default-terminal-application-windows-10-a.html)}}
```

**Comment by hojberg** [comment]
This has been fixed. Was a bug in the build script of the website repo.
