### ISSUE TITLE
Self-contained namespaces (replaces archived namespaces idea)

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2988]
So I want to close #1340 as being a bad approach (in addition to adding a bunch of ugly underscores to your namespace tree) and propose something better instead.

**Problem:** My namespace tree is a mess of multiple versions of libraries and definitions, even though for a given project / context, I don't really want everything that appears anywhere in my tree to be visible. In addition to just making search results a lot noisier, suffix-based resolution will find me things in places I don't really intend, and I'll get suffix-based resolution ambiguities just because somewhere in my namespace tree I have an old version of a library. This is no fun.

It's a FEATURE to be able to manage multiple projects in the same namespace tree and switch between them instantly. Let's keep that. But experience has shown us that we DO still want the ability to restrict what names are visible. So here is a dead simple proposal for how to do that, which has some nice properties:

__Nothing outside the current namespace is visible__

So you cannot `view` or `edit` or `find` anything outside your current namespace (we might introduce `find.at`, `view.at` etc to do the equivalent of `cd`, `find`, `back`). Each namespace is a completely isolated universe of code and you can never accidentally reference anything outside of it.

The only commands that can talk about things outside the current namespace are `fork`, `merge`, and `cd`.

Let's see how this plays out.

Rather than having various versions of libraries strewn about your namespace, each "project" (I'm using this term informally, but will connect this to the formal projects proposal at the end) will have a `lib` namespace for its external dependencies:

```
distributed/
  trunk/
    lib/
      base/
    Readme : Doc
    ability Remote
    type Seq
    ...

  releases/
    a2/
      lib/
        base/
      Readme : Doc
      ability Remote
      type Seq
```

Boom. Done. The `distributed` namespace is totally self-contained, as are the various subnamespaces that correspond to branches (like `trunk` and releases like `a1` and `a2`). If I want to add a new dependency to `distributed`, for now I can just:

```
.> cd distributed.trunk.lib
.distributed.trunk.lib> pull <somelibrary> json
```

Bammo. If I really want to install multiple versions of a library, I can always do `pull <somelibrary> json.v6` in my `lib` namespace. (Eventually some project-specific commands for installing and upgrading libraries would be great rather than this manual `cd` and `pull` business. Suggestion `install share.stew.json` will just do the correct `pull` command from share and stick it in `lib` under `stew.json`)

That's really it.

__Benefits:__

* The various forks and feature branches of my library no longer interfere with each other. I can't like, accidentally reference something from another fork or get bad suffix-based name resolution just because my tree has multiple projects and forks.
* Optimization: UCM can avoid even loading things into memory that are not under the current path. Hello instant startup times!
* I can easily create "template" projects with whatever curated collection of dependencies, and fork copies of those projects anytime I wanna start something new. I'd suggest that codebase initialization create a `scratch` project with a `lib` directory that includes just `base`.
* The feature naturally coaxes people to produce self-contained namespaces, since there's no way to reference definitions outside the current namespace!

__Drawbacks:__

* You can't really just `cd` into some random subnamespace of your project and mess around there. This feature was always a footgun anyway--for instance you pretty much never want to produce a patch in a random subnamespace of your project. Resurrecting the `namespace` blocks (implemented better though) will be a good substitute for the more legit concern of just not wanting to manually prefix all the symbols in your scratch file.
* You can no longer reference definitions willy nilly without understanding what libraries they are coming from. On the one hand I kind of liked this, but it doesn't scale and I don't think we're doing people any favors by making this the easy path. With this proposal, you now have to think about your dependencies more carefully and there's a bit more ceremony to bringing in a new dependency. As I mentioned, a `find.at` or `find.global` command would be nice for discovering libraries, though `cd .`, `find`, and then `back` works too.
* Not exactly a drawback, but `update` constructor mapping propagation relies on there being names that exist for the old and new versions of the constructors. If we do the thing proposed in https://github.com/unisonweb/unison/issues/2248 (where for each update, we create an `old` subnamespace containing old versions of things, prior to the change, and then `todo` is just reporting on things that depend on something in `old`), then this just works out and constructor mapping should work fine.

## Some other ideas I thought about

One idea I had was to have a `lib` namespace and a `src` namespace inside every project:

```
distributed/
  trunk/
    lib/
    src/
      Readme : Doc
      ability Remote
      ...
```

This allows people to have projects with a `lib` namespace that doesn't correspond to external dependencies. Which doesn't seem all that useful. It also is awkward to deal with the `src` namespace that prefixes literally all symbols in the project... even if you have `namespace` blocks, it is weak having to put `namespace src where` as boilerplate at the top of every file.

Another idea I considered was having `src` and `lib`, and then have `edit`, `add`, and `update` magically always target the `src` namespace without you having to manually prefix all the symbols in your scratch file. I didn't like this idea. It feels too magical and what if I really do want to just edit a thing at the root which isn't nested under `src`.

## Implementation notes

On startup, it probably pays to remember the last path you were in (perhaps reading it from a text file we store next to the reflog), and just load that namespace into RAM, rather than loading the entire namespace into RAM. So the loop state for `HandleInput` is a path and a `Branch`, but the branch corresponds to the `Branch` at that path (rather than what we do now where we store the root `Branch` and then a path). The codebase should be able to efficiently save a subnamespace of the root.

## How does this interact with the projects proposal?

Easy peasy. You'd just have a project definition at the root of your project, at the same level as `trunk` and `releases` and other feature branches:

```
distributed/
  project : Project
  trunk/
  releases/
```

Now, rather than manually mucking with the `lib` subnamespace of each fork, you use some more specific project-oriented commands for this purpose. But the idea is the same.

**Comment by pchiusano** [comment]
@ceedubs made me think that alias.term/type should also be able to reference an absolute name for their first argument - in this way, individual definitions can be brought into the "local universe" as well as whole namespaces.

**Comment by atacratic** [comment]
This feels good, I like it 😊

Comment: you're going to end up with a lot of copies of the base namespace kicking around, recursively through each dependency (see example below).  Is that really going to work out performance-wise?

```
foo/
  trunk/
    lib/
      base/
      bar/
        lib/
          base/
          baz/
            lib/
              base/
    Readme : Doc
    ...
```

Maybe when a library release is published its own sub-libs could be pruned just to names it references?  i.e. tree-shaking the libs namespace.  Just for the published release, not the trunk.

**Comment by runarorama** [comment]
Came here to add the same comment as @atacratic. One thing that can save us here is that you'll normally be working with one release (or a handful of releases) of `base` in your whole tree, and since namespaces are referenced by hash, it's absolutely fine if the same hash appears at multiple levels in the tree.

**Comment by pchiusano** [comment]
Yeah, the namespace loading should preserve sharing as well, so that if the same namespace hash appears in multiple places in the tree, there aren't two copies of that subnamespace in RAM. 

If we implement the optimization I mentioned of not even keeping things in RAM that are outside the current namespace, then this concern also goes away I think.

**Comment by ceedubs** [comment]
@atacratic that's a really good point.

Actually what concerns me more than performance is the potential namespace pollution. Say that I depend on a Vault client that happens to "internally" depend on some JSON library. I don't necessarily want terms/types from that JSON library to start showing up in my `view`/`edit`/autocomplete results. I think that I'd only want results from libraries that I directly (not transitively) depend on. Admittedly these notions of libraries and "direct" dependencies aren't necessarily the most direct fit in Unison. I'm not really sure how we could approach this other than by special-casing `lib` and not showing results for nested `lib` namespaces (unless they also have names somewhere else).

**Comment by ceedubs** [comment]
But maybe the namespace pollution isn't that much of a concern, especially if we treat multiple names for the same hash as a single result. In other languages it's common to see results from transitive dependencies when using autocomplete.

**Comment by pchiusano** [comment]
`view` and `edit` could certainly rank things in `lib` lower if we want... though we don't do that now FYI. You can type `view` and see something anywhere in the tree, even outside the current namespace, as long as you pick a unique suffix.

I do want to be able to see source code for things that are dependencies of my projects and I don't think we should make people jump through hoops to achieve that.

**Comment by ceedubs** [comment]
@pchiusano that's an option. But I don't think that `lib.vault.Config` is as much of a problem as `lib.vault.lib.json.Config`. If you want to be able to use the latter, then I would think that you would add `json` as a top-level dependency.

**Comment by ceedubs** [comment]
Having said that, @pchiusano I like the simplicity of your proposal and would be all for giving it a try and seeing how it feels.

**Comment by pchiusano** [comment]
> But I don't think that lib.vault.Config is as much of a problem as lib.vault.lib.json.Config. If you want to be able to use the latter, then I would think that you would add json as a top-level dependency.

Yeah... as long as those are the same versions of the json library! Unison has no problem with using a library which uses a different version of the json library than the one you are using directly.

I could imagine the `install` command being smarter and removing nested libraries that already exist at the top level of your `lib`.

**Comment by hojberg** [comment]
> You can't really just cd into some random subnamespace of your project and mess around there. This feature was always a footgun anyway--for instance you pretty much never want to produce a patch in a random subnamespace of your project. Resurrecting the namespace blocks (implemented better though) will be a good substitute for the more legit concern of just not wanting to manually prefix all the symbols in your scratch file.

With formal projects, we could help this drawback by extending the lookup boundary to the nearest parent project of whatever namespace you're currently cd'd into.

**Comment by pchiusano** [comment]
I had an interesting idea: suffix-based name resolution could prefer resolutions whose resolved name has fewer 'lib' segments.

Admittedly a special case but it has the effect of preferring definitions from your project over definitions from direct dependents.

This also has the important effect of allowing your dependencies to use totally different versions of libraries without it messing up name resolution for you. I don't care if Bob is using a different version of the json library than me, or he's using some library that happens to use the symbol List.filter to mean something totally different.

With this idea, I'd have the ranking treats anything with > 1 'lib' segments the same. So stuff in the current project is preferred (0 'lib' segments), then things you've explicitly added to lib (1 'lib' segment). And anything which is "dependencies of my dependencies" and beyond is ranked the same.

**Comment by ceedubs** [comment]
@pchiusano I just noticed a side effect of this. This encourages the `lib` approach, so you get to the point where running `test` runs the tests for all of your `lib` dependencies. With test caching I don't really think that this is a concern. Just bringing it up since I hadn't considered this consequence.

**Comment by pchiusano** [comment]
Good observation. It’s kind of noisy to include all that in the test output, though, even if it’s cached. I’ll noodle on it.
