### ISSUE TITLE
Universal equality on `Bytes` is always false

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#2989]
```
    1 | > 0xsff === 0xsff
          ⧩
          false
```

**Comment by ceedubs** [comment]
@runarorama what version of ucm are you using? This used to be a problem, but I think that you fixed it in #2929.

On `release/M3 (built on 2022-03-08)` this returns `true` for me. Maybe try `debug.clear-cache` too.

**Comment by runarorama** [comment]
Also returns `true` for me on M3. Switched back to `trunk` and now I can no longer reproduce.
