### ISSUE TITLE
Unison language specification/examples

### ISSUE THREAD

**Issue by minad** [unisonweb/unison#30]
Hi,

I found your project and the lamdu project which seem to go a bit in the same interesting direction. Unison seems to have a slightly bigger goal with this whole networking etc. But I am wondering, did you specify the supported language somewhere?

Basically the same issue as https://github.com/lamdu/lamdu/issues/39

Daniel

**Comment by pchiusano** [comment]
No, there's no spec at the moment and the language is still very much in flux so I think it would be premature to start on one. :) The core language is less interesting to me than the overall platform and I'm more focused on getting the platform further along before diving too far into improving the language. I'm also hoping to make transparent Unison node upgrades part of the platform (this isn't written up anywhere yet), so there isn't as much pressure to get version 1 of the language perfect.

At the moment, the language is:

* The lambda calculus, plus `let` and `let rec` bindings
* The type system is an implementation of [this paper](https://www.mpi-sws.org/~neelk/bidir.pdf)

So not very exciting, but enough to write some useful programs and get all the pieces of the platform working together.

I should do a (somewhat speculative) blog post about generally where I see the core language going though. I'm going to leave this issue open until then.
