### ISSUE TITLE
Getting vim plugin requires cloning entire unison repository

### ISSUE THREAD

**Issue by sullyj3** [unisonweb/unison#3002]
Currently, the editor plugins reside in `unisonweb/unison/editor-support`

This means that installing or updating the vim plugin with standard plugin managers like packer:
```
  use  { 'unisonweb/unison', branch = 'trunk', rtp = 'editor-support/vim' }
```
requires cloning the entire 300mb repo, a process which takes a good couple of minutes on my machine. Besides the fact that it's slow, storing this much data unnecessarily seems not ideal.

Would it be possible to split editor-support into its own repo under the unisonweb org?

**Comment by ceedubs** [comment]
@sullyj3 is your packer configured to do full clones as opposed to shallow clones? I haven't used packer, but in briefly skimming some info it seems like it defaults to shallow clones. When I pull a shallow clone of unison it is ~8.5 MB.

```
❯ git clone --depth 1 https://github.com/unisonweb/unison
Cloning into 'unison'...
remote: Enumerating objects: 1203, done.
remote: Counting objects: 100% (1203/1203), done.
remote: Compressing objects: 100% (982/982), done.
remote: Total 1203 (delta 130), reused 528 (delta 75), pack-reused 0
Receiving objects: 100% (1203/1203), 1.18 MiB | 3.21 MiB/s, done.
Resolving deltas: 100% (130/130), done.

❯ du -sh unison 
8.5M    unison
```

I'm not opposed to splitting editor support into a separate repo (or even maybe a repo specifically for unison-vim). But I wouldn't expect the current setup to be all that big of an issue.

**Comment by sullyj3** [comment]
Hm, I wasn't aware it does a shallow clone by default. I'm not sure why it isn't for me, I certainly haven't deliberately configured it that way. I might have to debug my config.

**Comment by sullyj3** [comment]
Most likely this packer bug:
https://github.com/wbthomason/packer.nvim/issues/792

**Comment by sullyj3** [comment]
Thanks for the tip!
