### ISSUE TITLE
Prettying printing of docs with triple quotes results in bad indentation.

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#3005]
When opening a Doc that uses triple quotes to represent code and that code is indented due to it being within several nested Sections, a bunch of empty space is added at the left side of the code example:

<img width="503" alt="CleanShot 2022-03-28 at 20 17 39@2x" src="https://user-images.githubusercontent.com/2371/160508590-dd443649-1a97-4a8b-872f-f251d459218b.png">

**Comment by pchiusano** [comment]
Closing in favor of: https://github.com/unisonweb/unison/issues/3006
