### ISSUE TITLE
`view` command doesn't show type signature if the type was inferred

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#301]
<img width="290" alt="image" src="https://user-images.githubusercontent.com/11074/51559147-272cae00-1e4f-11e9-8387-58acc5a9c91c.png">

When pulling out a definition for a term, we should check if the term has an annotation. If yes, leave it alone. If no, look up the type of that term and add it as an annotation.

**Comment by aryairani** [comment]
Note: this shouldn't/doesn't affect the hash on an update, because we drop the type signature on save if it's the same one that would have been inferred.
