### ISSUE TITLE
Somehow get stack to produce less garbage output

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#303]
<img width="960" alt="screen shot 2019-01-24 at 2 45 37 pm" src="https://user-images.githubusercontent.com/11074/51704351-d64fbd80-1fe6-11e9-8bea-67d79c1efba9.png">

```
ld: warning: text-based stub file /System/Library/Frameworks//ImageIO.framework/Versions/A/ImageIO.tbd and library file /System/Library/Frameworks//ImageIO.framework/Versions/A/ImageIO are out of sync. Falling back to library file for linking.
```

When I do a `stack build` on my Mac, I get some garbage like the above, which I've also seen on other Mac machines while building the project. I'd really just like to be notified whether the project built successfully, and if not, what are the compile errors. I don't need to be shown random cryptic warnings for the same thing over and over again. Can anyone reproduce and if so, figure out how to fix?

This [SO answer looks relevant](https://stackoverflow.com/questions/51314888/ld-warning-text-based-stub-file-are-out-of-sync-falling-back-to-library-file) but haven't had time to read carefully.

**Comment by francisdb** [comment]
@pchiusano I am not seeing this on my mac. I don't have these `.tbd` files, maybe you can just delete them?

```
ll /System/Library/Frameworks/ImageIO.framework/Versions/A
total 6792
drwxr-xr-x   5 root  wheel      160 Dec 14 12:30 .
drwxr-xr-x   4 root  wheel      128 Sep 24 21:46 ..
-rwxr-xr-x   1 root  wheel  7380576 Nov 30 08:51 ImageIO
drwxr-xr-x  51 root  wheel     1632 Dec 14 12:30 Resources
drwxr-xr-x   3 root  wheel       96 Dec 14 12:30 _CodeSignature
```

I also don't have the mentioned links in the SO answer

```
ll /Library/Frameworks/
total 0
drwxr-xr-x  13 root       wheel   416 Sep 24 21:55 .
drwxr-xr-x+ 66 root       wheel  2112 Nov 20 14:36 ..
lrwxr-xr-x   1 root       wheel    71 Sep 24 21:38 AEProfiling.framework -> ../../Applications/Motion.app/Contents/Frameworks/AEProfiling.framework
lrwxr-xr-x   1 root       wheel    74 Sep 24 21:38 AERegistration.framework -> ../../Applications/Motion.app/Contents/Frameworks/AERegistration.framework
lrwxr-xr-x   1 root       wheel    74 Sep 24 21:38 AudioMixEngine.framework -> ../../Applications/Motion.app/Contents/Frameworks/AudioMixEngine.framework
drwxr-xr-x   3 root       wheel    96 Dec 13  2017 GHC.framework
drwxr-xr-x@  7 francisdb  staff   224 Mar  3  2017 Growl.framework
drwxr-xr-x   6 root       wheel   192 Mar  3  2017 MacFUSE.framework
drwxr-xr-x   3 root       wheel    96 Mar  3  2017 Mono.framework
lrwxr-xr-x   1 root       wheel    60 Sep 24 21:38 NyxAudioAnalysis.framework -> /System/Library/PrivateFrameworks/NyxAudioAnalysis.framework
drwxr-xr-x   6 root       wheel   192 Mar  3  2017 OSXFUSE.framework
drwxr-xr-x   5 root       wheel   160 Sep 24 21:46 PluginManager.framework
lrwxr-xr-x@  1 root       wheel    50 Sep 24 21:38 iTunesLibrary.framework -> /System/Library/Frameworks/iTunesLibrary.framework
```

See also https://stackoverflow.com/a/53497919/42198 for how to regenerate these tbd files

I think we can close this as it's a local issue.

**Comment by noahhaasis** [comment]
[This](https://gist.github.com/karololszacki/dec8fd80b20e081b0e91a6bbd639c8fe) fixed it for me.
