### ISSUE TITLE
Updating a data type can leave references to the old type.

### ISSUE THREAD

**Issue by dolio** [unisonweb/unison#3041]
When updating a data type in a child namespace, it's necessary to fully qualify all recursive references right now, like so:

```unison
unique type name.space.Foo = F Text name.space.Foo
```

If this is not done, like this:

```unison
unique type name.space.Foo = F Text Foo
```

then it seems that name resolution is involved for the recursive references, and the new version of the type is not actually considered. So, the new version of the type ends up having the _old_ version occurring in all the (unqualified) recursive positions. This, of course, is a bit annoying, because fully qualifying all the names is very verbose, and I think it's not actually necessary if the type doesn't already exist, so you might initially write something that works, but behaves wrongly on updates.

**Comment by aryairani** [comment]
This seems to be working today
