### ISSUE TITLE
Lots of back and forth in Git can result in the inability to push.

### ISSUE THREAD

**Issue by ChrisPenner** [unisonweb/unison#3042]
https://unisonlanguage.slack.com/archives/C036D4CGA0K/p1649716812169779

```
.uniwordle> push git@github.com:BrunoBerisso/uniwordle.git .uniwordle
fatal: A branch named 'master' already exists.
Encountered Exception: callProcess: git "--git-dir" "/private/var/folders/n3/3hsfmbnn0kn6tc5kqcsvvxn80000gn/T/ucm-isolated-repo86230/.git" "--work-tree" "/private/var/folders/n3/3hsfmbnn0kn6tc5kqcsvvxn80000gn/T/ucm-isolated-repo86230" "checkout" "--orphan" "master" "--quiet" (exit 128): failed
```

### Notes for reproductions:

[Source](https://unisonlanguage.slack.com/archives/C036D4CGA0K/p1649753403728309?thread_ts=1649716812.169779&cid=C036D4CGA0K)

Deleting the content on ~/.cache/unisonlanguage/gitfiles for my namespace works. I was able to push the namespace to my repo without loosing any changes.
Which git settings were you going back and forth with?
I can't remember exactly the steps to reproduce (I play with Unison once per week :disappointed: ) but I think it was something like this:
I try to push.create [repo] [some_name] but I got the error "I expected an identifier but found [some_name]" I can't remember the exact command now
I created the namespace with namespace some_name and pushed the code successfully
I realice that I pulled "base" into my namespace instead of at the . level so I look for how to move that but didn't found a way so (I think) I delete my namespace and the remote GitHub repo.
I pulled "base" at the root level, created my namespace again and try to push with the command I shared. That give the the error "master already exists"
This is what I remember from a couple of weeks of sitting with it for 30 min so it's not an exact list of steps to reproduce, but I think is close.

**Comment by ceedubs** [comment]
@ChrisPenner this is probably irrelevant now, right?

**Comment by mitchellwrosen** [comment]
@ceedubs yeah it is, closing
