### ISSUE TITLE
validateSandboxed false positives from closure context

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#3058]
The following is output from [this transcript](https://gist.github.com/ceedubs/d0a781269edb22545620e83efe1b8a3d).

# validateSandboxed false positives from closure context

The `pureStuff` function is pure, which `validateSandboxed` recognizes.

```unison
main1 : '{Exception, IO} ()
main1 = 'let
  pureStuff : '{} Nat
  pureStuff = '42
  isAllowed = validateSandboxed [] pureStuff
  if not isAllowed then bug ("not allowed", pureStuff) else ()
```

```ucm

  I found and typechecked these definitions in scratch.u. If you
  do an `add` or `update`, here's how your codebase would
  change:
  
    ⍟ These new definitions are ok to `add`:
    
      main1 : '{IO, Exception} ()

```
```ucm
.> add

  ⍟ I've added these definitions:
  
    main1 : '{IO, Exception} ()

.> run main1

```
If we extract `pureStuff` into a top-level term, then we can add a sandboxed operation (`Debug.trace`) to our main method while preserving the sandbox validation.

```unison
topLevelPureStuff : '{} Nat
topLevelPureStuff = '42

main2 : '{Exception, IO} ()
main2 = 'let
  isAllowed = validateSandboxed [] topLevelPureStuff
  if not isAllowed then bug ("not allowed", topLevelPureStuff) else ()
  Debug.trace "a sandboxed operation outside of topLevelPureStuff" ()
```

```ucm

  I found and typechecked these definitions in scratch.u. If you
  do an `add` or `update`, here's how your codebase would
  change:
  
    ⍟ These new definitions are ok to `add`:
    
      main2             : '{IO, Exception} ()
      topLevelPureStuff : 'Nat

```
```ucm
.> add

  ⍟ I've added these definitions:
  
    main2             : '{IO, Exception} ()
    topLevelPureStuff : 'Nat

.> run main2

```
However, if we add a sandboxed operation to our main method without extracting `pureStuff` into a top-level term, then the sandboxed operation causes a false positive in `validateSandboxed`.

```unison
main3 : '{Exception, IO} ()
main3 = 'let
  pureStuff : '{} Nat
  pureStuff = '42
  isAllowed = validateSandboxed [] pureStuff
  if not isAllowed then bug ("not allowed", pureStuff) else ()
  Debug.trace "a sandboxed operation outside of pureStuff" ()
```

```ucm

  I found and typechecked these definitions in scratch.u. If you
  do an `add` or `update`, here's how your codebase would
  change:
  
    ⍟ These new definitions are ok to `add`:
    
      main3 : '{IO, Exception} ()

```
```ucm
.> add

  ⍟ I've added these definitions:
  
    main3 : '{IO, Exception} ()

.> run main3

  💔💥
  
  I've encountered a call to builtin.bug with the following
  value:
  
    ("not allowed", ('42 : 'Nat))
  
  I'm sorry this message doesn't have more detail about the
  location of the failure. My makers plan to fix this in a
  future release. 😢

```

🛑

The transcript failed due to an error in the stanza above. The error is:

  💔💥
  
  I've encountered a call to builtin.bug with the following
  value:
  
    ("not allowed", ('42 : 'Nat))
  
  I'm sorry this message doesn't have more detail about the
  location of the failure. My makers plan to fix this in a
  future release. 😢

**Comment by ceedubs** [comment]
We are considering this to not be very high priority for the moment. But in the future we may want to address it.

**Comment by dolio** [comment]
Just to note: the reason this happens is that sandboxing information is only tracked for whole definitions with a codebase reference. Local sub-definitions don't have their status tracked individually. So any use of a denied function will taint the entire definition. It's probably possible to figure out each definition on its own, but it'd involve extra work.

Factoring the safe parts into their own definition is a work around in the mean time.

**Comment by dolio** [comment]
I think this is resolved by the recent top level floating changes, right?

**Comment by ceedubs** [comment]
@dolio yes! 🎉
