### ISSUE TITLE
Building easytest removeLink permission denied

### ISSUE THREAD

**Issue by philderbeast** [unisonweb/unison#3060]
From the readme "The build uses Stack". Would you accept a contribution to add a `cabal.project`?

I don't use homebrew to manage stack as described in the readme but use ghcup for that. I had previously been able to build unison but it is failing with the latest source, at d79e396c44665fc5dd963cda6c31695b464bf8d2.

```
> stack build easytest
easytest> build (lib + exe)
.stack-work/dist/x86_64-osx/Cabal-3.2.1.0/package.conf.inplace/
easytest-0.1-KCnEv2E8xRDLDbaYlI6kjn.conf:
removeDirectoryRecursive:removeContentsRecursive:removePathRecursive:removeLink:
permission denied (Permission denied)

--  While building package easytest-0.1 (scroll up to its section to see the error) using:
      /Users/.../.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.7
  --builddir=.stack-work/dist/x86_64-osx/Cabal-3.2.1.0
  build lib:easytest exe:runtests --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

I was able to build easytest with cabal.

```
> cat cabal.project
packages:
    yaks/easytest⏎

> cabal build easytest
Resolving dependencies...
Build profile: -w ghc-9.2.2 -O1
In order, the following will be built (use -v for more details):
 - easytest-0.1 (lib) (first run)
 - easytest-0.1 (exe:runtests) (first run)
Configuring library for easytest-0.1..
Preprocessing library for easytest-0.1..
Building library for easytest-0.1..
[1 of 1] Compiling EasyTest

src/EasyTest.hs:424:3: warning: [-Wnoncanonical-monad-instances]
    Noncanonical ‘return’ definition detected
    in the instance declaration for ‘Monad Test’.
    ‘return’ will eventually be removed in favour of ‘pure’
    Either remove definition for ‘return’ (recommended) or define as ‘return = pure’
    See also: https://gitlab.haskell.org/ghc/ghc/-/wikis/proposal/monad-of-no-return
    |
424 |   return a = Test $ do
    |   ^^^^^^^^^^^^^^^^^^^^...

src/EasyTest.hs:447:3: warning: [-Wnoncanonical-monad-instances]
    Noncanonical ‘pure = return’ definition detected
    in the instance declaration for ‘Applicative Test’.
    Move definition from ‘return’ to ‘pure’
    See also: https://gitlab.haskell.org/ghc/ghc/-/wikis/proposal/monad-of-no-return
    |
447 |   pure = return
    |   ^^^^^^^^^^^^^
Configuring executable 'runtests' for easytest-0.1..
Preprocessing executable 'runtests' for easytest-0.1..
Building executable 'runtests' for easytest-0.1..
```

```
> sw_vers
ProductName:	macOS
ProductVersion:	11.6.5
BuildVersion:	20G527
```

**Comment by philderbeast** [comment]
Here's the setup I built easytest with. I typically build projects in stack and cabal.

![Screen Shot 2022-04-27 at 10 05 42 AM](https://user-images.githubusercontent.com/633283/165537351-ebc043d2-4136-445b-beb1-ef9b6dc31cb7.png)

**Comment by philderbeast** [comment]
I had a quick look to see what I could build with cabal and ghc-8.10.7. Here's the `cabal.project` with packages roughly sorted by number of in-project dependencies. Commented out ones don't build as-is, because of megaparsec.

```
packages:
  yaks/easytest
  lib/unison-prelude
  codebase2/util-serialization
  codebase2/codebase-sync

  lib/unison-util-relation
  codebase2/util
  unison-core
  lib/unison-sqlite

  codebase2/core
  codebase2/codebase
  codebase2/util-term

  codebase2/codebase-sqlite

  lib/unison-pretty-printer

  -- parser-typechecker
  -- unison-share-api
  -- unison-cli
```

**Comment by aryairani** [comment]
Hi @philderbeast, we have `contrib/cabal.project` that is community-maintained but not officially supported.

We've seen errors like this before
```
removeDirectoryRecursive:removeContentsRecursive:removePathRecursive:removeLink:
permission denied (Permission denied)
```
which seem to be due to a bug in `stack` and/or Windows. But I see you're on macOS, correct?

What happens if you run `stack` again? Is there any chance you have two instances of stack running at the same time? Perhaps one through `haskell-language-server`?

Your `stack` provided by `ghcup` should be fine, as far as I know.

**Comment by philderbeast** [comment]
> But I see you're on macOS, correct?

Yes this is on macOS.

I rebooted and didn't open vscode for which I do have the Haskell extension that uses HLS. I had expected to be good to go after deleting `.stack-work` in the root of the repo but found plenty of other like folders, such as `/.../codebase2/util-term/.stack-work`. The permission denied error also gets to `stack clean`. I do think it is likely a bad interaction with HLS.

I got `stack build --fast --test` to work after deleting all `**/.stack-work/` folders.

**Comment by philderbeast** [comment]
> we have `contrib/cabal.project` that is community-maintained but not officially supported.

For anyone else looking, this is not in the unisonweb/contrib repo but in this repo at [`contrib/cabal.project`](https://github.com/unisonweb/unison/blob/trunk/contrib/cabal.project).
