### ISSUE TITLE
[Tech Debt] Dismantle "Command <-> Action" divide

### ISSUE THREAD

**Issue by ChrisPenner** [unisonweb/unison#3065]
Me, @aryairani  and @mitchellwrosen  agreed it's providing pretty limited value for the amount of pain it's causing. we can remove the command abstraction and make each action/command use the same shared monad.

We can investigate removing the Free monad at the same time, we're not really using it.

**Comment by pchiusano** [comment]
Yeah. 

I feel like MTL-ish typeclasses on a regular ol' monad would be good.
