### ISSUE TITLE
Empty file parse error

### ISSUE THREAD

**Issue by francisdb** [unisonweb/unison#308]
created a new file `foo.u` and got this in the console

```
master>
I expected a block after this (in red),, but there wasn't one.  Maybe check your indentation:
    1 |   SourcePos {sourceName = “/xxx/foo.u", sourceLine = Pos 1, sourceColumn = Pos 1}
```

**Comment by pchiusano** [comment]
@francisdb hold off on this one, I'm rejiggering the file parser at the moment and coincidentally noticed why this is happening and can fix. :)

A bit of explanation - the error is in [this parser](https://github.com/unisonweb/unison/blob/master/parser-typechecker/src/Unison/FileParser.hs#L33-L45). The file starts with an `openBlock` and ends with a `closeBlock`. The lexer also inserts `openBlock`/`closeBlock` tokens based on indentation / layout rules. But notice that the parser which expects the `close` block is [here, inside the term parser](https://github.com/unisonweb/unison/blob/master/parser-typechecker/src/Unison/FileParser.hs#L43). So an empty file, which has no terms or types, will have nothing to consume that closing token.

The fix (am pretty sure) is to move that `closeBlock` outside of the term parser (the term parser that is invoked can just have `pure ()` as its closing parser). That way, even if there are no terms or types in the file, the opening and closing tokens for the file will both be consumed.

**Comment by francisdb** [comment]
@pchiusano thanks for explaining this issue even if you are going to fix it! I have a hard time wrapping my head around this megaparsec code, let me look for something else to fix :-)

**Comment by francisdb** [comment]
This seems to be fixed, I'm getting a new `master> ` prompt but no parse error

**Comment by aryairani** [comment]
Maybe some kind of message about noticing an updated .u file with no definitions — or some no-op contingency to suppress the double prompt?  Leaning towards the former.
