### ISSUE TITLE
Have empty `push` not refer to deprecated GitUrl config key

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#3089]
possibly closed by #3080

**Comment by ChrisPenner** [comment]
Current behavior now:

* Checks for a `RemoteMapping` key in your config, if it finds that dict, try finding a matching path prefix there and use that.
* If it finds a `RemoteMapping` but no matching prefix, print an error indicating we don't know where to push
* If we don't find any `RemoteMapping` dict, fall back to the deprecated `GitUrl` behaviour.
