### ISSUE TITLE
Unison throws error when encountering free variables

### ISSUE THREAD

**Issue by francisdb** [unisonweb/unison#309]
```
master>
unison: can't hashComponents if bindings have free variables:
  ["Value"]
CallStack (from HasCallStack):
  error, called at src/Unison/ABT.hs:498:11 in unison-parser-typechecker-0.1-70XM7uuv7rV3opxGwr6csD:Unison.ABT
Well that didn't work.
Press any key to re-launch.
Shutting down runtime.

master>
```

I guess it should complain about these but not exit?

**Comment by aryairani** [comment]
Could you include a sample program for this one?

**Comment by francisdb** [comment]
This is already fixed

**Comment by anovstrup** [comment]
I encountered this issue in M1g.

A minimal way to reproduce it is to save a scratch file with
```
> v = 1
test> t1 = run (expect (v == 1))
```

This results in ucm exiting with the following message: 
```
ucm: can't hashComponents if bindings have free variables:
  ["User \"v\""]
  ["User \"t1\""]
CallStack (from HasCallStack):
  error, called at src/Unison/ABT.hs:599:11 in unison-parser-typechecker-0.1-3ssAWNgc3jPJasVcPbQb8J:Unison.ABT
```

For what it's worth, what I was trying to do was to reuse the same complex value (e.g., `Cons 1 (Cons 2 (Cons 3 (Cons 4 Nil)))`) in multiple tests, without having to add its definition to the codebase or repeat it over and over. I hoped that the value would be inlined in the test definitions, and part of why I had hoped it would work is that _watch_ expressions _are_ able to refer back to bindings specified in previous watch statements:

```
-- This works!
> v = 1
> v == 1
> run (expect (v == 1))
```

**Comment by anovstrup** [comment]
@aryairani I think this should be reopened.
