### ISSUE TITLE
Windows CI seems to rebuild all dependencies a lot

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#3101]
Not high priority, but the windows build seems to often rebuild all dependencies, whereas the other targets do not. 

<img width="911" alt="image" src="https://user-images.githubusercontent.com/11074/172229727-6c1d57cb-715d-40a0-99b1-90190fd26103.png">

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/11074/172229781-9e3f7c29-6391-4911-bca5-adbb32c36bba.png">

**Comment by aryairani** [comment]
closing this as not enough info (e.g. was the cache evicted that contained those pre-built dependencies?) / probably fixed. i did some stuff to save cache space and haven't noticed this recently
