### ISSUE TITLE
Implement string escaping

### ISSUE THREAD

**Issue by francisdb** [unisonweb/unison#311]
Currently string escaping is not implemented as can be seen in the example below

```
> "\""

```

```
master>
Token {payload = Err (TextLiteralMissingClosingQuote "\n\n"), start = Pos 25 6, end = Pos 25 6} :| []
/Users/francisdb/workspace/unison/unison-src/json.u:25:6:
unexpected TextLiteralMissingClosingQuote "\n\n"
   25 | > "\""
```

What needs to be escaped? (", \, unicode, tab, newline, ...)
Any example lexer that implements that?

to fix in [Lexer.hs](https://github.com/unisonweb/unison/blob/master/parser-typechecker/src/Unison/Lexer.hs)

**Comment by noahhaasis** [comment]
I implementing string escaping like in Haskell
\0 | U+0000 | null character
\a | U+0007 | alert
\b | U+0008 | backspace
\f | U+000C | form feed
\n | U+000A | newline (line feed)
\r | U+000D | carriage return
\t | U+0009 | horizontal tab
\v | U+000B | vertical tab
\" | U+0022 | double quote
\' | U+0027 | single quote
