### ISSUE TITLE
one too many `public.` in download modal

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#3132]
<img width="533" alt="image" src="https://user-images.githubusercontent.com/538571/174420264-d692b6be-09e4-49f5-8fe0-6513ece8ba0e.png">

**Comment by hojberg** [comment]
Thanks! 
@aryairani I'm going to move this to the share-ui repo.

**Comment by hojberg** [comment]
Closing here, and re-opening there. Transferring doesn't work cross org.
