### ISSUE TITLE
clicking on a type/ability constructor name loads an error

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#3133]
e.g.
https://share-next.unison-lang.org/users/pchiusano/code/latest/namespaces/public/distributed/trunk/;/types/lib/base/ANSI/Color
or
https://share-next.unison-lang.org/users/pchiusano/code/latest/namespaces/public/distributed/trunk/;/terms/Box/close

clicking on a constructor or request in the main pane produces an error
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/538571/174420812-f66b94bc-679a-46ad-ab35-4851557cddfd.png">

clicking on them in the navigation sidebar works fine.

**Comment by hojberg** [comment]
This should be fixed now.
