### ISSUE TITLE
Empty namespaces are shown in Unison Share and Unison Local

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#3134]
<img width="226" alt="image" src="https://user-images.githubusercontent.com/11074/174452566-5d1779e5-6d36-48a3-9861-4bb8483d1802.png">

We discussed in Slack, we think the backend should strip these out before sending JSON to the front end.

**Comment by hojberg** [comment]
The Share portion has been fixed, but this also appears in Unison Local.

**Comment by pchiusano** [comment]
Fixed by: https://github.com/unisonweb/unison/pull/3229
