### ISSUE TITLE
suggestion: add command to quickly create a codebase without starting the repl

### ISSUE THREAD

**Issue by aslilac** [unisonweb/unison#3137]
Something like `ucm new --with-base ./` that creates a codebase and then exits could be helpful

**Comment by pchiusano** [comment]
If you or anyone would like to have a go at this, https://github.com/unisonweb/unison/blob/trunk/unison-cli/unison/ArgParse.hs#L98 might be a good starting point, you could add another flag that says whether to exit after initialization.

**Comment by emilhotkowski** [comment]
Could I pick this up?

**Comment by mitchellwrosen** [comment]
@emilhotkowski Please! And feel free to join the public Discord to hang out or pair if you'd like a second pair of eyes. https://discord.gg/Ns6zzsDhaJ

**Comment by emilhotkowski** [comment]
We have two options to handle this functionality.
- We can add a flag to existing command/s to exit after initalization
- We can have totally separate command just for initalization of a codebase (similar to what @aslilac provided)

I'm looking for opinion from more Unison experienced devs!

**Comment by aryairani** [comment]
How do we feel about 
```
echo exit | ucm --codebase-create <directory>
```
?

these also work:
```
echo | ucm --codebase-create <dir>
ucm --codebase-create <dir> </dev/null
```

**Comment by emilhotkowski** [comment]
all of this works of course. The question is if we want to add something to make it easier for user to create codebase without bash tricks. If not then this issue can be closed, if we want we need to discuss approach.

**Comment by mitchellwrosen** [comment]
I'm kind of a fan of having the repl separate from a "utility tool" that maybe has some overlapping functionality.

For example, maybe `ucm` could always launch an interactive thing; if you say `ucm -c <codebase-that-doesnt-exist>`, it could ask, "want me to make that codebase now?"

And separately, `ucm-tool create-codebase <codebase>` could be the non-interactive variant that creates a codebase and communicate via exit code(s), not stdout.

(I also think this would push us in a direction of better interfaces for and programmability of the codebase in general, for externally developed tools)

**Comment by emilhotkowski** [comment]
Sounds good to me. If there is some task for a newbie in this let me know.

**Comment by aslilac** [comment]
> How do we feel about

Bad. 😅 That `echo "exit"` trick is what I'm already doing, and it just feels gross/arcane/unreadable.

**Comment by pchiusano** [comment]
@emilhotkowski Let's go with:

> We can add a flag to existing command/s to exit after initalization

So an `--exit` flag, which when combined with `--codebase-create` (and/or `--with-base` when that gets added at some point), exits after initialization. Otherwise ignored.

```
ucm --codebase-create /some/path --exit
```

I think some more general scriptability of ucm would be great but we can consider that out of scope here.

**Comment by emilhotkowski** [comment]
Great. I have a question about implementation details. Would you treat it as a global option? [There is a ](https://github.com/unisonweb/unison/blob/5edede3d43d5b69139a84b6a81ae9a2e233deb72/unison-cli/unison/ArgParse.hs#L242)`globalOptionsParser` that we could extend with another flag, namely `--exit`.

**Comment by pchiusano** [comment]
That seems okay to me.
