### ISSUE TITLE
`list` and `view` commands should support search/display of hash-qualified types

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#314]
See this comment: https://github.com/unisonweb/unison/commit/c14cbbfcd35a833d6ba14b993fe06607479074d4#r32141412

**Comment by aryairani** [comment]
Fixed in #354 IMO:
![image](https://user-images.githubusercontent.com/538571/53782016-6a138400-3ed9-11e9-9ea4-ff60e762ec67.png)
