### ISSUE TITLE
Collect syntax-related modules under `Unison.Syntax`

### ISSUE THREAD

**Issue by seagreen** [unisonweb/unison#3156]
This would be a preparatory step towards https://github.com/unisonweb/unison/issues/499, if we choose to do it.

The possible advantage of doing this as a first step is twofold:

1. It would make https://github.com/unisonweb/unison/issues/499 easier, "make the change easy, then make the easy change", yadda yadda.
2. On the off chance that we don't add a second syntax for awhile, we avoid the clutter of passing a `Syntax` record around in the meantime. Though due to (1) this still helps us even if we want to do that immediately.

Here's one way we could do the reorg:
```
renamed:    parser-typechecker/src/Unison/Lexer.hs -> parser-typechecker/src/Unison/Syntax/Lexer.hs
renamed:    parser-typechecker/src/Unison/Parser.hs -> parser-typechecker/src/Unison/Syntax/Parser.hs
renamed:    parser-typechecker/src/Unison/TermParser.hs -> parser-typechecker/src/Unison/Syntax/Parser/Term.hs
renamed:    parser-typechecker/src/Unison/TypeParser.hs -> parser-typechecker/src/Unison/Syntax/Parser/Type.hs
renamed:    parser-typechecker/src/Unison/Parsers.hs -> parser-typechecker/src/Unison/Syntax/Parsers.hs
renamed:    parser-typechecker/src/Unison/DeclPrinter.hs -> parser-typechecker/src/Unison/Syntax/Printer/Decl.hs
renamed:    parser-typechecker/src/Unison/NamePrinter.hs -> parser-typechecker/src/Unison/Syntax/Printer/Name.hs
renamed:    parser-typechecker/src/Unison/TermPrinter.hs -> parser-typechecker/src/Unison/Syntax/Printer/Term.hs
renamed:    parser-typechecker/src/Unison/TypePrinter.hs -> parser-typechecker/src/Unison/Syntax/Printer/Type.hs
```

Resulting in the module structure:
```
$ tree parser-typechecker/src/Unison/Syntax/
parser-typechecker/src/Unison/Syntax/
├── Lexer.hs
├── Parser
│   ├── Term.hs
│   └── Type.hs
├── Parser.hs
├── Parsers.hs
└── Printer
    ├── Decl.hs
    ├── Name.hs
    ├── Term.hs
    └── Type.hs
```

Though someone more familiar with the code could probably improve on that. I'll put some notes below with questions.[1]

Also, this would prepare us for even another incremental improvement before we get to https://github.com/unisonweb/unison/issues/499: we could use `Unison.Syntax` to define the interface we want in our eventual `Syntax` type (though in a module not in a type yet). Then we could switch the rest of the code over to only interact with the parser/prettyprinter through that interface, forbidding it to import anything from `Unison.Syntax.*` except for `Unison.Syntax` itself. That way when we do make a `Syntax` type the only thing to do will be to thread it around.

I'd suggest we save that for a later issue and PR though, not here.

What do you folks think?

[1] If we do go with this idea, here are my questions:
- `Unison.FileParser` probably go in `Unison.Syntax` as well, right?
- Should we rename `Unison.FileParsers` since it does a lot more than parsing like typechecking and evaluation?
- Should we go ahead and call this stuff `Unson.Syntax.Default` instead of `Unison.Syntax`? I don't have an opinion one way or another.
- I'm not sure if `Unison.Parser.Ann` is default-syntax specific, in which case it should be moved into the same module hierarchy as all the above, or will be used by all the syntaxes, in which case it should probably stay a level up.
- Also not sure what to do about `Unison.PrettyPrintEnv*` and `Unison.PrintError`. They're not moved in the above suggested changes, down to do whatever with them.

**Comment by seagreen** [comment]
Threw up a draft PR for this: https://github.com/unisonweb/unison/pull/3157

**Comment by mitchellwrosen** [comment]
This seems like a good start to me, and I do think it would be useful to separate the parser/lexer code out into a separate package, even if we don't go full pluggable-syntax. I might suggest leaving the modules names as they were, though - I'm not sure `Printer.Term` is much better than `TermPrinter`. Other than that I'm +1 -- well, I'm +1 either way -- what do others think?

**Comment by seagreen** [comment]
> I might suggest leaving the modules names as they were, though - I'm not sure `Printer.Term` is much better than `TermPrinter`.

Sounds great to me.

A possible next step in this cleanup is to have the `Unison.Syntax` module encapsulate its child modules, so that it's the only thing other parts of the code import or interact with, and the organization of its children is an internal detail of this subcomponent.

If we do that then the internal names won't matter much. However, that seems like all the more reason to leave them alone for now (`Unison.Syntax.TermPrinter` style), and let some future maintainer of the parser/prettyprinter adjust them if they want.

**Comment by seagreen** [comment]
> I do think it would be useful to separate the parser/lexer code out into a separate package

I'll let y'all decide if you want it to be a separate package or not (seems like a good idea to me, but depends on subtle recompilation and build tool details that I won't have perspective on here). This issue/PR would certainly make pulling it out into a separate package easier if you decide to go that route.
