### ISSUE TITLE
`resolve-edit` command for resolving edit conflicts

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#317]
Examples:

    > resolve-edit foo#2hd foo#2893
    > resolve-edit foo bar

If the `foo` symbol is currently conflicted, this picks a winner, using `Branch.resolveNamedTermConflict` or `Branch.resolveNamedTypeConflict`. The winner can be any definition. 

Should do a `propagate` afterwards as picking a winner can allow for further propagation.

**Comment by runarorama** [comment]
Is this still relevant? How do you get into a conflicted state, and what does it mean to resolve it?

**Comment by pchiusano** [comment]
It’s still relevant. If Alice and Bob both update foo in different ways, then merge their namespaces, it shows up as an edit conflict and the todo command will report it as such.

Currently there is no command to reconcile edit conflicts, so this will definitely have to be implemented at some point. 😀

Conceptually, this is just deleting all outgoing edges from the source (first arg) and then adding an edge to the edit graph from the first arg to the second.

The comment about doing a patch / propagate is still relevant too.

**Comment by runarorama** [comment]
Resolved by #830
