### ISSUE TITLE
Switch to use Unison Local over Codebase UI

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#3186]
[codebase-ui](https://github.com/unisonweb/codebase-ui) has been deprecated in favor of [unison-local-ui](https://github.com/unisonweb/unison-local-ui)

- [x] Use unison-local-ui instead of codebase-ui
- [x] Bring unison-local-ui up to date with latest [ui-core](https://github.com/unisonweb/ui-core).
- [x] Update "publish on share" modal in unison-local-ui
- [x] Add a place for docs and language reference links
- [x] Re-enable sidebar collapse
- [x] Find a place for "help" and "bug" reporting links.
- [x] Fix sidebar header overflow issue

**Comment by aryairani** [comment]
Cool!

**Comment by hojberg** [comment]
All set
