### ISSUE TITLE
Migrate codebases to share-next

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#3205]
- [x] website
- [x] http
- [x] async
- [x] spark article upgrade to latest distributed

**Comment by aryairani** [comment]
What does this task mean, publish them on Share-Next? or publish them on Github with latest codebase? (or both)

**Comment by pchiusano** [comment]
http and async should move over to share-next

not sure about website. I'd say move it over to share next but if we have some build process that we want to keep pulling from github for now, then we could do the website later

**Comment by hojberg** [comment]
http is moved over, but missing a dependency (parsing) still.

**Comment by hojberg** [comment]
Done :)
