### ISSUE TITLE
Blog post on M4 release

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#3207]
Should include:

* Some graphic hero shot
* Video about Share Next
* And pushing
* Mention of new stuff - unboxed arrays, mutable and immutable, text matching primitives, doc improvements, performance improvements, the list goes on - link to release notes
* What do I need to do to get my stuff on share?
* What happens with old-share? Note about grace period
* CTA: sign up here

**Comment by aryairani** [comment]
Here's what I mined out of the PR list:

- Loads of bugfixes, performance improvements, UI improvements
- Unison Share code hosting
- Self-contained namespaces
- New builtins
    - https://github.com/unisonweb/unison/pull/3029
    - https://github.com/unisonweb/unison/pull/3068
    - https://github.com/unisonweb/unison/pull/3126
    - https://github.com/unisonweb/unison/pull/3104
    - https://github.com/unisonweb/unison/pull/3146
    - https://github.com/unisonweb/unison/pull/3173
    - https://github.com/unisonweb/unison/pull/3178
- New syntax
    - https://github.com/unisonweb/unison/pull/3135

**Comment by aryairani** [comment]
https://share.unison-lang.org/@runarorama/code/latest/terms/public/blog/draft/m4Post
