### ISSUE TITLE
add force push command for share

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#3214]
A `push.force` command that uses the push with lease api, along with a server-side reflog. I suppose the reflog should go into postgres (though it could go into sqlite if we don’t mind changing the server-side schema), and include `codebase_id`, `old_root` (causal hash id), `new_root` (causal hash id), `push_path`, `push_type` (fast-forward / forced).

edit: and `timestamp`

**Comment by pchiusano** [comment]
I marked this as nice-to-have. Don't want to hold up M4 just for this, but sure, if you can get it in then sounds good.

**Comment by hojberg** [comment]
would love for this reflog to be accessible in a history api as well with timestamps.

**Comment by aryairani** [comment]
@pchiusano I think we should hold up M4 for this; let's chat Monday

**Comment by aryairani** [comment]
We can discuss whether to postpone the reflog (which @hojberg yes we should expose) but since users can't blow away their own codebases or create arbitrary new ones on share-next like the could on github, I think a force push is essential functionality. My bad for not making it visible in earlier conversations / task tracking though.

**Comment by pchiusano** [comment]
Closed by: https://github.com/unisonweb/unison/pull/3222
