### ISSUE TITLE
Weird type inferred for ability handler

### ISSUE THREAD

**Issue by ThisFunctionalTom** [unisonweb/unison#3215]
Giving unison the code below without the type for `Stack.handler` it infers a weird type with repeating `Stack a`.

![image](https://user-images.githubusercontent.com/3315570/178157511-816ee16c-3946-41f6-b837-08dd48dfd552.png)

Removing the command and giving the correct type everything looks fine.

![image](https://user-images.githubusercontent.com/3315570/178157533-4bb82201-bf1e-48fd-b07b-134a86513b46.png)

```unison
structural ability Stack a where
  push : a -> ()
  pop : ()
  peek : Optional a
  isEmpty : Boolean

--Stack.handler: [a] -> Request {g, Stack a} r -> {g} r
Stack.handler stack = cases
    { push a -> cont } -> handle !cont with handler (a List.+: stack)
    { pop -> cont } -> handle !cont with handler (List.tail stack |> Optional.getOrElse [])
    { peek -> cont } -> handle cont (List.head stack) with handler stack
    { isEmpty -> cont } -> handle cont ([] === stack) with handler stack
    { r } -> r

Stack.run : '{Stack a } r -> r
Stack.run stackFunc =
  handle !stackFunc with Stack.handler []
```

UCM Version (Windows):
ucm.exe version: release/M3 (built on 2022-03-07)

**Comment by pchiusano** [comment]
Thanks for reporting!
