### ISSUE TITLE
Update DNS: share becomes share-prev, share-next becomes share

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#3219]
Todo:

- [x] create share-prev.unison-lang.org, have that go to same place as current share
- [x] modify share.unison-lang.org to point to same place as current share-next
- [x] add a redirect from share-next.unison-lang.org to share.unison-lang.org in case anyone is hitting share-next urls
- [x] confirm: do `push` and `pull` commands work with this config?
- [ ] confirm: what about default location where `base` is fetched from? try creating a fresh empty repo
- [ ] confirm: are links on website okay?

**Comment by hojberg** [comment]
I think this can be closed @pchiusano @aryairani ?
