### ISSUE TITLE
Add Text pattern matching

### ISSUE THREAD

**Issue by francisdb** [unisonweb/unison#323]
In general working with Text is currently quite limited but a pattern match on Text would help.

```
case x of Some "{" -> ...

unexpected "{"
expecting (, blank, false, symbol, or true
```

In case this will take a while to be implemented a "Pattern matching on Text not yet available" error might be a good temporary fix.
A current workaround is using if `else if else ...`

Will text be seen as some kind of sequence in the future? Otherwise #266 could fix the issue.

**Comment by francisdb** [comment]
Already tried that but it didn't work

```
f blah =
  case blah of
    x | x == "woot" -> false
    y | y == "foo" -> true
```

```
master> 
I'm not sure what x means at line 135, columns 9-10

  135 |     x | x == "woot" -> false

Whatever it is, it has a type that conforms to Text.
```

**Comment by aryairani** [comment]
@francisdb Would you add that last comment as a separate issue? :)

**Comment by francisdb** [comment]
@aryairani #327

**Comment by aryairani** [comment]
An implementation would begin in [Pattern.hs](https://github.com/unisonweb/unison/blob/wip/rt1/parser-typechecker/src/Unison/Pattern.hs).

**Comment by francisdb** [comment]
This has been implemented in the Haskell runtime
