### ISSUE TITLE
frequent "database locked" race condition during [at least] `pull`

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#3235]
![image](https://user-images.githubusercontent.com/538571/178859315-794cccd4-b8ab-452d-8db3-dd6b4a0e1070.png)

Log error:
```
13/Jul/2022:20:26:45 +0000 Error  SqliteQueryException {sql = "SELECT id FROM hash WHERE base32 = ? COLLATE NOCASE", params = "\"39dvhen1p6smk247mobauhs2qn6n3vbfu64kc0ac61tti8n2blioqds39990n891d0mcrbkstk8787t9471kihu569j427e7aq3jtro\"", exception = SQLite3 returned ErrorBusy while attempting to perform prepare "SELECT id FROM hash WHERE base32 = ? COLLATE NOCASE": database is locked, callStack = [], connection = Connection { name = "U-a29b719d-4429-4861-aa55-006cb492ce3f", file = "codebases/U-a29b719d-4429-4861-aa55-006cb492ce3f/.unison/v2/unison.sqlite3" }, threadId = ThreadId 22484}
CallStack (from HasCallStack):
  logError, called at src/Enlil/Utils/Errors.hs:40:3 in enlil-0.1.0.0-CyNiNHGP5AeJeLQFN60mcf:Enlil.Utils.Errors
  respondError, called at src/Enlil.hs:68:26 in enlil-0.1.0.0-CyNiNHGP5AeJeLQFN60mcf:Enlil
13/Jul/2022:20:26:44 +0000 Error method="POST" path="/sync/entities/download" requestID="06caf12b-3e8e-41e0-8e73-996bb4cfe3be" responseTimeMs=1.936264 status=500 userAgent="UCM/release/M3-686-gb3dd558e9" 
```
With the key phrase being "ErrorBusy" / "database is locked" aka `SQLITE_BUSY`.

By running enlil locally with `UNISON_DEBUG=sqlite`, redirected to a file, I confirmed that no `INSERT` or `UPDATE` sql statements are being run during my pulls, only read-only selects. (unless there can be selects in a write transaction.)

**Comment by aryairani** [comment]
@ChrisPenner suggested a possible connection to this:

> When the last connection to a particular database is closing, that connection will acquire an exclusive lock for a short time while it cleans up the WAL and shared-memory files. If a second database tries to open and query the database while the first connection is still in the middle of its cleanup process, the second connection might get an [SQLITE_BUSY](https://www.sqlite.org/rescode.html#busy) error.

https://www.sqlite.org/wal.html

In which case, we just need to retry a little before giving up.

**Comment by pchiusano** [comment]
Given how infrequently this seems to happen (I've yet to hit it myself), I think it's not the worst thing for this to be a known issue for M4, especially if the mitigation is "try again", which user can do manually.

That said it doesn't seem too hard to add a retry or two.

**Comment by mitchellwrosen** [comment]
Hmm, weird. I don't think that explains the SQLITE_BUSY, though - you can see in the error message we trying to prepare this statement.

```
SELECT id
FROM hash
WHERE base32 = ? COLLATE NOCASE
```

**Comment by aryairani** [comment]
@pchiusano Try with a new codebase? It comes up like crazy for me when pulling base for the first time, and there’s no obvious way to retry that. I’m guessing that it is more likely now that we have parallel downloads, but maybe not for small incremental pulls.

**Comment by aryairani** [comment]
(The automatic base download, where they didn’t enter the command)

**Comment by aryairani** [comment]
We could rewrite the welcome flow with a retry command, or maybe better yet add one to the 500 error output

**Comment by pchiusano** [comment]
@aryairani okay yeah. Let’s get this done then for M4.

**Comment by aryairani** [comment]
@pchiusano Here's my dramatic screenshot :) @tstat and @mitchellwrosen and I have a fix on the way.
<img width="555" alt="image" src="https://user-images.githubusercontent.com/538571/178998725-5f705f5d-b7cf-48a8-be37-8bd77c525af8.png">

**Comment by tstat** [comment]
fixed by https://github.com/unisonweb/unison/pull/3237
