### ISSUE TITLE
Can't delete namespace 

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#3241]
This occurred earlier in a Discord call when trying to delete a top-level namespace ,`learn`. The UCM prohibited us from deleting `learn` because terms __inside__ learn referenced other terms __inside__ learn? We were not certain why the operation was prohibited. 

A copy of the namespace we were trying to delete is at: 

```
pull git(git@github.com:rlmark/homeBase4)#j06d8qonot
```

<img width="1092" alt="Screen Shot 2022-07-14 at 10 32 18 AM" src="https://user-images.githubusercontent.com/7613551/179087411-6807137f-b689-441c-aafb-239c024cbb46.png">

**Comment by aryairani** [comment]
@rlmark Sorry for the delay. I wasn't able to reproduce this today, but also not sure if I was recreating the scenario correctly. Here's what I tried:

```
/tmp % git clone git@github.com:rlmark/homeBase4
/tmp % ucm -c homeBase4
<migration>

.> ls

  nothing to show

.> reflog

  ⚠️
  
  The reflog is empty
```

Hmm. (long code block below, need to scroll to the bottom of it)

```
.> fork #j06d8qonot learn

  Done.

.> ls learn

  1.  _sidebar            (Doc)
  2.  atAGlance           (Doc)
  3.  atAGlance/          (2 terms)
  4.  contributeDocs      (Doc)
  5.  delayGreet          ('Text)
  6.  exercises/          (36 terms, 1 type)
  7.  fundamentals/       (194 terms, 21 types)
  8.  glance/             (29 terms, 3 types)
  9.  glossary/           (30 terms)
  10. greet               (Text -> Text)
  11. helloWorld          ('{IO, Exception} ())
  12. index               (Doc)
  13. index/              (1 term)
  14. installInstructions (Doc)
  15. labs/               (136 terms, 8 types)
  16. languageReference/  (96 terms, 6 types)
  17. lib/                (3584 terms, 188 types)
  18. patch               (patch)
  19. quickstart          (Doc)
  20. quickstart/         (1 term)
  21. theBigIdea          (Doc)
  22. theBigIdea/         (1 term)
  23. todo/               (2 terms)
  24. tooling/            (4 terms)
  25. tour                (Doc)
  26. tour/               (5 terms)
  27. ucmCommands/        (65 terms)
  28. usageTopics/        (6 terms)
  29. utils/              (13 terms)

.> delete.namespace learn
<slowww>


  Done.

.> 
```

Basically either it's been fixed, or I'm not recreating the scenario right. What do you think?

**Comment by aryairani** [comment]
I'm going to tentatively close this, but feel free to reopen if you run into it again.
