### ISSUE TITLE
can't dismiss share welcome modal on mobile

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#3245]
![image](https://user-images.githubusercontent.com/538571/179325258-fb0af380-85a5-4859-acc0-9a90aac07880.png)
Same behavior on iOS Firefox, Chrome, Edge (Canary)

**Comment by hojberg** [comment]
Deployed a fix to make this slightly better. It should be usable now, but not pretty.

**Comment by hojberg** [comment]
This is fixed now.
