### ISSUE TITLE
Provide a tip for how to resolve `base` not being available in namespaces

### ISSUE THREAD

**Issue by bgerm** [unisonweb/unison#3246]
After migrating to M4 I received the error message provided below.

It would be helpful to add a tip for how to resolve `base` not being available.  Maybe include some background and then a resolution: `fork .base lib.base`.

```
.exercism.track>


    ❓

    I couldn't resolve any of these symbols:

        4 | unique type Error = Error Text


    Symbol   Suggestions

    Text     No matches
```

**Comment by aryairani** [comment]
Hi @bgerm, we're moving to a projects-oriented codebase, and `base` is installed by default into any new project, so that should avoid this issue. Feel free to reopen this ticket or a new one if you have any concerns.
