### ISSUE TITLE
Improve behavior when updating files containing unique types

### ISSUE THREAD

**Issue by bgerm** [unisonweb/unison#3247]
When resaving the code with unique types in a new ucm instance I get an unexpected result when I call `set` on the record type.

> Either Account.active.set should behave as if it’s the one you’re about to add, or the unique type Account should just become the same one you’ve already added, when everything matches. (I think this is how we were planning to address it.)
-- Arya Irani
 
Code:

```
unique type Account = {
  active: Boolean
}

activate account =
  Account.active.set true account

> activate (Account false)
```

Result:

```
  The 1st argument to `activate`

            has type:  Account
      but I expected:  Account#2j43viac7s

      1 | unique type Account = {
      .
      8 | > activate (Account false)
```

**Comment by aryairani** [comment]
@bgerm Sorry for the delayed response; I'm unable to reproduce this today.

```
    8 | > activate (Account false)
          ⧩
          Account true
```

Don't hesitate to reopen this ticket or a new one if you have any more issues.
