### ISSUE TITLE
Add Unison syntax highlighting on GitHub

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#325]
It would be nice if `.u` files could get highlighted as Unison code on GitHub, and also if fenced code blocks could use Unison as the language. Would anyone like to volunteer to:

a) See what is involved in making this happen and tell us about it here
b) Make it happen :)

The language is still under flux, so it would be good if we have a streamlined way of submitting updated syntax highlighting spec changes for the language.

**Comment by francisdb** [comment]
You do this by creating a PR in this project
https://github.com/github/linguist

but

> We try only to add new extensions once they have some usage on GitHub. In most cases we prefer that extensions be in use in hundreds of repositories before supporting them in Linguist.

So I would put this on hold

**Comment by aryairani** [comment]
I wonder, if we asked nicely...

**Comment by francisdb** [comment]
Seems to be using TextMate (tmbundle), sublime or Atom/VSCode syntax highlighting bundles
https://flight-manual.atom.io/hacking-atom/sections/creating-a-grammar/

So better start with that if not already available

**Comment by pchiusano** [comment]
We are going to close this one in favor of having a proper Unison codebase browser, which can read the repo format and render hyperlinked, pretty-printed code on demand! This is a better experience than having GitHub render some syntax-highlighted text anyway.

**Comment by francisdb** [comment]
see also https://github.com/seagreen/unison-code-explorer
