### ISSUE TITLE
regression of haskeline prompt in windows 11

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#3250]
Windows Terminal on the left, the standard Console Host on the right:

<img width="1315" alt="image" src="https://user-images.githubusercontent.com/538571/179416271-8f811cc1-a5ee-428c-b4f6-6754f092c7f8.png">

**Comment by ceedubs** [comment]
@aryairani is #3275 a duplicate of this? If so I'd be inclined to close this issue because the other one has more information.

**Comment by aryairani** [comment]
Sure. This one also has more information, but they are duplicates :)
