### ISSUE TITLE
Atom/VSCode syntax highlighting

### ISSUE THREAD

**Issue by francisdb** [unisonweb/unison#326]
https://flight-manual.atom.io/hacking-atom/sections/creating-a-grammar/

Underlying lib is [Tree-sitter](http://tree-sitter.github.io/tree-sitter) which also has Haskell bindings and could be used for docs

This is also a requisite for #325

Looks like a good starting point would be https://github.com/tree-sitter/tree-sitter-haskell
But the state of that repo is till [`in development`](https://github.com/tree-sitter/tree-sitter-haskell/issues/25#issuecomment-446350616)

**Comment by aryairani** [comment]
I started on a tree-sitter grammar for Unison but I didn’t really know what I was doing, and didn’t get too far.  Would be happy to try to collaborate with someone though.

**Comment by francisdb** [comment]
@aryairani let's see if I know what I'm doing :-)

**Comment by francisdb** [comment]
I'm giving up for now, this is non-trivial and their own [tree-sitter-haskell](https://github.com/tree-sitter/tree-sitter-haskell) is not even compiling / passing tests currently.

**Comment by aryairani** [comment]
Hah, that was fast.  No worries!

**Comment by pchiusano** [comment]
It sounds like Atom still uses TextMate grammars as well still, and tree sitter is the new way of doing things. I kinda think the textmate style grammar would be ok for now.

Re: tree sitter, it seems like the thing to do is define the grammar in JS, which is then compiled to C by tree sitter: http://tree-sitter.github.io/tree-sitter/creating-parsers

So maybe there’s no need to use the Haskell bindings for tree sitter? I took a quick look at those Haskell bindings and they are insanely low level and not something you’d want to use anyway, even if it worked.

The docs I linked to above make it seem pretty straightforward to create a grammar. The one thing I’m not sure about is how to do Unison’s indentation-based syntax. Maybe find a Python tree-sitter grammar and use that as inspiration.

**Comment by pchiusano** [comment]
Here’s the Python grammar: https://github.com/tree-sitter/tree-sitter-python/blob/master/src/grammar.json

**Comment by francisdb** [comment]
I tried to get something basic going thing morning and the test errors I got were anything but helpful. Might revisit this later.

You need a (modified?) native scanner like
https://github.com/tree-sitter/tree-sitter-haskell/blob/master/src/scanner.cc
or
https://github.com/tree-sitter/tree-sitter-haskell/blob/master/src/scanner.cc
(make sure the C exported functions have the correct name)

and point to them in your grammar
https://github.com/tree-sitter/tree-sitter-haskell/blob/master/grammar.js#L76

**Comment by francisdb** [comment]
How far did you get @aryairani ?

**Comment by francisdb** [comment]
Looks like these are both more or less available?

https://github.com/unisonweb/unison/tree/master/editor-support/atom/language-unison
https://github.com/BenFradet/vscode-unison

**Comment by aryairani** [comment]
Wow, cool!  Looks like mine and @benfradet’s both need “effect” replaced with “ability”, but pretty awesome that someone has made a vscode plugin.

**Comment by BenFradet** [comment]
cool, will update, I haven't dove into the language yet because I wanted syntax highlighting first, kind of a chicken and egg issue.

**Comment by aryairani** [comment]
@benfradet Please don’t hesitate to bug us (here or on gitter or however you like) if you need anything.  Super excited to know about early adoption.
