### ISSUE TITLE
Add command which explains how to set up environment variables to provide credentials to Cloud

### ISSUE THREAD

**Issue by ChrisPenner** [unisonweb/unison#3261]
The Cloud ability needs user credentials to submit jobs, rather than hard-code a specific token which might expire and need to be updated we instead provide the path to a credentials file (I believe google cloud console does something similar for its auth).

Users still need to expose their credentials path via an environment variable (but @ceedubs  is going to have the executable search a few probably locations for it if an env var isn't set).

Ideally we'd have a command which just prints out the env var that users need to add to their bash profile/rc

If the code which attempts to find the credentials file works well then this feature becomes less necessary, but is something we should still probably have eventually.

**Comment by ChrisPenner** [comment]
@ceedubs  is something like this still necessary? Seems like the default search paths have worked well for us so far?

**Comment by ceedubs** [comment]
@ChrisPenner I think that we can close this out. I don't really recall why we originally thought that we would want a ucm command for this, but this is something that we should be able to do completely on the `cloud.run` side. If we can't find the needed credentials we can just print an error that tells the user what to do.
