### ISSUE TITLE
More seamless push

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#3270]
typing in manual push destinations is annoying
adding things manually to your config is annoying

what I want:

I type `push blah`

It remembers that push destination in my config, and associates it with that path (and it gives me a friendly message "I've set `blah` as the default push destination for this namespace. Now you can `push` with no arguments if you just want to push there again."). I don't need to manually edit a config file.

If I push with no arguments, it suggests using the default for that path. ("Would you like me to push to the default `blah`? Either repeat the `push` command or `push.default` to push to the default destination without confirmation.")

If there's no default, it checks the parent, recursively, until finding a default or bailing with a nice message ("Sorry, there's no default push destination that I can find. Try `help push` to view syntax for pushing to different destinations"). 

If it finds a default in some parent, it pushes to the same relative path. So if I'm in `distributed.topics.blah` and do a push, it will find a default push location at `distributed` and then push to `<defaultloc>.topics.blah` (again with same confirmation step)

**Comment by aryairani** [comment]
I believe `push` has changed enough to be unrecognizable in the context of this ticket. Feel free to reopen if you disagree.
