### ISSUE TITLE
move reflog into database

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#3271]
and prompt to delete file that is in everyone’s home dir, whoops

**Comment by aryairani** [comment]
Instead of a prompt and deletion, we can just put it into the release notes.

**Comment by ChrisPenner** [comment]
https://unisonlanguage.slack.com/archives/C03MY5TMKT6/p1661376576351379

Had some conversation in the public slack; the rough plan is:

* Undo tree and reflog are separate things
* Reflog is a linear list of (timestamp, root-namespace-hash)
  * This reflog can be used for codebase history/push metrics on share.
* Undo tree is a _tree_ of (undoID, timestamp, root-namespace-hash, parentUndoID)
  * This allows undo/redo, and also allows deeper analysis if desired

**Comment by aryairani** [comment]
#3364 implements the local/ucm move into the database
~~this ticket can be repurposed for the share version~~
