### ISSUE TITLE
`patch` command should ignore `lib` subnamespace

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#3273]
A typical process is you update one of your dependencies, then want to apply the patch from its new release to your codebase. Like you'd type `patch lib.something.shiny_new_version.patch` at your project root.

That does not necessarily mean you want to apply that patch to all the stuff in `lib`. For that you could `cd` into `lib`.

**Comment by ceedubs** [comment]
I just noticed something related. If you run `replace foo bar` you end up with todo items within your `lib` namespace. This probably boils down to the same issue, but I thought that it would be worth explicitly calling out `replace` behavior for whomever works on this and writes test transcripts.
