### ISSUE TITLE
Logging out of Unison Share should redirect back to Share

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#3282]
Currently, when logging out of Share, a `Successfully logged out.` message is rendered without the context of the Share UI and feels out of place.

Instead we should redirect to something like `https://share.unison-lang.org?ation-taken=logged-out`

**Comment by hojberg** [comment]
cc @ChrisPenner @aryairani

**Comment by ChrisPenner** [comment]
Sounds good to me 👍🏼
