### ISSUE TITLE
stew's codebase takes 60 seconds to start

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#3290]
4GB of ram to get to a prompt
Ping @stew for a copy of his database.

Pin down what's happening

**Comment by ChrisPenner** [comment]
Some assorted notes on this:

```
.> ls

  1.  ansi/          (49 definitions)
  2.  asteroids/     (54023 definitions)
  3.  bankers/       (2491 definitions)
  4.  base/          (2457 definitions)
  5.  binary/        (154 definitions)
  6.  cloud/         (57165 definitions)
  7.  codec/         (4147 definitions)
  8.  consul/        (36 definitions)
  9.  crypto/        (12 definitions)
  10. datetime/      (318 definitions)
  11. demo/          (10972 definitions)
  12. distributed/   (19459 definitions)
  13. dns/           (207 definitions)
  14. enlil/         (26 definitions)
  15. exercism/      (22229 definitions)
  16. fuckstributed/ (19961 definitions)
  17. guid/          (8 definitions)
  18. histogram/     (91 definitions)
  19. http/          (4793 definitions)
  20. json/          (18763 definitions)
  21. labs/          (40 definitions)
  22. lib/           (6403 definitions)
  23. logging/       (40 definitions)
  24. metrics/       (69 definitions)
  25. nimbus/        (14976 definitions)
  26. parser/        (979 definitions)
  27. projects/      (18360 definitions)
  28. redis/         (14 definitions)
  29. share/         (108863 definitions)
  30. stew/          (43768 definitions)
  31. tmp/           (5905 definitions)
  32. toml/          (1 definition)
  33. turtle/        (2907 definitions)
  34. uuid/          (11 definitions)
```

This adds up to 419697 total definitions; mostly it's multiple copies of base spread around in many projects, but we aren't getting much sharing on these.

After loading the prompt, an initial `ls` hangs for a while, and memory usage almost doubles, presumably this is forcing thunks. The implementation for `ls` generates a pretty printer for the entire root, then suffixifies according to location.

Since we include definition count of each child, it also forces the deepTerms/deepTypes of every child.

**Comment by pchiusano** [comment]
Related observation I made in Slack - 

> interesting data - if I do a find at the root (which fully forces the root branch), memory usage goes from 250MB to 4GB. My tree has about 120k names in it. Not sure how many unique hashes, likely much less.

> I have a hypothesis. deepTerms/types is defined recursively via a cons onto the deep terms 1 level below, so a definition 10 levels deep will be in 10 different stars. Initially, those won’t be forced, but if you cd into a namespace and typecheck anything, they will be to (to resolve names). That’s 10x the memory usage necessary - we shouldn’t bother keeping around the deep terms of all those intermediate levels if the user never cds into them.

> If instead we define deepTerms/types as regular recursive fns that go all the way to leaves, then we don’t keep all those useless intermediate stars around.

**Comment by ChrisPenner** [comment]
I’m noticing we’re not really doing anything to enforce sharing right now, so if we have 300 copies of base (which Stew seems to) they seem to each be hydrated into their own unique Branch type. This means 300x the memory usage, but also it means the work for forcing its thunks (deepTerms/deepTypes) isn’t shared either; so 300x the work there, and 300x the sqlite queries and deserializations. Would be a big win to fix this given the duplication inherent in the new lib structure.
Would be as easy as having a CausalHash -> m (Branch m) cache lookup I think, I’ll probably try that out on Stew’s codebase.

Could probably store Weak references in the cache and use finalizers to remove themselves when they go out of scope; then we could use a cache for most values we’re loading from sqlite. Will take a bit of experimentation to find the right balance

**Comment by stew** [comment]
btw, @aryairani anyone on your team can get this codebase via scp if they are on tailscale:

`scp -r nobody@100.92.219.97:.unison /tmp/`
