### ISSUE TITLE
Opening up `Void` by hash generates an error

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#3292]
Steps to reproduce: 

Go to: https://share.unison-lang.org/@unison/code/latest/namespaces/public/base/latest/;/terms/Void/absurd

Click on `Void` there in the type signature.

This seems to crash Share, bringing it down until the container gets restarted (about 30s or so).

Oddly enough visiting https://share.unison-lang.org/@unison/code/latest/namespaces/public/base/latest/;/types/Void (loading it by name) works totally fine.

**Comment by pchiusano** [comment]
Same issue is present in local UI, just noticed.

Possibly a dupe of #2139

**Comment by mitchellwrosen** [comment]
Oh dear... I tracked this down... :see_no_evil: 

https://github.com/unisonweb/unison/blob/7f58e60cddf90fdcfebf95e3cab2fb4e7ec5c1a0/codebase2/codebase-sqlite/U/Codebase/Sqlite/Operations.hs#L982

This and all other instances of `0 - 1` at type `ConstructorId` (alias for `Word64`) are (obviously) wrong.

**Comment by pchiusano** [comment]
Good sleuthing. Though why does the other way of viewing the definition work okay? Using https://share.unison-lang.org/@unison/code/latest/namespaces/public/base/latest/;/types/Void
