### ISSUE TITLE
names.global false negatives

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#3294]
Sometimes `names.global` can't find types (and probably also terms?) that definitely exist. I'm having trouble creating a minimal example of this, but I see it with the following setup:

- `trunk` ucm build (I'm at commit 7f58e60cd).
- `pull git(https://github.com/unisonweb/share).stew.parser .stew.parser`
- `cd emptynamespace`

As you see below, `names.global` doesn't find the `Error` type even when provided an absolute path. `view` finds it just fine.

```
.emptynamespace> names.global .stew.parser.trunk.Error                                                                                                              
 
  😶
  
  I couldn't find anything by that name.

.emptynamespace> view .stew.parser.trunk.Error        
 
  unique type stew.parser.trunk.Error e t
    = FancyError Parser.Location (Set (ErrorFancy e))
    | TrivialError Parser.Location (Optional (ErrorItem t)) (Set (ErrorItem t))
```

**Comment by ChrisPenner** [comment]
I haven't looked at this yet, but I'm guessing we probably just need to explicitly use the global PPE or names object for this or something, I think I did something similar when swapping `view` to be local;

I'll try to take a look at this in the coming week or two 👍🏼 

Once again, thanks for providing a reproduction!
