### ISSUE TITLE
can we speed up windows CI?

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#3298]
This currently adds 1+ hrs to CI checks.

Related to #3101

**Comment by ChrisPenner** [comment]
I've made a few attempts: 

Initially here: https://github.com/unisonweb/unison/pull/3168

Then, since that didn't help as much as expected, here: https://github.com/unisonweb/unison/pull/3176 ; 

I'm not really sure why #3176 didn't help.

**Comment by ChrisPenner** [comment]
I tried running https://github.com/unisonweb/unison/pull/3176 again and it turns out it actually does work, I just forgot to warm up the cache first haha.

It takes builds down from ~1hr to ~20mins, still room for improvement, but much better 🙌🏼

**Comment by ceedubs** [comment]
As @ChrisPenner said, #3176 brings these down to 20 minutes. The last macos build time was 14 minutes, so there are diminishing returns on optimizing the Windows build time. I'm going to close this issue out as "good enough for now", but we can always come back to it in the future if it's still a source of pain.
