### ISSUE TITLE
Hide denominator of entities pushed/pulled

### ISSUE THREAD

**Issue by mitchellwrosen** [unisonweb/unison#3311]
We decided it'd be better with just the numerator

**Comment by aryairani** [comment]
Just thinking about this again.  If we had a known numerator, this would work again, and possibly be helpful. We could cache the full number of dependencies with each Causal hash; both on the server and the client. The client can then easily say something like 
`Synced 17 new and 6782 old entities, out of 6799.` 
or
`Downloaded 6799/6799 entities (skipped 6782)` (count downloaded + skipped in the numerator)
or 
`Downloaded (17+6782)/6799 entities` (count downloaded + skipped in the numerator)
or 
`Downloaded 17/6799 entities (skipped 6782)` (count downloaded only in the numerator)

Knowing the total up front, we could also have a progress bar. We could have different colors or shading for predominantly-downloaded or predominantly-skipped blocks. 🤩

**Comment by mitchellwrosen** [comment]
How might we compute the number of transitive dependencies of a causal?
