### ISSUE TITLE
Deterministic pull from Share

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#3322]
# Background / Motivation

Recently I've been thinking about how to package apps written in Unison. The output of the `compile` command isn't a full solution by itself, because:

1. The binary that it produces is tied to an exact version of ucm. It's not practical to not allow someone to run your app because it was published for M3 and the user has updated their ucm to M4.
2. It's not completely standalone; it requires a ucm binary to run it.

One approach that I'd like to try (but that won't be a good fit for everyone) is to have a Nix derivation that bundles a `ucm` binary with an app binary that it has produced.

# Problem

The first problem that I run into is that I need a deterministic way to pull the Unison code that needs to be fed to the `compile` command. By "deterministic" I mean that I should be able to verify the contents with a sha-256 checksum. This works fine for Unison projects hosted on GitHub, but now projects have generally moved to Unison Share. The results of pulling into a fresh codebase appear to not be deterministic.

For example I have the following transcript that simply pulls a release of base:

**fetch-base.md**

````
```ucm:hide
.> pull unison.public.base.releases.M4 .
```
````

And I have the following shell script that simply runs the transcript and checks the sha256 of the result. It does some wacky things to be able to figure out where `ucm transcript` saves the codebase, but let's ignore that for the moment.

**checksum-base.sh**

```
#!/bin/bash

set -euo pipefail

workdir=$(mktemp -d)

# INSIDE_EMACS is a hack to make ucm not try to open up less since this is a
# non-interactive script
TMPDIR="$workdir" INSIDE_EMACS=1 ucm transcript --save-codebase fetch-base.md 1>/dev/null
codebase="$workdir/$(ls "$workdir" | head -n 1)"

echo "codebase: $codebase"

find "$codebase" -type f -exec sha256sum {} \;
```

If I run this multiple times I get different checksums for the SQLite codebase:

```
❯ ./checksum-base.sh
codebase: /tmp/cody/tmp.gCv5nQawQj/transcript-3a7ab333277109ca
c64687e584ba4054022a2840b77fcfd297fb0a14b084b8f3d05671302c0b534b  /tmp/cody/tmp.gCv5nQawQj/transcript-3a7ab333277109ca/.unison/v2/unison.sqlite3
f4635a06c04ea5accad54d9d721a64480c308e80c66c4fc6c6cdc31f921c1ddb  /tmp/cody/tmp.gCv5nQawQj/transcript-3a7ab333277109ca/reflog

cody@harlan ~/code/unison-to-nix 12s
❯ ./checksum-base.sh
codebase: /tmp/cody/tmp.dEEAndpP29/transcript-63d53b605af62ce9
491eb19d08b0611e0bc15e754449fe7da223a0a2347cbdf7b5e638c9232a33b6  /tmp/cody/tmp.dEEAndpP29/transcript-63d53b605af62ce9/.unison/v2/unison.sqlite3
f4635a06c04ea5accad54d9d721a64480c308e80c66c4fc6c6cdc31f921c1ddb  /tmp/cody/tmp.dEEAndpP29/transcript-63d53b605af62ce9/reflog
```

This is a problem for a Nix derivation, because it means that we can't represent the base library with a content-addressed hash. And it generally seems like something that you would want to be able to do for other reasons (like making sure that nobody pushed malware to Share under a previously-valid namespace).

# Questions

Do we know what causes the SQLite file to vary? Fetching terms in parallel? Timestamps? Nondeterminism inherit to SQLite?

# Alternatives

Is this even the way that we'd want to go about this? For this use-case we don't necessarily need to pull a whole project/namespace. Really I want to be able to fetch a single term of type `'{Exception, IO} ()` and all of its dependencies. Is this something that you should be able to fetch in a format other than SQLite?

**Comment by mitchellwrosen** [comment]
> Fetching terms in parallel?

Yeah, things are fetched in parallel, so they'll be assigned different autoincrementing int identifiers across runs.

**Comment by ceedubs** [comment]
One thing that I just noticed is that if I run `compile`, then the `.uc` file that it generates _does_ seem to have a deterministic hash, even if the SQLite file itself doesn't. This is probably good enough for me to work with for now. I'll go ahead and close out this issue, though I could still see us wanting some features in this realm in the future (pull a tar file of code, etc).

**Comment by pchiusano** [comment]
Can we just build a binary that includes `ucm` and the output of the `compile` command in a single file? ELF binary something something?
