### ISSUE TITLE
Change `PrintError.hs` to use `Pretty ColorText`

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#334]
See `CommandLine.hs` for an example of how this is done.

**Comment by gvolpe** [comment]
Hi @runarorama , I can take this one if that's okay. I believe it refers to this function?

```haskell
putPrettyLn :: P.Pretty Color.ColorText -> IO ()
putPrettyLn p = do
  width <- getAvailableWidth
  putStrLn . P.toANSI width $ P.border 2 p
```

If so, what are the expectations? It's not so clear to me after giving both files a quick look.

**Comment by pchiusano** [comment]
@gvolpe some other stuff that might be useful - 

You'll be modifying [PrintError.hs](https://github.com/unisonweb/unison/blob/master/parser-typechecker/src/Unison/PrintError.hs), basically anywhere you see `AnnotatedText a` you'll be replacing that with `Pretty a` and using the `Pretty` functions directly. A big reason for this is getting rid of all the manual hard line wrapping, but also `Pretty` has a much richer API for formatting.

https://github.com/unisonweb/unison/blob/master/parser-typechecker/prettyprintdemo/Main.hs has a demo with commentary of the pretty-printing library, you can run `stack build && stack exec prettyprintdemo` to see the output of that.

In `CommandLine`, more specifically, check out [the `notifyUser` function](https://github.com/unisonweb/unison/blob/master/parser-typechecker/src/Unison/Codebase/CommandLine.hs#L84), which has [a whole bunch of examples of using `Pretty` for output formatting](https://github.com/unisonweb/unison/blob/master/parser-typechecker/src/Unison/Codebase/CommandLine.hs#L127).

If you run into trouble, ping us on Gitter or here. :)

**Comment by gvolpe** [comment]
Awesome @pchiusano , thanks for the great details. I'll do my best :)

**Comment by gvolpe** [comment]
Hi again guys, 

I tried to give it a shot today but it's not as simple as I thought it was and right now I don't have much more time to spare on this (going on holidays for a few weeks) so if anybody else wants to take it please go for it. I'll surely contribute in other occasions, thanks! :)

**Comment by runarorama** [comment]
Solved in https://github.com/unisonweb/unison/commit/28d91737d2ca7b99c2cc1988882123a7d6b65e56
