### ISSUE TITLE
diagnose #3275 & #3307

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#3340]
Currently this feels like a regression, I'd like to un-regress it before a release.

See https://github.com/unisonweb/unison/issues/3275#issuecomment-1216746172

and

https://github.com/judah/haskeline/issues/130#issuecomment-569530431

and

https://github.com/judah/haskeline/pull/126

Maybe it would be enough to apply https://github.com/judah/haskeline/pull/126 to some new branch of https://github.com/unisonweb/haskeline. If everything looks good, we can reset the `unison` branch to whatever commit is working well for us; possibly in conjunction with the `ENABLE_VIRTUAL_TERMINAL_PROCESSING` thing.

**Comment by ChrisPenner** [comment]
I'm not sure that it's necessarily a Haskeline exclusive thing is it?
You've looked into this deeper than I have, but I'm seeing it on every ANSI string we print, not just haskeline output 🤔 

<img width="626" alt="image" src="https://user-images.githubusercontent.com/6439644/189158765-7675db9b-5231-41d4-a90a-7fbd37b5e1db.png">

**Comment by hojberg** [comment]
@ChrisPenner Is this on M4 or trunk. I feel like I read that this bigger issue had started to happen only after we fixed the prompt rendering issue?

**Comment by ChrisPenner** [comment]
I haven't checked M4, but this screen-shot was trunk (on Windows)

**Comment by aryairani** [comment]
> I'm not sure that it's necessarily a Haskeline exclusive thing is it?

(It was multiple things.)
