### ISSUE TITLE
Exploration of overhauling how patches are created and used

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#3342]
Can we automatically generate them, and when? (On push? on merge? in PRs?) 
Do we need to track more info during development than what we currently track in patches? 
Do we need new commands for update?

**Comment by ceedubs** [comment]
If you are exploring overhauling patches, I think that it would be good to consider #2587 as part of this. It bit me again just today.

**Comment by hojberg** [comment]
Might be worth considering how these would be represented in an API to the UI.

**Comment by ceedubs** [comment]
#3273 is also relevant to this effort.

**Comment by kylegoetz** [comment]
@aryairani if patches aren't a thing with the new `update`, can this issue be closed?

**Comment by aryairani** [comment]
@kylegoetz Yes
