### ISSUE TITLE
look into windows dev box access

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#3344]
e.g. cloud VMs or worst-case local VMs

**Comment by ceedubs** [comment]
@aryairani do you see this being a single instance that you want running all the time, or would it be more convenient for people to be able to spin up Windows VMs as needed?

It would be easy for @stew or me to spin up the former on AWS. The latter seems more likely to be what you want, but will probably require a bit more work on our end around setting up some AWS permissions and on the user's end with using the AWS console/CLI.

**Comment by aryairani** [comment]
@ceedubs Probably either would work, or something in between.  Like... It wouldn't have to be a server that was up all the time, and we also don't need everyone to be on Windows at once, nor one person on multiple VMs.

A fixed number of VMs would be plenty for now, and maybe forever.  We can chat more, or if it's easy to set up a few, that'd be great.  Maybe a Win 7, Win 10, Win 11?  It just needs to be powerful enough to build and run ucm reasonably.  So far, I think only Chris and I have tried Windows, on local VMs, though eventually it would be nice to spread this pain around :)

**Comment by aryairani** [comment]
I could imagine it being nice to be able to revert the machine to a known state though, for reproducibility.  Especially if we are going to be telling people they need to install certain packages, or set certain registry settings, to get a successful run. But it's not necessary at the start.

**Comment by aryairani** [comment]
@ceedubs How about just setting up a Win7 VM and a Win11 VM on the VPN?

**Comment by ChrisPenner** [comment]
P.s. I'm happy using Parallels for now 👍🏼

**Comment by stew** [comment]
@aryairani Win7 and Win11 aren't easy options. Windows Server 2016, 2019, 2022 are

**Comment by aryairani** [comment]
@stew Ah, just noticed this now. That's fine. I don't know the relationships between those 5 releases, but anything would be a great start.

Parallels hasn't been a practical option on my machine due to ram and disk constraints.

**Comment by aryairani** [comment]
Stew set up us the bomb
