### ISSUE TITLE
Error message says "vector" instead of "list"

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#3360]
<img width="569" alt="image" src="https://user-images.githubusercontent.com/11074/186700731-0f8ba575-eb42-48dd-bc87-3fcd0c4ba75b.png">

That should say "elements of a list"

**Comment by pchiusano** [comment]
Look in `PrintError.hs` to fix.

**Comment by ceedubs** [comment]
Fixed by #3380 !
