### ISSUE TITLE
Share API: Project - `GET /users/:handle/projects/:project-slug`

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#3384]
2 new endpoints to get the details of a single project by user.

## Project Details

**Endpoint:**
```
GET /users/:handle/projects/:project-slug
```

**Response body:**
```typescript
type Owner
    = { type: "user", handle: string, name: string } 
    | { type: "organization", handle: string, name: string }
    
type Project = {
  slug: string
  owner: Owner
  // `name` is a human readable version of the `slug`.
  // `slug` is generated from this
  name: string 
  summary?: string // a brief blurb about the project
  tags: Set<string>
  visibility: "public" | "private"
  forkOf?: string // ProjectID (UUID) -> perhaps later version?
  numFavs: number
  numWeeklyDownloads: number
  isFaved: boolean // is faved by the current user - null if not logged in
}
```

## Readme

**Endpoint:**
```
GET /users/:handle/projects/:project-slug/readme
```

**Response body:**
```typescript
// our standard readme response
```

**Comment by ChrisPenner** [comment]
Can you clarify this a bit:

```
  // `name` is a human readable version of the `slug`.
  // `slug` is generated from this
  name: string 
```

What's the difference between `name` and `slug`? Are slugs not human readable as is?

Or is this the displayName thing that we've since agreed to drop for now 😄

**Comment by ChrisPenner** [comment]
I think I may leave off `owner` for now if that's okay.

We haven't really solidified the notion of 'organizations' internally yet; we could probably just add that as a field on users or something, but I'll probably leave that till the second iteration if that's okay 😄

**Comment by hojberg** [comment]
@ChrisPenner yeah that sounds ok for now

**Comment by ChrisPenner** [comment]
I added it to the response, but for now _every_ owner will be a "user". I'll add support for actually determining "org" owners later in a separate PR 👍🏼

**Comment by ChrisPenner** [comment]
Done
