### ISSUE TITLE
Share API: Project Settings - `PUT /users/:handle/projects/:project-slug/settings`

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#3386]
A new endpoint that accepts `ProjectSettings` to configure a project. Currently just `visibility`:

**Endpoint:**
```typescript
PUT /users/:handle/projects/:project-slug/settings
```

**Request payload:**
```typescript
type ProjectSettings {
  visibility: "public" | "private"
}
```

**Response body:**
```
Empty
```

Only the owner of a project can change settings.

**Comment by ChrisPenner** [comment]
Let me know if you need anything more on this,  but I think it's done for now.
