### ISSUE TITLE
Share API: Browsing Project Code

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#3387]
Mirror the Codebrowsing APIs we use broadly but within the scope of a project:

```
GET /users/:handle/projects/:project-slug/code/browse
GET /users/:handle/projects/:project-slug/code/find
GET /users/:handle/projects/:project-slug/code/namespaces/by-name/:name
GET /users/:handle/projects/:project-slug/code/definitions/by-name/:name
GET /users/:handle/projects/:project-slug/code/definitions/by-hash/:hash
```

Should also include the README lookup:

```
GET /users/:handle/projects/:project-slug/readme
```

**Comment by pchiusano** [comment]
@ChrisPenner commented: 

> [here](https://www.notion.so/unisonweb/Adapting-name-lookup-tables-to-projects-e23e260ca8fa44e2a809cf5810fb6e8a) are a number of changes we need to make to support multiple name-lookups within a single codebase, this will be primarily used in Share, but depending on which design we choose could benefit UCM as well.
I've drafted my thoughts and outlined some possible approaches here

**Comment by ChrisPenner** [comment]
BTW @hojberg  We don't have default branches for projects yet (though could add them) so we'll need a  branch name and (optional) contributor handle in those URLs somewhere 😄

**Comment by hojberg** [comment]
@ChrisPenner yeah that seems fine. I don't have a strong opinion about where in the URL it should be, but maybe something like this:

```
GET /users/:handle/projects/:project-slug/branches/:branch-ref/browse
GET /users/:handle/projects/:project-slug/branches/:branch-ref/find
GET /users/:handle/projects/:project-slug/branches/:branch-ref/namespaces/by-name/:name
GET /users/:handle/projects/:project-slug/branches/:branch-ref/definitions/by-name/:name
GET /users/:handle/projects/:project-slug/branches/:branch-ref/definitions/by-hash/:hash
```
`:branch-ref` being defined as either `:handle/:branch-slug` or just `:branch-slug`.
Let me know if thats doable (with the slash) in Servant (feels ok to be escaped for an API URL?) or we can do something different like a query param. 

I do think the README request should be for the default branch of `main`.

**Comment by ChrisPenner** [comment]
Merged into `topic/projects`
