### ISSUE TITLE
Share API: Catalog - `GET /catalog`

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#3388]
A new endpoint that returns a categorized catalog.

**Endpoint:**
```typescript
GET /catalog
```

**Request body:**
```
Empty
```

**Response body:**
```typescript
type Owner
    = { type: "user", handle: string, name: string } 
    | { type: "organization", handle: string, name: string }
    
type Project = {
  slug: string
  owner: Owner
  // `name` is a human readable version of the `slug`.
  // `slug` is generated from this
  name: string 
  summary?: string // a brief blurb about the project
  tags: Set<string>
  visibility: "public" | "private"
  forkOf?: string // ProjectID (UUID) -> perhaps later version?
  numFavs: number
  numWeeklyDownloads: number
  isFaved?: boolean // is faved by the current user - null if not logged in
}

type CatalogCategory {
  name: string
  projects: Array<Project>
}

type Catalog {
  categories: Array<CatalogCategory>
}

```

Only the owner of a project can change settings.

**Comment by ChrisPenner** [comment]
I'm confused, are "Categories" equivalent to tags, or are they a separate thing that we manage somehow?

If the latter, are those managed only by admins, or can users put their project into a category? Do I need to add this to the DB then?

I notice the request is empty, are we returning literally every project in the response here? Or only the ones for specific categories? Or are not all projects in a category?

🤔

**Comment by ChrisPenner** [comment]
Also, do we actually need `isFaved` in the response here?

Other than `isFaved` this seems like a really good candidate for caching since this'll be on the front page of share and I'd love to just serve this from cache basically all the time haha, although presumably PG will be plenty fast at aggregating this if we need to.

**Comment by hojberg** [comment]
Categories (and really the catalog) are things we curate. Users put tags on projects, we put projects in categories and from that we'll likely pick a few to feature—we won't return a lot. It'll be a fixed set of project that we want to feature on the front page for whatever reason. Over time we might have a more complex way of determining if a project should be displayed or not, based on popularity, when it was last updated etc.

Given the low number of projects here I don't think we'll have much of a problem with including `isFaved`.
