### ISSUE TITLE
ucm shouldn't always start in the . namespace

### ISSUE THREAD

**Issue by stew** [unisonweb/unison#3397]
When we are exiting, we should save the current namespace somewhere so that the next time UCM starts it can start in that same namespace.

Also add a command line switch which can set the initial namespace so `ucm` --namespce=.` would emulate the current behavior of always starting in the `.` namespace and `ucm --namespace=stew.share.public` would start ucm in the `.stew.share.public` namespace

**Comment by ChrisPenner** [comment]
@stew  is the provided option good enough for now or should we still investigate the "keep previous path" line of work?

**Comment by aryairani** [comment]
keep previous path is done in #4092

**Comment by aryairani** [comment]
startup flag is done in https://github.com/unisonweb/unison/pull/3430
