### ISSUE TITLE
unison: cannot serialize program with blank result

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#341]
```
unison: cannot serialize program with blank result
CallStack (from HasCallStack):
  error, called at src/Unison/Codecs.hs:175:18 in unison-parser-typechecker-0.1-7cPEYjyT8ESITgUFJnyJ9P:Unison.Codecs
Shutting down runtime.
```
when typechecking a .u file containing a _blank.

We should check for blanks before trying to execute.

**Comment by aryairani** [comment]
Still relevant with Haskell runtime.

**Comment by pchiusano** [comment]
Can you reopen with a link to a pending test, if this is still a thing? I tried to reproduce unsuccessfully on latest master.
