### ISSUE TITLE
spurious errors in the ucm shell when hovering over whitespace in vscode

### ISSUE THREAD

**Issue by stew** [unisonweb/unison#3419]
I'm using the latest vscode plugin, when I hover over whitespace at the beginning of the line, my ucm process will spout useless errors. 

This is not a huge problem, these errors are ignorable. They are annoying, however.

**Comment by ChrisPenner** [comment]
I think this is just because the lsp tries to parse whitespace as a name for "hover", should be easy to fix 👍🏼
