### ISSUE TITLE
Time to parse a scratch file grows with size of codebase

### ISSUE THREAD

**Issue by ChrisPenner** [unisonweb/unison#3421]
Using Stew's giant codebase I notice that, even in a completely empty branch, getting a slurp printout after saving a scratch file with a single definition takes about 2s; on a fresh codebase it's instant.

I suspect we're still loading the global PPE or something, but with self-contained namespaces we should probably just not do that.

**Comment by ChrisPenner** [comment]
I confirmed that we do indeed load the root names, and ALSO find historical names for all labeledreferences, all of which I believe is unnecessary under the new "self-contained namespaces" assumptions.

I'll look at fixing this probably after #3391  or something like it gets merged since it'll be much more noticeable at that point.

**Comment by ceedubs** [comment]
> all of which I believe is unnecessary under the new "self-contained namespaces" assumptions.

Today we talked about a violation of the "self-contained namespaces" assumption that is going to be common. If you update a type, then you will have a bunch of references to the previous (and now unnamed) type until you finish your entire `todo` list.

**Comment by aryairani** [comment]
probably fixed with #5041

**Comment by ChrisPenner** [comment]
I think this was probably already fixed when we removed the global root ppe fallback, but project-roots can't hurt either :)
