### ISSUE TITLE
ScopedTypeVariables?

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#343]
Plan here for how to support something like `ScopedTypeVariables`; I remember that it's not a slam dunk, but I think it's pretty important to be able to annotate anything you want.

**Comment by ChrisPenner** [comment]
Is there any consideration towards making this the default? The default behaviour of implicit foralls in haskell is consistently a source of confusion for newbies. If people want 'fresh' variables in a sub expression they can just make up a new name :)

**Comment by pchiusano** [comment]
100% agree. Will get done it’s just not super easy.

**Comment by pchiusano** [comment]
As of #511, this is implemented and now the default behavior. The work is in wip/branchless right now but that branch will be merged to master pretty soon.
