### ISSUE TITLE
The Readme field on the namespace details endpoint is always null

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#3431]
It looks like we might have introduced a regression where the `readme` field on the namespace details returns `null` even when that namespace has a readme.

Ex: https://share.unison-lang.org/@unison/code/latest/namespaces/public/base/latest

Response for the namespace details endpoint:

```json
{
  "fqn": "public.base.latest",
  "hash": "#abbreviatedlonghash",
  "readme": null
}
```

**Comment by hojberg** [comment]
@ChrisPenner any thoughts on what might have happened.

**Comment by ChrisPenner** [comment]
Fixed in https://github.com/unisoncomputing/enlil/pull/88
