### ISSUE TITLE
Cycle update minimegaticket

### ISSUE THREAD

**Issue by mitchellwrosen** [unisonweb/unison#3445]
This ticket tracks the cycle update issue, any related PRs, and outstanding work.

---

Tickets:

- https://github.com/unisonweb/unison/issues/2583
- https://github.com/unisonweb/unison/issues/2649
- https://github.com/unisonweb/unison/issues/2794

---

PRs:

- [x] Basic first draft
  - [x] #3443
  - [x] #3462
- [x] Discover new cycles formed by dependent components
  - [x] #3466
  - [x] #3473  
  - [x] #3489 
  - [x] #3490
  - [x] #3491
  - [x] #3500 
  - [x] #3503
  - [x] #3508
- [ ] Don't mention implicit cycle-mates in the output of an update
  - [x] #3463  
- [ ] Make nameless implicit term case work
  - [x] #3463 
- [ ] Do it all for decls, too
- [ ] Performance: don't bother with implicit terms of a type-changing update
- [ ] Undo change to view/edit that shlurps entire cycle
  - [x] terms #3591
  - [ ] decls

**Comment by aryairani** [comment]
superseded by new `update`
