### ISSUE TITLE
Improve migration message

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#3447]
<img width="338" alt="image" src="https://user-images.githubusercontent.com/11074/191840218-db4645ff-4c6a-4753-ba05-3881f6c42930.png">

`codebase` is not capitalized, but `Namespace` `Causal`, and `Integrity` are... except for the first line, where it's not. :) 

How about: 

```
🕵️  Checking codebase integrity (step 1 of 3) ...
🕵️  Checking codebase integrity (step 2 of 3) ...
✅  All good, cleaning up... 
🏁 Migration complete 🏁
```

And you can just rewrite the line as you get to the next step. Telling the user about "namespace integrity" and "causal integrity" is too much detail.

**Comment by runarorama** [comment]
Maybe squeeze in a "reticulating splines..." in there
