### ISSUE TITLE
editing multiple definitions and dependency ordering

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#3474]
Currently the order of definitions in a Scratch file can affect the compile errors that are are produced. For example if `b` depends on `a` and `a` appears below `b` in the Scratch file, you might see a misleading error message. I think that this is only the case with updating an existing `a` definition. I'm not quite sure of the specifics, but I think that it might have to do with TDNR picking up the old definition instead of the one in the scratch file until compile errors are resolved.

Ideally the order of definitions in the scratch file wouldn't matter. But here is a proposal that may be lower-hanging fruit:

When a multi-arg `edit` command like `edit termA termB termC` is issued, add the definitions to the scratch file with dependencies ordered before dependents. This seems to lead to more of the expected behavior with error messages.

This might be less of a concern once all of the issues with cycle detection and automatic propagation are sorted out, as it might be less common to edit a lot of definitions at once.

**Comment by aryairani** [comment]
@ceedubs With the new `update`, can we close this ticket?

**Comment by ceedubs** [comment]
@aryairani this doesn't seem to be as much of an issue as it used to be. I do feel like a couple of days ago I ran into a confusing error message related to this, but if that's true I think that the proper solution is probably to have error messages that aren't as dependent on the order of definitions in the scratch file. I'm going to close out and if this crops up again I'll reopen or create a new ticket.

**Comment by aryairani** [comment]
Okay, thanks.
