### ISSUE TITLE
record syntax for Unison data types

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#349]
Maybe something like:
```haskell
type Foo a = Foo   { p : Nat
                   , q : Int -> a } 

           | Foo2  { r : Nat
                   , p : Nat
                   , q : Int -> a } 

           | NoFoo { p : Nat }
```
becomes syntax sugar for (or at least produces definitions compatible with):
```haskell
type Foo a = Foo Nat (Int -> a) | Foo2 Nat Nat (Int -> a) | NoFoo Nat

Foo.p : Foo a -> Nat
Foo.p x = case x of 
  Foo.Foo p _ -> p
  Foo.Foo2 _ p _ -> p
  Foo.NoFoo p -> p

-- use Optional to avoid match error for partial functions
Foo.r : Foo a -> Optional Nat
Foo.r x = case x of
  Foo.Foo2 r _ _ -> Optional.Some r
  _ -> None  

Foo.q : Foo a -> Optional (Int -> a)
Foo.q x = case x or
  Foo.Foo _ q -> Optional.Some q
  Foo.Foo2 _ _ q -> Optional.Some q
  _ -> None
```

**Comment by pchiusano** [comment]
Yeah, I think this could be done just in the parser. The data declaration parser could just return a `(DataDeclaration v Ann, [(v, Term v Ann)])`, basically the data type plus a list of bindings which will get added to the `UnisonFile` that is parsed. In the case where there's no records, the list will be empty.

For simplicity and reduction of magic, I wouldn't do this for types with more than one constructor, I've always felt like that's an odd feature of Haskell (which I like _never_ use), and it's especially bogus that it just gleefully generates a partial function.

Having it generate a function in those cases that returns `Optional` feels kinda weird and magical. Why `Optional`? Why not `Either`? Or why not take a default value and do a `fromMaybe`? I think just write a regular function in these cases. We could always revisit this later (without breaking any Unison code) if we decide we really want to support more magic. 🧙‍♂️

One question - what about `ability` declarations? For now, maybe punt - no special syntax for these, and not sure how useful it is anyway.

**Comment by aryairani** [comment]
Great, let's just do the 1-constructor version:

```haskell
type Foo a = { p : Nat, q : Int -> a }
```

becomes

```haskell
type Foo a = Foo Nat (Int -> a)
Foo.p : Foo a -> Nat
Foo.q : Foo a -> Int -> a
```

Re. `ability` declarations, I don't see the connection — they are already in a record-like syntax, but coproduct rather than product.

**Comment by aryairani** [comment]
Note that there will still be some rough edges around pretty-printing and maybe with colliding names.

**Comment by aryairani** [comment]
Let's have a separate ticket if we want to discuss a new ability syntax.

**Comment by pchiusano** [comment]
Let’s have separate issue also if we want to have the pretty-printer do something fancy. I think it’s doable but we can punt on it for now. Basically, when displaying a data type with one ctor, check if it has record accessors of the exact form expected (literally can just lookup by the hash of its implementation). If yes for all arguments to the ctor, emit the record syntax, using the names of these accessor functions. If no, don’t do anything special.

@virusdave FYI 😀
