### ISSUE TITLE
delete shouldn't create new namespace dependencies

### ISSUE THREAD

**Issue by stew** [unisonweb/unison#3497]
right now when I'm upgrading a library, I typically do this:

```
.myapp> move.namespace lib.somelib lib.oldsomelib
.myapp> fork .share.someone.public.somelib.main lib.somelib
... fix stuff to use the new lib...
.myapp> delete.namespace lib.oldsomelib
```
but if I fail to upgrade all of the things or if I skip the "fix stuff" step. I'll end up having created new namespace dependencies to the lib I just deleted from this namespace.

it seems like I should have to use `.force` if I actually want to create new external dependencies, or at the very least it should warn me once I've done it

**Comment by aryairani** [comment]
I talked with Stew and we think that `delete.namespace` isn't warning about losing the last names, because it warns about losing the last name in the whole codebase, not the last name in the current/self-contained namespace.

**Comment by aryairani** [comment]
We think this is fixed in `trunk`, yeah?
