### ISSUE TITLE
new system for choosing compatible `base` versions for new setups

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#3502]
Ideally we could release base and ucm independently, while ensuring that ucm won't hand a developer a version of `base` that requires unknown builtins.

Ideally, minimal manual work incurred when adding builtins or releasing ucm or releasing base.

**Comment by aryairani** [comment]
Maybe a Set or a bloom filter or a runtime version number that represents the builtins a library and its deps require, matched against a value in ucm.  Could be special-cased to `base`, could be manually populated, or could be generic across all libraries.

A system that more directly represents the supported builtins than simple numbering seems better to me, as we may end up with multiple lineages of runtimes eventually. But probably not for a while.

**Comment by aryairani** [comment]
For now we can just manually release base, and manually kick off the automated ucm release.  So we should revert the download code to get an exactly matched release.

Eventually, there could be fewer updates to base than there are updates to ucm, and then we would revisit this.

**Comment by nmcb** [comment]
wild

> a bloom filter or a runtime version number that represents the builtins a library and its deps require, matched against a value in ucm

wild-requirement : the moment the revision is released as automated base - ie. effectively decoupling `base` versioning and release with your first, one-and-only `ucm` cli on your first one-and-only physical machine -  SHOULD provide lifetime support on base to individual Unison developers
