### ISSUE TITLE
Allow passing a base release to pull for each release.

### ISSUE THREAD

**Issue by ChrisPenner** [unisonweb/unison#3514]
This will allow us to pick which base version should be pulled for each individual UCM release.

**Comment by ceedubs** [comment]
Is this what would allow us to pull a squashed release instead of `main` when someone opens up ucm in a new codebase? If so this seems like it would dramatically improve the new user experience. It takes many minutes to pull `main`.

**Comment by ChrisPenner** [comment]
#3522
