### ISSUE TITLE
Unexpected capture with Pattern.optional and Pattern.join

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#3530]
This seems like a bug to me, but it could be my expectations being off. Consider the following code:

```haskell
  p = Pattern.capture (
    Pattern.optional (
      Pattern.join [
      , literal "a"
      , literal "b"
      ]
    )
  )
  Pattern.run p "ac"
```

I would expect it to return `Some ([], "ac")`, because the inner `Pattern.join` expects an `a` followed by a `b`, so I would expect the entire `optional` segment to return an empty string.

However, it actually returns `Some (["a"], "c")`. Am I off or is the `Pattern` implementation?

@dolio @pchiusano

**Comment by pchiusano** [comment]
Yeah, this looks like a bug. It shouldn't consume (or capture) the 'a'.

But it should actually capture the empty string, since that is what the inner `optional` consumes.

**Comment by pchiusano** [comment]
@ceedubs I went ahead and added a transcript regression test as well. :)
