### ISSUE TITLE
Spurious ability failure

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#3532]
<img width="860" alt="image" src="https://user-images.githubusercontent.com/11074/197067472-5c546aad-97f5-4e35-ba86-63329bdc7674.png">

**Comment by pchiusano** [comment]
I'm not positive this is a bug, but I was expecting it to typecheck, by setting `g` to `Atomic`.

**Comment by pchiusano** [comment]
Next step: a proper bug report and minimal example.

**Comment by dolio** [comment]
Closing. Ticket seems unlikely to progress to a useful state.
