### ISSUE TITLE
more helpful todo ordering after constructor change

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#3533]
Extracted from @pchiusano's text on #2711 

This came up when @ceedubs and @stew had a conflicting edit to a type, Foo and then some further edits on top of that. The todo output included a big list of all these other conflicts, but most of the other conflicts had one of the versions of Foo as a transitive dependency.

The user wants to know: what's the thing I actually need to act on. We can tell them that there's some transitive conflicts (just a count) but don't spam them with a big list of them.

Also specifically for a type conflict, you always want to first resolve conflicts on any functions that do direct pattern matching on the type or which directly call the constructor of that type. Once those are resolved, autopropagation can get a lot farther. I don't think the "what to work on first" output of todo properly reflects this - it looks for immediate dependents of the updated thing, but some of the immediate dependents might just mention the type in their signature. That doesn't matter, we want to update the things that actually pattern match or call a constructor.

**Comment by aryairani** [comment]
superseded by #5088, though we may still revisit if we implement something like this again in a future update process
