### ISSUE TITLE
Definition Summaries: JSON body are URL encoded resulting in weird rendering

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#3537]
Looks like we're URL encoding the JSON body of the response of definition summaries. I can certainly decode it on the frontend, but I don't think we actually need to encode this.

<img width="484" alt="CleanShot 2022-10-24 at 09 40 10@2x" src="https://user-images.githubusercontent.com/2371/197540994-853877fc-4cdb-498a-83c7-a073dbb78b90.png">

**Comment by ChrisPenner** [comment]
I believe this is a combination of https://github.com/fizruk/http-api-data/issues/79 and the fact that the name returned in the summary is just the "pass-through" of whatever is provided.

I think this also indicates we probably have some bugs when displaying/fetching other terms which include characters that need url-decoding 🤔;

So I think we just need to  add a [`urlDecode`](https://hackage.haskell.org/package/http-types-0.12.3/docs/Network-HTTP-Types.html#v:urlDecode) on most of our `FromHttpApiData` instances. Let me know if you'd like a hand on that @hojberg 😄

**Comment by hojberg** [comment]
@ChrisPenner thanks, I could definitely use a hand with this.

**Comment by ChrisPenner** [comment]
Upon further investigation it looks like the frontend is actually sending the emoji name encoded _twice_; so the server correctly decodes it _once_ and that's what's returned.

E.g. here's the literal request:
https://api.unison-lang.org/codebases/chrispenner/definitions/types/by-hash/@hanu8fnbp1shi4eonhrfpe8521c91e05gudn85q9u3543aijrl9g74k6rk210lcb3kss4nrhhidsglgo9cd5hobqd8rls92h5fb5jgg/summary?name=%25F0%259F%2590%25A2&relativeTo=public.turtle

Maybe the frontend is encoding it manually, then the http elm lib is encoding it again?
Maybe the server is returning an encoded string somewhere that the frontend then encodes and queries?

**Comment by hojberg** [comment]
This is an Elm issue, working on a fix right now.

**Comment by hojberg** [comment]
Fixed 🎉 
Thanks @ChrisPenner
