### ISSUE TITLE
mutable byte array bugs

### ISSUE THREAD

**Issue by stew** [unisonweb/unison#3542]
Attached is a transcript which crashes the runtime, I think that mutable ByteArrays are buggy:

````
```ucm
.> pull unison.public.base.main.mutable lib.base.mutable
.> pull unison.public.base.main.data.ByteArray lib.base.data.ByteArray
.> pull unison.public.base.main.abilities.Exception lib.base.data.abilities.Exception
```

```unison
> Exception.catch do Scope.run do
    array = Scope.byteArrayOf 1 10
    toList (freeze! array)
```


```ucm
.> add
```
````
```ucm
.> pull unison.public.base.main.mutable lib.base.mutable

  ✅
  
  ✅ Successfully pulled into newly created namespace
  lib.base.mutable.

.> pull unison.public.base.main.data.ByteArray lib.base.data.ByteArray

  ✅
  
  ✅ Successfully pulled into newly created namespace
  lib.base.data.ByteArray.

.> pull unison.public.base.main.abilities.Exception lib.base.data.abilities.Exception

  ✅
  
  ✅ Successfully pulled into newly created namespace
  lib.base.data.abilities.Exception.

```
```unison
> Exception.catch do Scope.run do
    array = Scope.byteArrayOf 1 10
    toList (freeze! array)
```

```ucm

  ✅
  
  scratch.u changed.
  
  Now evaluating any watch expressions (lines starting with
  `>`)... Ctrl+C cancels.

  💔💥
  
  I've encountered a call to builtin.bug with the following
  value:
  
    #r29dja8j9d#0
      (typeLink #6dtvam7msq)
      "ImmutableByteArray.read8: array index out of bounds"
      (##Any.Any 1)
  
  
  Stack trace:
    ##bug
    #l9h6537jpm

```

🛑

The transcript failed due to an error in the stanza above. The error
is:

  💔💥
  
  I've encountered a call to builtin.bug with the following value:
  
    #r29dja8j9d#0
      (typeLink #6dtvam7msq)
      "ImmutableByteArray.read8: array index out of bounds"
      (##Any.Any 1)
  
  
  Stack trace: ##bug #l9h6537jpm

````

````

**Comment by runarorama** [comment]
I've fixed this purely on the Unison side. The issue was that the length and content `Nat`s were swapped:

```
byteArrayOf b l = MBArr 0 l (Raw.byteArrayOf b l)
```

The builtin `Raw.byteArrayOf` expects the length first and the contents second, so our slice and the raw array will disagree on the length. I changed this to:

```
byteArrayOf l b = MBArr 0 l (Raw.byteArrayOf l b)
```

Pushed a fix to `base.main`, along with corresponding doc changes and a doctest.

**Comment by dolio** [comment]
Actually, `Scope.bytearrayOf` (the primop) is using the wrong argument order relative to all the other similar functions. Fixed in the unison PR above.

**Comment by runarorama** [comment]
Drat, beat me to it :) I reopened because I was doing that exact thing.

**Comment by dolio** [comment]
Yeah, sorry. I should have mentioned I was looking at it, because byte arrays are relevant to other stuff I'm working on.
