### ISSUE TITLE
program args are not captured when calling `!getArgs` 

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#3547]
It appears that calling `getArgs` returns an empty list rather than prompting for user arguments. 

I've attached a transcript with reproduces the issue, [test.md](https://github.com/unisonweb/unison/files/9892547/submitExercism.md)

Ucm version: m4c
Base version:
 latest/m4c.

**Comment by ceedubs** [comment]
Behavior is correct just needs a docs change. @rlmark is on it!
