### ISSUE TITLE
`view` and `edit` should not collect fuzzy-found results

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#355]
![image](https://user-images.githubusercontent.com/538571/53782082-ad6df280-3ed9-11e9-8c2b-baa2426b786c.png)
(I don't want to edit `Float.floor`.)

Perhaps:
First, search by exact name.
Then optionally: 
If this yields no results, and if fuzzy-find yields a single `Name`, then that is fine.
Or maybe just the first part.
Optionally: Some sort of wildcard/glob kind of search.  Like: `> edit Tree Tree.*`

**Comment by aryairani** [comment]
Unfortunately since `Tree.*` is a valud identifier, we’d need some sort of escaping too, which I think is annoying if you *are* trying to search for the name `Tree.*`.  Maybe there needs to be some additional syntax to enable wildcards 😞

**Comment by pchiusano** [comment]
This is done, right? @aryairani can you reopen and add some more info if not?
