### ISSUE TITLE
reflog not showing me all the changes

### ISSUE THREAD

**Issue by stew** [unisonweb/unison#3551]
i just made a few updates, but when I run reflog, I get:

```
  5.     24 mins ago         #3jl6t1mou5   reset-root #3jl6t1mou5
  6.     about 2 hours ago   #3j3i6lt0qc   .share.cloud.private.nimbus.main.patch
  7.     about 2 hours ago   #dt918mlh8k   .share.cloud.private.nimbus.main.patch
  8.     about 2 hours ago   #rfaisiujl2   delete.namespace .share.cloud.private.nimbus.main.lib.base
  9.     about 3 hours ago   #6l0gvo8ddb   .share.stew.public.projects.ansi.main.patch
  10.    about 3 hours ago   #nn7ne1266r   .share.stew.public.projects.ansi.main.patch
  11.    about 3 hours ago   #vd8kqn5moa   .share.stew.public.projects.ansi.main.patch
  12.    about 3 hours ago   #0q1qm3srsi   .share.stew.public.projects.ansi.main.patch
  13.    about 5 hours ago   #3jl6t1mou5   pull stew.public .share.stew.public
  14.    Monday, 10:29PM     #ijgp8d7r9q   replace .share.unison.public.base.releases.M2h.Random.lcg.ha...
  15.    Monday, 10:28PM     #r0to4n0qqr   replace .share.unison.public.base.releases.M2h.Random.lcg.ha...
```

Several items are missing, the first item in the output is numbered "5"

**Comment by stew** [comment]
some observations:

If I hit down arrow a few times, then up arrow, I lose more entries off the top. like for example if I hit down arrow 3 times, no matter how many times I hit up arrow, 8 will then become my top most entry.

If I hit down arrow 30 times though, I can then hit up arrow 35 times, and my top entry in the reflog will be 1, but my second will be something like 35

**Comment by ChrisPenner** [comment]
Bizarre, I think this is due to `less` choking on extra long lines or something, there's no conceivable reason that UCM would ever fail to print the pre-amble, e.g.

>   Here is a log of the root namespace hashes, starting with the most recent, along with the command
  that got us there.

**Comment by dolio** [comment]
Plan: try removing color from reflog output.

Or: don't page the reflog

**Comment by stew** [comment]
A workaround for people experiencing this is to make your terminal wide enough that the comments don't need to be wrapped

**Comment by ChrisPenner** [comment]
Question for @aryairani, currently the reflog shows a max of 500 entries, would it be acceptable to you to swap that to 100 or even 50 and remove paging?

Do we need some better way to manipulate/view the reflog?

**Comment by aryairani** [comment]
Next step: figure out what's even happening?

**Comment by ChrisPenner** [comment]
BTW I tried removing colors from the columns and it didn't seem to make any difference. Pretty sure this is just a `less` glitch, however unlikely that might be. Maybe we're using it wrong somehow?

If I scroll down, then scroll back up again it seems to change how it's displaying the first glitchy rows 🤔 

Our best course of action may be to  ensure the output of the reflog is within 80 columns or something
