### ISSUE TITLE
open ranges for numbered args

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#3558]
maybe `1-` expands all numbers from 1 onwards.  It can be time consuming to manually determine the end value of the range when ucm is slow.

workaround: `debug.numberedArgs` will show all the numbered args (and thus the range) fast. @ceedubs

**Comment by ceedubs** [comment]
@aryairani ooh `debug.numberedArgs` is something that I would have used so many times had I known about it. Thanks for the pointer!

**Comment by aryairani** [comment]
@ceedubs Is this still relevant?

**Comment by ceedubs** [comment]
The thing that made me not care about this any more is finding out that I can do `1-10000` and ucm is happy even if the numbers only go up to 11.

The `edit.namespace` command replaced my most common usage for this. But it's still handy in the case of something like `dependents foo; edit 1-100`.

But I'm happy to close it and we can reopen it if people are asking for it.
