### ISSUE TITLE
Potential unison-share term/type link issue  

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#3562]
Capturing for discussion at our issue triage meeting (feel free to delete if this is actually not an issue / already covered by an existing issue).  

Certain Unison share links appear to throw 403 permission denied errors upon interaction, however, this does not happen 100 percent of the time. 

I've attached a video of the behavior to this ticket:
https://user-images.githubusercontent.com/7613551/199793319-08686ba2-a046-4c86-8788-4c42063848b2.mov

Note that depending on how the wind blows, the issue seems to go away, (it is currently working for the recorded steps.) To try it yourself, check out the following readme: 
https://share.unison-lang.org/@rlmark/code/latest/namespaces/public/;/terms/projects/cron/Readme

Click on the linked terms in the readme, or hover over them. In the console you might see a 403 error with a url like "https://api.unison-lang.org/codebases/rlmark/definitions/terms/by-hash/@p0996s1e3o6pk9fp0qsoc5jr0h143v5fqeqmrsotn1i157g44qr6nrgekhm12k19b5klrm9jn251nlakn1k30gi6u1772dl23nv7u00@d0/summary?name=FieldType.Single" 

Or... you might see the term rendered.

**Comment by pchiusano** [comment]
@ChrisPenner and @rlmark It looks like the bug is simply that if you click on a link (which is by hash), without a perspective, then it 403s. It is deterministic as far as I can see, it's just that sometimes you can get to the same definition by name rather than by hash (say, if you navigate to the definition via the sidebar in the code browser).

**Comment by ChrisPenner** [comment]
Yup, I know what's causing it, we're having a conversation about possible fixes with the team, since it's not necessarily just a "bug", we need to come up with a good permissions model for viewing hashes.

We'll discuss it and come up with a plan at our planning meeting today.
