### ISSUE TITLE
try out constructing deepTypes/deepTerms more directly

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#3565]
We think we can get a quick space and time win by constructing `deepTypes`/`deepTerms` more directly, without forcing the same fields in child branches.

As a follow-on effort, we could try filtering out transitive dependencies.  i.e.
- lib/text - yes
- lib/text/lib - no
I say "try" because we don't know what the full consequences of doing so will be. We should audit the use sites of `deepTypes`/`deepTerms` to understand this better before committing such a change to trunk.

**Comment by aryairani** [comment]
Fwiw I tried this super quick version and it was worse: https://github.com/unisonweb/unison/compare/trunk...arya/fast-deep
It got to 40 gb of vm allocations before it killed itself 😬 
The trunk version completed in half the time that the experimental version took to crash.

**Comment by aryairani** [comment]
This version was better than the one linked in the previous comment (finished before killing itself), but still 2x as slow as trunk: https://github.com/unisonweb/unison/compare/trunk...arya/fast-deep2
cc @pchiusano

**Comment by hojberg** [comment]
YAY its done!
