### ISSUE TITLE
we are missing a Thread.join builtin

### ISSUE THREAD

**Issue by stew** [unisonweb/unison#3579]
It would be handy to be able to join a running thread (block until that thread exits)

**Comment by hojberg** [comment]
The thinking is that this should be part of base in library code instead of a builtin.

**Comment by ceedubs** [comment]
A bit of further clarification based on my (potentially wrong) understanding:

The Haskell runtime doesn't provide this sort of primitive; threads are independent and don't form a hierarchy. So this is not something that our current runtime could support.

If you want this sort of behavior you will need to need to do something (probably with an `MVar`) at the site where the thread is being forked. If there are common patterns that we could address with helper functions, then we could add those to base. But it won't have a type signature like `Thread.join : ThreadId -> {IO} ()`.
