### ISSUE TITLE
Regression in links to constructor terms in docs

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#3582]
Doc links like `{{ {Some} }}` used to render as (from current Share version):

![image](https://user-images.githubusercontent.com/130916/200459125-8e288a13-5f35-4d34-a5a2-b96e32bcf642.png)

Now they get rendered as (latest trunk):

![image](https://user-images.githubusercontent.com/130916/200459170-efb3f4a9-7270-4176-a950-2ecabbc83aa7.png)

So it looks like the term has been eta-expanded. I'm guessing this happens at compile-time, since this is only occurring with new docs, not e.g. docs pulled from Base.

**Comment by pchiusano** [comment]
@runarorama we assigned this to you during triage, but basically, solution is that doc renderer can do eta reduction inside of term links.
