### ISSUE TITLE
ucm version string can be misleading

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#3588]
`ucm --version` produces output like `ucm version: release/M4b (built on 2022-09-28)`. This version string is often misleading, as it usually seems to point to an older release/date.

I _think_ that what's happening is we are using template haskell to generate a version, and this isn't getting generated again until a `clean` happens.

**Comment by hojberg** [comment]
Maybe this is only for trunk builds?

**Comment by aryairani** [comment]
I think this is fixed now with #4829
