### ISSUE TITLE
Possible to use 7.10.3?

### ISSUE THREAD

**Issue by nightscape** [unisonweb/unison#36]
Hi Paul,

the automated build on Docker Hub takes too long and is killed after 2h.
The situation would improve if we could skip the the `stack setup` steps which consume a lot of time.
Unfortunately, I didn't find a Docker container that contains the required versions of GHC and GHCJS so we would skip the `stack setup`s.
We could at least skipped the first `stack setup` if Unison works under 7.10.3 because that's the first version for which the official Docker image also constains Stack.
Have you already tried building with 7.10.3? Would it be possible to switch?

**Comment by sfultong** [comment]
I've built with 7.10.3, and it seems to be fine.

**Comment by pchiusano** [comment]
I think we are already on 7.10.3, and will probably upgrade to 8.0 along with #103

**Comment by pchiusano** [comment]
Just confirmed that we are already on 7.10.3
