### ISSUE TITLE
Universal.compare on lists should probably be lexicographic

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#3603]
Right now `Universal.compare [1,2,3] [3]` returns `+1`, since the `[3]` list is shorter.

In general, I'd like `Universal.compare` to be a simple structural comparison done lexicographically.

Question: do we think it's okay to just change this behavior now? Or should we introduce a new builtin with the new behavior?

**Comment by runarorama** [comment]
Seems OK to change it as the current behavior is probably not very useful.

**Comment by hojberg** [comment]
Yay we fixed it!
