### ISSUE TITLE
Text.contains

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#3609]
We should have a function like that returns whether a `needle` is contained in a `haystack`.

```haskell
Text.contains : Text -> Text -> Boolean
Text.contains needle haystack = ???
```

I created this issue in the `unison` repo because I suspect that we'll want this as a builtin, but it could potentially be written in Unison and added to `base` without a builtin.

I attempted to implement `Text.contains` via `Pattern`, but I don't believe that there's a good way to do it.

**Comment by hojberg** [comment]
Fwiw my textExtra library includes a not fancy implementation of this

**Comment by ceedubs** [comment]
I realized that it's possible to (ab)use `Pattern` to implement `Text.contains` in a funky way:

```
  up.Text.contains : Text -> Text -> Boolean
  up.Text.contains needle =
    if Text.isEmpty needle then 'true
    else
      p = many (Pattern.or (Pattern.join [capture (literal needle), many anyChar]) anyChar)
      haystack ->
        (match Pattern.run p haystack with
          Some (_ +: _, _) -> true
          _                -> false
```

I have no intuition for the performance of it, and I haven't benchmarked it, though I'm sure that a builtin could perform better.

**Comment by ceedubs** [comment]
If this is implemented as a builtin, you might want something more like `Text.indexOf : Text -> Text -> Optional Nat`. You can implement `contains` in terms of this, and it could also support more things (like dropping the text before/after, doing a find/replace, etc).

For a global find and replace you would want something more like `Text.indexesOf : Text -> Text -> [Nat]`. But that wouldn't be as efficient if you only care about the first occurrence.

**Comment by aryairani** [comment]
@dolio Issue triage status check?

**Comment by ceedubs** [comment]
There is now a `Text.indexOf` builtin and a `Text.contains` in base that uses it. Closing!
