### ISSUE TITLE
comma-first sequence notation

### ISSUE THREAD

**Issue by francisdb** [unisonweb/unison#363]
```haskell
x = [a,b,c]

y = [ a
    , b
    , c
    ]
```

currently gives

```
master>
Token {payload = Semi, start = Pos 302 5, end = Pos 302 5} :| []
/Users/francisdb/workspace/unison-json/src/json.u:302:5:
unexpected <virtual semicolon>
expecting ]
  302 |     , b
```

have not tested this for records

**Comment by pchiusano** [comment]
Thanks for the report. This one might be an easy fix? I’d look in TermParser and add an ‘optional semi’ inside the sequence parser: 

https://github.com/unisonweb/unison/blob/master/parser-typechecker/src/Unison/TermParser.hs#L206
