### ISSUE TITLE
Need to find a more efficient way to handle names on huge codebases

### ISSUE THREAD

**Issue by ChrisPenner** [unisonweb/unison#3636]
The current strategy of "load _all_ names and then pretty print from that, uses waaaay too much memory and is infeasible on Share.

One feasible solution is to make pretty-printing monadic and to only load the names necessary to make a pretty-printer decision.

E.g. "I want  to pretty print #abc", we can write a query that uses the sqlite names index to find all names for #abc in the current namespace, pick the one with the shortest number of segments (could also keep segment count in the index if we want) then find all other names  with similar suffixes and do disambiguation on JUST those.

Other things that would help:
* Making the pretty printer monadic and doing surgical queries for only the names we need (I think this is the winner, since it should be blazing fast and use nearly no memory, but also it means we need to continue keeping the names index in SQLite, and doesn't work on historical namespaces)
* Restricting perspective to project roots so we only load names within that project
* Continuing in our quest of avoiding exponential number of names (I know Arya made some changes there, but they won't be reflected in the names index on share yet)

**Comment by pchiusano** [comment]
It's pretty easy to get the list of dependencies for a term up front and then use that to build a pretty print environment. As in, the database lookups don't literally need to be interleaved with the pretty printing.

**Comment by aryairani** [comment]
In progress (@ChrisPenner)

**Comment by ChrisPenner** [comment]
Cool to see how much we've progressed from here 😎

**Comment by ceedubs** [comment]
@ChrisPenner this progress was specifically on Share, right? Running todo still takes 30+ seconds for me when there are entries present, and I believe that time is mostly in name lookups for definitions without names in the current namespace.

**Comment by ChrisPenner** [comment]
@ceedubs yes this was for share, unfortunately I don't believe any of these approaches would actually help with historical names. From what I've heard, patches are getting a bit of a redesign so I'm hoping we can address the historical names issues as part of that.
