### ISSUE TITLE
Unison Share `pull user/project` parses as loose code, ignores the `/project`, tries to pull all of `user`, requiring auth

### ISSUE THREAD

**Issue by kylegoetz** [unisonweb/unison#3643]
If something is a public package (Unison docs say the default `push` is to a public repo), someone should not have to authenticate to `pull` it. Of the languages I'm familiar with (Python, JS/TS, Java, Kotlin), no auth is necessary to read public packages.

**Comment by kylegoetz** [comment]
Is there any interest in a PR for this? Looks like in Sync.hs

```haskell
pull ::
  -- | The HTTP client to use for Unison Share requests.
  AuthenticatedHttpClient ->
  -- | The Unison Share URL.
  BaseUrl ->
```

probably should take whatever the codebase's equivalent of `HttpClient | AuthenticatedHttpClient` and then have a `PullError` that is `PullErrorAuthRequired` or something if there's an attempt to pull a non-public lib.

I'm not familiar enough with the codebase to know more off the top of my head, but I do like this language enough that I'm writing some ancillary code to help with developing in Unison.

**Comment by ceedubs** [comment]
@kylegoetz authentication shouldn't be required to pull a public library. Are you seeing otherwise? I just tried to reproduce an issue and was unable to.

**Comment by kylegoetz** [comment]
@ceedubs  `pull hojberg/html` throws up the GitHub auth page in my browser, and if I decline the CLI says "Aborted"

I assume anything listed in unison share when I'm not logged in is public, and that was just a random package i picked to test this on after someone on Reddit criticized Unison for not allowing you to download from Share without signing up for GitHub.

**Comment by pchiusano** [comment]
@kylegoetz that's a bad error message, sorry about that - the command is `pull hojberg.public.html.latest` (or `pull username.public.projectname.releases.releaseName`) and it doesn't require authenticating.

<img width="893" alt="image" src="https://user-images.githubusercontent.com/11074/204873784-93a131f6-08cd-4b54-8cd4-895059a3763b.png">

You'll also be shown the right pull syntax if you click the download button in the sidebar when looking at the project release.

I'm going to rename this issue to track improving error reporting.

**Comment by aryairani** [comment]
I get
```
.> pull hojberg/html

  Oops, I received an unexpected status code from the server.
  
  Here is the request.
  
    Request
        { requestPath =
            ( BaseUrl
                { baseUrlScheme = Https
                , baseUrlHost = "api.unison-lang.org"
                , baseUrlPort = 443
                , baseUrlPath = ""
                }
            , "/ucm/v1/projects/project"
            )
        , requestQueryString = fromList
            [
                ( "name"
                , Just "hojberg"
                )
            ]
        , requestBody = Nothing
        , requestAccept = fromList
            [ application/json;charset=utf-8
            , application/json
            ]
        , requestHeaders = fromList []
        , requestHttpVersion = HTTP/1.1
        , requestMethod = "GET"
        }
  
  Here is the full response.
  
    Response
        { responseStatusCode = Status
            { statusCode = 400
            , statusMessage = "Invalid Parameter"
            }
        , responseHeaders = fromList
            [
                ( "Server"
                , "nginx/1.24.0"
                )
            ,
                ( "Date"
                , "Thu, 27 Jun 2024 02:16:29 GMT"
                )
            ,
                ( "Transfer-Encoding"
                , "chunked"
                )
            ,
                ( "Connection"
                , "keep-alive"
                )
            ,
                ( "X-RequestID"
                , "5e901a6e-e0b9-48c7-bae8-eafaa423d56e"
                )
            ]
        , responseHttpVersion = HTTP/1.1
        , responseBody = "Unable to parse parameter name, Project shorthand must be of the form @user/project"
        }

.> 
```

**Comment by hojberg** [comment]
Closing this as "loose code" is now deprecated and removed from UCM.
