### ISSUE TITLE
`pull` command "succeeds" when pulling from a namespace that does not exist

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#3648]
Currently when you `pull` a library that doesn't exist on share, the UCM will "succeed" by creating a namespace with zero entities. 

```
.> pull stew.public.projects.json.releases.v3 lib.json

 Downloaded 0 entities.

  ✅
  
  ✅ Successfully pulled into newly created namespace lib.json.
```

This might be ultimately desirable but this came up because of our Exercism track integration so it does have some interesting downstream effects. We were pulling something that had been deleted but silently failing to setup the testing environment.

**Comment by ceedubs** [comment]
> This might be ultimately desirable

I can't imagine the scenario in which this is what someone wants :)

**Comment by mitchellwrosen** [comment]
A discovery: `pull stew.public.projects.json.releases.v3` does exist; it has history, but no contents. We filter it out of the UI.

**Comment by mitchellwrosen** [comment]
So, is this a bug?

**Comment by aryairani** [comment]
What if we replace 
```
✅ Successfully pulled into newly created namespace lib.json.
```
with
```
⚠️ stew.public.projects.json.releases.v3 is currently empty, but has history. 
  Its history has been pulled into the newly created namespace lib.json.
```

**Comment by aryairani** [comment]
Another thing to keep in mind down the road is that we don't care about history in the context of installing a library, so then this definitely wouldn't be success.

**Comment by hojberg** [comment]
We have to be careful with the wording here. The mental model of the user is that they deleted something so it's gone, and we want to avoid breaking the illusion. Looking through history of things/doing recovery is often a more deliberate and separate task.

Maybe down the line this ought to be a prompt:

```
.> pull stew.public.projects.json.releases.v3 lib.json

  ⚠️ stew.public.projects.json.releases.v3 is currently empty, but has history. 
  
  Do you want to pull just the history: Y/n?
```
