### ISSUE TITLE
Showing values at runtime

### ISSUE THREAD

**Issue by francisdb** [unisonweb/unison#365]
For testing it would be useful to show the compared values if they are not equal. But as far as I can see there is no way to show the Text representation of a value at runtime like it is done by the repl for watch expressions?

Also related to the workaround for #364

**Comment by ChrisPenner** [comment]
Let's try to avoid haskell's problems where the 'Showable' representation is convoluted with the 'Representation' definition.

E.g. there should be two SEPARATE functions; one which shows a human readable version of the object, and one which prints a syntactically valid representation of the object which could be copy-pasted into a repl.

**Comment by plumenator** [comment]
Is the idea here to add a `toText` and `toRepresentation` for each type? Or is it to add a `Universal.toText`? Given that this is labeled a "good first issue", I guess it must be much simpler than that?

**Comment by pchiusano** [comment]
We now have `Debug.toText` https://share.unison-lang.org/@unison/p/code/latest/namespaces/public/base/latest/;/terms/Debug/toText

For fancy user-customized renderings, I think that's more like a typeclasses sort of use case.
