### ISSUE TITLE
`io.test` claims to look for test in the scratch file but does not

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#3654]
This one is quite annoying because you generally want to get tests passing before adding definitions to the codebase. 

```
  ...
  SemispaceCache.tests.ex1           : '{IO, Exception} [test.Result]

.distributed.main> io.test SemispaceCache.tests.ex1

  😶
  
  I looked for a function `SemispaceCache.tests.ex1` in the most recently typechecked file and
  codebase but couldn't find one. It has to have the type:
  
    SemispaceCache.tests.ex1 : '{IO, Exception} [test.Result]

.distributed.main>                                         
```

**Comment by ceedubs** [comment]
Hmm I had reported this as #2677 but seem to have prematurely marked it as resolved.

**Comment by ceedubs** [comment]
The workaround that I've been using is to use `run` instead of `io.test` until I get my test passing and add it. In the past you couldn't do this, but now `run` will work for functions with non-Unit return types.

**Comment by ChrisPenner** [comment]
From triage:
@mitchellwrosen would you have the bandwidth to pick this one up?

The goal would be: If I run `.> io.test mytest` it would find `mytest` if it's in the scratch file.

**Comment by mitchellwrosen** [comment]
Sure
