### ISSUE TITLE
Update website installation instructions with Rosetta for Apple Silicon

### ISSUE THREAD

**Issue by unorsk** [unisonweb/unison#3659]
Hey!

I tried installing unison with `brew` on `Apple M2 MacBook air, Ventura 13.0`

```
% brew install unison-language
unison-language 1.0.M4c is already installed but outdated (so it will be upgraded).
==> Downloading https://ghcr.io/v2/homebrew/core/fzf/manifests/0.35.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/fzf/blobs/sha256:7609e0c088fdc710b95226a1c5863cd967a17f30a42fd4a
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:7609e0c088fdc710b95226a1c586
######################################################################## 100.0%
==> Downloading https://github.com/unisonweb/unison/releases/download/release%2FM4e/ucm-macos.tar.gz
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/35164952/e7ccc5
######################################################################## 100.0%
==> Upgrading unisonweb/unison/unison-language
  1.0.M4c -> 1.0.M4e 

==> Installing dependencies for unisonweb/unison/unison-language: fzf
==> Installing unisonweb/unison/unison-language dependency: fzf
==> Pouring fzf--0.35.1.arm64_ventura.bottle.tar.gz
🍺  /opt/homebrew/Cellar/fzf/0.35.1: 17 files, 3MB
==> Installing unisonweb/unison/unison-language
🍺  /opt/homebrew/Cellar/unison-language/1.0.M4e: 72 files, 63.4MB, built in 1 second
==> Running `brew cleanup unison-language`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /opt/homebrew/Cellar/unison-language/1.0.M4c... (12 files, 59.7MB)
Removing: /Users/unorsk/Library/Caches/Homebrew/unison-language--1.0.M4c.tar.gz... (13.6MB)
```

Running unison:

```
% ucm
zsh: bad CPU type in executable: ucm
```

Here's what `file` returns:

```
% which ucm
/opt/homebrew/bin/ucm
% file /opt/homebrew/bin/ucm
/opt/homebrew/bin/ucm: Mach-O 64-bit executable x86_64
```

Here's just an example of running file on it self:
```
% file /usr/bin/file
/usr/bin/file: Mach-O universal binary with 3 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64] [arm64e:Mach-O 64-bit executable arm64e]
/usr/bin/file (for architecture x86_64):	Mach-O 64-bit executable x86_64
/usr/bin/file (for architecture arm64):	Mach-O 64-bit executable arm64
/usr/bin/file (for architecture arm64e):	Mach-O 64-bit executable arm64e
```

So far it just seems that unison binaries have't been built for M2. 

Or... am I doing smth wrong maybe? :)

**Comment by ChrisPenner** [comment]
Hi 👋🏼 ; You're correct that our mac binaries are still built on x86. We'd like to eventually provide native Apple Silicon builds, but that'll be some time further in the future.

I believe for now you should be able to simply install Rosetta (this is how I use ucm on my M1 mac and it works great), maybe try this?

```
usr/sbin/softwareupdate –install-rosetta –agree-to-license
```

**Comment by aryairani** [comment]
@unorsk Chris's reply didn't come through quite right on mobile.

You need to have Rosetta 2 installed, Apple's x86-to-ARM compatibility layer.

Can you try installing Rosetta 2 from your shell with the following command, and report back?

```
softwareupdate --install-rosetta
```

**Comment by unorsk** [comment]
Hey!

Thanks for the tips! I built it from source :)

With this ticket I just wanted to be helpful and report a problem I had when installing it with brew.

But before the problem gets addressed do you think it would be useful to include these instructions next to the installation instructions on the home page (may me some other places too)?

**Comment by hojberg** [comment]
@unorsk yeah we should definitely include this on the installation instructions.
I updated the title of this issue to reflect that work (let me know if there were any other outstanding issues with M2).

**Comment by unorsk** [comment]
Just tried the rosetta thing – works like a charm ✨

**Comment by hojberg** [comment]
Alright, got the website updated with a little rosetta help modal.
