### ISSUE TITLE
Complains about known unknown type

### ISSUE THREAD

**Issue by francisdb** [unisonweb/unison#366]
```haskell
type Value = Nested Value
           | Foo

Foo.format : Value -> Text
Foo.format v = case v of
  Value.Foo     -> "foo"
  Value.Nested v -> Foo.format v

> format (Value.Nested Value.Foo)
```

As you can see below this fails to compile and the error points to the correct `Foo.format` but says it doesn't know about it?

```
master>
I don't know about the type Foo.format.  Make sure it's imported and spelled correctly:

    9 | > format (Value.Nested Value.Foo)
```

If we switch to the fully qualified name the watch expression executes correctly

```
  ┌
  │  9 | > Foo.format (Value.Nested Value.Foo)
  │        ⧩
  │        "foo"
  └
```

And strangely another way to fix this is to not use the fully qualified name in the `case`

```haskell
type Value = Nested Value
           | Foo

Foo.format : Value -> Text
Foo.format v = case v of
  Value.Foo     -> "foo"
  Value.Nested v -> format v

> format (Value.Nested Value.Foo)
```

```
  ┌
  │  9 | > format (Value.Nested Value.Foo)
  │        ⧩
  │        "foo"
  └
```

**Comment by aryairani** [comment]
Hi @francisdb, did you mean rt1 branch?

Could you include a complete / minimized example?

Thanks for the report!

**Comment by francisdb** [comment]
@aryairani sorry about that, came up with a clean short test case and modified the issue. Somehow using a fqn in the `case` seems to have influence on an other place where the same name is used.

**Comment by pchiusano** [comment]
This example works fine in current master, so I'm going to close, but we're probably going to revisit how TDNR works, tracked in #448.

<img width="1153" alt="Screen Shot 2019-04-29 at 2 33 50 PM" src="https://user-images.githubusercontent.com/11074/56918374-d51da900-6a8b-11e9-92c6-073286026558.png">
