### ISSUE TITLE
edit command: openFile: resource busy (file is locked)

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#3664]
It's pretty common to see this `openFile: resource busy (file is locked)` error when running the `edit` command. I think that I might see it more when editing multiple terms at a time, but I'm not sure.

Everything seems to work fine. But the following error displays:

```
edit ?
‼  Got an exception while reading: /home/username/unison/aoe2022_unison/scratch.u
/home/username/unison/aoe2022_unison/scratch.u: openFile: resource busy (file is locked)
```

**Comment by ChrisPenner** [comment]
I think we either need to be less lazy when writing to file, or just move the file system IO out of our Output message handler.

Should also probably do all of the appends in memory before writing them out.

**Comment by ChrisPenner** [comment]
Confirmed that this doesn't happen if you disable file-watching with `--no-file-watch`; so I think the file-watcher is trying to read the file while we still have it open for writing.

Can probably solve this by just interleaving the actual file-reads for the watcher in between the UCM command loop.
