### ISSUE TITLE
Doc rendering crash

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#3668]
Suspect this is a compilation / decompilation bug, but certain docs can trigger a crash in doc rendering:

```
Encountered exception:
can't hashComponents if bindings have free variables: [ "User "v"" ]
    [ "User "d""
    , "User "d2""
    , "User "d"-1"
    ] CallStack ( from HasCallStack ) :
   error
```

The message is a bit confusing. Doc rendering uses the same evaluation cache as watch expressions. So for the backticked blocks in the doc, it hashes them and checks if it's already evaluated that hash. So I suspect compilation or decompilation is producing an expression that's not closed.

[Slack discussion](https://unisoncomputing.slack.com/archives/CF8D3DCP3/p1670383673148639?thread_ts=1670357266.932529&cid=CF8D3DCP3)

**Comment by ceedubs** [comment]
I think that this was fixed by #3671.
