### ISSUE TITLE
Add ability to delete multiple terms at once time 

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#3673]
From our stream earlier, we discussed the need to be able to delete more than one term at a time. Capturing in an issue here:

Here are some possible commands we'd like to run: 

```
.> delete.term 1-3
.> delete.term myTerm1 myTerm2 myTerm3
```

**Comment by ChrisPenner** [comment]
From triage: This would be a quick win, do @mitchellwrosen  or @tstat  have space to pick this up?

**Comment by mitchellwrosen** [comment]
Sure

**Comment by rlmark** [comment]
Hey @mitchellwrosen, not sure if you've started this, but I'm planning on a "intro to contributing to the UCM" blogpost series wherein I chronicle the process of working with the UCM as a newcomer and I think this one might be a good walk-through issue. If you haven't started this, do you mind if I take it?

**Comment by mitchellwrosen** [comment]
Go ahead!

**Comment by aryairani** [comment]
Currently in-progress. (@rlmark)

**Comment by rlmark** [comment]
Ticket cleanup - this has been closed for a while by #3798.
