### ISSUE TITLE
Nat.fromText gives incorrect results above maxNat

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#3674]
`Nat.fromText` gives the expected output for `maxNat`, but above that it wraps around instead of returning `None`.

```
    1 | > Nat.fromText "18446744073709551615" -- maxNat
          ⧩
          Some 18446744073709551615
  
    2 | > Nat.fromText "18446744073709551616" -- maxNat + 1
          ⧩
          Some 0
  
    3 | > Nat.fromText "18446744073709551617" -- maxNat + 2
          ⧩
          Some 1
  
    4 | > Nat.fromText "23097243598672405972349872359862405982349862354097234098" -- some big number
          ⧩
          Some 9163169909142151346
```

**Comment by dolio** [comment]
This does match what you'll get if you just type in literal numbers.

**Comment by ChrisPenner** [comment]
Options include:
* Parsing an overflowing nat returns `None`
* Parsing an overflowing nat throws an exception
* Parsing an overflowing nat overflows.

Probably needs more discussion.

**Comment by ceedubs** [comment]
I think that since `Nat.fromText` already returns an `Optional Nat`, most people would expect this case to return a `None`.
