### ISSUE TITLE
Nat.range and Nat.rangeClosed hang when argument "from" is greater than argument "to"  

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#3676]
When given two nat values "from" and "to" where "from" is accidentally greater than "to", the UCM will hang instead of returning empty list or an error:

```
> Nat.range 3 1 
```

**Comment by runarorama** [comment]
This is M4e with latest `main` of Base:

```
    1 | > Nat.range 3 1
          ⧩
          []
```

**Comment by rlmark** [comment]
Closed as this hasn't been reproducible since the stream! 🤔
