### ISSUE TITLE
Runtime crash with `Universal.compare` on closures over `Array`s

### ISSUE THREAD

**Issue by dfreeman** [unisonweb/unison#3678]
I initially ran into this via [`anovstrup.public.memo`](https://share.unison-lang.org/@anovstrup/p/code/latest/namespaces/public/memo), but poking around narrowed down a reproduction to:

```
a = Array.fromList []
Universal.compare 'a 'a
```

The call to the `compare` builtin crashes UCM with a segfault, seemingly for any values that close over an array.

OS: macOS 11.7
UCM version: release/M4e (built on 2022-11-23)

**Comment by pchiusano** [comment]
@dfreeman this is an amazing, minimal bug report, thank you so much! We'll get this fixed ASAP.
