### ISSUE TITLE
share: handles with hyphens

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#3690]
There are at least a couple of users who got Share handles with hyphens (`-`) in them because those were present in their github handles when they initially performed oauth. Pushing to `handle-with-hyphen.public.foo` doesn't work, leaving these people no way to push to Share.

Is there a good reason that we don't allow hyphens? Are there other characters that would hit this same issue?

If so, we could potentially remove the hyphens from those handles, but we need to beware of what would happen if removing the hyphen caused a collision with another user handle.

On a related note, we need to be aware that github handles can be changed. So when we are creating an account for a github handle we probably shouldn't assume that this is the only github account that has ever owned that handle, and we should make sure that there isn't a handle collision. Preventing handle collisions will need to happen anyway when we start supporting more OAuth providers.

**Comment by ChrisPenner** [comment]
So far we've been treating the first path segment as needing to be a valid path identifier in UCM, but I think we probably want to start switching to the `@user/project.namespace` syntax or something like that anyways, so we should probably do that.

I believe we check that the github user ID matches when users log in, so I don't think anyone can _steal_ an account right now, but we've always planned to have a "Handle selection workflow" just haven't gotten to it yet 🙃 . @hojberg 

Let's decide what to do with this in the next triage meeting 👍🏼
