### ISSUE TITLE
Proper pull.without-history support for Share

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#3699]
Right now you can use `pull.without-history` and point it at a Share address and it does pull, but it downloads all of the history. Or at least it's as slow as `pull`. For me pulling `unison.public.base.main` in a fresh codebase takes 10 minutes whether I use `.without-history` or not.

Generally library authors should probably solve this by creating (squashed) releases. But there are some use-cases that `pull.without-history` would help support:

1. Adding a library that doesn't have proper releases as a dependency. It is a pain to spend a long time pulling it just to squash it and add the squashed version to `lib`.
2. CI builds. Since we can't run CI on Share, we need to pull from Share to get code onto our CI box. It would be nice to not have to spend the first 10 minutes of the CI build doing that.
3. Pulling the code to run a program. Let's say that I just want to run a web app that's published on Share. I should be able to pull it and compile it to something that ucm can run without pulling the whole history.
  - @ChrisPenner and I talked about a potential command like `pull.compile ceedubs.public.mywebapp.main main` that pulls  a single executable term and compiles it to a `main.uc` file. But Chris said that implementing `pull.without-history` is probably easier, and I think that it satisfies more use-cases.

**Comment by mitchellwrosen** [comment]
One issue here is that namespaces contain their childrens' histories. So, I think solving this one in the right way will need some workshopping.

**Comment by ceedubs** [comment]
Another data point:

While pulling `unison.public.base.main` in a fresh codebase takes ~10 minutes, pulling `unison.public.base.latest` (which is squashed) takes less than 20 seconds.

**Comment by ceedubs** [comment]
Somewhat related: #3314

**Comment by ChrisPenner** [comment]
Closed in https://github.com/unisonweb/unison/pull/4301
