### ISSUE TITLE
transcript and transcript.fork: accept output path

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#3701]
Currently if you use `transcript` or `transcript.fork` with the `--save-codebase` argument, it saves the output codebase to a random tmp file.

In some cases, it's useful to be able to control where the output codebase is saved. For example:

- A Docker/CI build in which you want to use a transcript to pull a codebase for use by later commands.
- A transcript (or series of transcripts) that automate a task such as generating releases of libraries.

I've written shell script glue several times that accomplishes this task in a roundabout way, but it would be so much nicer to be able to do something like `--save-code-base-to /root/code`.

```sh
workdir=$(mktemp -d)
TMPDIR="$workdir" ucm transcript --save-codebase my-transcript.md
output=$(find "$workdir" -mindepth 1 -maxdepth 1 -type d)
mv "$output/.unison" /path/that/i/actually/want/.unison
```

**Comment by jaredly** [comment]
Fixed by https://github.com/unisonweb/unison/pull/3785
`--save-codebase-to` / `-S`
