### ISSUE TITLE
Syntax error on doc with inlined let

### ISSUE THREAD

**Issue by alvaroc1** [unisonweb/unison#3708]
```
someDoc = {{
  ``
    let
      double x = x * 2
      double 4
  ``
}}
```
```
.alvaro.experiments> 

  offset=20:
  unexpected end of input
```

Same if i replace `let` with `do`, or if i try to append `()` at the top-level.
Works fine with triple-backticks

**Comment by aryairani** [comment]
@alvaroc1 We think it's correct that this is an error (though the error message itself is lousy). Double-backticks aren't meant to support block expressions. We recommend using triple-backticks.
