### ISSUE TITLE
Misleading error message when defining an infix function wrong.

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#371]
```haskell
a (==) b = case (a,b) of
  ((ta, va), (tb, vb)) -> ta == tb && va == vb  
```
![image](https://user-images.githubusercontent.com/538571/54065010-99333980-41e8-11e9-817e-501ab2129a93.png)
The program is wrong, but the mistake was "You wrote `a (==) b = ...` instead of `a == b = ...`".
The error makes a bit more sense when we use different variable names:
```haskell
f p q = case (f,q) of
  ((x,y), (z,w)) -> x == z && y == w
```
In one spot, `f` is expected to be a function; in another, it's expected to be a tuple.
Let's check for this case explicitly; we might consider some way of giving alternative error messages:
> If you are trying to define a function called `a`, then I'm confused because you're using it \<here\> as a tuple.   If you are trying to define an infix function called `(==)`, then you need to remove the parentheses  from \<here\>.

**Comment by pchiusano** [comment]
Also you can define `(==) a b = ...` which works also.

What about the following - if a function takes two arguments, the first of which is `(==)` or any other operator, emit a note to the user:

> I'm interpreting `(==)` as a parameter to the function `a`. Within the body of `a`, `e1 == e2` will mean calling this function. If you meant to define a function `(==)` that takes two arguments `a` and `b`, that's written as `a == b = ...` or `(==) a b = ..` Use `> hints.disable infix-definitions` to disable this message for next time.

I think it might otherwise be hard to come up with a general way of reporting this nicely that doesn't have false positives and covers all the cases (but do you have some ideas for this?)

If you remove the effect variable noise and the location were reported accurately, the error is not terrible, in conjunction with the above note which will appear before the type error.

**Comment by pchiusano** [comment]
Maybe this is the same as #396 ?

**Comment by pchiusano** [comment]
@aryairani if you don't have ideas for a general algorithm (I suspect it's not possible - there are many ways the type error might manifest if the user makes this mistake, or not!! - but am happy to be proven wrong if you've got ideas), I'm going to go with my idea of just emitting a note to make sure the user understands the meaning of the syntax they typed.

This will also provide a good excuse for thinking about having some local dotfile state that lets hints and other info be shown initially, but then turned off as the user wishes.

**Comment by aryairani** [comment]
@Paul Yeah, sorry I haven’t put thought into it.  

I think a great step towards improving this and other weird error messages would be to add a debug command that prints the raw type error even when there was a formatted version like this available.  I’m on mobile so can’t check/remember exactly what should go in it, but probably the typechecker context at a minimum.  ie stash it in the LoopState and print it in demand.  Basically a “get more detail about this error” that will be a tool we use to improve bug reports and user messages goin forward.

And then yeah, can also add a warning for now; however you see fit.

**Comment by aryairani** [comment]
Updated for M1l:
```
a (==) b = match (a,b) with
  ((ta, va), (tb, vb)) -> ta == tb && va == vb
```

![image](https://user-images.githubusercontent.com/538571/80925995-4b6d7f00-8d62-11ea-804e-faf7735cca74.png)
