### ISSUE TITLE
Idea: allow non-unit returning actions as long as the value isn't a function type

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#3726]
This catches all the "undersaturated function call to an effectful function" mistakes, but doesn't require putting `void` everywhere. 

Idea from @systemfw

**Comment by ChrisPenner** [comment]
This will re-allow docs as comments too 👍🏼

**Comment by ceedubs** [comment]
> This will re-allow docs as comments

It's unclear to me whether this is a good thing 😀. Adding a doc to a line of code in your function means that the doc will be evaluated every time that line is hit. I don't think that this is what users would expect. We'll probably need a better story for inline docs at some point.

Outside of the context of docs, the proposed approach does have the downside that it would miss some potential forms of bugs. For example if you might have something like:

```
Remote.forkAt locationWithUserData do saveUser userId
doStuffWithUser userId
```

when really you want the user save to finish before doing stuff. The first line returns a `Task`, so you might have meant to `await` it:

```
Remote.await (Remote.forkAt locationWithUserData do saveUser userId)
doStuffWithUser userId
```

A possibly better example is if something returns `Either Failure ()` and you call it without remembering to handle the `Failure` case (maybe you want to log it).

It's a case of finding the sweet spot in a balancing act of catching potential bugs but making code noisier. Personally I don't mind being a bit more explicit/verbose if I really want to ignore a result if there's a 1% chance that it catches a bug for me. But I run a bit on the paranoid side, and this proposal might be about the right balance for most people.

**Comment by SystemFw** [comment]
I don't know, I personally still slightly prefer programs-as-values to Unison's direct style, but one of the advantages of direct style is that you can write simple looking imperative code, and having to add `void do` all over the place obscures that to the point that I found myself using suspended computations and combinators again instead (which sort of defeats the point).

re: docs as comments, I have to admit I didn't consider the point about evaluation, that sounds like a footgun for sure. But as you say, I do think inline comments are needed (e.g. often in concurrent code you want to document an invariant)

**Comment by pchiusano** [comment]
I think @ceedubs has sold me here. Those are both pretty good examples. If you're ignoring a non-Unit value, you're discarding information, and some % of the time that's a bug. Might not be a majority of the time, but enough that asking the user to type literally two extra characters `_=` (no spaces needed, if you prefer) feels like the right tradeoff to me. They get a message that `Either Failure ()` isn't the same as `()` or whatever, with a helpful tip on how to dismiss it, and they have to give it a moment's thought.

However, a couple things:

* We should definitely fix https://github.com/unisonweb/unison/issues/3773
* In the meantime there's `ignore : a -> ()`, which you can do instead of `void do blah`
* When designing APIs, I've noticed you can sometimes arrange things to separate the "take an action" step from the "return a value". For example, in a parsing library, most leaf-level parsers can return `()`, and then you have a separate `slice` combinator that goes from `'{Parse} a -> '{Parser} Text`, returning the portion of the input that the input parser consumed, if you need that.
