### ISSUE TITLE
LSP: resource vanished when scratch file is closed

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#3732]
When I am working in a Scratch file with LSP enabled (in Vim, but I imagine that this would happen for other editors as well), and then I close that Scratch file, I often get the following in my UCM window:

```
.myproject.main> <socket: 76 >: hPutBuf: resource vanished ( Broken pipe )
```

As far as I can tell there aren't any other issues; just the error message.

**Comment by ChrisPenner** [comment]
Yeah this shouldn't cause any issues, but it'd be nice to silence it. I wonder if this is happening inside the `lsp` lib, or maybe I can just catch and silence this particular exception in the right spot.
