### ISSUE TITLE
LSP returns empty hover response, rather than null, when no information is present

### ISSUE THREAD

**Issue by pragdave** [unisonweb/unison#3739]
<img width="1334" alt="Screenshot 2023-01-11 at 8 14 33 PM" src="https://user-images.githubusercontent.com/10648/211960078-5770c6f0-5b38-45b5-a71f-be6010656e33.png">

With my cursor over `twoDigit` on line 12, I hit K in vim to get the hover text. The Vim Lsp code blows up because the HoverResponse it received contains no text.

My reading of the LSP spec suggests that a Null response should have been sent.

**Comment by ChrisPenner** [comment]
Thanks for the report!
Hopefully this should do it: #3751 

Also note I've got a whole re-work of the hover feature here #3637 ; but there are a few parser bugs that need to be fixed for it to work properly so it's been delayed a bit.
