### ISSUE TITLE
Compare and swap primitives for IO refs

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#3741]
Propose adding the following builtins, backed by [this library](https://hackage.haskell.org/package/atomic-primops-0.8.4/docs/Data-Atomics.html#t:Ticket).

```Haskell
builtin type Ref.Ticket a

Ref.ticket : Ref {IO} a ->{IO} Ref.Ticket a
-- Ref.ticket.barrier : Ref {IO} a ->{IO} Ref.Ticket a
Ref.Ticket.read : Ticket a ->{} a
Ref.compareAndSwap : Ticket a -> a -> Ref {IO} a ->{IO} Boolean
```

The scheme runtime can literally just implement `Ticket a` as `a` for the runtime implementation.

**Comment by SystemFw** [comment]
Solved by #3745
