### ISSUE TITLE
Suffix-based resolution picks name in codebase instead of file

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#3759]
In your codebase, have a definition `Foo.state`. 

Then in the file, have `type Blah = { state : Nat} ` and use `state` unqualified. It picks the `Foo.state` in the codebase.

Another example - in the codebase, have a type `blah.Foo`, then in your scratch file have:

```
unique type OoogaBooga.Foo = Foo Text

unique ability Blah where
  foo : Foo -> ()

oog = do 
  foo 42
```

It resolves the `Foo` type suffix there to the codebase `blah.Foo` rather than the `OogaBooga.Foo` that's declared in the scratch file.

**Comment by aryairani** [comment]
@pchiusano to create a transcript to start with. Cody recommends not involving records if possible.

**Comment by ceedubs** [comment]
To clarify: I'm not recommending not involving records. I was just thinking out loud that record types might be the toughest case to support. My understanding is that it's kind of a two step process where the record type is saved and then accessor methods for it are generated and saved. So picking up the new accessor method that _would_ be generated from a record type defined in the scratch file seems like it could be a tough case. But it would definitely be nice for it to work!

**Comment by aryairani** [comment]
Is it not detecting non-uniqueness of suffixes between the file and the codebase?
