### ISSUE TITLE
Doc doesn't linkify a reference to a function called link

### ISSUE THREAD

**Issue by alvaroc1** [unisonweb/unison#3761]
trying to reference a function called `link` using the `{link}` syntax, but the ucm (and share) seem to ignore it:

<img width="404" alt="Screenshot 2023-01-21 at 10 57 20 AM" src="https://user-images.githubusercontent.com/107395/213880583-557ad645-eb96-4d3e-a1a1-42a0f7781f54.png">
<img width="529" alt="Screenshot 2023-01-21 at 10 59 09 AM" src="https://user-images.githubusercontent.com/107395/213880586-54537e41-5f16-4fb7-8e95-41d3aebf8c05.png">

**Comment by hojberg** [comment]
Looked this over. The JSON we got delivered to the frontend treats this node as a `Word`, not a link. I think this might be a parser bug?

Reassigning.

**Comment by hojberg** [comment]
@aryairani I'm not sure who best to look into this, but seems like a small win?

**Comment by aryairani** [comment]
Judging based on the output of the `display` command, this seems to be fixed.
<img width="361" alt="image" src="https://github.com/unisonweb/unison/assets/538571/b9d3c7ce-18ec-40cb-9679-8f5d43ab0b0b">
