### ISSUE TITLE
implement `move` command that moves term, type, and child namespace

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#3767]
This would be a pretty nice quality of life improvement.

How many times have you done `move.type Foo Bar` and `move.namespace Foo Bar` (to get the constructors and helper functions?) Why not just do both in the same command? (If you really meant to only move the type, which I'm pretty sure I have never wanted, you can always just `move.namespace Bar Foo` the the namespace back to its original location)

Likewise for `move.term` (move the terms underneath, including docs). 

Implementation notes, for anyone who wants to take this on:

* If there's no child namespace, it can just noop for the `move.namespace` part. 
* And you can look at the `move.namespace` logic and call into that in `move.term/type`.
* This logic all lives in `HandleInput`

**Comment by ceedubs** [comment]
@pchiusano wdyt about a `move` command that does _all_ of `move.term`, `move.type`, and `move.namespace`? You could potentially add that and not change the functionality of the existing commands.
