### ISSUE TITLE
Destructuring binds probably shouldn't accept guards

### ISSUE THREAD

**Issue by ChrisPenner** [unisonweb/unison#3769]
@pragdave found this one;

Currently this snippet compiles:

```unison
func val =
  (a, b) | a < 10 = val
  a
> func (1,2)    -- succeeds
> func(99, 2)   -- fails at runtime
```

It's likely just a quirk of the parser that this is accepted at all, but we probably shouldn't allow guards on destructuring binds; unless there's some feature here that I'm missing that causes it to make sense.

**Comment by pchiusano** [comment]
Yeah, agree, though also, the pattern coverage checker will catch this (as a type error, rather than a parse error) once that merges. #3737
