### ISSUE TITLE
Allow multiple (ignored) bindings called `_` in a block

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#3773]
Due to a quirk of the parser, this isn't allowed:

```haskell
foo = 
  _ = 1
  _ = 3
  1 + 1
```

The `_` is parsed as a regular variable name! And you can't have multiple bindings of the same name in the same block.

One easy fix without shaking things up:

`_ = blah` parses as `_ignore_<digits> = blah` 

(Where `<digits>` is just some random location-dependent digits, guaranteed unique in the file, which we use for other things in the parser.)

That is, it's just a regular binding with a special name. In the typechecker, for bindings whose name has this form, we can switch off the check that it be of type `()`. The prettyprinter can then print variables of this form just as `_`.

Alternately we could leave the typechecker alone and have it parse as `(_ -> ()) blah`, and then the pretty-printer elides this lambda if the binding name has the right form. I don't like this as much.

**Comment by ceedubs** [comment]
It's nice that `_ = blah` isn't many characters to type, but it feels a bit clunky to me. This adds an exception to the rule of what variable assignments do, and for a not-obvious effect. `ignore blah` is more characters but avoids special cases and seems more obvious to users. And if you see it on Share you can click on `ignore` to see what it does which isn't true for `_ = blah`.

Or we could name it `discard` or whatever.
