### ISSUE TITLE
Incomplete definition block not closed by 0 indentation

### ISSUE THREAD

**Issue by francisdb** [unisonweb/unison#378]
I would expect the incomplete `test =` block to end at `x = ...` but it seems not to be the case. In a large file this is annoying because the error is reported far away from the source and sometimes you get totally unrelated errors.

```haskell
type Either a b = Left a | Right b

test : Text -> Boolean
test =

x = Right 1
y = Right 2

test2 : Text -> Boolean
test2 t = t == "ok"
```

currently the error is reported at the end of the file somewhere

```
master>
I found a block that ends with a binding instead of an expression at line 9, columns 1-6:

    9 | test2 : Text -> Boolean

Based on the context, I'm expecting an expression of type Text -> Boolean after this binding.
```

haskell will report on the `x = ...` line with `parse error (possibly incorrect indentation or mismatched brackets)`

**Comment by pchiusano** [comment]
@francisdb if you want to take a crack at this, you could look in the lexer. After a token that introduces layout, like `=`, the lexer looks for the first non-whitespace column, which is used to determine the leftmost column of the block. If that column is 0, it should probably just close the block.

**Comment by francisdb** [comment]
Looking into this one

**Comment by francisdb** [comment]
thanks for pointing me to the related code
