### ISSUE TITLE
open in browser doesn't work on windows

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#3796]
allegedly!

**Comment by hojberg** [comment]
We use [open-browser](https://hackage.haskell.org/package/open-browser) fwiw, which is meant to include Windows support.

**Comment by aryairani** [comment]
This does work for me today; provided ucm can find the ui files.
<img width="937" alt="image" src="https://github.com/unisonweb/unison/assets/538571/0072d3e4-c6a1-4b91-a88a-85266ef6faec">
