### ISSUE TITLE
`dependents` and `dependencies` should be scoped

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#3803]
The `dependents` and `dependencies` functions are currently outliers because they operate in the global namespace instead of the current namespace. Instead they should only find dependents/dependencies in the _current_ namespace. Or, if projects are supported before this ticket is addressed then they should probably be scoped to a project instead of a namespace.

This was mentioned in #3403 but I didn't create a proper issue for it.

As a bonus, applying these commands with a smaller scope will probably make them faster.

**Comment by ceedubs** [comment]
There's also the question of whether they should give special treatment to the `lib` namespace, but I think that's a secondary issue.

**Comment by pchiusano** [comment]
Here's a particularly bad example: 

<img width="644" alt="image" src="https://github.com/unisonweb/unison/assets/11074/0d2ef3ea-644c-4cad-83a6-f6181eb69e8f">

Not sure why we are including the same reference once for every name it has globally. User can always do a `names` or `names.global` if they want all the aliases for a thing.

**Comment by pchiusano** [comment]
@mitchellwrosen I'm taking a crack at this, it's been super bugging me for refactoring stuff.
