### ISSUE TITLE
TLS example code (IO.net.Tls) doesn't work

### ISSUE THREAD

**Issue by jaredly** [unisonweb/unison#3808]
https://share.unison-lang.org/@unison/p/code/latest/namespaces/public/base/latest/;/types/IO/net/Tls

The example given, "Connect to a TLS server" doesn't work
```
socket = Socket.client (HostName "google.com") (Port "443")
config = ClientConfig.default (HostName "google.com") ""
tls = newClient config socket
conn = handshake tls
TlsSocket.send conn (toUtf8 "GET / HTTP/1.0\r\n\r\n")
response = TlsSocket.receive conn
TlsSocket.close
response
```
for a couple of reasons, `TlsSocket.close` needs an argument, and then `TlsSocket.send` fails hard on evaluation, with the following runtime error:
```
  dumpData: bad closure: Foreign (Wrap ##Tls _)
  expected type: #00nv2
```

I did manage to get a TLS example running, based on [tls.md](https://github.com/unisonweb/unison/blob/trunk/unison-src/transcripts-using-base/tls.md), but I had to do some nonstandard things:
```ucm
.> builtins.mergeio
.> cd builtin
.> load unison-src/transcripts-using-base/base.u
.> add
```
and then I was able to get this to run:
```
getExample _ =
    socket = clientSocket "example.com" "443"
    config = ClientConfig.default "example.com" Bytes.empty
    tls = newClient config socket
    reraise (handshake.impl tls)
    send tls (toUtf8 "GET /index.html HTTP/1.0\r\n\r\n")
    fromUtf8 (receive tls)
```

**Comment by runarorama** [comment]
This was a bug in the doc. I've changed it to be:

```unison
socket = Socket.client (HostName "google.com") (Port "443")
config = ClientConfig.default (HostName "google.com") ""
tls = newClient config socket
conn = handshake tls
send conn (toUtf8 "GET / HTTP/1.0\r\n\r\n")
response = receive conn
_ = close conn
fromUtf8 response
```

The issue was that the `close` function was missing an argument.

**Comment by jaredly** [comment]
@runarorama it's true that the close function needed an argument, but it still crashes for me with that fixed 🤔

**Comment by runarorama** [comment]
I'm not able to reproduce that. Tested with UCM version M4f as well as a trunk build as of this morning, both with `main` and `v1_1_0` of Base.

Which versions are you using?
