### ISSUE TITLE
Small parser bugs with underscores

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#381]
None of these parse:

```
_foo_ = x
```

Doesn't like underscores in the beginning of identifiers.

```
foo_ _ = x
```

Doesn't like arguments named `_`.

**Comment by mrdziuban** [comment]
I'd like to take a stab at this if that's alright @runarorama. Anything I should know before jumping in?

**Comment by runarorama** [comment]
@mrdziuban go for it! Can’t think of anything special to know, start by looking for how the lexer is treating underscores.

**Comment by mrdziuban** [comment]
Thanks! Just opened up #382.
