### ISSUE TITLE
LSP autocomplete misses some definitions

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#3849]
I apologize in advance if this turns out to be because of an issue with my editor/LSP setup.

When I trigger LSP autocompletion (with coc.nvim in neovim -- not sure how relevant that is), some definitions work great and some seem to be evasive. And even more confusing is that adding more matching characters makes some results go away.

For example, the prompt `List.ma<COMPLETION>` produces reasonable results (though I'm a bit surprised that `List.map` doesn't appear before `List.maximum` based on alphabetical ordering):

<img width="478" alt="Screenshot 2023-03-03 at 11 00 21 AM" src="https://user-images.githubusercontent.com/977929/222767520-4e63b8e7-edd5-485d-be4e-19034c837218.png">

The top results that show `[LS]` are completion results provided by the LSP server while the bottom `[A]` result is a fallback completion from the current buffer. So a `List.map` result isn't being shown from LSP but that may just be a cutoff of 5 results being applied.

But things get more perplexing when I add more characters.

`List.map<COMPLETION>` doesn't return any results from LSP.

`List.max<COMPLETION>` returns `List.maximum.tests.base` but not `List.maximum`:

<img width="545" alt="Screenshot 2023-03-03 at 11 02 46 AM" src="https://user-images.githubusercontent.com/977929/222768298-c8c25bac-0fd2-4fd4-b7fa-9b54da984e53.png">

`List.maxi<COMPLETION>` doesn't return any results.

**Comment by ChrisPenner** [comment]
@ceedubs Hrmm, I pulled base and am not able to reproduce on a fresh codebase with base in it in either VS Code or COC; 

I do know there's a bug where CWD of the LSP doesn't always get set correctly when using the `-p` startup option, maybe try again after cd-ing into your project without using that option?

There's one other thing, which is that the client can choose when it asks for more completions after you add more characters, so I actually wouldn't be terribly surprised if that was affecting this. 

Would you mind trying in VS Code as well?

If you're able to reproduce it, roughly what's in your codebase and which namespace is your UCM in when getting these completions?

**Comment by ChrisPenner** [comment]
Also what's up with that image?

![image](https://user-images.githubusercontent.com/6439644/222809686-d8bd074e-f76a-4c55-b5f4-121e07af42ac.png)

Why is your client matching the `ma` spread out in reverse order when there's clearly a prefix that matches better 🤔 
That definitely makes me think the issue could be with COC since the highlighting is done by the client.

**Comment by ceedubs** [comment]
@ChrisPenner oh wow I hadn't noticed the bizarre thing that it's doing with `ma`. Thanks for pointing that out, and for taking a look at this. coc.nvim made some breaking changes to completion to not use the native vim completion popup and in my attempt to work around it I probably messed something up. This sounds like an issue with my setup and not Unison so I'm going to close out the issue while I investigate.
