### ISSUE TITLE
Why `Text.==` but no `Bytes.==` ?

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#3857]
There is a builtin for `Text.==`, but I don't see one for `Bytes.==`. Is there a reason for this?

It's not a big deal, because universal equality on `Bytes` seems to work fine. But it seems odd to have `==` for one and not the other since they are otherwise so similar.

**Comment by pchiusano** [comment]
No good reason, really. A while ago there was a thought that the non-universal `==` might be able to be more efficient, but for necessarily boxed values like `Text` and `Bytes` that's not really true and we've stopped adding special case builtins. 

We do still have `Nat.==` and so forth, but those types can turn into unboxed values in some situations, so having a specialized operation is potentially more useful for efficiency of generated code.

**Comment by ChrisPenner** [comment]
Might be worthwhile just aliasing the universal one into `Bytes.==`, I just went looking for this and was surprised to not find it.

**Comment by aryairani** [comment]
Suggest adding a wrapper to `base` with the specialized type
