### ISSUE TITLE
docs not found for alias

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#3859]
This is a problem for both the `docs` ucm command and for Share.

`Universal.eq` and `Universal.===` are both aliases for the universal equality builtin.

## Share

If you search for `===` within the base library on Share, you get a result for `===`, but it doesn't show any docs. If you happen to know that it's also called `Universal.eq` then you can search for `Universal.eq` and the term you see is still called `===` (which is confusing but that's kind of a separate issue), but when you click on it you actually see the `Universal.eq.doc`.

## UCM

```
.unison.public.base.latest> names ===
              
  Term                                                                                                                                  
  Hash:   ##Universal.==                                    
  Names:  Universal.=== Universal.eq
                                                                                                                                        
  Tip: Use `names.global` to see more results.
                                                                    
.unison.public.base.latest> docs Universal.===                
         
  😶        
   
  No results. Try using the `link` command to add metadata to a definition.

.unison.public.base.latest> docs Universal.eq
  
  Structural equality of two Unison objects of the same type....
  ```

## Expected behavior

It's not obvious to me what the behavior _should_ be. There is a convention of looking for a doc under the term name concatenated with `.doc`, so one could argue that the current functionality works (if you set aside weirdness with not getting the name that you searched for). But I think that it would probably be more useful to do something like:

1. Find all names (within the current namespace) for the term.
2. Try `name.doc` for each name returned by step 1.
3. If there are multiple docs I guess we just prioritize the one for the provided name. Though we could maybe show all?

**Comment by runarorama** [comment]
Fixed in `trunk`. Thanks for reporting! Just aliased `Universal.eq.doc` to `Universal.===.doc`

**Comment by ceedubs** [comment]
@runarorama thanks!

But I guess I was thinking of this as an issue bigger than `===`. In general if people add aliases (especially symbolic aliases, as that's a common use-case), do we want them to need to alias their docs? Maybe it's fine.

**Comment by runarorama** [comment]
Hmm good question. I've opened #3860 to track.
