### ISSUE TITLE
LSP: diagnostic for incorrect handler type

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#3871]
Put the following watch expression in a scratch file:

```
> handle abort with 3.1
```

ucm will provide the following error:

```
  The handler used here
  
      1 | > handle abort with 3
  
  has type Nat but I'm expecting a function of the form abilities.Request e a -> o.
```

But I don't get a diagnostic error from the Unison language server. Apologies if this is because of something wrong with my LSP setup (again) 😬.

**Comment by ChrisPenner** [comment]
Looks like I probably just need to add another custom handler 👍🏼 
I'll try to get to this in the next off-week.
