### ISSUE TITLE
doc literals: treat unison code blocks as unison

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#3873]
If you put the following in a `Doc`:

````
```
1 + 1
```
````

Then the result will show `1 Nat.+ 1` as expected.

However, if you explicitly specify that it is `unison` code, then it treats it as raw text:

````
```unison
1 + 1
```
````

The output is:

````
``` unison
1 + 1
```
````

This seems inconsistent with transcripts, which expect Unison code to specify `unison` at the top of the code block.

I think that we should treat an explicit `unison` as Unison code.

**Comment by rlmark** [comment]
One caveat is that the website uses the triple backtick Unison blocks very liberally as a way of communicating syntax to users which the pretty printer would otherwise override. We need some way of indicating that a fenced codeblock is Unison code whose format should be preserved literally.

**Comment by ceedubs** [comment]
@rlmark 🤔 hmm good catch that does complicate matters. Some options that I can think of:

1. Use a flag like `unison:watch` for code where you actually want to evaluate a result.
2. XOR use a flag like `unison:raw` for code that you don't want to evaluate.
3. Abandon ship and close this issue.

I think that I have a slight leaning toward `2` with `3` being close behind.

**Comment by rlmark** [comment]
I have a slight preference for option 3 or `unison:watch` to force evaluation because Unison also has a highlight.js package which is looking for ```unison  to add syntax highlighting to unevaluated text blocks when incorporated as a node package. (We still need to add this package to the website though, so it's not something that would break existing functionality) We could change the highlight JS package conventions to support `unison:raw`, but am admittedly less confident in my javascripting. 😁

**Comment by ceedubs** [comment]
@rlmark okay ⃔🚢
