### ISSUE TITLE
Regression in typechecking performance from pattern-match coverage

### ISSUE THREAD

**Issue by ChrisPenner** [unisonweb/unison#3879]
Looks like pattern-match coverage caused a pretty significant regression in typechecking speed from M4h -> M4i.

I noticed it because `display`'ing a doc takes a long time after an initial UCM start-up (even for a trivial doc), but after it's "warmed up" it's fast, so AFAICT the new UCM is taking much longer to compile IOSource. I confirmed by copy-pasting IOSource into a scratch file and testing it on M4h and M4i; M4i is about 10X slower.

We can also observe this via the following transcripts:

With this transcript:

    ```ucm
    .> builtins.mergeio
    ```
I get the following timings:

```sh
$ time ./ucm-m4h transcript transcript.md
...
./ucm transcript transcript.md  0.90s user 0.24s system 128% cpu 0.886 total
```

```sh
$ time ./ucm-m4i transcript transcript.md
ucm transcript transcript.md  10.39s user 0.47s system 120% cpu 9.023 total
```

I get similar results when using the display command on docs, like the following transcript:

    ```unison
    mydoc = {{hello}}
    ```

    ```ucm
    > display mydoc
    ```

---

We've talked in the past about finding ways to embed/speed up IOSource, which would help here (if it is indeed the culprit); but a 10x slowdown in typechecking a moderate size file like IOSource is likely worth investigating regardless.

I confirmed it was from the pattern match coverage checker by disabling it on trunk (commenting out https://github.com/unisonweb/unison/blob/trunk/parser-typechecker/src/Unison/Typechecker/Context.hs#L1253 as directed by Travis) which speeds things back up.

Also slows down running some transcripts by 10s, which makes some iterations a bit more painful

**Comment by ceedubs** [comment]
Just throwing in my 2 cents as someone who regularly works in a fairly large scratch file.

I regularly work in a ~6k line scratch file, and the delay after saving the scratch file has increased noticeably after the addition of pattern matching checking (it's up to ~10s now). However, the pattern match coverage checking has also caught several bugs, so I'd say that it's worth it. If there's low-hanging fruit in the performance of pattern match checking then it's probably worth pursuing, but I'd hate for too much time and effort to be put into it if it might instead go into finding another solution for IOSource and/or preventing the need to load entire codebases into a scratch file. If the Unison workflow gets to the place that we want it to be, then the performance of type checking shouldn't be all that critical.
