### ISSUE TITLE
Garbage collect unreachable items in codebase

### ISSUE THREAD

**Issue by ChrisPenner** [unisonweb/unison#3887]
This is becoming more important as codebases on Share are growing; e.g. `cloud` is at 18G right now.

@ceedubs  mentions some of this is likely due to huge cycles churning on every update, which makes sense, so some of this won't be 'unreachable' code, but right now even if they truncate their history and re-push it won't actually shrink the codebase at all.

That said, space isn't at a huge premium on Share quite yet, but VACUUM's during migration are getting pretty slow and it'd be good to get ahead of this before it's a problem if we can.

We currently don't have any way to actually garbage collect a whole codebase, the only way I can think of to do it reliably would be to go through the Share Sync protocol, but we don't have a "local mode" for that, and it'd be slower than necessary.

**Comment by ceedubs** [comment]
@ChrisPenner if I understand correctly #3837 is a feature request for the "local mode" that you are referring to. It sounds like that might not be the way that you want to go, but I just thought that this was an interesting use-case.

**Comment by aryairani** [comment]
We'd have to decide that we don't care to generally be able to pin a dependency by hash, but I thought we did care to?

A separate question is could we be ok with garbage collection as an emergency maintenance procedure, which we could.

Maybe when we track dependencies on share we could do something smart here.

**Comment by ChrisPenner** [comment]
> We'd have to decide that we don't care to generally be able to pin a dependency by hash, but I thought we did care to?

For pushed projects the pinned dependency would be "part of" the project and wouldn't be garbage collected;
For local projects the pinned dependency is part of your local codebase, and can be pushed with the project if it's missing from the server.

This means you can't create links to arbitrary unreachable hashes, but at least breaking those doesn't break anyone's code 😄 .

Another option would be add a mechanism for creating permanent links, which Share would keep track of and not garbage collect those hashes, but that's probably not worth the effort in the meantime.

**Comment by aryairani** [comment]
Oops, right.

**Comment by aryairani** [comment]
Resolved by https://github.com/unisonweb/unison/pull/4056
