### ISSUE TITLE
Revisit effect generalization and inference

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#390]
Type _checking_ of effects is straightforward. We maintain an "ambient ability", which is pushed down into subexpressions following user-provided type annotations, and when typechecking a function call for a function `a ->{e} b`, we verify that the function's required abilities, `{e}` are a subset of the ambient abilities. This is the basic gist behind the Frank paper and I feel pretty good about it.

Effect inference (not in the Frank paper) is used in a few places as well - a lambda without an annotation will try to infer the effects used, and in `handle` blocks, the body of the block gets access to whatever effects the handler eliminates. I'd characterize our implementation of inference as pretty ad hoc and I feel less good about it.

Also on somewhat shaky ground: we do effect generalization. The idea behind effect generalization is that type signatures like `(a -> b) -> [a] -> [b]` can be generalized to `(a ->{e} b) -> [a] ->{e} b`, which makes them "effect polymorphic" (so `map` can be used as `traverse` without a separate definition). Effect generalization is fine by itself, except it interacts weirdly with effect inference, which has to introduce existential type variables for the ambient ability. I suspect #332 is an instance of this.

A few things I'd like to do:

* Start by documenting how we'd like this to work.
* Likely thing: don't do any generalization for non HOFs, as they don't benefit from it.
* Do effect inference at the level of a whole n-ary lambda. So the whole lambda gets one existential ambient ability, which is refined during typechecking of the body. This should generate predictable results for inferred types, which could be spec'd out in the above document.
* Think carefully about the inference provided by `handle` blocks. It may not be terrible to just eliminate this inference if it can't really be spec'd out and explained easily.

**Comment by pchiusano** [comment]
Noticed some issues related to this when defining an inner function: 

``` Haskell
search : (Nat -> Int) -> Nat -> Nat -> Optional Nat
search hit bot top =
  go : Nat -> Nat -> Optional Nat
  go bot top =
    if bot >= top then None
    else
      mid = (bot + top) / 2
      case hit mid of
        +0 -> Some mid
        -1 -> go bot (mid `drop` 1)
        +1 -> go (mid + 1) top
  go bot top
```

<img width="1276" alt="Screen Shot 2019-03-19 at 6 07 20 PM" src="https://user-images.githubusercontent.com/11074/54645292-df528d80-4a71-11e9-95f3-c7c2ab8700ba.png">

**Comment by aryairani** [comment]
Check this error message too:
```
I found a value of type Nat ->{𝛆, 𝛆, 𝛆, 𝛆, inferred-effect, 𝛆, inferred-effect} [Nat] where I expected to find one of type Nat:

   19 |   range : Nat -> Nat
   20 |   range start stopExclusive =
   21 |     go i = if i < stopExclusive then Some (i, i + 1) else None
   22 |     unfold start go
```
full source at https://gist.github.com/aryairani/0ca4943a1ac16ba62b374223c27040c6

**Comment by pchiusano** [comment]
Here's another example, added as a pending test: https://github.com/unisonweb/unison/blob/master/unison-src/tests/ability-inference-fail.uu

**Comment by pchiusano** [comment]
Made some progress on this, like you can now define local functions that close over outer ability-requesting functions. Added some more illustrative pending tests also.

@aryairani you may not have noticed this given the horrible error message (or maybe you did and were just pointing out the bad msg 😃), but that `range` function should be `Nat -> Nat -> [Nat]` and it typechecks with that signature.

**Comment by aryairani** [comment]
:100:

**Comment by pchiusano** [comment]
Writeup here: https://github.com/unisonweb/unison/blob/master/docs/ability-typechecking.markdown
