### ISSUE TITLE
Get off the off-repo commit for `judah/haskeline`?

### ISSUE THREAD

**Issue by philderbeast** [unisonweb/unison#3945]
Could we update the commit hash for the source repository package https://github.com/judah/haskeline/commit/d6c2643b0d5c19be7e440615c6f84d603d4bc648 to one within the repo or go with a release? Off-repo commits like this can disappear.

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

https://github.com/unisonweb/unison/blob/32256340a6fe06495ff924083a66baaffa0fcdad/stack.yaml#L59-L61

![image](https://user-images.githubusercontent.com/633283/235361820-9332cca2-d761-439b-af1d-124778294495.png)

**Comment by philderbeast** [comment]
A related fork and branch for the PR is [mpilgrem/haskeline/fix88](https://github.com/mpilgrem/haskeline/tree/fix88).

**Comment by jneira** [comment]
hi, want to note it is blocking somewhat the contrib build config for cabal (you cant use stale commits with source-repository-package)

**Comment by philderbeast** [comment]
Yes @jneira, this is exactly what alerted me to the problem (while dusting off the cabal project):

```
$ cabal build all --enable-tests --enable-benchmarks --project-file=contrib/cabal.project
Cloning into '.../unison/dist-newstyle/src/haskeline-6450a1727d5db11c'...
remote: Enumerating objects: 5057, done.
remote: Counting objects: 100% (91/91), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 5057 (delta 44), reused 71 (delta 32), pack-reused 4966
Receiving objects: 100% (5057/5057), 1.19 MiB | 8.73 MiB/s, done.
Resolving deltas: 100% (2425/2425), done.
fatal: Could not parse object 'd6c2643b0d5c19be7e440615c6f84d603d4bc648'.
```

**Comment by jneira** [comment]
just in case I tried to update cabal config here: https://github.com/unisonweb/unison/pull/3722#issuecomment-1374519600

**Comment by aryairani** [comment]
We can try any commit that works; but we don't have any automated tests for making sure that haskeline is working right, so I'm always hesitant to make changes.

Could someone create a PR and test things out (include some screenshots) on Mac, Windows, Linux? I can volunteer to test on Mac.

**Comment by ceedubs** [comment]
Would it be easier to point to https://github.com/unisonweb/haskeline instead of the main haskeline repo?

**Comment by aryairani** [comment]
@ceedubs Yes we can do that again. We briefly had a usable build on their repo, but then I guess they moved the branch head to one that didn't include the commit :headdesk:
