### ISSUE TITLE
Round Trip bug: multiline strings get extra leading \n

### ISSUE THREAD

**Issue by stew** [unisonweb/unison#3973]
When I store a string with a \n in it, it becomes a multiline string that has had an extra \n prepended

Transcript:
````
```unison

a = "a\nb"

```

```ucm
.> add
.> view a
```
````

Output:
````
```unison
a = "a\nb"

```

```ucm

  I found and typechecked these definitions in scratch.u. If you
  do an `add` or `update`, here's how your codebase would
  change:
  
    ⍟ These new definitions are ok to `add`:
    
      a : ##Text

```
```ucm
.> add

  ⍟ I've added these definitions:
  
    a : ##Text

.> view a

  a : ##Text
  a =
    """
    a
    b"""

```
````

**Comment by ceedubs** [comment]
#3848 says:

> The initial newline, if it exists, is ignored.

According to that, I think that this would be an error in the parser, not in the pretty-printer. But as far as I can tell this rule isn't yet documented in the language reference.
