### ISSUE TITLE
Unhelpful error message for missing equal sign

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#3990]
In this scratch file, I've forgotten the `=` on line 2:

```
foo : Nat -> Text
foo n
  Nat.toText n

---- Anything below this line is ignored by Unison.
a
b
c
d
```

The parse error is not very helpful:

```
  offset=11:
  unexpected <outdent>
     10 | 
```

One aspect that is particularly confusing is that it reports that the error is at the end of the file (line 10), even though that is many lines _below_ the "fold", where content should be ignored.

**Comment by aryairani** [comment]
I guess we'd need to treat the fold as an EOF somewhere

**Comment by sellout** [comment]
Duplicate of #813.
