### ISSUE TITLE
update mac dev docs for new ghc version

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#4025]
`trunk` is now on GHC 9.2.7 but https://github.com/unisonweb/unison/blob/trunk/docs/m1-mac-setup-tips.markdown still refers to 8.10.7.

**Comment by aryairani** [comment]
Next step is to try building UCM without any special instructions on a clean install; I think they might no longer be relevant.

**Comment by neduard** [comment]
Hey @aryairani !  Just fyi I built latest trunk (815c1b1f) on a M1 by just doing `brew install stack` and `stack build --fast --test && stack exec unison`.  Not sure if I missed anything or the newer versions of stack & GHC are easier to build with.  Happy to do more testing or raise a PR cleaning the docs if you think they aren't relevant any longer.
```
stack --version
Version 2.15.7 aarch64
```

**Comment by aryairani** [comment]
@neduard At a glance I think you're right, that it's mostly out of date or irrelevant. A PR would be welcome!
