### ISSUE TITLE
Figure out why the first ^C interrupts a running computation, and then if you do it again, it exits `ucm`

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#406]

**Comment by pchiusano** [comment]
There was an attempt to implement this, but two `^C`s kills ucm.

**Comment by mitchellwrosen** [comment]
This is a GHCism, it installs a one-time signal handler for `SIGINT` that throws `UserInterrupted` to the main thread. Then the signal handler is uninstalled, so falls back to the default behavior (kill process).

**Comment by mitchellwrosen** [comment]
More info: https://gitlab.haskell.org/ghc/ghc/wikis/commentary/rts/signals

**Comment by aryairani** [comment]
Fixed now
