### ISSUE TITLE
`Bytes.indexOf : Bytes -> Bytes -> Optional Nat`

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#4060]
And similarly `Text.indexOf` builtin.

This should use the efficient Boyer-Moore or KMP-style substring matching, so it doesn't do unnecessary work.

**Comment by runarorama** [comment]
Text.indexOf looks like it has a bug for multi-byte characters:

    1 | > ##Text.indexOf "foo👊🏿" "bar👊🏿foo👊🏿baz👊🏿"
          ⧩
          Some 7

    3 | > Text.size "foo👊🏿"
          ⧩
          5

The 👊🏿 character is two codepoints, so the answer should be `Some 5`

**Comment by pchiusano** [comment]
This has been fixed, see https://github.com/unisonweb/unison/pull/4101
