### ISSUE TITLE
Investigate server-side squash performance

### ISSUE THREAD

**Issue by ChrisPenner** [unisonweb/unison#4069]
Just double-check that the squash when publishing a release isn't doing anything slow or memory intensive.

**Comment by pchiusano** [comment]
Idea: squashing could (in Haskell) keep local state mapping branch hashes to squashed branch hashes - if the same subtree is encountered more than once, could skip it.

**Comment by pchiusano** [comment]
Idea: maybe detect if something is already squashed (a singleton causal), and short circuit that.

**Comment by ChrisPenner** [comment]
Closed in #4110
