### ISSUE TITLE
support cloning/pulling a latest release

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#4081]
Be able to ask Share what the latest release of a project is, and pull that.
part of #4083

**Comment by aryairani** [comment]
depends on https://github.com/unisoncomputing/enlil/pull/262

**Comment by mitchellwrosen** [comment]
Is something like this the user experience we want?

```
foo/bar> clone /releases/latest

  Ok, I cloned foo/releases/2.0.0

foo/releases/2.0.0>
```

**Comment by ChrisPenner** [comment]
Maybe I missed the discussion somewhere, but in which workflow are users _cloning_ releases?
I was under the impression releases were meant to be installed as dependencies, not cloned to be developed on 🤔

I thought this feature was meant for the use-case:

```
foo/bar> install @unison/base

  Okay, I installed @unison/base/releases/1.2.3 into lib.base 👍

foo/bar>
``` 

Or, perhaps in the meantime:

```
foo/bar> pull @unison/base/releases/latest lib.base

  Okay, I pulled @unison/base/releases/1.2.3

foo/bar>
```

But IMO it'd be best to just add the install command rather than implement custom support for `releases/latest`

**Comment by aryairani** [comment]
Honestly we should be able to develop on top of a release — e.g. a bugfix to an older version of a lib, how would you do that? We can't support that well right now, due to squashing, but it's a use case we should keep in mind.

Secondly: Even for an `install` command we need to be able to distinguish between releases, latest release, and other versions; e.g. you can `install` a particular branch (and/or probably hash once we nail down authorization) as a dependency.
I _guess_ it can be <project> alone means the latest release when installing? Arguably weird since that means the main dev branch in other contexts, but maybe it's fine. We'll nail this down during dependencies design. It's not guaranteed that `install <project>` should be installing the latest release though, e.g. if we end up trying to match a compatible version to your already-installed dependencies.

The main use case for **this ticket** is the ability for `ucm` to install the latest release of `@unison/base` when you `project.create` without `--no-base`.  If `ucm` is doing this automatically instead of suggesting a manual `pull` command, there doesn't need to be syntax yet.

Separately, I'm not opposed to this though:
```
foo/bar> pull @unison/base/releases/latest lib.base

  Okay, I pulled @unison/base/releases/1.2.3

foo/bar>
```

**Comment by aryairani** [comment]
Closing this for now
