### ISSUE TITLE
autocomplete for merge command

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#4108]
It would be nice for the `merge` command to autocomplete branch names. The behavior could be similar to the autocomplete for `switch`, but I don't know whether you'd need to autcomplete project names; maybe the other project is essentially a clone so you would want to be able to?

**Comment by aryairani** [comment]
@mitchellwrosen Could you analyze this task when you have a chance

**Comment by mitchellwrosen** [comment]
This one's done
