### ISSUE TITLE
be more helpful when calling branch with an existing name

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#4119]
Current behavior:

```
nimbus/testing_updates> branch new_remote
 
  nimbus/new_remote already exists.

nimbus/testing_updates>
```

I think that it should do one of two things (but I don't know which):

- Add "You can switch to it with `switch /new_remote`" to the error message.
- Do a `switch` instead of creating a branch and print a message to the screen letting them know that they switched to an existing branch.

**Comment by aryairani** [comment]
It would be nice if we could get some telemetry to know what people do next, before we start choosing something automatically. In the mean time we could add the `switch` tip though.
