### ISSUE TITLE
Make it more ergonomic to switch to a branch in the current project

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#4120]
Say that I want to switch to another branch in my current project but don't quite remember the name. I can run `branches` and in 2 commands I can get a pretty decent user experience. But it also would be nice to be able to do it with a single command.

If I run `switch <TAB>` then I see all branches _and_ projects in my codebase. This output is a bit overwhelming.

If I run `switch /<TAB>` then I don't get any output, but I would expect to get autocompletion of branches within my current project.

We could potentially overload `branch` to also work for switching to existing branches as brought up in #4119. But I think that fixing completion for `switch /<TAB>` is less controversial and should happen either way.

**Comment by mitchellwrosen** [comment]
Huh, yeah, `switch /<TAB>` should work. That was an oversight.
