### ISSUE TITLE
record types with fields with user-defined types don't roundtrip

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#4123]
e.g. In this example:
```unison
unique type Foo = { text : Text }
unique type Foo2 = { text2 : Foo }
```

`Foo` will round-trip as a record, but `Foo2` won't.

There's already a transcript demonstrating this error, from https://github.com/unisonweb/unison/pull/4098.

Here's what happens after adding these definitions:
```
innocent-reindeer/main> view Foo Foo2

  unique type Foo = { text : Text }
  
  unique type Foo2 = Foo2 Foo

innocent-reindeer/main> 
```

Note that `Foo` renders normally, while `Foo2` renders brokenly.

**Comment by ceedubs** [comment]
Is this separate from #4100?

**Comment by aryairani** [comment]
lol no I just forgot.
