### ISSUE TITLE
Unhandled request should not crash the codebase editor and the message should show some name for the request

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#415]
```
drew> execute Drew.main()
unison: user error (This ability is not an I/O ability: #2MfWM)
```

This is really saying that there was an unhandled non-IO request that bubbled up to the top.

**Comment by aryairani** [comment]
It should also say the name (or at least the number) of the constructor.

**Comment by pchiusano** [comment]
Seems like we should just get a type error here with an ability check failure - `execute` command only grants access to `IO`.

**Comment by aryairani** [comment]
Yeah.  I get the same error when saving this file (has unguarded effect with missing RequestPure case, although I don't totally get why it doesn't bubble up to the enclosing `handleFail` handler, which does have a pure case.)

![image](https://user-images.githubusercontent.com/538571/54871917-69606600-4d92-11e9-8606-baa010f9afdc.png)

https://gist.github.com/aryairani/338d36a63671f9f892fda4794e5b4a79

**Comment by aryairani** [comment]
To clarify, `Drew.main` has a pure type, but has an unhandled case in an effect handler.  So it isn’t a normal type error to be caught in typechecking; maybe totality checking.

**Comment by pchiusano** [comment]
This is probably a case of needing to plumb some `PrettyPrintEnv` through to the runtime. Or else the runtime returns a more structured object rather than constructing the error itself.

**Comment by pchiusano** [comment]
<img width="1124" alt="Screen Shot 2019-06-27 at 11 41 31 PM" src="https://user-images.githubusercontent.com/11074/60315596-22f04980-9935-11e9-83f1-6f9351e120f0.png">
