### ISSUE TITLE
push fails with just ❗️ when authentication is required

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#4152]
The output is no longer in my terminal, but I did a `push` and it said something like:

```
uploaded 0 entities

❗️
```

I authenticated with `auth.login` and then a new push succeeded.

**Comment by aryairani** [comment]
@ChrisPenner wdyt about this one? :)

**Comment by ChrisPenner** [comment]
@aryairani  I thought that @tstat took a look at this one a while back maybe? Not sure where that ended up though.

Would be nice if we didn't even have any code-paths with empty errors 😶
