### ISSUE TITLE
less hides part of auth URL

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#4153]
During the auth flow, if ucm can't open a browser, it prints an oauth URL to the terminal. However, this URL is truncated by `less`, which makes it difficult (impossible?) to copy into a browser to finish the oauth flow. It looks something like this:

```
https://api.unison-lang.org/oauth/authorize?state=abcdef&redirect_uri=http%3A%2F%2Flocalhost%3A34345%2Fredirect&response_type=code&scope=openid%20cloud%20sync&client_id=ucm&code_challenge=abcdef>
```

The `>` at the end seemingly represents truncation, but I can't figure out how to see and copy the rest. If I set `INSIDE_EMACS=1` then no pager is used, the full URL prints, and I can access it just fine.

## background

The reason that ucm can't open my browser is become I'm on my laptop but developing on a remote machine via ssh. This isn't how most people will be developing, but it's a scenario that should work (even if it means a bit of awkward pasting a redirect URL into `curl`, which it does).

**Comment by aryairani** [comment]
Hm first I'll try to repro, maybe some of the `less` commands, which vary by platform, will work?

For me on mac, the "right arrow" key lets me see another half-screen's worth of the contents for each press, but isn't super convenient, because you have to piece it together yourself; "left arrow" takes be back to the normal wrapped view, which is probably what you want, but also maybe what you can't have if it isn't showing for you already by default.

`s filename` is supposed to let you dump the buffer to a file, but my terminal just beeps at me when I try this. Does it work for you?

What terminal are you working in?

**Comment by ceedubs** [comment]
> For me on mac, the "right arrow" key lets me see another half-screen's worth of the contents for each press, but isn't super convenient, because you have to piece it together yourself

Same.

> "left arrow" takes be back to the normal wrapped view

Hmm strange. It's not wrapped for me.

> s filename is supposed to let you dump the buffer to a file, but my terminal just beeps at me when I try this. Does it work for you?

Interesting. This does work for me. But it's also inconvenient. In addition to needing to open a new window and look at the file, the file has ansi control characters in it that make it awkward to copy paste.

> What terminal are you working in?

I'm working in a tmux session that I've connected to via the macOS terminal.app.

## meh this is good enough

The `INSIDE_EMACS` hack left a distaste in my mouth, but I just realized that I can set `UNISON_PAGER=cat` to avoid paging entirely, so I'll do that and close out this issue. If others run into a similar problem hopefully they see this issue. And if there are enough of them maybe we can come up with a better solution.

**Comment by aryairani** [comment]
Yeah, tbh I think it "should" work fine with `less` in tmux etc unless there's something uniquely weird about some aspect of it? If you want to help me repro (I don't currently have any non-prod machine to tmux on), I'll still dig into it because I'm curious.
