### ISSUE TITLE
Should be able to run computations with `IO` without first adding them to codebase

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#417]
You can execute stuff in the CLI, but only if it's been added to the codebase.  You can execute stuff in the Unison file, but only if it's pure (not `IO`).  Was giving a little demo today, and this all required too much explanation IMO; too much awkward context switching between windows.

Maybe:
* Watch expressions have access to IO?
* `execute` can run local (typechecked but not added definitions)?

**Comment by aryairani** [comment]
Also, `execute` throws away a pure result.  I know it was created with a different use case in mind, but the current workflow requirement of edit, add, update, execute is approximately as inconvenient as only being able to execute from the shell prompt.

**Comment by pchiusano** [comment]
I had a random thought:

```
> 1 + 1 -- run automatically, can't do IO
> IO.launchMissiles -- don't really want this to run on every file save

execute> IO.launchMissiles -- "I found this menu of things you can execute in this file"
```

**Comment by pchiusano** [comment]
Here's one very simple design: 

When you parse and typecheck a file, the symbols in that file become available to the `execute` command (I think existing loop state may be sufficient as it has the most recently typechecked file in there). So, you have a definition like `main : Text ->{IO} ()` in the file, and after saving the file, you switch to the CLI and do `> execute main "arg1 arg2"`. If you're iterating rapidly, no problem, just hit the up arrow - no need to retype that command over and over again. Easy peasy.

That's it for the design. So, it won't run any `IO` actions automatically on every save, but pretty low friction.

My vote is to just do the above for M1, it'll be very simple, and then see how it feels and revisit for later.

**Comment by pchiusano** [comment]
Closing in favor of #632
