### ISSUE TITLE
aliasing caused by lack of nominal types causes confusing error messages

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#419]
![image](https://user-images.githubusercontent.com/538571/54871209-04534300-4d87-11e9-9c38-c4fedc368c5e.png)

Omg this message.  And we aren't doing anything with `Socket`s.

This was using an old version of the IO implementation which had `type Socket = Nat`, so `Socket = ()`

Related to #407, #411 in that the type error could use a PPE to print that constructor name; there is probably more going on too, as surely `putText` wasn't expecting `()`?

**Comment by pchiusano** [comment]
closing in favor of #446
