### ISSUE TITLE
delete help should mention varargs

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#4194]
`delete.term`, `delete.type`, and `delete` all seem to support varargs like `foo bar`, `1 2`, or `1-2`, but their help output doesn't mention it:

```
cloud/cloudability2_cody> help delete.term

  delete.term
  `delete.term foo` removes the term name `foo` from the namespace.
```

This should be documented.

**Comment by sixfourtwelve** [comment]
Happy to take, forgot to mention before creating a PR :)

**Comment by sixfourtwelve** [comment]
PR Merged, my first and hopefully of many ✨

Probably worth closing the ticket @ceedubs ?
