### ISSUE TITLE
flesh out optional and repeated CLI args

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#420]
```haskell
data InputPattern = InputPattern
  { patternName :: String
  , aliases     :: [String]
  , args        :: [(IsOptional, ArgumentType)]
  , help        :: P.Pretty CT.ColorText
  , parse       :: [String] -> Either (P.Pretty CT.ColorText) Input
  }

data ArgumentType = ArgumentType
  { typeName :: String
  , suggestions :: forall m v a . Monad m
                => String
                -> Codebase m v a
                -> Branch
                -> m [Line.Completion]
  }
```

I'm in a situation where it would be nice to support auto-completing of a variable number of arguments drawn from the `TypecheckedUnisonFile`.  Currently, `args` can't represent variable numbers of arguments and suggestions can't come from the `TypecheckedUnisonFile`.  Also, I think `IsOptional` is ignored.

**Comment by pchiusano** [comment]
@aryairani is this still open? I thought you added something for this kinda recently

**Comment by aryairani** [comment]
Yeah this is largely done.  I had wanted to do something to automatically display help when providing the wrong number of args, and I added some untested helpers for that (`InputPattern (minArgs, maxArgs)`), but I didn’t get to it yet.  It could be a separate ticket.

**Comment by pchiusano** [comment]
Closing this. —Arya
