### ISSUE TITLE
UCM output loses colored output triangle

### ISSUE THREAD

**Issue by gerardbosch** [unisonweb/unison#4201]
UCM version: ucm version: release/M5b (built on 2023-07-13)
Unison installation: Nix flakes
OS: Ubuntu 23.04
Shell: Zsh
Terminal: gnome-terminal

### Code:

```
myTerm = List.map (x -> x * 10) [1,2,3,4,5,6]
> myTerm
```

I observe this strange thing, the first time I saved the `.u` file, the UCM displayed the output with a colored triangle. After that, subsequent evaluations on save, display the triangle in b&w. I'm not sure if it's UCM or my terminal doing weird things.

Not really important BTW.

### Sample

![image](https://github.com/unisonweb/unison/assets/30733556/5ba61465-dac5-42c8-8217-f8e3835ce58e)

**Comment by gerardbosch** [comment]
After playing with Unison I started to think that this may be a feature and there is a pattern that makes the color to pop 😅. Maybe when a new term appears in a watch expression (`>`) or something like that?

Feel totally free to close this! I'm quite convinced it should be intended behavior now :)

**Comment by gerardbosch** [comment]
I close this, as I realized that the color pops only when a new term is watched.

**Comment by pchiusano** [comment]
Yeah, if the watch expression result is found in the cache, it does black and white, otherwise if it has to actually compute it, it's in color. I think it's probably too subtle, should just say `(cached)` or some such.
