### ISSUE TITLE
Move editor-support/vim to mainstream vim repository

### ISSUE THREAD

**Issue by chuwy** [unisonweb/unison#4202]
I'd like to add Unison support to Neovim and Vim. I personally care about file-detection in former and [I created a PR](https://github.com/neovim/neovim/pull/24359), but suspect they might reject it because all 3rd-party language features are added through mainstream vim repo. So I just wanted to ask @runarorama a permission to copy [editor-suppor/vim](https://github.com/unisonweb/unison/tree/trunk/editor-support) to mainstream vim repository (couldn't find a reason why it hasn't been done yet).

**Comment by runarorama** [comment]
It's all MIT licensed, so you're free to copy whatever you want 😀

**Comment by chuwy** [comment]
It has been merged https://github.com/vim/vim/pull/12715

**Comment by ceedubs** [comment]
@chuwy @runarorama should we be removing the `editor-support/vim` directory from this repo? On the one hand, I don't love the idea of improvements being blocked on a vim release. On the other hand, I don't want to two to drift out of sync.

**Comment by chuwy** [comment]
Short-term we absolutely should not - a lot of people refer to that directory in their configs. After next Vim and NeoVim releases are included in major distros we can re-open the question. Meanwhile someone (myself) can keep an eye on unison-repo changes and port them to mainstream Vim - I don't think there will be a lot of them.
