### ISSUE TITLE
Decide what we want M1 users to do to deal with name conflicts, and update the output to reflect that guidance.

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#421]
![image](https://user-images.githubusercontent.com/538571/55171273-6d9fd100-514e-11e9-8e5c-269b837e20f6.png)

**Comment by pchiusano** [comment]
This should probably be called `resolve-name`, `resolve.name`, `name.resolve` or something..

**Comment by aryairani** [comment]
Obsolete
