### ISSUE TITLE
Structural comparison of `TVar`s fails at runtime

### ISSUE THREAD

**Issue by dfreeman** [unisonweb/unison#4221]
Comparing two `TVar` values (or one to itself) with `Universal.===` results in a runtime exception:

```haskell
var = atomically TVar.new
var === var
```

```
Encountered exception:
Attempting to check equality of two values of different types:
    ( ##TVar
    , ##TVar
    )
  CallStack ( from HasCallStack ):
    error
```

**Comment by pchiusano** [comment]
Thanks for the report @dfreeman

@dolio could you point to where in the code this should be fixed, assuming we just want to compare the `TVar` via unsafe pointer equality. Which I think is fine here.

**Comment by ceedubs** [comment]
@pchiusano I think that it's [here](https://github.com/unisonweb/unison/blob/6d050d5bc74645cb572c01a0a5c8d2eb28479c71/parser-typechecker/src/Unison/Runtime/Foreign.hs#L143-L174), and there's a precedent for `MVar`.

**Comment by dfreeman** [comment]
Oh that looks easy; I'll open a PR. Thanks!

**Comment by dolio** [comment]
Yeah, a case just needs to be added to that using the `Eq` instance for `TVar`.
