### ISSUE TITLE
term declarations appear to allow hashes in the term names

### ISSUE THREAD

**Issue by kylegoetz** [unisonweb/unison#4233]
```
(Numeric.>=##Nat) : Int -> Int -> Boolean
(Numeric.>=##Nat) = todo "implement"
```

UCM does not complain about this. Have been told on Slack this should be a syntax error.

The issue appears to be the use of `prefixDefinitionName` in the `typedecl` parser in `TermParser.hs`:

```
typedecl =
  (,)
    <$> P.try (prefixDefinitionName <* reserved ":")
    <*> TypeParser.valueType
    <* semi

binding = 
  -- [snip]
  let prefixLhs = do
        v <- prefixDefinitionName
        vs <- many prefixDefinitionName
        pure (ann v, v, vs)
```

and in `Parser.hs`:

```
prefixDefinitionName = wordyDefinitionName <|> parenthesize symbolyDefinitionName

wordyDefinitionName = queryToken $ \case
  L.WordyId s _ -> Just $ Var.nameds s
  L.Blank s -> Just $ Var.nameds ("_" <> s)
  _ -> Nothing

symbolyDefinitionName = queryToken $ \case
  L.SymbolyId s _ -> Just $ Var.nameds s
  _ -> Nothing
```

I'm guessing instead of `prefixDefinitionName` there should be a separate function in `Parser.hs`,

```
prefixTermName = 
  wordyIdString <|> parenthesize symbolyIdString -- should fail on the presence of a hash
```

and then in `TermParser.hs`:

```
typedecl =
  (,)
    <$> P.try (prefixTermName <* reserved ":")
    <*> TypeParser.valueType
    <* semi

binding = 
  -- [snip]
  let prefixLhs = do
        v <- prefixTermName
        vs <- many prefixTermName -- iffy about this one, maybe it should just be wordyId <|> symbolyId?
        pure (ann v, v, vs)
```

**Comment by pchiusano** [comment]
@kylegoetz PR welcome if you'd like to take a crack. I think it's exactly as you say to fix.

**Comment by kylegoetz** [comment]
@pchiusano I don't see a "contributing" file in the root of the repo. I've also never contributed to a Haskell project like this. **Is there a preferred way for me to write the PR** and make sure tests still pass (not clear to me if I should write any regression tests for this), or should I just write the fixes, file the PR, and wait for suggestions/corrections/comments?

**Comment by aryairani** [comment]
@kylegoetz Good idea about adding a "contributing" file.
I would probably be good to an error transcript (we can help) that demonstrates an error when trying to parse that.
But yeah you can write the fixes and file the PR (and add yourself to the contributors file), and wait for suggestions or comments; discussing strategy here (as you've done) or on Slack is also a good idea.
