### ISSUE TITLE
incorrect render width for watch expressions?

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#424]
```
use Optional Some None
use Universal <

Sequence.foldl : (b -> a -> b) -> b -> [a] -> b
Sequence.foldl f b s =
  go i b = case Sequence.at i s of
    Some a -> go (i + 1) (f b a)
    None -> b
  go 0 b

> foldl (a -> b -> a Nat.+ b)

```

with a terminal width of 71 yielded:

![image](https://user-images.githubusercontent.com/538571/55207686-787f5380-5198-11e9-9a19-e63ce5170b97.png)

whereas it seems like there should be a linebreak after `->` so that the line doesn't overflow?

It doesn't reflow until I reduce the terminal width to 58:

![image](https://user-images.githubusercontent.com/538571/55207980-aca74400-5199-11e9-9ebc-677c7e8202a2.png)

**Comment by pchiusano** [comment]
Is it that the break decision is being made on the pre-indented available width? Or is that width of 58 something else?

**Comment by aryairani** [comment]
I haven’t dug into it at all, just documenting my *terminal* width to help reproducibility.

**Comment by aryairani** [comment]
maybe related to what we saw today @dolio @runarorama @pchiusano

**Comment by runarorama** [comment]
`help merge.preview` also exhibits this issue

![image](https://user-images.githubusercontent.com/130916/82691690-4d718200-9c2c-11ea-8a23-731579b90af1.png)

**Comment by aryairani** [comment]
> `help merge.preview` also exhibits this issue
> 
> ![image](https://user-images.githubusercontent.com/130916/82691690-4d718200-9c2c-11ea-8a23-731579b90af1.png)

Though we think this one might just be a missing (or misunderstood?) call to `wrap`.

**Comment by aryairani** [comment]
Some context: https://unisonlanguage.slack.com/archives/CLG4P0GSD/p1590166990216600

**Comment by mitchellwrosen** [comment]
Out of curiosity, I bisected this. It was either fixed or (as @aryairani suspects) merely hidden by

```
commit a5302afa4f4c9c5570cb366e382b81b94574a3ea
Author: Chris Gibbs <atacratic@users.noreply.github.com>
Date:   Thu May 30 23:23:21 2019 +0100

    Progress on FQN elision in pretty-printer, #285 - narrowness check now partially working

 parser-typechecker/src/Unison/ABT.hs               | 26 ++++++-----
 parser-typechecker/src/Unison/TermPrinter.hs       | 50 ++++++++++++++--------
 .../tests/Unison/Test/TermPrinter.hs               | 18 ++++----
 3 files changed, 51 insertions(+), 43 deletions(-)
```

So just to throw out a guess, the width calculation of qualified terms is/was inaccurate.
