### ISSUE TITLE
separate branch.merge and namespace.merge?

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#4242]
# Problem/background

I recently got really confused when I ran `merge main` and the diff didn't look at all like I would expect. The problem is that my project had a `main` namespace at the top level (with a few different entrypoint functions) and so that _namespace_ was merged into the top of my project when I really wanted to merge the main branch with `merge /main`.

# Proposal

I propose that we have separate commands for merging branches and merging namespaces. I think that as implemented, a project is really just a namespace wearing a mask, so from a technical perspective this might not make much sense. But from a use-case standpoint I think that it makes quite a bit of sense. It's really common to want to merge a branch into another branch, but it's pretty rare to want to merge non-branch namespaces.

I'd suggest a `branch.merge` aliased to `merge` and a `namespace.merge` without an alias. If you try to `merge` a non-branch then it would complain and suggest that you might mean `namespace.merge`.

# Alternative solutions

Part of the problem is that referencing projects/branches/namespaces isn't very obvious. If I do `merge .foo` then it's the `foo` namespace from the top-level of my codebase (not within the current project). If I do `merge foo` then it seems to look for the `foo` namespace within the current project, but in other commands this would be how you would reference a project named `foo`. `merge /foo` means to merge the _branch_ `foo`, but for people used to unix (probably most Unison devs), this probably looks like merging a top-level namespace `foo`. So it's possible that we don't need to separate `branch.merge` and `namespace.merge` if we just find a more obvious way of distinguishing between branches/projects/namespaces when referencing them in commands.

**Comment by ceedubs** [comment]
Another note: since merging a branch is what you want to do 95% of the time, it feels weird that you need to add a leading `/` or ucm assumes that you don't mean a branch and tells you that the namespace doesn't exist.

**Comment by aryairani** [comment]
Oh hm, I would've thought it would merge a branch if the namespace doesn't exist. The lack of a syntax for namespaces is a bummer, yes.

**Comment by ChrisPenner** [comment]
I believe this is already split up, is that right @mitchellwrosen  or nah?

**Comment by aryairani** [comment]
@ChrisPenner Yeah, I think basically `merge` is `branch.merge` and `merge.old` is `namespace.merge` "plus some patch stuff"

**Comment by aryairani** [comment]
I'm going to close this
