### ISSUE TITLE
hacky idea for LSP with multiple projects

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#4243]
I won't be offended if this is closed out as a bad idea.

Sometimes I use a split window in my editor to have two different projects open at a time. For example I might be working in `webapp.u` and see something that I need to change in the json library that I depend on, so I split my window with `json.u` to work on a change to the json library while referencing my use-case code in `webapp.u`.

Since my ucm can only be in one of the two projects at a time, LSP complains about the code in my other window. This makes sense; it has no way of knowing which project the scratch file belongs to.

I can't think of a good way to get it to know which project to use as the base namespace for LSP context. But what if we just assumed that `webapp.u` should be relative to the `webapp` project (in whatever the most recent branch was for that project)? It feels clunky, but might work well enough in practice?

Some things that are bad about this:

- It would differ from ucm's behavior. It assumes that any saved `.u` file (within the working directory) should be compiled against the current project/namespace.
- I don't know if ucm even has good support for two separate LSP sessions going on like this.
- It would be awkward for projects with an `@` in the name like the `@unison/base` that you get if you clone base without an explicit name.
- I think that `scratch.u` is a common convention and I'd be tempted to have it continue to use the current project, but that would be awkward if you have a project named `scratch`.

**Comment by ceedubs** [comment]
Alternative idea: what if there were some magic syntax for doing this in a comment in your scratch file? But this would also be awkward because `edit` prepends to the file, so we wouldn't want to just check at the very top of the file.

**Comment by pchiusano** [comment]
Could you just use the local codebase UI for this sort of thing? You can have as many projects open as you want in multiple tabs.

**Comment by chuwy** [comment]
I think I stumbled upon a similar problem and I wanted to propose a special namespace (like `lib`, but called for example `export`) that contains all the things that later could be exported into another project. So `webapp` project would have `export.json.Decoder.array12`, and ucm would know that I this definition will be exported into a mainstream project eventually.

**Comment by ceedubs** [comment]
> Could you just use the local codebase UI for this sort of thing? You can have as many projects open as you want in multiple tabs.

I don't really think that the codebase UI fully replaces this at the moment. For example I can only search definition _names_ in the UI, while I often want to find a log message or something. Also I'm a lot faster and navigating vim buffers than multiple browser tabs, but that's just the dinosaur in me, so that should be taken with a grain of salt.

Having said that, I'm not really convinced that this is a good idea. I'm going to close this out and maybe someone will come up with a better solution.
