### ISSUE TITLE
an ugly parse error on empty watch expression

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#425]
```
>
```
yields
```
Token {payload = Close, start = Pos 51 1, end = Pos 51 1} :| []
/Users/arya/unison/scratch.u:51:1:
unexpected <outdent>
expecting and, binding, infixApp, lambda, or or
   51 | 
```
Probably drop the Token stuff, at least?  Can we do even better?

**Comment by pchiusano** [comment]
Good catch. This is should be an easy fix and you could knock it out if you want. :) This would also be doable by another contributor too if anyone would like to pipe in and volunteer. Here's how:

I'd add a custom error constructor for this in `Unison.Parser (Error)`, say it's called `EmptyWatch` and then modify the watch expression parser: a `>` followed immediately by a `Close` token gets a `Text.Megaparsec.customFailure (EmptyWatch ..)`.

Compiler warnings should then guide you to add some custom logic for printing out this parse error, which you can make nice.

This is also generally the approach to adding better parse error messages - at the point in the parser where you are expecting a certain parser `p` to succeed, you add a `p <|> customFailure blah` and if it fails in an uncommitted state, you get `blah` as your error instead (if `p` fails in a committed state, then it's consumed some characters and `blah` isn't the right description of the error anyway as it's "too far back").

**Comment by BenFradet** [comment]
I can have a look :+1:
