### ISSUE TITLE
UCM Welcome message: don't show "project.create" message when there are projects

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#4266]
When a user already has projects, we shouldn't show this message in the welcome flow:

![CleanShot 2023-07-16 at 12 39 48@2x](https://github.com/unisonweb/unison/assets/2371/37e5cb54-196d-4a24-a27c-1092a2d20477).

Bonus: we could instead show something like `Hint: type 'projects' to list all your projects`—perhaps a hint cycling thing.

**Comment by sixfourtwelve** [comment]
Happy to take :)

**Comment by sixfourtwelve** [comment]
https://github.com/unisonweb/unison/issues/4204 just realised there's a dup

**Comment by hojberg** [comment]
lol I even used the same screenshot in both hah
