### ISSUE TITLE
add more Float functions

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#427]
e.g. these: http://www.cplusplus.com/reference/cmath/

**Comment by pchiusano** [comment]
Here’s how: in Builtin.hs, add the name and type, you can follow the other examples.

Then in Rt1.hs, add the implementation here: https://github.com/unisonweb/unison/blob/master/parser-typechecker/src/Unison/Runtime/Rt1.hs#L291

Then add some tests.
