### ISSUE TITLE
UI shows docs for other FQN

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#4277]
In this case, user has a top-level type called `Unit` in their library with no docs, and it shows the docs for `base.Unit` in the UI:

![image](https://github.com/unisonweb/unison/assets/11074/1d82a03d-2fd8-43fd-b87c-ecf4fe10f655)

The `docs Unit` also produces the docs for `base.Unit`, which is maybe okay (it's just doing a suffix lookup for `Unit.doc` and finding just one result and displaying it), but messaging could be improved.

Adding `Unit.doc : Doc` to the project doesn't seem to fix it in the UI (it still somehow shows the `base.Unit` docs in the UI), though `docs` correctly returns the user's docs in this case.

**Comment by ChrisPenner** [comment]
Yeah this is caused because the NameSearch does a suffix search when it should be doing an exact name lookup.

I fixed this in the port to Postgres, so it'll be fixed on Share within the next week-ish, should be an easy fix on local too.

**Comment by kylegoetz** [comment]
In case there are lingering issues about this before it's merged in and my experience can help, I got popped with the same issue today:

<img width="733" alt="Screen Shot 2023-10-29 at 4 49 12 PM" src="https://github.com/unisonweb/unison/assets/8161573/3c6a89ea-9597-4df9-a4ce-0c7638d947b1">


and in UCM when I'm in the namespace that has my `delete` at its root, ucm gives me:

```
huenison/main api.EntertainmentConfiguration> view delete

  delete :
    ResourceId
    -> '{IO, Exception, Ask (Settings, HueApiKey)} HueResponse [(ResourceId, ResourceType)]
  delete = deleteHueResource EntertainmentConfig

huenison/main api.EntertainmentConfiguration> view delete.doc

  lib.base.data.Map.delete.doc : Doc
  lib.base.data.Map.delete.doc =
    {{
    Deletes a key and its value from the {type Map}. Does nothing if the key is not in the
    {type Map}.
    }}
  
  lib.base.data.Map.Nonempty.delete.doc : Doc
  lib.base.data.Map.Nonempty.delete.doc =
    {{ Deletes a key from a nonempty map, returning the (possibly empty) map without the key.
    
    # Example
```
