### ISSUE TITLE
Record syntax doesn't allow free type parameters in field function signatures

### ISSUE THREAD

**Issue by kristiannotari** [unisonweb/unison#4279]
`version: m5d`

Let's imagine you have a type composed by two type parameters:
```haskell
unique type A x y =
```
and you want to create another type which encapsules a transformer from an `A` to another `A` changing only one of the two type parameters.
```haskell
unique type MyTransformer a b = { transformer: (A a y -> A b y) }
```
Right now I get an error writing this  `MyTransformer` type due to unison not getting what that `y` is. 
<img width="559" alt="image" src="https://github.com/unisonweb/unison/assets/17885006/b82c8087-b312-44ac-8a97-a82d1ddca359">

This doesn't work even when writing the `forall clause`, but fails with a different error:
```haskell
unique type MyTransformer a b = { transformer: ∀ x y . A a y -> A b y }
```
<img width="565" alt="image" src="https://github.com/unisonweb/unison/assets/17885006/250f40ef-2c6a-45ed-8d85-23cd807cb835">

It works fine if you defined the `MyTransformer` type without the record syntax AND with the forall clause (it fails without the forall clause):
```haskell
unique type MyTransformer a b = 
    MyTransformer (∀ y . A a y -> A b y)
```

**Comment by pchiusano** [comment]
This is a known issue https://github.com/unisonweb/unison/issues/498 but it's a good example of a bad error message.

I think we should either fix the limitation, or just say:

"Unfortunately, Unison doesn't currently support record fields that are polymorphic. As a workaround, you can just use a regular data type, which can contain polymorphic fields."

Or something like that.
