### ISSUE TITLE
Premature fixing of generic function type parameter when piping callbacks first

### ISSUE THREAD

**Issue by kristiannotari** [unisonweb/unison#4283]
Slack thread as a reference: https://unisonlanguage.slack.com/archives/CLUNF0J5S/p1692956407264309

```haskell
-- the generic type containing the function signature I want to bring to the type level
unique type A f = A f

unique type Wrapper a = Wrapper a

-- a simple A type for test purposes that receive an Optional
-- of whatever and always return a Nat ignoring input
toNat : A (Optional a -> Nat)
toNat = A (cases
  Some _ -> 42
  None -> 0)

apply : a -> A (a -> b) -> b
apply a = cases A f -> f a

-- simple test cases (OK) ✅

ok1 : Nat
ok1 = apply (Some 42) toNat
ok2 : Nat
ok2 = apply (Some "hello") toNat

applyWrapper : a -> Wrapper (A (a -> Nat)) -> Nat
applyWrapper a = cases Wrapper f -> apply a f

-- wrapped test cases (OK) ✅

ok3 : Nat
ok3 = applyWrapper (Some 42) (Wrapper toNat)
ok4 : Nat
ok4 = applyWrapper (Some "hello") (Wrapper toNat)

-- wrappedCallback test cases (NOT OK) ❌

wrapCallback : (s -> a) -> Wrapper s -> Wrapper s
wrapCallback f = cases Wrapper s -> Wrapper s -- do nothing with the callback

notOk : Wrapper (A (a -> Nat))
notOk = 
  (Wrapper toNat) |>
  wrapCallback (apply (Some 42)) |> -- ❓ here's the error, the wrapper A type has been fixed by the callback
  wrapCallback (apply (Some "hello")) -- so here I can't use it with Text even if I should be able to
```

I guess what's desirable is the ability to nest `forall` signatures inside a generic type you're asking for as input. Editing my previous example, the `apply` function really should look like this:

```haskell
apply : a -> A (forall b . b -> c) -> c -- not possible right now! ❌ (or at least I can't make it to work this way)
apply a = cases A f -> f a
```
This way I'm properly dealing with functions that can accept whatever you throw at them without risking to fix them during pipes.

**Comment by pchiusano** [comment]
Hi @kristiannotari this is a limitation of Unison's type system (and most other type systems), which is that a single type variable will never be instantiated to a polymorphic type (type systems that do some version of this have "impredicative instantiation").

So here, the `a` type in `Wrapper a` type won't be instantiated to a polymorphic type, it's just instantiated to a monomorphic type which it infers involves `Nat` from the first `apply (Some 42)`. If you want a type like `Wrapper` to contain polymorphic things, you'd have to declare with a type signature how you want it to be polymorphic. Like you could say `unique type Wrapper a b = Wrapper (forall a b . [(a,b)] -> [a])` or some such.

Aside: to see why impredicative instantiation can be a can of worms, consider inference of the following function, which has to figure out the types of `f` and `a`:

```haskell
foo f a = 
  if a then f (a Nat.+ 1) 
  else f (a Float.+ 22.0)
```

So here we have `f` being called with different types, a `Float` and a `Nat`. And we have `a` being assumed to be both a `Float` and a `Nat` in the two branches if the `if`. Is this a type error, or should the typechecker assume that `f` and/or `a` have polymorphic types? Like maybe `a` has type `forall x . x` and `f` has the type `forall b . b -> (b,b,b)`. When the typechecker is allowed to assume polymorphic types everywhere, even when the user hasn't specified they want this, the typechecking problem becomes very unconstrained.
