### ISSUE TITLE
Non ability datatypes can be included in ability requirement 

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#4294]
Thank you to @alvaroc1 for raising this issue (or [something related to this issue](https://unisonlanguage.slack.com/archives/CLUNF0J5S/p1693344092432819) ) 

Currently the UCM lets you add a non ability type in the ability requirement set of a function. 

```
y : '{Abort, Nat} Text
y = do "What is Nat ability?"

> !(Abort.toOptional y)

The expression in red needs the {Nat} ability, but this location does not have access to any abilities.
  
      5 | > !(Abort.toOptional y)
```

It seems like this should not be permitted to typecheck, but you can currently `add` a function with this requirement. (Calling it, however, is another story!)

**Comment by alvaroc1** [comment]
It's not wrong though... i kinda like the current behavior:

```
y : '{Abort, Nat} Text
y = do "What is Nat ability?"

h : Request {Nat} a -> a
h = cases {u} -> u

> handle !(Abort.toOptional y) with h
```
```
    8 | > handle !(Abort.toOptional y) with h
          ⧩
          Some "What is Nat ability?"
```


maybe useful for marker abilities? like:

```
unique type EastCoast = EastCoast
```
```
captureSunRiseOverOcean : '{EastCoast} ()
captureSunRiseOverOcean = ...
```

**Comment by SystemFw** [comment]
Isn't this just a consequence of not having kind checking yet?

**Comment by aryairani** [comment]
Yes, here is the current output on `trunk`:

```
  Kind mismatch arising from
        1 | y : '{Abort, Nat} Text
    
    An ability list must consist solely of abilities; however, this list contains Nat which
    has kind Type. Abilities are of kind Ability.
```
