### ISSUE TITLE
Make project UUIDs deterministic in transcripts

### ISSUE THREAD

**Issue by ChrisPenner** [unisonweb/unison#4314]
We couldn't write transcript tests for https://github.com/unisonweb/unison/pull/4285 because the project IDs appear in the api output. We can seed the UUID generator when in transcripts to prevent this issue.

**Comment by aryairani** [comment]
There's now a field accessible in `Cli` to tell you whether you're in a transcript.

**Comment by aryairani** [comment]
Question: Are there any APIs that still reveal project UUIDs?
Chris says that the transcript test for #4285 could now be written but whatever
