### ISSUE TITLE
UX around deleting branches in Share

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#4320]
I've noticed a number of small papercuts when deleting branches from Share. None of these are major, but I thought that it might be helpful to track them somewhere.

## Discoverability

When you have too many branches (which is probably when you _want_ to delete branches), it can be hard to figure out where to go to delete them.

<img width="340" alt="Screenshot 2023-09-11 at 2 42 30 PM" src="https://github.com/unisonweb/unison/assets/977929/6d5674b3-0bea-4620-932e-3e415744a41f">

You have to scroll down and find the `View all branches` link. It might be helpful to include this link near the top of the branches drop-down. Also maybe mention `View/manage branches` or something?

## Lingering modal box

After I delete a branch this modal dialog confirms success (yay), but then it sticks around even though it has served its purpose. Unless there is an action that I can take (like "undo"), then it probably should get out of the way. And even if there is an "undo" some day, this could still probably be a small notification that lives somewhere unobtrusive on the page.

<img width="593" alt="Screenshot 2023-09-11 at 2 45 46 PM" src="https://github.com/unisonweb/unison/assets/977929/91824c93-fcc3-473a-b61f-27c3f2ab8851">

## State doesn't sync

After I delete a branch and close the modal window I'm back on the "View all branches" page, but it still shows the branch that I just deleted. This makes me mentally keep track of some state (or refresh a bunch) if I want to go through and clean up a lot of branches.

**Comment by hojberg** [comment]
These should be fixed now and be deployed shortly.
