### ISSUE TITLE
Data constructors get incorrectly prefixed when one shares the same name as the type?

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#4330]
Here's an example. https://share.unison-lang.org/@unison/json/code/releases/1.0.1/latest/types/@c3699bcrq973hrdi5e1p4rvi597i65jem4la0061bp3m45hgeh7cn0d3na9uttd9snodugbroovcpmhfsvuv2893h80tbiltd4kj6qo

If you look at the namespace tree, you can see that the constructors are directly under the type's namespace, but that's not how they're rendered.

<img width="907" alt="CleanShot 2023-09-20 at 14 41 23@2x" src="https://github.com/unisonweb/unison/assets/11074/37c25a11-c9a9-456e-824a-2d0a3d17530b">

`view` handles things correctly:

```
@unison/json/main> view DecodingFailure

  unique type Decoder.DecodingFailure
    = DecodingFailure Text [PathElement] Json Any
    | ParseFailure ParseError
    | UnexpectedTrailingText Text Any
```

Problem also exists in the local UI.

Not urgent but this does look kinda janky and I wonder if it's something simple @ChrisPenner

**Comment by ChrisPenner** [comment]
Hrmm, I do see that we're using an `unsuffixified` ppe for constructors in the DeclPrinter, but don't know why.

Can you (or @runarorama ) think of any reason these might be intentionally unsuffixified?

https://github.com/unisonweb/unison/blob/6d11f10be9eef3b36e846f11ad4642f7d55cce4d/parser-typechecker/src/Unison/Syntax/DeclPrinter.hs#L117-L120

I vaguely recall that there's also a special case in the PPE somewhere for printing names of things within the same component that's currently being printed, which might be triggering this.

**Comment by ChrisPenner** [comment]
Found the other intentional unsuffixification: https://github.com/unisonweb/unison/blob/6d11f10be9eef3b36e846f11ad4642f7d55cce4d/parser-typechecker/src/Unison/PrettyPrintEnv/Util.hs#L19-L36

This makes sense in this case because the pretty printer always _thinks_ it's at the project root, so self-references (like constructor names) would need to be fully qualified to there, but on Share (and in constructors in general) it doesn't matter, so we probably don't need to do that.

**Comment by pchiusano** [comment]
@ChrisPenner the logic for getting the name of a constructor when it's printed within a type is supposed to be the following:

1. Get the fully qualified name of the type relative to the project root. Suppose this is `foo.bar.SomeType`
2. Get the fully qualified name of the constructor relative to the project root. Suppose this is `foo.bar.SomeType.multi.segment.constructor`
3. Strip the fully qualified type name from the prefix of the fully qualified constructor name. In this case, that would leave us with `multi.segment.constructor`.

You don't want to (say), just take the suffixed constructor name and use that, since doesn't round trip if the constructor name has multiple segments, the last of which is a unique suffix, and in other cases too.

**Comment by kylegoetz** [comment]
is this the same thing as #4300 ?

**Comment by aryairani** [comment]
Seems to be fixed now.
<img width="706" alt="image" src="https://github.com/unisonweb/unison/assets/538571/26f1c8a9-d6b1-41e1-86be-ce2865b0fb0a">
