### ISSUE TITLE
Pretty printer round-trip bug on constructor using lambda

### ISSUE THREAD

**Issue by alvaroc1** [unisonweb/unison#4340]
Version: release/M5f

This is how ucm pretty-prints the function:

```
  socketRouteHandler : Handler IO
  socketRouteHandler = HandlerWebSocket
    (cases
      req | Routes.get (root / "socket") req -> socketHandler
      _   -> abort)
```

But this produces a syntax error.
  
Changing the indentation allows ucm to accept it:

```
  socketRouteHandler : Handler IO
  socketRouteHandler = 
    HandlerWebSocket
      (cases
        req | Routes.get (root / "socket") req -> socketHandler
        _   -> abort)
```

**Comment by zetashift** [comment]
I have a similiar issue and I believe it's related to this.

Here's an example: https://share.unison-lang.org/@zetashift/unimark/code/@rlmark/nestedList/latest/namespaces/parser/listItem/;/terms/parseListItem

Notice the indentation the body starts unindented(you can already see it in the source in the Unison UI!):

```unison
parseListItem : Nat -> '{Parse err} ListItem2
parseListItem parentDepth = do use Debug trace
use Nat >
match !parseTabs with
  current   
    | current > parentDepth            ->
      trace "current depth greater than parent, nesting" current
      !(isNest current)
    | Universal.eq current parentDepth ->
      trace "current depth equals parent, siblings found" current
      !(isSibling current)
  otherwise ->
    trace "current depth less than parent, backtracking" otherwise
    Parse.fail (Error.Expected "nested list item" (Position _mark))
```
If you edit this term in the editor, it comes out exactly the same.

EDIT: created a separate issue about this, just in case: https://github.com/unisonweb/unison/issues/4344

**Comment by pchiusano** [comment]
@zetashift yeah, #4344 is unrelated but I have a fix for it in https://github.com/unisonweb/unison/pull/4368

@alvaroc1 am still trying to reproduce this, since when I try to simplify it I get:

```haskell
HandlerWebSocket x = x

socketRouteHandler = HandlerWebSocket cases
  1 -> 1
  _ -> abort
```

which round trips fine.

And in general, for a function call like this where the last argument is a `cases`, I'd expect that to render without parens around the cases.

**Comment by pchiusano** [comment]
Okay got a repro, the `HandlerWebSocket` actually needs to be a data constructor. If it's a function call then it doesn't trigger the bug. Very weird, but okay.
