### ISSUE TITLE
Blog post titles are not properly HTML decoded in the "Help & Resources" menu

### ISSUE THREAD

**Issue by JohanWinther** [unisonweb/unison#4360]
Under the "Help & Resources" menu on Unison Share there are links to the posts on the Unison blog. These titles have some HTML encoding artefacts:
![image](https://github.com/unisonweb/unison/assets/28558941/9c7a2457-c831-4bbe-8da2-4e5395f26a7b)

**Comment by hojberg** [comment]
Fixed :)
