### ISSUE TITLE
Support block comments

### ISSUE THREAD

**Issue by BenFradet** [unisonweb/unison#437]
It seems `{-` and `-}` don't parse:

```
Token {payload = Open "{", start = Pos 9 1, end = Pos 9 2} :| []
.../unison/unison-src/example-errors.u:9:1:
unexpected {
expecting binding or namespace
    9 | {- Ideal error:
```

**Comment by pchiusano** [comment]
We should definitely have something like block comments, but we are going to do a more comprehensive rethink of how comments in Unison, tracked in #443.

**Comment by aryairani** [comment]
@BenFradet Currently the Unison parser treats everything from `---` to EOF as ignored.  I haven't put any effort into figuring out how to implement that in the syntax highlighter, but it would be great  😁😁😁

**Comment by aryairani** [comment]
@BenFradet Maybe something like [this](https://github.com/theia-ide/theia/blob/master/packages/textmate-grammars/data/perl.tmLanguage.json#L884-L898)? (Perl 5 treated everything from `__DATA__` or `__END__` to EOF specially.)

**Comment by aryairani** [comment]
@BenFradet I got excited and went ahead: https://github.com/unisonweb/unison/commit/6e98189fea95e79099ff955f23287028cb6d9a55

**Comment by BenFradet** [comment]
ah excellent, I'll port that to the vscode plugin, thanks! :+1:
