### ISSUE TITLE
Pretty printer adding duplicative abilities

### ISSUE THREAD

**Issue by kylegoetz** [unisonweb/unison#4382]
I had

```
api.utils.getHueResource :
  ResourceType
  -> '{Decoder} a
  -> Optional ResourceId
  ->'{IO, Exception, Ask (Settings, HueApiKey)} HueResponse
    a
api.utils.getHueResource rtype d rid =
  use Text ++
  makeRequest''
    ("resource/"
      ++ ResourceType.show rtype
      ++ (rid
           |> Optional.map (ResourceId.show >> (++) "/")
           |> Optional.getOrElse ""))
    GET
    |> handleHueRequest d

```

When I `update` the response is

```
huenison/backup> update

  ⊡ Ignored previously added definitions: api.utils.getHueResource
```

and then it hangs (or at least doesn't present the `huenison/backup>` prompt to me again to type anything for 20–30 seconds (presumably checking dependents for update).

Once I get the prompt again, I try

```
huenison/backup> view api.utils.getHueResource

  api.utils.getHueResource :
    ResourceType
    -> '{Decoder} a
    -> Optional ResourceId
    ->{Ask (Settings, HueApiKey)} '{IO, Exception, Ask (Settings, HueApiKey)} HueResponse a
  api.utils.getHueResource rtype d rid =
    use Text ++
    makeRequest''
      ("resource/"
        ++ ResourceType.show rtype
        ++ (rid |> Optional.map (ResourceId.show >> (++) "/") |> Optional.getOrElse ""))
      GET
      |> handleHueRequest d
```

Observe that now, the return value of the function is `{Ask (Settings, HueApiKey)} '{... Ask (Settings, HueApiKey)} ` but the typesig I added just returns `'{IO, Exception, Ask (Settings, HueApiKey)} HueResponse`

**Comment by SystemFw** [comment]
I actually think it's behaving correctly and inferring Ask because you might be calling it strictly from the function, but I cannot tell for sure without knowing the types of the functions you are calling. If you don't write any abilities next to a function arrow, ucm will infer them for you. You can force no abilities with ->{} , and if I'm right it should give you a type error in this case saying that you use Ask.
BTW, unless you are returning Stream or Decoder, I would recommend not returning thunks, but directly attaching abilities to the output arrow

**Comment by kylegoetz** [comment]
@systemfw But it shouldn't be inferring, because my original type *explicitly* indicated the Ask:

```
api.utils.getHueResource :
  ResourceType
  -> '{Decoder} a
  -> Optional ResourceId
  ->'{IO, Exception, Ask (Settings, HueApiKey)} HueResponse
    a
api.utils.getHueResource rtype d rid =
  use Text ++
  makeRequest''
    ("resource/"
      ++ ResourceType.show rtype
      ++ (rid
           |> Optional.map (ResourceId.show >> (++) "/")
           |> Optional.getOrElse ""))
    GET
    |> handleHueRequest d
```

That's the first bit of code I shared in my original issue.

The pretty printer is turning

`{IO, Exception Ask (Settings, HueApiKey)} HueResponse`

into

`{Ask (Settings, HueApiKey)} '{IO, Exception, Ask (Settings, HueApiKey)} HueResponse a`

It doesn't need to infer ask because I already have it there.

> BTW, unless you are returning Stream or Decoder, I would recommend not returning thunks, but directly attaching abilities to the output arrow

Can you explain why? Isn't it preferable in functional languages to lazily evaluate things like async calls?

**Comment by kylegoetz** [comment]
Actually I think I understand the original issue now. The Ask I wrote is inside the thunk, but creating the thunk requires the Ask, so I needed the Ask outside the thunk, as in `{Ask...} '{IO...}` or something. But I actually just got rid of the thunkmark completely unless it was required (i.e., in the case

```
foo : '{Ask ...} MyApiResponse

```
