### ISSUE TITLE
library for key-value store

### ISSUE THREAD

**Issue by sfultong** [unisonweb/unison#44]
see https://github.com/unisonweb/unison/pull/43#issuecomment-210556072

As I understand it, I'll be adding basic key-value store functionality as builtins in the unison language.

**Comment by Ericson2314** [comment]
https://github.com/dmbarbour/haskell-vcache/issues/5 might be interesting. I was kinda planning on actually doing this and then mentioning it here, but I can't get around to that for a long time.

**Comment by sfultong** [comment]
The example API given by @pchiusano 
`data Index k v

index : Remote! (Index k v)
lookup : k -> Index k v -> Remote! (Maybe v)
delete : k -> Index k v -> Remote! ()
-- keys : Index k v -> Stream Remote! k`

I'm unsure of how data types will be constructed in unison. So far, all types have kind *. So I'm not sure how Index will work.

To start, I'll just make a String/String key value store interface.

**Comment by pchiusano** [comment]
Closed via #75
