### ISSUE TITLE
docs.to-html should support projects arguments

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#4402]
Currently the docs.to-html command expects a path to namespaces like ".myPath.to.namepsace" but in the projects ecosystem there is no way to refer to the root of the current project. It would be great if the docs.to-html command could support turning items like top-level README's into html. 

Also currently, if you follow the suggested help text and give a path argument like `~/my/path` it will create a directory called `~` in your codebase and that is a bit dangerous.

**Comment by sellout** [comment]
I’ve extracted the `~` issue to #5112. The example also had `namespace` as a path segment, which isn’t allowed.

In #5111 I changed the examples to avoid both of these issues.
