### ISSUE TITLE
Login problem in app.unison.cloud with Firefox

### ISSUE THREAD

**Issue by gfinol** [unisonweb/unison#4403]
When login to [https://app.unison.cloud/](https://app.unison.cloud/) using MZ Firefox (version 119.0.1, linux) I get the following error page:

![error image](https://github.com/unisonweb/unison/assets/11145254/27b6fb1c-673f-49fa-9db0-0be465d6a8ac)

"Try again" button redirects me to the main [app.unison.cloud](app.unison.cloud) page with a successful login.  The error appears regardless of whether I'm logged into Share or not.

**Comment by pchiusano** [comment]
@hojberg any idea what this is about? Or @ChrisPenner

**Comment by hojberg** [comment]
Hmm I can't reproduce this with any browser. @gfinol Is it consistently happening or was just the one time? cc @stew

**Comment by ChrisPenner** [comment]
I'm also unable to reproduce, have you tried clearing your cookies and trying again?

> You can remove all data stored in Firefox for a specific domain via "Forget About This Site" in the right-click context menu of an history entry ("History -> Show All History" or "View -> Sidebar -> History").

Try telling Firefox to forget the site on both `app.unison.cloud` as well as `api.unison.cloud` (even though the latter will return a "404 - not found" page) 😄

**Comment by gfinol** [comment]
After telling Firefox to forget both sites, nothing changed. 

But I managed to get rid of the error by adding an exception to the HTTPS-only mode for `app.unison.cloud`. 

If you want to try to reproduce it, to activate the HTTPS-only mode in Firefox you need to go: Settings -> Privacy & Security -> HTTPS-Only Mode -> `Enable HTTPS-Only Mode in all windows`.

**Comment by stew** [comment]
ok, weird, so when I enable https-only mode and then sign out and sign back in on https://app.unison.cloud I get an error 

```
The page isn’t redirecting properly

Firefox has detected that the server is redirecting the request for this address in a way that will never complete.
```

with a "try again" button. and when I hit "try again" it succeeds.

**Comment by stew** [comment]
in fact you don't need to hit the "try again" button at that point, the URL is "app.unison.cloud" and if you refresh, you are already logged in?

**Comment by gfinol** [comment]
Yes, that's the behavior that I've seen. 

I also notice that each time I Sing in or Sing out, Firefox opens a new tab. Is that the expected behavior? May it be related to the error?

**Comment by ceedubs** [comment]
@gfinol thanks again for reporting this. @ChrisPenner and @hojberg have identified the issue and resolved it. Can you please verify that you don't encounter it even if you remove the exception from your Firefox settings?

**Comment by gfinol** [comment]
@ceedubs Issue solved!
