### ISSUE TITLE
`bug "uh oh"` should not be tagged as a Doc or a Test

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#4407]
Currently it is probably both, with preference given to Doc.
<img width="988" alt="image" src="https://github.com/unisonweb/unison/assets/538571/74c6e1ee-6019-44b9-b574-2b9fde09c3de">

See `getTermTag` in `Backend.hs`; we don't want a subtype test here. I think `==` will work, but I haven't tried it.

cc @hojberg

**Comment by ChrisPenner** [comment]
I'll have to take time to test it yet, but whipped up the fix quick before I forget: https://github.com/unisonweb/unison/pull/4408

**Comment by ceedubs** [comment]
Something subtle:

For the purposes of `io.test`, `'{} [Test.Result]`, `'{IO} [Test.Result]`, `'{Exception} [Test.Result]`, and `'{Exception, IO} [Test.Result]` should probably all match. That is, it's probably fine do an exact match for the `Test.Result`, but you _do_ probably want subtyping for the abilities.
