### ISSUE TITLE
Unable to resolve type name

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#4415]
Just put this in a scratch file:

```
unique type A = C Int
unique type sub.A = D Int

--- results in

    ❓
    
    I couldn't resolve any of these symbols:
    
        1 | unique type A = C Int
    
    
    Symbol   Suggestions
             
    A        No matches
 
```

@stew reported this, it was introduced in M5g.

**Comment by stew** [comment]
```c4920426ed58bdd046a0858abd74936fe9aee0f5 is the first bad commit
commit c4920426ed58bdd046a0858abd74936fe9aee0f5
Author: Paul Chiusano <paul.chiusano@gmail.com>
Date:   Thu Sep 14 08:51:53 2023 -0500

    fixes type signature resolution issue

 parser-typechecker/src/Unison/UnisonFile/Names.hs | 31 +++++++++++++++++++++--
 unison-core/src/Unison/DataDeclaration/Names.hs   | 13 +++++++---
 unison-src/transcripts/fix3759.md                 | 22 ++++++++++++++++
 unison-src/transcripts/fix3759.output.md          | 28 ++++++++++++++++++++
 4 files changed, 89 insertions(+), 5 deletions(-)
 create mode 100644 unison-src/transcripts/fix3759.md
 create mode 100644 unison-src/transcripts/fix3759.output.md

```

**Comment by aryairani** [comment]
@pchiusano When the name in the scratch file also exists in the codebase, we get an even crazier situation, where the type of the result of the constructor call comes from the codebase, not from the scratch file (reminiscent of #4325 where the bisected commit came from), leading to an invalid decl (and a crash)

e.g. `scratch.C : Int -> codebase.C` instead of `scratch.C : Int -> scratch.C`

Can you give any insights  re. #4325?

**Comment by tstat** [comment]
Looks to me like the issue arises from here:
https://github.com/unisonweb/unison/blob/bc0788ba53abc77613674916cf263b21a0eb4b89/parser-typechecker/src/Unison/UnisonFile/Names.hs#L111
where we drop all mutimap keys that have non-singleton values. One of these keys could be the FQN for a type or term (e.g. `Foo => [Foo, sub.Foo]`), then we drop it and have no mapping for `Foo`.

I don't know the context of this `variableCanonicalizer` function, but I assume we want to keep some name for every input?

**Comment by pchiusano** [comment]
@tstat yeah I think it's that - it comes up when there's FQNs `Foo` and `blah.Foo`, where one is a suffix of the other, so both end up getting removed.

My guess is ensuring that all FQNs at least map to themselves would fix.

**Comment by pchiusano** [comment]
@stew btw appreciate reporting this and bisecting it! Made it very easy to track down the cause.
