### ISSUE TITLE
let `fork` reference `<project/branch>[.path]`

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#4423]
### Background
I have branches `mylib/main` and `myapp/main`, 
and I want to use `mylib` as a lib dependency of `myapp`.

Right now I don't know of a way to do that.

This doesn't work:
```
myapp/main> fork mylib/main .lib.mylib

  extra characters after mylib: "/main"
```

This works but isn't great:
```
myapp/main> switch mylib                          
mylib/main> history

  Note: The most recent namespace hash is immediately below this message.
  
  
  
  □ 1. #9q4lmbo6c9 (start of history)

mylib/main> switch myapp
myapp/main> fork 1 .lib.mylib

  Done.

myapp/main> ls lib

  1. base/ (6461 terms, 157 types)

myapp/main> fork 1 lib.mylib 

  Done.

myapp/main> ls lib          

  1. base/  (6461 terms, 157 types)
  2. mylib/ (6461 terms, 157 types)

myapp/main> 
```

This doesn't work:
```
myapp/main> history mylib/main
```

### Proposal
Make this work:
```
fork mylib/main lib.mylib
```

I'd also propose we make absolute paths reference the root of the branch, not anything else, but that's gotta fit into some bigger picture.

**Comment by hojberg** [comment]
Whats a "pseudo-lib"?

**Comment by aryairani** [comment]
@hojberg I just meant the kind of libs we have right now

**Comment by hojberg** [comment]
@aryairani gotcha, so this is meant to be able to add the dependency local without first having to push it remotely?

**Comment by aryairani** [comment]
@hojberg yeah exactly

**Comment by aryairani** [comment]
I think this has become:  "Let `fork` accept `<project-branch>` args or even `<project-branch>[.path]` args.

**Comment by aryairani** [comment]
We want to be careful about bringing in code that will be missing dependencies, however. Need a plan for that.

**Comment by aryairani** [comment]
part of #4470

**Comment by ceedubs** [comment]
> so this is meant to be able to add the dependency local without first having to push it remotely?

> yeah exactly

In this case what you really want is something more like `merge.squashed` (no history) , like we have in releases, right? Otherwise the gain that you get my not going through a remote server will be offset by a bulky history in your `lib` namespace.
