### ISSUE TITLE
Needs design: how do you document and attach comments to Unison code?

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#443]
Would be nice if comments and docs could be a more permanent artifact... right now comments are discarded by the lexer, which is obv not going to work especially since we're expecting the `.u` scratch files to get discarded or recycled.

Some interesting ideas:

* Documentation could be associated with a hash, and added after the fact.
* A "comment" might refer to a hash, and the a path into some subexpression of that hash's definition.
* It would be great if you don't need to produce a new release of something just to update its documentation, like you do now when the docs are literally just strings embedded in the source code.
* Documentation could be a more structured thing so it can be hyperlinked automatically, and renames propagate automatically to the docs.

Open question:

* How to reconcile different docs or comments for the same definition?

**Comment by atacratic** [comment]
Was thinking about this after Runar's Twitter [thread](https://twitter.com/runarorama/status/1115688300512202753?s=09).

I'd been wondering before how people 'get their files back', i.e. after their definitions and watch expressions get slurped into the codebase, how do they get that 'view' again.  Is there a 'notebook' concept?

If there is, maybe it is the same concept as is used by documentation. 'Want to understand this function? Sure, take a look at this explanation I wrote, plus some live examples from the test suite, and then the actual code.' Each function could have a notebook that acts as its 'comment'. Plus you could write other explanatory notebooks, not tied to specific functions, perhaps to explain some aspect of the wider design.

It's not clear to me how this would relate to explanatory annotations written inline within a function definition - maybe only simple text is allowed inline.

(I wonder if the text format is plain text, markdown, or 'an expression which can be evaluated to yield text'?)

**Comment by ChrisPenner** [comment]
Is it possible to simply associate all comments with a specific AST node? Then just have different printing strategies accordingly.

This seems the most flexible to me; function docs are just the comment associated with the root of the AST representing the function; but it also allows you to associate comments with types, function parameters, where clauses etc. Which may have uses we haven't even thought of yet.

**Comment by pchiusano** [comment]
See #462 posted a draft for comment.
