### ISSUE TITLE
eliminate loose code in ucm

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#4439]
- [ ] support forking code between projects/branches; currently loose code is used for that
- [ ] move it to a project
- [ ] update the docs / tutorials
- [ ] root branch implications

Seems like we should focus on supporting project workflows before putting energy into removing loose code?
Does leaving it as-is slow us down somehow?

- [ ] What about loose code on Share?
  - [ ] someone may depend on unmigrated share loose code
  - [ ] what about exercism?

**Comment by ceedubs** [comment]
Some use-cases that I think need to be addressed before eliminating loose code:

- #4253
- #4423
