### ISSUE TITLE
troubles with upgrading

### ISSUE THREAD

**Issue by stew** [unisonweb/unison#4449]
if you pull this repo:

https://share.unison-lang.org/@stew/testupdate/code/main

then run:

```
upgrade httpserver_1_0_2 httpserver_1_0_3
```

There are a number of problems with the things emitted into the scratch file:

1. It will put things into the scratch file unrelated to the upgrade
2. It will mange all the places that constructors named `Id` are referenced
3. It will mangle the Doc, breaking the typecheck block

**Comment by aryairani** [comment]
From https://unisoncomputing.slack.com/archives/CLGTK464E/p1701295022964219

> i'm upgrading from one version of httpserver to another, when I ran upgrade, it pulled lots of stuff into the buffer that I don't think it should have, for example:
> ```
> Environment.id.doc : Doc
> Environment.id.doc = {{ The unique identifier assigned to an environment. }}
> ```
> That can't possibly have been affected by a library upgrade. In doing this it pulled in a bunch of types it didn't need to and mangled some of their constructor names:
> ```
> unique ability durable.SkipList.internal.test.MapGeneration where
>   insert : Nat -> Bytes ->{durable.SkipList.internal.test.MapGeneration} ()
>   delete#7qjsk7rq#1 : Nat ->{durable.SkipList.internal.test.MapGeneration} ()
> ```
> ```
> unique type Database.Id
>   = Id#imemkql6#0 Text
> ```
> and that means that anywhere we pattern match on these constructors I have make edits:
> ```
> Database.Id.toText : Database.Id -> Text
> Database.Id.toText = cases Id#imemkql6#0 t -> t
> ```
> this is really rough, we have a ton of constructors named "Id" and it affects every call site and every pattern match

**Comment by aryairani** [comment]
These specific issues should be resolved by #4486
