### ISSUE TITLE
Should be possible to view any hash, even if it's not in the current branch

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#447]
Might let us figure out stuff like #400 and is just generally useful.

Idea for implementation - could just `mappend` all the `PrettyPrintEnv` for all branches, then print it using that combined environment. 

There's probably a more efficient implementation with a better codebase repo format than the one we have now.

**Comment by aryairani** [comment]
I would say this is currently done, although we currently see a limitation that we can only view terms that are found in the branch history, _not_ orphaned ones.  

e.g., this is okay:

```unison
x = 5
```

```ucm
.> add

  ⍟ I've added these definitions:
  
    x : ##Nat

.> names x

  Term
  Hash:   #fcqruba3pl
  Names:  x

.> delete.term x

  Removed definitions:
  
    1. x : ##Nat
  
  Tip: You can use `undo` or `reflog` to undo this change.

.> view #fcqruba3pl

  x#fcqruba3pl : ##Nat
  x#fcqruba3pl = 5

```

but this is not (note the use of `undo` rather than `delete`):

```unison
x = 5
```

```ucm
.> add

  ⍟ I've added these definitions:
  
    x : ##Nat

.> names x

  Term
  Hash:   #fcqruba3pl
  Names:  x

.> undo

  Here's the changes I undid
  
  Added definitions:
  
    1. x : ##Nat

.> view #fcqruba3pl

  ⚠️
  
  The following names were not found in the codebase. Check your spelling.
    #fcqruba3pl

```
