### ISSUE TITLE
DocTable no longer supports Header elements in cells

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#4476]
I've been trying to get some website updates done and fighting what appear to be a few Docs regressions. 

This minified Doc shows the problem where header elements `#` used to be able to be table headings, but are now rejected. 

```
whatProblemsDoesUnisonSolve : Doc
whatProblemsDoesUnisonSolve = {{

  # What problems does Unison solve?

    {{ docTable [ [{{ # The problem }}, {{ # Our remedy }}]
      , [ {{
          a
          }}
        , {{
          b
          }}
        ]
      ] }}
  }}
```

The error is 

```
  offset=128:
  unexpected "# "
  expecting "}}" or white space
```

**Comment by pchiusano** [comment]
Is this in trunk? I think a recent PR might have fixed this, but it's not in a release yet. You can try a dev release if you don't feel like building from source.

**Comment by neduard** [comment]
Heya, might be wrong but I'm wondering if this is actually related (if not the same) as https://github.com/unisonweb/unison/issues/4729 🤔  I've been looking into that one and this seems almost identical, especially since if we add an extra `#` to the _inner headings_ then it seems to parse?

```
    whatProblemsDoesUnisonSolve : Doc
    whatProblemsDoesUnisonSolve = {{
    
      # What problems does Unison solve?
    
        {{ docTable [ [{{ ## The problem }}, {{ ## Our remedy }}]
          , [ {{
              a
              }}
            , {{
              b
              }}
            ]
          ] }}
      }}
```

```
witty-toad/main> add

  ⍟ I've added these definitions:

    whatProblemsDoesUnisonSolve : Doc

witty-toad/main> display whatProblemsDoesUnisonSolve

  # What problems does Unison solve?

    # The problem   # Our remedy
    a               b

witty-toad/main>
```
