### ISSUE TITLE
Top level definitions evaluation is by name / not cached

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#4495]
This is sort of a footgun if you happen to directly write a loop or recursive function that references a top level definition.

Seems like we could just cache the result, @dolio can you see any issues with this?

```
foo = range 0 1000
```

**Comment by pchiusano** [comment]
I think this is kind of a footgun. We could fix either by lazily evaluating and caching (possibly complicated), or just evaluating the pure code strictly when the top level definition is compiled.

**Comment by ceedubs** [comment]
@ChrisPenner this was resolved by #5379, right?

**Comment by ChrisPenner** [comment]
@ceedubs For the interpreter yes, I'm not sure about the JIT, cc @dolio .

**Comment by dolio** [comment]
Oh, it's almost fixed for the jit. I think I can probably complete it now.
