### ISSUE TITLE
Possible `push` inefficiency

### ISSUE THREAD

**Issue by kylegoetz** [unisonweb/unison#4496]
1. clone lib.base (not as user `@unison`)
2. create a new branch
3. change one function definition
4. push as yourself

When I did this, this was the output:

```
@unison/base/offsetDateTimeFromIso8601DocTypo> push

  Uploaded 11979 entities.


  I just created @unison/base/@kylegoetz/offsetDateTimeFromIso8601DocTypo on
  https://api.unison-lang.org
```

Shouldn't only 1 entity need to be uploaded?

**Comment by aryairani** [comment]
Hi @kylegoetz, this is a known / intentional issue due to a temporary technical limitation. We can leave the ticket open to track it though.

We have a hack in the works to help though until we can plan the less hacky fix.

In the mean time though, you should only have to reupload it once, not more than once.

**Comment by kylegoetz** [comment]
Would this same issue be related to this:

```
serverSentEvent/main> clone @unison/http 

  Downloaded 35443 entities.


  Cloned @unison/http/main.

@unison/http/main> edit HttpResponse.fromStream

[snip]
@unison/http/main> branch typo

[snip]

@unison/http/typo> update

[snip]

@unison/http/typo> push

  Uploaded 98133 entities.
```

Downloaded 35K but uploaded 98K. The only thing I did was change one character of a Text from "o" to "u"

**Comment by aryairani** [comment]
@kylegoetz I believe this is fixed now; can you confirm or deny?

**Comment by kylegoetz** [comment]
Doesn't appear to happen anymore. I"ve been pushing a `runtime-tests` branch and whenever I do, it's just a handful of the entities being uploaded. Given the low number, I'm assuming it's just the modified term + the descendants that are updated to use a different hash for the term.
