### ISSUE TITLE
issue round-tripping records in that decl and accessors are printed independently/duplicatively

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#4501]
need a transcript

**Comment by ceedubs** [comment]
Is this issue referring specifically to `update`/`upgrade`? Because #4232 exists for `edit`.

**Comment by aryairani** [comment]
@ceedubs Yes it was specifically for `update`/`upgrade`, though we don't have a reproduction, just a report.

**Comment by ceedubs** [comment]
I have definitely run into this, but there have been some improvements to `upgrade` recently, so maybe it doesn't come up (or not very often) any more. I'll keep an eye out for it.

**Comment by mitchellwrosen** [comment]
I'm gonna close this until we have a repro (or at least someone saying "this definitely still happens")
