### ISSUE TITLE
UCM ANSI colors invisible in popular color schemes

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#4510]
Here's iTerm2 with Solarized Dark, the most popular color scheme for iTerm2:

<img width="580" alt="image" src="https://github.com/unisonweb/unison/assets/130916/8425bfc9-ce61-4aae-8023-cb07f8b0c5b5">

Here's iTerm2 with Gruvbox Light, another popular scheme:

<img width="571" alt="image" src="https://github.com/unisonweb/unison/assets/130916/f755ad17-9a05-4968-af48-58ceec8d2002">

Maybe we can make sure the screen is legible in like the top 6 most popular color schemes (in both dark and light variants):

1. Solarized
2. Monokai
3. Gruvbox
4. Nord
5. Dracula
6. Tomorrow Night

**Comment by pchiusano** [comment]
Which ANSI colors are causing problems here? We could either not use those colors (seems like kind of a bummer) or submit PRs upstream, since this issue would affect any program using those color schemes with ANSI codes.

**Comment by fwip** [comment]
It seems that it is unlikely that Solarized Dark will fix this upstream, unfortunately. Here's an open issue from 2012 tracking the problem. https://github.com/altercation/solarized/issues/220

**Comment by pchiusano** [comment]
Good grief, I just made the mistake of reading that thread and it made me sad. But yeah, let's not counting on upstream ever changing. :) 

To fix this (PR welcome!!), check in `ColorText.hs`. It looks like we should avoid the `HiBlack` ANSI code (and `Black` too but I don't think we use that anywhere) since some color schemes have that very similar to the background color. 

Also maybe just grep for `Black` and `HiBlack`.

```
defaultColors :: ST.Element r -> Maybe Color
defaultColors = \case
  ST.NumericLiteral -> Nothing
  ST.TextLiteral -> Nothing
  ST.BytesLiteral -> Just HiBlack
  ST.CharLiteral -> Nothing
  ST.BooleanLiteral -> Nothing
  ST.Blank -> Nothing
  ST.Var -> Nothing
  ST.TypeReference _ -> Nothing
  ST.TermReference _ -> Nothing
  ST.Op _ -> Nothing
  ST.Unit -> Nothing
  ST.AbilityBraces -> Just HiBlack
  ST.ControlKeyword -> Just Bold
  ST.LinkKeyword -> Just HiBlack
  ST.TypeOperator -> Just HiBlack
  ST.BindingEquals -> Nothing
  ST.TypeAscriptionColon -> Just Blue
  ST.DataTypeKeyword -> Nothing
  ST.DataTypeParams -> Nothing
  ST.DataTypeModifier -> Nothing
  ST.UseKeyword -> Just HiBlack
  ST.UsePrefix -> Just HiBlack
  ST.UseSuffix -> Just HiBlack
  ST.HashQualifier _ -> Just HiBlack
  ST.DelayForceChar -> Just Yellow
  ST.DelimiterChar -> Nothing
  ST.Parenthesis -> Nothing
  ST.DocDelimiter -> Just Green
  ST.DocKeyword -> Just Bold
```
