### ISSUE TITLE
Doc example code that intentionally doesn't compile

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#4516]
It would be nice to be able to intentionally demonstrate compile errors in a `Doc`. For example:

```
demoVoid : Either Void Nat -> Nat
demoVoid = cases
  Left v -> absurd v
  Right n -> n
```

This code doesn't compile, because the typechecker correctly identifies that the `Left` case can never happen (and therefore should be removed). But there isn't a great way to show this in a `Doc`. You could make a raw text code block, but that won't show you the compile error that the code would generate.

I won't be surprised if someone tells me that this is actually a super hard problem in Unison. Like would the example code just be a `Text` value? Would terms referenced in the code need to actually resolve to hashes, and if so would that manifest differently than other compile errors?

**Comment by aryairani** [comment]
Based on the message, you already know about raw text / monospaced blocks `'' unison code ''`.
```
'' 
more unison code
''
```

Sounds like you are asking for some sort of construction in a doc that would actually try to typecheck the code in the block, and the resulting error would be shown in the doc as well.

Would it be typechecked relative to the project the doc is in, or are you showing a compile error in a different project? 
Would you expect the error to change when ucm's typechecking changes?

For now I would recommend just using monospaced blocks as above for both the code and the error message you're trying to demonstrate.

**Comment by aryairani** [comment]
In an effort to close issues, I'm going to close this issue as wontfix, but feel free to reopen it to renew your request.
