### ISSUE TITLE
`ls -l` formatting bug causes type sigs to wrap harshly when terminal isn't wide enough to accommodate a definition's full hash

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#452]
![image](https://user-images.githubusercontent.com/538571/55825554-362d0f00-5ad4-11e9-868e-5fbbb5b32623.png)

I don't mind that the hash itself wraps, but the types shouldn't have to.  

Side note, this way that the types currently wrap won't currently parse (#254).

**Comment by pchiusano** [comment]
This is fixed in 466792a. I just put a `P.group` around the type signature rendering - this prevents it from breaking even if/when the outer thing doesn't fit.
