### ISSUE TITLE
add selected fzf completion to command history

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#4526]
Consider the following scenario:

- I run a no-arg `view`, which brings definitions into fzf
- I pick `ns1.ns2.ns3.ns4.myTerm` from the fzf selection
- Now I decide that I want to edit `myTerm`. If I hit the up arrow, my command history just shows `view` as opposed to `view ns1.ns2.ns3.ns4.myTerm`, so I can't just hit the up arrow and swap out `view` for `edit`.

If `myTerm` is unambiguous then I can just type an unqualified `myTerm`. But:

- I still won't get auto-completion while typing `myTerm`
- It may be ambiguous: I might have several `myTerm` names in different namespaces
- The name might be something more like `makeHttpRequestAndHandleFailures` instead of `myTerm`, which is a lot to type out.

I don't know whether this is trivial or impossible, but I often want it.

**Comment by aryairani** [comment]
@ChrisPenner was looking into this this morning.

**Comment by ChrisPenner** [comment]
I know how to do this now :),
However I'm going to hold off until we implement `edit.namespace` because I think it'll make the `edit 1-1000` situation weird (i.e. HUGE arg lists in history and not being able to re-run `edit 1-1000` from history when you want to.)

**Comment by aryairani** [comment]
`edit.namespace` is now implemented (:
