### ISSUE TITLE
add.run `CallStack` error issue on 0.5.11 

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#4528]
When writing cloud services, you might choose to `add.run` the last deployment to add a `ServiceHash` into the project for others to call. Currently this causes the UCM to exit with the message 

```
   ( Id "cpkb5ammhcpec7ju8fc4qfshq1lvdq7elgcn79u25khg3jjmu6fbj7rbvt64pacemhfhp2vftngfk61nlotqqivg064f5p9ruhf7t60" 0 )
  CallStack ( from HasCallStack ):
    error

```

A transcript reproducing the issue is attached here. 

[addRunIssue.md](https://github.com/unisonweb/unison/files/13708944/addRunIssue.md)

**Comment by aryairani** [comment]
@mitchellwrosen 🙏

**Comment by rlmark** [comment]
I noticed @mitchellwrosen had mentioned issues with the `run` command in the PR. In case it helps, here's a markdown file with a failing `run` case. Running where the return type should be a unique type returns a failure. 
[addRunIssueMini.md](https://github.com/unisonweb/unison/files/13721587/addRunIssueMini.md)
