### ISSUE TITLE
Unguarded circular let rec definitions shouldn't crash the CLI

### ISSUE THREAD

**Issue by sfultong** [unisonweb/unison#454]
Given
```
x = y + 1
y = if x Nat.< 5 then x else 5

> x
```

executing watch crashes with error
unison: user error (type error, expecting N, got (UninitializedLetRecSlot x in [y,x]))

**Comment by pchiusano** [comment]
Also, typechecker should report this as an error before getting to this point.

**Comment by pchiusano** [comment]
Removing this from M1 now that typechecker is preventing it. Should still be fixed at some point though.

**Comment by pchiusano** [comment]
Actually, going to close this. The real issue we want to fix is "runtime errors in your Unison program should not crash the CLI".
