### ISSUE TITLE
De-risk use of javascript to display a file from the containing repo

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#456]
There are three [locations that Github will publish GH Pages from][1]:

* `master:/`
* `master:/docs`
* `gh-pages:/`

This can be controlled in the github.com repo settings or with the [Pages API preview][2].  If there is a way to implicitly affect this setting just by carefully choosing the repo contents, I haven't yet been able to confirm it through experimentation.

Let's confirm that there are no XSS issues or whatever that would prevent us from loading data from Github via javascript.  

It would be nice if the user didn't have to worry about merge conflicts in display code when pushing an updated codebase.  (Display code should change relatively infrequently!)  Maybe we can achieve this by putting them in separate branches, e.g. codebase in `master:/` and display code lives in `gh-pages:/`.

---
So: Write a gh-pages doc that loads a file from an arbitrary Unison branch in the codebase. The Unison branch name shouldn't be known in advance. (We don't have to have changed the codebase format to JSON for these demos, just load some bytes and render them into a `<DIV>`.)

[1]: https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages
[2]: https://developer.github.com/changes/2019-03-14-enabling-disabling-pages/

**Comment by pchiusano** [comment]
Just discussing, thinking that it can't just be a totally static site, because (for instance) the set of branches is not known in advance and we don't want to have to update an index file every time (since that leads to conflicts). So how do we discover the files from JS and ensure we can load them?

Options are:

* A completely static site is just generated from the codebase, complete with an index file.
* JS could use GitHub API to enumerate directories of files (but then how does this work if viewing site locally??)
* Could have a web server in the CLI that lets them
* JS could be "dumb" - it requires a branch name or other parameters to be passed as part of the URL, but it's still a static site. And then you probably want some other layer to have "floating" URLs that refer to the latest code.
* `explore <commit>` opens the codebase in a browser as of that commit

**Comment by aryairani** [comment]
Maybe useful: https://stackoverflow.com/a/53218452/310162

**Comment by aryairani** [comment]
https://en.wikipedia.org/wiki/Same-origin_policy#Origin_determination_rules

**Comment by aryairani** [comment]
Here are the http response headers from https://api.github.com/repos/unisonweb/unison/contents?ref=c0f8ca6d
```
HTTP/1.1 200 OK
Server: GitHub.com
Date: Fri, 12 Apr 2019 19:21:22 GMT
Status: 304 Not Modified
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 55
X-RateLimit-Reset: 1555100065
Cache-Control: public, max-age=60, s-maxage=60
Vary: Accept
Last-Modified: Thu, 11 Apr 2019 15:08:01 GMT
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
Access-Control-Allow-Origin: *
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
X-GitHub-Request-Id: C612:260C:2B7E28:6CFFA4:5CB0E52A
Content-Type: application/json; charset=utf-8
ETag: W/"3633d0b6734276dc7172a672617aec8d3e4174fd"
X-GitHub-Media-Type: unknown, github.v3
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Content-Encoding: gzip
```

I'm hoping that `Access-Control-Allow-Origin: *` means we can load it from any JS?  But I don't have much experience with [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing).

**Comment by aryairani** [comment]
Some sample JS from https://stackoverflow.com/a/18278346/310162:

```javascript
function loadJSON(path, success, error)
{
    var xhr = new XMLHttpRequest();
    xhr.onreadystatechange = function()
    {
        if (xhr.readyState === XMLHttpRequest.DONE) {
            if (xhr.status === 200) {
                if (success)
                    success(JSON.parse(xhr.responseText));
            } else {
                if (error)
                    error(xhr);
            }
        }
    };
    xhr.open("GET", path, true);
    xhr.send();
}
```
Call it as:
```javascript
loadJSON('my-file.json',
         function(data) { console.log(data); },
         function(xhr) { console.error(xhr); }
);
```
