### ISSUE TITLE
Make file watching robust to emacs `.#` files

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#457]
[Discussion in Gitter](https://gitter.im/unisonweb/unison?at=5cae481c759abc043c9d48da)

When editing `foo.u`, Emacs will apparently generate `.#foo.u` file temporarily, which is [a lockfile](https://www.gnu.org/software/emacs/manual/html_node/emacs/Interlocking.html) and not a parseable unison file. Unison tries to read it and then chaos ensues. 

Suggested fix:

* Maybe just modify [this line](https://github.com/unisonweb/unison/blob/711b83206df0c6c69d02332124660f37d34bb004/parser-typechecker/src/Unison/CommandLine.hs#L70) to filter out those files, for one.
* Also, file watching background process should never crash. [This code needs some error handling](https://github.com/unisonweb/unison/blob/711b83206df0c6c69d02332124660f37d34bb004/parser-typechecker/src/Unison/Codebase/Watch.hs#L70).

Workaround suggested by @alanz is to "set create-lockfiles to nil for that directory in emacs".

**Comment by alanz** [comment]
I think [this line](https://github.com/unisonweb/unison/blob/711b83206df0c6c69d02332124660f37d34bb004/parser-typechecker/src/Unison/Codebase/Watch.hs#L80) needs an exception handler around it too, in case the watched file is bad for any reason, as I think it silently kills the watcher thread if it fails

**Comment by pchiusano** [comment]
@alanz this should be fixed, see 47a44d1 

I didn't test with Emacs, I just created files prefixed with `.#` and made sure they got ignored. Let us know if you encounter any issues.

**Comment by alanz** [comment]
@pchiusano It now works under emacs, ignoring the lock files. Thanks.
