### ISSUE TITLE
Extract clear interface for interacting with Unison Codebase

### ISSUE THREAD

**Issue by ChrisPenner** [unisonweb/unison#458]
The motivation for clarifying the interface is the idea of allowing more things than just the CLI to interact with a unison codebase. The sooner we separate out the interface, the easier it'll be to do.

Looks like the lines are a little blurred ATM between the internal and external interfaces of manipulating the codebase; e.g. the CLI queries and mutates the codebase directly in response to user input sometimes.  First step I think would be to codify the list of commands that are valid to perform (e.g. add definition; list definitions on branch, create new branch) etc. Then abstract the code that DOES these things from the code that decides WHICH things to do; e.g. the CLI decides to issue a `view` request because someone typed it; but a separate module actually has the code which says how to complete the actions behind a View request.

I'm leaning towards a more 'text-based' interface for this level; which would allow issuing commands over a port; over JSON, over grpc; etc. The layer backing the external interface can do all the parsing, file-reading, and dirty work in a single place (so we don't end up doing it inside every front-end).

Some things to think about:
- If I want to add a definition via some actor communicating with the CLI via JSON should I specify the source code as a Text blob or point to some file and just give a name?
- How granular should this be? For instance the CLI currently checks if a branch exists and creates it if missing all in a single step; I think it would be helpful to split these actions up in the interface, e.g. have a `GetBranch` and a `CreateBranch` separately

This is just a scratchpad of ideas at the moment; but I'm potentially interested in working on this. I'd start with a series of refactorings before building anything new 😄

**Comment by aryairani** [comment]
Yeah, we had attempted to create a tidy interface to separate generic logic from presentation, but it's probably that some elements blended together.  There's the `Codebase v a` interface, as well as the higher-level `Command i v a` interface, both were meant to be agnostic to the client.  But we probably want to share some code between implementations of `Command`.

**Comment by aryairani** [comment]
I'm going to close this for now; we can always revisit.
