### ISSUE TITLE
[Question] Using CID/multihash

### ISSUE THREAD

**Issue by sideeffffect** [unisonweb/unison#459]
Does Unison use [`CID`](https://github.com/multiformats/cid)/[`multihash`](https://github.com/multiformats/multihash) (originated in IPFS/IPLD) for identifying programs (CID is probably the right thing, multihash is just a component of that)?
In short, it's a way to encode the hash in a self-describing and thus future-proof way.
I've only found https://github.com/unisonweb/unison/issues/87 but without any conclusion or indication if some ideas from IPFS got used.

**Comment by aryairani** [comment]
No, it doesn't, should it?

**Comment by sideeffffect** [comment]
I'm not intimately familiar with unison and its internals, but it makes a lot of sense at least from a distant point of view.
The *self-describing* and *future-proof* way of working with hashes (or any kind of ID) should be especially beneficial for Unison.

The fact that it would play nicely with IPFS & co. is a nice benefit, but CID would be very well usable for Unison just on its own.

**Comment by aryairani** [comment]
For M1 we should decide whether or not we want to put some codec parameters into the References themselves.

**Comment by pchiusano** [comment]
So, we aren't going to use multihash exactly, it's not quite a fit for Unison, but I think it's a good idea to prepend a Unison version number onto hashes, so they are more self-describing. We can do this easily for M1.

**Comment by sideeffffect** [comment]
I'm sorry to hear that, are you sure you don't want to reconsider? `multihash` (along with its [Haskell implementation](https://github.com/multiformats/haskell-multihash)) is a ready made solution and if you used it it would make Unison truly futureproof and more interoperable than the ad-hoc approach with _Unison version number onto hashes_.

regardless, thanks so much on working on Unison, it's a magnificent project!

**Comment by pchiusano** [comment]
@sideeffffect hmm I think maybe I've missed the point of multihash so please jump in and correct me :) - my understanding is that it's a representation of the hash which is self describing, that is, it says what hash algorithm was used to produce it. But for Unison, we have two pieces of information that are relevant, there's the actual hash function (like SHA3) but then also the code which is used to convert a Unison definition to a value of that hash, which may change between Unison versions. We need both those pieces of information (actually, I would say that the Unison implies the hash function, so including both is probably redundant).

Hmm, @aryairani was just telling me that we could possibly use the "multicodec" field for the Unison version? Does that sound right?

**Comment by sideeffffect** [comment]
the multiformats can stack like a Matryoshka, maybe you need more than just multihash, like multicodec.
Or just go straight with CID which I mentioned above. It has the following form

[`<cidv1> ::= <multibase-prefix><cid-version><multicodec-content-type><multihash-content-address>`](https://github.com/multiformats/cid#how-does-it-work)

**Comment by pchiusano** [comment]
CID seems like it would work, I'm going to close this issue and we'll track work on this in #466.
