### ISSUE TITLE
Create latest-stable-release download shortcuts for UCM executables

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#4593]
Currently, the Unison download instructions point users who are manually downloading linux, mac, and windows executables to the pre-release alias. It would be nice to have a `/latest` or `/latest-stable-release` alias for our executables so that users who did not need a "dev" release could all get an official version.

Notes from slack convo: 
* We might need to set up a redirect so that we don't need to re-point the latest stable release to a new version each time.
* Alternatively, we can go back to manually updating the hard-coded version url links on the website with each release.

**Comment by aryairani** [comment]
from https://unisoncomputing.slack.com/archives/CF8D3DCP3/p1704815140636399?thread_ts=1704738354.685239&cid=CF8D3DCP3

> Okay actually this totally does the right thing:
> `curl -L https://github.com/unisonweb/unison/releases/latest/download/ucm-linux.tar.gz` should work. The difference is `releases/latest/download` instead of `releases/download/latest`.

cc @rlmark

**Comment by aryairani** [comment]
I think with the url template above, this ticket is done; but reopen if disagree.
