### ISSUE TITLE
Parsing problem with doc annotations without the `unique` keyword

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#4634]
We recently removed the need for the `unique` keyword when defining types, but there seems to be a case where parsing breaks down, when having a doc annotation:

![CleanShot 2024-01-24 at 12 49 33@2x](https://github.com/unisonweb/unison/assets/2371/b5570c3f-292d-4fcc-9bf0-912881cd9c97)
The above fails to parse with this error:
![image](https://github.com/unisonweb/unison/assets/2371/950a7b66-db95-4727-81ca-57282bebbd55)
(which is pretty hard to know what to do with on its own)

![CleanShot 2024-01-24 at 12 52 00@2x](https://github.com/unisonweb/unison/assets/2371/276d79cf-0388-4172-ae56-aee4af6d59fd)
It works in the above example when adding the `unique` keyword.

**Comment by aryairani** [comment]
Weird, thanks for reporting
