### ISSUE TITLE
Investigate bugs in stream.uu

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#464]
We found some typechecker bugs in this file, stream2.uu, and stream3.uu, in the tests directory. Needs investigation.

**Comment by aryairani** [comment]
I made a pass over these, but they use namespace blocks which means they don't parse without modification, and I'm not sure even what error we're looking for, or what the problem part of the file was supposed to be. (Some of the type signatures were commented out, I'm not sure what that was trying to communicate.)

**Comment by aryairani** [comment]
`stream3.uu` typechecks today with minimal modifications.
`stream2.uu` has some other issue that seem at least superficially like user error.  I'm assuming these were masked by weirder typechecker issues in 2019, but that we are now ok to close.  Feel free to reopen if desired.

**Comment by aryairani** [comment]
![image](https://user-images.githubusercontent.com/538571/139558452-5ba6f5ec-5b84-453f-976f-70fb4ceac181.png)
