### ISSUE TITLE
Add sequence cons and snoc symbol function aliases

### ISSUE THREAD

**Issue by mrdziuban** [unisonweb/unison#471]
Add `+:` and `:+` as aliases for `cons` and `snoc`, as in https://github.com/mrdziuban/unison/commit/b0f68e1b9cdd7b9347f086b053d000aaf4159bbf. Depends on #468.

**Comment by aryairani** [comment]
fixed in f035083a6c0d5eb917ac41e300ef5d926b40eea1
```
  Now evaluating any watch expressions (lines starting with `>`)...

    1 | > (+:) == List.cons
          ⧩
          true

.> 
```
