### ISSUE TITLE
Type annotations not pushed down to branches of a `match`

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#4722]
I'll try to minimize this later, but given this code

<img width="1294" alt="CleanShot 2024-02-27 at 17 29 22@2x" src="https://github.com/unisonweb/unison/assets/11074/110d8bb3-250a-437f-b47b-50a4a750e639">

I get an unexpected failure:
```

>               needs the abilities: {𝕖3480}
    but was assumed to only require: {𝕖3405, 𝕖3406, 𝕖3407, Remote, Orderator (SearchResult id3199 url3205 (Unit ->{Remote} content3196))}
  
  This is likely a result of using an un-annotated function as an argument with concrete abilities. Try adding an annotation to the function definition whose body is red.
  
    141 |       (Orderator.subtractBy SearchResult.ordering (go q1) (go q2)) --  : '{Remote, Orderator (SearchResult id url ('{Remote} content)} ())
```

Annotating the result on line 141 makes it work. 

But this seems like it shouldn't be necessary - there's a type annotation on the function, which consists of a pattern match. Therefore the type of the RHS of each pattern match should match the signature, so we could be doing a `check` here and avoiding inference.

Aside is I'm not sure why inference fails here, but I'm proposing we avoid inference entirely in this case. That is:

```
check (a -> match a with Case1 -> blah) (x -> y)
==>
check blah y
```

**Comment by pchiusano** [comment]
I also tried changing the type of `Orderator.subtractBy`

```
up.Orderator.subtractBy : (a -> a -> Ordering) -> 
                          '{g, Orderator a} () -> 
                          '{g2, Orderator a} () -> 
                          '{g, g2, Orderator a} ()
up.Orderator.subtractBy ord a a2 = todo "Orderator.subtractBy"
```

but I get the same error

```
  The expression in red
  
                needs the abilities: {𝕖3484}
    but was assumed to only require: {𝕖3409, 𝕖3410, 𝕖3411, Remote, Orderator (SearchResult id3203 url3209 (Unit ->{Remote} content3200))}
  
  This is likely a result of using an un-annotated function as an argument with concrete abilities. Try adding an annotation to the function definition whose body is red.
  
    141 |       (Orderator.subtractBy SearchResult.ordering (go q1) (go q2)) --  : '{Remote, Orderator (SearchResult id url ('{Remote} content)} ())
```

**Comment by aryairani** [comment]
I saw this message several times in base round-trip errors too.

**Comment by aryairani** [comment]
I have another different repro which produces the same error message, I'll try to collect it here asap

**Comment by aryairani** [comment]
Here's my attempt to minimize:

```haskell
ability X a where yield : {X a} ()

f : '{g, X a} r -> '{g, X a} r
f s = s

foo : '{g, X a} () -> '{g, X a} ()
foo s = do
  go s =
    x = f s
    go x
  go s
```

The above typechecks, but if I substitute the definition of `x` into the usage of `x`, it fails:

```haskell
foo' : '{g, X a} () -> '{g, X a} ()
foo' s = do
  go s =
    x = f s
    go (f s)
  go s
```
>  The expression in red needs the abilities: {g67}
>  but was assumed to only require: {𝕖106, 𝕖107, X a64}
>  
>  This is likely a result of using an un-annotated function as an argument with concrete abilities. Try adding an annotation to the function definition whose body is red.

**Comment by aryairani** [comment]
A more concrete version:
```
ability X a where x : ()
ability Y where y : ()

f : '{g, X a} r -> '{g, X a} r
f s = s

foo : '{Y, X ()} () -> '{Y, X ()} ()
foo s = do
  go s =
    x = f s
    go x
  go s

-- if I substitute the definition of `x` for the usage of `x`, it no longer typechecks
foo' : '{Y, X ()} () -> '{Y, X ()} ()
foo' s = do
  go s =
    x = f s
    go (f s)
  go s
```

**Comment by pchiusano** [comment]
@aryairani did you mean to post your minimization on the other typechecking ticket? This ticket is about pattern match checking. 😀

**Comment by aryairani** [comment]
> @aryairani did you mean to post your minimization on the other typechecking ticket? This ticket is about pattern match checking. 😀

Hmmm! Sorry if I wrongly polluted the ticket. I think what happened is that when I started minimizing my pattern match issue which was producing the same error as yours, I was able to minimize away the pattern match altogether. (:

@dolio Should I open a separate ticket, or did they turn out to be related in some way?

**Comment by dolio** [comment]
This change isn't going to fix your example, because it's just about pushing type _checks_ against a specified type down into a match, so that you don't have to annotate every branch.

I wouldn't be surprised if your example is the same as some other issue we already have, but you can just make a new ticket if you want, and we can figure that out later.

**Comment by aryairani** [comment]
Bleh, I think mine in the overly simplified form just needed me to read the error message and do what it said, and I lost the original, so nevermind.
