### ISSUE TITLE
Ensure that `Codebase.makeSelfContained` / `makeSelfContained'` don't bomb if there's no name for a reference.

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#473]
It might be fine, this is just a reminder to investigate it.

**Comment by pchiusano** [comment]
Added a definition `blarg`, that depends on another, `woot`, then did `unname woot`, then did:

<img width="342" alt="Screen Shot 2019-04-29 at 2 19 03 PM" src="https://user-images.githubusercontent.com/11074/56917556-c7ffba80-6a89-11e9-937d-7d3f8ecfe8c9.png">

Also just from looking at the implementation of `makeSelfContained`, it uses `PrettyPrintEnv.termName` which will use the first 10 characters of the hash if no name can be found.

So I think we're good here.
