### ISSUE TITLE
Pattern match in ability handlers doesn't shadow constructor variables properly

### ISSUE THREAD

**Issue by andreystepanov** [unisonweb/unison#4746]
Here's a quick demo of the issue:

```unison
ability Issue t where
  one : '{Issue t} () -> {Issue t} ()
  two : '{Issue t} () -> {Issue t} ()
  three : '{Issue t} () -> {Issue t} ()

x : '{Issue t} () -> {Issue t} ()
x _ = ()

works x = x + 1

run : '{Issue t} () -> '{Stream Text} ()
run s = 
  go = cases
    { one x -> resume } -> 
      emit "one"
      handle resume !x with go
    { two x -> resume } -> 
      emit "two"
      handle resume !x with go
    { three x -> resume } -> 
      emit "three"
      handle resume !x with go
    { _ } -> emit "done"
  do handle !s with go
  
> Stream.toList! <| run do
  Issue.one do
    Issue.two do
      ()
    Issue.three do
      ()
```

If you inspect the result (`["one", "done"]`), it becomes obvious that handler just skipped `two x -> resume` and `three x -> resume` cases. At first i couldn't figure out what the reason was ([neither did Runar](https://discord.com/channels/862108724948500490/1213451735977431051/1213489030956847135)), but in that example i was using `coerceAbilities`, and thought maybe it has to do something with it.

As it turns out, the issue is the definition of `x : '{Issue t} () -> {Issue t} ()
x _ = ()` outside of the handler.

I was expecting `x` to be a bound variable from constructor pattern match (`{ two x -> resume }`), and not a globally defined function. Just like it behaves in `works x = x + 1` function above.

By renaming function `x` to `xx` the result of the execution would be as expected (no cases got skipped):

```unsion
["one", "two", "three", "done"]
```

**Comment by aryairani** [comment]
Thanks for writing up this report, it should definitely be a variable that shadows.

**Comment by pchiusano** [comment]
This is very surprising to me. Name resolution should absolutely avoid bound variables, and there’s logic for this (I thought). Is the bug specific to bound variables introduced by pattern matching, or can we also trigger with a variable introduced by other language constructs like lambdas?

We use ABTs for all binding structure so I would think this bug would appear for all types of bindings or not at all.

**Comment by pchiusano** [comment]
Yeah we are calling ABT.substInheritAnnotations which will definitely avoid touching bound variables.

https://github.com/unisonweb/unison/blob/trunk/unison-core/src/Unison/Term.hs#L178

So maybe this is a parser issue, it’s resolving some names eagerly in an unexpected way. I know it does that for pattern heads but don’t see how that would explain this.

**Comment by dolio** [comment]
Not a parser bug. Seems to be a variable capture bug during lambda lifting.

**Comment by dolio** [comment]
Okay, here's what's actually happening. When you write:

```unison
x = ...
foo = cases
  { eff x -> resume } ->
    handle resume !x with ...
  ...
```

The compiler wants to float out the 'compound' body of the `handle` block into its own definition. The first step is to enclose it into a lambda term like:

```
handle (resume x -> resume !x) resume x with ...
```

However, match blocks aren't handled by the encloser correctly, so it misses that `x` is a local variable, and instead produces:

```
handle (resume -> resume !x) resume with ...
```

Then this lambda expression gets floated out of the handle block, and you get:

```unison
x = ...
float resume = resume !x
foo = cases
  { eff x -> resume } ->
    handle float resume with ...
  ...
```

Shouldn't be too hard to fix.

**Comment by pchiusano** [comment]
nice!
