### ISSUE TITLE
In the UCM the view and edit commands show hashes instead of names for terms but the ui shows them correctly

### ISSUE THREAD

**Issue by petergabryanczyk** [unisonweb/unison#4750]
`determined-penguin/main> pull @unison/cloud-start/releases/latest

  Downloaded 14189 entities.

  ✅

  Successfully pulled into determined-penguin/main, which was empty.

determined-penguin/main> ls

  1. README       (Doc)
  2. ReleaseNotes (Doc)
  3. examples/    (81 terms, 6 types)
  4. lib/         (412235 terms, 10582 types)
  5. metadata/    (3 terms)
  6. patch        (patch)

determined-penguin/main> cd examples
determined-penguin/main examples> ls

  1. LICENSE       (#7k7de5eej4)
  2. LICENSE/      (1 term)
  3. chat/         (48 terms, 5 types)
  4. counter/      (4 terms)
  5. helloWorld/   (2 terms)
  6. messages/     (1 term)
  7. multiService/ (2 terms)
  8. todoApp/      (22 terms, 1 type)

determined-penguin/main examples> cd helloWorld
determined-penguin/main examples.helloWorld> ls

  1. deploy ('{##IO, #4n0fgs00hp} ())
  2. logic  (#t7s1lkpstc ->{#4n0fgs00hp, #ka0hfasvah} #o1f9g64v8e)

determined-penguin/main examples.helloWorld> view 1
determined-penguin/main examples.helloWorld> view deploy

  deploy : '{##IO, #4n0fgs00hp} ()
  deploy = #auldctc0n6 do
    name = #06h6cv2k70 "hello-world"
    serviceHash = #609t9ivreh !#9omr5rmlvq logic
    #86t298bgvn (#qhf6u0qaj1 name serviceHash)
    #le5947v6dm "Logs available at:\n  https://app.unison.cloud"`

<img width="1563" alt="image" src="https://github.com/unisonweb/unison/assets/134212974/498bfb8a-2029-44ad-8838-632bd06afc7f">

**Comment by petergabryanczyk** [comment]
<img width="1537" alt="image" src="https://github.com/unisonweb/unison/assets/134212974/9818d1a7-e1b3-4849-98a7-0d53486f4a62">

**Comment by piotrga** [comment]
examples/main examples.helloWorld> version

  release/0.5.18

**Comment by ceedubs** [comment]
@petergabryanczyk the `cd` command hasn't really caught up with the shift toward projects. It needs a bit of an overhaul, which will hopefully come soon. In the meantime, do you still see hashes if you stay in the root of the project instead of using `cd` to move to a subnamespace?

**Comment by piotrga** [comment]
Thank you @ceedubs ! It does work with the FQN :)
