### ISSUE TITLE
Unison language docs occasionally show hashes instead of terms

### ISSUE THREAD

**Issue by piotrga** [unisonweb/unison#4759]
![IMG_0143](https://github.com/unisonweb/unison/assets/129663/7fd86e29-ac4f-43f3-b46d-98dd745c3a43)

**Comment by ceedubs** [comment]
Heads up @rlmark for the doc fix. But there may be work to do on the ucm side to prevent this.

**Comment by rlmark** [comment]
Oh no! Perhaps the Doc hash issue is back! I will see if I can minimally reproduce this. I'll keep this ticket open for now and will link it to the bug ticket if that is indeed the case.

**Comment by ceedubs** [comment]
@rlmark when this happens so they show up as namespace dependencies? We might be able to set up a crown job that periodically checks for these.

**Comment by aryairani** [comment]
It looks like this is currently fixed: https://www.unison-lang.org/docs/language-reference/record-type/

<img width="605" alt="image" src="https://github.com/unisonweb/unison/assets/538571/e235dd88-c1b4-4d26-a2ae-40cb78ab3502">

It is still weird that `x` is prefixed and `y` isn't, but I don't have an easy fix for that.

I'll close the ticket for now, but feel free to reopen if it's not fixed for you.
