### ISSUE TITLE
https://www.unison-lang.org/docs/#installing-a-library-is-easy-just-pull is broken

### ISSUE THREAD

**Issue by piotrga** [unisonweb/unison#4764]
<img width="1070" alt="image" src="https://github.com/unisonweb/unison/assets/129663/9b68a641-a3f7-48a6-a068-a8583e9611ba">

**Comment by hojberg** [comment]
Hey @piotrga where was this linked from?

**Comment by piotrga** [comment]
From the wordle.

Peter

**Comment by hojberg** [comment]
cc @rlmark

**Comment by rlmark** [comment]
Thank you! I've added this as a ticket to the website repo and will close both once it gets updated.

**Comment by rlmark** [comment]
Thank you for reporting @piotrga, this has been deployed as of today!
