### ISSUE TITLE
Per-command help

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#480]
I type `help` at the Unison CLI and I see lots of goodness, about various commands like `ls` etc etc.

But I type `help ls` and it just says `"I don't know of that command. Try help."`

**Comment by pchiusano** [comment]
Try ‘help find’

It looks like the per command help doesn’t check for alias matches. That can be a separate ticket, or even better, a PR. 😀

**Comment by aryairani** [comment]
Wait, just change the title of this ticket to be that.

**Comment by pchiusano** [comment]
I generally prefer “create a separate ticket” and then link to it rather than mutating existing issues in place. In this case maybe doesn’t matter so much, since not much content, so whichever is fine.

**Comment by atacratic** [comment]
No problem, will make a new one!
