### ISSUE TITLE
Error message "I'm not sure what User "_200012" means"

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#481]
I saved a .u file containing an error.  The error message talks about `User "_200012"`, but I don't know who that is...
```
master> 
I'm not sure what User "_200012" means at line 4, columns 12-13

    4 | fac n = if n = 0 

Whatever it is, it has a type that conforms to Boolean.
```

@aryairani said:
> I’m guessing that’s related to the Show instance for the new Var type; to accidentally Show-ing it in the message even now that it contains metadata

In subsequent attempts it seems to have stopped mentioning `User`.

**Comment by aryairani** [comment]
@atacratic Can you still reproduce this or similar in `wip/branchless`?

**Comment by atacratic** [comment]
Nope!
