### ISSUE TITLE
TDNR failing to resolve == to Nat.==

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#482]
Typechecking:

```
f : Nat -> Nat
f n = if n == 0 then 1 else 0
```

gives me

```
I'm not sure what User "==" means at line 2, columns 12-14

    2 | f n = if n == 0 then 1 else 0

Whatever it is, it has a type that conforms to Nat ->{𝕖} Nat ->{𝕖} Boolean.
I found some terms in scope that have matching names and types. Maybe you meant one of these:

  - Universal.== : a -> a -> Boolean
  - Nat.== : Nat -> Nat -> Boolean
```

but is it meant to be able to resolve == to Nat.== using TDNR?

Not really sure if this is a bug or not.  I guess probably not in one sense because I think I remember reading that TDNR is looking for a unique match, and there are two here.

But `Nat.==` has a more specific type, so maybe it could choose that one?

Also I wonder if we realised this implication of adding `Universal.==` etc.

**Comment by pchiusano** [comment]
This is as designed. We don’t have any policy for picking a “more specific” type if there’s multiple possibilities. There are some languages (like Scala) that try to do this sort of thing, and I’m not a fan.

What we’ll do eventually is just make Universal.== the thing that is available in the default namespace, and the monomorphic versions can still be available but with some uglier name. (You can achieve this now just with a rename..)

**Comment by aryairani** [comment]
@pchiusano I started a Builtins2 with the name splitting refactor (it doesn’t have a ticket).
