### ISSUE TITLE
Polymorphic integer literals?

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#483]
Typechecking: 
```
fac : Int -> Int
fac n = use Int == 
        if n == 0 
        then 1
        else n * (fac (n - 1))
```

gives me

```
The 2nd argument to the function (Int.==) is Nat, but I was expecting Int:

    3 |         if n == 0 
```

(It wants me to put `+0` instead of just `0`.)

Will Unison one day be able to interpret a numeric literal as Nat/Int/Float selectively depending on context?

This is a bit of a nasty paper-cut for people trying things out, since many 'my first Unison programs' are going to involve integer handling.

I guess this issue might tie in to the whole 'what to do instead of typeclasses' thing.

**Comment by pchiusano** [comment]
Probably not for the near future. Maybe someday, after we figure out if we want something like typeclasses.

**Comment by aryairani** [comment]
@pchiusano What if we make Nat a subtype of Int? 😄 
I'm not sure what happens currently when parsing and out-of-range literal.

**Comment by aryairani** [comment]
Alternative: If a literal Nat is being checked against Int, have a special error message that suggests prepending `+`.

**Comment by pchiusano** [comment]
Going to close this for now, I think that the nice error reporting around `Int` / `Nat` mismatches is okay. When we have some better solution for bounded polymorphism, let's revisit. 

Making `Nat <: Int` seems like a can of worms to me, don't really want to go down that road.
