### ISSUE TITLE
Policy on bugfixes in builtins

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#4836]
Recently we had a bugfix to `Pattern.many` https://github.com/unisonweb/unison/pull/4790 which hasn't made it into any release yet. When it does, it will break older uses of the httpclient library which were accidentally reliant on the buggy behavior (this includes old versions of the cloud client). Newer versions will work fine with any version of UCM.

What should be the general policy for this sort of thing? Options:

a) Never change the behavior of a builtin, even for a bugfix. Instead, create a new builtin with the fix, release a new version of base with it, and let it percolate through the ecosystem. At a later time, the buggy version can be removed.
b) Change builtins for a bugfix, communicate to users that they should upgrade certain dependent libraries.
c) Delay releasing a bugfix until some time has passed and libraries have had a chance to upgrade.

Or it's case-by-case, depending on the impact.

**Comment by pchiusano** [comment]
Proposal: if we have evidence that people are reliant on the buggy behavior, use strategy a). 

Otherwise, use strategy c), with a waiting period of 1 month, giving some time for updates to percolate through the ecosystem, then b). Also do this if for some reason it's infeasible or very difficult to maintain two versions of the builtin.

If in our estimation there's no chance any reasonable program could be reliant on the buggy behavior, it's fine to jump straight to b).

**Comment by aryairani** [comment]
This `Pattern.many` situation was special because we had a "buggy" implementation in one runtime (with people relying on the behavior), and one "non-buggy" implementation in another runtime, so to accomplish (a), we would need to newly implement the buggy implementation in the new runtime.

**Comment by aryairani** [comment]
For (c), what does "upgrading" mean?

**Comment by pchiusano** [comment]
> For (c), what does "upgrading" mean?

In this case, it means that libraries and code transitively dependent on httpclient will have a chance to update to the new version of it.

**Comment by stew** [comment]
I think its less of an ask to say that users that want to try native have to use the latest libraries, but less of an ask that they not do a brew upgrade until they are sure they have upgraded all their libraries, so we could perhaps skip the buggy implementation in racket?

**Comment by pchiusano** [comment]
Okay, summarizing the decision:

We're going to do a) in this instance. If it's difficult for some reason to reproduce the old behavior on the JIT, then we're okay with having the JIT implement both builtins the same way (as the new version).

We'll do a new release of base with `Pattern.many` set to the new version.

After X months, support for the old builtin can be dropped from the runtimes and users will be forced to upgrade to a more recent base if they want to use a recent UCM version. Suggest X is 6 months.

This is annoying but doesn't break any existing code and lets people upgrade at their leisure to the non-buggy version.

Going forward, if in our estimation there's no chance any reasonable program could be reliant on the buggy behavior, it's fine to just modify the behavior of an existing builtin.
