### ISSUE TITLE
Niggle with bracket coloring in error message

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#484]
(sorry I haven't worked out how to actually put colours in this bug report - that would have made it easier to follow)

Typechecking: 
```
fac : Int -> Int
fac n = use Int == 
        if n == +0 
        then 1
        else n * (fac (n - 1))
```

gives me

```
I found a value of type Nat where I expected to find one of type Int:

    1 | fac : Int -> Int
    2 | fac n = use Int == 
    3 |         if n == -0 
    4 |         then 1
    5 |         else n * (fac (n - 1))

  from right here:

    4 |         then 1
```

with the code marked as lines 3/4/5 shown in blue.

But the last two parentheses on line 5 are *not* show in blue, despite being part of the faulty expression, so the blue highlighted portion has unbalanced parentheses.

Not the biggest deal in the world I know, but I thought I'd raise it anyway.

**Comment by francisdb** [comment]
you can paste a screenshot

**Comment by atacratic** [comment]
Oh yeah! :smile: 

![image](https://user-images.githubusercontent.com/21991324/57246325-ea1ead00-7034-11e9-99d9-920bb0ec61fd.png)

**Comment by pchiusano** [comment]
Thanks for this report. I think the issue is that the range for the `if` expression is just derived from the ranges for the leaves underneath. And the parenthesized expression doesn't include the parens in its range. Maybe the fix is as simple as having the parser make the range of a parenthesized expression  include the parens as well as whatever's inside the parens.

**Comment by jdevuyst** [comment]
I think the issue is that in `Unison.PrintError`, the expression is converted to `Pretty (AnnotatedText a)` (in `fromOverHere`) before the parentheses are added (in `renderType`).

Here's an updated code snippet to produce the error, by the way:
```
use .base Int

fac : Int -> Int
fac n = if n == +0
        then 1
        else n * (fac (n - 1))
```

**Comment by mitchellwrosen** [comment]
This appears to be fixed, but please re-open if it isn't.
