### ISSUE TITLE
Could do with better error messages for some lex failures around infix operators

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#485]
I tried a couple of programs trying to subtract integers, without doing `use Int -`.  They failed to pass the lexer - I thought maybe they should have been accepted.  

Typechecking: 
```
fac : Int -> Int
fac n = use Int == 
        if n == +0 
        then +1
        else n * (fac (n `Int.-` +1))
```

gives me

```
/home/chris/unison/u.u:5:31:
unexpected -
expecting [, bang, blank, case, false, handle, if, let, quote, symbol, true, or tuple
    5 |         else n * (fac (n `Int.-` +1))
```

And with `else n * (fac (Int.- n +1))` in the last line it gives me

```
/home/chris/unison/u.u:5:30:
unexpected n
expecting lambda
    5 |         else n * (fac (Int.- n +1))
```

Should these two attempts actually compile?

Note that with the following last line it *does* compile: `else n * (fac ((Int.-) n +1))`

I realise that the following is a more stylish way to do it (and this parses fine).

```
fac : Int -> Int
fac n = use Int == -
        if n == +0 
        then +1
        else n * (fac (n - +1))
```

**Comment by pchiusano** [comment]
That is as expected - the thing in backticks can’t be an operator, and if you’re calling a function prefix, and they function name is an operator, it needs parens around it, just like Haskell.

Could use a better error message!

**Comment by aryairani** [comment]
@atacratic It will parse if you just leave off the backticks, `n Int.- +1`. These are all random holdovers from Haskell :-/

**Comment by aryairani** [comment]
I'm going to close this for now; we don't have backticked infix identifiers anymore, so hopefully no one will think to try them. Feel free to reopen if you still find it to be a problem.
