### ISSUE TITLE
feature: ability to pass string parameters to transcripts

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#4855]
like what we can do with `envsubst` and templates, but without having to juggle the extra files

**Comment by ceedubs** [comment]
For anyone who comes across this, I've been using `envsubst` for this. [Example](https://github.com/unisonweb/base/blob/96d22dcdc93b59a8400aaf72ad9037c0354ae8eb/tests/run-tests.sh#L9)

**Comment by aryairani** [comment]
Yeah! I saw that in the Dockerfile and it's my backup plan, but I wanted to avoid juggling the extra files.

**Comment by aryairani** [comment]
Well, in an effort to reduce the number of open tickets, I'm just going with Cody's suggestion.
