### ISSUE TITLE
transcript "Processing stanza Nothing of <nn>"

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#4858]
<img width="372" alt="image" src="https://github.com/unisonweb/unison/assets/538571/cec97821-9fed-4bfc-a7ee-cf2f27009e57">

Weird

**Comment by aryairani** [comment]
Oh I guess it has to do with `:hide` stanzas? maybe?

**Comment by sellout** [comment]
It actually had to do with `unison:added-by-ucm` stanzas, and was fixed in #5290.
