### ISSUE TITLE
Typo assist in error messages

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#486]
If I mistype a name, say `Goo`, it would be great if the error message I see included something like `did you mean 'Foo'?`

(I mistyped something where my error was solely in capitalization, which made me think of this.)

I don't think we have this already?  Not completely sure.

**Comment by pchiusano** [comment]
Totally open to doing this in M1 if someone wanted to dive in..

**Comment by pchiusano** [comment]
Going to close this one in favor of #713 which has some more examples.
