### ISSUE TITLE
Multi-line watch expressions

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#487]
I tried 
```
test> use Int ==
      if (fac +4) == +24 then Test.Result.Ok "ok" else Test.Result.Fail "sad"
```

and got 

```
/home/chris/unison/u.u:9:7:
unexpected use
expecting and, binding, infixApp, lambda, or or
    9 | test> use Int ==
```

Should watch expressions parse as a block so `use` works?

**Comment by pchiusano** [comment]
Yeah, that should work I’d say. Might be a small change in FileParser.

**Comment by pchiusano** [comment]
Specifically, unnamed watch expressions.

**Comment by pchiusano** [comment]
This works fine - 

<img width="196" alt="image" src="https://user-images.githubusercontent.com/11074/179538679-e5df703b-f3e7-4440-9b94-3bf547df3df2.png">
