### ISSUE TITLE
`merge.preview` shows hashes even if the definitions have names

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#4873]
I'm guessing it just needs a pretty-print environment which includes the source and/or the target location as a fallback.

https://discord.com/channels/862108724948500490/1225906912877609010/1226229059164573716

**Comment by aryairani** [comment]
I'm just going to close this, because `merge.preview` needs to be completely overhauled after "new `merge`" and "per-branch namespace roots".
