### ISSUE TITLE
Possible unimplemented functions in JIT's TCP

### ISSUE THREAD

**Issue by kylegoetz** [unisonweb/unison#4877]
Unison TCP `base.IO.net.Socket.toText : Socket -> Text` exists in Unison Share as a built-in, but the JIT's `tcp.rkt` does not appear to implement this.

**Comment by aryairani** [comment]
I think it's here; https://github.com/unisonweb/unison/blob/trunk/scheme-libs/racket/unison/primops.ss#L972-L973 @dolio would you confirm?

**Comment by dolio** [comment]
Yeah, that's the primitive part. Based on that there should also be an auto-generated wrapper in one of the wrapper files.

Was there more indication that it's not working somehow?

**Comment by kylegoetz** [comment]
@dolio no indication it's not working. I was just learning by reading the TCP code and noticed I hadn't seen it in the tcp.rkt file. And you're right, it's in simple-wrappers. I had mistakenly assumed the wrong location for the function.
