### ISSUE TITLE
(possibly) LSP missing type names from scratch file?

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#4893]
<img width="650" alt="image" src="https://github.com/unisonweb/unison/assets/538571/4c31497d-d73f-44e1-b39f-a303d1b0b7d0">
vs
<img width="492" alt="image" src="https://github.com/unisonweb/unison/assets/538571/0e34123a-6b64-4fc3-a5e1-92124eb73fce">

where `ElectoralJurisdictions` is a unique type in the scratch file (only).

**Comment by aryairani** [comment]
https://gist.github.com/aryairani/bce4bc6c21b47bf87840421dcb28b8cd
https://share.unison-lang.org/@aryairani/evcount/code/@aryairani/unison4893

**Comment by aryairani** [comment]
Seems to apply to recently added terms too?
<img width="559" alt="image" src="https://github.com/unisonweb/unison/assets/538571/8327a415-b3e2-4478-b09d-ae757a8119ff">

after that term being added from the previous scratch file

**Comment by ceedubs** [comment]
Is this a duplicate of https://github.com/unisonweb/unison/issues/4460 ?

**Comment by aryairani** [comment]
@ceedubs Seems like it.
