### ISSUE TITLE
`view <name>` should emit a message if <name> is not found

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#490]
I type `view foo`, where `foo` is a name that does not exist in the codebase, and I just see

```
master> view foo

  

```
There should be an explanatory message.

**Comment by pchiusano** [comment]
fixed in wip/branchless

<img width="924" alt="Screen Shot 2019-06-27 at 12 42 05 AM" src="https://user-images.githubusercontent.com/11074/60235038-6931a400-9874-11e9-85f1-a5a44773bfe0.png">
