### ISSUE TITLE
Pure Unison testing library

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#495]
Background: #444 (design) and #477 (implementation)

We now have a basic framework for running and caching tests, but are missing a convenient, pure Unison way of constructing test values.

@runarorama is currently on this!

**Comment by francisdb** [comment]
Is there some documentation on this?

**Comment by pchiusano** [comment]
@francisdb #477 is closest thing to docs at the moment.

I think @runarorama is going to look at [EasyTest](https://github.com/unisonweb/unison/tree/master/yaks/easytest) for inspiration for this ticket, but it will probably work out differently than Haskell.

If you have suggestions or ideas, feel free to leave comments here!
