### ISSUE TITLE
`names arg` should list all the names for hash-qualified `arg`

### ISSUE THREAD

**Issue by sullyj3** [unisonweb/unison#497]

**Comment by aryairani** [comment]
It's worth noting that all names (aliases) for a definition are equal, none is less aliasey than the others.  So `alias` with no args couldn't do anything, as aliases aren't a real thing.  You could have a command, `aliases foo` that lists additional names for `foo`.

Would you describe your use case a bit?

Thanks!

**Comment by sullyj3** [comment]
Right, of course. Yeah, I think that would make more sense.

**Comment by aryairani** [comment]
Maybe this is a good reason to use a single nomenclature for names/aliases.

Anyway, `view -l <name>` will list all the names for that exact definition.

**Comment by pchiusano** [comment]
- [ ] add an `Input` for this command (to `Input.hs`)
- [ ] need an `Output`
- [ ] add syntax for it in `InputPatterns.hs`
- [ ] add a case in `HandleInput.hs`
- [ ] add a case in `OutputMessages.hs`

**Comment by pchiusano** [comment]
<img width="923" alt="Screen Shot 2019-07-01 at 3 53 56 PM" src="https://user-images.githubusercontent.com/11074/60462867-781faa00-9c18-11e9-9ea0-4d8df5e7a28a.png">

This is fixed. When showing names, it tries to use local names (relative to the current path) if those exist, but also shows absolute names when they refer to different paths in the tree.
