### ISSUE TITLE
merge precondition message: Term or type in `lib`

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#4985]
### Term or type in `lib`

By convention, `lib` can only namespaces; each of these represents a library dependencies. Individual terms and types are not allowed at the top level of `lib`.

Alice's branch:
```unison
lib.foo : Nat
lib.foo = 1
```

Bob's branch:
```unison
bob : Nat
bob = 100
```

```ucm
project/alice> merge /bob

  On project/alice, there's a type or term directly in the `lib`
  namespace, but I expected only library dependencies to be in
  there. Please remove it before merging.

```
---
> Sorry, I wasn't able to perform the merge:
> 
> On`project/alice`, there's type or term at the top level of the `lib` namespace, where I only expect to find subnamespaces representing library dependencies.
>
> Please move or remove it and then try merging again.

**Comment by aryairani** [comment]
I think this was done in #5032 also

**Comment by mitchellwrosen** [comment]
Yeah, it was, I missed tagging it
