### ISSUE TITLE
sort out loose code migration plan

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#4994]
If Share loose code gets migrated to a project first, you can pull out a subnamespace with
```
.> clone @arya/legacy_code
@arya/legacy_code> project.create-empty my-real-project
my-real-project/main> fork @arya/legacy_code:subproject1 :
```

If not, then we could update `clone` to allow
```
clone arya.subproject1 my-real-project
```
or update `pull` to allow
```
pull arya.subproject1 my-real-project/main
```

**Comment by aryairani** [comment]
If share loose code gets migrated to a project, it should happen no sooner than #4439, which is connected to #4441, which is in progress.

**Comment by aryairani** [comment]
Some related discussion:
https://discord.com/channels/862108724948500490/1238180855571021924
https://unisoncomputing.slack.com/archives/C03HW54CYP4/p1716217466697409
https://unisoncomputing.slack.com/archives/C039BETNDMF/p1716221859634149

**Comment by mitchellwrosen** [comment]
@aryairani FYI I believe pull does support this form:

> pull arya.subproject1 my-real-project/main

**Comment by aryairani** [comment]
Okay, yes I confirmed this succeeded:
```
.> project.create-empty test-pull-migrate
test-pull-migrate/main> pull chrispenner.public.turtle

  Downloaded 9166 entities.


  ✅
  
  Successfully pulled into test-pull-migrate/main, which was empty.

test-pull-migrate/main> 
```
