### ISSUE TITLE
LSP completion details don't use the best fully-qualified name for a definition

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#5007]
In this example LSP does a great job of knowing that `List.map` is enough qualification to get what I want. But in the details just under the type signature the fully-qualified name that it shows is not the best one.

![image](https://github.com/unisonweb/unison/assets/977929/a38ce6ab-626b-41ee-932a-3ef245437226)

Here are the available names:

```
@cloud/nimbus/main> names List.maximum
 
  Term
  Hash:   #7cg6khq0ve
  Names:  lib.ansi_1_0_0.lib.base_2_9_1.data.List.maximum
          lib.aws_4_0_3.lib.http_2_2_2.lib.base_2_12_0.data.List.maximum
          lib.aws_4_0_3.lib.ini_1_0_1.lib.base_2_8_0.data.List.maximum
          lib.aws_4_0_3.lib.json_1_0_0.lib.base.data.List.maximum
          lib.aws_4_0_3.lib.json_1_0_0.lib.json.lib.base.data.List.maximum
          lib.base_2_18_0.data.List.maximum
          lib.cloud_15_0_0.lib.base_3_4_1.data.List.maximum
          lib.cloud_15_0_0.lib.codec_1_8_0.lib.base_3_2_0.data.List.maximum
          lib.cloud_15_0_0.lib.orderator_0_7_1.lib.base_2_17_0.data.List.maximum
          lib.cloud_15_0_0.lib.rollingHash_0_1_0.lib.base_2_14_2.data.List.maximum
          lib.json_1_2_1.lib.base_2_10_0.data.List.maximum
          lib.metrics_2_0_1.lib.httpserver_3_0_2.lib.httpclient_4_1_2.lib.websocket_1_0_0.lib.base.data.List.maximum
```

LSP shows `lib.aws_4_0_3.lib.json_1_0_0.lib.json.lib.base.data.List.maximum` but `lib.base_2_18_0.data.List.maximum` seems like a strictly better FQN to me: shorter and fewer `lib` segments.

I'm not sure of whether this issue is specific to the LSP support or is coming from some more general "give me a FQN" functionality in ucm.

**Comment by aryairani** [comment]
This seems to be fixed now

<img width="543" alt="image" src="https://github.com/user-attachments/assets/139855d6-ce03-4b05-8ae4-fceff3b77fb2" />

This is with

```
lib.install @runarorama/terminus
lib.install @unison/aws
lib.install @unison/base
lib.install @unison/cloud
lib.install @unison/json
lib.install @stew/metrics
```

Or else send over a repro?

**Comment by ceedubs** [comment]
I don't think that @aryairani's screenshot really captures it, because the issue was in the details section and not in the name selection; but I do think that this issue is resolved. I think that there have been some changes to where transitive dependency definition names show up, which is probably why this is better than it was.

![image](https://github.com/user-attachments/assets/c4e2b849-9d68-4a55-bb7d-ebc1a12de0e6)

**Comment by aryairani** [comment]
Oops, sorry.

<img width="883" alt="image" src="https://github.com/user-attachments/assets/6aa9cf56-cdf5-41e7-8a2c-429b50e6ac95" />
<img width="929" alt="image" src="https://github.com/user-attachments/assets/6ce4ba1b-b730-42a3-9ad9-5f1b6084a04b" />
