### ISSUE TITLE
load and save Unison branches on Github

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#501]
Work should be done on wip/branchless branch.

In Editor2.hs, we need these two functions:

```haskell
-- for example: loadGithubRootBranch "unisonweb" "unison" "master"
-- loadGithubRootBranch "unisonweb" "unison" "7637859b90ce"
loadGithubRootBranch :: MonadIO m => Text -> Text -> Text -> m (Branch m)
loadGithubRootBranch user repo treeish = error "todo"

syncGithubRootBranch :: MonadIO m => Text -> Text -> Text -> Branch m -> m ()
syncGithubRootBranch user repo ghbranch b = error "todo"
```

Or whatever; maybe you have to just use IO, idk.  If the functions do something that can authenticate with github using my `~/.ssh/` keys, like the `git` executable magically does, that would be ideal.  Otherwise they'll probably need more args.

Although `treeish` can be a git commit id, the user can just supply the prefix (4-6 characters is typical).  We shouldn't need to write any special code to filter by prefix or whatever, the git library should handle it.  (The github web api does handle it.)

`treeish` can be a tag, branch name, or commit id. That's fine for reading, but to do a git commit, we have to use a branch name, not either of the other two.

Paul says: if using some git library, make sure it's compatible with MIT license and doesn't like require that we make Unison GPL, say.

It might be possible to implement these hackily just by calling out to external git executable. That might be kludgy or maybe it's the simplest way? Just another option to consider.

Would prefer not to have to use GitHub specific API for actually doing the fetching and committing, using the native Git protocol seems better (unless that's much more complicated).

**Comment by aryairani** [comment]
I don't think we have to worry about whatever may already exist on a git branch that we're pushing to; I think we can lay out the whole catalog based on the `Branch m` (including its history and their children, and the terms and types and metadata (??) that they reference) and that can be the entirety of the new commit.  I think the git branch will only ever add files, apart from fluctuating root heads.

**Comment by runarorama** [comment]
We're calling out to `git` to push branches to Github, and you can pull them too. Needs some exercising to shake out all the kinks.
