### ISSUE TITLE
fork can create unnamed dependencies

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#5044]
It seems that the `fork` command doesn't check whether copying a namespace will result in unnamed dependencies in the current project.

A specific example that I ran into is when running `fork /my-branch-1:JobContext.UserHandle JobContext.UserHandle`. It copied over the `JobContext.UserHandle` namespace but not the `JobContext.UserHandle` type. So now all of the references to the `UserHandle` type show up in `namespace.dependencies`.

There's also a question of whether `fork` should just copy over the type that matches the name of forked namespace.

**Comment by aryairani** [comment]
@ceedubs Any suggestions? Or what's the bug exactly?

**Comment by ceedubs** [comment]
@aryairani at a minimum I think that `fork` should issue a warning if the result adds items to `namespace.dependencies`.
