### ISSUE TITLE
`todo` builtin for tracking expressions that need filling in

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#507]
Very often when programming, it's convenient to stub out a function, then come back to filling in the implementation later. Idea, what if you could type:

```Haskell
frobnicate : Nat -> Nat
frobnicate = todo
```

`todo` is a regular term of type `forall a . a`. You can typecheck a program just fine if it uses `todo`. The `todo` command tells you about all the places you've used `todo` in the current branch, so you can fill these in (just a normal `update` of `frobnicate` will do the trick).

If you try to anything that transitively references `todo`, you get a warning that your program and if you really want to run it anyway, add an extra flag or retype the command.

The nice thing is that your todos are tracked quite explicitly in the code, rather than you just (hopefully) remembering to do a search for all your todos. Also, the `todo` is a regular term, so we aren't like relying on some hacky regex search to identify these places in the code.

Other ideas:

* Maybe it's `todo : forall a . Text -> a`, so you say `todo "fill in frobnicate using the wrangle function"` and this note to yourself is printed by the `todo` command.
* If it takes an argument, maybe it's just builtin syntax, since wth does it mean if it's partially applied?

**Comment by atacratic** [comment]
Sounds good!

- What actually happens when you run a program containing todo? Does it just return an error or does it do maximal evaluation around the todo and return the resulting expression?

- Is there a similar `error : Text -> a` like in Haskell? To signify a hopefully unhittable branch, rather than a work in progress.

- Are people banned from editing/replacing `todo`? I guess that question could go for any builtin.

**Comment by pchiusano** [comment]
> What actually happens when you run a program containing todo? Does it just return an error or does it do maximal evaluation around the todo and return the resulting expression?

For v1 of this feature, just return an error, I'd say. The other thing sounds very cool, but more of a science project.

> Is there a similar error : Text -> a like in Haskell? To signify a hopefully unhittable branch, rather than a work in progress.

Yeah, there should be. Elm calls it `crash`.

> Are people banned from editing/replacing todo? I guess that question could go for any builtin.

If `todo` is a builtin function, you could edit it. Same goes for any builtin - editing builtins is allowed. You're just introducing a new definition and moving the name to point to that new definition.

But I don't know if `todo` should be a function if it takes any arguments (like a text description), since what does it mean if those arguments aren't literal text?

**Comment by atacratic** [comment]
Sounds good 😊

- Is there anything to help me if my to-do is in a comment? Maybe if I do `todo` in backticks then it will work?

**Comment by aryairani** [comment]
Between `todo` and `dependents`, I think we have this now.
