### ISSUE TITLE
No way to delete a patch?

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#5084]
**Describe and demonstrate the bug**

Right now if I do `ls up` then I see a patch entry. But the `delete.patch` command seems to have gone away, so I don't know how to delete the patch entry. Similarly I can't view it. How do I get rid of this?

**Comment by mitchellwrosen** [comment]
Indeed; I think the right fix here is to continue ripping out patches. Hide them from `ls` output, etc. Then, some day we can migrate patches out of everyones' namespaces, if we want to.

**Comment by aryairani** [comment]
Agreed, let's hide it from `ls` output.
