### ISSUE TITLE
OOM crashes

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#5085]
**Describe and demonstrate the bug**

I don't know a simple way to reproduce this. But for the last couple of hours I have doing a lot of the following commands on the nimbus codebase while searching for unused code and code that has been upstreamed to libraries:

- `ls`
- `dependents`
- `delete.term`
- `delete.namespace`
- `view`

Often I'm calling these with numbered args from `ls` and `dependents` output.

2 or 3 times my computer has frozen and my fans have gone full throttle (presumably from CPU usage). One time I gave up and did a hard power reset of my computer and the other time my OS had killed my tmux process when I returned to my computer ~10 min later.

I'm guessing that there is a memory leak and that I could get this to fail more gracefully by setting a max memory limit on the Haskell runtime. But ideally this wouldn't be necessary.

**Environment (please complete the following information):**
 - `ucm --version` 335512e331339cd496db97b6d3bead1efc090f42 (via `nix run`)
 - OS/Architecture: x86 NixOS

**Comment by aryairani** [comment]
Let's reevaluate this after #5041, though it shouldn't be leaking per se.

In Haskell can we detect memory pressure and reduce our cache sizes?

**Comment by ceedubs** [comment]
I have not experienced this at all since #5041. I'm going to close this out and can reopen if it happens again.
