### ISSUE TITLE
update `todo`

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#5088]
The updated command should
* list name conflicts
* list missing dependency names
  * bonus: provide hints if they are named in other project branches
* list violated merge preconditions
* list dependents of `todo`

**Comment by mitchellwrosen** [comment]
What's "list dependents of `todo`" – typo?

**Comment by hojberg** [comment]
@mitchellwrosen I think that refers to dependents of https://share.unison-lang.org/@unison/base/code/releases/3.7.0/latest/terms/todo

**Comment by mitchellwrosen** [comment]
Ah, yes, of course

**Comment by aryairani** [comment]
Re:
> * bonus: provide hints if they are named in other project branches

Not sure what we can reasonably accomplish here, but this is the motivation:

<img width="446" alt="image" src="https://github.com/unisonweb/unison/assets/538571/cf0a0a4a-af5f-4879-9733-73953e8f20e0">

**Comment by aryairani** [comment]
Also, in the previous screenshot... what is `ucm` doing? It seems like if `#dc5` appears in the list, that `#t7r` should too. But where's the dependent of `#dc5`? I guess I can use `dependents` to find out, but it would be better if `todo` told me why things were in the list.

<img width="605" alt="image" src="https://github.com/unisonweb/unison/assets/538571/95d0aa35-276d-4bc3-8543-e7ac8d44827c">

**Comment by mitchellwrosen** [comment]
@aryairani It's currently just showing the unnamed things that are directly – not indirectly – referenced by your code

**Comment by aryairani** [comment]
> @aryairani It's currently just showing the unnamed things that are directly – not indirectly – referenced by your code

Right, ok. We should consider at some point what other hints we could try to provide that would be helpful in choosing a name for it.  Maybe that's dependent names, maybe it's names from other projects or Share, maybe it's something else.

And maybe transitive unnamed deps of from the direct unnamed deps, so that you're not getting one entry per time you `todo`
