### ISSUE TITLE
Subtyping judgement should not assume covariance for type application

### ISSUE THREAD

**Issue by atennapel** [unisonweb/unison#512]
Reading through the typechecking code I noticed there is no unification used for type applications. The following rule is used for subtyping type applications:
```
t1 <: t3
t2 <: t4
----------------
t1 t2 <: t3 t4
```

However, what if the `t1` and `t3` is the following type (in Haskell):
```haskell
data Contra t = t -> ()
```

Now subtyping should be contravariant and not covariant:
```
b <: a
---------------------------
Contra a <: Contra b
```

In general you might not know the variance of the type parameters of some datatype so you'd have to fall back on unification:
```
t1 ~ t3
t2 ~ t4
---------------
t1 t2 <: t3 t4
```

Of course for function types we know the variance so we can use a special rule just for that:
```
t3 <: t1
t2 <: t4
---------------------------
(->) t1 t2 <: (->) t3 t4
```

Am I misreading the code or is this an oversight? I'm still thinking myself on how to combine subtyping and unification in "Complete and easy..." without duplicating code.

**Comment by pchiusano** [comment]
Thanks for this. I think it’s an oversight. Seems like the right thing to do is to track the variance of all data type parameters, then just make use of that in the subtyping judgement for type application. 

Offhand I’m not sure you’d ever not know the variance, seems like it could be statically computed from the data declaration?

To get type equality, you can just do a subtype check in both directions. We could do this as a quick fix in the type application case. It’s just more restrictive than necessary if the data type isn’t invariant in that type parameter.

**Comment by atennapel** [comment]
Aah doing subtyping in both directions will work yes, didn't think of that (although it does sound very inefficient).

I also can't think of any issues with variance inference, but I asked Phil Freeman (of Purescript) once and he replied:
"in the PureScript compiler, the function type constructor is just another type constructor, and there is a special case for it in the subsumption rule. Type application in general doesn't have a subsumption rule, and we fall back on unification, since we don't know the variance on the type on the left of the application in general."
and
"Q:Thanks, have you ever felt the limitations of falling back to unification for type applications in Purescript? For some datatypes you could do some kind of variance inference, but I'm not sure if it's worth the trouble.
A:I'm not sure it's worth it to be honest. Once you get into subsumption involving type class constraints, you're going to need to elaborate to dictionary passing style, and it's not obvious (to me anyway) how that would work with type applications."

**Comment by TomasMikula** [comment]
I haven't studied the code, but from @atennapel's description I do not see the problem.

If `t1` (or `t3`) is `Contra t`, then `t1 t2` (or `t3 t4`) doesn't typecheck because `Contra t` is not a function type.

If `t1` is `u1 -> ()` and `t3` is `u3 -> ()`, then `t1 <: t3` only if `u3 <: u1`. So

```
        u3 <: u1
------------------------
 u1 -> ()  <:  u3 -> ()
------------------------
       t1 <: t3                t2 <: t4
----------------------------------------
               t1 t2 <: t3 t4
```

**Comment by atennapel** [comment]
If you expand all type constructors before subtyping it might work (if you have the special rule for function types)?

Also I am thinking, in the presence of HKTs the variance of a type might depend on the variance of the type parameters. It might be a lot of work to get it right.

**Comment by pchiusano** [comment]
Here's an example - 

```
Contra (forall a . a -> a) <: Contra (Nat -> Nat)
```

We don't want this to hold, even though it's true that `forall a . a -> a` is a subtype of `Nat -> Nat` (any function expecting a `Nat -> Nat` could be given a `forall a . a -> a`). It should be flipped around, `Contra (Nat -> Nat) <: Contra (forall a . a -> a)`.

@atennapel that's an interesting data point that PureScript doesn't bother with tracking variance, thanks for that. I suspect that if you are careful about where you generalize over existentials, it works out okay in many cases. If you're doing a lot of rank N stuff, then not having the variance accurate seems like it would be painful. But I guess that's a lot less common.
 
@paf31 if you end up here I'd love to hear if you have more color. Might be fun to compare notes sometime, too. :)

**Comment by pchiusano** [comment]
Note on implementation idea - no need to modify the AST for data declarations. If we decided to compute variance it could just be done locally in the typechecker, just a surgical edit to that one file. Typechecker already has access to the full AST for the declarations relevant to the current typechecking, which is enough info to at least produce a conservative determination of variance for each data type parameter. This could be computed once in a pass up front, and then used throughout typechecking.

**Comment by atennapel** [comment]
I think in practice you probably won't end up with types like `Contra (forall a . a -> a)` though, since you don't have impredicative instantiation anyway. If you do have that, in [HMF](https://www.microsoft.com/en-us/research/publication/hmf-simple-type-inference-for-first-class-polymorphism/) and ["Guarded Impredicate Polymorphism"](https://www.microsoft.com/en-us/research/uploads/prod/2017/07/impredicative-pldi18.pdf) they have everything being invariant, so deep subsumption is not used anyway.

**Comment by pchiusano** [comment]
I'm going to put this in M1, I think we should at least do the quick thing of using equality for type application. What we have now isn't sound.

Using variance could be something we consider for later, but it would be more work.

**Comment by pchiusano** [comment]
and @atennapel thanks again for flagging! Cheers. 😀

**Comment by TomasMikula** [comment]
What about subtyping being only an auxiliary notion for the purposes of type inference. All subtyping would have to be translated to type application. Then, even the otherwise correct `Contra (Nat -> Nat) <: Contra (forall a . a -> a)` would not hold, because `Contra (Nat -> Nat)` cannot be applied to a type to get `Contra (forall a . a -> a)`.

**Comment by pchiusano** [comment]
@TomasMikula not sure if I follow, but the subtyping judgement is a big part of the type system that's described by [the paper Unison's system is based on](https://www.cl.cam.ac.uk/~nk480/bidir.pdf) (see Figure 9) and it gets used in a number of places in the overall typechecking.

**Comment by TomasMikula** [comment]
Sorry, I was sloppy in my phrasing. By _"subtyping being only an auxiliary notion for the purposes of type inference"_ I meant that in typechecked programs, there would be no subtyping. For example, if `f : A -> B`, `A0 ≨: A`, `a0 : A0`, you could not have `f a0` in a typechecked program, because `f` can only be applied to values of type `A`. However, you could write `f a0` in a source file and have type inference transform the subtyping `A0 <: A` into a transformation `upcast : A0 -> A` and the typechecked program would be `f (upcast a0)`. I also said that such inferred upcasts would be restricted to type applications, i.e. of the form `upcast a0 = a0 @Foo`, but maybe that would be too restrictive.

**Comment by atennapel** [comment]
I was thinking a little and I think with "Complete and easy..." it's actually impossible to get `Contra (forall a . a -> a)`, even with a type annotation. Only abstractions can be given a higher-ranked type, even `id : (forall t. t -> t) -> (forall t. t -> t)` won't work. You'd need something like Visible Type Application to allow that. Visible Type Application of the form `(id : forall t. t -> t @ forall t. t -> t)` is easy (and sound) to add though.

Also, I found this paper: [Formalization of a Polymorphic Subtyping Algorithm](https://people.cs.kuleuven.be/~tom.schrijvers/portfolio/itp2018.html). It gives a simpler subtyping algorithm that can work with the "Complete and easy..." system. (I have a little JS implementation here: https://github.com/atennapel/bidirectional.js/blob/master/simpler.hkt.js)
