### ISSUE TITLE
hide patches from ls output

### ISSUE THREAD

**Issue by mitchellwrosen** [unisonweb/unison#5122]

**Comment by ceedubs** [comment]
Related: #5084

**Comment by aryairani** [comment]
closed by #5123

**Comment by hojberg** [comment]
@mitchellwrosen @ChrisPenner @aryairani does this also remove patches from the codebase server that the local ui relies on (and what about patches on share?)

**Comment by aryairani** [comment]
@hojberg This only affects what's printed on the screen by the `ls` command, it doesn't change or remove anything under the hood.

**Comment by aryairani** [comment]
@hojberg Wait, now I'm not sure.

@mitchellwrosen can you confirm whether the change to [`Backend.hs`](https://github.com/unisonweb/unison/pull/5123/files#diff-b4cb027e1d2557425c55d5b4c43fb157f0bce0060f769d9a62ed308f7c33a243) affects the local server or Share server (cc @ChrisPenner)

**Comment by hojberg** [comment]
To be clear: it'd be great if patches didn't show in those places :)

**Comment by aryairani** [comment]
@hojberg Thanks, that is more clear.

**Comment by mitchellwrosen** [comment]
@aryairani as far as I can tell this `lsAtPath` function in the "backend" module is only called from the command-line `ls` handler (so should probably just be moved there)

**Comment by aryairani** [comment]
@mitchellwrosen Thanks — 
So @hojberg probably no impact to Share or Local
