### ISSUE TITLE
todo is silent if there is nothing to do

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#5145]
**What's the message you're seeing?**

The null message

```
@ceedubs/scratch/main> todo
@ceedubs/scratch/main>
```

**What would a better version look like?**
```
@ceedubs/scratch/main> todo

You have no pending todo items. Good work! ✅

@ceedubs/scratch/main>
```

Environment (please complete the following information):

* `ucm --version` 8292786e0

**Comment by hojberg** [comment]
> You have no pending todo items. Good work! ✅

Love the positive vibes of this!
