### ISSUE TITLE
`use A.x` has no effect but silently succeeds

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#516]
Suppose I mean to write
```
use A x
```
but I accidentally write
```
use A.x
```
then I get no error message, even though the `use` statement has no effect.  When I try and reference `A.x` as just `x` I will get an error, and I won't understand it because I can't see any problem with my `use` statement.

`use` statements with an empty list of names to `use` should cause a parse error.

**Comment by pchiusano** [comment]
This has been a parse error for a little while, but I just added a nicer message for it, this is in wip/branchless, which will be getting merged to master Real Soon Now:

<img width="618" alt="Screen Shot 2019-07-14 at 1 07 51 PM" src="https://user-images.githubusercontent.com/11074/61186884-92a24c00-a638-11e9-949d-21f188b68980.png">
