### ISSUE TITLE
Surplus parentheses when if/then/else, handle/in and case/of nested under each other

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#517]
The pretty-printer sometimes emits code with ugly and unnecessary parentheses, for example:
```
handle bar in
  (if foo then
    use A.X c
    f c c
  else
    use A.Y c
    g c c)
```
As per the comment 'Explanation of precedence handling' above `pretty` in TermPrinter.hs, if/then/else, handle/in, and case/of all use the same precedence level.

But the pretty-printer emits newlines and whitespace in such a way that the parser can pick up the right parenthesization based on layout.

Ideally the pretty-printer would use this fact to suppress some brackets.

**Comment by atacratic** [comment]
The fix in #587 removes parentheses around the contents of `if` branches, but doesn't handle all the cases in this ticket.  For example, I've tested that we still get

```
handle bar
in
  (if foo then a
  else b)
```

**Comment by aryairani** [comment]
@atacratic do you know if this is still relevant?

**Comment by atacratic** [comment]
Here's another example with today's ucm:

```
t : Boolean -> Nat -> Nat -> x -> x
t a b c x = match (if a then b else c) with _ -> x
```
The parens are superfluous.

Maybe at some point we'll want to revisit how nested blocks are pretty-printed.

But I think let's close this ticket til then.
