### ISSUE TITLE
Missing line-break before `then` after multi-line `if` condition

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#518]
The pretty-printer emits the following code:
```
if
  use A x
  f x x then
  x
else y
```
Note the missing line-break before `then`.  

The problem will be something to do with the height checks in the `If'` branch of `pretty` in TermPrinter.hs.

**Comment by pchiusano** [comment]
Is this issue still open @atacratic ? If not can you close?

**Comment by atacratic** [comment]
The original example above is no longer valid since we won't put a `use` if an if condition any more, but the problem still exists, search for "#518" in https://github.com/unisonweb/unison/blob/master/parser-typechecker/tests/Unison/Test/TermPrinter.hs 

for example:
``` haskell 
if
  a = b
  a then foo else bar
```

So leaving open til I/someone get to it.

**Comment by pchiusano** [comment]
Just confirmed this is still a problem.
