### ISSUE TITLE
Wrong reference being selected during parse/typecheck in the presence of namespace and qualified names

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#519]
Suppose we have
```
namespace D where
  ff = 6
  D.ff = 7 
  gg = ff + ff -- I think this should be using the one with value 6, not 7
```
and then we view `D.gg`:
```
  D.gg : Nat
  D.gg =
    use D.D ff
    use Nat +
    ff + ff
```
This is using the wrong `ff` - it's using `D.D.ff` when it should be using `D.ff`.

Despite the issue title I haven't actually checked that the use of `namespace` is necessary to trigger this bug.

**Comment by pchiusano** [comment]
Closing until we bring back namespace blocks.
