### ISSUE TITLE
Editor eval feature

### ISSUE THREAD

**Issue by tomtau** [unisonweb/unison#52]
Currently, it is not possible to evaluate expressions in the editor.
This issue is opened to keep track of if someone is working on it.

@pchiusano mentioned on [gitter](https://gitter.im/unisonweb/unison?at=570ff5beaf46361038649d73) that it should be easy to implement and that he had a few other features for the editor in mind -- I suggest opening issues for these additional editor features.

**Comment by refried** [comment]
+1 to cajoling @pchiusano into doing more braindumps into issues :)

**Comment by pchiusano** [comment]
Closing this and any editor-related issues. We are going to be focused on getting the Unison core language and runtime to "MVP" state over the next several months. See #138 for a bit more discussion.
