### ISSUE TITLE
LSP: unused binding false positive on match guard

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#5247]
**Describe and demonstrate the bug**

If a binding is used only in a match guard it is flagged as unused, even though this _is_ a type of usage.

Input:
````
foo = cases
  Some n | n > 0 -> "positive"
  _ -> "not positive"
````

Output:
````
■ Unused binding "n". Use the binding, or prefix it with an _ to dismiss this warning.
````

**Screenshots**

![image](https://github.com/user-attachments/assets/a4b429d3-60c3-4a3c-ad00-f64b5ab81f95)

**Environment (please complete the following information):**
 - `ucm --version` "0.5.25"
 - OS/Architecture: x86 NixOS

**Comment by ChrisPenner** [comment]
I don't have time to actually fix it today, but documenting what I've found:

Looks like bindings are brought into scope separately, once for the guard and once for the body, so unless you use it in BOTH places you get an error 🙃 

Therefore, this one fails for the _opposite_ reason :'( 

```
foo = cases
  Some n | 1 < 999 -> n
  _ -> 0
```

I think I can fix it by adding some manual lifting over Match Cases https://github.com/unisonweb/unison/blob/trunk/unison-core/src/Unison/Term.hs#L47-L48

It's strange to me that we `Abs` the same binding in multiple places, but w/e I guess I'll just have to special case this one.
