### ISSUE TITLE
Some commands don't wind up in command history (Haskeline?)

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#527]

**Comment by atacratic** [comment]
For example, I had a session as follows:
```
view base.list.reverse
ls reverse
view base.List.reverse
help alias.term
```
The `help` command didn't appear in my history when I used the up arrow to go through old commands.

I then did `help alias.type`, afterwards neither of the help commands appeared.

(M1a)

**Comment by atacratic** [comment]
... I then did `alias.type base.List.foldLeft base.List.foldl`, and afterwards that command did not appear in the history, but `help alias.term` now did appear.

Does haskeline get kicks to update itself sometimes?  Are we missing some calls to do that?  

Or is there some file involved - could be to do with behavior around how that file is flushed?

**Comment by pchiusano** [comment]
@aryairani reproduced this, see https://github.com/unisonweb/unison/issues/674

**Comment by aryairani** [comment]
It looks like when a command fails (not sure what constitutes a failed command), it doesn't get added to the command history.

When a command succeeds, it adds the first command since the last success to the command history, which may be the most recent command, or may be a totally different, past, failed command.

```
.> find a
.> fail b
.> find c
.> fail d
.> fail e
.> find f
.> fail g
.> fail h
.> fail i
.> find j
.> find k
.> find l
.> find m
```

produces this LIFO command history:

```
find m
find l
find k
fail g -- added upon executing `find j`, which is not added
fail d -- added upon executing `find f`, which is not added
fail b -- added upon executing `find c`, which is not added
find a
```
