### ISSUE TITLE
network connect failure should include host/port

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#5274]
**What's the message you're seeing?**

```
    Failure
      (typeLink IOFailure)
      "Network.Socket.connect: <socket: 74>: does not exist (Connection refused)"
      (Any ())
```

**What would a better version look like?**

```
    Failure
      (typeLink IOFailure)
      "Network.Socket.connect: Failed to connect to localhost:8080; does not exist (Connection refused)"
      (Any ())

```

Environment (please complete the following information):

* `ucm --version` d5d9d9d9a
* OS/Architecture: x86 linux (NixOS)

**Comment by aryairani** [comment]
@ceedubs I agree it would've been better if the original message had included host/port, but in the spirit of not changing builtins, I would try to get this behavior changed in `base` if possible. Feel free to reopen if I misunderstood and that isn't possible to fix without altering the behavior of a builtin
