### ISSUE TITLE
Change syntax of `and` and `or` to not be prefix, which is super annoying (either `and` infix or `&&` infix)

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#530]
Currently they are builtin prefix syntax and look like functions even though they're not. Possible alternatives:

1. Make these `&&` and `||`, which will be familiar to most programmers. People are more ready to accept that infix operators are builtin syntax.
2. Make them special infix syntax like `foo and bar`. This might be OK and is more friendly to newbies who maybe have never seen a programming language.

**Comment by atacratic** [comment]
Why are they built in? Is it so they can short-circuit, i.e avoid evaluating 2nd arg if possible? Why wouldn't making them regular functions with delayed 2nd arg work for that?

**Comment by atacratic** [comment]
Ah - I see - so they can be infix. An argument for allowing user defined infix operators maybe. Having them builtin seems a bit yuk to me, but not too bad.

**Comment by aryairani** [comment]
Yeah, they're built-in so they can short circuit.  You can already user-define infix operators, we just don't have delayed args unless you're willing to use extra syntax at the call site to pass the second arg as delayed, a matter of `(&&) : Boolean -> 'Boolean -> Boolean` vs `(&&) : Boolean -> Boolean -> Boolean`.

**Comment by atacratic** [comment]
Makes me wonder about automatically coercing arguments to be delayed, if that makes them match the expected argument type. Idris does this, with its inference of `Delay` for `Lazy` arguments (and `Force` for non-lazy ones) - [more info](http://docs.idris-lang.org/en/latest/tutorial/typesfuns.html#laziness).

On infix:  if you input ``x `foo` y``, then even aside from the backtick noise, it will later get pretty-printed back out again as `foo x y` - see comment [here](https://github.com/unisonweb/unison/blob/939a88f153bbaf81e979c573bdd521ccd297929e/parser-typechecker/src/Unison/TermPrinter.hs#L276) - so I don't think we have the full setup for user-defined infix ops yet.  I think it would involve some metadata on the operator definition, as well as complications in the parser.

**Comment by aryairani** [comment]
Interesting, I didn't know that about Idris.

On infix: ah yeah, good point.  I was thinking specifically about "symboly" infix operators, like `Nat.+` or `<=`. I expect those are rendered infix by default, based on the class of the name.  "Wordy" functions like `foo` are rendered prefix by default.

**Comment by aryairani** [comment]
> Makes me wonder about automatically coercing arguments to be delayed, if that makes them match the expected argument type. Idris does this, with its inference of `Delay` for `Lazy` arguments (and `Force` for non-lazy ones) - [more info](http://docs.idris-lang.org/en/latest/tutorial/typesfuns.html#laziness).

@pchiusano

**Comment by TomasMikula** [comment]
> Makes me wonder about automatically coercing arguments to be delayed, if that makes them match the expected argument type.

In Scala, I always find it confusing that by-value and by-name arguments are indistinguishable at the call site (one has to look at the function definition to find out that an argument is by-name). I prefer being explicit.

**Comment by aryairani** [comment]
@TomasMikula Does that extend to `&&` and `||`, which short-circuit in other strict languages?

**Comment by pchiusano** [comment]
My vote is for `&&` and `||`. Probably 99% of early users will be more familiar with this syntax than the thing we have now, which is kind of strange IMO. Also with #499, we could revisit this decision later very easily and not break anyone's code. :)

As for making them regular functions... maybe later. Like every other strict language, `and` and `or` get treated specially during compilation and code generation, so you aren't creating thunks every time they are called. It might be cool to be able to define your own non-strict functions with no syntactic or runtime overhead but it doesn't feel like a priority right now.

**Comment by TomasMikula** [comment]
> Does that extend to && and ||, which short-circuit in other strict languages?

I only meant function calls.
