### ISSUE TITLE
LSP incorrectly warns about unused bindings

### ISSUE THREAD

**Issue by tfausak** [unisonweb/unison#5322]
``` unison
f : List Boolean -> List Boolean
f = cases
  x +: ys | x -> ys
  _ -> []
```

![image](https://github.com/user-attachments/assets/133dc63f-5a63-4ab8-9bec-b97dfa62e0a7)

``` sh
$ uname -a
Linux cc6a47ee3517 6.10.7-orbstack-00280-gd3b7ec68d3d4 #4 SMP Mon Sep  2 03:51:24 UTC 2024 x86_64 GNU/Linux

$ ucm --version
unison version: release/0.5.25 (built on 2024-07-22)
```

**Comment by ceedubs** [comment]
This was fixed about a month ago, but it doesn't look like it has made it into a release yet. https://github.com/unisonweb/unison/pull/5265

**Comment by tfausak** [comment]
Ah, so this is a duplicate of #5247. I can wait for the next release 😄
