### ISSUE TITLE
Empty code block in doc causes UCM exception

### ISSUE THREAD

**Issue by channingwalton** [unisonweb/unison#5349]
**Describe and demonstrate the bug**

Input in scratch.u:
````
README = {{{
```
```
}}
````
Then save the editor:
```ucm
Encountered exception:
Prelude.last: empty list
CallStack (from HasCallStack):
  error, called at libraries/base/GHC/List.hs:1644:3 in base:GHC.List
  errorEmptyList, called at libraries/base/GHC/List.hs:158:13 in base:GHC.List
  lastError, called at libraries/base/GHC/List.hs:153:29 in base:GHC.List
  last, called at src/Unison/Syntax/Lexer/Unison.hs:432:23 in unison-syntax-0.0.0-45p2Y49CWcnC6rok1OkVIc:Unison.Syntax.Lexer.Unison
```

**Environment (please complete the following information):**
 - unison version: release/0.5.26 (built on 2024-09-05)
 - MacOS 14.6.1 on Macbook Pro M1 Max

**Comment by aryairani** [comment]
Sorry about that, thanks for the report. 

It looks like it started here: [`31f952`](https://github.com/unisonweb/unison/pull/5187/commits/31f952201c5a1448af0eb78b5a9dbff63f12c05f#diff-9aec44c368f63feea9735b79fe84b40ad5990d15a9d1856a7f82f45166fa6f89R831), https://github.com/unisonweb/unison/pull/5187.
