### ISSUE TITLE
@unison/http doesn't round-trip due to indirect dependency aliases

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#5358]
If you `edit.namespace` in `@unison/http` you'll have to first comment out a bunch of definitions due to typechecker errors, and then will hit this one which @mitchellwrosen thought had been fixed in #5343 

```
  I couldn't figure out what contentLength.get refers to here:

    165 | Body.decodeNonChunkedBody headers = match contentLength.get headers with

  The name contentLength.get is ambiguous. Its type should be: Headers -> Optional
  Nat

  I found some terms in scope that have matching names and types. Maybe you meant
  one of these:

  ...ers.standard.contentLength.get : Headers -> Optional Nat
  standard.contentLength.get : Headers -> Optional Nat
```

@mitchellwrosen will do an initial spike

**Comment by ceedubs** [comment]
A change to the http library to remove the offending aliases happened shortly before this issue was created.

**Comment by mitchellwrosen** [comment]
This is fixed by https://github.com/unisonweb/unison/pull/5360
