### ISSUE TITLE
The dichotomy between `Pair a b` and `(a,b)` is confusing.

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#536]

**Comment by pchiusano** [comment]
Thoughts on renaming `Pair` type to `Tuple` and its constructor `Tuple.Cons`? 

Might make it more clear tuples are just nonempty hlists. So for instance, `Tuple.at1` becomes:

```Haskell
Tuple.at1 : Tuple a rest -> a
Tuple.at1 t = case t of Cons hd _ -> hd

-- some type syntax sugar like `(a,b..rest)` might be nice
Tuple.at2 : Tuple a (Tuple b rest) -> b
Tuple.at2 t = case t of Cons _ (Cons b _) -> b
```

**Comment by aryairani** [comment]
Sounds good to me.  Lisp’s cons was often treated as a pair

**Comment by pchiusano** [comment]
fixed in https://github.com/unisonweb/unisonbase
