### ISSUE TITLE
Documentation for packages/branches

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#537]
Need a way of linking docs to not just types and terms, but branches/packages or groups of things.

**Comment by pchiusano** [comment]
Options: a simple convention for package docs might be ok. The package docs for a path, p, are the term of type “PackageDocs”, under the path p.

Alternately, we could allow links to be attached to the branch at any level. That would require changes to branch structure. Probably more to think through.

**Comment by aryairani** [comment]
Does the `README : Doc` convention satisfy this ticket?

**Comment by hojberg** [comment]
Yeah, Readme can just link to a docs namespace for high level docs.
