### ISSUE TITLE
Make the output of `update` and `add` more friendly.

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#543]
As well as the output in response to saving a scratch file. The table format is confusing and complicated.

I propose implementing suggestion #1 from here:

https://gist.github.com/pchiusano/419f8f8b1abee8f5e465ccd7c2ddf1bf

**Comment by pchiusano** [comment]
Spent way too long on this, and I'm not even sure it's great, though it's an improvement over what was there before.

The message on each .u file save tells you how the codebase would be affected by an `add` or `update`:

<img width="900" alt="Screen Shot 2019-07-04 at 1 03 18 AM" src="https://user-images.githubusercontent.com/11074/60641020-f38b8200-9df7-11e9-8424-122e3619a9a3.png">

After an `add`, the message switches to past tense, describing what happened.

<img width="609" alt="Screen Shot 2019-07-04 at 1 03 30 AM" src="https://user-images.githubusercontent.com/11074/60641021-f38b8200-9df7-11e9-9535-aa40df07e46a.png">

If you `add` again, and the file is all duplicates, you get a shorter message saying exactly that:

<img width="908" alt="Screen Shot 2019-07-04 at 1 03 50 AM" src="https://user-images.githubusercontent.com/11074/60641022-f38b8200-9df7-11e9-85ac-317f175bad31.png">

If not everything is a duplicate, the duplicates are greyed out and shown in a compact way:

<img width="888" alt="Screen Shot 2019-07-04 at 1 11 24 AM" src="https://user-images.githubusercontent.com/11074/60641194-d0150700-9df8-11e9-9d57-e79628754e9f.png">

And if you have more than 10 duplicates, you get a `... 42 more`, along with a tip that suggests moving things below the fold:

<img width="908" alt="Screen Shot 2019-07-04 at 1 12 12 AM" src="https://user-images.githubusercontent.com/11074/60641202-d7d4ab80-9df8-11e9-9f5e-9e564d66087d.png">

Lastly, failures are shown in a compact table, with the reason for the failure alongside each symbol. If the user isn't familiar with the different failure causes, they get a tip to find out more. I like this sort of "just in time" teaching.

<img width="913" alt="Screen Shot 2019-07-04 at 1 05 57 AM" src="https://user-images.githubusercontent.com/11074/60641023-f38b8200-9df7-11e9-8933-0056e6c7a098.png">

**Comment by aryairani** [comment]
Can the “reason” for ones blocked by dep failure include the names of the blocked deps?

**Comment by pchiusano** [comment]
Sure... although that info not currently in the slurpresult so we’d have to add that.
