### ISSUE TITLE
can't distinguish identical local and codebase constructor in TDNR

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#545]
If I save, add, and re-save this file:

```
type MyEnum = X Nat Nat Nat
makeX = X 3 3 3
```
I get:
```
I'm not sure what X means at line 6, columns 9-10

    6 | makeX = X 3 3 3

Whatever it is, it has a type that conforms to Nat -> Nat -> Nat -> o.
I found some terms in scope that have matching names and types. Maybe you meant one of these:

  - MyEnum.X : Nat -> Nat -> Nat -> MyEnum
  - .MyEnum.X : Nat -> Nat -> Nat -> .MyEnum
.> 
```
Possibly a constructor-specific version of #377.

**Comment by pchiusano** [comment]
<img width="926" alt="Screen Shot 2019-07-13 at 8 00 02 AM" src="https://user-images.githubusercontent.com/11074/61171343-3e1da480-a544-11e9-90e5-61fba43837d4.png">

No longer present in topic/556, seems to have fixed itself...
