### ISSUE TITLE
Parser should support importing and referencing of absolute names

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#547]
- [x] Lexer changes to handle wordy and symboly ids starting with '.'
- [x] For consistency, import syntax should work for `use . Nat` (imports a root name locally). This syntax is weird, but it's consistent.
- [x] Nice parse error message if you attempt to define something with a leading '.'
- [x] Why doesn't parse error message get triggered for a binding? Like `.foo = 23`

Bonus:

- [ ] Unique name suffixing transformation on `Names0`.

Later:

- [ ] `add` and `update` should allow definitions to appear anywhere in the tree, not just at absolute paths? or at least make this give this a nice error message, rather than silently doing something stupid (add a . prefixed name at the current path).

**Comment by atacratic** [comment]
Probably need to check how it interacts with FQN elision, i.e. what TermPrinter.calcImports makes of a leading dot.

**Comment by pchiusano** [comment]
Okay, am closing this, but added #553 #552 for later improvements.
