### ISSUE TITLE
why is `move` slow?

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#5476]
**Describe and demonstrate the bug**

Mitchell had seen like an 8s deletion, but why? It should be like constant work, right?

**Screenshots**

**Environment (please complete the following information):**

**Additional context**

**Comment by mitchellwrosen** [comment]
I can't seem to reproduce this... I think what may have happened is my terminal screen coincidentally didn't update (happens all the time in iTerm2...) after I ran `move` for the first time in ages, which made me think `move` was to blame. Closing for now.
