### ISSUE TITLE
Allow any unique suffix to identify a definition

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#552]
Example: you can use `Optional` unqualified, without an import, as long as there's no other `Optional` type in your tree. 

If you've got two `Optional` types, `.foo.bar.Optional` and `.qux.zing.Optional`, then `zing.Optional` is a suffix of name segments that uniquely identifies the type you want and can be used without any imports.

I think this goes a long way. Like no need to `use Optional None Some`, since `None` and `Some` are unique suffixes (as are many constructor names for other data types).

More generally, you can refer to a thing without imports using any suffix of name segments that has just one corresponding `Reference`/`Referent`.

Idea for implementation: a function `Names0 -> Names0`. Any referent `r` with just one name gets all the suffixes of that name inserted as aliases for `r` as long as these suffixes aren't taken. Example, if `foo.bar.baz` uniquely maps to `r`, we also insert `(bar.baz, r)` and `(baz, r)`. If `baz` or `bar.baz` already exist as mappings, we skip inserting these aliases.

**Comment by pchiusano** [comment]
Let's have this also be the issue that solves #669, which was specifically about the `find` command.

**Comment by pchiusano** [comment]
Also #657

**Comment by atacratic** [comment]
I wonder about taking advantage of this to cut down on use statements emitted by the pretty-printer. Currently they're nice and clear, but also a bit unsightly.

Do you think this is a good idea in principle @pchiusano?

Maybe there could be a preference setting to control this.

**Comment by atacratic** [comment]
Some chat about various options for pretty printing, imported from a slack thread...

The current behaviour has the property that you need zero knowledge of the names in the codebase to (a) understand the code and (b) work out the full path of any name mentioned. I think we'd want to keep access to that behaviour (`view.verbose`?)

The 'show minimal suffix' behaviour (this ticket) has property a, but not property b, which is fine. People can use `find` or `view.verbose` to work out full paths, with no ambiguity.

The problem with inserting wildcard imports is that you'd lose property a - people could easily assume that Optional means base.Optional when actually it's resolving to foo.qing.Optional, and spotting that that's what's happening requires 1) knowing that foo.qing.Optional exists 2) spotting that there's a `use foo.qing` in your file and 3) knowing that `use` statements interact in an order-significant way in cases of suffix collisions.
