### ISSUE TITLE
Overhaul Codebase interface to not depend on FilePath and particular serialization format

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#560]
This may require adding some methods that enumerate known `Terms`/`Types` (as `Reference.Id`), etc.

**Comment by aryairani** [comment]
Or maybe just expose a the lists of term, decl references, and then `syncTo/From` could be a separate function (in any module) that loads `terms`, `decls`, `watches`, `getRootBranch`, and calls `put*` as needed.

**Comment by pchiusano** [comment]
Note: the current `syncTo/From` functions are super efficient because they don't need to serialize or deserialize anything, they are just copying files. Would be nice to still have this happen.

**Comment by aryairani** [comment]
Note: Just copying files may not be significantly more efficient than serializing/deserializing them.

**Comment by ceedubs** [comment]
@aryairani is this still relevant or has the move to SQLite rendered this issue obsolete?
