### ISSUE TITLE
Do kind checking

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#567]
```
foo : Optional   -- (Should be `Optional a`)
foo = None
```
yields
![image](https://user-images.githubusercontent.com/538571/61097604-f0ad1480-a429-11e9-8e36-26d102baa9bc.png)

**Comment by pchiusano** [comment]
Phase 1 of this might be: come up with implementation plan and sketch it out, timeboxed.

**Comment by pchiusano** [comment]
@dolio Just recording this here. 

For implementation, we realized that there's probably no need to change the codebase format or AST at all, at least for now where kinds can be fully inferred.

What we could do is have the typechecker do a kind inference pass up-front before starting typechecking. The typechecker should already have all data declarations used or referenced by the program in its environment (if not we could tweak things to ensure all transitively referenced decls are included in the environment). 

So it can just do the kind-inference on all those data decls, report errors, and then use the kind info when doing typechecking of the terms. It would be a change that's totally local to the typechecker - other than some new error messages.

**Comment by ceedubs** [comment]
Some test cases that came up from [this discussion](https://unisonlanguage.slack.com/archives/CLKV43YE4/p1631197470159600). All of these _currently_ compile, but only a few of them should.

```
structural type Reader f a b = Reader (a -> {f} b)

-- should compile
x1: Reader Abort Text Nat
x1 = Reader (_ -> abort)

-- should compile and be the same as x1
x2 : Reader {Abort} Text Nat
x2 = Reader (_ -> abort)

-- should compile
x3 : Reader {Abort, .base.Exception Text} Text ('Nat)
x3 = Reader (_ -> _ -> abort)

-- shouldn't compile because `f` is expected to be an ability and `Int` is not
x4: Reader Int Text Nat
x4 = Reader (_ -> 3)

-- shouldn't compile because `Optional` is neither a rank-1 type nor an ability.
x5: Reader Optional Text Nat
x5 = Reader (_ -> 3)
```

**Comment by tstat** [comment]
https://github.com/unisonweb/unison/pull/4331
