### ISSUE TITLE
Let's not put `use` inside of the `if` condition

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#568]
Even if we fix the formatting bug where a multiline condition isn't indented, I just think multiline conditions look pretty weird so we shouldn't insert a `use` statement in the middle of an `if` expression's condition:

<img width="415" alt="Screen Shot 2019-07-12 at 3 15 51 PM" src="https://user-images.githubusercontent.com/11074/61153107-36182300-a4b8-11e9-9bc5-fcef12e61e82.png">

Also maybe related is #518

@atacratic can you take a look at this one?

**Comment by atacratic** [comment]
Sure! (I see you've toned down the colors 😉)
