### ISSUE TITLE
Building blocks for making node runtime agnostic to underlying storage layer: `BlockStore` and `Namespace`

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#57]
Currently, we have some of the node runtime relying on access to the local filesystem to persist some of its state. We'd like to move away from this and make the storage backends pluggable. For that we need a couple interfaces which I'm calling `BlockStore` (an immutable, content-addressed storage layer in which blocks are addressed by a hash of their content) and `Namespace` (a mutable name service in which the values associated with a key may be altered given a proper signature).

Node containers [as discussed in this post](http://unisonweb.org/2016-06-17/node-containers.html#post-start) will use these APIs for storing persistent state of the container and of individual nodes in the container.

Here is a sketch of the APIs, which can just be added to `unison-shared`.

```Haskell
module BlockStore where

import Data.ByteString (ByteString)

newtype Hash = Hash ByteString

-- | Represents an immutable content-addressed storage layer. We can insert
-- some bytes, getting back a `Hash` value that can be used for `lookup`.
-- Given `bs : BlockStore` and `bytes: ByteString`:
--   `insert bs bytes >>= \h -> lookup bs h` should result in `Just bytes`.
-- also `insert bs bytes >> insert bs bytes` is equivalent to `insert bs bytes`, requiring
-- that the returned hash be purely a hash of the content of `bytes`
data BlockStore = BlockStore {
  insert :: ByteString -> IO Hash,
  lookup :: Hash -> IO (Maybe ByteString),
  -- proposal for allowing GC of old blocks; can allocate a series
  insertSeries :: ByteString -> IO (Hash, Series),
  -- this fails if the hash does not match the last written block for this series
  -- but if it succeeds, the input hash is marked as garbage and can be deleted
  update :: Series -> Hash -> ByteString -> IO Hash
}
```

Whenever you need to persist some values, you call `insert` on the block store, and use the returned `Hash` as the handle to that persisted data. `delete` is deliberately missing for now.

For implementing mutable, persistent data structures like a key-value store, we need the ability to _update_ what hash is considered 'current' (similar model to git, where we have an immutable DAG of hashes, and branch names are mutable pointers to a hash). For this we use a `Unison.Namespace`:

```Haskell
module Unison.Namespace where

newtype Name = Name ByteString
newtype Nonce = Nonce Word64

newtype Authorization = Authorization { nonce :: Nonce, bytes :: ByteString }

-- | A mutable namespace of hashes. 
data Namespace key fingerprint h = Namespace {
  -- | Associate the given name with the provided key, returning a hash of key
  declare :: key -> Name -> IO fingerprint,
  -- | Resolve a fingerprint + name to a hash
  resolve :: fingerprint -> Name -> IO (Maybe (h, Nonce)),
 -- | Requires proof of knowledge of the key passed to `declare`
  publish :: fingerprint -> Name -> Authorization -> h -> IO (Maybe Nonce)
}
```

The idea here is that the owner of the `key` passed to `declare` may update the value associated with that name, but the `Namespace` store enforces strictly sequential updates to a particular name by requiring that the authorization passed to `publish` incorporate a nonce which is updated after each `publish`. Thus multiple threads may contend to publish, and the updates are forced to be linearized, similar to STM.

The usual implementation of this interface would be for `key` to be a public key, `fingerprint` to be a hash of that public key, and `Authorization` to be a signature (using the corresponding private key) of the nonce plus the new value `h` plus perhaps some padding, etc. But the way the interface is written, we can also have `key` be a private key, `fingerprint` be a hash of that private key, and `Authorization` bytes be a hash of (nonce, private key, new hash).

Subtasks:

- [ ] Sanity check: make sure we can implement key-value store atop these interfaces, possibly make adjustments to the interfaces accordingly
- [x] Implement these interfaces in unison-shared
- [ ] Provide in-memory implementations of both these interfaces, `Unison.BlockStore.MemoryBacked` and `Unison.Namespace.MemoryBacked`, in unison-shared project.
- [ ] Provide file-backed implementation of both these interfaces, `Unison.BlockStore.FileBacked` and `Unison.Namespace.FileBacked`
- [ ] Optional: provide combinators for adding caching to a `BlockStore` or a `Namespace`
- [ ] Implement acid-state-like library parameterized on a `BlockStore` and `Namespace`
- [ ] Convert key-value store implementation to use this acid-state-like library. A big benefit here is that we have more control over what is actually persisted and what lives in memory. For instance, we can have just the keys live in memory

**Comment by sfultong** [comment]
I don't think I'm seeing your vision through this code.

What does the returned IO Hash represent in BlockStore.insert?

What does Namespace represent, and how does it relate to Nodes?

I also have some unresolved uncertainty with how loading an existing BlockStore will work. So a namespace will provide a way of resolving named BlockStores? I assume then Unison will have a BlockStoreName type builtin.

**Comment by pchiusano** [comment]
Yeah, stand by, @sfultong I am adding some more info then will contact you to discuss.

**Comment by pchiusano** [comment]
@sfultong okay added a bunch more detail, will ping you tomorrow to discuss, in the meantime see if you can start thinking about how you'd write a persistent key-value store using just these abstractions for dealing with storage.

Some open questions around providing some ability to safely delete things added to the block store. You want to somehow enforce that the hash that's been returned isn't still being referenced.

**Comment by sfultong** [comment]
How come h is a parameter to Namespace? Wouldn't it always be Hash?

Will the linkage of a Namespace to a particular BlockStore be explicit, or should I hard-code one Namespace to one particular BlockStore for now?

**Comment by pchiusano** [comment]
> How come h is a parameter to Namespace? Wouldn't it always be Hash?

Probably yeah, but there didn't seem to be any harm in abstracting it. Gives the option of encoding the hash function in the return type (like that it is a SHA3 hash, not an MD5).

> Will the linkage of a Namespace to a particular BlockStore be explicit

No it is implicit / out-of-band knowledge. `Namespace` is just a general-purpose thing. It will be a common usage for the values in a `Namespace` to be hashes that refer to some `BlockStore`, and that is how I was imagining it would be used for us, but the type doesn't assume that.

 or should I hard-code one Namespace to one particular BlockStore for now?

**Comment by pchiusano** [comment]
@sfultong I think I figured out a nice way of doing deletions in the `BlockStore` interface. Have a look. Will discuss with you tomorrow.

**Comment by Ericson2314** [comment]
I might have mentioned this before, but I made https://github.com/Ericson2314/haskell-vcache/blob/master/generic-store/hsrc_lib/Database/Generic.hs to abstract over the haskell-vache API. Some overlap in the concept.
