### ISSUE TITLE
Add local configuration file where you can find default `push` / `pull` targets for paths, and other config

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#577]
```
> cd .myproject

<hack hack hack>

.myproject> push

I don't know where to push to! Use `track <giturl>` to set up this path to push and pull from <giturl>.

.myproject> track git@github.com:unisonweb/testrepo.git

A `push` or `pull` from `.myproject` path will now talk to the git@github.com:unisonweb/testrepo.git repo.

I've saved this configuration to your `.config` file, which you can edit directly if you like. 

in `.config` file:

.myproject = git@github.com:unisonweb/testrepo.git
.myotherproject = git@github.com:pchiusano/topsecrete.git

.myproject> push

Here's what will happen on `push`, type `push` again to actually do it:

-- show a preview of what's going to happen

.myproject> push

... DONE

.myproject> pull

... DONE
```

So the thought here is that `push` and `pull` almost never take any arguments, they usually just lookup the default that's in the users's `.config` file.

Also if you `pull <url>` from a path, it does a `track <url>` if there's not already something tracked at that path.

**Comment by pchiusano** [comment]
@runarorama Implementation notes, will need a `Command` for accessing info from the `.config` file, and then updates to `HandleCommand` (to interpret the new command) and then `push` and `pull` implementations can access the config.

If `pull` populates the config file (seems reasonable), can maybe get away with not having a separate `track` command for now.

**Comment by francisdb** [comment]
was this implemented?
