### ISSUE TITLE
Add a version of `update` and `todo` that doesn't need/use a patch, just assume <currentpath>.patch by default, and tell the user.

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#580]
- [x] update inputs
  - [x] `update`
  - [x] `todo`
  - [x] `listedits`
- [x] update inputpatterns
  - [x] `update`
  - [x] `todo`
  - [x] `listedits`
- [ ] update outputs to include patch names
- [ ] update outputmessages to include patch names

**Comment by aryairani** [comment]
the inputpatterns don't have access to the current path, although the auto-complete providers do!

**Comment by aryairani** [comment]
Remaining items are tracked in #909.
