### ISSUE TITLE
Handle external branch file updates (see todo in HandleInput.hs) - maybe just ignore for now and give some message.

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#581]

**Comment by aryairani** [comment]
![image](https://user-images.githubusercontent.com/538571/61506655-d090ce80-a9b0-11e9-9608-d40fbeff1148.png)

**Comment by pchiusano** [comment]
@aryairani I'm not totally happy with this message since for the common case where one hash is an ancestor of the other, the merge would be a noop and I wouldn't suggest they do surgery on their codebase repo. What about the following check:

* If one hash is an ancestor of the other (can just do the merge and see if the merged hash equals one of the arguments), I'd just have the merged version become the root. You can have a less alarming message in this case. Maybe: "I just detected and ignored an old codebase root. This shouldn't happen but isn't a problem. It will be fixed in a future release. 😅"
* If one isn't an ancestor of the other, then you can give the alarming message that you've got now.

**Comment by pchiusano** [comment]
Dup of #616
