### ISSUE TITLE
`push` and `pull` should be sure to deal with `patches` directory

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#590]
Apparently they don't right now, which leads to cryptic failures.

**Comment by runarorama** [comment]
It does actually deal with it, so something else is going on. Would be nice to have a test case, or, you know, anything.

**Comment by pchiusano** [comment]
sorry, don't have a minimized test right now, noticed it randomly while messing around. I'll see about putting one together.

**Comment by pchiusano** [comment]
I'm going to close this until I can actually reproduce in some fashion or have any description at all, this ticket not really useful as is.
