### ISSUE TITLE
Crash on hashing higher rank constructor type

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#595]
Added a pending test:

```
type Any = Any (∀ r . (∀ a . a -> r) -> r) 
```

Which typechecks as expected but crashes when added to codebase. 

```
unison2: unknown var in environment: "r" environment = [Right User "a"]
CallStack (from HasCallStack):
  error, called at src/Unison/ABT.hs:632:19 in unison-parser-typechecker-0.1-JxZSVhIPWTr4SazQ0mw03q:Unison.ABT
```

**Comment by TomasMikula** [comment]
I encountered the same error when poking around the typechecker, expecting some tests to fail. All tests passed, but then Unison crashed when copying the test code to the watched directory. This suggests a couple things that could be done:

 - Compute hashes of definitions in `unison-src/tests` (in addition to typechecking).
 - `ABT.hash` should not crash, but return an error. The caller can then print a more useful error message to the user.

**Comment by TomasMikula** [comment]
I'm willing to try returning some error type from `ABT.hash`, if you agree it is a good idea.
