### ISSUE TITLE
Change remote Git repo structure to contain the `.unison/v1` structure that the user has locally

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#599]
Right now if I `push` to a fresh repo, I see something like this:

<img width="1265" alt="Screen Shot 2019-07-24 at 9 59 47 PM" src="https://user-images.githubusercontent.com/11074/61840231-84390900-ae5e-11e9-80f2-0d8164b4a811.png">

But I think all those same directories should be nested under `.unison/v1`, just as they are in my local codebase. Reasoning: 

1. Makes the repo self-describing, rather than version info being some out of band information.
2. It's good if a Unison remote repo can have code from multiple versions of the Unison codebase format (so it could have `.unison/v1`, `.unison/v2` etc). Imagine if on every Unison codebase format change, everyone with Unison code needed to create a new Git repo and then tell all users of their code about the new repo. That would be pretty tedious.

I think we should make this change ASAP before the release, since it is going to be annoying to change later once people have Unison git repos.

**Comment by runarorama** [comment]
Resolved by dc3c4773f581e8ed48f8b0b432e1fe9881d78994
