### ISSUE TITLE
rfc5051 :: Stackage Server

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#606]
https://www.stackage.org/lts-13.29/package/rfc5051-0.1.0.4 should use this for sorting names

**Comment by pchiusano** [comment]
Note: I added this library as a dependency, and added a couple functions to the `Unison.Name` module:

```Haskell
-- ex: sortNamed fst (results :: [(Name, stuff)])
Name.sortNamed : (a -> Name) -> [a] -> [a]
Name.sortNames : [Name] -> [Name]
```

I'm now using it for the diff display #605 but haven't hooked it up elsewhere. I think the most immediate win is that upper and lowercase of the same letter appear together in results.

Also briefly considered just changing the `Ord` instance for Name but that didn't seem like a good idea as this is a display level concern.

**Comment by aryairani** [comment]
I think we are using this more universally now, so I am closing for now. Feel free to make a new ticket or reopen this one if the sorting is found to be missing in a more specific context.
