### ISSUE TITLE
Parser of `Float` literals should support exponents.

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#611]
A resolution of this issue should add parsing and pretty-printing for exponents in floating point numbers. For example `1e-3` for `0.003`.

It's currently a syntax error to write `1.6777217e7`, but this should be parsed as the number `16777216.0`. Without the exponent portion, the vast majority of floating point numbers are inaccessible to literals.

The parser should expect floating point literals to have the following form:

``[`-`](decimal.decimal[exponent]|decimal[exponent])``

``where exponent = (`e`|`E`)[`-`]decimal``

**Comment by pchiusano** [comment]
Tip for anyone looking into this, I think on the parsing side, just modifying this one function in the lexer might do it: 

https://github.com/unisonweb/unison/blob/master/parser-typechecker/src/Unison/Lexer.hs#L498

The `Either Err (String,String)` it is returning is the (unparsed numeric literal, remaining input). The unparsed literal is later converted by the parser to an actual number.

**Comment by pchiusano** [comment]
One more parsing spot - I think this check in term parser here won't be quite right, instead should additionally check for presence of `e` or `E` character maybe?

https://github.com/unisonweb/unison/blob/master/parser-typechecker/src/Unison/TermParser.hs#L528

**Comment by atacratic** [comment]
If someone looks at this, it might also be a good moment to consider whether we should be able to parse or pretty-print float literals with values Infinity, -Infinity and NaN.  ([comment](https://github.com/unisonweb/unison/blob/bf943e2df6b33acfcca549dfb8617d99e3988b35/parser-typechecker/src/Unison/TermPrinter.hs#L166))

**Comment by scott-christopher** [comment]
Happy to have a look at this.

**Comment by pchiusano** [comment]
This is closed, thanks to @scott-christopher :)
