### ISSUE TITLE
`I loaded scratch.u and didn't find anything` message, but then it works

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#625]
It seems to take ucm two goes to load the scratch file it created for me, after I edit it.

I follow the quickstart, run `edit quickstart.dsort`, and open the scratch file it creates.  I make an edit to add a watch expression, then save.  I see the output below.  First it claims not to find anything, then immediately it evidently does find the contents OK.

```
  I loaded /home/chris/u1/scratch.u and didn't find anything.

.> 

  
  ✅
  
  I found and typechecked these definitions in ~/u1/scratch.u. If you do an
  `add` or `update` , here's how your codebase would change:
  
    ⍟ These new definitions will replace existing ones of the same name and are
      ok to `update`:
    
      quickstart.dsort : (a
                         ->{quickstart.Remote} a
                         ->{quickstart.Remote} base.Boolean)
                         -> [a]
                         ->{quickstart.Remote} [a]
  
  Now evaluating any watch expressions (lines starting with `>`)...
  Ctrl+C cancels.

    1 | > runLocal '(quickstart.dsort (<) [8,2,3,1,4,5,6,7])
          ⧩
          [1, 2, 3, 4, 5, 6, 7, 8]

.> 
```
M1a, Ubuntu 18.04.2 fresh install.

**Comment by aryairani** [comment]
@atacratic Thanks — what editor are you using for your scratch file?

**Comment by atacratic** [comment]
@aryairani SublimeText (v3.2.1)

**Comment by BenFradet** [comment]
I've been experiencing the same thing from the start, it might have to do with the file watching on Linux (I'm using fedora).

**Comment by atacratic** [comment]
What's your editor @BenFradet?

FWIW I've now also seen the 'didn't find anything' message, but not then followed with it sorting itself out, so I need to save again.

**Comment by BenFradet** [comment]
vscode, I too have both issues but the latter (not finding anything and having to manually re-edit the file) more often.

**Comment by aryairani** [comment]
@atacratic Your ubuntu isn't in WSL, is it? :)

**Comment by atacratic** [comment]
@aryairani no, sorry :-)  It is running on top of VirtualBox on top of Windows 10 though.  I'd hope that wouldn't make a difference...

**Comment by bbarker** [comment]
I believe I'm having the same issue on Ubuntu 18.04 with vs code, though really i'm mostly using nixpkgs instead of Ubuntu packages, including for vs code, and even for building unison and its dependencies.

**Comment by BenFradet** [comment]
I finally have a bit of time, I'll try looking into this :+1:

**Comment by atacratic** [comment]
> FWIW I've now also seen the 'didn't find anything' message, but not then followed with it sorting itself out, so I need to save again.

I see this variant much more often for longer scratch files.  Once my file was around 1500 lines / 36k, I was seeing it > 75% of the time, but then I split the scratch file in half and the frequency went down again.  

Maybe this is a clue that it could be related to timing, and/or to some bit of 'flush buffer once it contains X bytes' config somewhere.

**Comment by atacratic** [comment]
The file watcher uses `System.FSNotify`, and I spotted in the FSNotify docs some rather suspicious talk about debouncing ([docs](http://hackage.haskell.org/package/fsnotify-0.3.0.1/docs/System-FSNotify.html), see `defaultConfig`.)  I bet that's to blame here somehow.  Next step would be to play with the debouncing interval and see if it affects the behaviour in this issue.  I might have a go at that at some point.

**Comment by atacratic** [comment]
In particular the docs say

> Note that the current debouncing logic may fail to report certain changes to a file, potentially leaving your program in a state that is not consistent with the filesystem.

😟

**Comment by atacratic** [comment]
Very brief experimentation with the patch in topic/625-watch-no-debounce hasn't made the 'didn't find anything' message go away, but it might have got rid of the following.

> FWIW I've now also seen the 'didn't find anything' message, but not then followed with it sorting itself out, so I need to save again... I see this variant much more often for longer scratch files.

**Comment by atacratic** [comment]
It looks like every time my editor saves, FSNotify received two modify events.  For example:

```
event: Modified "/home/chris/unison/scratch.u" 2019-09-20 22:21:53.550142716 UTC False
event: Modified "/home/chris/unison/scratch.u" 2019-09-20 22:21:53.550249438 UTC False
```

In this example they're < 1 ms apart, which means they are debounced (... although I thought I'd switched that off in my branch?)

For a bigger file it might be
```
event: Modified "/home/chris/unison/scratch.u" 2019-09-20 22:23:16.548478583 UTC False
  I loaded /home/chris/unison/scratch.u and didn't find anything.
event: Modified "/home/chris/unison/scratch.u" 2019-09-20 22:23:16.570474655 UTC False
```
with a bigger time gap, so no debouncing, so two messages, the first of which being the "didn't find anything".

I don't know why there seem to be two writes. 

Possible next step: instrument `listenRecursive` in FSNotify.Linux, [here](http://hackage.haskell.org/package/fsnotify-0.3.0.1/docs/src/System.FSNotify.Linux.html).
- What are the EventVariety values for the two modifies?
- Is this comment as relevant as it looks? "-- TODO: there's a chance of this generating double events, fix"

Possible next step: run my editor under strace, or some similar way of seeing how many times it's actually writing.  (First attempt: sublime in strace doesn't just work - maybe try a simpler editor, assuming the original issue still repros with that).

Note there is recent unpublished activity in the haskell-fswatch notify in this area, https://github.com/haskell-fswatch/hfsnotify/commits/master, including [this](https://github.com/haskell-fswatch/hfsnotify/commit/e7763158bdfcc1164a20197a5057f8709142f015) and [this](https://github.com/haskell-fswatch/hfsnotify/commit/bf992f2fec8f3f5009112acb9418b68b57f24147).  Possibly relevant [issue](https://github.com/haskell-fswatch/hfsnotify/issues/55).

(full transcript of the session that generated the traces above is [here](https://gist.github.com/atacratic/59ea880881be3fe1b0eec94c0ef5debd))

**Comment by atacratic** [comment]
Unproven but plausible theory:  suppose that
- the editor is making two writes to the file, one that leaves it empty, one that adds the new contents
- both of those are being picked up by FSNotify
- `*` the debouncing mechanism doesn't prevent ucm seeing the file after only the first write (is this really plausible?  interaction with fsync?).

Then that would give the following possible behaviours:
```
  if the two write notifications get debounced into one
  then 
    if ucm reads the file after the second write
    then 
      GOOD: ucm outputs one, correct message
    else -- ucm reads the file after the first write (assumes condition *)
      BAD: ucm just says "I didn't find anything"
  else -- no debounce, unison sees two notifications
    if ucm first reads the file after the first write, and second after the second
    then 
      BAD: ucm first outputs "I didn't find anything", then the correct message
    else -- the other interleaving - both reads are after the second write
      BAD: ucm outputs the correct message, but twice 
        -- (have we observed this one? easy to miss)
```

I think that's a full explanation of all the behaviour we've seen.

Need to actually confirm the theory with diagnostics, but I guess fixes might include
- filter out the first kind of write, if we can (may mean ucm doesn't react to emptying a scratch file)
- increase the debounce timer, and improve debouncing so it only sees the file after the second write
- special case empty files so that they cause some extra application-level debouncing ('wait to see if something gets written').

**Comment by aryairani** [comment]
I haven’t checked the implementation, but it sounds like when debouncing it should be the first events that are ignored, not the last.

**Comment by atacratic** [comment]
Here's what vi does when writing to a pre-existing file, according to strace.  Plus my annotations of what inotify events these map to, from my reading of `man inotify`.

```
openat(AT_FDCWD, "temp", O_WRONLY|O_CREAT, 0644) = 3   IN_CREATE or IN_OPEN?
fstat(3, {st_mode=S_IFREG|0644, st_size=6, ...}) = 0
ftruncate(3, 0)                         = 0            IN_MODIFY
write(3, "hello\n", 6)                  = 6            IN_MODIFY
fsync(3)                                = 0
fchmod(3, 0100644)                      = 0            IN_ATTRIB
close(3)                                = 0            IN_CLOSE_WRITE
```

Note I haven't actually reproduced the problem with vi as the editor, although I do see that the unison watcher is receiving multiple events.  Probably with vi the events are happening over a short enough time span that it works out.  

Certainly supports the theory that there are multiple events, some of which (`ftruncate`) leave the file empty.  

There's no use of timers that I can see in the FSNotify code for this - it is indeed just passing up the first event of the sequence that is being debounced...  Unfortunate because then the client's response to that event (reading the file) races with the rest of the writes in the sequence, and the client will also never see was was written by the later events in the sequence.  

Fix should be to run a timer somewhere, lasting the debounce interval, and only report the event at the end.  Next step is to consider whether to tackle this within FSNotify itself (probably as a new optional behaviour), or just do it in the ucm code.  Either way, a PR for FSNotify to improve the API docs in this area would be good.

(Other part of fix: increase the debounce interval that unison uses from 1ms to maybe more like 5 or 10.  Note the tradeoff with CLI response time.)

**Comment by aryairani** [comment]
So now we need to call these from a C program with sleeps between each call, to confirm which syscalls result in an fsnotify event.  The truncate? The write? The close?  In our case, it would be nice if it were only the close.

**Comment by atacratic** [comment]
My feeling is the diagnosis is safe enough.  e.g. see http://man7.org/linux/man-pages/man7/inotify.7.html  It calls out `write` and `truncate` as both causing a modify.  From a code read the FSNotify debouncing is clearly bugged in that it's reporting the first event rather than waiting til the end of the debouncing interval.  And the various races fit the various symptoms exactly.

I don't think configuring the set of events is the way forward, as truncate and write are treated identically by inotify.  We need actual debouncing, and we need it to work.

**Comment by atacratic** [comment]
Ah - I missed your suggestion of only watching for close: yeah, might be a way forward.  But doesn't work for editors that open the file twice to write it - thinking of the C/POSIX file API I reckon this might be a common case (open once for overwrite and once for append).  Also doesn't work for editors that keep the file open.

**Comment by aryairani** [comment]
Great, thanks for digging into that.

I would be surprised to learn that editors would open the file twice or hold it open, but I’ve been wrong before!

**Comment by atacratic** [comment]
vi seems to do all sorts of stuff - I didn't paste in the bit of the trace where it opens the file for read-only first, and various calls to `stat` and `access` ([full trace](https://gist.github.com/atacratic/cc2a8e10429d50dc9cedce1dbb00de97) for reference).  Also thinking about the rope structures that some editors use, I reckon there could be quite a variety of behaviour on the file API.  "close the file while we GC, then open it again to write the next chunks..."  You're probably right a serious editor wouldn't hold it open.

Nice fun issue anyway :slightly_smiling_face:
