### ISSUE TITLE
ucm should contain help on concepts

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#629]
There are a bunch of mystifying terms and concepts mentioned by the unison commands and help text:
* patch, edit, refactoring session, edit frontier, type-preserving edit
* namespace
* link
* dependent
* alias, hash
* merge (since it doesn't mean the thing people are used to)

Each of these should have some help available to briefly explain the concept, either directly at the command like (as with `help`), or popping up in your browser.

Not everyone is going to assiduously read all the docs before diving in, so it has to be learnable from the bottom up.

I think `help filestatus` is a move in this direction?  It's help that is not specific to a single given command.

**Comment by pchiusano** [comment]
Closing in favor of #708
