### ISSUE TITLE
`Unison bug, unknown term` when typechecking an unnamed test

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#633]
I save a scratch file with
```
test> run ( expect ( 1 == 1 ) ) 
```
and then I see 
```
  
  ✅
  
  I found and typechecked these definitions in ~/u1/scratch.u. If you do an
  `add` or `update` , here's how your codebase would change:
  
    ⍟ These new definitions are ok to `add`:
    
    test.s0o3c5t8o6 (Unison bug, unknown term)
  
  Now evaluating any watch expressions (lines starting with `>`)...
  Ctrl+C cancels.

    16 | test> run ( expect ( 1 == 1 ) ) 
    
    ✅ Passed : Passed 1 tests. (cached)

```

Note the `test.s0o3c5t8o6 (Unison bug, unknown term)`.

M1a.  My .unison folder directly after the failure is attached.
[z.unison.tar.gz](https://github.com/unisonweb/unison/files/3463709/z.unison.tar.gz)

**Comment by rjdestigter** [comment]
I'm running into the same issue for version `devel/M1l-1388-g04040b6ff`

**Comment by pchiusano** [comment]
@rjdestigter yeah, unnamed tests are not really supported at the moment and are an undocumented "feature" that I'm not sure is even useful. How often do you want your tests to be randomly named?

I think the fix might be to just disable unnamed tests in the parser and turn this into a parse error.

I could see putting anonymous tests right before a definition, similar to how we handle anonymous doc blocks. Will give that some thought.

**Comment by rjdestigter** [comment]
I'm not sure if mine are anonymous though:
![image](https://user-images.githubusercontent.com/14314519/118150231-8e2f5180-b3cf-11eb-8cf3-f5bc14565ec0.png)

**Comment by pchiusano** [comment]
A named test looks like this:

```
test> mytest = check (1 + 1 == 2)
```

Basically, it has to be a binding `somename = <expr>`. It can't just be an expression that references a named value that exists elsewhere in the file or the codebase.

**Comment by aryairani** [comment]
<img width="751" alt="image" src="https://user-images.githubusercontent.com/538571/179418442-ab21758c-a170-4bdd-bf89-0a3274adfd87.png">
ucm no longer does this, though I'm not sure exactly when it was fixed.
