### ISSUE TITLE
edit+slurp round-trip fails for definitions that reference unit type ()

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#640]
I add the following:
```
x = ()
```
Then I edit it - Unison gives me this:
```
x : base.()
x = ()
```
But then it doesn't accept that same definition:
```
  /home/chris/u1/scratch.u:1:9:
  unexpected .
  expecting -> or [
      1 | x : base.()
  

.> 
```

If I remove the `base.` from the type signature then it works.

(M1a)

**Comment by aryairani** [comment]
Hi @atacratic I can't reproduce this in the current build, can you?

**Comment by atacratic** [comment]
Agree - suffixy names has gotten rid of it.  Now Unison outputs this:
```haskell
x : ()
x = ()
```
Probably there's still no way of referring to a definition named `()` with a namespace qualification, but maybe that's fine, or at least we don't need this ticket for it.

**Comment by aryairani** [comment]
#742
