### ISSUE TITLE
Compounding use clauses has surprising behaviour

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#653]
Some folks found it surprising that

```
use .base
use Optional
```

didn't bring `Some` and `None` into scope.

Not sure if this is a bug or a feature.

**Comment by atacratic** [comment]
I initially felt like I wanted it to be a bug, so use statements could be nice and abbreviated. But I guess the worry would be ambiguity in the second use statement - is it importing `base.Optional`, or `Optional`? 
I think the strict rules about how use statements manipulate the environment would say the former, but that could certainly be very surprising. Maybe one option would be to throw an error if both of those paths existed in the namespace.

Now feeling slightly more inclined towards it being a feature.

**Comment by runarorama** [comment]
I'm inclined to say that `use` should check what namespaces are actually in scope. If the name `use`d is unambiguous, just use that. If it's ambiguous, give an error like "I don't know which `Optional` you want."

**Comment by atacratic** [comment]
Yeah, sounds good to me. 👍

**Comment by aryairani** [comment]
This also seems to be superseded by suffixification.
