### ISSUE TITLE
Consider allowing types in `.base` to be used unqualified.

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#657]
This is pretty annoying. Specifically:

```
.> find : Nat -> Text

  ❓

  I couldn't resolve any of these symbols:

      1 | Nat -> Text

  Using these fully qualified names: Text
```

**Comment by aryairani** [comment]
Maybe we should allow some kind of suffix match on these types’ names, like
we do with `find` in general.

**Comment by pchiusano** [comment]
This proposal seems relevant: https://github.com/unisonweb/unison/issues/552

**Comment by pchiusano** [comment]
I don’t want types in base to have any special status re: name resolution and would much prefer some more general solution like the one I linked above and/or having some user configurable default import mechanism.

**Comment by pchiusano** [comment]
Tracked in #552
