### ISSUE TITLE
`execute` silently fails when passed a delayed computation

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#661]
I added
```
test : '{io.IO} ()
test _ = .base.io.putText (.base.io.Handle "stdout") "hello world\n"  
```
and did `execute test`, and saw nothing:
```
.> execute test
.>
```
I eventually realised I'd meant `execute !test`.  This will be a common mistake.

Shouldn't `execute` reject `test` based on its type?  (Or possibly be a bit flexible and do the forcing itself.)

**Comment by aryairani** [comment]
`execute` is gone now; `run` accepts programs with type `'{IO, Exception} ()` in release M4, and `'{IO, Exception} a` in the upcoming release.  If you pass the wrong type of argument, it'll give an error now:
```
.> run program2                                            

  😶
  
  I found this function:
  
    program2 : Nat
  
  but in order for me to `run` it it needs to have the type:
  
    program2 : '{IO, Exception} ()
```
