### ISSUE TITLE
should I really have to specify delete.term vs delete.type?

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#662]
I have to write `delete.term` or `delete.type` according to what I'm trying to delete.  But should I really have to, in the common case where the name does not exist both as term and type, but only as one of the two?

Ditto `alias` and `move`.

I appreciate it's hard to get too excited about this one.

(`delete` and `move` have the patch and namespace variants to think about as well.)

**Comment by mitchellwrosen** [comment]
Question: can a term ever have the same name as a type?
