### ISSUE TITLE
`execute` seems to resolve names case-insensitively

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#663]
```
execute .base.IO.putText (.base.io.Handle "stdout") "hello world"
```
... works nicely.  Except it shouldn't!  It should have been:
```
execute .base.io.putText (.base.io.Handle "stdout") "hello world"
```
Note the lower-case `io` qualifying `putText`.

`.base.io.putText` does not have any aliases in my codebase, according to `names`.

@aryairani did some investigation - see the thread under [this message](https://unisonlanguage.slack.com/archives/CLUNF0J5S/p1564949419397100). No hot leads yet though.

**Comment by mitchellwrosen** [comment]
It is perhaps due to this logic:

https://github.com/unisonweb/unison/blob/f06f0ebc5f1b508d595c32c9100fe02593435c39/parser-typechecker/src/Unison/FileParsers.hs#L102-L105

In particular, this guard

```haskell
Name.unqualified name == Name.unqualified (Name.fromVar v)
```

keeps around entries that look like

```haskell
(".io.printLine","IO.printLine",Ref ShortHash {prefix = "ssbda", cycle = Nothing, cid = Nothing})
```

**Comment by aryairani** [comment]
Nice find.  That does look busted.  I think we probably want some kind of suffix match, not a throw-away-the-prefix match.

**Comment by atacratic** [comment]
Could this also explain #688?  Maybe not.

**Comment by aryairani** [comment]
I think this doesn't happen anymore; please reopen if I'm mistaken!
