### ISSUE TITLE
Program using IO won't always update

### ISSUE THREAD

**Issue by russellmcc** [unisonweb/unison#677]
entering

```
use base.io

program : '{IO} ()
program = 'let
  printLine "Message1"
  printLine "Message2"
  ()
```

into a clean codebase gives me

```
  
  ✅
  
  I found and typechecked these definitions in ~/proj/learnproj/unison/scratch.u. If you do an
  `add` or `update` , here's how your codebase would change:
  
    ⍟ These new definitions are ok to `add`:
    
      program : '{base.io.IO} ()
  
  Now evaluating any watch expressions (lines starting with `>`)... Ctrl+C cancels.

.> add

  ⍟ I've added these definitions:
  
    program : '{base.io.IO} ()
```

As I expect, but then when I edit it to 

```
use base.io

program : '{IO} ()
program = 'let
  printLine "Message2"
  printLine "Message1"
  ()
```

I unexpectedly get 

```
  ✅
  
  I found and typechecked the definitions in ~/proj/learnproj/unison/scratch.u. This file has been
  previously added to the codebase.
  
  Now evaluating any watch expressions (lines starting with `>`)... Ctrl+C cancels.
```

But, I expected the chance to update here.  

However, this does work as expected without the trailing `()`.

**Comment by pchiusano** [comment]
Wow, thanks for reporting. This looks like it’ll be a good one and I look forward to understanding WTH is going on. 😀

**Comment by aryairani** [comment]
A lot has changed since 2019; this works for me now, though I do need to update the type signature to
`program : '{IO, Exception} ()`, or infer it.

<img width="583" alt="image" src="https://user-images.githubusercontent.com/538571/186539156-33a8c4b1-b993-4cab-8d6b-ad3864350c42.png">
