### ISSUE TITLE
edit+slurp round-trip fails for handle blocks

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#679]
A large `handle` block that needs to split onto lines will misplace the `in` when pretty-printing in such a way that it can't be parsed again.

Example:

```
use .base

ability Default d where
  default : d

natDefault : Request (Default Nat) a -> a
natDefault = mkDefault 0

defaultPair : () -> {Default a} () -> {Default b}(a, b)
defaultPair = 'let
  defa = Default.default
  '(defa, Default.default)

mkDefault : d -> Request (Default d) a -> a
mkDefault d r = case r of 
  { Default.default -> k } -> handle mkDefault d in k d
  { a } -> a

> handle natDefault in !!handle natDefault in defaultPair

pairDefault :
  '{Default a} ('{Default b} (Request (Default (a, b)) a -> a))
pairDefault _ =
  use Default default
  defa = default
  'let
    defb = default
    r ->
      (case r of
        {default -> k} ->
          handle
            (handle mkDefault defb
              in !(handle mkDefault defa in !pairDefault))
           in k (defa, defb)
        { a } -> a)
```

The `in` is required to be further indented than `handle`, otherwise an unexpected virtual semicolon gets parsed.

Possible fixes (either):
1. Make sure virtual semicolons only get generated when there's an actual outdent (the `in` is further left than the `handle`). This might just be an off-by-one error.
2. Make sure `in` gets further indented than `handle` when pretty-printing.

**Comment by atacratic** [comment]
(added the label so I can find this again, despite the fact one of the possible fixes is not in the pretty-printer)

**Comment by pchiusano** [comment]
No longer relevant now that syntax is `handle ... with`.

Also tried this example:

```
foo a b = cases
  { a } -> a
  { abort -> _ } -> 0

ex = 
  handle 
    a = 1
    b = 2
    abort
  with
    foo 
      (1 + 1 + 292 + 39 + 1 + 38439 + 3848 + 393 + 2398982348 + 3883484 + 2828 + 28292) 
      2     
```

And it round-trips fine.
