### ISSUE TITLE
Error when adding example from getting started instructions from scratch file

### ISSUE THREAD

**Issue by rklaehn** [unisonweb/unison#680]
I am going through the examples in the getting started instructions, and am running into a problem with the first test example. I did a verbatim copy of the scratch.u from the instructions, but I get an error when the scratch file is ingested.

```
use .base

square : Nat -> Nat
square x = x * x

use test.v1

test> tests.square.ex1 = run (expect (square 4 == 16))

test> tests.square.prop1 =
  go _ = a = !nat
         b = !nat
         expect (square a * square b == square (a * b))
  runs 100 go
```

![image](https://user-images.githubusercontent.com/248257/62644293-11458d00-b94a-11e9-8dd0-d6bab515685a.png)

cd . and then pull https://github.com/unisonweb/unisonbase.git did not help...

![image](https://user-images.githubusercontent.com/248257/62644345-2cb09800-b94a-11e9-8197-48eb072fb2b2.png)

![image](https://user-images.githubusercontent.com/248257/62644356-333f0f80-b94a-11e9-9f48-90832d644774.png)

Workaround of using `use Universal` at the top of the file did work.

This was done on linux using the ucm from the tarball, but I do get the same problem on OSX as well, even after doing `brew upgrade unison-language`...

Github repo is at https://github.com/rklaehn/unison-playground/tree/0800ef8b61cad73d3c9db654e552cdf63d45cab7

**Comment by pchiusano** [comment]
@rklaehn we think this is due to having initialized your codebase with a pre-M1 version of Unison. Easiest fix is to delete your `.unison` directory and restart the instructions from the beginning. However if you've already got definitions in there that you don't want to lose, let us know and we will help you recover them / port them forward. :)
