### ISSUE TITLE
Tab completion in UCM hangs process

### ISSUE THREAD

**Issue by virusdave** [unisonweb/unison#683]
After pulling the stdlib, 
`.> find <tab>`
pressing tab without a prefix for a type seems to send `ucm` into a cpu-burning loop from which it doesn't recover.

**Comment by pchiusano** [comment]
@virusdave wow, this is a good one, thanks for reporting. 

@aryairani I'm guessing this is the same sort of bug as before? Just in the tab completion code. I tested with M1c release and it's present there.

**Comment by pchiusano** [comment]
A bit more detail: 

You need a space after the `find`, just `find<tab>` completes with `find.all`, `find.verbose` subcommands. You gotta do `find <tab>` to trigger. And for me, even providing a single character after the space causes it to work as expected. So `find t<tab>` works fine.

**Comment by aryairani** [comment]
More clues:

`find` uses `fuzzyDefinitionQueryArg`, whereas `view` (which doesn't cause a tab-completion hang) uses `exactDefinitionQueryArg`.  The two definitions are identical, apart from the call to `fuzzyComplete` vs `exactComplete`, so the problem is probably with `fuzzyComplete`.

```haskell
fuzzyDefinitionQueryArg :: ArgumentType
fuzzyDefinitionQueryArg =
  -- todo: improve this
  ArgumentType "fuzzy definition query" $
    bothCompletors (termCompletor fuzzyComplete)
                   (typeCompletor fuzzyComplete)

exactDefinitionQueryArg :: ArgumentType
exactDefinitionQueryArg =
  ArgumentType "definition query" $
    bothCompletors (termCompletor exactComplete)
                   (typeCompletor exactComplete)
```

**Comment by pchiusano** [comment]
@virusdave - Arya got to the bottom of this one. Thanks for the report!
