### ISSUE TITLE
Add/Edit roundrip drops parens from patterns

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#695]
```
use .base
use .Optional
use .Pair

foo : Optional (Pair Nat Nat) -> ()
foo x =
  case x of
    None -> ()
    Some (Pair _ _) -> ()
```

Views back as:

```
foo : Optional (Pair Nat Nat) -> ()
foo x =
  case x of
    Optional.None -> ()
    Optional.Some Pair.Pair _ _ -> ()
```

Which doesn't parse.

**Comment by zenhack** [comment]
Slight correction: It parses ok but then reports a pattern airty mismatch (because you're trying to match Some with three arguments).

**Comment by virusdave** [comment]
I ran into this several times while trying to structurally match certain types of lists: 
```
a +: (b +: rest) -> ...
```

**Comment by atacratic** [comment]
All Unison infix operators associate to the left at the moment, so you will need the parens.  But yes it's bugged that the parens are dropped by the pretty-printer.
