### ISSUE TITLE
'proxy handler' pattern doesn't work

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#697]
I was thinking about a custom handler for `IO`, to log/tweak certain requests.  Such a handler would proxy stuff over to the 'real' `IO`.  I decided first to try out the idea of proxying one handler to another of the same ability, but it didn't work.

```
use .base Request
 
ability Store v where
  get : v
  put : v -> ()

storeHandler : v -> Request (Store v) a -> a
storeHandler storedValue s = case s of 
  {Store.get -> k} ->
    handle storeHandler storedValue in k storedValue
  {Store.put v -> k} ->
    handle storeHandler v in k ()
  {a} -> a

-- this is the proxy handler
storeHandlerLog : Request (Store v) a ->{.base.io.IO, Store v} a
storeHandlerLog s = case s of 
  {Store.get -> k} ->
    printLine "get"
    storedValue = Store.get
    handle storeHandlerLog in k storedValue
  {Store.put v -> k} ->
    printLine "put"
    Store.put v
    handle storeHandlerLog in k ()
  {a} -> a

s = '(put 2)

-- works without the proxy
f = handle storeHandler 0 in s

-- doesn't compile
f' = handle storeHandler 0 in (handle storeHandlerLog in !s)
```
It all typechecks except `f'`, which gives me:
```
  The expression in red  needs these abilities: {.base.io.IO, Store v183}, but this location only has access to the {Store .base.Nat} ability,
  
     31 | f' = handle storeHandler 0 in (handle storeHandlerLog in !s)

```
(`storeHandlerLog` is in red)

(m1a)

**Comment by pchiusano** [comment]
This message could be improved but I think it is correctly an ability check failure. f’ has {} as its ambient abilities since it is a top level definition. The inner handle produces IO requests and Store requests but the outer handle block only provides the Store ability.

**Comment by atacratic** [comment]
Ah - I was missing the `'` to delay the definition of `f'`.  That must be the umpteenth time I've done that.  I'll raise a separate issue around the error message for that sort of thing.

So, some working code (with `f` also fixed to be what I meant):
``` haskell
-- inferred as s : ∀ (). () ->{Store .base.Nat} .base.Nat
 -- the weird quantification over unit is #689 
s = 'let
      Store.put 2
      Store.get

-- inferred as f : .base.Nat
f = handle storeHandler 0 in !s

-- inferred as f' : ∀ (). () ->{.base.io.IO} .base.Nat
f' = '(handle storeHandler 0 in (handle storeHandlerLog in !s))
```

**Comment by atacratic** [comment]
Oh, the error message thing is #641.
