### ISSUE TITLE
Story for documentation of Unison code

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#709]
Currently we have story for this, but a bunch of ideas.

This might be a combination of:

* New features of `ucm`
* Documenting some conventions for using existing features to document code

**Comment by pchiusano** [comment]
Okay, here is a simple proposal.

* For tutorial style documentation and overviews, use transcripts. I think we could add a few more bells and whistles to the transcript parser over time (like various kinds of "transclusion" other than using the `view` command) but it's fine for now. I think it has a nice property that it sort of teaches the command set of ucm ambiently.
* For API level documentation, we introduce a new type, `Doc` (proposal below), then use the metadata system to associate it with definitions. We then modify `ucm` (and the codebase browser) to have some special rendering for `Doc` links. So to look up docs for `List.map` you just do `links List.map Doc`. To associate docs with a definition, you say `link List.map docs.List.map`, where `docs.List.map : Doc`. Maybe we will want to split `view` command into `source` (show the source) and `display` (show some nice, human readable rendering of the source). 
* It might be cool to tweak the `find` and other commands to look for associated docs and include a summary snippet of the docs alongside the search results.
* It might also be cool to have the parser be able to produce a `Doc` using some markdown-like syntax, rather than just using existing Unison syntax to build up a `Doc` value.
* For discovery purposes,  a convention like `foo.docs` could be the docs for the namespace `foo`. It could a `URL` which points to a transcript file, or it could be a `Doc` value. 

Okay, now here's a couple proposals for a `Doc` type:

### Proposal 1, totally unstructured

```haskell
unique type Doc = Doc [Segment]
unique type Segment = Link Reference | Blob Text
```

So it's just a bunch of text that you concatenate with embedded links. Names are chosen dynamically for those references when displayed, similar to what we already do when prettyprinting code. No structure is provided. How do you get access to a term or type `Reference`? Ideas:

* New syntax, `termReference List.map` and `typeReference MyType`
* No new syntax, we just have a regular function `reference : a -> Reference`, and we autogenerate a `Reference` value for types, so if you define `type Blah = Ooo Int | Wat Nat`, that generates a term `Blah.Reference : Reference` for you.

### Proposal 2 (DRAFT), more structured

```haskell
unique type Doc = Doc [Doc.Segment]
unique type Doc.Segment 
  = Section Text Doc
  | Blob Text
  | Link Reference
  | Bulleted [Doc]
  | Numbered Nat [Doc] -- Nat is starting number
```

This is a little more structured and lets us do things like generate a table of contents automatically.

**Comment by atacratic** [comment]
Looks good! 😁 

- I'd like my `edit`/slurp workflow to show me the doc for the function I'm editing directly above the function itself, and to slurp doc edits together with function edits as part of the same scratch file save.

- Will references always be output fully qualified? Might be annoying. Maybe we can reuse FQN elision, but where would the use statements be printed?

- Any story yet for inline comments? Eg above a binding in a let block.

- I think API docs should support per-function-argument docs in a structured way.  Maybe that's just another kind of inline comment.

- What about structure around the kind of information in the text? So a specific kind of doc or link for, say, a statement about a function's computational complexity? I think that could be valuable for a nice browsing experience (fold/show the kind of info you're interested in) and also for spotting functions missing that kind of info.

- Do we really want an extra name showing up in the codebase for every API doc?

- `reference` looks a bit like the beginnings of a metaprogramming/reflection API.

- transclusion would be nice in API docs too. E.g. of terms that are good usage examples for the function. We want those examples to be compiled and tested. Generally worth keeping an eye out for common ground between docs and transcripts. Would it be good if it felt like they were written in the same format? Less to learn.

- Proposal 2, defining an ADT for ~markdown, seems a bit like hard work, but I could be wrong. Benefits of just having blobs of text that are just GFM? One thought with 2: can we evolve the format without breaking old code/docs.

**Comment by pchiusano** [comment]
Design review with @runarorama and @aryairani. Notes:

* Going to go with a variant of proposal 1, keeping these docs unstructured. We observed that it's easy enough to evolve over the `Doc` type over time.
* We are going to add a couple different kinds of transclusion, in addition to links. See `Segment` type below.
* Overall, this seems like it will be cool. Docs that link to each other via links that never break. Propagation of updates also affects docs, which is cool. The transclusion seems to open up a lot of possibilities, like writing literate Unison programs, but in a nicer way because the same definitions can be transcluded into multiple docs.
* Observation we weren't sure what to do with: there does seem to be some overlap in functionality between this and the transcript runner.

```Haskell
unique type Doc = Doc [Segment]
type Doc.Segment
  = Blob Text
  | Link Reference
  | Transclude Reference -- include a rendered version of the thing, falls back to source
  | Source Reference       -- includes the prettyprinted source of the thing
  -- later, things like: Evaluate Reference -- transclusion and show evaluated result
```

Stuff todo:

- [ ] New builtin `Reference` type, and syntax for creating `Reference` values for arbitrary terms and types. This could be its own PR.
- [ ] Define `Doc` and `Segment`, place in `IOSource` for now (and maybe rename it to something else)
- [ ] Have link renderer do something special with `Doc` values to print them nicely
- [ ] Bikeshed some syntax for `Doc` blocks, decide if we want them to be allowed in `.u` format or somehow specified elsewhere.

@atacratic good questions

> I'd like my edit/slurp workflow to show me the doc for the function I'm editing directly above the function itself, and to slurp doc edits together with function edits as part of the same scratch file save.

Could be cool, though I can also imagine times where you don't want this (if docs are long). Putting this in "cool for later" category.

> Will references always be output fully qualified? Might be annoying. Maybe we can reuse FQN elision, but where would the use statements be printed?

Yeah. Also putting in "cool for later" category.

> Any story yet for inline comments? Eg above a binding in a let block.

Right now, just strings inside the block (a dummy binding which is a string).

> I think API docs should support per-function-argument docs in a structured way. Maybe that's just another kind of inline comment.

I am not sure I agree. I often find it unnatural and boilerplate-y to specify what each argument means, rather than documenting the function more holistically. BUT, in any case, I could totally see that as a separate kind of metadata which could also be attached to definitions. Nothing stops us from adding that later!

> What about structure around the kind of information in the text? So a specific kind of doc or link for, say, a statement about a function's computational complexity? I think that could be valuable for a nice browsing experience (fold/show the kind of info you're interested in) and also for spotting functions missing that kind of info.

Again, I think textual conventions are fine for this sort of thing, but I could see having "asymptotic complexity" be a separate kind of metadata too.

> Do we really want an extra name showing up in the codebase for every API doc?

I'm okay with this, especially if you put your docs in a separate namespace.

> reference looks a bit like the beginnings of a metaprogramming/reflection API.

HMM...

> transclusion would be nice in API docs too. E.g. of terms that are good usage examples for the function. We want those examples to be compiled and tested. 

Totally, and this led to us wanting that transclusion segment types above.
