### ISSUE TITLE
source file ending in a `use` statement yields weird errors

### ISSUE THREAD

**Issue by tpolecat** [unisonweb/unison#718]
Guessing this is a duplicate, but the parser can't quite handle a source file ending with a `use` statement.

```
x = 1

use .base
```

Yields

```
  /Users/rnorris/Unison/scratch.u:1:3:
  unexpected =
      1 | x = 1
```

The actual error message depends on what comes before the `use`.

**Comment by mitchellwrosen** [comment]
It is: https://github.com/unisonweb/unison/issues/686
