### ISSUE TITLE
Usability fixes as temporary substitute for codebase browser

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#720]
Some or all of:
1. `log [branch-hash]` prints back to the last merge point?
2. `fork [branch-hash] <empty-namespace>` links an old root into the namespace?
3. `undo.preview` ?
4. Some kind of `redo`?

**Comment by aryairani** [comment]
1. and 3. are done in #732.

**Comment by pchiusano** [comment]
3. Is maybe covered by #732 - the diff between the last two hashes in the history shows what would be undone. I guess it doesn't hurt to have a separate command for it, but doesn't feel essential.

The lack of some sort of redo feels like more of a problem. Like I am scared to type `undo` - what if I undo too much?? Even though the information is still there in the codebase to be able to redo, there's no good way to access it.

**Comment by pchiusano** [comment]
Other comment is `history` command gives you more context than an `undo.preview` - it's nice to be able to scroll back and see "oh, I actually want to undo 3 steps".

**Comment by aryairani** [comment]
Good point re 3.  We should brainstorm what `redo` should / could do.
