### ISSUE TITLE
parse weirdness with layout + record syntax

### ISSUE THREAD

**Issue by tpolecat** [unisonweb/unison#739]
This yields `unexpected <virtual semicolon>`
```
type MonoidRec a = {
  combine : a -> a -> a,
  empty   : a
}
```
While adding an extra space works.
```
type MonoidRec a = {
  combine : a -> a -> a,
   empty   : a 
}
```

**Comment by pchiusano** [comment]
Thanks for this report @tpolecat 

This might be an easy one if anyone would like to take a crack at it, here's the relevant section of the file parser: https://github.com/unisonweb/unison/blob/master/parser-typechecker/src/Unison/FileParser.hs#L237-L242

I'm guessing the `sepBy1 (reserved ",")` could become `sepBy1 (reserved "," <* optional semi)`.

If this does it, you can add a `.u` file to the `unison-src/tests` directory. It will get picked up by the test suite and parsed and typechecked. I usually name the file `fix739.u` for tests like this that verify a bug is fixed.

**Comment by scott-christopher** [comment]
I've raised a PR (#748) with a fix working as suggested.
