### ISSUE TITLE
Code wrongly accepted, when using multiple args with abilities

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#745]
In the following code, `orderServer1` should fail to type check.  But it doesn't.

```haskell
use .base
use .base.io

-- bad code, wrongly accepted... the log call should be an ability check failure 
-- since it is inside the body of an arrow that only provides IO
orderServer1 : ServerConfig ->{Log} '{IO} ()
orderServer1 sc unit = 
  log (ServerConfig.toText sc)
  startServer sc

-- good code (correctly accepted) - each arrow gets its own lambda with 
-- access to the appropriate ability
orderServer2 : ServerConfig ->{Log} '{IO} ()
orderServer2 sc = 
  log (ServerConfig.toText sc)
  '(startServer sc)

-- boring stuff follows
startServer : ServerConfig ->{IO} ()
startServer sc = printLine "started, honest!"
type ServerConfig =
ServerConfig.toText : ServerConfig -> Text
ServerConfig.toText sc = ""
ability Log where
  log : .base.Text -> ()
```

From @pchiusano via slack [here](https://unisonlanguage.slack.com/archives/CLUNF0J5S/p1566135939298700): "So it seems like bug is we are “pushing” onto ambient abilities when we should be “replacing” ambient abilities. I suspect it could be a very small fix in checking / synthesis of lambdas."

**Comment by atacratic** [comment]
(issue description updated after clarification from Paul about what the desired error is)

**Comment by pchiusano** [comment]
Made some progress on this. It's due to some dubious logic in lambda checking when the lambda is multi-argument. Still working on fix though that doesn't break other stuff.
