### ISSUE TITLE
Unison starts hanging every time I save my file / Unison caches watch expressions before finding out whether they terminate

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#755]
I'm reading between the lines a bit from the behaviour I saw, so I hope the summary is in fact right.

I slurped a term a, a term b depending on a, and a watch expression for b.  b is no good - evaluation doesn't terminate.  

As soon did that slurp, I see the watch expression evaluation hanging - fair enough, I can ctrl-C out of it.  I delete the watch expression from my scratch file and start playing around with a and b.

But now every time I save, I see the hang!  Even though my scratch file isn't asking for any evaluation to happen.

I think the first slurp probably put a watch expression in the cache, but without an accompanying cached value since it never got a result from evaluation, and now every time I try to update a or b, it's trying to reevaluate it that watch expression.

Came up during a small saga as described in #753 (now closed).

Questions:
* is it right to cache watch expressions when there hasn't been an 'add'? (maybe yes)
* should watch expressions only be stored off once they've once successfully been evaluated?

**Comment by pchiusano** [comment]
@atacratic - here’s what I think is going on: 

Top level definitions are all evaluated on every save. So unless b is guarded in some way, by a lambda or a delay, it’ll keep looping on every save.

The cache is only updated once evaluation completes as you’d expect - since the cache contains the evaluated result there’s not really anything we could do to update the cache before it finishes running.

**Comment by atacratic** [comment]
I think I did a save of just a and b into a ucm running on a fresh .unison, and it didn't loop. I'll try and repro the exact steps and then post again.

**Comment by atacratic** [comment]
Well, if I did see that, I can't see it now.  What I see now matches your explanation @pchiusano.

So I think the only questionable/surprising thing is that Unison runs my code without me thinking I've asked it to.  Since I don't realise what's being run, I get confused as soon as there's a non-terminating term.  

Also what about a top-level definition that is bug free, but does some numerical heavy lifting and takes 2 minutes to complete?  Don't we want to be able to talk about terms without evaluating them?  Why not leave evaluation to watch expressions, tests and `execute`?

**Comment by ceedubs** [comment]
As far as I know this is resolved. If you don't create a watch expression for a term, it isn't evaluated. I just tried to create a watch expression for a term with infinite recursion and after I did a ctrl-c and removed the watch expression, the term no longer resulted in ucm spinning.
