### ISSUE TITLE
`ls`/`list` should be shallow and `find` should be deep

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#757]
Currently the `ls` command is an alias for `find`, but it should probably be an alias for a new command `list`, which lists only the types/terms/abilities in the current namespace, as well ast the **namespaces** under the current namespace.

- [ ] add numbered search results to LoopState appropriately (or get rid of numbers?)

**Comment by aryairani** [comment]
Recently I'd said we didn't need this now that we had #788, but it isn't the case.

**Comment by aryairani** [comment]
Implemented by #808, #819.
