### ISSUE TITLE
the source arg for `alias.term / alias.type` should allow hash-only.

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#780]
```
.> alias.type ##Sequence base.List

  HQSplit' doesn't have a hash-only option.

.> 
```

**Comment by FrankSD** [comment]
Can i  take  this   up?

**Comment by aryairani** [comment]
@FrankSD That’d be great.  Feel free to spec it out here, if you like; or just dive in.

**Comment by FrankSD** [comment]
@aryairani Can you please  guide me on where  can i  locate this  code?Sorry i am new to the codebase

**Comment by aryairani** [comment]
@FrankSD No worries, I didn't do a very thorough job of writing up the issue!  I would start start here, at the symbolic version of the commands: https://github.com/unisonweb/unison/blob/master/parser-typechecker/src/Unison/Codebase/Editor/Input.hs#L59-L60

**Comment by FrankSD** [comment]
Thanks @aryairani ..Let  me check  it out

**Comment by FrankSD** [comment]
@aryairani Can you please  enlighten me  a little  bit the big picture difference between  `HashQualified`  and `HashQualified'`.

**Comment by aryairani** [comment]
@pchiusano I took this up over the weekend because it’s blocking my simple test case creation for debugging the file copy sync.

Is there any good reason we wouldn’t want to support adding an alias for a hash that isn’t in the current namespace?

Current status: adding some logic for parsing a shorthash that includes a hash, constructorid, and length, and verifying that the hash is unique, then loading the type decl and verifying the constructor id and length

**Comment by pchiusano** [comment]
@aryairani No good reason for this limitation. I think previously the codebase didn't have a `referencesByPrefix` function so there was no way to implement resolving a short hash to the full hash, but now that it has that function, seems straightforward.

**Comment by aryairani** [comment]
@pchiusano Aha, ok, I like that explanation.
