### ISSUE TITLE
How is unison different and same as Dark?

### ISSUE THREAD

**Issue by xiaodaigh** [unisonweb/unison#783]
See https://darklang.com/

**Comment by francisdb** [comment]
unison is open source, dark is private

**Comment by xiaodaigh** [comment]
but otherwise the same?

**Comment by francisdb** [comment]
I have requested access to the alpha but so far no response

We'll have to wait for some more topics to be available at
https://medium.com/darklang/the-design-of-dark-59f5d38e52d2

Both share the idea that text to define programming languages is sub-optimal
Both share the idea that deployment should be simple

Darklang seems to be at a further stage in development regarding cloud deployment and structured editor

> Dark has a deliberately small compilation unit (the amount of code which is compiled together, and therefore which must be type checked together). You can make changes in a single HTTP route without having to make it type check with the rest of your program. This lowers the amount of type changes that you need to make to test out a single change.

From this I guess they are focusing more on the function as a service ecosystem with http as main driver. I wonder what the thoughts are on the unison side. More like a distributed actor system? @pchiusano @runarorama 

Also for me Darklang feels a bit less academic

**Comment by pchiusano** [comment]
Dark seems like a cool project and I'm looking forward to trying it out once it's released. :)

There's some more discussion happening over at [this reddit thread](https://www.reddit.com/r/ProgrammingLanguages/comments/d24dad/dark_vs_unison/) (see [Arya's reply](https://www.reddit.com/r/ProgrammingLanguages/comments/d24dad/dark_vs_unison/ezt8kr1/) there) and I kind of think reddit is a better forum for this kind of discussion anyway.

I'm going to close this issue but thanks for your interest. Cheers!
