### ISSUE TITLE
Can't move an infix term

### ISSUE THREAD

**Issue by stacycurl** [unisonweb/unison#800]
```
.> move.term base.Text.++ ++

  InvalidWordyId ""
```

**Comment by aryairani** [comment]
Oof, sorry about this @stacycurl, and thanks for reporting.  That said, I’m going to close it as a duplicate of #763, which we should make a priority.

**Comment by stacycurl** [comment]
Oops, sorry, I looked for an existing bug, but I must have missed it.

**Comment by aryairani** [comment]
@stacycurl No worries, thanks for reporting.
