### ISSUE TITLE
Running `ucm --version` initializes a codebase

### ISSUE THREAD

**Issue by jackjennings** [unisonweb/unison#805]
After installing `unison`, I immediately ran `ucm --version` to check that installation had succeeded correctly (force of habit). This unexpectedly created a new codebase in the directory I was in.

Output:

```
  ☝️

  No codebase exists here so I'm initializing one in: .unison/v1
ucm version: release/M1d
```

I would expect to only return the version and the exit.

**Comment by aryairani** [comment]
Oops, thanks for reporting this.
