### ISSUE TITLE
Unison accepts a type constructor passed too many parameters

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#815]
Unison accepts the following bad code:
```haskell
ability Do where
  do : ()

ability Remote where
  at : '{forall t . Do t} a -> ()
```
Note how in the signature of `at`, `Do` is passed a type parameter, when it doesn't actually take one.

(master@0d031ff)

**Comment by pchiusano** [comment]
This is another bug due to lack of kind checking. Should probably close as a dupe of that ticket, if you can locate it.

**Comment by atacratic** [comment]
Ah yes!  Missed that one.  Closing as dup of #567
