### ISSUE TITLE
add codebase_path arg to ucm

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#817]
Default to user-specific path for the platform, eg `~/.unison` for posix; whatever is normal for windows (guessing the same, but maybe not).

**Comment by aryairani** [comment]
cc @francisdb

**Comment by francisdb** [comment]
@aryairani would that [shebang](https://github.com/unisonweb/unison/pull/816#issuecomment-534698838) use case then be possible?

**Comment by aryairani** [comment]
@francisdb Sorry, I misunderstood the conversation in the other thread.  I think
```sh
#!/bin/sh
ucm -execute .foo.bar.main
```
is probably a simpler version of what you want?

**Comment by francisdb** [comment]
But then as I understood that is not possible without creating a scratch file first that points to that main?
See https://github.com/unisonweb/unison/pull/816#issuecomment-534696649
