### ISSUE TITLE
pretty-printing glitch in wrapColumn2?

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#820]
![image](https://user-images.githubusercontent.com/538571/65640268-f4c3e980-dfb7-11e9-9899-4e2016877328.png)

I believe this 👇 should produce 3 lines of output, but it only produces 2? ☝️ 
```
  (P.wrapColumn2
    [ ("`list`", "lists definitions and namespaces at the current level of the current namespace.")
    , ( "`list foo`", "lists the 'foo' namespace." )
    , ( "`list .foo`", "lists the '.foo' namespace." )
    ]
  )
```

Change my mind! :)

**Comment by pchiusano** [comment]
Definitely seems like a bug
