### ISSUE TITLE
add namespace hash completion to Codebase interface

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#842]
In order to avoid rendering and typing 512-bit hashes for namespace-manipulation functions (`fork`, `merge`, `reflog`, `history`), it would be nice to be able to use a unique hash prefix instead.  (Similar to `ShortHash` for Unison references.)

To support this, let's add these methods to `Unison.Codebase`:
```haskell
branchHashesByPrefix :: Text -> m (Set Branch.Hash)
```
which takes a base32hex string and returns the set of known branches matching that prefix.  Passing `mempty` should return all of the branches in the codebase.  In the implementation of `FileCodebase`, the branches are currently stored as `<base32hex>.ub` within `FileCodebase.branchesDir`, so you can probably do some file globbing thing.

and
```haskell
branchHashLength :: m Int
```
which can initially be set to always return 7 or 10 or something, or else the full implementation per #843

**Comment by pchiusano** [comment]
implemented in a2349247a8f5443890fde65348d8e607d945b495
