### ISSUE TITLE
simple watch expressions are broken

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#849]
Per https://unisonlanguage.slack.com/archives/CLUNF0J5S/p1570339673426300, watch expressions seem to be broken:
```haskell
x = 2
> x
```
```
.> 

  I found and typechecked these definitions in ~/unison/u.u. If you do an `add` or `update`, here's
  how your codebase would change:
  
    ⍟ These new definitions are ok to `add`:
    
      x : builtin.Nat
   
  Now evaluating any watch expressions (lines starting with `>`)... Ctrl+C cancels.

.> 
```

I'm running a `git bisect` now.  /cc @sullyj3

**Comment by aryairani** [comment]
```
24bb79fe91905769a16883d9d3d8b63c3dcb5c4b is the first bad commit
commit 24bb79fe91905769a16883d9d3d8b63c3dcb5c4b
Author: Paul Chiusano <paul.chiusano@gmail.com>
Date:   Mon Sep 23 21:47:12 2019 -0400

    rejigger execute command to allow running main in latest file

```
/cc @pchiusano

**Comment by pchiusano** [comment]
https://github.com/unisonweb/unison/commit/24bb79fe91905769a16883d9d3d8b63c3dcb5c4b#r35380780

**Comment by pchiusano** [comment]
Confirmed that the `when` I linked to above is responsible (commenting it out causes watches to show up again), now trying to figure out right fix.

**Comment by pchiusano** [comment]
Okay pushed a fix, also added a transcript "test". It's not exactly a test, but it confirms that the output has that watch expression result, and if the output ever changes it's pretty likely that we will notice (you run `stack exec transcripts` locally, notice that the transcript output differs, and make sure you the transcript output is still sane before you commit the updated transcript).

This fix revealed that we were missing a line break after the "typechecked" message, leading the first watch expression to show up on the same line as the "typechecked" message in the transcript output. I fixed just by having the transcript output use the same padded output as the console printer. I'd like to strip the leading and trailing blank lines at some point, and maybe also unindent ucm output which is just one message, but not a big deal and we can address that later.
