### ISSUE TITLE
Character literal syntax isn't documented anywhere

### ISSUE THREAD

**Issue by isovector** [unisonweb/unison#851]
The [Literals](https://www.unisonweb.org/docs/language-reference/literals/) page doesn't make any reference to the `?x` syntax for character literals.

**Comment by aryairani** [comment]
Thanks for creating this ticket.

But yeah I think character literals weren't merged at the time that the Literals page was written, and I also kind of want to change the syntax, but haven't.  I suppose the doc page should be current even if we want it to change though?

https://github.com/unisonweb/unisonweb-org/blob/master/src/data/docs/language-reference/literals.md if anyone wants to take a stab at it.
