### ISSUE TITLE
publish nightly ucm packages

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#877]
Currently ucm releases are created through an Azure pipeline according to `https://github.com/unisonweb/unison/blob/series/M1/azure-pipelines.yml`.  First, the `multi_build` job builds the binaries, and tgz's them into `$(archiveFile)`;  then the `github_release` job attaches the tgz files to a Github release; then the `homebrew_template` job creates an updated homebrew formula `unison-language.rb` and commits it to the `unisonweb/homebrew-unison` repo.

Currently, `azure-pipelines.yml` only exists in the `series/M1`, it would need to be in `master` for Azure to pick it up on pushes to `master`. 

We don't want a Github release for nightly builds, so the binaries need to be hosted some other way.  Maybe in a Github repo of their own?  That's probably a lot less psychologically dangerous than the all-Azure approach I had been attempting.

P.S. I think they can be built on every merge to master; doesn't have to be nightly.

P.P.S. We don't have to use Azure pipelines forever.

**Comment by aryairani** [comment]
It [looks like](https://github.com/rust-lang/rust/blob/master/src/ci/azure-pipelines/steps/run.yml) the rust-lang folks upload CD artifacts to an S3 bucket.

**Comment by ceedubs** [comment]
I'm going to go ahead and close this out. The developer build/release happens on every merge to `trunk`. Right now the homebrew formula only is updated for releases, but that seems like pretty reasonable behavior to me. If we want the homebrew formula to update for every merge to `trunk` then we can open a separate issue for that.
