### ISSUE TITLE
Coverage checking for pattern matching

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#913]
(@augustss if you are seeing this - we are adding pattern coverage checking to Unison and could use a good reference on how to implement for a language without GADTs)

Right now, you can have incomplete pattern matches and it will compile without even a warning. This should be a compile error that reports which patterns aren't covered by the cases. It should also report redundant patterns, like if you have `4 -> "hi"` after a `x -> "bye"` case.

(If you have a set of patterns which you think are complete, you can explicitly crash using a wildcard pattern that calls the new `error` / `bug` function in #881, which we are still doing some bikeshedding on)

I imagine adding a function like this to the typechecker, and then calling it after typechecking a case expression somewhere [here in Context.hs](https://github.com/unisonweb/unison/blob/master/parser-typechecker/src/Unison/Typechecker/Context.hs#L850-L860):

```Haskell
-- for a given type and a list of patterns at some location, verify that the patterns cover that type, are not redundant, and fail otherwise
verifyCoverage :: loc -> [Pattern loc] -> Type v a -> M v loc ()
```

And then add a new kind of type error in `Context.hs` for if pattern matching is incomplete (maybe a separate error if it's redundant).

Guards should ultimately be incorporated into this check as well, though the logic for guards can be really straightforward / conservative. 

Here are some pointers: 

* https://stackoverflow.com/questions/7883023/algorithm-for-type-checking-ml-like-pattern-matching gives a basic overview.
* Page 17 of [this paper](https://arxiv.org/pdf/1601.05106.pdf) also has an algorithm, but that is for a type system with GADTs so I'm guessing that will be more complicated than necessary.

@TomasMikula given that you're getting pretty familiar with the typechecker I thought you might like to have a go at this one. :)

Also, @mrdziuban I know we have talked about this one and if you're still interested in helping out with this let us know!

**Comment by TomasMikula** [comment]
Thanks for the mention @pchiusano! This is definitely something I would like to work on. I have a few other tweaks in the making, so I don't want to call dibs on this one just yet. :)

**Comment by noahhaasis** [comment]
Unfortunately, I currently don't have the time to write a coverage checker but I've found some hopefully helpful resources.
This is a paper about implementing coverage and redundancy checking for pattern matching in ML-like languages:
http://moscova.inria.fr/~maranget/papers/warn/warn.pdf
It's also what Elm uses.
https://github.com/elm/compiler/blob/master/compiler/src/Nitpick/PatternMatches.hs

**Comment by aryairani** [comment]
keyword exhaustiveness

**Comment by pchiusano** [comment]
Looks like a good reference: https://www.reddit.com/r/haskell/comments/gst4il/lower_your_guards_a_compositional_patternmatch/

**Comment by pchiusano** [comment]
@aryairani noted on https://github.com/unisonweb/unison/pull/1700#issuecomment-700190633 that we might want to use abilities to track incomplete pattern matches. Some ideas:

* We have a type that's isomorphic to `Abort` or `Exception` which becomes part of the type automatically if you don't fully match the pattern.
* You just get a type error if you don't have full coverage.
* Maybe some syntax for indicating that you're okay with an incomplete match and what to do with the `Abort` if it's hit.

**Comment by sullyj3** [comment]
This is cool, like a better version of MonadFail that's applicable to all pattern matches, rather than just the ones in do blocks.
