### ISSUE TITLE
Read the `.unisonConfig` file from wherever the codebase is.

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#917]
Right now `.unisonConfig` is read from the working directory (wherever `ucm` is launched). It makes more sense for it to be read from wherever the codebase is. So for example if you start `ucm` with no arguments, the codebase is in the user's home directory. The `.unisonConfig` file should be read from there as well.

**Comment by mitchellwrosen** [comment]
Suggestion: monoidally combine them, with local `.unisonConfig` overriding home `.unisonConfig` when there's no way to combine
