### ISSUE TITLE
Fail if a pending test actually passes

### ISSUE THREAD

**Issue by TomasMikula** [unisonweb/unison#928]
E.g.

```haskell
pending ok
```

would be a failing test.

### Motivation:
1. When a PR is opened that adds a pending test, then a passing CI build will be sufficient evidence that the added test is actually failing.
2. If a previously failing test becomes passing incidentally as a side-effect of some change, it will let the author know that the test is now passing.

**Comment by aryairani** [comment]
I would also like this feature.
