### ISSUE TITLE
a pushed namespace may be missing dependencies / dependency names unknown at receiver

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#929]
Option 1: just copy dependencies on push / pull, may be missing names
Option 2: copy dependency names on push into `_deps` namespace
  - `_deps` probably should be some name that "looks" reserved, like `_deps`.
  -  and deprioritize these `_deps` names during view so that some more maintained pull of them is shown instead whenever available (filter these out before pretty printing)
  * we might warn the user that we're going to push definitions with missing dependency names, but that is the common case (e.g. depending on `.base` and no we don't want to special-case it)

Other ideas for how to prioritize name selection
* prioritize according to graph distance from the definition(s) being displayed
* deprioritize for one-offs like `_deps` or `_startsWithUnderscore`
* "priority" metadata on namespace
* prioritize names that have metadata indicating current user had some hand in selecting them
* on a per-namespace basis, give a list of priority namespaces

**Comment by atacratic** [comment]
Worth noting that in the story for PRs in #867, there are lots of copies of names being pulled in to namespaces like `.pulls.base.contributor1.topic`.  So maybe not enough to deprioritize just based on `_` or `_deps`.  

Another variation:
- each name has an 'am I a copy' metadata flag, and non-copies are prioritized
- the user can configure a list of namespaces acting as a priority order for name selection.

**Comment by aryairani** [comment]
Yeah, I'm thinking we should have some heuristic (e.g. something based on the relationship between the current path, the definition being viewed, and the available dependency names) and some optional configuration.

**Comment by aryairani** [comment]
We could have an optional arg that tells ucm how to copy in external dependency names; e.g. "copy everything in <specified namespace> into `dependencies`".  When the provided namespace is omitted or not inclusive enough, we could compute and propose a nearest common ancestor for the user.
