### ISSUE TITLE
include patches diffs when showing branch diffs

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#965]
Relates to `PreviewMergeLocalBranchI` and `CreatePullRequest` and `ShowDiff` and #867.

Currently, diffs are displayed with `ShowDiff`, which only considers Names.
___
Alternatively: we could make patches into terms.  The codebase could be updated in-place to copy existing patches to terms whenever `deepEdits /= null`, and ignore the current `patches` field; however, prior builds of ucm wouldn't find the new/migrated patches.

**Comment by pchiusano** [comment]
Superceded by #982
