### ISSUE TITLE
let the default `ucm transcript` behavior delete a codebase that the transcript runner created

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#975]
The resulting transcript `.output.md` would still be preserved, and the resulting codebase should be preserved with a flag, e.g. `-preserve`.

Rationale: Since transcript running so far is just for running tests or generating `.output.md`, the resulting codebases are uninteresting accumulated garbage.

See: `Main.runTranscripts`

**Comment by aryairani** [comment]
Just spent over 10 minutes trying to clone my unison dev working directory before cancelling; it was partially due to many test-output subdirs.

**Comment by pete-ts** [comment]
Quick question, are you envisioning the default behaviour to delete the temporary folder for both `transcript` and `transcript.fork`?

**Comment by pete-ts** [comment]
Further question: if a transcript is syntactically correct, but causes an error, like calling an invalid ucm command for example:
```
🛑

Transcript failed due to the message above.
Codebase as of the point of failure is in
```
should the preserve flag affect the cleanup of the temporary dir?

**Comment by aryairani** [comment]
I think this is done?
