### ISSUE TITLE
Minimize term cycles before hashing

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#987]
Thanks to @isovector for surfacing this, he was asking if there were any cases where hash based cycle normalization can cause definitions with different effect orders to hash the same. I replied:

> let rec blocks are not allowed to use abilities (the bindings in the block may be functions that use abilities when called, but that is different), and same goes for top level definitions, precisely because it’s a can of worms re: ordering of effects. So you shouldn’t be able to construct a typechecking Unison program where the cycle order normalization leads two semantically different programs to hash the same.

> That said, while looking at this to verify I noticed that we are failing to do cycle minimization before hashing, which is a bug that makes your concern still valid. :upside_down_face:  I’ll create an issue to track

Fix is either:

* Modify the term hashing to have a call to cycle minimization before doing the hashing.
* Modify the term parser to do cycle minimization upon parsing the term (not sure this will work - could this depend on name resolution which isn't done until after parsing?)
  * If we go this route, we should make sure prettyprinter does fine with nested let / let rec blocks.

For those curious, cycle minimization is converting one big `let rec` block to nested `let` / `let rec` blocks. [Here is the current implementation](https://github.com/unisonweb/unison/blob/master/parser-typechecker/src/Unison/Typechecker/Components.hs#L19).

**Comment by TomasMikula** [comment]
Could you maybe illustrate the problem on an example?

If the concern is

> if there were any cases where hash based cycle normalization can cause definitions with different effect orders to hash the same

then

> failing to do cycle minimization before hashing

seems to me like a different problem, namely two semantically equal programs to hash differently, which is not really a problem.

**Comment by pchiusano** [comment]
An example of a problem would be like:

```Haskell
spaceAttack1 x = 
  y = IO.launchMissiles saturn
  z = IO.launchMissiles neptune
  "All done"

spaceAttack2 x = 
  z = IO.launchMissiles neptune
  y = IO.launchMissiles saturn
  "All done"
```

These should hash differently since they do things in a different order. But with current Unison they will hash the same because they are both parsed as a `let rec` whose binding order gets normalized by the hashing algorithm. The way this would show up to users is that user would try to add `spaceAttack2` only to be told (incorrectly) that it was just an alias for `spaceAttack1`.

The fix I implemented is to have them parse as a nested `let` - that is, I am doing cycle minimization during parsing. I don't think it's correct to modify the hashing of terms, as that would break the property that you can read a term, rehash it, and get back the same hash.

**Comment by TomasMikula** [comment]
Thanks for the explanation, @pchiusano. So what will the fixed version do on

```haskell
spaceAttack x = 
  y = IO.launchMissiles z saturn -- notice dependency on z, which comes later
  z = IO.launchMissiles x neptune
  "All done"
```
?

**Comment by pchiusano** [comment]
@TomasMikula mm good question. It reorders them, basically as if you wrote:

```haskell
spaceAttack x = 
  z = IO.launchMissiles x neptune
  y = IO.launchMissiles z saturn -- notice dependency on z, which comes later
  "All done"
```

... which I don't like. In this particular case it's not terrible because it's preserving evaluation order, you can't evaluate `IO.launchMissiles z` without first evaluating `z`. But it would also reorder if you wrote `someFunction 'z x saturn` which may actually change order of effects, which is no good.

So I think the cycle minimization done by the parser should work a bit differently - it should preserve the order of any unguarded bindings the user typed, and just focus on inserting minimal let/let rec. In this case, I'd like it to produce a `let rec` block to cover the forward reference (and then that will result in a type error since `let rec` blocks don't have access to any abilities).

**Comment by TomasMikula** [comment]
I'm not sure what "unguarded" means and how the parser can tell what is unguarded.

If function definition or a lambda is guarded and everything else is unguarded, i.e.

```haskell
  f a = a + a      -- guarded
  g = λ a -> a + a -- guarded
  h = g            -- unguarded
```
then guardedness does not seem like the right criterion for whether something can be reordered.

FWIW, I think things would be clearer for Unison _users_ if effectful assignments had different syntax from pure bindings, e.g.

```haskell
spaceAttack x =
  y = x * x                        -- pure
  z := IO.launchMissiles y neptune -- effectful, notice the :=
  "All done"
```

And surely this would simplify implementation, since already the parser could tell what is pure and what is effectful, and thus what can be reordered and what can't.

**Comment by pchiusano** [comment]
Unguarded just means the body of the binding is not a lambda. Lambdas are safe to reorder (other definitions may be safe to reorder if they are pure, but parser doesn’t know that for sure).

Also FYI there is no distinction between f x = ... and f = x -> ...

**Comment by TomasMikula** [comment]
If I understand the proposed fix correctly, I'm afraid it could lead to surprising behavior. Consider

```haskell
f = λ a -> a +1
z =
  x = f 5 -- refers to the f below
  f a = a * a
  x
```

and

```haskell
f = λ a -> a +1
z =
  x = f 5 -- refers to the f **above**
  y = 7   -- added this line (unused)
  f a = a * a
  x
```

Adding an unguarded assignment changed lexical scoping. Or did I misunderstand something?

**Comment by pchiusano** [comment]
@TomasMikula I decided not to do any reordering for non top-level blocks. Even though it's safe to rearrange lambdas I think it's better to preserve the source order of the definitions.

Regardless of the reordering, both those `f` references will be to the one in the same block, not the outer block - names in the current block shadow names from outer blocks. Similar to Haskell, there is no syntax for referring to an outer variable which has been shadowed locally - just name your inner variables something else if you don't want the shadowing.

**Comment by TomasMikula** [comment]
@pchiusano You mean the order of bindings is no longer normalized by the hashing algorithm?

The reason I thought it would refer to the outer `f` was that I assumed the block would be parsed into nested `let`/`let rec`, where the latter `f` below would be in a nested block, something like

```haskell
f = λ a -> a +1
z =
  let
    x = f 5 -- refers to the f **above**
  in
    let rec -- nested let rec, prompted by the unguarded assignment `y = 7`
      y = 7
      f a = a * a
    in x
```

but I probably misunderstood your intention.

**Comment by pchiusano** [comment]
@TomasMikula binding order is still normalized within a cycle. It's just cycles are being computed differentl in a way that preserves the order of the bindings if all the cycles were flattened. I'll point out the algorithm in the PR once it is ready for review. :)
